**labels of common vars
capture label var date "Time"
capture label var unit "Unit of measure"
capture label var geo "Geopolitical entity (reporting)"
capture label var partner "Geopolitical entity (partner)"
capture label var nace_r2 "NACE Rev. 2"
capture label var s_adj "Seasonal adjustment"
capture label var p_adj "Price adjustment"
capture label var sizeclas "Size classes in number of employees"
capture label var currency "Currency"
capture label var sector "Sector"
capture label var direct "Direction of flow"
capture label var itm_newa "List of products - EAA"
capture label var year "Year"
capture label var freq "Time frequency"
capture label var stk_flow "Stock or flow"
capture label var reporting "Geopolitical entity"
capture label var sector10 "Sector (ESA 2010)"
capture label var sectpart "Sector (ESA 2010)"
capture label var legtype "Legal type of the holding"
capture label var agrarea "Agricultural area"
capture label var so_eur "Standard output in Euros"
capture label var farmtype "Farm type"
capture label var croparea "Area under corresponding crop"
capture label var irrig "Irrigated area"
capture label var lsu "Livestock units (LSU) size classes"
capture label var snglhldr "Legal form: Single holder"
capture label var esu "Economic size classes of holdings in European Size Unit"
capture label var organic "Organic farming"
capture label var sex "Sex"
capture label var dairyprod "Dairy and other animal products (except meat)"
capture label var strucpro "Structure of production"
capture label var hatchitm "Activity of hatcheries"
capture label var sizehatch "Capacity of the hatchery in number of eggs"
capture label var typ_rear "Type of rearing"
capture label var prodmilk "Milk product"
capture label var volume "Volume"
capture label var meat "Meat product"
capture label var typ_rear "Type of rearing"
capture label var n_head "Number of heads"
capture label var airp_pr "Airport pairs (routes)"
capture label var indic_sb "Economical indicator for structural business statistics"
capture label var nace_r1 "NACE Rev. 1.1"
capture label var entity  "Entity"
capture label var fdi_item "FDI item"
capture label var indic_bp "Balance of payments indicator"
capture label var post "Item of the balance of payments"
capture label var clspec "Client specialisation"
capture label var enterpr "Enterprise"
capture label var barrier "Barriers"
capture label var cbtrade "Cross border trade"
capture label var lev_impt "Level of importance"
capture label var media "Media"
capture label var size_emp "Size classes in number of persons employed"
capture label var cltype "Client/Trader"
capture label var resid "Place of residence"
capture label var cpa08 "Statistical Classification of Products by Activity 2008"
capture label var cpa2_1 "Statistical Classification of Products by Activity (CPA 2.1)"
capture label var lev_impt "Level of importance"
capture label var wst_oper "Waste management operations"
capture label var waste "Waste categories"
capture label var rawmat "Raw materials"
capture label var indic_env "Environment indicator"
capture label var cpatc "Cooperative patent classification"
capture label var age "Age class"
capture label var isced97 "International Standard Classification of Education (ISCED 1997)"
capture label var isco08 "International Standard Classification of Occupations 2008 (ISCO-08)"
capture label var y_birth "Year of birth"
capture label var n_activ "Number of active persons"
capture label var n_person "Number of persons"
capture label var n_unemp "Number of unemployed persons"
capture label var n_child "Number of children"
capture label var y_const "Year of construction"
capture label var amenity "Amenities"
capture label var indic_co "Cooperation statistics indicators"
capture label var source "Data source"
capture label var leg_stat "Legal status"
capture label var iccs "International classification of crime for statistical purposes (ICCS)"
capture label var ind_type "Individual type"
capture label var cities "Geopolitical entity (declaring)"
capture label var leg_case "Legal case"
capture label var prod_ct "Cultural products"
capture label var frequenc "Frequency"
capture label var coicop "Classification of individual consumption by purpose (COICOP)"
capture label var acl00 "Classification of activities for time use"
capture label var n_book "Number of books"
capture label var indic_em "Employment indicator"
capture label var isced11 "International Standard Classification of Education (ISCED 2011)"
capture label var indic_de "Demographic indicator"
capture label var ord_brth "Birth order"
capture label var month "Month"
capture label var agedef "Age definition"
capture label var weight "Weight"
capture label var duration "Duration"
capture label var isced11f "International Standard Classification of Education (ISCED 2011)"
capture label var marsta "Marital status
capture label var marsta2 "Marital status (of bride)"
capture label var area "Area"
capture label var cpa02 "Statistical Classification of Products by Activity, 2002"
capture label var worktime "Working time"
capture label var owner "Type of ownership"
capture label var indic_se "Structure of earnings indicator"
capture label var ecase "Earnings case"
capture label var estruct "Earnings structure"
capture label var cpayagr "Collective pay agreement"
capture label var l_serv "Length of service"
capture label var emp_cont "Type of employment contract"
capture label var quantile "Quantile"
capture label var isco88 "International Standard Classification of Occupations (ISCO-88 (COM))"
capture label var n_lang "Number of foreign languages"
capture label var deg_urb "Degree of urbanisation"
capture label var lev_know "Level of knowledge"
capture label var wstatus "Activity and employment status"
capture label var training "Training"
capture label var indic_ed "Education indicator"
capture label var workstud "Work experience during studies"
capture label var field "Education or training field"
capture label var studentc "Student category"
capture label var language "Language"
capture label var iscedf13 "ISCED Fields of education and training (ISCED-F 2013)"
capture label var sector2 "Counterpart sector"
capture label var expend "Expenditure and investment"
capture label var mobscheme "Mobility scheme"
capture label var mobility "Mobility"
capture label var arable "Arable land area"
capture label var landcover "Land cover"
capture label var hold_man "Legal form and holder-manager relationship"
capture label var crop_rot "Share of arable land with crop rotation"
capture label var tillage "Tillage of arable land"
capture label var soil_cov "Soil cover of arable land"
capture label var indic_agr "Agricultural indicators"
capture label var oga_hld "Other gainful activity of the holder"
capture label var oga_spou "Other gainful activity of the spouse"
capture label var ruraldev "Rural development"
capture label var terrtypo "Territorial typology"
capture label var obzone "Objective zones (CAP)"
capture label var bop_item "BOP_item"
capture label var sitc06 "Standard International Trade Classification (SITC Rev. 4, 2006)"
capture label var maturity "Maturity"
capture label var int_rt "Interest rate"
capture label var indic_is "Information society indicator"
capture label var hazard "Hazard class"
capture label var ww_tp "Wastewater treatment plants"
capture label var vessel "Type of vessel"
capture label var nrg_bal "Energy balance"
capture label var vehicle "Vehicles"
capture label var accommod "Mode of accommodation"
capture label var c_resid "Country of residence"
capture label var airpol "Air pollutants and greenhouse gases"
capture label var material "Materials"
capture label var ceparema "Classifications of environmental activities: (CEPA) and (CReMA)"
capture label var ty "Type of expenditure"
capture label var env_econ "Environmental economic characteristics"
capture label var env_exp "Expenditure"
capture label var induse "Industries, categories of final uses and imports"
capture label var origin "Place of origin"
capture label var indic_pefa "Physical energy flow accounts indicators"
capture label var prod_nrg "Energy product"
capture label var tax "Taxes"
capture label var airpol "Air pollutants and greenhouse gases"
capture label var src_nfr "Source sectors for emissions of air pollutants (CLRTAP)"
capture label var statinfo "Statistical information"
capture label var thickness "Thickness"
capture label var wat_src "Water sources"
capture label var rbd "River basin districts (RBD) and sub-units (SU)"
capture label var wat_proc "Water process"
capture label var substance "Substances"
capture label var ww_gtd "Wastewater generation, treatment and discharge"
capture label var ww_tpar "Wastewater treatment plant parameters"
capture label var exch_rt "Exchange rate"
capture label var indic_et "External trade indicator"
capture label var bec_r5 "Broad economic categories (BEC Rev.5)"
capture label var ebops2010 "Extended Balance of Payments Services Classification 2010 (EBOPS 2010)"
capture label var bclas_bec "Basic classes of goods in the System of National Accounts (SNA) in terms of Broad Economic Categories (BEC)"
capture label var ranking "Ranking"
capture label var n_partner "Number of partners"
capture label var operator "Operator/Trader"
capture label var percent "Size classes in percentage"
capture label var c_ctrl "Country, in which the controlling enterprise is located"
capture label var aquameth "Aquaculture method"
capture label var aquaenv "Aquatic environment"
capture label var fishreg "Fishing regions"
capture label var species "Species"
capture label var dest_use "Fish destination and use"
capture label var length "Length"
capture label var eng_pow "Engine power"
capture label var gear "Fishing gears"
capture label var natvessr "Nationality of registration of vessel"
capture label var pres "Presentation form"
capture label var indic_fb "Indicator on factors of business success"
capture label var expernce "Experience"
capture label var sizeclas "Size classes in number of employees"
capture label var indic_fo "Forestry indicators"
capture label var treespec "Tree species"
capture label var prod_wd "Wood products"
capture label var for_acc "Forestry economic accounts"
capture label var prod_wd "Wood products"
capture label var bark "Under bark / over bark"
capture label var fund "Type of funding"
capture label var cofog99 "Classification of the functions of government (COFOG 1999)"
capture label var co_nco "Consolidated/Non consolidated"
capture label var sector2 "Counterpart sector"
capture label var finpos "Financial position"
capture label var na_item "National accounts indicator (ESA 2010)"
capture label var hhcaract "Household characteristics"
capture label var incsrc "Main source of income"
capture label var hhtyp "Type of household"
capture label var icd10 "International Statistical Classification of Diseases and Related Health Problems (ICD-10 2010)"
capture label var agechild "Age of the child"
capture label var mortalit "Type of mortality"
capture label var parity "Number of children previously born to a woman"
capture label var indic_he "Health indicator"
capture label var icha_hc "Health care functions SHA"
capture label var facility "Health facility"
capture label var icd9cm "International Classification of Diseases (Medical procedures)"
capture label var levels "Level"
capture label var yes_no "Survey answer - Yes/No"
capture label var hp_cause "Cause of health problem or disability"
capture label var hlth_pb "Health problems"
capture label var lev_limit "Level of activity limitation"
capture label var bmi "Body Mass Index"
capture label var incgrp "Income situation in relation to the risk of poverty threshold"
capture label var assist "Assistance"
capture label var accident "Accident"
capture label var hlthcare "Health care"
capture label var quant_inc "Income quantile"
capture label var n_contact "Number of contacts"
capture label var lev_diff "Level of difficulty"
capture label var smoking "Smoking behaviour"
capture label var n_portion "Number of portions"
capture label var frequenc "Frequency"
capture label var lev_perc "Level of perception"
capture label var physact "Specific physical activity"
capture label var med_spec "Medical speciality"
capture label var icha11_fs "Classification of revenues of health care financing schemes - SHA 2011"
capture label var icha11_hc "Classification of health care functions - SHA 2011"
capture label var icha11_hp "Classification of health care providers - SHA 2011"
capture label var icha11_hf "Classification of health care financing schemes - SHA 2011"
capture label var c_birth "Country/region of birth"
capture label var citizen "Country of citizenship"
capture label var n_injury "Number of accidental injuries"
capture label var category "Category"
capture label var sizes "Size"
capture label var severity "Severity (days lost)"
capture label var modinj "Contact - mode of injury"
capture label var deviatn "Deviation"
capture label var matagent "Material agent"
capture label var injury "Type of injury"
capture label var wrkenv "Working environment"
capture label var workproc "Working process"
capture label var wrkstat "Workstation"
capture label var factor "Factors"
capture label var diagnose "Diagnosis"
capture label var n_hprob "Number of health problems"
capture label var n_job "Number of jobs"
capture label var wsta_acc "Working status after the accident"
capture label var bodypart "Part of body injured"
capture label var indic_in "Innovation indicator"
capture label var prof_pos "Professional position"
capture label var income "Income group"
capture label var lev_depr "Level of deprivation"
capture label var lev_expn "Level of expenditure"
capture label var yn_rskpov "At risk of poverty - Yes/No"
capture label var workint "Work intensity"
capture label var yn_rskpov "At risk of poverty - Yes/No"
capture label var duration "Duration"
capture label var indic_il "Income and living conditions indicator"
capture label var quant_expn "Expenditure quantile"
capture label var quant_wlth "Wealth quantile"
capture label var contrib "Contributor"
capture label var cost "Costs"
capture label var reason "Reason"
capture label var carestat "Care status"
capture label var subjnmon "Subjective and non-monetary indicator"
capture label var trans1y "Transition from the previous year situation"
capture label var trans2y "Transition within two years"
capture label var trans3y "Transition within three years"
capture label var lev_satis "Level of satisfaction"
capture label var trans1g "Transitions from previous generation"
capture label var building "Type of building"
capture label var tenure "Tenure status"
capture label var n_item "Number of items"
capture label var afford "Affordability"
capture label var indic_wb "Personnal well-being indicators"
capture label var enterpr "Enterprise"
capture label var entgrp "Enterprise group identification"
capture label var coop_ptn "Cooperation partners"
capture label var inn_act "Innovation activities"
capture label var ipr_trn "Transaction and type of Intellectual Property Rights (IPRs)""
capture label var effect "Effects"
capture label var subj_regl "Subject of the regulation/legislation"
capture label var innovat "Type of innovation"
capture label var mktplace "Market place"
capture label var n_design "Number of designs in application"
capture label var src_fund "Source of funding"
capture label var src_info "Source of information"
capture label var inn_act "Innovation activities"
capture label var src_act "Sourcing activity"
capture label var bsn_strat "Business strategy"
capture label var locpart "Location of partner"
capture label var fin_typ "Finance type"
capture label var gd_serv "Type of goods and services"
capture label var lev_expc "Level of expectation"
capture label var ipr_trn "Transaction and type of Intellectual Property Rights (IPRs)"
capture label var inn_devr "Innovation developer"
capture label var n_class "Number of classes to which the intellectual property right belongs"
capture label var wrkmeth "Work methods"
capture label var y_regis "Year of registration"
capture label var ncl "International Classification of Goods and Services for the Purposes of the Registration of Marks (Nice Classification, 10th edition)"
capture label var ctm_nat "Nature of the trademark"
capture label var procstat "Process status"
capture label var bonds "Bonds"
capture label var maturity "Maturity"
capture label var yld_curv "Yield curve"
capture label var sizen_r2 "Enterprise size and Nace Rev. 2"
capture label var inet_spd "Internet speed"
capture label var inet_tec "Internet technologies"
capture label var bus_func "Business function"
capture label var bus_part "Kind of business partners"
capture label var change "Change"
capture label var lev_impc "Level of impact"
capture label var pow_asy "Power asymmetry"
capture label var supply "Means of goods and services supply"
capture label var job_cl "Job creation, losses and mobility"
capture label var impacpcv "Impact"
capture label var impact "Impact"
capture label var n_vessel "Number of vessels"
capture label var loadstat "Loading status"
capture label var tra_cov "Transport coverage"
capture label var cargo "Type of cargo"
capture label var c_load "Country/region of loading/embarking"
capture label var c_unload "Country/region of unloading/disembarking"
capture label var nstr24 "NST/R24 groups"
capture label var nst07 "Standard goods classification for transport statistics (NST 2007, 20 group)"
capture label var dang_gds "Dangerous goods"
capture label var port_iww "Ports used for inland waterways transport"
capture label var tra_meas "Traffic and transport measurement"
capture label var iww_hd "Categories of navigable inland waterways by horizontal dimensions of vessels and pushed convoys"
capture label var indic_lc "Labour cost indicators"
capture label var lcstruct "Labour costs structure"
capture label var eseg "European Socio-economic groups"
capture label var wantwork "Willingness to work"
capture label var regis_es "Registration with employment services"
capture label var ynlfs "Modalities of the variable for the ad-hoc module"
capture label var reasret "Reason for retirement"
capture label var c_bthfat "Country of birth of father"
capture label var c_bthmot "Country of birth of mother"
capture label var c_bthpar "Country of birth of parents"
capture label var mgstatus "Migration status"
capture label var hhwkstat "Working status within households"
capture label var swmethod "Method used for seeking work"
capture label var commute "Commuting"
capture label var workfind "Method used for finding work"
capture label var lev_match "Level of job matching"
capture label var job_autn "Job autonomy"
capture label var wstatuspr "Preferred employment status"
capture label var bsnpart "Business partner"
capture label var hire_plan "Hiring plan"
capture label var ctr_wtime "Control over working time"
capture label var effemp "Effects on employment"
capture label var chcare "Childcare services"
capture label var careresp "Care responsibility"
capture label var leave "Type of leave"
capture label var wtflex "Working time flexibility"
capture label var record "Recording"
capture label var frq_wtpr "Frequency of working under time pressure"
capture label var workplace "Place of work"
capture label var frq_woth "Frequency of working at other locations"
capture label var empsough "Type of employment sought"
capture label var hhcomp "Household composition"
capture label var c_work "Country/region of work"
capture label var par_mar "Maritime entity (partner)"
capture label var rep_mar "Maritime entity (reporting)"
capture label var seabasin "Sea basins"
capture label var tonnage "Size classes in gross tonnage"
capture label var indic_md "Indicator used in Euro_Med"
capture label var indic_en "Energy indicator"
capture label var indic_to "Tourism indicator"
capture label var indic_mg "Indicator on migration"
capture label var airsect "Source sectors for air emissions"
capture label var src "Hydrological parameters - flows - sources - water supply - treatment of water"
capture label var cons "Abstraction and use sector or treatment type"
capture label var la "Land use category (kmq)"
capture label var port_infr "Port infrastructure"
capture label var activity "Type of activity"
capture label var metroreg "Metropolitan regions"
capture label var ipc "International patent classification (IPC)"
capture label var asyl_app "Applicant type"
capture label var decision "Decision"
capture label var applicant "Applicant type"
capture label var withdraw "Type of withdrawal"
capture label var decision "Decision"
capture label var request "Requests"
capture label var leg_prov "Legal provision"
capture label var apprehen "Place of apprehension"
capture label var c_dest "Country of destination"
capture label var return "Type of return"
capture label var leg_fram "Legal framework"
capture label var indic_ip "Macroeconomic imbalance procedure indicators"
capture label var release "Release"
capture label var prod_na "Products and gross value added components"
capture label var asset10 "Assets (ESA 2010)"
capture label var penscheme "Pension scheme"
capture label var indic_nrg "Energy indicator"
capture label var calval "Calorific values"
capture label var siec "Standard international energy product classification (SIEC)"
capture label var gen_tech "Generation technologies"
capture label var lev_efcy "Level of efficiency"
capture label var plants "Type of plant"
capture label var network "Type of network"
capture label var customer "Customer"
capture label var hp_tech "Heat pumps technologies"
capture label var plant_tec "Technical characteristics of plants"
capture label var nrg_prc "Components of energy prices"
capture label var nrg_cons "Energy consumption"
capture label var fruitvar "Fruit species and groups of varieties"
capture label var density "Plantation density"
capture label var agprdmet "Agricultural production methods"
capture label var copat "Patenting and co-patenting"
capture label var sectperf "Sector of performance"
capture label var expen "Type of expenditure"
capture label var indx "Index"
capture label var purchase "Purchases"
capture label var ppp_cat "Analytical categories for purchasing power parities (PPPs) calculation"
capture label var projection "Type of projection"
capture label var victim "Type of victim"
capture label var train "Train category"
capture label var distance "Distance"
capture label var power "Type of current"
capture label var tra_infr "Transport infrastructure"
capture label var gaugetrk "Type of tracks gauge"
capture label var n_tracks "Number of tracks"
capture label var net_seg10 "Rail network segment (2010)"
capture label var net_seg15 "Rail network Segment (2015)"
capture label var net_seg "Rail network segment (2005)"
capture label var sectfund "Source of funds"
capture label var ford "Fields of research and development classification"
capture label var nabs07 "Nomenclature for the analysis and comparison of scientific programmes and budgets (NABS 2007)"
capture label var n_vehicl "Number of vehicles"
capture label var mot_nrg "Motor energy"
capture label var carriage "Type of carriage"
capture label var engine "Engine capacity of vehicle (in cmc)"
capture label var c_trans "Country of transit"
capture label var tra_oper "Type of operation and loading status"
capture label var regisveh "Category of vehicle registration"
capture label var value "Monetary value by size class"
capture label var annex "Annex"
capture label var priority "Priority of data collection"
capture label var credinst "Credit institutions"
capture label var size_mbr "Size classes in number of members"
capture label var nutrient "Nutrient"
capture label var org_inst "National and international organizations and institutions"
capture label var watpol "Water pollutants"
capture label var comspec "Bird species"
capture label var prod_sp "Sport products"
capture label var spscheme "ESSPROS-category of schemes"
capture label var spdep "ESSPROS-expenditure"
capture label var spfunc "ESSPROS-function"
capture label var spdepm "ESSPROS-means-testing"
capture label var spdepb "ESSPROS-pension type"
capture label var spdeps "ESSPROS-main expenditure types"
capture label var sptype "ESSPROS-receipts"
capture label var spsector "ESSPROS-receipts - sector of origin"
capture label var tra_mode "Mode of transport"
capture label var milkitem "Item of milk"
capture label var accomunit "Accommodation unit"
capture label var purpose "Purpose
capture label var hotelsize "Size of tourism establishments by number of rooms"
capture label var tinfo "Tourism information"
capture label var tripdest "Type of trip destination"
capture label var trip_arr "Trip arrangement"
capture label var dest "Destination"
capture label var indic_sp "Social protection indicators"
capture label var c_regis "Country of registration"
capture label var pers_cat "Category of persons"
capture label var tngprov "Training providers"
capture label var particip "Participation"
capture label var sourinfo "Sources from which participants found information on learning possibilities"
capture label var learning "Learning form"
capture label var cvtplan "Planning of CVT (continuing vocational training) in enterprises"
capture label var cvtplan cvtagr "Agreement on CVT (continuing vocational training)"
capture label var cvtplan involve "Involvement"
capture label var cvtplan skills "Skills and competences"
capture label var cvtplan reaction "Reaction"
capture label var cvtplan assess "Assessment"
capture label var cvtplan mainw "Main ways to obtain/develop new skills"
capture label var cvtplan formev "Form to evaluate CVT"
capture label var cvtplan tech "Technological or structural changes"
capture label var cvtplan cvt_ch "CVT change and subject of change"
capture label var cvtplan typtraif "Future type of training"
capture label var cvtplan prov "Vocational training providers"
capture label var cvtplan n_action "Number of training actions"
capture label var cvtplan twrk_hr "Taught activities during paid working hours"
capture label var cvtplan schedule "Type of schedule"
capture label var cvtplan startime "Starting time of the activity"
capture label var cvtplan daysweek "Days of the week"
capture label var cvtplan indic_ur "Urban audit indicator"
capture label var cvtplan vtarcls "Class of area under vines"
capture label var cvtplan indic_vi "Survey on variables under vines"
capture label var cvtplan vitype "Type of area under vines"
capture label var cvtplan wine_var "Wine-grape vine variety"
capture label var cvtplan vinespec "Specialisation of the vine holdings"

capture label var yn_arope "At risk of poverty or social exclusion - Yes/No"
capture label var yn_ovbur "Overburden - Yes/No"
exit

