cap label var CODE "Label - English"
cap label var TOTAL "All airlines"
cap label var LIC_EU "Airlines licensed in EU countries"
cap label var LIC_NEU "Airlines licensed in non-EU countries"
cap label var NSP "Not specified"
cap label var UNK "Unknown"
