cap label var CODE "Label - English"
cap label var NABS01 "Exploration and exploitation of the earth"
cap label var NABS02 "Environment"
cap label var NABS03 "Exploration and exploitation of space"
cap label var NABS04 "Transport, telecommunication and other infrastructures"
cap label var NABS05 "Energy"
cap label var NABS06 "Industrial production and technology"
cap label var NABS07 "Health"
cap label var NABS08 "Agriculture"
cap label var NABS09 "Education"
cap label var NABS10 "Culture, recreation, religion and mass media"
cap label var NABS11 "Political and social systems, structures and processes"
cap label var NABS12 "General advancement of knowledge: R&D financed from General University Funds (GUF)"
cap label var NABS121 "R&D related to natural sciences - financed from GUF"
cap label var NABS122 "R&D related to engineering sciences - financed from GUF"
cap label var NABS123 "R&D related to medical sciences - financed from GUF"
cap label var NABS124 "R&D related to agricultural sciences - financed from GUF"
cap label var NABS125 "R&D related to social sciences - financed from GUF"
cap label var NABS126 "R&D related to humanities - financed from GUF"
cap label var NABS13 "General advancement of knowledge: R&D financed from other sources than GUF"
cap label var NABS131 "R&D related to natural sciences - financed from other sources  than GUF"
cap label var NABS132 "R&D related to engineering sciences - financed from other sources  than GUF"
cap label var NABS133 "R&D related to medical sciences - financed from other sources  than GUF"
cap label var NABS134 "R&D related to agricultural sciences - financed from other sources  than GUF"
cap label var NABS135 "R&D related to social sciences - financed from other sources  than GUF"
cap label var NABS136 "R&D related to humanities - financed from other sources  than GUF"
cap label var NABS14 "Defence"
cap label var TOTALXNABS14 "Civil budget on R&D"
cap label var TOTAL "Total government budget allocations for R&D"
