cap label var TOTAL "Total"
cap label var ALL_MOST "All or most of the working time"
cap label var HLF_SLGMORE "Half of the working time or slightly more"
cap label var GE_HLF "At least half of the working time"
cap label var SOME "Some of the working time"
cap label var LTL "Little of the working time"
cap label var LTL_NONE "Little or none of the working time"
cap label var NONE "None"
cap label var NRP "No response"
