cap label var A "COVID-19 Test kits/ Instruments and apparatus used in diagnostic testing"
cap label var A1 "COVID-19 Test kits and diagnostic reagents"
cap label var A1_30021098 "Blood fractions and immunological products, whether or not modified or obtained by means of biotechnological processes (excl. antisera, haemoglobin, blood globulins and serum globulins)"
cap label var A1_30021300 "Immunological products, unmixed, not put up in measured doses or in forms or packings for retail sale"
cap label var A1_30021400 "Immunological products, mixed, not put up in measured doses or in forms or packings for retail sale"
cap label var A1_30021500 "Immunological products, put up in measured doses or in forms or packings for retail sale"
cap label var A1_30069300 "Placebos and blinded or double-blinded clinical trial kits for a recognised clinical trial, put up in measured doses"
cap label var A1_38220000 "Composite diagnostic or laboratory reagents (excl. composite diagnostic reagents for administration to patients, reagents for determining blood groups and blood factors, animal blood for diagnostic purposes and vaccines, toxins, cultures of microorganisms and similar products)"
cap label var A1_38221900 "Diagnostic or laboratory reagents on a backing, prepared diagnostic or laboratory reagents whether or not on a backing, whether or not put up in the form of kits (excl. for malaria, for Zika and other diseases transmitted by mosquitoes of the genus Aedes, for blood-grouping, and goods of 3006)"
cap label var A2 "COVID-19 Diagnostic test instruments and apparatus"
cap label var A2_38210000 "Culture media specially prepared for the development of micro-organisms"
cap label var A2_902780 "Instruments and apparatus for physical or chemical analysis, or for measuring or checking viscosity, porosity, expansion, surface tension or the like, or for measuring or checking quantities of heat, sound or light, n.e.s."
cap label var A2_90278100 "Mass spectrometers"
cap label var A2_90278990 "Instruments and apparatus for physical or chemical analysis or for determining surface tension or the like, or for measuring heat or sound, n.e.s."
cap label var B "Protective garments and the like"
cap label var B1 "Face masks (excl. paper surgical masks - under B6)"
cap label var B1_63079093 "Filtering facepieces (FFP) according to EN149, and other masks conforming to a similar standard for masks as respiratory protective devices to protect against particles"
cap label var B1_63079095 "Protective face masks (excl. filtering facepieces FFP according to EN149, and other masks conforming to a similar standard for masks as respiratory protective devices to protect against particles)"
cap label var B2 "Protective head caps"
cap label var B2_65050030 "Peaked caps and the like, knitted or crocheted, or made up from lace, felt or other textile fabric, in the piece (but not in strips), whether or not lined or trimmed (excl. toy and carnival headgear)"
cap label var B2_65050090 "Hats and other headgear, knitted or crocheted, or made up from lace, felt or other textile fabric, in the piece (but not in strips), whether or not lined or trimmed (excl. of fur felt or of felt of wool and fur, peaked caps, headgear for animals or headgear having the character of toys or festive articles)"
cap label var B2_65061010 "Safety headgear of plastics, whether or not lined or trimmed"
cap label var B2_65061080 "Safety headgear, whether or not lined or trimmed (other than of plastics)"
cap label var B2_65069100 "Bathing caps, hoods and other headgear, whether or not lined or trimmed, of rubber or plastics (other than safety headgear and headgear having the character of toys or festive articles)"
cap label var B3 "Gloves (excl. plastic gloves under B4)"
cap label var B3_40151100 "Surgical gloves, of vulcanised rubber other than hard rubber (excl. fingerstalls)"
cap label var B3_40151200 "Gloves, mittens and mitts, of a kind used for medical, surgical, dental or veterinary purposes, of vulcanised rubber"
cap label var B3_40151900 "Gloves, mittens and mitts, of vulcanised rubber (excl. surgical gloves)"
cap label var B3_61161020 "Gloves, impregnated, coated or covered with rubber, knitted or crocheted"
cap label var B4 "Protective unisex garments made of plastic sheeting, textile reinforced plastics or textile backed plastics"
cap label var B4_39262000 "Articles of apparel and clothing accessories produced by the stitching or sticking together of plastic sheeting, incl. gloves, mittens and mitts"
cap label var B4_39269060 "Protective face shields/visors of plastics"
cap label var B4_39269097 "Articles of plastics and articles of other materials of heading 3901 to 3914, n.e.s."
cap label var B5 "Hygienic or pharmaceutical articles, articles of apparel, clothing accessories and protective unisex garments made of rubber or vulcanized rubber"
cap label var B5_40149000 "Hygienic or pharmaceutical articles, incl. teats, of vulcanised rubber (excl. hard rubber), with or without fittings of hard rubber, n.e.s. (excl. sheath contraceptives and articles of apparel and clothing accessories, incl. gloves, for all purposes)"
cap label var B5_40159000 "Articles of apparel and clothing accessories, for all purposes, of vulcanised rubber (excl. hard rubber and footwear and headgear and parts thereof, and gloves, mittens and mitts)"
cap label var B6 "Paper or cellulose garments and clothing accessories for surgical/medical use"
cap label var B6_48185000 "Articles of apparel and clothing accessories, of paper pulp, paper, cellulose wadding or webs of cellulose fibres (excl. footware and parts thereof, incl. insoles, heel pieces and similar removable products, gaiters and similar products, headgear and parts thereof)"
cap label var B6_48189010 "Articles of paper pulp, paper, cellulose wadding or webs of cellulose fibre of a kind used for surgical, medical or hygienic purposes (excl. toilet paper, handkerchiefs, cleansing or facial tissues and towels, tablecloths, serviettes, sanitary towels and tampons, napkins and napkin liners for babies and similar sanitary articles, and goods put up for retail sale)"
cap label var B6_48189090 "Paper, cellulose wadding or webs of cellulose fibres, of a kind used for household or sanitary purposes, in rolls of a width <= 36 cm, or cut to size or shape; articles of paper pulp, paper, cellulose wadding or webs of cellulose fibres for household, sanitary or hospital use (excl. toilet paper, handkerchiefs, cleansing or facial tissues and towels, tablecloths, serviettes, sanitary towels and tampons, napkins and napkin liners for babies and similar sanitary articles, and articles of a kind used for surgical, medical or hygienic purposes not put up for retail sale)"
cap label var B7 "Industrial and occupational clothing"
cap label var B7_62113210 "Men's or boys' industrial and occupational clothing of cotton (excl. knitted or crocheted)"
cap label var B7_62113290 "Men's or boys' garments, of cotton, n.e.s. (not knitted or crocheted)"
cap label var B7_62113310 "Men's or boys' industrial and occupational clothing of man-made fibres (excl. knitted or crocheted)"
cap label var B7_62113390 "Men's or boys' garments, of man-made fibres, n.e.s. (not knitted or crocheted)"
cap label var B7_62113900 "Men's or boys' tracksuits and other garments, n.e.s. of textile materials (excl. of wool, fine animal hair, cotton or man-made fibres, knitted or crocheted)"
cap label var B7_621142 "Women's or girls' tracksuits and other garments, n.e.s. of cotton (excl. knitted or crocheted)"
cap label var B7_621143 "Women's or girls' tracksuits and other garments, n.e.s. of man-made fibres (excl. knitted or crocheted)"
cap label var B7_621149 "Women's or girls' tracksuits and other garments, n.e.s. of textile materials (excl. of cotton or man-made fibres, knitted or crocheted and goods of 9619)"
cap label var B8 "Other protective garments for surgical/medical use"
cap label var B8_611300 "Garments, knitted or crocheted, rubberised or impregnated, coated or covered with plastics or other materials (excl. babies' garments and clothing accessories)"
cap label var B8_62101010 "Garments made up of felt, whether or not impregnated, coated, covered or laminated (excl. babies' garments and clothing accessories)"
cap label var B8_62101092 "Single-use gowns made up of nonwovens, of a kind used by patients or surgeons during surgical procedures"
cap label var B8_62101098 "Garments made up of nonwovens, whether or not impregnated, coated, covered or laminated (excl. babies' garments, clothing accessories, and single-use gowns used during surgical procedures)"
cap label var B8_62102000 "Garments of the type described in subheading 6201,11 to 6201,19, rubberised or impregnated, coated, covered or laminated with plastics or other substances"
cap label var B8_62103000 "Garments of the type described in subheading 6202,11 to 6202,19, rubberised or impregnated, coated, covered or laminated with plastics or other substances"
cap label var B8_62104000 "Men's or boys' garments of textile fabrics, rubberised or impregnated, coated, covered or laminated with plastics or other substances (excl. of the type described in subheading 6201,11 to 6201,19, and babies' garments and clothing accessories)"
cap label var B8_62105000 "Women's or girls' garments of textile fabrics, rubberised or impregnated, coated, covered or laminated with plastics or other substances (excl. of the type described in subheading 6202,11 to 6202,19, and babies' garments and clothing accessories)"
cap label var B9 "Other protective accessories"
cap label var B9_56031110 "Nonwovens, coated or covered, n.e.s., of man-made filaments, weighing <= 25 g/m²"
cap label var B9_56039490 "Nonwovens, whether or not impregnated or laminated, n.e.s., weighing > than 150 g/m² (excl. coated or covered or of man-made filaments)"
cap label var B9_63079092 "Single-use drapes used during surgical procedures made up of nonwovens"
cap label var B9_900490 "Spectacles, goggles and the like, corrective, protective or other (excl. spectacles for testing eyesight, sunglasses, contact lenses, spectacle lenses and frames and mountings for spectacles)"
cap label var B9_902000 "Breathing appliances and gas masks, incl. parts and accessories (excl. protective masks having neither mechanical parts nor replaceable filters, and artificial respiration or other therapeutic respiration apparatus)"
cap label var B9_90200010 "Gas masks (excl. protective masks having neither mechanical parts nor replaceable filters)"
cap label var C "Disinfectants and sterilization products"
cap label var C1 "Hydroalcoholic and other solutions"
cap label var C1_22071000 "Undenatured ethyl alcohol, of actual alcoholic strength of >= 80%"
cap label var C1_22072000 "Denatured ethyl alcohol and other spirits of any strength"
cap label var C1_22089091 "Undenatured ethyl alcohol, of an alcoholic strength of < 80% vol, in containers holding <= 2 l"
cap label var C1_22089099 "Undenatured ethyl alcohol, of an alcoholic strength of < 80% vol, in containers holding > 2 l"
cap label var C1_28470000 "Hydrogen peroxide, whether or not solidified with urea"
cap label var C1_29051200 "Propan-1-ol "propyl alcohol" and propan-2-ol "isopropyl alcohol""
cap label var C1_29151100 "Formic acid"
cap label var C1_29151200 "Salts of formic acid"
cap label var C1_29182100 "Salicylic acid and its salts"
cap label var C2 "Hand sanitizers and other disinfectant preparations"
cap label var C2_38089410 "Disinfectants, based on quaternary ammonium salts, put up for retail sale or as preparations or articles (excl. goods of subheading 3808.50)"
cap label var C2_38089420 "Disinfectants, based on halogenated compounds, put up for retail sale or as preparations or articles (excl. goods of subheading 3808.50)"
cap label var C2_38089490 "Disinfectants, put up for retail sale or as preparations or articles (excl. such products based on quaternary ammonium salts or halogenated compounds and goods of subheading 3808.50)"
cap label var C3 "Sterilizers"
cap label var C3_84192000 "Medical, surgical or laboratory sterilizers"
cap label var C4 "Other equipment for disinfection purposes"
cap label var C4_85394900 "Ultraviolet or infra-red lamps"
cap label var C4_85395000 "Light-emitting diode "LED" lamps"
cap label var C4_85395200 "Light-emitting diode "LED" lamps"
cap label var D "Oxygen therapy equipment"
cap label var D_842139 "Machinery and apparatus for filtering or purifying gases (excl. isotope separators and intake air filters for internal combustion engines)"
cap label var D_901920 "Ozone therapy, oxygen therapy, aerosol therapy, artificial respiration or other therapeutic respiration apparatus, incl. parts and accessories"
cap label var D_90192010 "Mechanical ventilation apparatus, capable of providing invasive ventilation"
cap label var D_90192020 "Mechanical ventilation apparatus, non-invasive"
cap label var D_90192090 "Ozone therapy, oxygen therapy, aerosol therapy, artificial respiration or other therapeutic respiration apparatus, incl. parts and accessories (excl. mechanical ventilation apparatus)"
cap label var E "Medical devices and equipment"
cap label var E2 "Monitors"
cap label var E2_85285291 "LCD monitors designed for computer use but of a kind not used principally with a computer (excl. with TV receiver)"
cap label var E2_85285299 "Monitors designed for computer use but of a kind not used principally with a computer (excl. CRT, LCD, with TV receiver)"
cap label var E2_85285900 "Monitors (excl. with TV receiver, CRT and those designed for computer use)"
cap label var E2_85285920 "Monochrome flat panel displays, not incorporating television reception apparatus, able to display signals from automatic data-processing machines with an acceptable level of"
cap label var E2_85285931 "Colour LCD monitors, not incorporating television reception apparatus, able to display signals from automatic data-processing machines with an acceptable level of functionality (excl. those of a kind solely or principally used in an automatic data-processing system of heading 8471)"
cap label var E2_85285939 "Colour flat panel displays, not incorporating television reception apparatus, able to display signals from automatic data-processing machines with an acceptable level of functionality (excl. LCD monitors and those of a kind solely or principally used in an automatic data-processing system of heading 8471)"
cap label var E2_85285970 "Monitors, not incorporating television reception apparatus (excl. with cathode ray tube, and flat panel displays able to display signals from automatic data-processing machines with an acceptable level of functionality)"
cap label var E2_90181910 "Electro-diagnostic monitoring apparatus for simultaneous monitoring of two or more physiological parameters"
cap label var E2_90181990 "Electro-diagnostic apparatus, incl. apparatus for functional exploratory examination or for checking physiological parameters (excl. electro-cardiographs, ultrasonic scanning apparatus, magnetic resonance imaging apparatus, scintigraphic apparatus and monitoring apparatus for simultaneous monitoring of two or more physiological parameters)"
cap label var E3 "Pumps"
cap label var E3_84138100 "Pumps for liquids, power-driven (excl. those of subheading 8413.11 and 8413.19, fuel, lubricating or cooling medium pumps for internal combustion piston engine, concrete pumps, general reciprocating or rotary positive displacement pumps and centrifugal pumps of all kinds)"
cap label var E3_90189050 "Transfusion and infusion apparatus used in medical sciences"
cap label var E3_90189084 "Instruments and appliances used in medical, surgical or veterinary sciences, n.e.s."
cap label var E4 "Thermometers"
cap label var E4_902511 "Thermometers, liquid-filled, for direct reading, not combined with other instruments"
cap label var E4_902519 "Thermometers and pyrometers, not combined with other instruments (excl. liquid-filled thermometers for direct reading)"
cap label var E5 "Other medical devices and equipment"
cap label var E5_37011000 "Photographic plates and film in the flat, sensitised, unexposed, for X-ray (excl. of paper, paperboard and textiles)"
cap label var E5_37021000 "Photographic film in rolls, unexposed, for X-ray (excl. of paper, paperboard or textiles)"
cap label var E5_7017 "Laboratory, hygienic or pharmaceutical glassware, whether or not graduated or calibrated (excl. containers for the conveyance or packing of goods, measuring, checking or medical instruments and apparatus of chapter 90)"
cap label var E5_731100 "Containers of iron or steel, for compressed or liquefied gas (excl. containers specifically constructed or equipped for one or more types of transport)"
cap label var E5_73249000 "Sanitary ware, incl. parts thereof (excl. cans, boxes and similar containers of heading 7310, small wall cabinets for medical supplies or toiletries and other furniture of chapter 94, and fittings, complete sinks and washbasins, of stainless steel, complete baths and fittings)"
cap label var E5_76130000 "Aluminium containers for compressed or liquefied gas"
cap label var E5_85437090 "Electrical machines and apparatus, having individual functions, n.e.s. in chap. 85(2018-2500);Indicator panels with liquid crystal devices "LCD" (excl. active matrix liquid crystal devices and those of a kind used for motor vehicles, cycles or traffic signalling)(2017-2017);Electrical machines and apparatus, having individual functions, n.e.s. in chap. 85(2007-2016)"
cap label var E5_90181100 "Electro-cardiographs"
cap label var E5_90181200 "Ultrasonic scanning apparatus"
cap label var E5_90189020 "Endoscopes used in medical, surgical or veterinary sciences"
cap label var E5_90189060 "Anaesthetic apparatus and instruments"
cap label var E5_90192090 "Ozone therapy, oxygen therapy, aerosol therapy, artificial respiration or other therapeutic respiration apparatus, incl. parts and accessories (excl. mechanical ventilation apparatus)"
cap label var E5_90221200 "Computer tomography apparatus"
cap label var E5_90221400 "Apparatus based on the use of X-rays, for medical, surgical or veterinary uses (excl. for dental purposes and computer tomography apparatus)"
cap label var E5_90268020 "Electronic instruments or apparatus for measuring or checking variables of liquids or gases, n.e.s."
cap label var E5_90268080 "Non-electronic instruments or apparatus for measuring or checking variables of liquids or gases, n.e.s."
cap label var E5_90282000 "Liquid meters, incl. calibrating meters therefor"
cap label var F "Medical consumables"
cap label var F1 "Medicines / Vaccines"
cap label var F1_29339980 "Heterocyclic compounds with nitrogen hetero-atom{s} only (excl. those containing an unfused pyrazole, imidazole, pyridine or triazine ring, whether or not hydrogenated, a quinoline or isoquinoline ring-system, not further fused, whether or not hydrogenated, a pyrimidine ring, whether or not hydrogenated, or piperazine ring in the structure, lactams, alprazolam (INN), camazepam (INN), chlordiazepoxide (INN), clonazepam (INN), clorazepate, delorazepam (INN), diazepam (INN), estazolam (INN), ethyl loflazepate (INN), fludiazepam (INN), flunitrazepam (INN), flurazepam (INN), halazepam (INN), lorazepam (INN), lormetazepam (INN), mazindol (INN), medazepam (INN), midazolam (INN), nimetazepam (INN), nitrazepam (INN), nordazepam (INN), oxazepam (INN), pinazepam (INN), prazepam (INN), pyrovalerone (INN), temazepam (INN), tetrazepam (INN), triazolam (INN), salts thereof, indole, 3-methylindole "skatole", 6-allyl-6,7-dihydro-5H-dibenz"c,e"azepine "azapetine", phenindamine (INN) and their salts, imipramine hydrochloride "INNM", 2,4-di-tert-butyl-6-"5-chlorobenzotriazol-2-yl"phenol and azinphos-methyl (ISO))(2017-2500);Heterocyclic compounds with nitrogen hetero-atom{s} only (excl. those containing an unfused pyrazole, imidazole, pyridine or triazine ring, whether or not hydrogenated, a quinoline or isoquinoline ring-system, not further fused, whether or not hydrogenated, a pyrimidine ring, whether or not hydrogenated, or piperazine ring in the structure, lactams, alprazolam (INN), camazepam (INN), chlordiazepoxide (INN), clonazepam (INN), clorazepate, delorazepam (INN), diazepam (INN), estazolam (INN), ethyl loflazepate (INN), fludiazepam (INN), flunitrazepam (INN), flurazepam (INN), halazepam (INN), lorazepam (INN), lormetazepam (INN), mazindol (INN), medazepam (INN), midazolam (INN), nimetazepam (INN), nitrazepam (INN), nordazepam (INN), oxazepam (INN), pinazepam (INN), prazepam (INN), pyrovalerone (INN), temazepam (INN), tetrazepam (INN), triazolam (INN), salts thereof, indole, 3-methylindole "skatole", 6-allyl-6,7-dihydro-5H-dibenz"c,e"azepine "azapetine", phenindamine (INN) and their salts, imipramine hydrochloride "INNM", 2,4-di-tert-butyl-6-"5-chlorobenzotriazol-2-yl"phenol)(2009-2016)"
cap label var F1_29349990 "Nucleic acids and their salts, whether or not chemically defined; heterocyclic compounds (excl. those with oxygen or nitrogen hetero-atom"s" only, compounds containing in the structure an unfused thiazole ring or a benzothiazole or phenothiazine ring-system or further fused, aminorex (INN), brotizolam (INN), clotiazepam (INN), cloxazolam (INN), dextromoramide (INN), haloxazolam (INN), ketazolam (INN), mesocarb (INN), oxazolam (INN), pemoline (INN), phendimetrazine (INN), phenmetrazine (INN), sufentanil (INN), salts thereof, chlorpothixene (INN), thenalidine (INN) and its tartrates and maleates, furazolidone (INN), 7-aminocephalosporanic acid, salts and esters of "6R, 7R"-3-acetoxymethyl-7-{"R"-2-formyloxy-2-phenylacetamido}-8-oxo-5-thia-1-azabicyclo{4.2.0}oct-2-ene-2-carboxylic acid, 1-{2-"1,3-dioxan-2-yl"ethyl}-2-methylpyridinium bromide, and inorganic or organic compounds of mercury)(2022-2500);Nucleic acids and their salts, whether or not chemically defined; heterocyclic compounds (excl. those with oxygen or nitrogen hetero-atom"s" only, compounds containing in the structure an unfused thiazole ring or a benzothiazole or phenothiazine ring-system or further fused, aminorex (INN), brotizolam (INN), clotiazepam (INN), cloxazolam (INN), dextromoramide (INN), haloxazolam (INN), ketazolam (INN), mesocarb (INN), oxazolam (INN), pemoline (INN), phendimetrazine (INN), phenmetrazine (INN), sufentanil (INN), salts thereof, chlorpothixene (INN), thenalidine (INN) and its tartrates and maleates, furazolidone (INN), 7-aminocephalosporanic acid, salts and esters of "6R, 7R"-3-acetoxymethyl-7-{"R"-2-formyloxy-2-phenylacetamido}-8-oxo-5-thia-1-azabicyclo{4.2.0}oct-2-ene-2-carboxylic acid, 1-{2-"1,3-dioxan-2-yl"ethyl}-2-methylpyridinium bromide, and inorganic or organic compounds of mercury)(2017-2021);Nucleic acids and their salts, whether or not chemically defined; heterocyclic compounds (excl. those with oxygen or nitrogen hetero-atom"s" only, compounds containing in the structure an unfused thiazole ring or a benzothiazole or phenothiazine ring-system or further fused, aminorex (INN), brotizolam (INN), clotiazepam (INN), cloxazolam (INN), dextromoramide (INN), haloxazolam (INN), ketazolam (INN), mesocarb (INN), oxazolam (INN), pemoline (INN), phendimetrazine (INN), phenmetrazine (INN), sufentanil (INN), salts thereof, chlorpothixene (INN), thenalidine (INN) and its tartrates and maleates, furazolidone (INN), 7-aminocephalosporanic acid, salts and esters of "6R, 7R"-3-acetoxymethyl-7-{"R"-2-formyloxy-2-phenylacetamido}-8-oxo-5-thia-1-azabicyclo{4.2.0}oct-2-ene-2-carboxylic acid, 1-{2-"1,3-dioxan-2-yl"ethyl}-2-methylpyridinium bromide, and inorganic or organic compounds of mercury)(2012-2016);Nucleic acids and their salts, whether or not chemically defined; heterocyclic compounds (excl. those with oxygen or nitrogen hetero-atom"s" only, compounds containing in the structure an unfused thiazole ring or a benzothiazole or phenothiazine ring-system or further fused, aminorex (INN), brotizolam (INN), clotiazepam (INN), cloxazolam (INN), dextromoramide (INN), haloxazolam (INN), ketazolam (INN), mesocarb (INN), oxazolam (INN), pemoline (INN), phendimetrazine (INN), phenmetrazine (INN), sufentanil (INN), salts thereof, chlorpothixene (INN), thenalidine (INN) and its tartrates and maleates, furazolidone (INN), 7-aminocephalosporanic acid, salts and esters of "6R, 7R"-3-acetoxymethyl-7-{"R"-2-formyloxy-2-phenylacetamido}-8-oxo-5-thia-1-azabicyclo{4.2.0}oct-2-ene-2-carboxylic acid, 1-{2-"1,3-dioxan-2-yl"ethyl}-2-methylpyridinium bromide, and inorganic or organic compounds of mercury)(2007-2011);Nucleic acids and their salts, whether or not chemically defined; heterocyclic compounds (excl. those with oxygen or nitrogen hetero-atom"s" only, compounds containing in the structure an unfused thiazole ring or a benzothiazole or phenothiazine ring-system or further fused, aminorex (INN), brotizolam (INN), clotiazepam (INN), cloxazolam (INN), dextromoramide (INN), haloxazolam (INN), ketazolam (INN), mesocarb (INN), oxazolam (INN), pemoline (INN), phendimetrazine (INN), phenmetrazine (INN), sufentanil (INN), salts thereof, chlorpothixene (INN), thenalidine (INN) and its tartrates and maleates, furazolidone (INN), 7-aminocephalosporanic acid, salts and esters of "6R, 7R"-3-acetoxymethyl-7-{"R"-2-formyloxy-2-phenylacetamido}-8-oxo-5-thia-1-azabicyclo{4.2.0}oct-2-ene-2-carboxylic acid and 1-{2-"1,3-dioxan-2-yl"ethyl}-2-methylpyridinium bromide)(2002-2006)"
cap label var F1_300220 "Vaccines for human medicine"
cap label var F1_30022010 "Vaccines against SARS-related coronaviruses "SARS-Cov species", for human medicine"
cap label var F1_30024110 "Vaccines against SARS-related coronaviruses "SARS-CoV species", for human medicine"
cap label var F1_30024900 "Toxins, cultures of micro-organisms and similar products, e.g. plasmodia (excl. yeasts and vaccine"
cap label var F1_30025100 "Cell therapy products"
cap label var F1_30025900 "Cell cultures, whether or not modified (excl. cell therapy products)"
cap label var F1_30039000 "Medicaments consisting of two or more constituents mixed together for therapeutic or prophylactic uses, not in measured doses or put up for retail sale (excl. antibiotics containing hormones or steroids used as hormones, but not containing antibiotics, alkaloids or derivatives thereof, hormones or antibiotics or goods of heading 3002, 3005 or 3006)(2017-2500);Medicaments consisting of two or more constituents mixed together for therapeutic or prophylactic uses, not in measured doses or put up for retail sale (excl. antibiotics containing hormones or steroids used as hormones, but not containing antibiotics, alkaloids or derivatives thereof, hormones or antibiotics or goods of heading 3002, 3005 or 3006)(2010-2016)"
cap label var F1_30049000 "Medicaments consisting of mixed or unmixed products for therapeutic or prophylactic purposes, put up in measured doses "incl. those in the form of transdermal administration" or in forms or packings for retail sale (excl. medicaments containing antibiotics, medicaments containing hormones or steroids used as hormones, but not containing antibiotics, medicaments containing alkaloids or derivatives thereof but not containing hormones or antibiotics and medicaments containing  provitamins, vitamins or derivatives thereof used as vitamins)(2017-2500);Medicaments consisting of mixed or unmixed products for therapeutic or prophylactic purposes, put up in measured doses "incl. those in the form of transdermal administration" or in forms or packings for retail sale (excl. medicaments containing antibiotics, medicaments containing hormones or steroids used as hormones, but not containing antibiotics, medicaments containing alkaloids or derivatives thereof but not containing hormones or antibiotics and medicaments containing  provitamins, vitamins or derivatives thereof used as vitamins)(2012-2016)"
cap label var F2 "Wadding, gauze, bandages, tape and similar, impregnated or coated with pharmaceutical substances, for medical use."
cap label var F2_30051000 "Adhesive dressings and other articles having an adhesive layer, impregnated or covered with pharmaceutical substances or put up for retail sale for medical, surgical, dental or veterinary purposes"
cap label var F2_30059010 "Wadding and articles of wadding, impregnated or coated with pharmaceutical substances or put up in forms or packings for retail sale for medical, surgical, dental or veterinary purposes"
cap label var F2_30059031 "Gauze and articles of gauze, impregnated or covered with pharmaceutical substances or put up for retail sale for medical, surgical, dental or veterinary purposes"
cap label var F2_30059099 "Bandages and similar articles impregnated or covered with pharmaceutical substances or put up for retail sale for medical, surgical, dental or veterinary purposes (excl. those of textile materials, adhesive dressings and other articles having an adhesive layer)"
cap label var F3 "Soap and organic surface-active products and preparations"
cap label var F3_34011100 "Soap and organic surface-active products and preparations, in the form of bars, cakes, moulded pieces or shapes, and paper, wadding, felt and nonwovens, impregnated, coated or covered with soap or detergent, for toilet use, incl. medicated products"
cap label var F3_34011900 "Soap and organic surface-active products and preparations, in the form of bars, cakes, moulded pieces or shapes, and paper, wadding, felt and nonwovens, impregnated, coated or covered with soap or detergent (excl. those for toilet use, incl. medicated products)"
cap label var F3_34012010 "Soap in the form of flakes, granules or powders"
cap label var F3_34012090 "Soap in paste form "soft soap" or in aqueous solution "liquid soap""
cap label var F3_34013000 "Organic surface-active products and preparations for washing the skin, in the form of liquid or cream and put up for retail sale, whether or not containing soap"
cap label var F3_34021200 "Cationic organic surface-active agents, whether or not put up for retail sale (excl. soap)"
cap label var F3_34024100 "Cationic organic surface-active agents, whether or not put up for retail sale"
cap label var F4 "Sterile tubes (excl. endotracheal tubes under E5)"
cap label var F4_391721 "Rigid tubes, pipes and hoses, of polymers of ethylene"
cap label var F4_391722 "Rigid tubes, pipes and hoses of polymers of propylene"
cap label var F4_391723 "Rigid tubes, pipes and hoses, of polymers of vinyl chloride"
cap label var F4_39172900 "Rigid tubes, pipes and hoses, of plastics (excl. those of polymers of ethylene, propylene and vinyl chloride)"
cap label var F4_39173100 "Flexible tubes, pipes and hoses, of plastics, burst pressure >= 27,6 MPa"
cap label var F4_39173200 "Flexible tubes, pipes and hoses of plastics, not reinforced or otherwise combined with other materials, without fittings"
cap label var F4_39173300 "Flexible tubes, pipes and hoses of plastics, not reinforced or otherwise combined with other materials, with fittings, seals or connectors"
cap label var F4_39173900 "Flexible tubes, pipes and hoses, of plastics, reinforced or otherwise combined with other materials (excl. those with a burst pressure of >= 27,6 MPa)"
cap label var F5 "Syringes, with or without needles"
cap label var F5_90183110 "Syringes of plastic, with or without needles, used in medical, surgical, dental or veterinary sciences"
cap label var F5_90183190 "Syringes, with or without needles, used in medical, surgical, dental or veterinary sciences (excl. of plastic)"
cap label var F5_90183210 "Tubular metal needles, used in medical, surgical, dental or veterinary sciences"
cap label var F5_90183290 "Needles for sutures, used in medical, surgical, dental or veterinary sciences"
cap label var F5_90183900 "Needles, catheters, cannulae and the like, used in medical, surgical, dental or veterinary sciences (excl. syringes, tubular metal needles and needles for sutures)"
cap label var F6 "Other medical consumables"
cap label var F6_28044000 "Oxygen"
cap label var F6_30067000 "Gel preparations designed to be used  in human or veterinary medicine as a lubricant for parts of the body for surgical operations or physical examinations or as a coupling agent between the body and medical instruments"
cap label var F6_392329 "Sacks and bags, incl. cones, of plastics (excl. those of polymers of ethylene)"
cap label var G "Medical vehicles and furniture"
cap label var G_63062200 "Tents of synthetic fibres (excl. umbrella and play tents)"
cap label var G_63062900 "Tents of textile materials (excl. cotton or synthetic fibres and fly sheets)"
cap label var G_84248900 "Mechanical appliances, whether or not hand-operated, for projecting, dispersing or spraying liquids or powders, n.e.s."
cap label var G_84248970 "Mechanical appliances, whether or not hand-operated, for projecting, dispersing or spraying liquids or powders, n.e.s."
cap label var G_870590 "Special purpose motor vehicles (other than those principally designed for the transport of persons or goods and excl. concrete-mixer lorries, fire fighting vehicles, mobile drilling derricks and crane lorries)"
cap label var G_87139000 "Carriages for disabled persons, motorised or otherwise mechanically propelled (excl. specially designed motor vehicles and bicycles)"
cap label var G_94029000 "Operating tables, examination tables, and other medical, dental, surgical or veterinary furniture (excl. dentists' or similar chairs, special tables for X-ray examination, and stretchers and litters, incl. trolley-stretchers)"
