cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var SAL "Employees"
cap label var OJA "Online job advertisements"
cap label var OJAR "Online job advertisement rate"
cap label var LMD "Labour market demand"
cap label var LSH "Labour shortages"
cap label var UNE "Unemployment (ILO)"
cap label var UNE_MM "Mismatch unemployment"
cap label var UNE_MM_ACRS "Mismatch unemployment across countries"
cap label var UNE_GAP "Unemployment gap"
cap label var LTU "Long-term unemployment"
cap label var VLTU "Very long-term unemployment"
cap label var ACT "Persons in the labour force"
cap label var EMP_LFS "Total employment (resident population concept - LFS)"
cap label var EMP_CLT "Cultural employment"
cap label var UEMP "Underemployed part-time workers"
cap label var SEEK_NAV "Persons seeking work but not immediately available"
cap label var NSEE_AV "Persons available to work but not seeking"
cap label var JOBVAC "Job vacancies"
cap label var JOBOCC "Occupied (posts) jobs"
cap label var JVR "Job vacancy rate"
cap label var JVRCH_Q "Job vacancy quarterly rate of change"
cap label var JVRCH_A "Job vacancy annual rate of change"
cap label var SLACK "Labour market slack"
cap label var SC071 "Children aged 0-17 living in jobless households: share of persons aged 0-17 who are living in households where no-one is working"
cap label var SC072 "People aged 18-59 living in jobless households: share of persons aged 18-59 who are living in households where no-one works"
cap label var SC073 "Women aged 18-59 living in jobless households: share of women aged 18-59 who are living in households where no-one works"
cap label var SC074 "Men aged 18-59 living in jobless households: share of men aged 18-59 who are living in households where no-one works"
cap label var E_E "Transition employment - employment"
cap label var E_U "Transition employment - unemployment"
cap label var E_I "Transition employment - outside the labour force"
cap label var U_E "Transition unemployment - employment"
cap label var U_U "Transition unemployment - unemployment"
cap label var U_I "Transition unemployment - outside the labour force"
cap label var I_E "Transition outside the labour force - employment"
cap label var I_U "Transition outside the labour force - unemployment"
cap label var I_I "Transition outside the labour force - outside the labour force"
cap label var INAC "Persons outside the labour force"
cap label var OTH "Others"
