cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var HHC_10 "Children (living with other adults)"
cap label var HHC_20 "Single adult - total"
cap label var HHC_21 "Single adult with children"
cap label var HHC_22 "Single adult without children"
cap label var HHC_30 "Couple - total"
cap label var HHC_31 "Couple with children"
cap label var HHC_32 "Couple without children"
cap label var HIC_30 "Adult living in a couple - total"
cap label var HIC_31 "Adult living in a couple with children"
cap label var HIC_32 "Adult living in a couple without children"
cap label var HHC_40 "Other type of household - total"
cap label var HHC_41 "Other type of household with children"
cap label var HHC_42 "Other type of household without children"
cap label var HIC_40 "Adult living in another type of household - total"
cap label var HIC_41 "Adult living in another type of household with children"
cap label var HIC_42 "Adult living in another type of household without children"
cap label var HHC_50 "Total of adults"
cap label var HHC_51 "Adult (total) with children"
cap label var HHC_52 "Adult (total) without children"
cap label var HWC_50 "Total (all households)"
cap label var HWC_51 "Households with dependent children - total"
cap label var HWC_52 "Households without dependent children - total"
cap label var FAM "Family nucleus"
cap label var FAM1 "One-family nucleus"
cap label var CH_A_OTH "Children (living with other adults)"
cap label var CPL "Couple"
cap label var CPL_CH "Couple with resident children"
cap label var CPL_NCH "Couple without resident children"
cap label var CPL_YCH "Couple with at least one resident child under 25 years"
cap label var CPL_NYCH "Couple without resident children under 25 years"
cap label var CPL_OCH "Couple with youngest resident child 25 years or older"
cap label var MAR "Married couple"
cap label var MAR_NCH "Married couple without resident children"
cap label var MARO_NCH "Opposite-sex married couple without resident children"
cap label var MARS_NCH "Same-sex married couple without resident children"
cap label var MAR_YCH "Married couple with at least one resident child under 25 years"
cap label var MARO_YCH "Opposite-sex married couple with at least one resident child under 25 years"
cap label var MARS_YCH "Same-sex married couple with at least one resident child under 25 years"
cap label var MAR_OCH "Married couple with youngest resident child 25 years or older"
cap label var MARO_OCH "Opposite-sex married couple with youngest resident child 25 years or older"
cap label var MARS_OCH "Same-sex married couple with youngest resident child 25 years or older"
cap label var REP "Couple in registered partnership"
cap label var REP_NCH "Couple in registered partnership without resident children"
cap label var REPO_NCH "Opposite-sex couple in registered partnership without resident children"
cap label var REPS_NCH "Same-sex couple in registered partnership without resident children"
cap label var REP_YCH "Couple in registered partnership with at least one resident child under 25 years"
cap label var REPO_YCH "Opposite-sex couple in registered partnership with at least one resident child under 25 years"
cap label var REPS_YCH "Same-sex couple in registered partnership with at least one resident child under 25 years"
cap label var REP_OCH "Couple in registered partnership with youngest resident child 25 years or older"
cap label var REPO_OCH "Opposite-sex couple in registered partnership with youngest resident child 25 years or older"
cap label var REPS_OCH "Same-sex couple in registered partnership with youngest resident child 25 years or older"
cap label var MAR_REP "Married couple or in registered partnership"
cap label var MAR_REP_NCH "Married couple or in registered partnership without resident children"
cap label var MAR_REP_YCH "Married couple or in registered partnership with at least one resident child under 25 years"
cap label var MAR_REP_OCH "Married couple or in registered partnership with youngest resident child 25 years or older"
cap label var MARS_REPS "Same-sex married couple or registered partnership"
cap label var MARS_REPS_NCH "Same-sex married couple or registered partnership without resident children"
cap label var MARS_REPS_YCH "Same-sex married couple or registered partnership with at least one resident child under 25 years"
cap label var MARS_REPS_OCH "Same-sex married couple or registered partnership with youngest resident child 25 years or older"
cap label var CSU "Couple in consensual union"
cap label var CSU_NCH "Couple in consensual union without resident children"
cap label var CSUO_NCH "Opposite-sex couple in consensual union without resident children"
cap label var CSUS_NCH "Same-sex couple in consensual union without resident children"
cap label var CSU_YCH "Couple in consensual union with at least one resident child under 25 years"
cap label var CSUO_YCH "Opposite-sex couple in consensual union with at least one resident child under 25 years"
cap label var CSUS_YCH "Same-sex couple in consensual union with at least one resident child under 25 years"
cap label var CSU_OCH "Couple in consensual union with youngest resident child 25 years or older"
cap label var CSUO_OCH "Opposite-sex couple in consensual union with youngest resident child 25 years or older"
cap label var CSUS_OCH "Same-sex couple in consensual union with youngest resident child 25 years or older"
cap label var PAR_YCH_P "At least one parent with at least one resident child under 25 years and other person"
cap label var PAR1_YCH "Lone parent with at least one resident child under 25 years"
cap label var PAR1_OCH "Lone parent with youngest resident child 25 years or older"
cap label var M1 "One single male"
cap label var M1_CH "Lone father living with at least one child"
cap label var M1_YCH "Lone father with at least one resident child under 25 years"
cap label var M1_OCH "Lone father with at least one resident child 25 years or older"
cap label var F1 "One single female"
cap label var F1_CH "Lone mother living with at least one child"
cap label var F1_YCH "Lone mother with at least one resident child under 25 years"
cap label var F1_OCH "Lone mother with at least one resident child 25 years or older"
cap label var P1_CH "Lone mother or father living with at least one child"
cap label var FAM_GE2 "Two-or-more-family nucleus"
cap label var NFAM "Non-family nucleus"
cap label var P1 "One-person household"
cap label var A1 "One adult"
cap label var A1_DCH "One adult with dependent children"
cap label var A1_NDCH "One adult without dependent children"
cap label var A1_CH "One adult with resident children"
cap label var A1_NCH "One adult without resident children"
cap label var A2 "Two adults"
cap label var A2_DCH "Two adults with dependent children"
cap label var A2_DCH1 "Two adults with one dependent child"
cap label var A2_DCH2 "Two adults with two dependent children"
cap label var A2_DCH_GE3 "Two adults with three or more dependent children"
cap label var A_GE2_DCH "Two or more adults with dependent children"
cap label var A_GE2_NDCH "Two or more adults without dependent children"
cap label var A_GE3 "Three or more adults"
cap label var A_GE3_DCH "Three or more adults with dependent children"
cap label var MULTI "Multiperson household other than family nucleus"
cap label var DCH_NDCH "Household"
cap label var DCH "Household with dependent children"
cap label var NDCH "Household without dependent children"
cap label var A1_LT30 "One adult younger than 30 years"
cap label var A1_Y30_64 "One adult aged between 30 and 64 years"
cap label var A1_LT65 "One adult younger than 65 years"
cap label var A1_GE65 "One adult 65 years or over"
cap label var A2_2LT65 "Two adults younger than 65 years"
cap label var A2_GE1_GE65 "Two adults, at least one aged 65 years or over"
cap label var A_CPL "Adult living in a couple"
cap label var A_CPL_CH "Adult living in a couple with resident children"
cap label var A_CPL_NCH "Adult living in a couple without resident children"
cap label var A_OTH "Adult living in another type of household"
cap label var A_OTH_CH "Adult living in another type of household with resident children"
cap label var A_OTH_NCH "Adult living in another type of household without resident children"
cap label var A_CH_NCH "Adult"
cap label var A_CH "Adult with resident children"
cap label var A_NCH "Adult without resident children"
cap label var OTH "Other type of household"
cap label var OTH_CH "Other type of household with resident children"
cap label var OTH_NCH "Other type of household without resident children"
cap label var NRP "No response"
cap label var UNK "Unknown"
