cap label var AD "Andorra"
cap label var AE "United Arab Emirates"
cap label var AF "Afghanistan"
cap label var AG "Antigua and Barbuda"
cap label var AI "Anguilla"
cap label var AL "Albania"
cap label var AM "Armenia"
cap label var AN "Netherlands Antilles (incl. Aruba 'AW' -> 1986)"
cap label var AO "Angola"
cap label var AQ "Antarctica"
cap label var AR "Argentina"
cap label var AS "American Samoa"
cap label var AT "Austria"
cap label var AU "Australia"
cap label var AW "Aruba"
cap label var AZ "Azerbaijan"
cap label var BA "Bosnia and Herzegovina"
cap label var BB "Barbados"
cap label var BD "Bangladesh"
cap label var BE "Belgium (incl. Luxembourg 'LU' -> 1998)"
cap label var BF "Burkina Faso"
cap label var BG "Bulgaria"
cap label var BH "Bahrain"
cap label var BI "Burundi"
cap label var BJ "Benin"
cap label var BL "Saint Barthélemy"
cap label var BM "Bermuda"
cap label var BN "Brunei Darussalam"
cap label var BO "Bolivia, Plurinational State of"
cap label var BQ "Bonaire, Sint Eustatius and Saba"
cap label var BR "Brazil"
cap label var BS "Bahamas"
cap label var BT "Bhutan"
cap label var BV "Bouvet Island"
cap label var BW "Botswana"
cap label var BY "Belarus (Belorussia)"
cap label var BZ "Belize"
cap label var CA "Canada"
cap label var CC "Cocos Islands (or Keeling Islands)"
cap label var CD "Congo, Democratic Republic of"
cap label var CF "Central African Republic"
cap label var CG "Congo"
cap label var CH "Switzerland (incl. Liechtenstein 'LI' -> 1994)"
cap label var CI "Côte d’Ivoire (Ivory Coast)"
cap label var CK "Cook Islands"
cap label var CL "Chile"
cap label var CM "Cameroon"
cap label var CN "China"
cap label var CO "Colombia"
cap label var CR "Costa Rica"
cap label var CS "Serbia and Montenegro(2004-2005);Czechoslovakia(1976-1992)"
cap label var CU "Cuba"
cap label var CV "Cabo Verde"
cap label var CW "Curaçao"
cap label var CX "Christmas Island"
cap label var CY "Cyprus"
cap label var CZ "Czechia"
cap label var DD "German Democratic Republic"
cap label var DE "Germany (incl. German Democratic Republic 'DD' from 1991)"
cap label var DJ "Djibouti"
cap label var DK "Denmark"
cap label var DM "Dominica"
cap label var DO "Dominican Republic"
cap label var DZ "Algeria"
cap label var EA "Euro area (AT-01/1999, BE-01/1999, CY-01/2008, DE-01/1999, EE-01/2011, ES-01/1999, FI-01/1999, FR-01/1999, GR-01/2001, HR-01/2023, IE-01/1999, IT-01/1999, LT-01/2015, LU-01/1999, LV-01/2014, MT-01/2008, NL-01/1999, PT-01/1999, SI-01/2007, SK-01/2009)"
cap label var EA19 "Euro area - 19 countries (AT, BE, CY, DE, EE, ES, FI, FR, GR, IE, IT, LT, LU, LV, MT, NL, PT, SI, SK)"
cap label var EA19_EXTRA "Extra-euro area - 19 countries (= 'WORLD' - 'EA19_INTRA')"
cap label var EA19_INTRA "Intra-euro area - 19 countries (AT, BE, CY, DE, EE, ES, FI, FR, GR, IE, IT, LT, LU, LV, MT, NL, PT, SI, SK, QR, QV, QY)"
cap label var EA20 "Euro area - 20 countries (AT, BE, CY, DE, EE, ES, FI, FR, GR, HR, IE, IT, LT, LU, LV, MT, NL, PT, SI, SK)"
cap label var EA20_EXTRA "Extra-euro area - 20 countries (= 'WORLD' - 'EA20_INTRA')"
cap label var EA20_INTRA "Intra-euro area - 20 countries (AT, BE, CY, DE, EE, ES, FI, FR, GR, HR, IE, IT, LT, LU, LV, MT, NL, PT, SI, SK, QR, QV, QY)"
cap label var EA_EXTRA "Extra-euro area (= 'WORLD' - 'EA_INTRA')"
cap label var EA_INTRA "Intra-euro area (AT-01/1999, BE-01/1999, CY-01/2008, DE-01/1999, EE-01/2011, ES-01/1999, FI-01/1999, FR-01/1999, GR-01/2001, HR-01/2023, IE-01/1999, IT-01/1999, LT-01/2015, LU-01/1999, LV-01/2014, MT-01/2008, NL-01/1999, PT-01/1999, SI-01/2007, SK-01/2009, QR-01/1999, QV-01/1999, QY-01/1999)"
cap label var EC "Ecuador"
cap label var EE "Estonia"
cap label var EG "Egypt"
cap label var EH "Western Sahara(2013-2500);Ceuta and Melilla, Spanish Sahara(1976-1976)"
cap label var ER "Eritrea"
cap label var ES "Spain (incl. Canary Islands 'XB' from 1997)"
cap label var ET "Ethiopia (incl. Eritrea 'ER' -> 1993)"
cap label var EU "European Union (AT-01/1995, BE-01/1958, BG-01/2007, CY-05/2004, CZ-05/2004, DE-01/1958, DK-01/1973, EE-05/2004, ES-01/1986, FI-01/1995, FR-01/1958, GB-01/1973->01/2020, GR-01/1981, HR-07/2013, HU-05/2004, IE-01/1973, IT-01/1958, LT-05/2004, LU-01/1958, LV-05/2004, MT-05/2004, NL-01/1958, PL-05/2004, PT-01/1986, RO-01/2007, SE-01/1995, SI-05/2004, SK-05/2004)"
cap label var EU27_2020 "European Union - 27 countries (AT, BE, BG, CY, CZ, DE, DK, EE, ES, FI, FR, GR, HR, HU, IE, IT, LT, LU, LV, MT, NL, PL, PT, RO, SE, SI, SK)"
cap label var EU27_2020_EXTRA "Extra-EU27 (= 'WORLD' - 'EU27_2020_INTRA')"
cap label var EU27_2020_INTRA "Intra-EU27 (AT, BE, BG, CY, CZ, DE, DK, EE, ES, FI, FR, GR, HR, HU, IE, IT, LT, LU, LV, MT, NL, PL, PT, RO, SE, SI, SK, QR, QV, QY)"
cap label var EU28 "European Union - 28 countries (AT, BE, BG, CY, CZ, DE, DK, EE, ES, FI, FR, GB, GR, HR, HU, IE, IT, LT, LU, LV, MT, NL, PL, PT, RO, SE, SI, SK)"
cap label var EU28_EXTRA "Extra-EU28 (= 'WORLD' - 'EU28_INTRA')"
cap label var EU28_INTRA "Intra-EU28 (AT, BE, BG, CY, CZ, DE, DK, EE, ES, FI, FR, GB, GR, HR, HU, IE, IT, LT, LU, LV, MT, NL, PL, PT, RO, SE, SI, SK, QR, QV, QY)"
cap label var EUROZONE "Euro area (AT-01/1999, BE-01/1999, CY-01/2008, DE-01/1999, EE-01/2011, ES-01/1999, FI-01/1999, FR-01/1999, GR-01/2001, HR-01/2023, IE-01/1999, IT-01/1999, LT-01/2015, LU-01/1999, LV-01/2014, MT-01/2008, NL-01/1999, PT-01/1999, SI-01/2007, SK-01/2009)"
cap label var EUROZONE_EXTRA "Extra-euro area (= 'WORLD' - 'EUROZONE_INTRA')"
cap label var EUROZONE_INTRA "Intra-euro area (AT-01/1999, BE-01/1999, CY-01/2008, DE-01/1999, EE-01/2011, ES-01/1999, FI-01/1999, FR-01/1999, GR-01/2001, HR-01/2023, IE-01/1999, IT-01/1999, LT-01/2015, LU-01/1999, LV-01/2014, MT-01/2008, NL-01/1999, PT-01/1999, SI-01/2007, SK-01/2009, QR-01/1999, QV-01/1999, QY-01/1999)"
cap label var EU_EXTRA "Extra-EU (= 'WORLD' - 'EU_INTRA')"
cap label var EU_INTRA "Intra-EU (AT-01/1995, BE-01/1958, BG-01/2007, CY-05/2004, CZ-05/2004, DE-01/1958, DK-01/1973, EE-05/2004, ES-01/1986, FI-01/1995, FR-01/1958, GB-01/1973->01/2020, GR-01/1981, HR-07/2013, HU-05/2004, IE-01/1973, IT-01/1958, LT-05/2004, LU-01/1958, LV-05/2004, MT-05/2004, NL-01/1958, PL-05/2004, PT-01/1986, RO-01/2007, SE-01/1995, SI-05/2004, SK-05/2004, QR-01/1993, QV-01/1993, QY-01/1988)"
cap label var EXT_EA "Extra-euro area"
cap label var EXT_EA19 "Extra-euro area - 19 countries (from 2015)"
cap label var EXT_EA20 "Extra-euro area - 20 countries (from 2023)"
cap label var EXT_EU "Extra-EU"
cap label var EXT_EU27_2020 "Extra-EU27 (from 2020)"
cap label var FI "Finland"
cap label var FJ "Fiji"
cap label var FK "Falkland Islands (Malvinas)"
cap label var FM "Micronesia, Federated States of"
cap label var FO "Faroe Islands"
cap label var FR "France (incl. Saint Barthélemy 'BL' -> 2012; incl. French Guiana 'GF', Guadeloupe 'GP', Martinique 'MQ', Réunion 'RE' from 1997; incl. Mayotte 'YT' from 2014)"
cap label var GA "Gabon"
cap label var GB "United Kingdom"
cap label var GD "Grenada"
cap label var GE "Georgia"
cap label var GF "French Guiana"
cap label var GH "Ghana"
cap label var GI "Gibraltar"
cap label var GL "Greenland"
cap label var GM "Gambia"
cap label var GN "Guinea"
cap label var GP "Guadeloupe"
cap label var GQ "Equatorial Guinea"
cap label var GR "Greece"
cap label var GS "South Georgia and South Sandwich Islands"
cap label var GT "Guatemala"
cap label var GU "Guam"
cap label var GW "Guinea-Bissau"
cap label var GY "Guyana"
cap label var HK "Hong Kong"
cap label var HM "Heard Island and McDonald Islands"
cap label var HN "Honduras"
cap label var HR "Croatia"
cap label var HT "Haiti"
cap label var HU "Hungary"
cap label var ID "Indonesia (incl. East Timor 'TP' from 1977 -> 2000)"
cap label var IE "Ireland (Eire)"
cap label var IL "Israel (incl. West Bank and Gaza Strip 'XP' -> 1994)"
cap label var IN "India"
cap label var INT_EA "Intra-euro area"
cap label var INT_EA19 "Intra-euro area - 19 countries (from 2015)"
cap label var INT_EA20 "Intra-euro area - 20 countries (from 2023)"
cap label var INT_EU "Intra-EU"
cap label var INT_EU27_2020 "Intra-EU27 (from 2020)"
cap label var IO "British Indian Ocean Territory"
cap label var IQ "Iraq"
cap label var IR "Iran, Islamic Republic of"
cap label var IS "Iceland"
cap label var IT "Italy (incl. San Marino 'SM' -> 1993)"
cap label var JM "Jamaica"
cap label var JO "Jordan"
cap label var JP "Japan"
cap label var KE "Kenya"
cap label var KG "Kyrgyzstan"
cap label var KH "Cambodia"
cap label var KI "Kiribati (incl. Solomon Islands 'SB', Tuvalu 'TV' -> 1979; incl. Pitcairn 'PN' -> 1980)"
cap label var KM "Comoros (incl. Mayotte 'YT' -> 1976)"
cap label var KN "St Kitts and Nevis"
cap label var KP "Korea, Democratic People’s Republic of (North Korea)"
cap label var KR "Korea, Republic of (South Korea)"
cap label var KW "Kuwait"
cap label var KY "Cayman Islands"
cap label var KZ "Kazakhstan"
cap label var LA "Lao People’s Democratic Republic (Laos)"
cap label var LB "Lebanon"
cap label var LC "St Lucia"
cap label var LI "Liechtenstein"
cap label var LK "Sri Lanka"
cap label var LR "Liberia"
cap label var LS "Lesotho"
cap label var LT "Lithuania"
cap label var LU "Luxembourg"
cap label var LV "Latvia"
cap label var LY "Libya"
cap label var MA "Morocco"
cap label var MD "Moldova, Republic of"
cap label var ME "Montenegro"
cap label var MG "Madagascar"
cap label var MH "Marshall Islands"
cap label var MK "North Macedonia"
cap label var ML "Mali"
cap label var MM "Myanmar (Burma)"
cap label var MN "Mongolia"
cap label var MO "Macao"
cap label var MP "Northern Mariana Islands"
cap label var MQ "Martinique"
cap label var MR "Mauritania (incl. Spanish Sahara from 1977)"
cap label var MS "Montserrat"
cap label var MT "Malta"
cap label var MU "Mauritius"
cap label var MV "Maldives"
cap label var MW "Malawi"
cap label var MX "Mexico"
cap label var MY "Malaysia"
cap label var MZ "Mozambique"
cap label var NA "Namibia"
cap label var NC "New Caledonia"
cap label var NE "Niger"
cap label var NF "Norfolk Island"
cap label var NG "Nigeria"
cap label var NI "Nicaragua"
cap label var NL "Netherlands"
cap label var NO "Norway (incl. Svalbard and Jan Mayen 'SJ' -> 1994 and again from 1997)"
cap label var NP "Nepal"
cap label var NR "Nauru"
cap label var NU "Niue"
cap label var NZ "New Zealand"
cap label var OM "Oman"
cap label var PA "Panama (incl. Panama Canal Zone 'PZ' from 1981)"
cap label var PE "Peru"
cap label var PF "French Polynesia"
cap label var PG "Papua New Guinea"
cap label var PH "Philippines"
cap label var PK "Pakistan"
cap label var PL "Poland"
cap label var PM "St Pierre and Miquelon"
cap label var PN "Pitcairn"
cap label var PS "Occupied Palestinian Territory (West Bank (incl. East Jerusalem) and Gaza Strip)"
cap label var PT "Portugal"
cap label var PW "Palau"
cap label var PY "Paraguay"
cap label var PZ "Panama Canal Zone"
cap label var QA "Qatar"
cap label var QP "High seas"
cap label var QQ "Stores and provisions"
cap label var QR "Stores and provisions within the framework of intra-Union trade"
cap label var QS "Stores and provisions within the framework of extra-Union trade"
cap label var QT "West Indies (incl. Dominica 'DM', St Lucia 'LC', St Vincent and the Grenadines 'VC' -> 1979; incl. Antigua and Barbuda 'AG' -> 1982; incl. St Kitts and Nevis 'KN' -> 1985)"
cap label var QU "Countries and territories not specified"
cap label var QV "Countries and territories not specified within the framework of intra-Union trade"
cap label var QW "Countries and territories not specified within the framework of extra-Union trade"
cap label var QX "Countries and territories not specified for commercial or military reasons"
cap label var QY "Countries and territories not specified for commercial or military reasons in the framework of intra-Union trade"
cap label var QZ "Countries and territories not specified for commercial or military reasons in the framework of extra-Union trade"
cap label var RE "Réunion"
cap label var RO "Romania"
cap label var RU "Russian Federation (Russia)"
cap label var RW "Rwanda"
cap label var SA "Saudi Arabia"
cap label var SB "Solomon Islands"
cap label var SC "Seychelles"
cap label var SD "Sudan (incl. South Sudan 'SS' -> 2012)"
cap label var SE "Sweden"
cap label var SG "Singapore"
cap label var SH "Saint Helena, Ascension and Tristan da Cunha"
cap label var SI "Slovenia"
cap label var SJ "Svalbard and Jan Mayen"
cap label var SK "Slovakia"
cap label var SL "Sierra Leone"
cap label var SM "San Marino"
cap label var SN "Senegal"
cap label var SO "Somalia"
cap label var SR "Suriname"
cap label var SS "South Sudan"
cap label var ST "Sao Tome and Principe"
cap label var SU "Soviet Union"
cap label var SV "El Salvador"
cap label var SX "Sint Maarten (Dutch part)"
cap label var SY "Syrian Arab Republic (Syria)"
cap label var SZ "Eswatini (Ngwane)"
cap label var TC "Turks and Caicos Islands"
cap label var TD "Chad"
cap label var TF "French Southern Territories"
cap label var TG "Togo"
cap label var TH "Thailand"
cap label var TJ "Tajikistan"
cap label var TK "Tokelau"
cap label var TL "Timor-Leste"
cap label var TM "Turkmenistan"
cap label var TN "Tunisia"
cap label var TO "Tonga"
cap label var TP "East Timor(2001-2002);Portuguese Timor(1976-1976)"
cap label var TR "Türkiye"
cap label var TT "Trinidad and Tobago"
cap label var TV "Tuvalu"
cap label var TW "Taiwan"
cap label var TZ "Tanzania, United Republic of"
cap label var UA "Ukraine"
cap label var UG "Uganda"
cap label var UM "United States Minor Outlying Islands"
cap label var US "United States (incl. Navassa Island (part of 'UM') from 1995 -> 2000)"
cap label var UY "Uruguay"
cap label var UZ "Uzbekistan"
cap label var VA "Holy See (Vatican City State)"
cap label var VC "St Vincent and the Grenadines"
cap label var VD "North Viet Nam"
cap label var VE "Venezuela, Bolivarian Republic of"
cap label var VG "Virgin Islands, British (incl. Montserrat 'MS' -> 1994)"
cap label var VI "Virgin Islands, United States"
cap label var VN "Viet Nam (incl. North Viet Nam 'VD' from 1977)"
cap label var VU "Vanuatu"
cap label var WF "Wallis and Futuna"
cap label var WORLD "All countries of the world"
cap label var WS "Samoa"
cap label var XA "American Oceania (incl. Federated States of Micronesia 'FM', Marshall Islands 'MH' -> 1991; incl. Northern Mariana Islands 'MP' -> 1993; incl. Palau 'PW', Navassa Island (part of 'UM') -> 1994)"
cap label var XB "Canary Islands"
cap label var XC "Ceuta (incl. Melilla 'XL' -> 1998)"
cap label var XI "United Kingdom (Northern Ireland)"
cap label var XK "Kosovo"
cap label var XL "Melilla"
cap label var XM "Montenegro"
cap label var XO "Australian Oceania"
cap label var XP "West Bank (incl. East Jerusalem) and Gaza Strip"
cap label var XR "Polar regions"
cap label var XS "Serbia"
cap label var XU "United Kingdom (excluding Northern Ireland)"
cap label var XZ "New Zealand Oceania"
cap label var YD "South Yemen"
cap label var YE "Yemen (incl. South Yemen 'YD' from 1991)"
cap label var YT "Mayotte"
cap label var YU "Yugoslavia (incl. Bosnia and Herzegovina 'BA', Croatia 'HR', Slovenia 'SI' -> 1991; incl. North Macedonia 'MK' -> 1992)"
cap label var ZA "South Africa (incl. Namibia 'NA' -> 1989)"
cap label var ZM "Zambia"
cap label var ZW "Zimbabwe"
