cap label var CODE "Label - English"
cap label var TAXI "Taxi"
cap label var TRA "Transport"
cap label var RENT_ACCOM "Renting out accommodation"
cap label var SELL_GD "Good selling"
cap label var CLE_HNWRK "Cleaning and handiwork"
cap label var CH_ELD_CARE "Child and elderly care"
cap label var MED_HLTH_CARE "Medical and health care"
cap label var TUT_TEACH "Tutoring and teaching"
cap label var TRANSL "Translation"
cap label var IT "IT"
cap label var SUPP_ONLN "Online support or checks for online content"
cap label var CREA_CONT "Creating contents such as videos or texts"
cap label var OTH "Other"
