cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var VH_H "Very high or high"
cap label var VHIGH "Very high"
cap label var HIGH "High"
cap label var SOME "Some"
cap label var LOW_NONE "Low or none"
cap label var LOW "Low"
cap label var NONE "None"
cap label var NRP "No response"
