cap label var CODE "Label - English"
cap label var PSY "Psychological"
cap label var THRT "Threats"
cap label var PHY "Physical"
cap label var PHY_THRT "Physical (including threats)"
cap label var PHY_THRT_NSX "Physical (including threats and not sexual)"
cap label var PHY_SX "Physical or sexual"
cap label var SX "Sexual"
cap label var RAPE "Rape"
cap label var PHY_THRT_SX "Physical (including threats) or sexual"
cap label var PSY_PHY_THRT_SX "Psychological, physical (including threats) or sexual"
cap label var PSY_THRT "Psychological or threats"
cap label var SXH_WRK "Sexual harassment at work"
cap label var MSG "Violence using messaging apps"
cap label var SM "Violence using social media"
cap label var OTL "Violence using online tools"
cap label var NOTL "Violence not using online tools"
cap label var PHY_PSY "Physical or psychological"
