cap label var PUB "Public schools and colleges"
cap label var UNIV "Universities and other higher education establishments"
cap label var PUTR "Public training institutions (financed or guided by the government; e.g. adult education centres)"
cap label var SPEC "Specialised training institutions"
cap label var PRALL "Private training organisations"
cap label var PRIV "Private companies whose main activity is not training"
cap label var EQUIP "Equipment suppliers"
cap label var PAR "Parent/associate companies"
cap label var UNION "Unions"
cap label var CHOC "Chambers of commerce, sector bodies, employers' organisations"
cap label var OTH "Other providers"
cap label var NRESP "No response"
cap label var FEDINST "Formal education institution"
cap label var NFEINST "Non formal education and training institutions"
cap label var COMINST "Commercial institution where education and training is not the main activity (e.g. equipment suppliers)"
cap label var EMPL "Employer"
cap label var CHACOM "Employers' organisations, chambers of commerce"
cap label var TRDINST "Trade unions"
cap label var NONPROF "Non-profit associations (e.g. cultural society, political party)"
cap label var INDIV "Individuals (e.g. students giving private lessons)"
cap label var NONCOM "Non commercial instituion where ET is not the main activity (e.g. libraries, museums, ministers)"
cap label var OTHER "Other"
