cap label var _11 "Agriculture, forestry, fishing, food, beverages, tobacco;  Goods"
cap label var _111 "Agriculture, forestry, fishing, food, beverages, tobacco;  Goods;  Intermediate consumption"
cap label var _111100 "Agriculture, forestry, fishing, food, beverages, tobacco; Goods; Intermediate consumption; Primary"
cap label var _111210 "Agriculture, forestry, fishing, food, beverages, tobacco; Goods; Intermediate consumption; Processed; Generic"
cap label var _111220 "Agriculture, forestry, fishing, food, beverages, tobacco; Goods; Intermediate consumption; Processed; Specific"
cap label var _111XXX "Agriculture, forestry, fishing, food, beverages, tobacco; Goods; Intermediate consumption; Not elsewhere specified"
cap label var _112 "Agriculture, forestry, fishing, food, beverages, tobacco;  Goods;  Gross fixed capital formation"
cap label var _112010 "Agriculture, forestry, fishing, food, beverages, tobacco; Goods; Gross fixed capital formation; Generic"
cap label var _112020 "Agriculture, forestry, fishing, food, beverages, tobacco; Goods; Gross fixed capital formation; Specific"
cap label var _113 "Agriculture, forestry, fishing, food, beverages, tobacco;  Goods;  Final consumption"
cap label var _113101 "Agriculture, forestry, fishing, food, beverages, tobacco; Goods; Final consumption; Primary; Non-durable"
cap label var _113102 "Agriculture, forestry, fishing, food, beverages, tobacco; Goods; Final consumption; Primary; Durable"
cap label var _113201 "Agriculture, forestry, fishing, food, beverages, tobacco; Goods; Final consumption; Processed; Non-durable"
cap label var _113202 "Agriculture, forestry, fishing, food, beverages, tobacco; Goods; Final consumption; Processed; Durable"
cap label var _113XXX "Agriculture, forestry, fishing, food, beverages, tobacco; Goods; Final consumption; Not elsewhere specified"
cap label var _114 "Agriculture, forestry, fishing, food, beverages, tobacco;  Goods;  Intermediate or final consumption"
cap label var _114100 "Agriculture, forestry, fishing, food, beverages, tobacco; Goods; Intermediate or final consumption; Primary"
cap label var _114200 "Agriculture, forestry, fishing, food, beverages, tobacco; Goods; Intermediate or final consumption; Processed"
cap label var _114XXX "Agriculture, forestry, fishing, food, beverages, tobacco; Goods; Intermediate or final consumption; Not elsewhere specified"
cap label var _115 "Agriculture, forestry, fishing, food, beverages, tobacco; Goods;  Intermediate consumption or gross fixed capital formation"
cap label var _115XXX "Agriculture, forestry, fishing, food, beverages, tobacco; Goods;  Intermediate consumption or gross fixed capital formation; Not elsewhere specified"
cap label var _11X "Agriculture, forestry, fishing, food, beverages, tobacco;  Goods;  Not elsewhere specified"
cap label var _11XXXX "Agriculture, forestry, fishing, food, beverages, tobacco; Goods; Not elsewhere specified"
cap label var _12 "Agriculture, forestry, fishing, food, beverages, tobacco;  Services"
cap label var _121 "Agriculture, forestry, fishing, food, beverages, tobacco;  Services;  Intermediate consumption"
cap label var _121010 "Agriculture, forestry, fishing, food, beverages, tobacco; Services; Intermediate consumption; Generic"
cap label var _121020 "Agriculture, forestry, fishing, food, beverages, tobacco; Services; Intermediate consumption; Specific"
cap label var _123 "Agriculture, forestry, fishing, food, beverages, tobacco;  Services;  Final consumption"
cap label var _123000 "Agriculture, forestry, fishing, food, beverages, tobacco; Services; Final consumption"
cap label var _21 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment;  Goods"
cap label var _211 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment;  Goods;  Intermediate consumption"
cap label var _211100 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Intermediate consumption; Primary"
cap label var _211210 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Intermediate consumption; Processed; Generic"
cap label var _211220 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Intermediate consumption; Processed; Specific"
cap label var _211XXX "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Intermediate consumption; Not elsewhere specified"
cap label var _212 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment;  Goods;  Gross fixed capital formation"
cap label var _212010 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Gross fixed capital formation; Generic"
cap label var _212020 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Gross fixed capital formation; Specific"
cap label var _212XXX "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Gross fixed capital formation; Not elsewhere specified"
cap label var _213 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment;  Goods;  Final consumption"
cap label var _213101 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Final consumption; Primary; Non-durable"
cap label var _213102 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Final consumption; Primary; Durable"
cap label var _213201 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Final consumption; Processed; Non-durable"
cap label var _213202 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Final consumption; Processed; Durable"
cap label var _213XXX "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Final consumption; Not elsewhere specified"
cap label var _214 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment;  Goods;  Intermediate or final consumption"
cap label var _214100 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Intermediate or final consumption; Primary"
cap label var _214200 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Intermediate or final consumption; Processed"
cap label var _214XXX "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Intermediate or final consumption; Not elsewhere specified"
cap label var _215 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment;  Goods;  Intermediate consumption or gross fixed capital formation"
cap label var _215010 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Intermediate consumption or gross fixed capital formation; Generic"
cap label var _215XXX "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment;  Goods;  Intermediate consumption or gross fixed capital formation; Not elsewhere specified"
cap label var _216 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment;  Goods;  Final consumption or gross fixed capital formation"
cap label var _216XXX "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment;  Goods;  Final consumption or gross fixed capital formation;  Not elsewhere specified"
cap label var _21X "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment;  Goods;  Not elsewhere specified"
cap label var _21XXXX "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Goods; Not elsewhere specified"
cap label var _22 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment;  Services"
cap label var _221 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment;  Services;  Intermediate consumption"
cap label var _221010 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Services; Intermediate consumption; Generic"
cap label var _221020 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Services; Intermediate consumption; Specific"
cap label var _223 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment;  Services;  Final consumption"
cap label var _223000 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment; Services; Final consumption"
cap label var _31 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture;  Goods"
cap label var _311 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture;  Goods;  Intermediate consumption"
cap label var _311100 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Intermediate consumption; Primary"
cap label var _311200 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Intermediate consumption; Processed"
cap label var _311210 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Intermediate consumption; Processed; Generic"
cap label var _311220 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Intermediate consumption; Processed; Specific"
cap label var _311XXX "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Intermediate consumption; Not elsewhere specified"
cap label var _312 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture;  Goods;  Gross fixed capital formation"
cap label var _312010 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Gross fixed capital formation; Generic"
cap label var _312020 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Gross fixed capital formation; Specific"
cap label var _312XXX "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Gross fixed capital formation; Not elsewhere specified"
cap label var _313 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture;  Goods;  Final consumption"
cap label var _313101 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Final consumption; Primary; Non-durable"
cap label var _313102 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Final consumption; Primary; Durable"
cap label var _313201 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Final consumption; Processed; Non-durable"
cap label var _313202 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Final consumption; Processed; Durable"
cap label var _313XXX "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Final consumption; Not elsewhere specified"
cap label var _314 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture;  Goods;  Intermediate or final consumption"
cap label var _314200 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Intermediate or final consumption; Processed"
cap label var _314XXX "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Intermediate or final consumption; Not elsewhere specified"
cap label var _315 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture;  Goods;  Intermediate consumption or gross fixed capital formation"
cap label var _315010 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Intermediate consumption or gross fixed capital formation; Generic"
cap label var _315XXX "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Intermediate consumption or gross fixed capital formation; Not elsewhere specified"
cap label var _316 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture;  Goods;  Final consumption or gross fixed capital formation"
cap label var _316XXX "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Final consumption or gross fixed capital formation; Not elsewhere specified"
cap label var _31X "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture;  Goods;  Not elsewhere specified"
cap label var _31XXXX "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Goods; Not elsewhere specified"
cap label var _32 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture;  Services"
cap label var _321 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture;  Services;  Intermediate consumption"
cap label var _321010 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Services; Intermediate consumption; Generic"
cap label var _321020 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Services; Intermediate consumption; Specific"
cap label var _323 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture;  Services;  Final consumption"
cap label var _323000 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture; Services; Final consumption"
cap label var _41 "Textile, apparel, shoes;  Goods"
cap label var _411 "Textile, apparel, shoes;  Goods;  Intermediate consumption"
cap label var _411100 "Textile, apparel, shoes; Goods; Intermediate consumption; Primary"
cap label var _411210 "Textile, apparel, shoes; Goods; Intermediate consumption; Processed; Generic"
cap label var _411220 "Textile, apparel, shoes; Goods; Intermediate consumption; Processed; Specific"
cap label var _411XXX "Textile, apparel, shoes; Goods; Intermediate consumption; Not elsewhere specified"
cap label var _412 "Textile, apparel, shoes;  Goods;  Gross fixed capital formation"
cap label var _412010 "Textile, apparel, shoes; Goods; Gross fixed capital formation; Generic"
cap label var _412020 "Textile, apparel, shoes; Goods; Gross fixed capital formation; Specific"
cap label var _413 "Textile, apparel, shoes;  Goods;  Final consumption"
cap label var _413101 "Textile, apparel, shoes; Goods; Final consumption; Primary; Non-durable"
cap label var _413102 "Textile, apparel, shoes; Goods; Final consumption; Primary; Durable"
cap label var _413201 "Textile, apparel, shoes; Goods; Final consumption; Processed; Non-durable"
cap label var _413202 "Textile, apparel, shoes; Goods; Final consumption; Processed; Durable"
cap label var _413XXX "Textile, apparel, shoes; Goods; Final consumption; Not elsewhere specified"
cap label var _414 "Textile, apparel, shoes;  Goods;  Intermediate or final consumption"
cap label var _414200 "Textile, apparel, shoes; Goods; Intermediate or final consumption; Processed"
cap label var _414XXX "Textile, apparel, shoes; Goods; Intermediate or final consumption; Not elsewhere specified"
cap label var _415 "Textile, apparel, shoes; Goods; Intermediate consumption or gross fixed capital formation"
cap label var _415XXX "Textile, apparel, shoes; Goods; Intermediate consumption or gross fixed capital formation; Not elsewhere specified"
cap label var _416 "Textile, apparel, shoes;  Goods;  Final consumption or gross fixed capital formation"
cap label var _416XXX "Textile, apparel, shoes; Goods; Final consumption or gross fixed capital formation; Not elsewhere specified"
cap label var _41X "Textile, apparel, shoes;  Goods;  Not elsewhere specified"
cap label var _41XXXX "Textile, apparel, shoes; Goods; Not elsewhere specified"
cap label var _42 "Textile, apparel, shoes;  Services"
cap label var _421 "Textile, apparel, shoes;  Services;  Intermediate consumption"
cap label var _421010 "Textile, apparel, shoes; Services; Intermediate consumption; Generic"
cap label var _421020 "Textile, apparel, shoes; Services; Intermediate consumption; Specific"
cap label var _423 "Textile, apparel, shoes;  Services;  Final consumption"
cap label var _423000 "Textile, apparel, shoes; Services; Final consumption"
cap label var _51 "Transport equipment and services, travel, postal services;  Goods"
cap label var _511 "Transport equipment and services, travel, postal services;  Goods;  Intermediate consumption"
cap label var _511100 "Transport equipment and services, travel, postal services; Goods; Intermediate consumption; Primary"
cap label var _511200 "Transport equipment and services, travel, postal services; Goods; Intermediate consumption; Processed"
cap label var _511210 "Transport equipment and services, travel, postal services; Goods; Intermediate consumption; Processed; Generic"
cap label var _511220 "Transport equipment and services, travel, postal services; Goods; Intermediate consumption; Processed; Specific"
cap label var _511XXX "Transport equipment and services, travel, postal services; Goods; Intermediate consumption; Not elsewhere specified"
cap label var _512 "Transport equipment and services, travel, postal services;  Goods;  Gross fixed capital formation"
cap label var _512010 "Transport equipment and services, travel, postal services; Goods; Gross fixed capital formation; Generic"
cap label var _512020 "Transport equipment and services, travel, postal services; Goods; Gross fixed capital formation; Specific"
cap label var _512XXX "Transport equipment and services, travel, postal services; Goods; Gross fixed capital formation; Not elsewhere specified"
cap label var _513 "Transport equipment and services, travel, postal services;  Goods;  Final consumption"
cap label var _513101 "Transport equipment and services, travel, postal services; Goods; Final consumption; Primary; Non-durable"
cap label var _513102 "Transport equipment and services, travel, postal services; Goods; Final consumption; Primary; Durable"
cap label var _513201 "Transport equipment and services, travel, postal services; Goods; Final consumption; Processed; Non-durable"
cap label var _513202 "Transport equipment and services, travel, postal services; Goods; Final consumption; Processed; Durable"
cap label var _513XXX "Transport equipment and services, travel, postal services; Goods; Final consumption; Not elsewhere specified"
cap label var _514 "Transport equipment and services, travel, postal services;  Goods;  Intermediate or final consumption"
cap label var _514200 "Transport equipment and services, travel, postal services; Goods; Intermediate or final consumption; Processed"
cap label var _514XXX "Transport equipment and services, travel, postal services;  Goods;  Intermediate or final consumption; Not elsewhere specified"
cap label var _515 "Transport equipment and services, travel, postal services;  Goods;  Intermediate consumption or gross fixed capital formation"
cap label var _515020 "Transport equipment and services, travel, postal services; Goods; Intermediate consumption or gross fixed capital formation; Specific"
cap label var _515XXX "Transport equipment and services, travel, postal services; Goods; Intermediate consumption or gross fixed capital formation; Not elsewhere specified"
cap label var _516 "Transport equipment and services, travel, postal services;  Goods;  Final consumption or gross fixed capital formation"
cap label var _516XXX "Transport equipment and services, travel, postal services; Goods; Final consumption or gross fixed capital formation; Not elsewhere specified"
cap label var _51X "Transport equipment and services, travel, postal services;  Goods;  Not elsewhere specified"
cap label var _51XXXX "Transport equipment and services, travel, postal services; Goods; Not elsewhere specified"
cap label var _52 "Transport equipment and services, travel, postal services;  Services"
cap label var _521 "Transport equipment and services, travel, postal services;  Services;  Intermediate consumption"
cap label var _521010 "Transport equipment and services, travel, postal services; Services; Intermediate consumption; Generic"
cap label var _521020 "Transport equipment and services, travel, postal services; Services; Intermediate consumption; Specific"
cap label var _523 "Transport equipment and services, travel, postal services;  Services;  Final consumption"
cap label var _523000 "Transport equipment and services, travel, postal services; Services; Final consumption"
cap label var _61 "ICT, media, computers, business and financial services;  Goods"
cap label var _611 "ICT, media, computers, business and financial services;  Goods;  Intermediate consumption"
cap label var _611100 "ICT, media, computers, business and financial services; Goods; Intermediate consumption; Primary"
cap label var _611210 "ICT, media, computers, business and financial services; Goods; Intermediate consumption; Processed; Generic"
cap label var _611220 "ICT, media, computers, business and financial services; Goods; Intermediate consumption; Processed; Specific"
cap label var _611XXX "ICT, media, computers, business and financial services; Goods; Intermediate consumption; Not elsewhere specified"
cap label var _612 "ICT, media, computers, business and financial services;  Goods;  Gross fixed capital formation"
cap label var _612010 "ICT, media, computers, business and financial services; Goods; Gross fixed capital formation; Generic"
cap label var _612020 "ICT, media, computers, business and financial services; Goods; Gross fixed capital formation; Specific"
cap label var _612XXX "ICT, media, computers, business and financial services; Goods; Gross fixed capital formation; Not elsewhere specified"
cap label var _613 "ICT, media, computers, business and financial services;  Goods;  Final consumption"
cap label var _613101 "ICT, media, computers, business and financial services; Goods; Final consumption; Primary; Non-durable"
cap label var _613102 "ICT, media, computers, business and financial services; Goods; Final consumption; Primary; Durable"
cap label var _613201 "ICT, media, computers, business and financial services; Goods; Final consumption; Processed; Non-durable"
cap label var _613202 "ICT, media, computers, business and financial services; Goods; Final consumption; Processed; Durable"
cap label var _613XXX "ICT, media, computers, business and financial services; Goods; Final consumption; Not elsewhere specified"
cap label var _614 "ICT, media, computers, business and financial services;  Goods;  Intermediate or final consumption"
cap label var _614100 "ICT, media, computers, business and financial services; Goods; Intermediate or final consumption; Primary"
cap label var _614200 "ICT, media, computers, business and financial services; Goods; Intermediate or final consumption; Processed"
cap label var _614XXX "ICT, media, computers, business and financial services; Goods; Intermediate or final consumption; Not elsewhere specified"
cap label var _615 "ICT, media, computers, business and financial services;  Goods;  Intermediate consumption or gross fixed capital formation"
cap label var _615010 "ICT, media, computers, business and financial services; Goods; Intermediate consumption or gross fixed capital formation; Generic"
cap label var _615020 "ICT, media, computers, business and financial services; Goods; Intermediate consumption or gross fixed capital formation; Specific"
cap label var _615XXX "ICT, media, computers, business and financial services; Goods; Intermediate consumption or gross fixed capital formation; Not elsewhere specified"
cap label var _616 "ICT, media, computers, business and financial services;  Goods;  Final consumption or gross fixed capital formation"
cap label var _616XXX "ICT, media, computers, business and financial services; Goods; Final consumption or gross fixed capital formation; Not elsewhere specified"
cap label var _61X "ICT, media, computers, business and financial services;  Goods;  Not elsewhere specified"
cap label var _61XXXX "ICT, media, computers, business and financial services; Goods; Not elsewhere specified"
cap label var _62 "ICT, media, computers, business and financial services;  Services"
cap label var _621 "ICT, media, computers, business and financial services;  Services;  Intermediate consumption"
cap label var _621010 "ICT, media, computers, business and financial services; Services; Intermediate consumption; Generic"
cap label var _621020 "ICT, media, computers, business and financial services; Services; Intermediate consumption; Specific"
cap label var _623 "ICT, media, computers, business and financial services;  Services;  Final consumption"
cap label var _623000 "ICT, media, computers, business and financial services; Services; Final consumption"
cap label var _71 "Health, pharmaceuticals, education, cultural, sport;  Goods"
cap label var _711 "Health, pharmaceuticals, education, cultural, sport;  Goods;  Intermediate consumption"
cap label var _711100 "Health, pharmaceuticals, education, cultural, sport; Goods; Intermediate consumption; Primary"
cap label var _711210 "Health, pharmaceuticals, education, cultural, sport; Goods; Intermediate consumption; Processed; Generic"
cap label var _711220 "Health, pharmaceuticals, education, cultural, sport; Goods; Intermediate consumption; Processed; Specific"
cap label var _711XXX "Health, pharmaceuticals, education, cultural, sport; Goods; Intermediate consumption; Not elsewhere specified"
cap label var _712 "Health, pharmaceuticals, education, cultural, sport;  Goods;  Gross fixed capital formation"
cap label var _712010 "Health, pharmaceuticals, education, cultural, sport; Goods; Gross fixed capital formation; Generic"
cap label var _712020 "Health, pharmaceuticals, education, cultural, sport; Goods; Gross fixed capital formation; Specific"
cap label var _712XXX "Health, pharmaceuticals, education, cultural, sport; Goods; Gross fixed capital formation; Not elsewhere specified"
cap label var _713 "Health, pharmaceuticals, education, cultural, sport;  Goods;  Final consumption"
cap label var _713101 "Health, pharmaceuticals, education, cultural, sport; Goods; Final consumption; Primary; Non-durable"
cap label var _713102 "Health, pharmaceuticals, education, cultural, sport; Goods; Final consumption; Primary; Durable"
cap label var _713201 "Health, pharmaceuticals, education, cultural, sport; Goods; Final consumption; Processed; Non-durable"
cap label var _713202 "Health, pharmaceuticals, education, cultural, sport; Goods; Final consumption; Processed; Durable"
cap label var _713XXX "Health, pharmaceuticals, education, cultural, sport; Goods; Final consumption; Not elsewhere specified"
cap label var _714 "Health, pharmaceuticals, education, cultural, sport;  Goods;  Intermediate or final consumption"
cap label var _714100 "Health, pharmaceuticals, education, cultural, sport; Goods; Intermediate or final consumption; Primary"
cap label var _714200 "Health, pharmaceuticals, education, cultural, sport; Goods; Intermediate or final consumption; Processed"
cap label var _714XXX "Health, pharmaceuticals, education, cultural, sport; Goods; Intermediate or final consumption; Not elsewhere specified"
cap label var _715 "Health, pharmaceuticals, education, cultural, sport;  Goods;  Intermediate consumption or gross fixed capital formation"
cap label var _715020 "Health, pharmaceuticals, education, cultural, sport; Goods; Intermediate consumption or gross fixed capital formation; Specific"
cap label var _715XXX "Health, pharmaceuticals, education, cultural, sport;  Goods;  Intermediate consumption or gross fixed capital formation; Not elsewhere specified"
cap label var _716 "Health, pharmaceuticals, education, cultural, sport;  Goods;  Final consumption or gross fixed capital formation"
cap label var _716XXX "Health, pharmaceuticals, education, cultural, sport; Goods; Final consumption or gross fixed capital formation; Not elsewhere specified"
cap label var _71X "Health, pharmaceuticals, education, cultural, sport;  Goods;  Not elsewhere specified"
cap label var _71XXXX "Health, pharmaceuticals, education, cultural, sport; Goods; Not elsewhere specified"
cap label var _72 "Health, pharmaceuticals, education, cultural, sport;  Services"
cap label var _721 "Health, pharmaceuticals, education, cultural, sport;  Services;  Intermediate consumption"
cap label var _721010 "Health, pharmaceuticals, education, cultural, sport; Services; Intermediate consumption; Generic"
cap label var _721020 "Health, pharmaceuticals, education, cultural, sport; Services; Intermediate consumption; Specific"
cap label var _723 "Health, pharmaceuticals, education, cultural, sport;  Services;  Final consumption"
cap label var _723000 "Health, pharmaceuticals, education, cultural, sport; Services; Final consumption"
cap label var _81 "Government, military and other;  Goods"
cap label var _811 "Government, military and other;  Goods;  Intermediate consumption"
cap label var _811100 "Government, military and other; Goods; Intermediate consumption; Primary"
cap label var _811210 "Government, military and other; Goods; Intermediate consumption; Processed; Generic"
cap label var _811220 "Government, military and other; Goods; Intermediate consumption; Processed; Specific"
cap label var _811XXX "Government, military and other; Goods; Intermediate consumption; Not elsewhere specified"
cap label var _812 "Government, military and other;  Goods;  Gross fixed capital formation"
cap label var _812010 "Government, military and other; Goods; Gross fixed capital formation; Generic"
cap label var _812020 "Government, military and other; Goods; Gross fixed capital formation; Specific"
cap label var _813 "Government, military and other;  Goods;  Final consumption"
cap label var _813101 "Government, military and other; Goods; Final consumption; Primary; Non-durable"
cap label var _813102 "Government, military and other; Goods; Final consumption; Primary; Durable"
cap label var _813201 "Government, military and other; Goods; Final consumption; Processed; Non-durable"
cap label var _813202 "Government, military and other; Goods; Final consumption; Processed; Durable"
cap label var _814 "Government, military and other;  Goods;  Intermediate or final consumption"
cap label var _814200 "Government, military and other; Goods; Intermediate or final consumption; Processed"
cap label var _814XXX "Government, military and other; Goods; Intermediate or final consumption; Not elsewhere specified"
cap label var _815 "Government, military and other;  Goods;  Intermediate consumption or gross fixed capital formation"
cap label var _815020 "Government, military and other; Goods; Intermediate consumption or gross fixed capital formation; Specific"
cap label var _815XXX "Government, military and other;  Goods;  Intermediate consumption or gross fixed capital formation; Not elsewhere specified"
cap label var _816 "Government, military and other;  Goods;  Final consumption or gross fixed capital formation"
cap label var _816XXX "Government, military and other; Goods; Final consumption or gross fixed capital formation; Not elsewhere specified"
cap label var _81X "Government, military and other;  Goods;  Not elsewhere specified"
cap label var _81XXXX "Government, military and other; Goods; Not elsewhere specified"
cap label var _82 "Government, military and other;  Services"
cap label var _821 "Government, military and other;  Services;  Intermediate consumption"
cap label var _821010 "Government, military and other; Services; Intermediate consumption; Generic"
cap label var _821020 "Government, military and other; Services; Intermediate consumption; Specific"
cap label var _823 "Government, military and other;  Services;  Final consumption"
cap label var _823000 "Government, military and other; Services; Final consumption"
cap label var TOTAL "Total"
cap label var X1 "Goods not elsewhere specified"
cap label var X11 "Goods not elsewhere specified; Intermediate consumption"
cap label var X11XXX "Goods not elsewhere specified;Intermediate consumption"
cap label var X12 "Goods not elsewhere specified;  Gross fixed capital formation"
cap label var X12XXX "Goods not elsewhere specified; Gross fixed capital formation"
cap label var X13 "Goods not elsewhere specified;  Final consumption"
cap label var X13XXX "Goods not elsewhere specified; Final consumption"
cap label var X1X "Goods not elsewhere specified"
cap label var X1XXXX "Goods not elsewhere specified"
