cap label var CODE "Label - English"
cap label var SPR "Social protection benefits"
cap label var CASH "Cash benefits"
cap label var CASH_P "Periodic cash benefits"
cap label var CASH_P_PSICK "Periodic cash benefits - paid sick leave"
cap label var CASH_P_DIS_PEN "Periodic cash benefits - disability pension"
cap label var CASH_P_ERRC "Periodic cash benefits - early retirement benefit due to reduced capacity to work"
cap label var CASH_P_OLD_PEN "Periodic cash benefits - old age pension"
cap label var CASH_P_AOLD_PEN "Periodic cash benefits - anticipated old age pension"
cap label var CASH_P_PART_PEN "Periodic cash benefits - partial pension"
cap label var CASH_P_CARE "Periodic cash benefits - care allowance"
cap label var CASH_P_EH "Periodic cash benefits - economic integration of the handicapped"
cap label var CASH_P_SRV_PEN "Periodic cash benefits - survivors' pension"
cap label var CASH_P_MNTCHB "Periodic cash benefits - income maintenance in the event of childbirth"
cap label var CASH_P_PARL "Periodic cash benefits - parental leave"
cap label var CASH_P_FAM_ALL "Periodic cash benefits - family or child allowance"
cap label var CASH_P_UNE_FULL "Periodic cash benefits - full unemployment"
cap label var CASH_P_UNE_PART "Periodic cash benefits - partial unemployment"
cap label var CASH_P_ERLM "Periodic cash benefits - early retirement benefit for labour market reasons"
cap label var CASH_P_VT_ALL "Periodic cash benefits - vocational training allowance"
cap label var CASH_P_INC "Periodic cash benefits - income support"
cap label var CASH_P_OTH "Periodic cash benefits - other"
cap label var CASH_LUMP "Lump sum cash benefits"
cap label var CASH_LUMP_CARE "Lump sum cash benefits - care allowance"
cap label var CASH_LUMP_EH "Lump sum cash benefits - economic integration of the handicapped"
cap label var CASH_LUMP_DTH "Lump sum cash benefits - death grant"
cap label var CASH_LUMP_BRTH "Lump sum cash benefits - birth grant"
cap label var CASH_LUMP_PARL "Lump sum cash benefits - parental leave"
cap label var CASH_LUMP_VT_ALL "Lump sum cash benefits - vocational training allowance"
cap label var CASH_LUMP_RED_COMP "Lump sum cash benefits - redundancy compensation"
cap label var CASH_LUMP_OTH "Lump sum cash benefits - other"
cap label var KND "Benefits in kind"
cap label var KND_IN "Benefits in kind - in-patient care"
cap label var KND_IN_DPR "Benefits in kind - in-patient care direct provision"
cap label var KND_IN_REMB "Benefits in kind - in-patient care reimbursement"
cap label var KND_OUT "Benefits in kind - out-patient care"
cap label var KND_OUT_DPR_PHRM "Benefits in kind - out-patient care direct provision of pharmaceutical products"
cap label var KND_OUT_DPR_OTH "Benefits in kind - out-patient care other direct provision"
cap label var KND_OUT_REMB_PHRM "Benefits in kind - out-patient care reimbursement of pharmaceutical products"
cap label var KND_OUT_REMB_OTH "Benefits in kind - out-patient care other reimbursement"
cap label var KND_CHDC "Benefits in kind - child day care"
cap label var KND_ACCOM "Benefits in kind - accommodation"
cap label var KND_ASS_DT "Benefits in kind - assistance in carrying out daily tasks"
cap label var KND_REH "Benefits in kind - rehabilitation"
cap label var KND_FUNE "Benefits in kind - funeral expenses"
cap label var KND_HOM "Benefits in kind - home help"
cap label var KND_MOB "Benefits in kind - mobility and resettlement"
cap label var KND_VT "Benefits in kind - vocational training"
cap label var KND_PSJOB "Benefits in kind - placement services and job search assistance"
cap label var KND_RENT "Benefits in kind - rent"
cap label var KND_RENT_SHOU "Benefits in kind - rent - social housing"
cap label var KND_RENT_OTH "Benefits in kind - rent - other"
cap label var KND_OWN "Benefits in kind - benefit to owner-occupiers"
cap label var KND_REH_ABUS "Benefits on kind - rehabilitation of alcohol and drugs abusers"
cap label var KND_OTH "Benefits in kind - other"
