cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var VH_H "Very high or high"
cap label var VHIGH "Very high"
cap label var HIGH "High"
cap label var MED "Medium"
cap label var MOD "Moderate"
cap label var MOD_LOW "Moderate or low"
cap label var LOW "Low"
cap label var NMATCH "No match"
cap label var NONE "None"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
