cap label var CODE "Label - English"
cap label var CAP_HEAT "Installed thermal capacity"
cap label var CAP_HEAT_ABVTH "Installed thermal capacity above the minimum seasonal performance factor threshold"
cap label var ACT_FACT "Activity factor"
cap label var SPERF_FACT "Seasonal performance factor"
cap label var SPFPE_AVG "Average seasonal performance factor based on primary energy"
cap label var SPFPE_AVG_ABVTH "Average seasonal performance factor based on primary energy - systems above the threshold"
cap label var CLSUP_REN_SHR "Share of cooling supply - renewable"
cap label var CLDD_RED "Cooling degree days - Renewable Energy Directive"
cap label var CAP_CL_AVG_ABVTH "Average nominal cooling capacity - systems above the threshold"
cap label var CAP_CL_AVG_ABVTH_REN "Average nominal cooling capacity - systems above the threshold - renewable heat driven (absorption and adsorption)"
cap label var TIME_USE "Time usage"
cap label var AMBT_HEAT "Ambient heat"
cap label var TH_NRG_INP_HEAT "Thermal energy input to heat pumps"
cap label var ELC_INP_HEAT "Electricity input to heat pump"
cap label var CAP_NET_ELC "Net maximum electrical capacity"
cap label var CAP_NET_ELC_C "Net maximum electrical capacity - commissioned"
cap label var CAP_NET_ELC_DCM "Net maximum electrical capacity - decommissioned"
cap label var CAP_NET_ELC_AC "Net maximum electrical capacity - alternative current"
cap label var CAP_NET_ELC_DC "Net maximum electrical capacity - direct current"
cap label var SOL_COL_SURF "Solar collectors surface"
cap label var CAP_PRD "Production capacity"
cap label var CAP_PRD_STM_RFOR "Production capacity - steam reforming"
cap label var CAP_ST "Storage capacity"
cap label var CAP_GST "Gas storage capacity"
cap label var CAP_GST_DP_FD "Gas storage capacity - depleted oil and gas fields"
cap label var CAP_GST_AQUI "Gas storage capacity - aquifers"
cap label var CAP_GST_SC "Gas storage capacity - salt cavities"
cap label var CAP_GST_ABVG "Gas storage capacity - above ground"
cap label var CAP_GST_BLWG "Gas storage capacity - below ground"
cap label var CAP_GST_OTH "Gas storage capacity - other"
cap label var CAP_TRA "Transport capacity"
cap label var PO_GST "Gas storage - peak output"
cap label var PO_GST_DP_FD "Gas storage - peak output - depleted oil and gas fields"
cap label var PO_GST_AQUI "Gas storage - peak output - aquifers"
cap label var PO_GST_SC "Gas storage - peak output - salt cavities"
cap label var PO_GST_ABVG "Gas storage - peak output - above ground"
cap label var PO_GST_BLWG "Gas storage - peak output - below ground"
cap label var PO_GST_OTH "Gas storage - peak output - other"
cap label var PL "Peak load"
cap label var PCAP "Peak capacity"
cap label var LNGIT_RG "LNG import terminals - regasification capacity"
cap label var LNGIT_RG_ABVG "LNG import terminals - regasification capacity - above ground"
cap label var LNGIT_RG_BLWG "LNG import terminals - regasification capacity - below ground"
cap label var LNGIT_VP "LNG import terminals - vaporizers"
cap label var LNGIT_VP_ABVG "LNG import terminals - vaporizers - above ground"
cap label var LNGIT_VP_BLWG "LNG import terminals - vaporizers - below ground"
cap label var LNGIT_TRN "LNG import terminals - trains"
cap label var LNGIT_ST "LNG import terminals - storage capacity"
cap label var LNGIT_ST_ABVG "LNG import terminals - storage capacity - above ground"
cap label var LNGIT_ST_BLWG "LNG import terminals - storage capacity - below ground"
cap label var LNGIT_TNK "LNG import terminals - tanks"
cap label var LNGIT_TNK_ABVG "LNG import terminals - tanks - above ground"
cap label var LNGIT_TNK_BLWG "LNG import terminals - tanks - below ground"
cap label var LNGIT_PO "LNG import terminals - peak output"
cap label var LNGIT_PO_ABVG "LNG import terminals - peak output - above ground"
cap label var LNGIT_PO_BLWG "LNG import terminals - peak output - below ground"
cap label var LNGET_LIQ "LNG export terminals - liquefaction capacity"
cap label var LNGET_LIQ_ABVG "LNG export terminals - liquefaction capacity - above ground"
cap label var LNGET_LIQ_BLWG "LNG export terminals - liquefaction capacity - below ground"
cap label var LNGET_TRN "LNG export terminals - trains"
cap label var LNGET_TRN_ABVG "LNG export terminals - trains - above ground"
cap label var LNGET_TRN_BLWG "LNG export terminals - trains - below ground"
cap label var LNGET_ST "LNG export terminals - storage capacity"
cap label var LNGET_ST_ABVG "LNG export terminals - storage capacity - above ground"
cap label var LNGET_ST_BLWG "LNG export terminals - storage capacity - below ground"
cap label var LNGET_TNK "LNG export terminals - tanks"
cap label var LNGET_TNK_ABVG "LNG export terminals - tanks - above ground"
cap label var LNGET_TNK_BLWG "LNG export terminals - tanks - below ground"
cap label var LNGET_PO "LNG export terminals - peak output"
cap label var LNGET_PO_ABVG "LNG export terminals - peak output - above ground"
cap label var LNGET_PO_BLWG "LNG export terminals - peak output - below ground"
cap label var CAP_GNW "Gas network - maximum capacity"
cap label var CAP_GNW_I "Gas network - maximum imports capacity (incoming)"
cap label var CAP_GNW_E "Gas network - maximum exports capacity (outgoing)"
cap label var CAP_GNW_R "Gas network - reverse flow maximum capacity"
cap label var RCAP_AD "Refinery capacity - atmospheric distillation"
cap label var RCAP_AD_NOP_NAR "Refinery capacity - atmospheric distillation - not in operation and not in active repair"
cap label var RCAP_VD "Refinery capacity - vacuum distillation"
cap label var RCAP_TC "Refinery capacity - thermal cracking"
cap label var RCAP_TC_VB "Refinery capacity - thermal cracking - visbreaking"
cap label var RCAP_TC_CO "Refinery capacity - thermal cracking - coking"
cap label var RCAP_CC "Refinery capacity - catalytic cracking"
cap label var RCAP_CC_FCC "Refinery capacity - catalytic cracking - fluid catalytic cracking"
cap label var RCAP_CC_HC "Refinery capacity - catalytic cracking - hydro-cracking"
cap label var RCAP_DS "Refinery capacity - desulphurisation"
cap label var RCAP_DS_NG_LD "Refinery capacity - desulphurisation - naphtha, gasoline and other light distillates"
cap label var RCAP_DS_MIDD "Refinery capacity - desulphurisation - middle distillates"
cap label var RCAP_DS_HD "Refinery capacity - desulphurisation - heavy distillates"
cap label var RCAP_RFOR "Refinery capacity - reforming"
cap label var RCAP_API "Refinery capacity - alkylation, polymerisation, isomeration"
cap label var RCAP_ETH "Refinery capacity - etherification"
cap label var RCAP_UPU_OTH "Refinery capacity - other upgrading units"
cap label var RCAP_H "Refinery capacity - hydrogen"
cap label var CAP_EN "Enrichment capacity (tSWU)"
cap label var PRDCAP_FF "Production capacity of fresh fuel elements (tHM)"
cap label var PRDCAP_MOXF "Production capacity of MOX fuel fabrication plants (tHM)"
cap label var PRD_FF "Production of fresh fuel elements (tHM)"
cap label var PRD_MOXF "Production of MOX fuel elements (tHM)"
cap label var PRD_NUCH "Production of nuclear heat (ktoe)"
cap label var BAA_IRRADF "Annual average burnup of definitively discharged irradiated fuel elements (GWd/tHM)"
cap label var PRD_UP "Production of uranium and plutonium in reprocessing plants (tHM)"
cap label var CAP_UP "Capacity (uranium and plutonium) of reprocessing plants (tHM)"
cap label var CAP_BAST "Batteries - storage capacity"
cap label var CAP_BAP "Batteries - power capacity"
cap label var BA_G_ELC_I "Batteries - grid - electricity injected"
cap label var BA_G_ELC_U "Batteries - grid - electricity used"
