cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var FIN "Financial reasons"
cap label var NINT "No interest"
cap label var PER "Personal reasons"
cap label var PER_HOL "Holidays, leisure and recreation"
cap label var PER_VFR "Visits to friends and relatives"
cap label var PER_OTH "Other personal reasons"
cap label var PROF "Professional, business"
cap label var HLTH "Health reasons"
cap label var SAFE "Safety reasons"
cap label var OTH "Other reason"
