cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var POS "Positive decision"
cap label var POS_RFG "Positive decision - refugee status"
cap label var POS_HUM "Positive decision - humanitarian status"
cap label var POS_SPROT "Positive decision - subsidiary protection status"
cap label var POS_TPROT "Positive decision - temporary protection status"
cap label var POS_PART "Partially positive decision"
cap label var POS_OTH "Positive decision - other"
cap label var NSTA "Non-status decision"
cap label var NEG "Negative decision"
cap label var PEN "Decision pending at the end of the period"
cap label var CHG "Decision to change"
cap label var RNEW "Decision to renew"
cap label var GRNT "Decision to grant"
cap label var GRNT_FRST "Decision to grant first permit"
cap label var WDN "Decision to withdraw"
cap label var NOTF_RECV "Notification received"
cap label var NOTF_OBJ "Notification objected"
cap label var IPROT "International protection status"
cap label var UNK "Unknown"
cap label var ACC "Requests accepted"
cap label var PART "Requests partially accepted"
cap label var REF "Requests refused"
