cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var ST "Storage facilities for manure"
cap label var NST "No storage facilities for manure"
cap label var ST_SO "Manure solid storage"
cap label var ST_SO_NC "Manure solid storage without cover"
cap label var ST_SO_HEAP "Manure solid storage in heaps"
cap label var ST_COMP "Manure stored in compost piles"
cap label var ST_PIT "Manure stored in pits below animal confinement"
cap label var ST_DPLT "Manure stored in deep litter systems"
cap label var ST_LQ "Liquid manure storage"
cap label var ST_SL "Slurry manure storage"
cap label var ST_LQ_SL "Liquid manure/slurry storage"
cap label var ST_LQ_SL_C "Liquid manure/slurry storage with cover"
cap label var ST_LQ_SL_NC "Liquid manure/slurry storage without cover"
cap label var ST_LQ_SL_PC "Liquid manure/slurry storage with permeable cover"
cap label var ST_LQ_SL_IC "Liquid manure/slurry storage with impermeable cover"
cap label var ST_OF "Manure stored in other facilities n.e.c."
cap label var INC_BC_LE4H "Manure broadcast incorporation within 4 hours"
cap label var INC_BC_GT4H "Manure broadcast incorporation after 4 hours"
cap label var NINC_BC "Manure broadcast no incorporation"
cap label var INC_BSTH "Manure band spread trailing hose incorporation"
cap label var INC_BSTS "Manure band spread trailing shoe incorporation"
cap label var INJN_SWOP "Manure injection shallow/open slit"
cap label var INJN_DPCL "Manure injection deep/closed slit"
cap label var NAP "Not applicable"
