cap label var TOT_X_5 "Total emissions"
cap label var TOT_IA "Total emissions including international aviation"
cap label var TOT_NET "Total net emissions (sectors 1-7, including 5. LULUCF)"
cap label var _1 "Energy"
cap label var _1_A "Fuel Combustion - Sectoral Approach"
cap label var _1_A_1 "Energy Industries"
cap label var _1_A_1A "Public Electricity and Heat Production"
cap label var _1_A_1B "Petroleum Refining"
cap label var _1_A_1C "Manufacture of Solid Fuels and Other Energy Industries"
cap label var _1_A_2 "Manufacturing Industries and Construction"
cap label var _1_A_2A "Iron and Steel"
cap label var _1_A_2B "Non-Ferrous Metals"
cap label var _1_A_2C "Chemicals"
cap label var _1_A_2D "Pulp, Paper and Print"
cap label var _1_A_2E "Food Processing, Beverages and Tobacco"
cap label var _1_A_2F "Other"
cap label var _1_A_3 "Transport"
cap label var _1_A_3A "Civil Aviation"
cap label var _1_A_3B "Road Transport"
cap label var _1_A_3C "Railways"
cap label var _1_A_3D "Navigation"
cap label var _1_A_3E "Other Transport"
cap label var _1_A_4 "Other Sectors"
cap label var _1_A_4A "Commercial/Institutional"
cap label var _1_A_4B "Residential"
cap label var _1_A_4C "Agriculture/Forestry/Fisheries"
cap label var _1_A_5 "Other (Not elsewhere specified)"
cap label var _1_B "Fugitive Emissions from Fuels"
cap label var _1_B_1 "Solid Fuels"
cap label var _1_B_2 "Oil and Natural Gas"
cap label var _1_C1 "International Bunkers"
cap label var _1_C1_A "International aviation"
cap label var _1_C1_B "International maritime transport"
cap label var _1_C2 "Multilateral Operations"
cap label var _1_C3 "CO2 Emissions from Biomass"
cap label var _2 "Industrial Processes"
cap label var _2_A "Mineral Products"
cap label var _2_B "Chemical Industry"
cap label var _2_C "Metal Production"
cap label var _2_D "Other Production"
cap label var _2_E "Production of Halocarbons and SF6"
cap label var _2_F "Consumption of Halocarbons and SF6"
cap label var _2_G "Other"
cap label var _3 "Solvent and Other Product Use"
cap label var _4 "Agriculture"
cap label var _4_A "Enteric Fermentation"
cap label var _4_A_1 "Enteric fermentation: Cattle"
cap label var _4_A_2 "Enteric fermentation: Buffalo"
cap label var _4_A_3 "Enteric fermentation: Sheep"
cap label var _4_A_4 "Enteric fermentation: Goats"
cap label var _4_A_5 "Enteric fermentation: Camels and Llamas"
cap label var _4_A_6 "Enteric fermentation: Horses"
cap label var _4_A_7 "Enteric fermentation: Mules and Asses"
cap label var _4_A_8 "Enteric fermentation:Swine"
cap label var _4_A_9 "Enteric fermentation: Poultry"
cap label var _4_A_10 "Enteric fermentation: Other livestock"
cap label var _4_B "Manure Management"
cap label var _4_B_1 "Manure management: Cattle"
cap label var _4_B_2 "Manure management: Buffalo"
cap label var _4_B_3 "Manure management: Sheep"
cap label var _4_B_4 "Manure management: Goats"
cap label var _4_B_5 "Manure management: Camels and llamas"
cap label var _4_B_6 "Manure management: Horses"
cap label var _4_B_7 "Manure management: Mules and asses"
cap label var _4_B_8 "Manure management: Swine"
cap label var _4_B_9 "Manure management: Poultry"
cap label var _4_B_10 "Manure management: Other livestock"
cap label var _4_B_11 "Manure management: Anaerobic lagoon"
cap label var _4_B_12 "Manure management: Liquid system"
cap label var _4_B_13 "Manure management: Solid storage and dry lot"
cap label var _4_B_14 "Manure management: Other agricultural waste management system"
cap label var _4_C "Rice Cultivation"
cap label var _4_C_1 "Rice cultivation: Irrigated"
cap label var _4_C_2 "Rice cultivation: Rainfed"
cap label var _4_C_3 "Rice cultivation: Deep water"
cap label var _4_C_4 "Rice cultivation: Other"
cap label var _4_D "Agricultural Soils"
cap label var _4_D_1 "Agricultural soils: Direct soil emissions"
cap label var _4_D_2 "Agricultural soils: Pasture, range and paddock manure"
cap label var _4_D_3 "Agricultural soils: Indirect emissions"
cap label var _4_D_4 "Agricultural soils: Other"
cap label var _4_E "Prescribed Burning of Savannas"
cap label var _4_F "Field Burning of Agricultural Residues"
cap label var _4_F_1 "Field burning of agricultural residues: Cereals"
cap label var _4_F_2 "Field burning of agricultural residues: Pulse"
cap label var _4_F_3 "Field burning of agricultural residues: Tuber and roots"
cap label var _4_F_4 "Field burning of agricultural residues: Sugar cane"
cap label var _4_F_5 "Field burning of agricultural residues: Other"
cap label var _4_G "Other"
cap label var _5 "LULUCF (land use, land use change and forestry)"
cap label var _6 "Waste"
cap label var _6_A "Solid Waste Disposal on Land"
cap label var _6_B "Wastewater Handling"
cap label var _6_C "Waste Incineration"
cap label var _6_D "Other"
cap label var _7 "Other"
cap label var TOT_NAT "Total sectors of emissions for the national territory"
cap label var SE1_EPD "Energy production and distribution (NFR 1A1a, b, c, 1B1a, b, c, 1B2ai, aiv, av, b, c, d)"
cap label var SE1_EUI "Energy use in industry (NFR 1A2a, b, c, d, e, f, gvii, gviii)"
cap label var SE1_RD "Road transport (NFR 1A3b)"
cap label var SE1_NRD "Non-road transport (NFR 1A3a, c, d and 1A4ciii)"
cap label var SE1_RD_NRD "Road and non-road transport (NFR 1A3a, b, c, d and 1A4ciii)"
cap label var SE1_CIH "Commercial, institutional and households (NFR 1A4ai, aii, bi, bii, ci, cii, 1A5a, b)"
cap label var SE2_IP "Industrial processes and product use (NFR 2A1-6, 2B1-7, 2C1-7, 2D3, 2G, 2H, 2I, 2J, 2K, 2L)"
cap label var SE3_SPU "Solvent and other product use (NFR 3A1-3, 3B1-2, 3C, 3D1-3)"
cap label var SE4_AGR "Agriculture (NFR 3B1-4, 3D, 3F, 3I)"
cap label var SE6_WST "Waste (NFR 5A, 5B, 5C1-2, 5D1-3, 5E)"
cap label var SE7_OTH "Other (NFR 6A)"
cap label var _90 "International aviation"
cap label var _91 "International maritime transport"
