cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var ECO01 "Settlements and other artificial areas"
cap label var ECO0101 "Continuous settlement area"
cap label var ECO0102 "Discontinuous settlement area"
cap label var ECO0103 "Infrastructure"
cap label var ECO0104 "Urban greenspace"
cap label var ECO0105 "Other artificial areas"
cap label var ECO02 "Cropland"
cap label var ECO0201 "Annual cropland"
cap label var ECO0202 "Rice fields"
cap label var ECO0203 "Permanent crops"
cap label var ECO0204 "Agro-forestry areas"
cap label var ECO0205 "Mixed farmland"
cap label var ECO0206 "Other farmland"
cap label var ECO03 "Grassland"
cap label var ECO0301 "Sown pastures and grass (modified grassland)"
cap label var ECO0302 "Natural and semi-natural grassland"
cap label var ECO04 "Forest and woodlands"
cap label var ECO0401 "Broadleaved deciduous forest"
cap label var ECO0402 "Coniferous forests"
cap label var ECO0403 "Broadleaved evergreen forest"
cap label var ECO0404 "Mixed forests"
cap label var ECO0405 "Transitional forest and woodland shrub"
cap label var ECO0406 "Plantations"
cap label var ECO05 "Heathlands and shrub"
cap label var ECO0501 "Tundra"
cap label var ECO0502 "Scrub and heathland"
cap label var ECO0503 "Sclerophyllous vegetation"
cap label var ECO06 "Sparsely vegetated ecosystems"
cap label var ECO0601 "Bare rocks"
cap label var ECO0602 "Semi-desert, desert and other sparsely vegetated areas"
cap label var ECO0603 "Ice sheets, glaciers and perennial snowfields"
cap label var ECO07 "Inland wetlands"
cap label var ECO0701 "Inland marshes and other wetlands on mineral soil"
cap label var ECO0702 "Mires, bogs and fens"
cap label var ECO08 "Rivers and canals"
cap label var ECO0801 "Rivers"
cap label var ECO0802 "Canals, ditches and drains"
cap label var ECO09 "Lakes and reservoirs"
cap label var ECO0901 "Lakes and ponds"
cap label var ECO0902 "Artificial reservoirs"
cap label var ECO0903 "Geothermal pools and wetlands (Iceland)"
cap label var ECO10 "Marine inlets and transitional waters"
cap label var ECO1001 "Coastal lagoons"
cap label var ECO1002 "Estuaries and bays"
cap label var ECO1003 "Intertidal flats"
cap label var ECO11 "Coastal beaches, dunes and wetlands"
cap label var ECO1101 "Artificial shorelines"
cap label var ECO1102 "Coastal dunes, beaches and sandy and muddy shores"
cap label var ECO1103 "Rocky shores"
cap label var ECO1104 "Coastal saltmarshes and salines"
cap label var ECO12 "Marine ecosystems"
cap label var ECO1201 "Marine macrophyte habitats"
cap label var ECO1202 "Coral reefs"
cap label var ECO1203 "Worm reefs"
cap label var ECO1204 "Shellfish beds and reefs"
cap label var ECO1205 "Subtidal sand beds and mud plains"
cap label var ECO1206 "Subtidal rocky substrates"
cap label var ECO1207 "Continental and island slopes"
cap label var ECO1208 "Deepwater benthic and pelagic ecosystems"
cap label var ECO1209 "Deepwater coastal inlets (fjords)"
cap label var ECO1210 "Sea ice"
cap label var NAP "Not applicable"
