cap label var TOTAL "Total"
cap label var STD "Standard gauge"
cap label var STDGAU "Standard gauge"
cap label var LRG "Large gauge"
cap label var LARGAU "Large gauge"
cap label var NAR "Narrow gauge"
cap label var NARGAU "Narrow gauge"
