cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var SICK "Sickness/health care"
cap label var DIS "Disability"
cap label var OLD "Old age"
cap label var SRV "Survivors"
cap label var FAM "Family/children"
cap label var UNE "Unemployment"
cap label var HOU "Housing"
cap label var EXCL "Social exclusion, n.e.c."
cap label var SICK_DIS "Sickness/healthcare and disability"
cap label var OLD_SRV "Old age and survivors"
cap label var HOU_EXCL "Housing and social exclusion, n.e.c."
