cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var POP "Population"
cap label var EMP "Employed persons"
cap label var EMP_FT "Employed persons working full-time"
cap label var EMP_PT "Employed persons working part-time"
cap label var SAL_PERM "Employees with a permanent job"
cap label var SAL_TEMP "Employees with a temporary job"
cap label var NSAL "Employed persons except employees"
cap label var UNE "Unemployed persons"
cap label var INAC "Persons outside the labour force"
cap label var EDUC "Students"
cap label var RET "Retired persons"
cap label var INAC_OTH "Other persons outside the labour force"
cap label var OTH "Others"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
