cap label var TOTAL "All sectors"
cap label var BES "Business enterprise sector"
cap label var BES_IND_DOM "Independent enterprises and enterprises within the domestic group"
cap label var BES_MN "Multi-national enterprises"
cap label var BES_MN_DOMC "Multi-national enterprises domestically controlled"
cap label var BES_MN_FORC "Multi-national enterprises foreign controlled"
cap label var GOV_PNP "Government sector or private non-profit sector"
cap label var GOV "Government sector"
cap label var GOV_CTL "Central (or federal) government"
cap label var GOV_REG "Regional (or state) government"
cap label var GOV_LOC "Local (or municipal) government"
cap label var GOV_NPI "Non-profit institutions controlled by government"
cap label var HES "Higher education sector"
cap label var HEST "Tertiary level education institutions"
cap label var HESTI "Education institutions"
cap label var HESTI_OTH "Other tertiary level education institutions"
cap label var HESTI_UNI "Universities"
cap label var HEST_UNIHOS "University hospitals or clinics"
cap label var HEST_UNIRI "University research institutes or centres"
cap label var HESC_RO "Research organizations the R&D of which is controlled by higher education institutions"
cap label var PNP "Private non-profit sector"
cap label var PNP_SHH "Non-profit institutions serving households"
cap label var PNP_HH_IND "Households and private individuals (engaged or not engaged in market activities)"
cap label var ABR "Abroad"
cap label var HOS "Hospitals"
cap label var INA "Individual applicant"
cap label var OTH "Other sectors"
cap label var UNK "Unknown"
