cap label var HE_Y0 "Health expectancy in absolute values at birth"
cap label var HE_Y50 "Health expectancy in absolute values at 50"
cap label var HE_Y65 "Health expectancy in absolute values at 65"
cap label var LE_Y0 "Life expectancy in absolute value at birth"
cap label var LE_Y50 "Life expectancy in absolute value at 50"
cap label var LE_Y65 "Life expectancy in absolute value at 65"
cap label var HLY_Y0 "Healthy life years in absolute value at birth"
cap label var HLY_Y50 "Healthy life years in absolute value at 50"
cap label var HLY_Y65 "Healthy life years in absolute value at 65"
cap label var HLY_LE_Y0_PC "Healthy life years in percentage of the life expectancy at birth"
cap label var HLY_LE_Y50_PC "Healthy life years in percentage of the life expectancy at 50"
cap label var HLY_LE_Y65_PC "Healthy life years in percentage of the life expectancy at 65"
