cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var FRST "First time voters"
cap label var EU_CTZ "Voters with citizenship of another EU Member State"
cap label var NEU_VOT "Voters voting from outside the EU"
