cap label var E1 "ONLY MFN"
cap label var E2 "ONLY GSP"
cap label var E3 "ONLY PREFERENCES"
cap label var E5 "GSP AND PREFERENCES"
cap label var E7 "GSP AND/OR PREFERENCES"
cap label var EZ "UNKNOWN"
