cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var FRW "Fresh surface and groundwater"
cap label var FSW "Fresh surface water"
cap label var FSW_ON_OF_FRM "Fresh surface water - on-farm and off-farm"
cap label var FGW "Fresh groundwater"
cap label var FGW_ON_FRM "Fresh groundwater - on-farm"
cap label var NFW "Non fresh water"
cap label var DSW "Desalinated water"
cap label var RUW "Reused water"
cap label var RUW_T_GE2 "Reused water - at least secondary treatment"
cap label var NRGW "Non renewable groundwater"
cap label var IMP "Imports of water"
cap label var EXP "Exports of water"
cap label var WAU "Water available for use"
cap label var WSN_OF_FRM "Water supply networks - off-farm"
cap label var PRECIP "Precipitation"
cap label var RFW_RES "Renewable freshwater resources"
cap label var REW "Water returned without use"
cap label var WW "Wastewater"
cap label var TWW "Treated wastewater"
cap label var RUWW_T "Reused treated wastewater"
cap label var RUWW_T_NT "Reused treated and untreated wastewater"
cap label var OTH "Other"
