cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var HYD "Hydrogen"
cap label var HYD_PR "Pressurised hydrogen"
cap label var HYD_LIQ "Liquiefied hydrogen"
cap label var HYD_LIQ_CHM_OTH "Hydrogen in other chemicals (liquiefied)"
cap label var HYD_OTH "Other hydrogen"
cap label var AMM "Ammonia"
cap label var HYD_AS_AMM "Hydrogen as ammonia"
cap label var EFUEL "E-fuels"
cap label var NG "Natural gas"
cap label var NG_NCCS "Natural gas - without carbon capture and storage"
cap label var NG_CCS "Natural gas - with carbon capture and storage"
cap label var OIL_PP "Oil and petroleum products"
cap label var OIL_PP_NCCS "Oil and petroleum products - without carbon capture and storage"
cap label var OIL_PP_CCS "Oil and petroleum products - with carbon capture and storage"
cap label var SF "Solid fuels"
cap label var SF_NCCS "Solid fuels - without carbon capture and storage"
cap label var SF_CCS "Solid fuels - with carbon capture and storage"
cap label var REN "Renewables (including renewable waste)"
cap label var REN_NCCS "Renewables (including renewable waste) - without carbon capture and storage"
cap label var REN_CCS "Renewables (including renewable waste) - with carbon capture and storage"
cap label var NRW "Non-renewable waste"
cap label var NRW_NCCS "Non-renewable waste - without carbon capture and storage"
cap label var NRW_CCS "Non-renewable waste - with carbon capture and storage"
cap label var ELC_ELCYS "Electricity - electrolysis"
cap label var ELC_ELCYS_G_ELC "Electricity - electrolysis - grid electricity"
cap label var ELC_ELCYS_DL_REN "Electricity - electrolysis - direct line - renewables"
cap label var ELC_ELCYS_DL_NUC "Electricity - electrolysis - direct line - nuclear"
cap label var ELC_ELCYS_DL_FF "Electricity - electrolysis - direct line - fossil fuels"
cap label var ELC_OTH "Electricity - others"
cap label var NIDF_CFDL "Not identified and/or confidential"
cap label var OTH "Other"
