cap label var CODE "Label - English"
cap label var FCA "Fat content (% of product weight) (annual)"
cap label var PTEN "Protein content"
cap label var PRD "Product obtained"
cap label var BTE "Butter equivalent"
cap label var WPE "Whey powder equivalent"
cap label var PCA "Protein content (% of product weight) (annual)"
cap label var PRO "Products obtained (1 000 t)"
cap label var FAT "Fat content (t)"
cap label var PAT "Protein content (t)"
cap label var USM "Utilization of skimmed milk and buttermilk (1 000 t)"
cap label var UWM "Utilization of whole milk (1 000 t)"
