cap label var CODE "Label - English"
cap label var INF_ONL "Only informal care"
cap label var FML_ONL "Only formal care"
cap label var INF_FML "Both informal and formal care"
cap label var PROF "Professional home care"
cap label var NPROF_ND "No professional home care but need of long-term care"
cap label var NPROF_NND "No professional home care as no need of long-term care"
cap label var NC "No care"
