cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var HHW_10 "All adults working"
cap label var HHW_11 "All adults working full time"
cap label var HHW_12 "At least one adult working part time, all other adults (if any) working full time"
cap label var HHW_20 "At least one adult working and one adult not working"
cap label var HHW_30 "All adults not working (all households)"
cap label var HHW_31 "All adults not working (excluding households composed solely of students)"
cap label var HHW_32 "All adults not working (excluding households composed solely of students or solely inactive aged 65 and over)"
cap label var NRESP "No response"
cap label var WRK "Working"
cap label var WRK_FT "Working full-time"
cap label var GE1_WRK_PT_OTH_FT "At least one adult working part-time, all others full-time"
cap label var GE1_WRK_A1_NWRK "At least one adult working and one not"
cap label var NWRK "Not working (for any reason)"
cap label var NWRK_X_EDUC "Not working (excluding households composed solely of students)"
cap label var NWRK_X_EDUC_INAC_GE65 "Not working (excluding households composed solely of students or solely persons outside the labour force aged 65 or over)"
cap label var NRP "No response"
