cap label var CODE "Label - English"
cap label var STOCKS "Direct investment stocks - million ECU/EUR"
cap label var FLOWS "Direct investment flows - million ECU/EUR"
cap label var INCOME "Direct investment income - million ECU/EUR"
cap label var FGDP "GDP (flows in % of GDP)"
cap label var SGDP "GDP (stocks in % of GDP)"
cap label var IPOS "Rate of return on direct investment (FDI income/FDI stocks)"
cap label var PCPOS "FDI stocks (in % of extra EU FDI stocks)"
cap label var TI100 "Market integration - trade integration of goods"
cap label var TI200 "Market integration - trade integration of services"
cap label var TIFDI "Market integration - foreign direct investment intensity - average value of inward and outward foreign direct investment flows divided by GDP, multiplied by 100"
cap label var TUR "Turnover - million ECU/EUR"
cap label var EMP "Number of persons employed"
cap label var ENT "Number of enterprises"
cap label var PEC "Personnel costs - million ECU/EUR"
cap label var GIT "Gross investments in tangible goods - million ECU/EUR"
cap label var VAC "Value added at factor cost - million ECU/EUR"
