cap label var TOTAL "Total"
cap label var STIM_INN "Stimulation of innovation"
cap label var NMAJPB "No major problems created"
cap label var UNC "Creation of uncertainty"
cap label var EXS_BUR "Generation of an excessive burden"
cap label var LCSI_EU "Lack of consistency across the EU"
cap label var INI "Initiation of one or more innovation activities"
cap label var NINI "No initiation of one or more innovation activities"
cap label var PCL "Preclusion of starting one or more activities"
cap label var NPCL "No preclusion of starting one or more activities"
cap label var STOP_ONGO "Stop of one or more ongoing innovation activities"
cap label var NSTOP_ONGO "No stop of one or more ongoing innovation activities"
cap label var D_END "Delay in the completion of one or more innovation activities"
cap label var ND_END "No delay in the completion of one or more innovation activities"
cap label var INCR_COST "Increase of the costs of one or more innovation activities"
cap label var NINCR_COST "No increase of the costs of one or more innovation activities"
cap label var SUCC "Success"
cap label var NSUCC "No success"
cap label var INI_FAC "Initiation or facilitation"
cap label var PHIC "Prevention, hampering or increase of the costs"
cap label var MOV_BK "Decision to move or plan to move business function back from abroad"
cap label var MOV_BK_TEMP "Temporary decision to move or plan to move business function back from abroad"
cap label var MOV_BK_PERM "Permanent decision to move or plan to move business function back from abroad"
cap label var ENGA_SRC_INTL "Decision to engage or plan to engage in international sourcing"
cap label var ENGA_SRC_INTL_TEMP "Temporary decision to engage or plan to engage in international sourcing"
cap label var ENGA_SRC_INTL_PERM "Permanent decision to engage or plan to engage in international sourcing"
cap label var DISR_SRC_INTL "Disruption of international sourcing plans"
cap label var DISR_SRC_INTL_TEMP "Temporary disruption of international sourcing plans"
cap label var DISR_SRC_INTL_PERM "Permanent disruption of international sourcing plans"
cap label var NIMPC "No impact"
cap label var CHG_INCR_INC "Any change to increase income"
cap label var CHG_JOB "Change of job or employer"
cap label var LS_WRKHR "Less working hours"
cap label var LS_DTSK "Less demanding tasks in job"
cap label var FAM_LEAV "Family leave"
cap label var WRKINTR "Work interruption"
cap label var NWRKINTR "No work interruption"
cap label var RED_WRKTIME "Reduction of working time"
cap label var NWRKINTR_NRED_WRKTIME "No work interruption or reduction of working time"
cap label var NVR_WRK_CHCARE "Never worked for childcare reasons"
cap label var NVR_WRK_OTH "Never worked for other reasons"
cap label var NVR_CH "Never had children"
cap label var NVR_CARE "Never had care responsibilities"
cap label var FQLF_REC "Formal qualification recognised"
cap label var FQLF_NREC "Formal qualification not recognised"
cap label var PROC_UW "Procedure under way or outcome pending"
cap label var NLK "Did not look for"
cap label var LK_FD "Looked for and found"
cap label var LK_NFD "Looked for but did not find"
cap label var INJ "Physical injury"
cap label var LIFE_DNG "Felt that their life was in danger"
cap label var CHG_TLF_CL_SNW "Changed telephone number/email address or closed social network"
cap label var IMPL_PROT "Implemented protecting measures (e.g. changed going out or usual route or taking with knife, pepper spray etc.)"
cap label var MOV_RES_CHG_WRK "Moved to another residence or changed working or studying"
cap label var ENTRY_REF "Refused entry"
cap label var PRES_NLEG "Found to be illegally present"
cap label var L_ORD "Ordered to leave an EU Member State"
cap label var RE_L_ORD "Returned following an order to leave"
cap label var SUP_SH "Supply shortages in existing supply chains of raw materials, intermediate and final goods and services"
cap label var INCR_COST_NRG "Increased costs of raw material in connection with energy supply"
cap label var PB_COST_TRA "Problems with transportation capacity, extended transport time or transport costs from already existing locations to markets"
cap label var INCR_COST_OTH "Increased costs of raw materials, intermediate and final goods in existing supply chains, other than those in connection with energy supply and transportation costs"
cap label var SANC_RU "Sanctions on Russia"
cap label var LIM_COV19 "Limitations and constraints related to COVID-19"
cap label var CSTR_ENV "Constraints related to environmental policies"
cap label var FND_NEWSUPPL_EU "Found new suppliers or buyers within the EU"
cap label var FND_NEWSUPPL_NEU "Found new suppliers or buyers outside of the EU"
cap label var RED_SUPPL_ORD "Reduced the number of suppliers or orders from other suppliers"
cap label var INCR_SUPPL "Increased the number of suppliers from countries where we already have suppliers"
cap label var RE_BKSRC_OUT "Returned business functions previously sourced abroad back to our home market, but to another enterprise"
cap label var RE_BKSRC_IN "Returned business functions previously sourced abroad back to our own enterprise"
cap label var INCR_DGTL_GVC "Increased the digitalisation of the processes within the global value chain"
cap label var INCR_STK "Increased the stocks/inventory"
cap label var ENT_MFG_SERVP "Enterprise purchases manufacturing, processing or assembly services"
cap label var ENT_CMFG_SERVP "Enterprise purchases the complete manufacturing, processing or assembly services"
cap label var ENT_MFG_SERVS "Enterprise supplies manufacturing, processing or assembly services"
cap label var OTH "Other"
cap label var NONE "No effects"
cap label var NAP_NAPLD "Not applicable - did not apply for recognition"
cap label var NAP "Not applicable"
cap label var NRP "No response"
