cap label var CODE "Label - English"
cap label var S1_S2 "Total economy and rest of the world"
cap label var S1 "Total economy"
cap label var S1D "Non-educational private sector"
cap label var S1D_OTH "Other non-educational private entities"
cap label var S1N "Not sectorised"
cap label var S11_S14_S15 "Non-financial corporations; households; non-profit institutions serving households"
cap label var S1V "Non-financial corporations, households and non-profit institutions serving households"
cap label var S11_S12 "Corporations"
cap label var S11 "Non-financial corporations"
cap label var S11DO "Domestically controlled non-financial corporations"
cap label var S11001 "Public non-financial corporations"
cap label var S110011 "Public non-financial corporations, which are part of domestic multinationals"
cap label var S11002 "National private non-financial corporations"
cap label var S110021 "National private non-financial corporations, which are part of domestic multinationals"
cap label var S11003 "Foreign controlled non-financial corporations"
cap label var S12 "Financial corporations"
cap label var S12DO "Domestically controlled financial corporations"
cap label var S12001 "Public financial corporations"
cap label var S120011 "Public financial corporations, which are part of domestic multinationals"
cap label var S12002 "National private financial corporations"
cap label var S120021 "National private financial corporations, which are part of domestic multinationals"
cap label var S12003 "Foreign controlled financial corporations"
cap label var S121_S122_S123 "Monetary financial institutions"
cap label var S12K "Monetary financial institutions (MFI)"
cap label var S121 "Central bank"
cap label var S122 "Deposit taking corporations, except the central bank"
cap label var S122_S123 "Monetary financial institutions other than central bank"
cap label var S12T "Monetary Financial Institutions (MFI) other than central bank"
cap label var S125_S126_S127 "Other financial intermediaries (except ICPFs), financial auxiliaries, CFIs, and money lenders"
cap label var S123 "Money market funds"
cap label var S124 "Non-MMF investment funds"
cap label var S124_TO_S127 "Other financial institutions (financial corporations other than MFIs, insurance corporations and pension funds)"
cap label var S125 "Other financial intermediaries, except insurance corporations and pension funds"
cap label var S126 "Financial auxiliaries"
cap label var S127 "Captive financial institutions and money lenders"
cap label var S128 "Insurance corporations"
cap label var S128_S129 "Insurance corporations and pension funds"
cap label var S12Q "Insurance corporations and pension funds"
cap label var S129 "Pension funds"
cap label var S12M "Financial corporations other than MFIs"
cap label var S12R "Other financial corporations"
cap label var S12O "Other financial institutions"
cap label var S13_S212 "General government; institutions of the EU"
cap label var S13 "General government"
cap label var S1311 "Central government"
cap label var S13111 "Budgetary central government"
cap label var S13112 "Central government other than budgetary central government"
cap label var S1312_S1313 "State and local government"
cap label var S1312 "State government"
cap label var S1313 "Local government"
cap label var S1314 "Social security funds"
cap label var S1315 "European institutions and bodies"
cap label var S13_S15 "General government; non-profit institutions serving households"
cap label var S13_BC "Base case"
cap label var S13_SC1 "Base case minus 1% change in discount rate"
cap label var S13_SC2 "Base case plus 1% change in discount rate"
cap label var S1X "Monetary authorities"
cap label var S14_S15 "Households; non-profit institutions serving households"
cap label var S14 "Households"
cap label var S15 "Non-profit institutions serving households"
cap label var S1M "Households and non-profit institutions serving households"
cap label var S1P "Other sectors than MFIs and general government"
cap label var S1A "Affiliates"
cap label var S1W "Other sectors than general government"
cap label var S1Z "Sectors other than deposit-taking corporations and general government"
cap label var S2 "Rest of the world"
cap label var S2I "Rest of the world - of which: intra Euro area"
cap label var S21 "European Union"
cap label var S212 "Institutions of the EU"
cap label var S22 "Third countries and international organisations"
cap label var INTLORG "International organisations"
cap label var TOT_SEC "Total"
cap label var PUB "Public institutions"
cap label var PUBL "Public institutions"
cap label var PRV "Private institutions"
cap label var PRIV "Private institutions"
cap label var PRIV_DEP "Private government dependant institutions"
cap label var PRIV_IND "Private government independent institutions"
