cap label var CODE "Label - English"
cap label var BS_IPT "Production development observed over the past 3 months"
cap label var BS_EEI_I "Employment expectations indicator over the next 3 months"
cap label var BS_IEME "Employment expectations over the next 3 months"
cap label var BS_IEME_BAL "Employment expectations over the next 3 months - industry"
cap label var BS_CEME_BAL "Employment expectations over the next 3 months - construction"
cap label var BS_REM_BAL "Employment expectations over the next 3 months - retail trade"
cap label var BS_SEEM_BAL "Employment expectations over the next 3 months - services"
cap label var BS_IOB "Assessment of order-book levels"
cap label var BS_IEOB "Assessment of export order-book levels"
cap label var BS_ISFP "Assessment of the current level of stocks of finished products"
cap label var BS_IPE "Production expectations over the next 3 months"
cap label var BS_ISPE "Selling price expectations over the next 3 months"
cap label var BS_ICI "Industrial confidence indicator"
cap label var BS_ICPC_BAL "Assessment of current production capacity"
cap label var BS_INO_BAL "New orders in recent months"
cap label var BS_ICU_PC "Current level of capacity utilization (%)"
cap label var BS_CP3M_FMIEU_BAL "Competitive position on foreign markets inside the EU over the past three months"
cap label var BS_CP3M_EXEU_BAL "Competitive position on foreign markets outside the EU over the past three months"
cap label var BS_FLP1_PC "Factors limiting the production - none"
cap label var BS_FLP2_PC "Factors limiting the production - insufficient demand"
cap label var BS_FLP3_PC "Factors limiting the production - labour"
cap label var BS_FLP4_PC "Factors limiting the production - equipment"
cap label var BS_FLP5_PC "Factors limiting the production - other"
cap label var BS_FLP6_PC "Factors limiting the production - financial constraints"
cap label var BS_CTA_BAL "Building activity development over the past 3 months"
cap label var BS_COB_BAL "Evolution of the current overall order books"
cap label var BS_CPE_BAL "Price expectations over the next 3 months"
cap label var BS_CCI_BAL "Construction confidence indicator"
cap label var BS_FLBA1_PC "Factors limiting building activity - none"
cap label var BS_FLBA2_PC "Factors limiting building activity - insufficient demand"
cap label var BS_FLBA3_PC "Factors limiting building activity - weather conditions"
cap label var BS_FLBA4_PC "Factors limiting building activity - shortage of labour"
cap label var BS_FLBA5_PC "Factors limiting building activity - shortage of material and/or equipment"
cap label var BS_FLBA6_PC "Factors limiting building activity - other"
cap label var BS_FLBA7_PC "Factors limiting building activity - financial constraints"
cap label var BS_OTEB "Operating time ensured by current backlog, months"
cap label var BS_RPBS "Business activity (sales) development over the past 3 months"
cap label var BS_RAS "Volume of stocks currently hold"
cap label var BS_ROP "Expectations of the number of orders placed with suppliers over the next 3 months"
cap label var BS_REBS "Business activity expectations over the next 3 months"
cap label var BS_REM "Employment expectations over the next 3 months"
cap label var BS_RPE "Price expectations over the next 3 months"
cap label var BS_RCI "Retail confidence indicator"
cap label var BS_FS_LY "Financial situation over the last 12 months"
cap label var BS_FS_NY "Financial situation over the next 12 months"
cap label var BS_GES_LY "General economic situation over the last 12 months"
cap label var BS_GES_NY "General economic situation over the next 12 months"
cap label var BS_PT_LY "Price trends over the last 12 months"
cap label var BS_PT_NY "Price trends over the next 12 months"
cap label var BS_UE_NY "Unemployment expectations over the next 12 months"
cap label var BS_MP_PR "The current economic situation is adequate to make major  purchases"
cap label var BS_MP_NY "Major purchases over the next 12 months"
cap label var BS_SV_NY "Savings over the next 12 months"
cap label var BS_SFSH "Statement on financial situation of household"
cap label var BS_CSMCI "Consumer confidence indicator"
cap label var BS_PBH_NTY "Purchase or build a home within the next 12 months"
cap label var BS_HI_NY "Home improvements over the next 12 months"
cap label var BS_ESI_I "Economic sentiment indicator"
cap label var BS_ICI_BAL "Industrial confidence indicator"
cap label var BS_RCI_BAL "Retail confidence indicator"
cap label var BS_CSMCI_BAL "Consumer confidence indicator"
cap label var BS_SCI_BAL "Services confidence indicator"
cap label var BS_SABC "Business situation development over the past 3 months"
cap label var BS_SARM "Evolution of demand over the past 3 months"
cap label var BS_SAEM "Expectation of the demand over the next 3 months"
cap label var BS_SEEM "Expectation of the employment over the next 3 months"
cap label var BS_SCI "Services confidence indicator"
cap label var BS_PE3M "Expectations of the prices over the next 3 months"
cap label var BS_BCI "Business climate indicator"
cap label var CP_HI00 "HICP - All items (HICP=harmonized index of consumer prices)"
cap label var CP_HI01 "HICP - Food and non alcoholic beverages"
cap label var CP_HI02 "HICP - Alcoholic beverages and tobacco"
cap label var CP_HI03 "HICP - Clothing and footwear"
cap label var CP_HI04 "HICP - Housing, water, electricity,gas and other fuels"
cap label var CP_HI05 "HICP - Furnishings, household equipment and maintenance"
cap label var CP_HI06 "HICP - Health"
cap label var CP_HI07 "HICP - Transport"
cap label var CP_HI08 "HICP - Communication"
cap label var CP_HI09 "HICP - Recreation and culture"
cap label var CP_HI10 "HICP - Education"
cap label var CP_HI11 "HICP - Hotels, cafes and restaurants"
cap label var CP_HI12 "HICP - Miscellaneous goods and services"
cap label var CP_HI00XEF "HICP - All items excluding energy, food, alcohol and tobacco"
cap label var CP_HI00XTB "HICP - All items excluding tobacco"
cap label var CP_HIE "HICP - Energy"
cap label var CP_HIF "HICP - Food"
cap label var CP_HIFU "HICP - Unprocessed food"
cap label var CP_HIG "HICP - Total goods"
cap label var CP_HIIG "HICP - Industrial goods"
cap label var CP_HIS "HICP - Total services"
cap label var CP_HIIGXE "HICP - Non-energy industrial goods"
cap label var CP_HI00XE "HICP - All items excluding energy"
cap label var CP_HI00XEFU "HICP - All items excluding energy and unprocessed food"
cap label var CP_HI00XES "HICP - All items excluding energy and seasonal food"
cap label var ET_T "Total"
cap label var ET_CAP "Capital goods"
cap label var ET_CONS "Consumer goods"
cap label var ET_CONXT "Consumer goods (excluding transport equipment)"
cap label var ET_INTER "Intermediate goods"
cap label var IS_PPI "Output prices of the domestic market index (producer price index) (NSA)"
cap label var IS_IP "Production index"
cap label var IS_IP_CA "Production index - calendar adjusted data, not seasonally adjusted data (CA)"
cap label var IS_IP_SCA "Production index - seasonally and working days adjusted data (SCA)"
cap label var IS_EPI "Number of persons employed index"
cap label var IS_HWI "Hours worked index"
cap label var IS_WSI "Gross wages and salaries index"
cap label var IS_IPI "Cost index (input price index) - new residential buildings"
cap label var IS_PEI "Building permits index - new residential buildings"
cap label var IS_ITT "Turnover index - total"
cap label var IS_ITD "Turnover index - domestic market"
cap label var IS_ITND "Turnover index - non-domestic market"
cap label var IS_IMPR "Import price index (NSA)"
cap label var IS_IMPX "Import price index - non euro area (NSA)"
cap label var IS_IMPZ "Import price index - euro area (NSA)"
cap label var IS_PNG_TJ "Production of natural gas, TJ (GCV)"
cap label var IS_CNG_TJ "Total consumption of natural gas, TJ (GCV)"
cap label var IS_ING_TJ "Imports of natural gas, TJ (GCV)"
cap label var IS_PEL_GWH "Production of electricity - GWh"
cap label var IS_CEL_GWH "Consumption of electricity - GWh"
cap label var IS_IEL_GWH "Imports of electricity - GWh"
cap label var IS_ROMS_T "Refinery output of motor spirit - 1000t"
cap label var IS_IDMS_T "Inland deliveries of motor spirit - 1000t"
cap label var IS_ROGD_T "Refinery output of gas/diesel oil - 1000t"
cap label var IS_IDGD_T "Inland deliveries of gas/diesel oil - 1000t"
cap label var IS_IDC_T "Inland deliveries of brown coal - 1000t"
cap label var IS_ICO_T "Imports of crude oil - 1000t"
cap label var IS_IDMG_T "Inland deliveries of motor gasoline - 1000t"
cap label var IS_IDJF_T "Inland deliveries of kerosene-type jet fuel - 1000t"
cap label var LM_UN_T_TOT "Unemployment according to ILO definition - total"
cap label var LM_UN_M_TOT "Unemployment according to ILO definition - males"
cap label var LM_UN_F_TOT "Unemployment according to ILO definition - females"
cap label var LM_UN_T_LE25 "Unemployment according to ILO definition - under 25 years - total"
cap label var LM_UN_M_LE25 "Unemployment according to ILO definition - under 25 years - males"
cap label var LM_UN_F_LE25 "Unemployment according to ILO definition - under 25 years - females"
cap label var LM_UN_T_GT25 "Unemployment according to ILO definition - over 25 years - total"
cap label var LM_UN_M_GT25 "Unemployment according to ILO definition - over 25 years - males"
cap label var LM_UN_F_GT25 "Unemployment according to ILO definition - over 25 years - females"
cap label var LM_LCI_TOT "Labour cost index - total labour cost"
cap label var LM_LCI_SAL "Labour cost index - wages and salaries"
cap label var LM_LCI_OTH "Labour cost index - labour costs other than wages and salaries"
cap label var MF_DDI_RT "Day-to-day money market interest rates (average)"
cap label var MF_3MI_RT "3-month interest rates (average)"
cap label var MF_EY1YM_RT "Euro yields - 1 year (average)"
cap label var MF_EY5YM_RT "Euro yields - 5 years (average)"
cap label var MF_EY10YM_RT "Euro yields - 10 years (average)"
cap label var MF_LTGBY_RT "Long term government bond yields - Maastricht definition (average)"
cap label var MF_EXA_RT "Exchange rates against the ECU/euro (average)"
cap label var INV_TOT "Total investment"
cap label var INV_BSN "Business investment"
cap label var INV_GOV "Government investment"
cap label var INV_HH "Households investment"
cap label var BS_FCI "Financial services confidence indicator"
cap label var BS_BSDP3 "Assessment of business situation over the past 3 months"
cap label var BS_DEVP3 "Evolution of demand over the past 3 months"
cap label var BS_DEXN3 "Evolution of demand expected over the next 3 months"
cap label var BS_EEVP3 "Evolution of employment over the past 3 months"
cap label var BS_EEXN3 "Evolution of employment expected over the next 3 months"
cap label var BS_OIDP3 "Operating income development over the last three months"
cap label var BS_OIEN3 "Operating income expectations over the next three months"
cap label var BS_OEDP3 "Operating expenses development over the last three months"
cap label var BS_OEEN3 "Operating expenses expectations over the next three months"
cap label var BS_PDP3 "Profitability development over the last three months"
cap label var BS_PEN3 "Profitability expectations over the next three months"
cap label var BS_CEDP3 "Capital expenditure development over the last 3 months"
cap label var BS_CEEN3 "Capital expenditure expectations over the next 3 months"
cap label var BS_CPDTP3 "Competitive position development over the past 3 months (total)"
cap label var BS_CPD1P3 "Competitive position development over the past 3 months (in your country)"
cap label var BS_CPD2P3 "Competitive position development over the past 3 months (within the euro area)"
cap label var BS_CPD3P3 "Competitive position development over the past 3 months (within the EU)"
cap label var BS_CPD4P3 "Competitive position development over the past 3 months (outside the EU)"
cap label var BS_CPETN3 "Competitive position expectations over the next 3 months (total)"
cap label var BS_CPE1N3 "Competitive position expectations over the next 3 months (in your country)"
cap label var BS_CPE2N3 "Competitive position expectations over the next 3 months (within the euro area)"
cap label var BS_CPE3N3 "Competitive position expectations over the next 3 months (within the EU)"
cap label var BS_CPE4N3 "Competitive position expectations over the next 3 months (outside the EU)"
cap label var TOTAL "Total"
cap label var JOBRATE "Job vacancy rate"
cap label var NEER37 "Nominal effective exchange rate - 37 trading partners"
cap label var NEER42 "Nominal effective exchange rate - 42 trading partners"
cap label var REER37CPI "Real effective exchange rate (deflator: consumer price indices - 37 trading partners)"
cap label var REER42CPI "Real effective exchange rate (deflator: consumer price indices - 42 trading partners)"
cap label var IND_H "Headline indicators"
cap label var IND_A "Auxiliary indicators"
cap label var IND_T "All indicators"
cap label var BS_FLB1_PC "Main factors limiting the business - none"
cap label var BS_FLB2_PC "Main factors limiting the business - insufficient demand"
cap label var BS_FLB3_PC "Main factors limiting the business - labour"
cap label var BS_FLB4_PC "Main factors limiting the business - equipment and/or space"
cap label var BS_FLB5_PC "Main factors limiting the business - financial constraints"
cap label var BS_FLB6_PC "Main factors limiting the business - others"
cap label var BS_QP_PC "Possibility to increase the volume of activity with present resources"
cap label var VOL_SLS "Volume of sales"
cap label var NETTUR "Net turnover"
