cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var YES_DIF_BACT "Difficulty in basic activities"
cap label var YES_DIF_PCARE "Difficulty in personal care"
cap label var YES_DIF_HCARE "Difficulty in household care"
cap label var YES_WLIM_HLTH "Limitation in work caused by a health condition or difficulty in a basic activity"
cap label var YES_LHCILL "Long-standing health condition, illness or disease"
cap label var YES_SDIF_TADL "Severe difficulty with both personal care and household activities - total activities of daily living (TADL)"
cap label var YES_SDIF_ADL "Severe difficulty with personal care only - activities of daily living (ADL)"
cap label var YES_SDIF_IADL "Severe difficulty with household activities only - instrumental activities of daily living (IADL)"
cap label var NO_DIF_BACT "No difficulty in basic activities"
cap label var NO_DIF_PCARE "No difficulty in personal care"
cap label var NO_DIF_HCARE "No difficulty in household care"
cap label var NO_WLIM_HLTH "No limitation in work caused by a health condition or difficulty in basic activities"
cap label var NO_LHCILL "No long-standing health condition, illness or disease"
cap label var NO_SDIF "No severe difficulty"
