cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var CANCER "Cancer"
cap label var CARDIO_V "Cardiovascular disorders"
cap label var CARDIO_VASC "Cardiovascular disorders"
cap label var HEARING "Hearing disorders"
cap label var HEAR "Hearing"
cap label var PULMONAR "Pulmonary disorders"
cap label var PULMO "Pulmonary disorders"
cap label var MUSC_SKE "Musculo-skeletal disorders"
cap label var INFECTIO "Infectious diseases"
cap label var INFECT "Infectious diseases"
cap label var STOMACH "Stomach, liver, kidney or digestive problems"
cap label var STRESS "Stress, depression, anxiety"
cap label var SKIN_DIS "Skin problems"
cap label var SKIN "Skin problems"
cap label var HEAD_EYE "Headaches, eyestrains, migraines"
cap label var OTHER "Other not elsewhere mentioned"
cap label var UNK "Unspecified"
cap label var OTH "Other"
cap label var NSP "Unspecified"
