cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var CO "Co-created"
cap label var CUS "Customised"
cap label var CO_CUS "Co-created or customised"
cap label var STD "Standardised"
cap label var RM_ENT "Raw materials used in enterprise's production process"
cap label var CMPT_ENT "Components of enterprise's product"
cap label var MAC_ENT "Machinery and other technical equipment used by the enterprise"
cap label var DESG_ENT "Product designed by the enterprise"
cap label var RM_ABR "Raw materials used by customers abroad in their production process"
cap label var CMPT_ABR "Components used by customers abroad as part of their product"
cap label var MAC_ABR "Machinery and other technical equipment used by customers abroad"
cap label var DESG_OTH "Product designed by another enterprise"
cap label var DIST_LOG "Distribution and logistics"
cap label var MKTG_SLS "Marketing, sales, and after-sales service"
cap label var ICT "Information and communication technology services"
cap label var ADM_MGMT "Administrative and management"
cap label var EGNG_TEC "Engineering and related technical services"
cap label var RND "Research and development"
cap label var GDS_DOM "Goods supplied to domestic partners"
cap label var GDS_DOM_EXP "Goods supplied to domestic partners that are eventually exported"
cap label var GDS_DOM_WHLS "Goods supplied to domestic wholesale partners"
cap label var GDS_DOM_WHLS_EXP "Goods supplied to domestic wholesale partners that are eventually exported"
cap label var GDU_ENT_IMP_THRD "Goods used by the enterprise that are imported by a third party"
cap label var GDS_ENT_IN_OUT "Goods supplied to enterprises within or outside of the enterprise group"
cap label var GDP_ENT_IN_OUT "Goods purchased from enterprises within or outside of the enterprise group"
cap label var GDS_OTH "Other goods"
cap label var SERVS_ENT_IN_OUT "Services supplied to enterprises within or outside of the enterprise group"
cap label var SERVP_ENT_IN_OUT "Services purchased from enterprises within or outside of the enterprise group"
cap label var SERV_OTH "Other services"
cap label var OTH "Other"
