cap label var MOGA_FAM "Family members having other gainful activities as main activity"
cap label var MOGA_FAM_RH "Family members having other gainful activities (related to the agricultural holding) as main activity"
cap label var MOGA_FAM_NRH "Family members having other gainful activities (not related to the agricultural holding) as main activity"
cap label var MOGA_NFAM_RH "Non-family labour force regularly working on the agricultural holding and having other gainful activities (related to the agricultural holding) as main activity"
cap label var SOGA_FAM "Family members having other gainful activities as secondary activity"
cap label var SOGA_FAM_RH "Family members having other gainful activities (related to the agricultural holding) as secondary activity"
cap label var SOGA_FAM_NRH "Family members having other gainful activities (not related to the agricultural holding) as secondary activity"
cap label var SOGA_NFAM_RH "Non-family labour force regularly working on the agricultural holding and having other gainful activities (related to the agricultural holding) as secondary activity"
cap label var NOGA_FAM "Family members not having other gainful activities"
cap label var NOGA_FAM_RH "Family members not having other gainful activities (related to the agricultural holding)"
cap label var NOGA_FAM_NRH "Family members not having other gainful activities (not related to the agricultural holding)"
