cap label var CODE "Label - English"
cap label var _25 "Total from group 01 to 24"
cap label var _00 "Groups of goods"
cap label var _01 "Cereals"
cap label var _02 "Potatoes, other fresh or frozen fruits and vegetables"
cap label var _03 "Live animals, sugar beet"
cap label var _04 "Wood and cork"
cap label var _05 "Textiles, textile articles and man-made fibres, other raw animal and vegetable materials"
cap label var _06 "Foodstuff and animal fodder"
cap label var _07 "Oil seeds and oleaginous fruits and fats"
cap label var _08 "Solid minerals fuels"
cap label var _09 "Crude petroleum"
cap label var _10 "Petroleum products"
cap label var _11 "Iron ore, iron and steel waste and blast furnace dust"
cap label var _12 "Non-ferrous ores and waste"
cap label var _13 "Metal products"
cap label var _14 "Cement, lime, manufactured building materials"
cap label var _15 "Crude and manufactured minerals"
cap label var _16 "Natural and chemical fertilizers"
cap label var _17 "Coal chemicals, tar"
cap label var _18 "Chemicals other than coal chemicals and tar"
cap label var _19 "Paper pulp and waste paper"
cap label var _20 "Transport equipment, machinery, apparatus, engines, whether or not assembled, and parts thereof"
cap label var _21 "Manufactures of metal"
cap label var _22 "Glass, glassware, ceramic products"
cap label var _23 "Leather, textile, clothing, other manufactured articles"
cap label var _24 "Miscellaneous articles"
cap label var _99 "Not defined"
cap label var TOTAL "Total"
