cap label var CODE "Label - English"
cap label var BE "Belgium"
cap label var BE001C "Bruxelles/Brussel (greater city)"
cap label var BE001F "Bruxelles/Brussel/Leuven"
cap label var BE002C "Antwerpen (greater city)"
cap label var BE002F "Antwerpen"
cap label var BE003C "Gent"
cap label var BE003F "Gent"
cap label var BE004C "Charleroi (greater city)"
cap label var BE004F "Charleroi"
cap label var BE005C "Liège (greater city)"
cap label var BE005F "Liège"
cap label var BE006C "Brugge"
cap label var BE006F "Brugge"
cap label var BE007C "Namur"
cap label var BE007F "Namur"
cap label var BE008C "Leuven"
cap label var BE009C "Mons (greater city)"
cap label var BE009F "Mons"
cap label var BE010C "Kortrijk (greater city)"
cap label var BE010F "Kortrijk"
cap label var BE011C "Oostende (greater city)"
cap label var BE011F "Oostende"
cap label var BE012C "Mechelen"
cap label var BE012F "Mechelen"
cap label var BE013C "Mouscron"
cap label var BE013F "Mouscron"
cap label var BE014C "La Louvière (greater city)"
cap label var BE014F "La Louvière"
cap label var BE015C "Verviers (greater city)"
cap label var BE015F "Verviers"
cap label var BG "Bulgaria"
cap label var BG001C "Sofia"
cap label var BG001F "Sofia"
cap label var BG002C "Plovdiv"
cap label var BG002F "Plovdiv"
cap label var BG003C "Varna"
cap label var BG003F "Varna"
cap label var BG004C "Burgas"
cap label var BG004F "Burgas"
cap label var BG005C "Pleven"
cap label var BG005F "Pleven"
cap label var BG006C "Ruse"
cap label var BG006F "Ruse"
cap label var BG007C "Vidin"
cap label var BG007F "Vidin"
cap label var BG008C "Stara Zagora"
cap label var BG008F "Stara Zagora"
cap label var BG009C "Sliven"
cap label var BG009F "Sliven"
cap label var BG010C "Dobrich"
cap label var BG010F "Dobrich"
cap label var BG011C "Shumen"
cap label var BG011F "Shumen"
cap label var BG012C "Pernik"
cap label var BG013C "Yambol"
cap label var BG013F "Yambol"
cap label var BG014C "Haskovo"
cap label var BG014F "Haskovo"
cap label var BG015C "Pazardzhik"
cap label var BG015F "Pazardzhik"
cap label var BG016C "Blagoevgrad"
cap label var BG016F "Blagoevgrad"
cap label var BG017C "Veliko Tarnovo"
cap label var BG017F "Veliko Tarnovo"
cap label var BG018C "Vratsa"
cap label var BG018F "Vratsa"
cap label var CZ "Czechia"
cap label var CZ001C "Praha"
cap label var CZ001F "Praha"
cap label var CZ002C "Brno"
cap label var CZ002F "Brno"
cap label var CZ003C "Ostrava"
cap label var CZ003F "Ostrava"
cap label var CZ004C "Plzeň"
cap label var CZ004F "Plzen"
cap label var CZ005C "Ústí nad Labem"
cap label var CZ005F "Ústí nad Labem"
cap label var CZ006C "Olomouc"
cap label var CZ006F "Olomouc"
cap label var CZ007C "Liberec (greater city)"
cap label var CZ007F "Liberec"
cap label var CZ008C "České Budějovice"
cap label var CZ008F "Ceské Budejovice"
cap label var CZ009C "Hradec Králové"
cap label var CZ009F "Hradec Králové"
cap label var CZ010C "Pardubice"
cap label var CZ010F "Pardubice"
cap label var CZ011C "Zlín"
cap label var CZ011F "Zlín"
cap label var CZ012C "Kladno"
cap label var CZ013C "Karlovy Vary"
cap label var CZ013F "Karlovy Vary"
cap label var CZ014C "Jihlava"
cap label var CZ014F "Jihlava"
cap label var CZ015C "Havířov"
cap label var CZ016C "Most"
cap label var CZ016F "Most"
cap label var CZ017C "Karviná"
cap label var CZ018C "Chomutov-Jirkov (greater city)"
cap label var CZ018F "Chomutov"
cap label var DK "Denmark"
cap label var DK001C "København (greater city)"
cap label var DK001C1 "København"
cap label var DK001F "København"
cap label var DK002C "Århus"
cap label var DK002F "Århus"
cap label var DK003C "Odense"
cap label var DK003F "Odense"
cap label var DK004C "Aalborg"
cap label var DK004F "Aalborg"
cap label var DE "Germany"
cap label var DE001C "Berlin"
cap label var DE001F "Berlin"
cap label var DE002C "Hamburg"
cap label var DE002F "Hamburg"
cap label var DE003C "München"
cap label var DE003F "München"
cap label var DE004C "Köln"
cap label var DE004F "Köln"
cap label var DE005C "Frankfurt am Main"
cap label var DE005F "Frankfurt am Main"
cap label var DE006C "Essen"
cap label var DE006F "Ruhrgebiet"
cap label var DE007C "Stuttgart"
cap label var DE007F "Stuttgart"
cap label var DE008C "Leipzig"
cap label var DE008F "Leipzig"
cap label var DE009C "Dresden"
cap label var DE009F "Dresden"
cap label var DE010C "Dortmund"
cap label var DE011C "Düsseldorf"
cap label var DE011F "Düsseldorf"
cap label var DE012C "Bremen"
cap label var DE012F "Bremen"
cap label var DE013C "Hannover"
cap label var DE013F "Hannover"
cap label var DE014C "Nürnberg"
cap label var DE014F "Nürnberg"
cap label var DE015C "Bochum"
cap label var DE016C "Bielefeld"
cap label var DE016F "Bielefeld"
cap label var DE017C "Halle an der Saale"
cap label var DE017F "Halle an der Saale"
cap label var DE018C "Magdeburg"
cap label var DE018F "Magdeburg"
cap label var DE019C "Wiesbaden"
cap label var DE019F "Wiesbaden"
cap label var DE020C "Göttingen"
cap label var DE020F "Göttingen"
cap label var DE021C "Mülheim a.d.Ruhr"
cap label var DE022C "Moers"
cap label var DE023C "Darmstadt"
cap label var DE023F "Darmstadt"
cap label var DE024C "Trier"
cap label var DE024F "Trier"
cap label var DE025C "Freiburg im Breisgau"
cap label var DE025F "Freiburg im Breisgau"
cap label var DE026C "Regensburg"
cap label var DE026F "Regensburg"
cap label var DE027C "Frankfurt (Oder)"
cap label var DE027F "Frankfurt (Oder)"
cap label var DE028C "Weimar"
cap label var DE028F "Weimar"
cap label var DE029C "Schwerin"
cap label var DE029F "Schwerin"
cap label var DE030C "Erfurt"
cap label var DE030F "Erfurt"
cap label var DE031C "Augsburg"
cap label var DE031F "Augsburg"
cap label var DE032C "Bonn"
cap label var DE032F "Bonn"
cap label var DE033C "Karlsruhe"
cap label var DE033F "Karlsruhe"
cap label var DE034C "Mönchengladbach"
cap label var DE034F "Mönchengladbach"
cap label var DE035C "Mainz"
cap label var DE035F "Mainz"
cap label var DE036C "Kiel"
cap label var DE036F "Kiel"
cap label var DE037C "Saarbrücken"
cap label var DE037F "Saarbrücken"
cap label var DE038C "Potsdam"
cap label var DE039C "Koblenz"
cap label var DE039F "Koblenz"
cap label var DE040C "Rostock"
cap label var DE040F "Rostock"
cap label var DE041C "Kaiserslautern"
cap label var DE041F "Kaiserslautern"
cap label var DE042C "Iserlohn"
cap label var DE042F "Iserlohn"
cap label var DE043C "Esslingen am Neckar"
cap label var DE044C "Hanau"
cap label var DE045C "Wilhelmshaven"
cap label var DE045F "Wilhelmshaven"
cap label var DE046C "Ludwigsburg"
cap label var DE047C "Tübingen"
cap label var DE047F "Tübingen"
cap label var DE048C "Villingen-Schwenningen"
cap label var DE048F "Villingen-Schwenningen"
cap label var DE049C "Flensburg"
cap label var DE049F "Flensburg"
cap label var DE050C "Marburg"
cap label var DE050F "Marburg"
cap label var DE051C "Konstanz"
cap label var DE051F "Konstanz"
cap label var DE052C "Neumünster"
cap label var DE052F "Neumünster"
cap label var DE053C "Brandenburg an der Havel"
cap label var DE053F "Brandenburg an der Havel"
cap label var DE054C "Gießen"
cap label var DE054F "Gießen"
cap label var DE055C "Lüneburg"
cap label var DE056C "Bayreuth"
cap label var DE056F "Bayreuth"
cap label var DE057C "Celle"
cap label var DE057F "Celle"
cap label var DE058C "Aschaffenburg"
cap label var DE058F "Aschaffenburg"
cap label var DE059C "Bamberg"
cap label var DE059F "Bamberg"
cap label var DE060C "Plauen"
cap label var DE060F "Plauen"
cap label var DE061C "Neubrandenburg"
cap label var DE061F "Neubrandenburg"
cap label var DE062C "Fulda"
cap label var DE062F "Fulda"
cap label var DE063C "Kempten (Allgäu)"
cap label var DE063F "Kempten (Allgäu)"
cap label var DE064C "Landshut"
cap label var DE064F "Landshut"
cap label var DE065C "Sindelfingen"
cap label var DE066C "Rosenheim"
cap label var DE066F "Rosenheim"
cap label var DE067C "Frankenthal (Pfalz)"
cap label var DE068C "Stralsund"
cap label var DE068F "Stralsund"
cap label var DE069C "Friedrichshafen"
cap label var DE069F "Friedrichshafen"
cap label var DE070C "Offenburg"
cap label var DE070F "Offenburg"
cap label var DE071C "Görlitz"
cap label var DE071F "Görlitz"
cap label var DE072C "Sankt Augustin"
cap label var DE073C "Neu-Ulm"
cap label var DE074C "Schweinfurt"
cap label var DE074F "Schweinfurt"
cap label var DE075C "Greifswald"
cap label var DE075F "Greifswald"
cap label var DE076C "Wetzlar"
cap label var DE076F "Wetzlar"
cap label var DE077C "Speyer"
cap label var DE077F "Speyer"
cap label var DE078C "Passau"
cap label var DE078F "Passau"
cap label var DE079C "Dessau-Roßlau"
cap label var DE079F "Dessau-Roßlau"
cap label var DE080C "Duisburg"
cap label var DE081C "Mannheim"
cap label var DE081F "Mannheim-Ludwigshafen"
cap label var DE082C "Gelsenkirchen"
cap label var DE083C "Münster"
cap label var DE083F "Münster"
cap label var DE084C "Chemnitz"
cap label var DE084F "Chemnitz"
cap label var DE085C "Braunschweig"
cap label var DE085F "Braunschweig-Salzgitter"
cap label var DE086C "Aachen"
cap label var DE086F "Aachen"
cap label var DE087C "Krefeld"
cap label var DE087F "Krefeld"
cap label var DE088C "Oberhausen"
cap label var DE089C "Lübeck"
cap label var DE089F "Lübeck"
cap label var DE090C "Hagen"
cap label var DE091C "Kassel"
cap label var DE091F "Kassel"
cap label var DE092C "Hamm"
cap label var DE093C "Herne"
cap label var DE094C "Solingen"
cap label var DE094F "Solingen"
cap label var DE095C "Osnabrück"
cap label var DE095F "Osnabrück"
cap label var DE096C "Ludwigshafen am Rhein"
cap label var DE097C "Leverkusen"
cap label var DE098C "Oldenburg (Oldenburg)"
cap label var DE098F "Oldenburg (Oldenburg)"
cap label var DE099C "Neuss"
cap label var DE100C "Heidelberg"
cap label var DE100F "Heidelberg"
cap label var DE101C "Paderborn"
cap label var DE101F "Paderborn"
cap label var DE102C "Würzburg"
cap label var DE102F "Würzburg"
cap label var DE103C "Recklinghausen"
cap label var DE104C "Wolfsburg"
cap label var DE104F "Wolfsburg"
cap label var DE105C "Bremerhaven"
cap label var DE105F "Bremerhaven"
cap label var DE106C "Bottrop"
cap label var DE107C "Heilbronn"
cap label var DE107F "Heilbronn"
cap label var DE108C "Remscheid"
cap label var DE108F "Remscheid"
cap label var DE109C "Offenbach am Main"
cap label var DE110C "Ulm"
cap label var DE110F "Ulm"
cap label var DE111C "Pforzheim"
cap label var DE111F "Pforzheim"
cap label var DE112C "Ingolstadt"
cap label var DE112F "Ingolstadt"
cap label var DE113C "Gera"
cap label var DE113F "Gera"
cap label var DE114C "Salzgitter"
cap label var DE115C "Reutlingen"
cap label var DE115F "Reutlingen"
cap label var DE116C "Fürth"
cap label var DE117C "Cottbus"
cap label var DE117F "Cottbus"
cap label var DE118C "Siegen"
cap label var DE118F "Siegen"
cap label var DE119C "Bergisch Gladbach"
cap label var DE120C "Hildesheim"
cap label var DE120F "Hildesheim"
cap label var DE121C "Witten"
cap label var DE122C "Zwickau"
cap label var DE122F "Zwickau"
cap label var DE123C "Erlangen"
cap label var DE123F "Erlangen"
cap label var DE124C "Wuppertal"
cap label var DE124F "Wuppertal"
cap label var DE125C "Jena"
cap label var DE125F "Jena"
cap label var DE126C "Düren, Stadt"
cap label var DE126F "Düren, Stadt"
cap label var DE127C "Bocholt, Stadt"
cap label var DE127F "Bocholt, Stadt"
cap label var DE128C "Elmshorn"
cap label var DE129C "Norderstedt"
cap label var DE130C "Delmenhorst"
cap label var DE131C "Hilden"
cap label var DE132C "Langenfeld (Rheinland)"
cap label var DE133C "Ratingen"
cap label var DE134C "Dinslaken"
cap label var DE135C "Herzogenrath"
cap label var DE136C "Troisdorf (greater city)"
cap label var DE137C "Castrop-Rauxel"
cap label var DE138C "Gladbeck"
cap label var DE139C "Herten"
cap label var DE140C "Marl"
cap label var DE141C "Gütersloh"
cap label var DE142C "Hattingen"
cap label var DE143C "Lüdenscheid"
cap label var DE144C "Lünen"
cap label var DE145C "Unna"
cap label var DE146C "Rüsselsheim am Main (greater city)"
cap label var DE147C "Oberursel (greater city)"
cap label var DE148C "Böblingen"
cap label var DE149C "Esslingen am Neckar (greater city)"
cap label var DE150C "Göppingen (greater city)"
cap label var DE151C "Ludwigsburg (greater city)"
cap label var DE152C "Waiblingen (greater city)"
cap label var DE153C "Lörrach (greater city)"
cap label var EE "Estonia"
cap label var EE001C "Tallinn"
cap label var EE001F "Tallinn"
cap label var EE002C "Tartu"
cap label var EE002F "Tartu"
cap label var EE003C "Narva"
cap label var EE003F "Narva"
cap label var IE "Ireland"
cap label var IE001C "Dublin (greater city)"
cap label var IE001C1 "Dublin"
cap label var IE001F "Dublin"
cap label var IE002C "Cork (greater city)"
cap label var IE002F "Cork"
cap label var IE003C "Limerick (greater city)"
cap label var IE003F "Limerick"
cap label var IE004C "Galway (greater city)"
cap label var IE004F "Galway"
cap label var IE005C "Waterford (greater city)"
cap label var IE005F "Waterford"
cap label var EL "Greece"
cap label var EL001C "Athina (greater city)"
cap label var EL001C1 "Athina"
cap label var EL001F "Athina"
cap label var EL002C "Thessaloniki (greater city)"
cap label var EL002F "Thessaloniki"
cap label var EL003C "Pátra (greater city)"
cap label var EL003F "Pátra"
cap label var EL004C "Irakleio (greater city)"
cap label var EL004F "Irakleio"
cap label var EL005C "Larisa"
cap label var EL005F "Larisa"
cap label var EL006C "Volos (greater city)"
cap label var EL006F "Volos"
cap label var EL007C "Ioannina (greater city)"
cap label var EL007F "Ioannina"
cap label var EL008C "Kavala"
cap label var EL008F "Kavala"
cap label var EL009C "Kalamata"
cap label var EL009F "Kalamata"
cap label var EL010C "Trikala"
cap label var EL010F "Trikala"
cap label var EL011C "Serres"
cap label var EL011F "Serres"
cap label var EL012C "Katerini"
cap label var EL012F "Katerini"
cap label var EL013C "Xanthi"
cap label var EL013F "Xanthi"
cap label var EL014C "Chania (greater city)"
cap label var EL014F "Chania"
cap label var EL015C "Chalkida"
cap label var ES "Spain"
cap label var ES001C "Madrid (greater city)"
cap label var ES001C1 "Madrid"
cap label var ES001F "Madrid"
cap label var ES002C "Barcelona (greater city)"
cap label var ES002C1 "Barcelona"
cap label var ES002F "Barcelona"
cap label var ES003C "Valencia (greater city)"
cap label var ES003F "Valencia"
cap label var ES004C "Sevilla"
cap label var ES004F "Sevilla"
cap label var ES005C "Zaragoza"
cap label var ES005F "Zaragoza"
cap label var ES006C "Málaga"
cap label var ES006F "Málaga"
cap label var ES007C "Murcia"
cap label var ES007F "Murcia"
cap label var ES008C "Las Palmas"
cap label var ES008F "Las Palmas"
cap label var ES009C "Valladolid (greater city)"
cap label var ES009F "Valladolid"
cap label var ES010C "Palma de Mallorca"
cap label var ES010F "Palma de Mallorca"
cap label var ES011C "Santiago de Compostela"
cap label var ES011F "Santiago de Compostela"
cap label var ES012C "Vitoria/Gasteiz"
cap label var ES012F "Vitoria/Gasteiz"
cap label var ES013C "Oviedo"
cap label var ES013F "Oviedo"
cap label var ES014C "Pamplona/Iruña (greater city)"
cap label var ES014F "Pamplona/Iruña"
cap label var ES015C "Santander"
cap label var ES015F "Santander"
cap label var ES016C "Toledo"
cap label var ES016F "Toledo"
cap label var ES017C "Badajoz"
cap label var ES017F "Badajoz"
cap label var ES018C "Logroño"
cap label var ES018F "Logroño"
cap label var ES019C "Bilbao (greater city)"
cap label var ES019F "Bilbao"
cap label var ES020C "Córdoba"
cap label var ES020F "Córdoba"
cap label var ES021C "Alicante/Alacant (greater city)"
cap label var ES021F "Alicante/Alacant"
cap label var ES022C "Vigo"
cap label var ES022F "Vigo"
cap label var ES023C "Gijón"
cap label var ES023F "Gijón"
cap label var ES024C "Santa Cruz de Tenerife (greater city)"
cap label var ES024F "Santa Cruz de Tenerife"
cap label var ES025C "A Coruña (greater city)"
cap label var ES025F "A Coruña"
cap label var ES026C "Reus"
cap label var ES026F "Reus"
cap label var ES027C "Telde"
cap label var ES028C "Lugo"
cap label var ES028F "Lugo"
cap label var ES029C "San Fernando"
cap label var ES030C "Girona (greater city)"
cap label var ES030F "Girona"
cap label var ES031C "Cáceres"
cap label var ES031F "Cáceres"
cap label var ES032C "Torrevieja"
cap label var ES032F "Torrevieja"
cap label var ES033C "Puerto de Santa María, El"
cap label var ES033F "Puerto de Santa María, El"
cap label var ES034C "Avilés (greater city)"
cap label var ES034F "Avilés"
cap label var ES035C "Talavera de la Reina"
cap label var ES035F "Talavera de la Reina"
cap label var ES036C "Palencia"
cap label var ES036F "Palencia"
cap label var ES037C "Ferrol (greater city)"
cap label var ES037F "Ferrol"
cap label var ES038C "Pontevedra"
cap label var ES038F "Pontevedra"
cap label var ES039C "Ceuta"
cap label var ES039F "Ceuta"
cap label var ES040C "Gandia (greater city)"
cap label var ES040F "Gandia"
cap label var ES041C "Guadalajara"
cap label var ES041F "Guadalajara"
cap label var ES042C "Manresa (greater city)"
cap label var ES042F "Manresa"
cap label var ES043C "Ciudad Real"
cap label var ES043F "Ciudad Real"
cap label var ES044C "Benidorm"
cap label var ES044F "Benidorm"
cap label var ES045C "Melilla"
cap label var ES045F "Melilla"
cap label var ES046C "Ponferrada"
cap label var ES046F "Ponferrada"
cap label var ES047C "Zamora"
cap label var ES047F "Zamora"
cap label var ES048C "Fuengirola"
cap label var ES049C "Sanlúcar de Barrameda"
cap label var ES049F "Sanlúcar de Barrameda"
cap label var ES050C "Vilanova i la Geltrú"
cap label var ES051C "Línea de la Concepción, La"
cap label var ES051F "Línea de la Concepción, La"
cap label var ES052C "Torremolinos (greater city)"
cap label var ES053C "Irun (greater city)"
cap label var ES053F "Irun"
cap label var ES054C "Granollers (greater city)"
cap label var ES055C "Arrecife"
cap label var ES055F "Arrecife"
cap label var ES056C "Elda (greater city)"
cap label var ES056F "Elda"
cap label var ES057C "Santa Lucía de Tirajana"
cap label var ES057F "Santa Lucía de Tirajana"
cap label var ES058C "Mollet del Vallès (greater city)"
cap label var ES059C "Granada (greater city)"
cap label var ES059F "Granada"
cap label var ES060C "Elche/Elx"
cap label var ES060F "Elche/Elx"
cap label var ES061C "Cartagena"
cap label var ES061F "Cartagena"
cap label var ES062C "Jerez de la Frontera"
cap label var ES062F "Jerez de la Frontera"
cap label var ES063C "San Sebastián/Donostia (greater city)"
cap label var ES063F "San Sebastián/Donostia"
cap label var ES064C "Alcalá de Henares"
cap label var ES065C "Almería (greater city)"
cap label var ES065F "Almería"
cap label var ES066C "Burgos"
cap label var ES066F "Burgos"
cap label var ES067C "Salamanca (greater city)"
cap label var ES067F "Salamanca"
cap label var ES068C "Albacete"
cap label var ES068F "Albacete"
cap label var ES069C "Castellón de la Plana/Castelló de la Plana"
cap label var ES069F "Castellón de la Plana/Castelló de la Plana"
cap label var ES070C "Huelva"
cap label var ES070F "Huelva"
cap label var ES071C "Cádiz"
cap label var ES071F "Cádiz"
cap label var ES072C "León (greater city)"
cap label var ES072F "León"
cap label var ES073C "Tarragona (greater city)"
cap label var ES073F "Tarragona"
cap label var ES074C "Jaén"
cap label var ES074F "Jaén"
cap label var ES075C "Lleida"
cap label var ES075F "Lleida"
cap label var ES076C "Ourense (greater city)"
cap label var ES076F "Ourense"
cap label var ES077C "Mataró"
cap label var ES078C "Dos Hermanas"
cap label var ES079C "Algeciras"
cap label var ES079F "Algeciras"
cap label var ES080C "Marbella"
cap label var ES080F "Marbella"
cap label var ES081C "Torrejón de Ardoz"
cap label var ES082C "Alcalá de Guadaíra"
cap label var ES083C "Alcoy"
cap label var ES083F "Alcoy"
cap label var ES084C "Ávila"
cap label var ES084F "Ávila"
cap label var ES085C "Benalmádena"
cap label var ES086C "Chiclana de la Frontera"
cap label var ES086F "Chiclana de la Frontera"
cap label var ES087C "Collado Villalba"
cap label var ES088C "Cuenca"
cap label var ES088F "Cuenca"
cap label var ES089C "Eivissa"
cap label var ES089F "Eivissa"
cap label var ES090C "Linares"
cap label var ES090F "Linares"
cap label var ES091C "Lorca"
cap label var ES091F "Lorca"
cap label var ES092C "Mérida"
cap label var ES092F "Mérida"
cap label var ES093C "Sagunto (greater city)"
cap label var ES093F "Sagunto"
cap label var ES094C "Torrelavega"
cap label var ES095C "Valdemoro"
cap label var ES096C "Puerto de la Cruz (greater city)"
cap label var ES096F "Puerto de la Cruz"
cap label var ES097C "Igualada (greater city)"
cap label var ES097F "Igualada"
cap label var ES098C "San Vicente del Raspeig/Sant Vicent del Raspeig"
cap label var ES099C "Vícar"
cap label var ES100C "Armilla (greater city)"
cap label var ES101C "Mairena del Aljarafe (greater city)"
cap label var ES102C "Aranjuez"
cap label var ES103C "Parla"
cap label var ES104C "Pinto"
cap label var ES105C "Arganda del Rey"
cap label var ES106C "Fuenlabrada"
cap label var ES107C "Rivas-Vaciamadrid"
cap label var ES108C "Coslada (greater city)"
cap label var ES109C "Las Rozas de Madrid (greater city)"
cap label var ES110C "Castelldefels"
cap label var ES111C "Viladecans (greater city)"
cap label var ES112C "Prat de Llobregat, El"
cap label var ES113C "Sant Boi de Llobregat"
cap label var ES114C "Sant Cugat del Vallès (greater city)"
cap label var ES115C "Premià de Mar (greater city)"
cap label var ES116C "Sabadell (greater city)"
cap label var ES117C "Terrassa"
cap label var ES118C "Huesca"
cap label var FR "France"
cap label var FR001C "Paris (greater city)"
cap label var FR001C1 "Paris"
cap label var FR001F "Paris"
cap label var FR002C "Lyon (greater city)"
cap label var FR002F "Lyon"
cap label var FR003C "Lille (greater city)"
cap label var FR003F "Lille"
cap label var FR004C "Marseille (greater city)"
cap label var FR004F "Marseille"
cap label var FR005C "Bordeaux (greater city)"
cap label var FR005F "Bordeaux"
cap label var FR006C "Toulouse (greater city)"
cap label var FR006F "Toulouse"
cap label var FR007C "Nantes (greater city)"
cap label var FR007F "Nantes"
cap label var FR008C "Nice (greater city)"
cap label var FR008F "Nice"
cap label var FR009C "Strasbourg (greater city)"
cap label var FR009F "Strasbourg"
cap label var FR010C "Rouen (greater city)"
cap label var FR010F "Rouen"
cap label var FR011C "Montpellier (greater city)"
cap label var FR011F "Montpellier"
cap label var FR012C "Grenoble (greater city)"
cap label var FR012F "Grenoble"
cap label var FR013C "Tours (greater city)"
cap label var FR013F "Tours"
cap label var FR014C "Cannes-Antibes (greater city)"
cap label var FR014F "Cannes-Antibes"
cap label var FR015C "Toulon (greater city)"
cap label var FR015F "Toulon"
cap label var FR016C "Rennes (greater city)"
cap label var FR016F "Rennes"
cap label var FR017C "Reims (greater city)"
cap label var FR017F "Reims"
cap label var FR018C "Orléans (greater city)"
cap label var FR018F "Orléans"
cap label var FR019C "Nancy (greater city)"
cap label var FR019F "Nancy"
cap label var FR020C "Dijon (greater city)"
cap label var FR020F "Dijon"
cap label var FR021C "Clermont-Ferrand (greater city)"
cap label var FR021F "Clermont-Ferrand"
cap label var FR022C "Le Havre (greater city)"
cap label var FR022F "Le Havre"
cap label var FR023C "Saint-Étienne (greater city)"
cap label var FR023F "Saint-Étienne"
cap label var FR024C "Angers (greater city)"
cap label var FR024F "Angers"
cap label var FR025C "Mulhouse (greater city)"
cap label var FR025F "Mulhouse"
cap label var FR026C "Lens (greater city)"
cap label var FR026F "Lens"
cap label var FR027C "Metz (greater city)"
cap label var FR027F "Metz"
cap label var FR028C "Nîmes"
cap label var FR028F "Nîmes"
cap label var FR029C "Le Mans (greater city)"
cap label var FR029F "Le Mans"
cap label var FR030C "Saint-Denis"
cap label var FR030F "Saint-Denis"
cap label var FR031C "Caen (greater city)"
cap label var FR031F "Caen"
cap label var FR032C "Limoges (greater city)"
cap label var FR032F "Limoges"
cap label var FR033C "Aix-en-Provence"
cap label var FR034C "Brest"
cap label var FR034F "Brest"
cap label var FR035C "Amiens (greater city)"
cap label var FR035F "Amiens"
cap label var FR036C "Dunkerque (greater city)"
cap label var FR036F "Dunkerque"
cap label var FR037C "Perpignan (greater city)"
cap label var FR037F "Perpignan"
cap label var FR038C "Annecy (greater city)"
cap label var FR038F "Annecy"
cap label var FR039C "Besançon"
cap label var FR039F "Besançon"
cap label var FR040C "Bayonne (greater city)"
cap label var FR040F "Bayonne"
cap label var FR041C "La Seyne-sur-Mer (greater city)"
cap label var FR042C "Pau (greater city)"
cap label var FR042F "Pau"
cap label var FR043C "Avignon (greater city)"
cap label var FR043F "Avignon"
cap label var FR044C "Troyes (greater city)"
cap label var FR044F "Troyes"
cap label var FR045C "Valenciennes (greater city)"
cap label var FR045F "Valenciennes"
cap label var FR046C "Fort-de-France (greater city)"
cap label var FR046F "Fort-de-France"
cap label var FR047C "Poitiers (greater city)"
cap label var FR047F "Poitiers"
cap label var FR048C "Valence (greater city)"
cap label var FR048F "Valence"
cap label var FR049C "Fréjus (greater city)"
cap label var FR049F "Fréjus"
cap label var FR050C "Chambéry (greater city)"
cap label var FR050F "Chambéry"
cap label var FR051C "Mantes-la-Jolie (greater city)"
cap label var FR052C "Douai (greater city)"
cap label var FR052F "Douai"
cap label var FR053C "Melun (greater city)"
cap label var FR054C "La Rochelle (greater city)"
cap label var FR054F "La Rochelle"
cap label var FR055C "Lorient (greater city)"
cap label var FR055F "Lorient"
cap label var FR056C "Cherbourg-en-Cotentin"
cap label var FR056F "Cherbourg-en-Cotentin"
cap label var FR057C "Béziers"
cap label var FR057F "Béziers"
cap label var FR058C "Chartres (greater city)"
cap label var FR058F "Chartres"
cap label var FR059C "Creil (greater city)"
cap label var FR060C "Boulogne-sur-Mer (greater city)"
cap label var FR060F "Boulogne-sur-mer"
cap label var FR061C "Calais (greater city)"
cap label var FR061F "Calais"
cap label var FR062C "Mamoudzou"
cap label var FR062F "Mamoudzou"
cap label var FR063C "Montbéliard (greater city)"
cap label var FR063F "Montbéliard"
cap label var FR064C "Arras (greater city)"
cap label var FR064F "Arras"
cap label var FR065C "Colmar (greater city)"
cap label var FR065F "Colmar"
cap label var FR066C "Martigues (greater city)"
cap label var FR067C "Meaux (greater city)"
cap label var FR068C "Bourges"
cap label var FR068F "Bourges"
cap label var FR069C "Saint-Brieuc (greater city)"
cap label var FR069F "Saint-Brieuc"
cap label var FR070C "Quimper"
cap label var FR070F "Quimper"
cap label var FR071C "Belfort (greater city)"
cap label var FR071F "Belfort"
cap label var FR072C "Cayenne"
cap label var FR072F "Cayenne"
cap label var FR073C "Hayange"
cap label var FR073F "Hayange"
cap label var FR074C "Saint-Louis"
cap label var FR074F "Saint-Louis"
cap label var FR075C "Vannes"
cap label var FR075F "Vannes"
cap label var FR076C "Annemasse-Geneva (French part) (greater city)"
cap label var FR076F "Annemasse-Geneva (French part)"
cap label var FR077C "Saint-Louis-Bâle, (French part) (greater city)"
cap label var FR077F "Saint-Louis-Basel (French part)"
cap label var FR078C "Ajaccio"
cap label var FR079C "Roanne (greater city)"
cap label var FR080C "Irun-Hendaye, FR part"
cap label var FR081C "Tarbes (greater city)"
cap label var HR "Croatia"
cap label var HR001C "Zagreb"
cap label var HR001F "Zagreb"
cap label var HR002C "Rijeka"
cap label var HR002F "Rijeka"
cap label var HR003C "Slavonski Brod"
cap label var HR003F "Slavonski Brod"
cap label var HR004C "Osijek"
cap label var HR004F "Osijek"
cap label var HR005C "Split (greater city)"
cap label var HR005F "Split"
cap label var HR006C "Pula/Pola"
cap label var HR006F "Pula/Pola"
cap label var HR007C "Zadar"
cap label var HR007F "Zadar"
cap label var IT "Italy"
cap label var IT001C "Roma"
cap label var IT001F "Roma"
cap label var IT002C "Milano (greater city)"
cap label var IT002F "Milano"
cap label var IT003C "Napoli (greater city)"
cap label var IT003C1 "Napoli"
cap label var IT003F "Napoli"
cap label var IT004C "Torino"
cap label var IT004F "Torino"
cap label var IT005C "Palermo"
cap label var IT005F "Palermo"
cap label var IT006C "Genova"
cap label var IT006F "Genova"
cap label var IT007C "Firenze"
cap label var IT007F "Firenze"
cap label var IT008C "Bari"
cap label var IT008F "Bari"
cap label var IT009C "Bologna"
cap label var IT009F "Bologna"
cap label var IT010C "Catania (greater city)"
cap label var IT010F "Catania"
cap label var IT011C "Venezia"
cap label var IT011F "Venezia"
cap label var IT012C "Verona"
cap label var IT012F "Verona"
cap label var IT013C "Cremona"
cap label var IT013F "Cremona"
cap label var IT014C "Trento"
cap label var IT014F "Trento"
cap label var IT015C "Trieste"
cap label var IT015F "Trieste"
cap label var IT016C "Perugia"
cap label var IT016F "Perugia"
cap label var IT017C "Ancona"
cap label var IT017F "Ancona"
cap label var IT018C "Pescara (greater city)"
cap label var IT018F "Pescara"
cap label var IT019C "Campobasso"
cap label var IT019F "Campobasso"
cap label var IT020C "Caserta  (greater city)"
cap label var IT020F "Caserta"
cap label var IT021C "Taranto"
cap label var IT021F "Taranto"
cap label var IT022C "Potenza"
cap label var IT022F "Potenza"
cap label var IT023C "Catanzaro"
cap label var IT023F "Catanzaro"
cap label var IT024C "Reggio di Calabria"
cap label var IT024F "Reggio di Calabria"
cap label var IT025C "Sassari"
cap label var IT025F "Sassari"
cap label var IT026C "Cagliari (greater city)"
cap label var IT026F "Cagliari"
cap label var IT027C "Padova"
cap label var IT027F "Padova"
cap label var IT028C "Brescia"
cap label var IT028F "Brescia"
cap label var IT029C "Modena"
cap label var IT029F "Modena"
cap label var IT030C "Foggia"
cap label var IT030F "Foggia"
cap label var IT031C "Salerno"
cap label var IT031F "Salerno"
cap label var IT032C "Piacenza"
cap label var IT032F "Piacenza"
cap label var IT033C "Bolzano"
cap label var IT033F "Bolzano"
cap label var IT034C "Udine"
cap label var IT034F "Udine"
cap label var IT035C "La Spezia"
cap label var IT035F "La Spezia"
cap label var IT036C "Lecce"
cap label var IT036F "Lecce"
cap label var IT037C "Barletta"
cap label var IT037F "Barletta"
cap label var IT038C "Pesaro"
cap label var IT038F "Pesaro"
cap label var IT039C "Como"
cap label var IT039F "Como"
cap label var IT040C "Pisa"
cap label var IT040F "Pisa"
cap label var IT041C "Treviso"
cap label var IT041F "Treviso"
cap label var IT042C "Varese"
cap label var IT042F "Varese"
cap label var IT043C "Asti"
cap label var IT043F "Asti"
cap label var IT044C "Pavia"
cap label var IT044F "Pavia"
cap label var IT045C "Massa"
cap label var IT045F "Massa"
cap label var IT046C "Cosenza (greater city)"
cap label var IT046F "Cosenza"
cap label var IT047C "Savona"
cap label var IT047F "Savona"
cap label var IT048C "Matera"
cap label var IT048F "Matera"
cap label var IT049C "Acireale (greater city)"
cap label var IT049F "Acireale"
cap label var IT050C "Avellino"
cap label var IT050F "Avellino"
cap label var IT051C "Pordenone"
cap label var IT051F "Pordenone"
cap label var IT052C "Lecco"
cap label var IT052F "Lecco"
cap label var IT053C "Altamura"
cap label var IT053F "Altamura"
cap label var IT054C "Bitonto"
cap label var IT055C "Molfetta"
cap label var IT056C "Battipaglia"
cap label var IT056F "Battipaglia"
cap label var IT057C "Bisceglie"
cap label var IT057F "Bisceglie"
cap label var IT058C "Carpi"
cap label var IT058F "Carpi"
cap label var IT059C "Cerignola"
cap label var IT059F "Cerignola"
cap label var IT060C "Gela"
cap label var IT060F "Gela"
cap label var IT061C "Bagheria"
cap label var IT062C "Anzio (greater city)"
cap label var IT063C "Sassuolo"
cap label var IT063F "Sassuolo"
cap label var IT064C "Messina"
cap label var IT064F "Messina"
cap label var IT065C "Prato"
cap label var IT065F "Prato"
cap label var IT066C "Parma"
cap label var IT066F "Parma"
cap label var IT067C "Livorno"
cap label var IT067F "Livorno"
cap label var IT068C "Reggio nell'Emilia"
cap label var IT068F "Reggio nell'Emilia"
cap label var IT069C "Ravenna"
cap label var IT069F "Ravenna"
cap label var IT070C "Ferrara"
cap label var IT070F "Ferrara"
cap label var IT071C "Rimini"
cap label var IT071F "Rimini"
cap label var IT072C "Siracusa"
cap label var IT072F "Siracusa"
cap label var IT073C "Bergamo (greater city)"
cap label var IT073F "Bergamo"
cap label var IT074C "Forlì"
cap label var IT074F "Forlì"
cap label var IT075C "Latina"
cap label var IT075F "Latina"
cap label var IT076C "Vicenza"
cap label var IT076F "Vicenza"
cap label var IT077C "Terni"
cap label var IT077F "Terni"
cap label var IT078C "Novara"
cap label var IT078F "Novara"
cap label var IT079C "Alessandria"
cap label var IT079F "Alessandria"
cap label var IT080C "Arezzo"
cap label var IT080F "Arezzo"
cap label var IT081C "Grosseto"
cap label var IT081F "Grosseto"
cap label var IT082C "Brindisi"
cap label var IT082F "Brindisi"
cap label var IT083C "Trapani"
cap label var IT083F "Trapani"
cap label var IT084C "Ragusa"
cap label var IT084F "Ragusa"
cap label var IT085C "Andria"
cap label var IT085F "Andria"
cap label var IT086C "Trani"
cap label var IT086F "Trani"
cap label var IT087C "L'Aquila"
cap label var IT087F "L'Aquila"
cap label var IT088C "Vigevano"
cap label var IT089C "Guidonia Montecelio (greater city)"
cap label var IT090C "Tivoli"
cap label var CY "Cyprus"
cap label var CY001C "Lefkosia (greater city)"
cap label var CY001F "Lefkosia"
cap label var CY002C "Larnaka (greater city)"
cap label var CY002F "Larnaka"
cap label var CY003C "Lemesos (greater city)"
cap label var CY003F "Lemesos"
cap label var LV "Latvia"
cap label var LV001C "Rīga"
cap label var LV001F "Riga"
cap label var LV002C "Liepāja"
cap label var LV002F "Liepaja"
cap label var LV003C "Jelgava"
cap label var LV003F "Jelgava"
cap label var LV004C "Daugavpils"
cap label var LV004F "Daugavpils"
cap label var LV005C "Jurmala"
cap label var LV006C "Ventspils"
cap label var LV007C "Rezekne"
cap label var LV008C "Valmiera"
cap label var LV009C "Jekabpils"
cap label var LV010C "Ogre"
cap label var LT "Lithuania"
cap label var LT001C "Vilnius"
cap label var LT001F "Vilnius"
cap label var LT002C "Kaunas"
cap label var LT002F "Kaunas"
cap label var LT003C "Panevėžys"
cap label var LT003F "Panevežys"
cap label var LT004C "Alytus"
cap label var LT004F "Alytus"
cap label var LT005C "Klaipėda"
cap label var LT005F "Klaipeda"
cap label var LT006C "Šiauliai"
cap label var LT006F "Šiauliai"
cap label var LU "Luxembourg"
cap label var LU001C "Luxembourg (greater city)"
cap label var LU001F "Luxembourg"
cap label var HU "Hungary"
cap label var HU001C "Budapest (greater city)"
cap label var HU001F "Budapest"
cap label var HU002C "Miskolc"
cap label var HU002F "Miskolc"
cap label var HU003C "Nyíregyháza"
cap label var HU003F "Nyíregyháza"
cap label var HU004C "Pécs"
cap label var HU004F "Pécs"
cap label var HU005C "Debrecen"
cap label var HU005F "Debrecen"
cap label var HU006C "Szeged"
cap label var HU006F "Szeged"
cap label var HU007C "Gyõr"
cap label var HU007F "Gyõr"
cap label var HU008C "Kecskemét"
cap label var HU008F "Kecskemét"
cap label var HU009C "Székesfehérvár"
cap label var HU009F "Székesfehérvár"
cap label var HU010C "Szombathely"
cap label var HU010F "Szombathely"
cap label var HU011C "Szolnok"
cap label var HU011F "Szolnok"
cap label var HU012C "Tatabánya"
cap label var HU012F "Tatabánya"
cap label var HU013C "Veszprém"
cap label var HU013F "Veszprém"
cap label var HU014C "Békéscsaba"
cap label var HU014F "Békéscsaba"
cap label var HU015C "Kaposvár"
cap label var HU015F "Kaposvár"
cap label var HU016C "Eger"
cap label var HU016F "Eger"
cap label var HU017C "Dunaújváros"
cap label var HU017F "Dunaújváros"
cap label var HU018C "Zalaegerszeg"
cap label var HU018F "Zalaegerszeg"
cap label var HU019C "Sopron"
cap label var HU019F "Sopron"
cap label var MT "Malta"
cap label var MT001C "Greater Valletta"
cap label var MT001F "Malta"
cap label var NL "Netherlands"
cap label var NL001C "Amsterdam (greater city)"
cap label var NL001F "Amsterdam"
cap label var NL002C "Alkmaar (greater city)"
cap label var NL002F "Alkmaar"
cap label var NL003C "Almelo"
cap label var NL003F "Almelo"
cap label var NL004C "Almere"
cap label var NL005C "Alphen aan den Rijn"
cap label var NL005F "Alphen aan den Rijn"
cap label var NL006C "Amersfoort"
cap label var NL006F "Amersfoort"
cap label var NL007C "Apeldoorn"
cap label var NL007F "Apeldoorn"
cap label var NL008C "Arnhem"
cap label var NL008F "Arnhem"
cap label var NL009C "Assen"
cap label var NL009F "Assen"
cap label var NL010C "Bergen op Zoom"
cap label var NL010F "Bergen op Zoom"
cap label var NL011C "Breda"
cap label var NL011F "Breda"
cap label var NL012C "Deventer"
cap label var NL012F "Deventer"
cap label var NL013C "Ede"
cap label var NL013F "Ede"
cap label var NL014C "Eindhoven (greater city)"
cap label var NL014F "Eindhoven"
cap label var NL015C "Enschede"
cap label var NL015F "Enschede"
cap label var NL016C "Gouda"
cap label var NL016F "Gouda"
cap label var NL017C "'s-Gravenhage (greater city)"
cap label var NL017F "'s-Gravenhage"
cap label var NL018C "Groningen"
cap label var NL018F "Groningen"
cap label var NL019C "Haarlem (greater city)"
cap label var NL020C "Haarlemmermeer"
cap label var NL021C "Heemskerk (greater city)"
cap label var NL022C "Heerlen (greater city)"
cap label var NL022F "Heerlen"
cap label var NL023C "Helmond"
cap label var NL024C "Hengelo"
cap label var NL025C "'s-Hertogenbosch"
cap label var NL025F "'s-Hertogenbosch"
cap label var NL026C "Hilversum"
cap label var NL027C "Hoorn"
cap label var NL028C "Leeuwarden"
cap label var NL028F "Leeuwarden"
cap label var NL029C "Leiden (greater city)"
cap label var NL029F "Leiden"
cap label var NL030C "Lelystad"
cap label var NL030F "Lelystad"
cap label var NL031C "Maastricht"
cap label var NL031F "Maastricht"
cap label var NL032C "Middelburg       "
cap label var NL032F "Middelburg"
cap label var NL033C "Nijmegen"
cap label var NL033F "Nijmegen"
cap label var NL034C "Nissewaard (greater city)"
cap label var NL035C "Oss"
cap label var NL035F "Oss"
cap label var NL036C "Purmerend"
cap label var NL037C "Rotterdam (greater city)"
cap label var NL037F "Rotterdam"
cap label var NL038C "Roosendaal"
cap label var NL038F "Roosendaal"
cap label var NL039C "Sittard-Geleen (greater city)"
cap label var NL039F "Sittard-Geleen"
cap label var NL040C "Soest (greater city)"
cap label var NL040F "Soest"
cap label var NL041C "Tilburg (greater city)"
cap label var NL041F "Tilburg"
cap label var NL042C "Utrecht (greater city)"
cap label var NL042F "Utrecht"
cap label var NL043C "Veenendaal"
cap label var NL043F "Veenendaal"
cap label var NL044C "Venlo"
cap label var NL044F "Venlo"
cap label var NL045C "Zaanstad (greater city)"
cap label var NL046C "Zoetermeer"
cap label var NL047C "Zwolle"
cap label var NL047F "Zwolle"
cap label var NL048C "Lansingerland (greater city)"
cap label var AT "Austria"
cap label var AT001C "Wien (greater city)"
cap label var AT001F "Wien"
cap label var AT002C "Graz"
cap label var AT002F "Graz"
cap label var AT003C "Linz (greater city)"
cap label var AT003F "Linz"
cap label var AT004C "Salzburg"
cap label var AT004F "Salzburg"
cap label var AT005C "Innsbruck"
cap label var AT005F "Innsbruck"
cap label var AT006C "Klagenfurt"
cap label var AT006F "Klagenfurt"
cap label var AT007C "Bregenz (greater city)"
cap label var AT008C "Wels"
cap label var PL "Poland"
cap label var PL001C "Warszawa"
cap label var PL001F "Warszawa"
cap label var PL002C "Łódź"
cap label var PL002F "Lódz"
cap label var PL003C "Kraków"
cap label var PL003F "Kraków"
cap label var PL004C "Wrocław"
cap label var PL004F "Wroclaw"
cap label var PL005C "Poznań"
cap label var PL005F "Poznan"
cap label var PL006C "Gdańsk"
cap label var PL006F "Gdansk"
cap label var PL007C "Szczecin"
cap label var PL007F "Szczecin"
cap label var PL008C "Bydgoszcz"
cap label var PL008F "Bydgoszcz"
cap label var PL009C "Lublin"
cap label var PL009F "Lublin"
cap label var PL010C "Katowice"
cap label var PL010F "Katowice"
cap label var PL011C "Białystok"
cap label var PL011F "Bialystok"
cap label var PL012C "Kielce"
cap label var PL012F "Kielce"
cap label var PL013C "Toruń"
cap label var PL013F "Torun"
cap label var PL014C "Olsztyn"
cap label var PL014F "Olsztyn"
cap label var PL015C "Rzeszów"
cap label var PL015F "Rzeszów"
cap label var PL016C "Opole"
cap label var PL016F "Opole"
cap label var PL017C "Gorzów Wielkopolski"
cap label var PL017F "Gorzów Wielkopolski"
cap label var PL018C "Zielona Góra"
cap label var PL018F "Zielona Góra"
cap label var PL019C "Jelenia Góra"
cap label var PL019F "Jelenia Góra"
cap label var PL020C "Nowy Sącz"
cap label var PL020F "Nowy Sacz"
cap label var PL021C "Suwałki"
cap label var PL021F "Suwalki"
cap label var PL022C "Konin"
cap label var PL022F "Konin"
cap label var PL023C "Zory"
cap label var PL024C "Częstochowa"
cap label var PL024F "Czestochowa"
cap label var PL025C "Radom"
cap label var PL025F "Radom"
cap label var PL026C "Płock"
cap label var PL026F "Plock"
cap label var PL027C "Kalisz"
cap label var PL027F "Kalisz"
cap label var PL028C "Koszalin"
cap label var PL028F "Koszalin"
cap label var PL029C "Słupsk"
cap label var PL029F "Slupsk"
cap label var PL030C "Jastrzębie-Zdrój"
cap label var PL030F "Jastrzebie-Zdrój"
cap label var PL031C "Siedlce"
cap label var PL031F "Siedlce"
cap label var PL032C "Piotrków Trybunalski"
cap label var PL032F "Piotrków Trybunalski"
cap label var PL033C "Lubin"
cap label var PL033F "Lubin"
cap label var PL034C "Piła"
cap label var PL034F "Pila"
cap label var PL035C "Inowroc?aw"
cap label var PL035F "Inowroclaw"
cap label var PL036C "Ostrowiec Swietokrzyski"
cap label var PL036F "Ostrowiec Swietokrzyski"
cap label var PL037C "Gniezno"
cap label var PL037F "Gniezno"
cap label var PL038C "Stargard"
cap label var PL038F "Stargard"
cap label var PL039C "Ostrów Wielkopolski"
cap label var PL039F "Ostrów Wielkopolski"
cap label var PL040C "Przemysl"
cap label var PL040F "Przemysl"
cap label var PL041C "Zamość"
cap label var PL041F "Zamosc"
cap label var PL042C "Chełm"
cap label var PL042F "Chelm"
cap label var PL043C "Pabianice"
cap label var PL043F "Pabianice"
cap label var PL044C "Głogów"
cap label var PL044F "Glogów"
cap label var PL045C "Stalowa Wola"
cap label var PL045F "Stalowa Wola"
cap label var PL046C "Tomaszów Mazowiecki"
cap label var PL046F "Tomaszów Mazowiecki"
cap label var PL047C "Łomża"
cap label var PL047F "Lomza"
cap label var PL048C "Leszno"
cap label var PL048F "Leszno"
cap label var PL049C "Swidnica"
cap label var PL049F "Swidnica"
cap label var PL050C "Zgierz"
cap label var PL051C "Tczew"
cap label var PL051F "Tczew"
cap label var PL052C "Ełk"
cap label var PL052F "Elk"
cap label var PL053C "Gdynia"
cap label var PL054C "Sosnowiec"
cap label var PL055C "Gliwice"
cap label var PL056C "Zabrze"
cap label var PL057C "Bytom"
cap label var PL058C "Bielsko-Biała"
cap label var PL058F "Bielsko-Biala"
cap label var PL059C "Ruda Śląska"
cap label var PL060C "Rybnik"
cap label var PL060F "Rybnik"
cap label var PL061C "Tychy"
cap label var PL062C "Wałbrzych"
cap label var PL062F "Walbrzych"
cap label var PL063C "Elbląg"
cap label var PL063F "Elblag"
cap label var PL064C "Włocławek"
cap label var PL064F "Wloclawek"
cap label var PL065C "Tarnów"
cap label var PL065F "Tarnów"
cap label var PL066C "Chorzów"
cap label var PL067C "Legnica"
cap label var PL067F "Legnica"
cap label var PL068C "Grudziądz"
cap label var PL068F "Grudziadz"
cap label var PL069C "Będzin"
cap label var PL070C "Dąbrowa Górnicza"
cap label var PL071C "Legionowo"
cap label var PL072C "Mysłowice"
cap label var PL073C "Pruszków"
cap label var PL074C "Siemianowice Śląskie"
cap label var PL075C "Świętochłowice"
cap label var PT "Portugal"
cap label var PT001C "Lisboa (greater city)"
cap label var PT001C1 "Lisboa"
cap label var PT001F "Lisboa"
cap label var PT002C "Porto (greater city)"
cap label var PT002F "Porto"
cap label var PT003C "Braga (greater city)"
cap label var PT003F "Braga"
cap label var PT004C "Funchal (greater city)"
cap label var PT004F "Funchal"
cap label var PT005C "Coimbra (greater city)"
cap label var PT005F "Coimbra"
cap label var PT006C "Setúbal (greater city)"
cap label var PT007C "Ponta Delgada (greater city)"
cap label var PT007F "Ponta Delgada"
cap label var PT008C "Aveiro (greater city)"
cap label var PT008F "Aveiro"
cap label var PT009C "Faro (greater city)"
cap label var PT009F "Faro"
cap label var PT010C "Viseu (greater city)"
cap label var PT010F "Viseu"
cap label var PT011C "Viana do Castelo (greater city)"
cap label var PT011F "Viana do Castelo"
cap label var PT012C "Paredes (greater city)"
cap label var PT013C "Póvoa de Varzim (greater city)"
cap label var PT013F "Póvoa de Varzim"
cap label var PT014C "Sintra (greater city)"
cap label var PT015C "Guimarães (greater city)"
cap label var PT015F "Guimarães"
cap label var PT016C "Vila Franca de Xira (greater city)"
cap label var RO "Romania"
cap label var RO001C "Bucuresti"
cap label var RO001F "Bucuresti"
cap label var RO002C "Cluj-Napoca"
cap label var RO002F "Cluj-Napoca"
cap label var RO003C "Timișoara (greater city)"
cap label var RO003F "Timisoara"
cap label var RO004C "Craiova"
cap label var RO004F "Craiova"
cap label var RO005C "Brăila"
cap label var RO005F "Braila"
cap label var RO006C "Oradea"
cap label var RO006F "Oradea"
cap label var RO007C "Bacău"
cap label var RO007F "Bacau"
cap label var RO008C "Arad"
cap label var RO008F "Arad"
cap label var RO009C "Sibiu"
cap label var RO009F "Sibiu"
cap label var RO010C "Târgu Mureș"
cap label var RO010F "Târgu Mures"
cap label var RO011C "Piatra-Neamț"
cap label var RO011F "Piatra Neamt"
cap label var RO012C "Călărași"
cap label var RO012F "Calarasi"
cap label var RO013C "Giurgiu"
cap label var RO013F "Giurgiu"
cap label var RO014C "Alba Iulia"
cap label var RO014F "Alba Iulia"
cap label var RO015C "Focșani"
cap label var RO015F "Focsani"
cap label var RO016C "Târgu Jiu"
cap label var RO016F "Târgu Jiu"
cap label var RO017C "Tulcea"
cap label var RO017F "Tulcea"
cap label var RO018C "Târgoviște"
cap label var RO018F "Târgoviste"
cap label var RO019C "Slatina"
cap label var RO019F "Slatina"
cap label var RO020C "Bârlad"
cap label var RO020F "Bârlad"
cap label var RO021C "Roman"
cap label var RO021F "Roman"
cap label var RO022C "Bistrița"
cap label var RO022F "Bistrita"
cap label var RO023C "Constanța"
cap label var RO023F "Constanta"
cap label var RO024C "Iași (greater city)"
cap label var RO024F "Iasi"
cap label var RO025C "Galați"
cap label var RO025F "Galati"
cap label var RO026C "Brașov"
cap label var RO026F "Brasov"
cap label var RO027C "Ploiești"
cap label var RO027F "Ploiesti"
cap label var RO028C "Pitești"
cap label var RO028F "Pitesti"
cap label var RO029C "Baia Mare"
cap label var RO029F "Baia Mare"
cap label var RO030C "Buzău"
cap label var RO030F "Buzau"
cap label var RO031C "Satu Mare"
cap label var RO031F "Satu Mare"
cap label var RO032C "Botoșani"
cap label var RO032F "Botosani"
cap label var RO033C "Râmnicu Vâlcea"
cap label var RO033F "Râmnicu Vâlcea"
cap label var RO034C "Suceava"
cap label var RO034F "Suceava"
cap label var RO035C "Drobeta-Turnu Severin"
cap label var RO035F "Drobeta-Turnu Severin"
cap label var RO040C "Vaslui"
cap label var RO049C "Deva"
cap label var SI "Slovenia"
cap label var SI001C "Ljubljana"
cap label var SI001F "Osrednjeslovenska"
cap label var SI002C "Maribor"
cap label var SI002F "Podravska"
cap label var SK "Slovakia"
cap label var SK001C "Bratislava (greater city)"
cap label var SK001F "Bratislava"
cap label var SK002C "Košice (greater city)"
cap label var SK002F "Košice"
cap label var SK003C "Banská Bystrica"
cap label var SK003F "Banská Bystrica"
cap label var SK004C "Nitra"
cap label var SK004F "Nitra"
cap label var SK005C "Prešov"
cap label var SK005F "Prešov"
cap label var SK006C "Žilina"
cap label var SK006F "Žilina"
cap label var SK007C "Trnava"
cap label var SK007F "Trnava"
cap label var SK008C "Trenčín"
cap label var SK008F "Trencín"
cap label var FI "Finland"
cap label var FI001C "Helsinki/Helsingfors"
cap label var FI001C2 "Helsinki / Helsingfors"
cap label var FI001F "Helsinki/Helsingfors"
cap label var FI002C "Tampere/Tammerfors"
cap label var FI002F "Tampere/Tammerfors"
cap label var FI003C "Turku/Åbo"
cap label var FI003F "Turku/Åbo"
cap label var FI004C "Oulu/Uleåborg"
cap label var FI004F "Oulu/Uleåborg"
cap label var FI005C "Espoo/Esbo"
cap label var FI006C "Vantaa/Vanda"
cap label var FI007C "Lahti/Lahtis"
cap label var FI007F "Lahti/Lahtis"
cap label var FI008C "Kuopio"
cap label var FI008F "Kuopio"
cap label var FI009C "Jyväskylä"
cap label var FI009F "Jyväskylä"
cap label var SE "Sweden"
cap label var SE001C "Stockholm (greater city)"
cap label var SE001C1 "Stockholm"
cap label var SE001F "Stockholm"
cap label var SE002C "Göteborg (greater city)"
cap label var SE002F "Göteborg"
cap label var SE003C "Malmö"
cap label var SE003F "Malmö"
cap label var SE004C "Jönköping"
cap label var SE004F "Jönköping"
cap label var SE005C "Umeå"
cap label var SE005F "Umeå"
cap label var SE006C "Uppsala"
cap label var SE006F "Uppsala"
cap label var SE007C "Linköping"
cap label var SE007F "Linköping"
cap label var SE008C "Örebro"
cap label var SE008F "Örebro"
cap label var SE009C "Södertälje"
cap label var SE009F "Södertälje"
cap label var SE010C "Västerås"
cap label var SE010F "Västerås"
cap label var SE011C "Norrköping"
cap label var SE011F "Norrköping"
cap label var SE012C "Helsingborg"
cap label var SE012F "Helsingborg"
cap label var SE013C "Lund"
cap label var SE014C "Borås"
cap label var SE014F "Borås"
cap label var SE015C "Växjö"
cap label var IS "Iceland"
cap label var IS001C "Reykjavík"
cap label var IS001F "Reykjavík"
cap label var LI001C1 "Vaduz"
cap label var LI002C1 "Schaan"
cap label var NO "Norway"
cap label var NO001C "Oslo (greater city)"
cap label var NO001F "Oslo"
cap label var NO002C "Bergen"
cap label var NO002F "Bergen"
cap label var NO003C "Trondheim"
cap label var NO003F "Trondheim"
cap label var NO004C "Stavanger (greater city)"
cap label var NO004F "Stavanger"
cap label var CH "Switzerland"
cap label var CH001C "Bern (greater city)"
cap label var CH001C1 "Zürich"
cap label var CH001F "Bern"
cap label var CH002C "Zurich (greater city)"
cap label var CH002C1 "Genève"
cap label var CH002F "Zürich"
cap label var CH003C "Geneva (greater city)"
cap label var CH003F "Genève"
cap label var CH003T "Geneva crossborder FUA"
cap label var CH004C "Basel (greater city)"
cap label var CH004F "Basel"
cap label var CH004T "Basel crossborder FUA"
cap label var CH005C "Lausanne (greater city)"
cap label var CH005F "Lausanne"
cap label var CH006C "Lucerne (greater city)"
cap label var CH006F "Luzern"
cap label var CH007C "Winterthur"
cap label var CH008C "Lugano (greater city)"
cap label var CH008F "Lugano"
cap label var CH009C "St. Gallen (greater city)"
cap label var CH009F "St. Gallen"
cap label var CH010C "Biel/Bienne (greater city)"
cap label var CH010F "Biel/Bienne"
cap label var CH011C "Thun (greater city)"
cap label var CH012C "Zug (greater city)"
cap label var CH012F "Zug"
cap label var CH013C "Fribourg (greater city)"
cap label var CH014C "Montreux – Vevey (greater city)"
cap label var CH015C "Aarau (greater city)"
cap label var UK "United Kingdom"
cap label var UK001C "London"
cap label var UK001F "London"
cap label var UK002C "Birmingham"
cap label var UK002F "West Midlands urban area"
cap label var UK003C "Leeds"
cap label var UK003F "Leeds"
cap label var UK004C "Glasgow"
cap label var UK004C1 "Glasgow City"
cap label var UK004F "Glasgow"
cap label var UK005C "Bradford"
cap label var UK006C "Liverpool"
cap label var UK006F "Liverpool"
cap label var UK007C "Edinburgh"
cap label var UK007F "Edinburgh"
cap label var UK008C "Manchester"
cap label var UK008C1 "Manchester"
cap label var UK008F "Manchester"
cap label var UK009C "Cardiff"
cap label var UK009F "Cardiff"
cap label var UK010C "Sheffield"
cap label var UK010F "Sheffield"
cap label var UK011C "Bristol"
cap label var UK011F "Bristol"
cap label var UK012C "Belfast"
cap label var UK012C2 "Belfast"
cap label var UK012F "Belfast"
cap label var UK013C "Newcastle upon Tyne"
cap label var UK013C1 "Newcastle upon Tyne"
cap label var UK013F "Newcastle upon Tyne"
cap label var UK014C "Leicester"
cap label var UK014F "Leicester"
cap label var UK015C "Aberdeen"
cap label var UK015F "Aberdeen"
cap label var UK016C "Cambridge"
cap label var UK016F "Cambridge"
cap label var UK017C "Exeter"
cap label var UK017F "Exeter"
cap label var UK018C "Lincoln"
cap label var UK018F "Lincoln"
cap label var UK019C "Gravesham"
cap label var UK020C "Stevenage"
cap label var UK020F "Stevenage"
cap label var UK021C "Wrexham"
cap label var UK021F "Wrexham"
cap label var UK022C "Portsmouth"
cap label var UK022F "Portsmouth"
cap label var UK023C "Worcester"
cap label var UK023F "Worcester"
cap label var UK024C "Coventry"
cap label var UK024F "Coventry"
cap label var UK025C "Kingston-upon-Hull"
cap label var UK025F "Kingston upon Hull"
cap label var UK026C "Stoke-on-Trent"
cap label var UK026F "Stoke-on-Trent"
cap label var UK027C "Wolverhampton"
cap label var UK028C "Nottingham"
cap label var UK028F "Nottingham"
cap label var UK029C "Wirral"
cap label var UK030C "Bath and North East Somerset"
cap label var UK030F "Bath and North East Somerset"
cap label var UK031C "Thurrock"
cap label var UK032C "Guildford"
cap label var UK032F "Guildford"
cap label var UK033C "Thanet"
cap label var UK034C "Nuneaton and Bedworth"
cap label var UK035C "Tunbridge Wells"
cap label var UK036C "Ashford"
cap label var UK036F "Ashford"
cap label var UK037C "East Staffordshire"
cap label var UK037F "East Staffordshire"
cap label var UK038C "Darlington"
cap label var UK038F "Darlington"
cap label var UK039C "Worthing"
cap label var UK039F "Worthing"
cap label var UK040C "Mansfield"
cap label var UK040F "Mansfield"
cap label var UK041C "Chesterfield"
cap label var UK041F "Chesterfield"
cap label var UK042C "Burnley"
cap label var UK042F "Burnley"
cap label var UK043C "Great Yarmouth"
cap label var UK043F "Great Yarmouth"
cap label var UK044C "Woking"
cap label var UK045C "Hartlepool"
cap label var UK046C "Cannock Chase"
cap label var UK047C "Eastbourne"
cap label var UK047F "Eastbourne"
cap label var UK048C "Hastings"
cap label var UK048F "Hastings"
cap label var UK049C "Hyndburn"
cap label var UK050C "Redditch"
cap label var UK050F "Redditch"
cap label var UK051C "Tamworth"
cap label var UK052C "Harlow"
cap label var UK053C "Halton"
cap label var UK053F "Halton"
cap label var UK054C "Kirklees"
cap label var UK055C "North Lanarkshire (Airdrie/Bellshill/Coatbridge/Motherwell)"
cap label var UK056C "Wakefield"
cap label var UK057C "Dudley"
cap label var UK058C "Wigan"
cap label var UK059C "Doncaster"
cap label var UK059F "Doncaster"
cap label var UK060C "Stockport"
cap label var UK061C "Sefton"
cap label var UK062C "Sandwell"
cap label var UK063C "Sunderland"
cap label var UK063F "Sunderland"
cap label var UK064C "Bolton"
cap label var UK065C "Walsall"
cap label var UK066C "Medway"
cap label var UK066F "Medway"
cap label var UK067C "Rotherham"
cap label var UK068C "Brighton and Hove"
cap label var UK068F "Brighton and Hove"
cap label var UK069C "Plymouth"
cap label var UK069F "Plymouth"
cap label var UK070C "Swansea"
cap label var UK070F "Swansea"
cap label var UK071C "Derby"
cap label var UK071F "Derby"
cap label var UK072C "Barnsley"
cap label var UK073C "Southampton"
cap label var UK073F "Southampton"
cap label var UK074C "Oldham"
cap label var UK075C "Salford"
cap label var UK076C "Tameside"
cap label var UK077C "Trafford"
cap label var UK078C "Milton Keynes"
cap label var UK078F "Milton Keynes"
cap label var UK079C "Rochdale"
cap label var UK080C "Solihull"
cap label var UK081C "Northampton"
cap label var UK081F "Northampton"
cap label var UK082C "North Tyneside"
cap label var UK083C "Gateshead"
cap label var UK084C "Warrington"
cap label var UK084F "Warrington"
cap label var UK085C "Luton"
cap label var UK085F "Luton"
cap label var UK086C "York"
cap label var UK086F "York"
cap label var UK087C "Bury"
cap label var UK088C "Swindon"
cap label var UK088F "Swindon"
cap label var UK089C "Stockton-on-Tees"
cap label var UK090C "St. Helens"
cap label var UK091C "Basildon"
cap label var UK092C "Bournemouth"
cap label var UK092F "Bournemouth"
cap label var UK093C "Southend-on-Sea"
cap label var UK094C "Telford and Wrekin"
cap label var UK094F "Telford and Wrekin"
cap label var UK095C "North East Lincolnshire"
cap label var UK095F "North East Lincolnshire"
cap label var UK096C "Chelmsford"
cap label var UK097C "Peterborough"
cap label var UK097F "Peterborough"
cap label var UK098C "Colchester"
cap label var UK098F "Colchester"
cap label var UK099C "South Tyneside"
cap label var UK100C "Basingstoke and Deane"
cap label var UK100F "Basingstoke and Deane"
cap label var UK101C "Bedford"
cap label var UK101F "Bedford"
cap label var UK102C "Dundee City"
cap label var UK102F "Dundee City"
cap label var UK103C "Falkirk"
cap label var UK103F "Falkirk"
cap label var UK104C "Reading"
cap label var UK104F "Reading"
cap label var UK105C "Blackpool"
cap label var UK105F "Blackpool"
cap label var UK106C "Maidstone"
cap label var UK106F "Maidstone"
cap label var UK107C "Dacorum"
cap label var UK107F "Dacorum"
cap label var UK108C "Blackburn with Darwen"
cap label var UK108F "Blackburn with Darwen"
cap label var UK109C "Newport"
cap label var UK109F "Newport"
cap label var UK110C "Middlesbrough"
cap label var UK110F "Middlesbrough"
cap label var UK111C "Oxford"
cap label var UK111F "Oxford"
cap label var UK112C "Torbay"
cap label var UK112F "Torbay"
cap label var UK113C "Preston"
cap label var UK113F "Preston"
cap label var UK114C "St Albans"
cap label var UK115C "Warwick"
cap label var UK116C "Newcastle-under-Lyme"
cap label var UK117C "Norwich"
cap label var UK117F "Norwich"
cap label var UK118C "Slough"
cap label var UK118F "Slough"
cap label var UK119C "Cheshire West and Chester"
cap label var UK119F "Cheshire West and Chester"
cap label var UK120C "Ipswich"
cap label var UK120F "Ipswich"
cap label var UK121C "Cheltenham"
cap label var UK121F "Cheltenham"
cap label var UK122C "Gloucester"
cap label var UK122F "Gloucester"
cap label var UK123C "Bracknell Forest"
cap label var UK123F "Bracknell Forest"
cap label var UK124C "Carlisle"
cap label var UK124F "Carlisle"
cap label var UK125C "Crawley"
cap label var UK125F "Crawley"
cap label var UK126C "Watford"
cap label var UK127C "Gosport"
cap label var UK128C "Eastleigh"
cap label var UK129C "Rushmoor"
cap label var UK129F "Rushmoor"
cap label var UK130C "Rugby"
cap label var UK131C "Corby"
cap label var UK131F "Corby"
cap label var UK132C "Kettering"
cap label var UK132F "Kettering"
cap label var UK133C "Inverclyde (Greenock)"
cap label var UK134C "Renfrewshire (Paisley)"
cap label var UK135C "Derry & Strabane Local Government District"
cap label var UK135F "Derry & Strabane Local Government District"
cap label var BA001C1 "Sarajevo"
cap label var ME001C "Podgorika"
cap label var MK001C "Skopje"
cap label var AL001C "Tirana"
cap label var RS001C "Belgrade"
cap label var TR "Türkiye"
cap label var TR001C "Ankara"
cap label var TR001F "Ankara"
cap label var TR002C "Adana"
cap label var TR002F "Adana"
cap label var TR003C "Antalya"
cap label var TR003F "Antalya"
cap label var TR004C "Balikesir"
cap label var TR004F "Balikesir"
cap label var TR005C "Bursa"
cap label var TR005F "Bursa"
cap label var TR006C "Denizli"
cap label var TR006F "Denizli"
cap label var TR007C "Diyarbakir"
cap label var TR007F "Diyarbakir"
cap label var TR008C "Edirne"
cap label var TR008F "Edirne"
cap label var TR009C "Erzurum"
cap label var TR009F "Erzurum"
cap label var TR010C "Gaziantep"
cap label var TR010F "Gaziantep"
cap label var TR011C "Hatay"
cap label var TR011F "Hatay"
cap label var TR012C "Istanbul"
cap label var TR012F "Istanbul"
cap label var TR013C "Izmir"
cap label var TR013F "Izmir"
cap label var TR014C "Kars"
cap label var TR014F "Kars"
cap label var TR015C "Kastamonu"
cap label var TR015F "Kastamonu"
cap label var TR016C "Kayseri"
cap label var TR016F "Kayseri"
cap label var TR017C "Kocaeli"
cap label var TR017F "Kocaeli"
cap label var TR018C "Konya"
cap label var TR018F "Konya"
cap label var TR019C "Malatya"
cap label var TR019F "Malatya"
cap label var TR020C "Manisa"
cap label var TR020F "Manisa"
cap label var TR021C "Nevsehir"
cap label var TR021F "Nevsehir"
cap label var TR022C "Samsun"
cap label var TR022F "Samsun"
cap label var TR023C "Siirt"
cap label var TR023F "Siirt"
cap label var TR024C "Trabzon"
cap label var TR024F "Trabzon"
cap label var TR025C "Van"
cap label var TR025F "Van"
cap label var TR026C "Zonguldak"
cap label var TR026F "Zonguldak"
cap label var XK001C "Prishtinë/Priština"
