cap label var CODE "Label - English"
cap label var ROY "Recipients over the year"
cap label var AAS "Annual average stock"
cap label var GSP_MIO_NAC "Gross social protection - millions of national currency"
cap label var NSP_MIO_NAC "Net social protection - millions of national currency"
cap label var GSP_MIO_EUR "Gross social protection - million euro"
cap label var NSP_MIO_EUR "Net social protection - million euro"
cap label var NSP_PC_GSP "Net social protection - percentage of gross social protection"
cap label var GSP_PC_GDP "Gross social protection - percentage of GDP"
cap label var NSP_PC_GDP "Net social protection - percentage of GDP"
cap label var SPB_PC_TSC "Social protection benefits subject to taxation or social contributions - percentage"
cap label var SPB_PC_TAX "Social protection benefits subject to taxation - percentage"
cap label var SPB_PC_SC "Social protection benefits subject to social contributions - percentage"
cap label var SPC_PC_TSC "Social protection cash benefits subject to taxation or social contributions - percentage"
cap label var SPC_PC_TAX "Social protection cash benefits subject to taxation - percentage"
cap label var SPC_PC_SC "Social protection cash benefits subject to social contributions - percentage"
cap label var TSC_RT_LE "Effective combined taxation and social contribution rates on benefits subject to levies"
cap label var TSC_RT_SPB "Effective combined taxation and social contribution rates on all social protection benefits"
