cap label var CODE "Label - English"
cap label var EUR "Europe"
cap label var EU "European Union (EU6-1958, EU9-1973, EU10-1981, EU12-1986, EU15-1995, EU25-2004, EU27-2007, EU28-2013, EU27-2020)"
cap label var EU27_2020 "European Union - 27 countries (from 2020)"
cap label var EU28 "European Union - 28 countries (2013-2020)"
cap label var EU27_2007 "European Union - 27 countries (2007-2013)"
cap label var EU25 "European Union - 25 countries (2004-2006)"
cap label var EU15 "European Union - 15 countries (1995-2004)"
cap label var NMS13 "New Member States - 13 countries (from 2013)"
cap label var NMS12 "New Member States - 12 countries (2007-2013)"
cap label var NMS10 "New Member States - 10 countries (2004-2006)"
cap label var EU12 "European Community - 12 countries (1986-1994)"
cap label var EA "Euro area (EA11-1999, EA12-2001, EA13-2007, EA15-2008, EA16-2009, EA17-2011, EA18-2014, EA19-2015, EA20-2023)"
cap label var EA20 "Euro area – 20 countries (from 2023)"
cap label var EA19 "Euro area - 19 countries  (2015-2022)"
cap label var EA18 "Euro area - 18 countries (2014)"
cap label var EA17 "Euro area - 17 countries (2011-2013)"
cap label var EA16 "Euro area - 16 countries (2009-2010)"
cap label var EA15 "Euro area - 15 countries (2008)"
cap label var EA13 "Euro area - 13 countries (2007)"
cap label var EA12 "Euro area - 12 countries (2001-2006)"
cap label var EA11 "Euro area - 11 countries (1999-2000)"
cap label var BE "Belgium"
cap label var BG "Bulgaria"
cap label var CZ "Czechia"
cap label var DK "Denmark"
cap label var DE "Germany"
cap label var DEW "Federal Republic of Germany (former territory of the FRG only)"
cap label var EE "Estonia"
cap label var IE "Ireland"
cap label var EL "Greece"
cap label var ES "Spain"
cap label var ES630 "Ceuta"
cap label var ES640 "Melilla"
cap label var FR "France"
cap label var FR91 "Guadeloupe (NUTS 2010)"
cap label var FR92 "Martinique (NUTS 2010)"
cap label var FR93 "Guyane (NUTS 2010)"
cap label var FR94 "Réunion (NUTS 2010)"
cap label var YT "Mayotte (FR - part of EU as of 01.01.2014)"
cap label var HR "Croatia"
cap label var IT "Italy"
cap label var CY "Cyprus"
cap label var LV "Latvia"
cap label var LT "Lithuania"
cap label var LU "Luxembourg"
cap label var HU "Hungary"
cap label var MT "Malta"
cap label var NL "Netherlands"
cap label var AT "Austria"
cap label var PL "Poland"
cap label var PT "Portugal"
cap label var RO "Romania"
cap label var SI "Slovenia"
cap label var SK "Slovakia"
cap label var FI "Finland"
cap label var SE "Sweden"
cap label var BLEU "Belgo-Luxembourg Economic Union"
cap label var BAL "Baltic countries"
cap label var EU27_2020_NEA20 "EU27 countries (from 2020) not in EA20 (from 2023) - 7 countries"
cap label var EU27_2020_NEA20_X_DK_SE "EU27 countries (from 2020) not in EA20 (from 2023), except DK and SE"
cap label var EU27_2020_NEA19 "EU27 countries (from 2020) not in EA19 (from 2015) - 8 countries"
cap label var NMS_NEA19 "New Member States not in EA19 (from 2015) - 6 countries"
cap label var EU_OTH "Other EU countries"
cap label var EU25_OTH "Other EU25 countries (2004-2006)"
cap label var EU15_OTH "Other EU15 countries (1995-2004)"
cap label var INT_EU "Intra-EU"
cap label var INT_EU27_2020 "Intra-EU27 (from 2020)"
cap label var INT_EU28 "Intra-EU28 (2013-2020)"
cap label var INT_EU27_2007 "Intra-EU27 (2007-2013)"
cap label var INT_EU15 "Intra-EU15 (1995-2004)"
cap label var INT_NMS12 "Intra-New Member States - 12 countries (2007-2013)"
cap label var INT_EU_NAL "Intra-EU, not allocated"
cap label var INT_EU15_NAL "Intra-EU15 (1995-2004), not allocated"
cap label var INT_EA_NAL "Intra-euro area, not allocated"
cap label var EU27_2020_FOR "EU27 countries (from 2020) except reporting country"
cap label var EU28_FOR "EU28 countries (2013-2020) except reporting country"
cap label var EU27_2007_FOR "EU27 countries (2007-2013) except reporting country"
cap label var EU25_FOR "EU25 countries (2004-2006) except reporting country"
cap label var EU15_FOR "EU15 countries (1995-2004) except reporting country"
cap label var EU12_FOR "EU12 countries (1986-1994) except reporting country"
cap label var EEA "European Economic Area (EEA18-1995, EEA28-2004, EEA30-2007, EEA31-2013, EEA30-2020)"
cap label var EEA30_2020 "European Economic Area (EU27 from 2020 and IS, LI, NO)"
cap label var EEA31 "European Economic Area (EU28 - 2013-2020 and IS, LI, NO)"
cap label var EEA30_2007 "European Economic Area (EU27 - 2007-2013 and IS, LI, NO)"
cap label var EEA28 "European Economic Area (EU25 - 2004-2006 and IS, LI, NO)"
cap label var EEA18 "European Economic Area (EU15 - 1995-2004 and IS, LI, NO)"
cap label var EEA_NEU "EEA-countries except the EU-countries"
cap label var EEA18_OTH "Other European Economic Area (EU15 - 1995-2004 and IS, LI, NO)"
cap label var EFTA "European Free Trade Association"
cap label var IS "Iceland"
cap label var LI "Liechtenstein"
cap label var NO "Norway"
cap label var CH "Switzerland"
cap label var EFTA_FOR "European Free Trade Association except reporting country"
cap label var UK "United Kingdom"
cap label var CC9_23 "Candidate countries from 2023 (9 countries)"
cap label var CC9_23_FOR "Candidate countries from 2023 (9 countries) except reporting country"
cap label var CC8_22 "Candidate countries from 2022 (8 countries)"
cap label var CC8_22_FOR "Candidate countries from 2022 (8 countries) except reporting country"
cap label var CC5_15 "Candidate countries from 2015 (5 countries)"
cap label var CC5_15_FOR "Candidate countries from 2015 (5 countries) except reporting country"
cap label var CC5_13 "Candidate countries in 2013 (5 countries)"
cap label var CC5_13_FOR_X_IS "Candidate countries in 2013 (5 countries) except reporting country and Iceland"
cap label var CC5_10 "Candidate countries in 2010 (5 countries)"
cap label var CC4_10 "Candidate countries in 2010 (4 countries)"
cap label var CC3_07 "Candidate countries in 2007 (3 countries)"
cap label var BA "Bosnia and Herzegovina"
cap label var ME "Montenegro"
cap label var MD "Moldova"
cap label var MK "North Macedonia"
cap label var GE "Georgia"
cap label var AL "Albania"
cap label var RS "Serbia"
cap label var TR "Türkiye"
cap label var UA "Ukraine"
cap label var XK "Kosovo*"
cap label var EUR_C_E "Central and Eastern Europe"
cap label var EUR_C_E_OTH "Other Central and Eastern European countries"
cap label var WBC "WBC - Western Balkan Countries (aggregate changing according to the context)"
cap label var AD "Andorra"
cap label var BY "Belarus"
cap label var GG "Guernsey"
cap label var JE "Jersey"
cap label var CQ "Sark"
cap label var FO "Faroes"
cap label var GI "Gibraltar"
cap label var VA "Holy See"
cap label var IM "Isle of Man"
cap label var MC "Monaco"
cap label var RU "Russia"
cap label var SM "San Marino"
cap label var SJ "Svalbard and Jan Mayen"
cap label var CZ_SK "Czechoslovakia"
cap label var RS_ME "Serbia and Montenegro"
cap label var EX_YU "Yugoslavia"
cap label var EX_YU_OTH "Other countries of former Yugoslavia (before 1992)"
cap label var EX_SU "Soviet Union"
cap label var EX_SU_EUR "European Republics of the former Soviet Union"
cap label var EX_SU_OTH "Other countries of former Soviet Union (before 1991)"
cap label var CIS "Commonwealth of Independent States (Former Soviet Union except BAL)"
cap label var EXT "Countries other than EU, EFTA and Candidate countries"
cap label var HDC_EXT "Highly developed countries (other than EU, EFTA and Candidate countries)"
cap label var MDC_EXT "Medium developed countries (other than EU, EFTA and Candidate countries)"
cap label var LDC_EXT "Less developed countries (other than EU, EFTA and Candidate countries)"
cap label var EXT_EU "Extra-EU"
cap label var EXT_EU27_2020 "Extra-EU27 (from 2020)"
cap label var EXT_EU28 "Extra-EU28 (2013-2020)"
cap label var EXT_EU27_2007 "Extra-EU27 (2007-2013)"
cap label var EXT_EU25 "Extra-EU25 (2004-2006)"
cap label var EXT_EU15 "Extra-EU15 (1995-2004)"
cap label var EXT_EU12 "Extra-EU12 (1986-1994)"
cap label var EXT_EA "Extra-euro area"
cap label var EXT_EA20 "Extra-euro area - 20 countries (from 2023)"
cap label var EXT_EA19 "Extra-euro area - 19 countries (from 2015)"
cap label var EXT_EA18 "Extra-euro area - 18 countries (2014)"
cap label var EXT_EA17 "Extra-euro area - 17 countries (2011-2013)"
cap label var EXT_EA16 "Extra-euro area - 16 countries (2009-2010)"
cap label var EXT_EA15 "Extra-euro area - 15 countries (2008))"
cap label var EXT_EA13 "Extra-euro area - 13 countries (2007)"
cap label var EXT_EA12 "Extra-euro area - 12 countries (2001-2006)"
cap label var EXT_EA11 "Extra-euro area - 11 countries (1999-2000)"
cap label var EXT_EU_NAL "Extra-EU, not allocated"
cap label var EXT_EA_NAL "Extra-euro area, not allocated"
cap label var EXT_FOR_HDI "Countries other than EU, EFTA and Candidate countries with Human Development Index (HDI) ranking"
cap label var EXT_FOR_HDI_VH "Countries other than EU, EFTA and Candidate countries with very high Human Development Index (HDI)"
cap label var EXT_FOR_HDI_H "Countries other than EU, EFTA and Candidate countries with high Human Development Index (HDI)"
cap label var EXT_FOR_HDI_M "Countries other than EU, EFTA and Candidate countries with medium Human Development Index (HDI)"
cap label var EXT_FOR_HDI_L "Countries other than EU, EFTA and Candidate countries with low Human Development Index (HDI)"
cap label var NEU27_2020_NEFTA "Non-EU27 countries (from 2020) nor EFTA countries"
cap label var NEU27_2020 "Non-EU27 countries (from 2020)"
cap label var NEU27_2020_FOR "Non-EU27 countries (from 2020) nor reporting country"
cap label var NEU28_FOR "Non-EU28 countries (2013-2020) nor reporting country"
cap label var NEU27_2007_FOR "Non-EU27 countries (2007-2013) nor reporting country"
cap label var EUR_NEU "European non-EU countries (aggregate changing according to the context)"
cap label var EUR_NEU27_2020_NEFTA "European non-EU27 countries (from 2020) and European non-EFTA countries"
cap label var EUR_NEU27_2020 "European non-EU27 countries (from 2020)"
cap label var EUROTH "European countries not EU nor EFTA (aggregate changing according to the context)"
cap label var EUR_OTH "Other European countries (aggregate changing according to the context)"
cap label var EUR_NSP "European countries, not specified"
cap label var AFR "Africa"
cap label var AFR_C_S "Central and South Africa"
cap label var AFR_C "Central Africa"
cap label var AO "Angola"
cap label var CM "Cameroon"
cap label var CF "Central African Republic"
cap label var TD "Chad"
cap label var CG "Congo"
cap label var CD "Democratic Republic of the Congo"
cap label var GQ "Equatorial Guinea"
cap label var GA "Gabon"
cap label var ST "São Tomé and Príncipe"
cap label var AFR_E "Eastern Africa"
cap label var BI "Burundi"
cap label var KM "Comoros"
cap label var DJ "Djibouti"
cap label var ER "Eritrea"
cap label var ET "Ethiopia"
cap label var KE "Kenya"
cap label var MG "Madagascar"
cap label var MW "Malawi"
cap label var MU "Mauritius"
cap label var MZ "Mozambique"
cap label var RW "Rwanda"
cap label var SC "Seychelles"
cap label var SO "Somalia"
cap label var UG "Uganda"
cap label var TZ "Tanzania"
cap label var ZM "Zambia"
cap label var ZW "Zimbabwe"
cap label var AFR_N "Northern Africa"
cap label var DZ "Algeria"
cap label var EG "Egypt"
cap label var LY "Libya"
cap label var MA "Morocco"
cap label var SS "South Sudan"
cap label var SD "Sudan"
cap label var TN "Tunisia"
cap label var EH "Western Sahara"
cap label var AFR_S "Southern Africa"
cap label var BW "Botswana"
cap label var LS "Lesotho"
cap label var NA "Namibia"
cap label var ZA "South Africa"
cap label var SZ "Eswatini"
cap label var AFR_W "Western Africa"
cap label var BJ "Benin"
cap label var BF "Burkina Faso"
cap label var CV "Cabo Verde"
cap label var CI "Côte d’Ivoire"
cap label var GM "Gambia, The"
cap label var GH "Ghana"
cap label var GN "Guinea"
cap label var GW "Guinea-Bissau"
cap label var LR "Liberia"
cap label var ML "Mali"
cap label var MR "Mauritania"
cap label var NE "Niger"
cap label var NG "Nigeria"
cap label var SH "Saint Helena, Ascension and Tristan da Cunha"
cap label var SN "Senegal"
cap label var SL "Sierra Leone"
cap label var TG "Togo"
cap label var AFR_OTH "Other African countries (aggregate changing according to the context)"
cap label var AFR_NSP "African countries, not specified"
cap label var AME "America"
cap label var AME_N "Northern America"
cap label var BM "Bermuda"
cap label var CA_US "Canada and United States"
cap label var CA "Canada"
cap label var GL "Greenland"
cap label var PM "Saint Pierre and Miquelon"
cap label var US "United States"
cap label var AME_N_OTH "Other Northern American countries"
cap label var AME_N_NSP "Northern American countries, not specified"
cap label var AME_X_N "Caribbean, Central and South America"
cap label var AME_C_CRB "Central America and Caribbean"
cap label var CRB "Caribbean"
cap label var AI "Anguilla"
cap label var AG "Antigua and Barbuda"
cap label var AW "Aruba"
cap label var BS "Bahamas"
cap label var BB "Barbados"
cap label var BQ "Bonaire, Saint Eustatius and Saba"
cap label var VG "British Virgin Islands"
cap label var KY "Cayman Islands"
cap label var CU "Cuba"
cap label var CW "Curaçao"
cap label var DM "Dominica"
cap label var DO "Dominican Republic"
cap label var GD "Grenada"
cap label var HT "Haiti"
cap label var JM "Jamaica"
cap label var MS "Montserrat"
cap label var AN "Netherlands Antilles"
cap label var PR "Puerto Rico"
cap label var BL "Saint Barthélemy"
cap label var KN "Saint Kitts and Nevis"
cap label var LC "Saint Lucia"
cap label var MF "Saint Martin"
cap label var VC "Saint Vincent and the Grenadines"
cap label var SX "Sint Maarten"
cap label var TT "Trinidad and Tobago"
cap label var TC "Turks and Caicos Islands"
cap label var VI "US Virgin Islands"
cap label var AME_C_S "Central and South America"
cap label var AME_LAT "Latin American countries"
cap label var AME_C "Central America"
cap label var BZ "Belize"
cap label var CR "Costa Rica"
cap label var SV "El Salvador"
cap label var GT "Guatemala"
cap label var HN "Honduras"
cap label var MX "Mexico"
cap label var NI "Nicaragua"
cap label var PA "Panama"
cap label var AME_S "South America"
cap label var AR "Argentina"
cap label var BO "Bolivia"
cap label var BR "Brazil"
cap label var CL "Chile"
cap label var CO "Colombia"
cap label var EC "Ecuador"
cap label var FK "Falkland Islands"
cap label var GY "Guyana"
cap label var PY "Paraguay"
cap label var PE "Peru"
cap label var SR "Suriname"
cap label var UY "Uruguay"
cap label var VE "Venezuela"
cap label var AME_C_S_OTH "Other Central or South American countries"
cap label var AME_X_N_NSP "Caribbean, Central and South American countries, not specified"
cap label var AME_OTH "Other American countries (aggregate changing according to the context)"
cap label var ASI "Asia"
cap label var ASI_C "Central Asia"
cap label var KZ "Kazakhstan"
cap label var KG "Kyrgyzstan"
cap label var TJ "Tajikistan"
cap label var TM "Turkmenistan"
cap label var UZ "Uzbekistan"
cap label var ASI_E "Eastern Asia"
cap label var CN "China"
cap label var CN_X_HK "China except Hong Kong"
cap label var HK "Hong Kong"
cap label var MO "Macao"
cap label var JP "Japan"
cap label var MN "Mongolia"
cap label var KP "North Korea"
cap label var KR "South Korea"
cap label var TW "Taiwan"
cap label var TW_CAP "Taipei"
cap label var ASI_S "Southern Asia"
cap label var AF "Afghanistan"
cap label var BD "Bangladesh"
cap label var BT "Bhutan"
cap label var IO "British Indian Ocean Territory"
cap label var IN "India"
cap label var IR "Iran"
cap label var MV "Maldives"
cap label var NP "Nepal"
cap label var PK "Pakistan"
cap label var LK "Sri Lanka"
cap label var ASI_S_E "South-Eastern Asia"
cap label var BN "Brunei Darussalam"
cap label var KH "Cambodia"
cap label var ID "Indonesia"
cap label var LA "Laos"
cap label var MY "Malaysia"
cap label var MM "Myanmar/Burma"
cap label var PH "Philippines"
cap label var SG "Singapore"
cap label var TH "Thailand"
cap label var TL "Timor-Leste"
cap label var VN "Viet Nam"
cap label var ASI_W_IR "Western Asia including Iran"
cap label var ASI_W "Western Asia"
cap label var AM "Armenia"
cap label var AZ "Azerbaijan"
cap label var BH "Bahrain"
cap label var IQ "Iraq"
cap label var IL "Israel"
cap label var JO "Jordan"
cap label var KW "Kuwait"
cap label var LB "Lebanon"
cap label var PS "Palestine*"
cap label var OM "Oman"
cap label var QA "Qatar"
cap label var SA "Saudi Arabia"
cap label var SY "Syria"
cap label var AE "United Arab Emirates"
cap label var YE "Yemen"
cap label var ASI_NME "Near and Middle East Asia (aggregate changing according to the context)"
cap label var ASI_NME_OTH "Other Near and Middle East Asian countries"
cap label var ASI_G "Gulf Arabian Countries"
cap label var ASI_W_OTH "Other Western Asian countries"
cap label var ASI_OTH "Other Asian countries (aggregate changing according to the context)"
cap label var ASI_NSP "Asian countries, not specified"
cap label var ASI_OCE_OTH "Other Asian and Oceanian countries (aggregate changing according to the context)"
cap label var OCE_PLR "Oceania and southern polar regions"
cap label var OCE "Oceania"
cap label var AU_NZ "Australia and New Zealand"
cap label var AU "Australia"
cap label var AU_ISL "Australian Oceania"
cap label var CX "Christmas Island"
cap label var CC "Cocos (Keeling) Islands"
cap label var HM "Heard Island and McDonald Islands"
cap label var NF "Norfolk Island"
cap label var NZ "New Zealand"
cap label var NZ_ISL "New Zealand Oceania"
cap label var MEL "Melanesia"
cap label var FJ "Fiji"
cap label var NC "New Caledonia"
cap label var PG "Papua New Guinea"
cap label var SB "Solomon Islands"
cap label var VU "Vanuatu"
cap label var MIC "Micronesia"
cap label var GU "Guam"
cap label var KI "Kiribati"
cap label var MH "Marshall Islands"
cap label var FM "Federated States of Micronesia"
cap label var NR "Nauru"
cap label var MP "Northern Mariana Islands"
cap label var PW "Palau"
cap label var POL "Polynesia"
cap label var AS "American Samoa"
cap label var CK "Cook Islands"
cap label var PF "French Polynesia"
cap label var NU "Niue"
cap label var PN "Pitcairn Islands"
cap label var WS "Samoa"
cap label var TK "Tokelau"
cap label var TO "Tonga"
cap label var TV "Tuvalu"
cap label var WF "Wallis and Futuna"
cap label var US_ISL "American Oceania (US)"
cap label var UM "United States Minor Outlying Islands"
cap label var OCE_OTH "Other Oceanian countries (aggregate changing according to the context)"
cap label var OCE_NSP "Oceanian countries, not specified"
cap label var PLR "Southern polar regions"
cap label var AQ "Antarctica"
cap label var BV "Bouvet Island"
cap label var GS "South Georgia and the South Sandwich Islands"
cap label var TF "French Southern and Antarctic Lands"
cap label var EUI "Institutions and bodies of the European Union"
cap label var EUI_X_EAI "EU institutions except the institutions of the euro area (aggregate changing according to the context)"
cap label var PARL "European Parliament"
cap label var COMM "European Commission"
cap label var ECB "European Central Bank (ECB)"
cap label var EIB "European Investment Bank (EIB)"
cap label var ESM "European Stability Mechanism"
cap label var EFSF "European Financial Stability Facility"
cap label var IMF "International Monetary Fund"
cap label var ACP "African, Caribbean and Pacific Group of States, signatories of the Partnership Agreement"
cap label var ACP_AFR "African ACP states"
cap label var ACP_CRB "Caribbean ACP states"
cap label var ACP_PAC "Pacific ACP states"
cap label var ASEAN "Association of Southeast Asian Nations"
cap label var DAC "Development assistance committee (DAC)"
cap label var EHEA "European Higher Education Area (Bologna Process)"
cap label var EURMED "Mediterranean countries in the Euro-Mediterranean Partnership"
cap label var FZ "Franc Zone"
cap label var G20_X_EU27_2020 "Group of Twenty except the EU27 countries (from 2020)"
cap label var MACR "Mashrek"
cap label var MAGR "Maghreb"
cap label var MED "Mediterranean Basin Countries"
cap label var MED_X_HR "Mediterranean Basin Countries except Croatia"
cap label var MERCOSUR "Southern Common Market Southern Common Market (MERCOSUR5_1991, MERCOSUR4_2016)"
cap label var MERCOSUR5_1991 "Southern Common Market – 5 countries (1991-2016)"
cap label var MERCOSUR4_2016 "Southern Common Market – 4 countries (from 2016)"
cap label var NAFTA "North American Free Trade Agreement"
cap label var ODA "Official Development Assistance (ODA) recipients from Development Assistance Committee (DAC)"
cap label var OECD "Organisation for Economic Co-operation and Development (OECD)"
cap label var OECD34 "Organisation for Economic Co-operation and Development (OECD - 34 countries)"
cap label var OECD_NEU "OECD non-EU countries"
cap label var OPEC "Organization of Petroleum Exporting Countries (OPEC)"
cap label var OPEC12 "Organization of Petroleum Exporting Countries (OPEC - 12 countries)"
cap label var USMCA "United States-Mexico-Canada Agreement (USMCA)"
cap label var ORG_NEUR "Non European International Organizations"
cap label var DAE "Dynamic Asian economies (DAEs)"
cap label var FOR "Foreign country"
cap label var LDC "Least developed countries"
cap label var LMIC "Lower middle income countries"
cap label var MSHO "Member State of head office"
cap label var NAT "Reporting country"
cap label var NIC_S1 "Core Newly Industrializing Countries"
cap label var NIC_S2A "Asian NICs of the second wave of industrialization"
cap label var NIC_S2LA "Latin American NICs of the second wave of industrialization"
cap label var OFFSHO "Offshore financial centers"
cap label var OLIC "Other low income countries"
cap label var RNC "Recognised non-citizens"
cap label var STLS "Stateless"
cap label var THRD "Third country"
cap label var TOTAL "Total"
cap label var UMIC_X_CN "Upper middle income countries except China"
cap label var WORLD "All countries of the world"
cap label var WRL_NAL "World - not allocated"
cap label var WRL_REST "Rest of the world"
cap label var WRL_X_REP "World total except for the reporting country"
cap label var WRL_X_EUR "World except Europe"
cap label var OTH "Others"
cap label var NAL "Not allocated"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var NSP "Not specified"
cap label var UNK "Unknown"
