cap label var CODE "Label - English"
cap label var _993 "Current account"
cap label var _100 "Current account, goods"
cap label var _200 "Current account, services"
cap label var _201 "Current account, services, branding, quasi-transit adjustment"
cap label var _205 "Current account, services, transportation"
cap label var _206 "Current account, services, transportation, sea transport"
cap label var _207 "Current account, services, transportation, sea transport, passenger transport on sea"
cap label var _208 "Current account, services, transportation, sea transport, freight transport on sea"
cap label var _209 "Current account, services, transportation, sea transport, supporting, auxiliary and other sea transport services"
cap label var _210 "Current account, services, transportation, air transport"
cap label var _211 "Current account, services, transportation, air transport, passenger transport by air"
cap label var _212 "Current account, services, transportation, air transport, freight transport by air"
cap label var _213 "Current account, services, transportation, air transport, supporting, auxiliary and other air transport services"
cap label var _214 "Current account, services, transportation, other transport (other than sea and air)"
cap label var _215 "Current account, services, transportation, other transport (other than sea and air), passenger on other transport"
cap label var _216 "Current account, services, transportation, other transport (other than sea and air), freight on other transport"
cap label var _217 "Current account, services, transportation, other transport (other than sea and air), other of other transport"
cap label var _218 "Current account, services, transportation, other transport (other than sea and air) - extended classification, space transport"
cap label var _219 "Current account, services, transportation, other transport (other than sea and air) - extended classification, rail transport"
cap label var _220 "Current account, services, transportation, other transport (other than sea and air) - extended classification, rail transport, passenger on rail"
cap label var _221 "Current account, services, transportation, other transport (other than sea and air) - extended classification, rail transport, freight on rail"
cap label var _222 "Current account, services, transportation, other transport (other than sea and air) - extended classification, rail transport, supporting, auxiliary and other rail transport services"
cap label var _223 "Current account, services, transportation, other transport (other than sea and air) - extended classification, road transport"
cap label var _224 "Current account, services, transportation, other transport (other than sea and air) - extended classification, road transport, passenger on road"
cap label var _225 "Current account, services, transportation, other transport (other than sea and air) - extended classification, road transport, freight on road"
cap label var _226 "Current account, services, transportation, other transport (other than sea and air) - extended classification, road transport, supporting, auxiliary and other road transport services"
cap label var _227 "Current account, services, transportation, other transport (other than sea and air) - extended classification, inland waterway transport"
cap label var _228 "Current account, services, transportation, other transport (other than sea and air) - extended classification, inland waterway transport, passenger on inland waterway"
cap label var _229 "Current account, services, transportation, other transport (other than sea and air) - extended classification, inland waterway transport, freight on inland waterway"
cap label var _230 "Current account, services, transportation, other transport (other than sea and air) - extended classification, inland waterway transport, supporting, auxiliary and other inland waterway transport services"
cap label var _231 "Current account, services, transportation, other transport (other than sea and air) - extended classification, pipeline transport"
cap label var _232 "Current account, services, transportation, other transport (other than sea and air) - extended classification, other supporting and auxiliary transport services"
cap label var _236 "Current account, services, travel"
cap label var _237 "Current account, services, travel, business travel"
cap label var _238 "Current account, services, travel, business travel, expenditure by seasonal and border workers"
cap label var _239 "Current account, services, travel, business travel, other business travel"
cap label var _240 "Current account, services, travel, personal travel"
cap label var _241 "Current account, services, travel, personal travel, health-related expenditure"
cap label var _242 "Current account, services, travel, personal travel, education related expenditure"
cap label var _243 "Current account, services, travel, personal travel, other personal travel"
cap label var _981 "Current account, services, other services"
cap label var _245 "Current account, services, other services, communications services"
cap label var _246 "Current account, services, other services, communications services, postal and courier services"
cap label var _958 "Current account, services, communications services, postal and courier services, postal services"
cap label var _959 "Current account, services, communications services, postal and courier services, courier services"
cap label var _247 "Current account, services, other services, communications services, telecommunication services"
cap label var _249 "Current account, services, other services, construction services"
cap label var _250 "Current account, services, other services, construction services, construction abroad"
cap label var _251 "Current account, services, Other services, construction services, construction in the compiling economy"
cap label var _253 "Current account, services, other services, insurance services"
cap label var _254 "Current account, services, other services, insurance services, life insurance and pension funding"
cap label var _255 "Current account, services, other services, insurance services, freight insurance"
cap label var _256 "Current account, services, other services, insurance services, other direct insurance"
cap label var _257 "Current account, services, other services, insurance services, reinsurance"
cap label var _258 "Current account, services, other services, insurance services, auxiliary services"
cap label var _260 "Current account, services, other services, financial services"
cap label var _262 "Current account, services, other services, computer and information services"
cap label var _263 "Current account, services, other services, computer and information services, computer services"
cap label var _264 "Current account, services, other services, computer and information services, information services"
cap label var _889 "Current account, services, other services, computer and information services, information services, news agency services"
cap label var _890 "Current account, services, other services, computer and information services, information services, other information provision services"
cap label var _266 "Current account, services, other services, royalties and license fees"
cap label var _891 "Current account, services, other services, royalties and license fees, franchises and similar rights"
cap label var _892 "Current account, services, other services, royalties and license fees, other royalties and license fees"
cap label var _268 "Current account, services, other services, other business services"
cap label var _269 "Current account, services, other services, other business services, merchanting and other trade-related services"
cap label var _270 "Current account, services, other services, other business services, merchanting and other trade-related services, merchanting"
cap label var _271 "Current account, services, other services, other business services, merchanting and other trade-related services, other trade-related services"
cap label var _272 "Current account, services, other services, other business services, operational leasing services"
cap label var _273 "Current account, services, other services, other business services, miscellaneous business, professional and technical services"
cap label var _274 "Current account, services, other services, other business services, miscellaneous business, professional and technical services, legal, accounting, management and public relations services"
cap label var _275 "Current account, services, other services, other business services, miscellaneous business, professional and technical services, legal, accounting, management and public relations services, legal services"
cap label var _276 "Current account, services, other services, other business services, miscellaneous business, professional and technical services, legal, accounting, management and public relations services, accounting, auditing, book-keeping and tax consulting services"
cap label var _277 "Current account, services, other services, other business services, miscellaneous business, professional and technical services, legal, accounting, management and public relations services, business and management consultancy, public relations services"
cap label var _278 "Current account, services, other services, other business services, miscellaneous business, professional and technical services, advertising, market research and public opinion polling"
cap label var _279 "Current account, services, other services, other business services, miscellaneous business, professional and technical services, research and development services"
cap label var _280 "Current account, services, other services, other business services, miscellaneous business, professional and technical services, architectural, engineering and other technical consultancy"
cap label var _281 "Current account, services, other services, other business services, miscellaneous business, professional and technical services, agricultural, mining, and on-site processing"
cap label var _282 "Current account, services, other services, other business services, miscellaneous business, professional and technical services, agricultural, mining , and on-site processing, waste treatment and depolution"
cap label var _283 "Current account, services, other services, other business services, miscellaneous business, professional and technical services, agricultural, mining , and on-site processing, other agricultural, mining and on-site processing"
cap label var _284 "Current account, services, other services, other business services, miscellaneous business, professional and technical services, other miscellaneous business, professional and technical services"
cap label var _285 "Current account, services, other services, other business services, miscellaneous business, professional and technical services, services between affiliated enterprises, n.i.e."
cap label var _287 "Current account, services, other services, personal, cultural and recreational services"
cap label var _288 "Current account, services, other services, personal, cultural and recreational services, audio-visual and related services"
cap label var _289 "Current account, services, other services, personal, cultural and recreational services, other personal, cultural and recreational services"
cap label var _895 "Current account, services, other services, personal, cultural and recreational services, other personal, cultural and recreational services, education services"
cap label var _896 "Current account, services, personal, cultural and recreational services, other personal, cultural and recreational services, health services"
cap label var _897 "Current account, services, other services, personal, cultural and recreational services, other personal, cultural and recreational services, other"
cap label var _291 "Current account, services, other services, government services, n.i.e."
cap label var _292 "Current account, services, other services, government services, n.i.e., embassies and consulates"
cap label var _293 "Current account, services, other services, government services, n.i.e., military units and agencies"
cap label var _294 "Current account, services, other services, government services, n.i.e., other government services"
cap label var _982 "Current account, services, services not allocated"
cap label var _894 "Current account, services, memorandum items, audiovisual transactions"
cap label var _330 "Current account, income, investment income, direct investment"
cap label var _331 "Current account, income, investment income, direct investment, income on equity"
cap label var _332 "Current account, income, investment income, direct investment, Income on equity, dividends and distributed branch profits"
cap label var _333 "Current account, income, investment income, direct investment, income on equity, reinvested earnings and undistributed branch profits"
cap label var _334 "Current account, income, investment income, direct investment, income on debt (interest)"
cap label var _994 "Capital account"
cap label var _995 "Financial account"
cap label var _505 "Financial account, direct investment, abroad"
cap label var _506 "Financial account, direct investment, abroad, equity capital and reinvested earnings"
cap label var _510 "Financial account, direct investment, abroad, equity capital"
cap label var _525 "Financial account, direct investment, abroad, reinvested earnings"
cap label var _530 "Financial account, direct investment, abroad, other capital"
cap label var _555 "Financial account, direct investment, in the reporting economy"
cap label var _556 "Financial account, direct investment, in the reporting economy, equity capital and reinvested earnings"
cap label var _560 "Financial account, direct investment, in the reporting economy, equity capital"
cap label var _575 "Financial account, direct investment, in the reporting economy, reinvested earnings"
cap label var _580 "Financial account, direct investment, in the reporting economy, other capital"
cap label var _983 "Commercial services (services excluding government services, n.i.e.)"
cap label var _998 "Net errors and omissions"
cap label var _991 "Current account, goods and services"
