cap label var CODE "Label - English"
cap label var AR_THS_HA "Area (sown/harvested/production) - thousand hectares"
cap label var HPRD_THS_T "Harvested production - thousand tonnes"
cap label var MAR_THS_HA "Main area - thousand hectares"
cap label var HUMD_PC "Humidity - percentage"
cap label var SUG_SB_PC "Sugar content of sugar beet - percentage"
cap label var HUMD_EU_PC "EU standard humidity - percentage"
cap label var HPRD_HUMD_EU_THS_T "Harvested production in EU standard humidity - thousand tonnes"
cap label var YLD_T_HA "Yield - tonnes per hectare"
cap label var YLD_HUMD_EU_T_HA "Yield in EU standard humidity - tonnes per hectare"
cap label var AR_ORG_HA "Certified organic area (sown/harvested/production) - hectare"
cap label var HPRD_ORG_T "Certified organic harvested production - tonne"
cap label var MAR_ORG_HA "Main certified organic area - hectare"
cap label var MAR_UCONV_HA "Main area under conversion to organic - hectare"
cap label var MAR_ORG_UCONV_HA "Main area certified or under conversion to organic - hectare"
cap label var HPRD_ORG_HUMD_EU_T "Certified organic harvested production in EU standard humidity - tonne"
cap label var YLD_ORG_T_HA "Certified organic yield - tonnes per hectare"
cap label var YLD_ORG_HUMD_EU_T_HA "Certified organic yield in EU standard humidity - tonnes per hectare"
cap label var AR_ORG_PC "Certified organic area - percentage of total area"
cap label var MAR_ORG_PC "Main certified organic area - percentage of main area"
cap label var MAR_UCONV_PC "Main area under conversion to organic - percentage of main area"
cap label var MAR_ORG_UCONV_PC "Main area certified or under conversion to organic - percentage of main area"
cap label var HPRD_ORG_PC "Certified organic harvested production - percentage of total harvested production"
cap label var AR "Area (cultivation/harvested/production) (1000 ha)"
cap label var PR "Harvested production (1000 t)"
cap label var PR_HU_EU "Harvested production in EU standard humidity (1000 t)"
cap label var YI "Yield (tonne/ha)"
cap label var YI_HU_EU "Yield in EU standard humidity (tonne/ha)"
cap label var HOL "Number of holders (1000)"
cap label var ANI "Number of animals (1000)"
cap label var MA "Main area (1000 ha)"
cap label var HU "Humidity (%)"
cap label var HU_EU "EU standard humidity (%)"
