cap label var CODE "Label - English"
cap label var UAA "Utilised agricultural area"
cap label var UAAIB "Irrigable utilised agricultural area"
cap label var UAA_IB "Irrigable utilised agricultural area"
cap label var UAAIT "Irrigated utilised agricultural area"
cap label var UAA_IT "Irrigated utilised agricultural area"
cap label var UAAT_IB "Irrigable utilised agricultural area - outdoor"
cap label var UAATIT "Irrigated utilised agricultural area - outdoor"
cap label var UAAT_IT_AVG "Average irrigated utilised agricultural area - outdoor﻿"
cap label var UAAT_IT "Irrigated utilised agricultural area - outdoor"
cap label var UAAS "Utilised agricultural area - under glass or high accessible cover"
cap label var UAAS_IT "Irrigated utilised agricultural area - under glass or high accessible cover"
