cap label var CODE "Label - English"
cap label var PSY_PHY_THRT_SX "Psychological, physical (including threats) or sexual"
cap label var PHY_THRT_SX "Physical (including threats) or sexual"
cap label var PSY "Psychological"
cap label var PSY_THRT "Psychological or threats"
cap label var THRT "Threats"
cap label var THRT_NPHY_NSX "Threats (and not physical and sexual)"
cap label var PHY "Physical"
cap label var PHY_THRT "Physical (including threats)"
cap label var PHY_THRT_NSX "Physical (including threats and not sexual)"
cap label var PHY_NSX "Physical (and not sexual)"
cap label var PHY_SX "Physical or sexual"
cap label var PHY_PSY "Physical or psychological"
cap label var PHY_PSHP_STWS "Physical - pushing, shoving, hair pulling, slapping, throwing with something"
cap label var PHY_PB_BS_WPN "Physical - punching, beating, burning, strangling, using a weapon"
cap label var PHY_PSHP "Physical - pushing, shoving, hair pulling"
cap label var PHY_STWS "Physical - slapping, throwing with something"
cap label var PHY_PBWOK "Physical - punching, beating with an object, kicking"
cap label var PHY_BWFA "Physical - burning with fire, acid etc."
cap label var PHY_TCS "Physical - trying to choke or strangle"
cap label var PHY_WPN "Physical - threatening with or using a weapon"
cap label var PHY_OTH "Physical - other"
cap label var SX "Sexual"
cap label var SX_RAPE "Sexual - rape"
cap label var SX_RAPE_FORC "Sexual - rape with force"
cap label var SX_RAPE_NCONS "Sexual - rape without consent"
cap label var SX_RAPE_ATT "Sexual - attempted rape"
cap label var SX_TCH "Sexual - touching"
cap label var SX_OTH "Sexual - other"
cap label var SX_OTH_NRAPE "Sexual - other than rape"
cap label var SXH "Sexual harassment"
cap label var SXH_WRK "Sexual harassment at work"
cap label var MSG "Violence using messaging apps"
cap label var SM "Violence using social media"
cap label var OTL "Violence using online tools"
cap label var NOTL "Violence not using online tools"
cap label var RAPE "Rape"
