cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var RDEV "Beneficiary of rural development measures"
cap label var RDEV_A "Investments"
cap label var RDEV_A01 "Investments for forests"
cap label var RDEV_A011 "Investments for afforestation"
cap label var RDEV_A012 "Investments for the establishment of agroforestry"
cap label var RDEV_A013 "Investments for the improvement of resilience in forestry"
cap label var RDEV_A014 "Investments in forest technologies and processing"
cap label var RDEV_A02 "Investments for animal welfare"
cap label var RDEV_A03 "Investments for infrastructures"
cap label var RDEV_A04 "Investments for the restoration of damage to agricultural or forestry production"
cap label var RDEV_A05 "Investments in diversification"
cap label var RDEV_A06 "Investments for the establishment of irrigation systems"
cap label var RDEV_A07 "Investments scheme for small farms"
cap label var RDEV_A08 "Investments for the production of renewable energy"
cap label var RDEV_A09 "Investments in physical assets"
cap label var RDEV_A10 "Non-productive investments"
cap label var RDEV_A11 "Investments for agricultural products"
cap label var RDEV_A111 "Investments to add value to agricultural products"
cap label var RDEV_A112 "Investments to respect Community standards"
cap label var RDEV_B "Farm and business development"
cap label var RDEV_B01 "Setting up young farmers"
cap label var RDEV_B02 "Start-up for new farmers"
cap label var RDEV_B03 "Start up for income diversification"
cap label var RDEV_B04 "Start-up for non-agricultural activities"
cap label var RDEV_B05 "Business support for small and medium-sized enterprises"
cap label var RDEV_B06 "Business development"
cap label var RDEV_C "Commitments"
cap label var RDEV_C01 "Commitments for animal welfare"
cap label var RDEV_C02 "Commitments for organic farming"
cap label var RDEV_C03 "Commitments for environment and climate"
cap label var RDEV_C04 "Commitments for the support of genetic resources"
cap label var RDEV_C05 "Commitments for environment and climate related to existing forest land"
cap label var RDEV_C06 "Commitments on afforested land or agroforestry systems"
cap label var RDEV_D "Area-specific disadvantages"
cap label var RDEV_D01 "Habitats and water framework Directive"
cap label var RDEV_D011 "Habitats Directive - Natura 2000"
cap label var RDEV_D012 "Water framework Directive"
cap label var RDEV_E "Natural constraints"
cap label var RDEV_E01 "Natural constraints related to area"
cap label var RDEV_E011 "Mountainous area"
cap label var RDEV_E012 "Non-mountainous area"
cap label var RDEV_E02 "Risk management"
cap label var RDEV_F "Knowledge exchange and dissemination of information"
cap label var RDEV_F01 "Learning from innovative projects"
cap label var RDEV_F02 "Participation in trainings"
cap label var RDEV_F03 "Received farm advisory services"
cap label var RDEV_G "Cooperation"
cap label var RDEV_G01 "Cooperation for generational renewal"
cap label var RDEV_G02 "Cooperation targeting commitments related to environment or climate"
cap label var RDEV_G03 "Cooperation to support quality schemes"
cap label var RDEV_G04 "Cooperation to support interbranch organisations"
cap label var RDEV_G05 "Cooperation to support tourism activities"
cap label var RDEV_H "Digitalisation"
cap label var RDEV_H01 "Digital tools for irrigation"
cap label var RDEV_H02 "Digital tools for the production of renewable energy"
cap label var RDEV_H03 "Digital tools for small farms"
cap label var RDEV_H04 "Training on digital tools"
cap label var RDEV_H05 "Precision farming"
cap label var RDEV_I "Other (n.e.c)"
cap label var NRDEV "Non-beneficiary of rural development measures"
cap label var RDEV15 "Advisory services, farm management and farm relief services (article 15)"
cap label var RDEV16 "Quality schemes for agricultural products, and foodstuffs (article 16)"
cap label var RDEV17 "Investment in physical assets (article 17)"
cap label var RDEV18 "Restoring agricultural production potential damaged by natural disasters and catastrophic events and introduction of appropriate prevention actions (article 18)"
cap label var RDEV19 "Farm and business development (article 19)"
cap label var RDEV19A1 "Farm and business development - business start-up support for young farmers (article 19A1)"
cap label var RDEV19A3 "Farm and business development - business start-up support for development of micro- and small- enterprises and natural persons in rural areas (article 19A3)"
cap label var RDEV21 "Investments in forest area development and improvement of the viability of forests (article 21)"
cap label var RDEV21A "Afforestation and creation of woodland (article 21A)"
cap label var RDEV21B "Establishment of agroforestry systems (article 21B)"
cap label var RDEV21C "Prevention and restoration of damage to forests from forest fires, natural disasters and catastrophic events, including pest and disease outbreaks, and climate related threats (article 21C)"
cap label var RDEV21D "Investments improving the resilience and environmental value as well as the mitigation potential of forest ecosystems (article 21D)"
cap label var RDEV21E "Investments in forestry technologies and in the processing, the mobilising and the marketing of forest products (article 21E)"
cap label var RDEV28 "Agri-environment-climate (article 28)"
cap label var RDEV29 "Organic farming (article 29)"
cap label var RDEV30 "Natura 2000 and water framework directive payments (article 30)"
cap label var RDEV31 "Payments to areas facing natural or other specific constraints (article 31)"
cap label var RDEV33 "Animal welfare (article 33)"
cap label var RDEV34 "Forest-environmental and climate services and forest conservation (article 34)"
cap label var RDEV36 "Risk management (article 36)"
cap label var RDEV40 "Financing of complementary national direct payments for Croatia (article 40)"
