cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var AC25000 "Alternating current - 50 Hz / 25 000 V"
cap label var AC15000 "Alternating current - 16 2/3 Hz / 15 000 V"
cap label var AC_KW_LT7P4 "Alternating current -  < 7,4 kW (slow, single-phase)"
cap label var AC_KW_LE7P4_LE22 "Alternating current - ≤ 7,4 kW but ≤ 22 kW (medium-speed, triple-phase)"
cap label var AC_KW_GT22 "Alternating current - > 22 kW (fast, triple-phase)"
cap label var AC_OTH "Alternating current - other"
cap label var DC3000 "Direct current - 3 000 V"
cap label var DC1500 "Direct current - 1 500 V"
cap label var DC_KW_LT50 "Direct current - < 50 kW (slow)"
cap label var DC_KW_LE50_LT150 "Direct current - ≤ 50 kW but < 150 kW (fast)"
cap label var DC_KW_LE150_LT350 "Direct current - ≤ 150 kW but < 350 kW (ultra-fast, level 1)"
cap label var DC_KW_GE350 "Direct current - ≥ 350 kW (ultra-fast, level 2)"
cap label var DC_OTH "Direct current - other"
cap label var UNK "Unknown"
