cap label var CODE "Label - English"
cap label var DPH "During paid hours"
cap label var ODPH "Only during paid hours"
cap label var MDPH "Mostly during paid hours"
cap label var OPH "Outside paid hours"
cap label var MOPH "Mostly outside paid hours"
cap label var OOPH "Only outside paid hours"
cap label var NJB "No job at that time"
cap label var NRP "No response"
