cap label var CODE "Label - English"
cap label var SSOW "Sows"
cap label var SPIG "Total pigs"
cap label var SFAT "Pigs for fattening"
cap label var SCOW "Dairy cows"
cap label var SNDC "Non-dairy cows"
cap label var SCAT "Cattle"
cap label var SGOT "Goats - total"
cap label var SGGK "Nanny-Goats and goats which have already kidded"
cap label var STSH "Sheeps - total"
cap label var SLRE "Lambs put to the ram and ewes"
cap label var SMEW "Milk ewes and milk ewe lambs put to the ram"
cap label var SOEW "Others ewes and ewe lambs put to the ram"
