cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var FIN "Financial reasons"
cap label var NINT "No interest"
cap label var PER "Personal reasons"
cap label var PER_HOL "Holidays, leisure and recreation"
cap label var PER_VFR "Visits to friends and relatives"
cap label var PER_OTH "Other personal reasons"
cap label var PROF "Professional, business"
cap label var HLTH "Health reasons"
cap label var SAFE "Safety reasons"
cap label var MKTG_SLS "Marketing or sales"
cap label var PRD "Production processes"
cap label var ORG_BAM "Organisation of business administration processes or management"
cap label var ICT_SECU "ICT security"
cap label var RND_INN_ACT "Research and development (R&D) or innovation activity"
cap label var GE1 "At least one of the purposes"
cap label var GE2 "At least two of the purposes"
cap label var GE3 "At least three of the purposes"
cap label var LOG "Logistics"
cap label var OTH "Other reason"
