cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var PC_LT10 "Less than 10 percent of all persons employed"
cap label var PC10_49 "From 10 percent to 49 percent of all persons employed"
cap label var PC_GE50 "50 percent or more of all persons employed"
cap label var PT_W "Persons who participated but wanted to participate more"
cap label var PT_NW "Persons who participated and did not want to participate more"
cap label var NPT_W "Persons who did not participate but wanted to participate"
cap label var NPT_NW "Persons who did not participate and did not want to participate"
cap label var NRP "No response"
