cap label var _0 "Unknown"
cap label var _1 "Sea"
cap label var _2 "Rail"
cap label var _3 "Road"
cap label var _4 "Air"
cap label var _5 "Post"
cap label var _7 "Fixed Mechanism"
cap label var _8 "Inland Waterway"
cap label var _9 "Self Propulsion"
