cap label var TSTL "Tie stall"
cap label var LSE_CUB "Loose/cubicle housing"
cap label var OUT "Free range - outdoors"
cap label var OUT_ALW "Always outdoors"
cap label var OUT_PART "Partly outdoors"
cap label var WACS_EXERY "Housing with access to exersice yards"
cap label var SLTD_FUL "Fully slatted floor"
cap label var SLTD_PART "Partially slatted floor"
cap label var SO_X_DPLT "Solid floor housing (excluding deep litter)"
cap label var DPLT "Deep litter housing"
cap label var DPLT_ENTI "Entire deep litter surface"
cap label var AVNLT "Aviary house (without litter)"
cap label var CAG "Cages"
cap label var CAG_MNRBLT "Cages with manure belt"
cap label var CAG_DPPIT "Cages with deep pits"
cap label var CAG_STLT "Cages with stilt house"
cap label var OTH "Other"
