cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var MRTG "Mortgage arrears as percentage of all owners"
cap label var MRTG_LOAN "Mortgage arrears as percentage of all owners with a mortgage"
cap label var RENT "Tenant rent arrears"
cap label var UTBL "Schedulated utility bills arrears"
cap label var DEBT_IN "Debts and in arrears"
cap label var DEBT_NIN "Debts but not in arrears"
cap label var DEBT_PAID "Debts to be paid"
cap label var NDEBT_PAID "No debts to be paid"
cap label var UNK "Unknown"
