cap label var _1 "NORMAL"
cap label var _2 "INWARD PROCESSING"
cap label var _3 "OUTWARD PROCESSING"
cap label var _4 "Total"
cap label var _5 "INWARD PROCESSING (SUSPENSION)"
cap label var _6 "INWARD PROCESSING (DRAWBACK)"
cap label var _7 "ECONOMIC PROCESSING ARRANGMENTS FOR TEXTILES"
cap label var _9 "NOT RECORDED FROM CUSTOMS DECLARATIONS"
