cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var ERN "Gross earnings"
cap label var E_F_M_PC "Gross earnings of women as a percentage of those of men"
cap label var OPAY "Overtime pay"
cap label var OP_E_PC "Overtime pay as a percentage of earnings"
cap label var MEAN_B_SALC_EUR "Mean annual bonuses per employee concerned in euro"
cap label var MEAN_B_SALC_PPS "Mean annual bonuses per employee concerned in PPS"
cap label var MEAN_H "Mean annual number of holidays"
cap label var SPAY "Shift pay"
cap label var SP_E_PC "Shift pay as a percentage of earnings"
cap label var BNS "Annual bonuses"
cap label var B_E_PC "Annual bonuses as a percentage of annual earnings"
cap label var HPAID "Hours paid"
cap label var OHP "Overtime hours paid"
cap label var OH_H_PC "Overtime hours as a percentage of hours"
cap label var MMW_MEAN_ME_PP "Monthly minimum wage as a proportion of the mean gross monthly earnings"
cap label var MMW_MED_ME_PP "Monthly minimum wage as a proportion of the median gross monthly earnings"
cap label var HOL "Annual holidays"
cap label var SAL "Employees"
cap label var LOC_UNIT "Local units"
cap label var MEAN_E_EUR "Mean earnings in euro"
cap label var MEAN_E_PPS "Mean earnings in PPS"
cap label var MED_E_EUR "Median earnings in euro"
cap label var MED_E_PPS "Median earnings in PPS"
cap label var D1_E_EUR "First decile earnings in euro"
cap label var D1_E_PPS "First decile earnings in PPS"
cap label var D9_E_EUR "Ninth decile earnings in euro"
cap label var D9_E_PPS "Ninth decile earnings in PPS"
cap label var MEAN_OP_SAL_EUR "Mean overtime pay per employee in euro"
cap label var MEAN_OP_SAL_PPS "Mean overtime pay per employee in PPS"
cap label var MEAN_OP_SALC_EUR "Mean overtime pay per employee concerned in euro"
cap label var MEAN_OP_SALC_PPS "Mean overtime pay per employee concerned in PPS"
cap label var MEAN_SP_SAL_EUR "Mean shift pay per employee in euro"
cap label var MEAN_SP_SAL_PPS "Mean shift pay per employee in PPS"
cap label var MEAN_SP_SALC_EUR "Mean shift pay per employee concerned in euro"
cap label var MEAN_SP_SALC_PPS "Mean shift pay per employee concerned in PPS"
cap label var MEAN_HP "Mean number of hours paid"
cap label var MEAN_OHP_SAL "Mean number of overtime hours paid per employee"
cap label var MEAN_OHP_SALC "Mean number of overtime hours paid per employee concerned"
cap label var MEAN_B_SAL_EUR "Mean annual bonuses per employee in euro"
cap label var MEAN_B_SAL_PPS "Mean annual bonuses per employee in PPS"
