cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var TOTXDUR "Total excluding durables and valuable goods"
cap label var TRA "Expenditure on transport"
cap label var REST "Expenditure on restaurants/cafés"
cap label var ACCOM "Expenditure on accommodation"
cap label var TRP_OTH "Other expenditure on tourism trips (including restaurants/cafes if not reported separately)"
cap label var DUR "Expenditure on durables and valuable goods"
cap label var PACK_ARR "Expenditure on package arrangement"
cap label var ASERV "Expenditure on ancillary services"
cap label var RD "Expenditure on R&D activities"
cap label var INIT "Expenditure of government before intergovernmental transfers"
cap label var FINL "Expenditure of government after intergovernmental transfers"
cap label var ADJ "Adjustments for changes in fund balances"
cap label var INV "Investment"
cap label var TRF_PAY "Transfers and payments"
cap label var TRF "Subsidies/transfers"
cap label var TRF_NET "Net transfers"
cap label var MNT "Maintenance"
cap label var CUR "Current expenditure"
cap label var CUR_LC "Current - labour cost"
cap label var CUR_LC_RND_IPER "Current - labour cost - internal R&D personnel"
cap label var CUR_LC_RND_EPER "Current - labour cost - external R&D personnel"
cap label var CUR_COMP "Expenditure for compensation of personnel"
cap label var CUR_COMPT "Expenditure for compensation of teachers (with active teaching responsibilities)"
cap label var CUR_COMPO "Expenditure for compensation of other pedagogical, administrative, professional, and support personnel"
cap label var CUR_RET "Expenditure for retirement pensions"
cap label var CUR_NLC "Expenditure for other non-salary compensation"
cap label var CUR_OTH "Current - other expenditure"
cap label var CUR_OTH_RND_EPER "Current - other expenditure - external R&D personnel"
cap label var CUR_OTHXRND_EPER "Current - other expenditure (excluding external R&D personnel)"
cap label var CAP "Capital expenditure"
cap label var CAP_LAND "Capital - land and buildings"
cap label var CAP_INSTRM "Capital - instruments and equipment"
cap label var CAP_SOFT "Capital - computer software"
cap label var CAP_IPP_OTH "Capital - other intellectual property products"
cap label var FA "Financial aid to households and students"
cap label var FA_GRNT "Scholarships and other grants to students/households"
cap label var FA_LOAN "Student loans"
cap label var DIR "Direct expenditure"
cap label var PAY "Payments"
cap label var PAY_NET "Net payments"
cap label var PAY_SEA "Payments for specific educational activities"
cap label var DW_ACQ "Acquisitions of dwellings"
cap label var DW_ACQ_NEW "New dwellings"
cap label var DW_ACQ_NEWP "Purchases of newly built dwellings"
cap label var DW_ACQ_NEWSB "Self-build dwellings and major renovations"
cap label var DW_ACQ_EXST "Existing dwellings new to the households"
cap label var DW_ACQ_OTH "Other services related to the acquisition of dwellings"
cap label var DW_OWN "Ownership of dwellings"
cap label var DW_OWN_RMNT "Major repairs and maintenance"
cap label var DW_OWN_INS "Insurance connected with dwellings"
cap label var DW_OWN_OTH "Other services related to ownership of dwellings"
cap label var INN "Expenditure on innovation (including R&D)"
cap label var INNXRND_CONTR_OUT "Expenditure on innovation excluding expenditure on R&D contracted out"
cap label var RND "Expenditure on R&D activities"
cap label var RND_IH "Expenditure on R&D performed in-house"
cap label var RND_CONTR_OUT "Expenditure on R&D contracted out"
cap label var INNXRND "Expenditure on innovation (excluding R&D)"
cap label var INNXRND_OWN_PER "Own personnel working on innovation"
cap label var INNXRND_CAP_GD "Capital goods for innovation (acquisition of machinery, equipment, software, intellectual property rights (IPRs), buildings, etc.)"
cap label var INNXRND_SMSP "Services, materials, supplies purchased for innovation"
cap label var INNXRND_OTH "Other expenditure on innovation (excl. R&D, own personnel, capital goods and purchases for innovation)"
cap label var ACQ_MEBTA "Acquisition of machinery, equipment, buildings and other tangible assets"
cap label var ACQ_MES "Acquisition of machinery, equipment and software"
cap label var SOFT_DBA_DA "Software development, database work and data analysis (include in-house costs and purchased services)"
cap label var RFM_IPR_PUR_LIC "Registering, filing and monitoring own Intellectual Property Rights (IPRs) and purchasing or licensing IPRs from others"
cap label var ACQ_EKNOW "Acquisition of other external knowledge"
cap label var MKTG_BB_ADV "Marketing, brand building, advertising (include in-house costs and purchased services)"
cap label var TNG_STAFF "Training own staff (include all in-house costs including wages and salaries of staff while being trained, and costs of purchased services from others)"
cap label var PRD_DESG "Product design (include in-house costs and purchased services)"
cap label var INN_OTH "Other expenditure on innovation (including design, training, marketing and other)"
cap label var MONE "Monetary expenditure"
cap label var NMONE "Non-monetary expenditure"
cap label var MONE_CB "Monetary cross-border expenditure"
cap label var FRVES "Expenditure on freight vessels"
cap label var FRVES_INV "Investment in freight vessels"
cap label var FRVES_MNT "Maintenance in freight vessels"
cap label var INF "Expenditure on infrastructure"
cap label var INF_INV "Investment in infrastructure"
cap label var INF_MNT "Maintenance in infrastructure"
cap label var VEH "Expenditure on transport vehicles"
cap label var VEH_INV "Investment in transport vehicles"
cap label var VEH_MNT "Maintenance in transport vehicles"
cap label var RSTK "Expenditure on rolling stock"
cap label var RSTK_INV "Investment in rolling stock"
cap label var RSTK_MNT "Maintenance in rolling stock"
cap label var OTH "Other expenditure"
cap label var NAP "Not applicable"
