cap label var CODE "Label - English"
cap label var MOD "Moderate"
cap label var LMOD "At least moderate"
cap label var LTL "A little"
cap label var LOT "A lot"
cap label var XTRM "Extreme"
cap label var NONE "None"
