cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var ELC "Electricity"
cap label var GAS "Gas (natural or propane)"
cap label var OIL_COAL "Oil or coal"
cap label var WDLG "Wood logs"
cap label var REN_BMA "Renewable energy or biomass"
cap label var OTH "Other"
cap label var UNK "Unknown"
