cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var PAS "Passengers"
cap label var EMP "Employed persons"
cap label var SAL "Employees"
cap label var DRIV "Drivers"
cap label var PED "Pedestrians"
cap label var LV_USR "Level crossing users"
cap label var UA_PER "Unauthorised persons"
cap label var CREW "Crew"
cap label var IPTN_FAM "Intimate partner or family member"
cap label var FAM_HLD_BLUE "Family member of EU Blue Cards holder"
cap label var FAM "Family member"
cap label var FAM_REL "Family and relatives"
cap label var FRD "Friends"
cap label var HLD_BLUE "EU Blue Cards holder"
cap label var IPTN "Intimate partner"
cap label var OTH "Others"
cap label var UNK "Unknown"
