cap label var CODE "Label - English"
cap label var TOT_CEP "Total environmental purposes"
cap label var TOT_CEP_EP "Total environmental purposes for environmental protection"
cap label var CEP01 "Air and climate"
cap label var CEP0101 "Reduction and control of greenhouse gases"
cap label var CEP010101 "Prevention of greenhouse gases emissions"
cap label var CEP010102 "Treatment of greenhouse gases"
cap label var CEP010103 "Monitoring and measurement of greenhouse gases"
cap label var CEP010199 "Others for reduction and control of greenhouse gases, n.e.c."
cap label var CEP0102 "Reduction and control of other air pollutants"
cap label var CEP010201 "Prevention of other air pollutants emissions"
cap label var CEP010202 "Treatment of other air pollutants"
cap label var CEP010203 "Monitoring and measurement of other air pollutants"
cap label var CEP010299 "Others for reduction and control of other air pollutants, n.e.c."
cap label var CEP02 "Energy"
cap label var CEP0201 "Energy from renewable sources"
cap label var CEP020101 "Production of energy from renewable sources"
cap label var CEP020102 "Equipment and technologies for renewable energy"
cap label var CEP020103 "Supporting services for renewable energy"
cap label var CEP020104 "Monitoring and measurement of energy from renewable sources"
cap label var CEP020199 "Others for energy from renewable sources, n.e.c."
cap label var CEP0202 "Energy savings and management"
cap label var CEP020201 "Energy savings through in-process modifications"
cap label var CEP020202 "Energy efficient buildings; other efficient energy-demand technologies"
cap label var CEP020202_NZEB "Nearly Zero Energy efficiency buildings (NZEB)"
cap label var CEP020203 "Monitoring and measurement for energy savings and management"
cap label var CEP020299 "Others for energy savings and management, n.e.c."
cap label var CEP03 "Wastewater and water resources"
cap label var CEP0301 "Wastewater management"
cap label var CEP030101 "Prevention of wastewater pollution"
cap label var CEP030102 "Management of sewerage networks"
cap label var CEP030103 "Treatment of wastewater"
cap label var CEP030104 "Treatment of cooling water"
cap label var CEP030105 "Monitoring and measurement for wastewater management"
cap label var CEP030199 "Others for wastewater management, n.e.c."
cap label var CEP0302 "Water savings and management of natural water resources"
cap label var CEP030201 "Reduction of water intake"
cap label var CEP030202 "Water reuse and savings, reduction of water losses and leaks"
cap label var CEP030203 "Replenishment of natural water resources"
cap label var CEP030204 "Monitoring and measurement of water savings and natural water resources"
cap label var CEP030299 "Others for water savings and management of natural water resources, n.e.c."
cap label var CEP04 "Waste, materials recovery and savings"
cap label var CEP0401 "Waste management"
cap label var CEP040101 "Prevention of solid waste pollution"
cap label var CEP040102 "Collection and transport of waste"
cap label var CEP040103 "Treatment and disposal of hazardous waste"
cap label var CEP040104 "Treatment and disposal of non-hazardous waste"
cap label var CEP040105 "Monitoring and measurement for waste management"
cap label var CEP040199 "Others for waste management, n.e.c."
cap label var CEP0402 "Materials recovery and savings"
cap label var CEP040201 "Reduction of the intake of wood"
cap label var CEP040202 "Reduction of the intake of mineral (metal, stone, glass, ceramics, other)"
cap label var CEP040203 "Reduction of the intake of fossil fuels for non-energy uses"
cap label var CEP040204 "Reduction of the intake of natural resources for textiles"
cap label var CEP040205 "Reduction of the intake of other materials"
cap label var CEP040206 "Monitoring and measurement for materials recovery and savings"
cap label var CEP040299 "Others for materials recovery and savings, n.e.c."
cap label var CEP05 "Soil, surface and groundwater, biodiversity and forest"
cap label var CEP0501 "Protection of soil, surface and groundwater"
cap label var CEP050101 "Prevention of pollutant infiltration into soil and water bodies"
cap label var CEP050102 "Cleaning up of soil and water bodies"
cap label var CEP050103 "Protection from erosion and other physical degradation of soil and water"
cap label var CEP050104 "Prevention and remediation of soil and groundwater salinity"
cap label var CEP050105 "Monitoring and measurement for soil, surface and groundwater protection"
cap label var CEP050199 "Others for soil, surface and groundwater protection, n.e.c."
cap label var CEP0502 "Protection of biodiversity and landscape"
cap label var CEP050201 "Protection and rehabilitation of species and habitats"
cap label var CEP050202 "Protection of natural and semi-natural landscapes"
cap label var CEP050203 "Monitoring and measurement for protection of biodiversity and landscape"
cap label var CEP050299 "Others for protection of biodiversity and landscape, n.e.c."
cap label var CEP0503 "Management of forest resources"
cap label var CEP050301 "Reforestation, afforestation and forest-related land management"
cap label var CEP050302 "Protection against forest fires"
cap label var CEP050303 "Monitoring and measurement of forest resources"
cap label var CEP050399 "Others for management of forest resources, n.e.c."
cap label var CEP06 "Noise and radiation"
cap label var CEP0601 "Protection against noise and vibration"
cap label var CEP060101 "Prevention and reduction of noise and vibration"
cap label var CEP060102 "Monitoring and measurement for protection against noise and vibration"
cap label var CEP060199 "Others for protection against noise and vibration, n.e.c."
cap label var CEP0602 "Protection against radiation"
cap label var CEP060201 "Protection of ambient media against radiation"
cap label var CEP060202 "Transport and treatment of high level radioactive waste"
cap label var CEP060203 "Monitoring and, measurement of radioactivity"
cap label var CEP060299 "Others for protection against radiation, n.e.c."
cap label var CEP07 "Research and development (R&D)"
cap label var CEP0701_03_05_07_09 "R&D environmental protection"
cap label var CEP0702_04_06_08 "R&D resource management"
cap label var CEP0701 "R&D for reduction and control of air emissions"
cap label var CEP070101 "R&D for reduction and control of greenhouse gases"
cap label var CEP070102 "R&D for reduction and control of other air pollutants"
cap label var CEP0702 "R&D for energy"
cap label var CEP070201 "R&D for renewables"
cap label var CEP070202 "R&D for renewables and energy savings"
cap label var CEP0703 "R&D for wastewater management"
cap label var CEP0704 "R&D for water resources"
cap label var CEP0705 "R&D for waste management"
cap label var CEP0706 "R&D for materials recovery and savings"
cap label var CEP0707 "R&D for soil, surface and groundwater and biodiversity"
cap label var CEP070701 "R&D for soil, surface and groundwater"
cap label var CEP070702 "R&D for biodiversity"
cap label var CEP0708 "R&D for forest management"
cap label var CEP0709 "R&D for noise and radiation"
cap label var CEP070901 "R&D for noise and vibration"
cap label var CEP070902 "R&D for radiation"
cap label var CEP08 "Cross-cutting and other environmental purposes"
cap label var CEP0801 "Environmental education and training"
cap label var CEP0802 "General environmental administration, management, regulation, dissemination and consultancy"
cap label var CEP0803 "Other environmental purposes"
cap label var CEP08_EP "Cross-cutting and other environmental purposes for environmental protection"
cap label var CEP_OTH "Other CEP not listed"
cap label var NUC_PRD "Production of nuclear energy"
cap label var NUC_RND "R&D for nuclear energy"
cap label var NRG_GRID "Energy grids"
cap label var LWC_TRA_ACT "Low carbon transport activities"
cap label var LWC_TRA_INFR "Low carbon transport infrastructures"
cap label var CCM "Climate change mitigation"
cap label var CCM_NCEP_OTH "Other climate change mitigation out of CEP scope"
cap label var CCM_NCEP "Climate change mitigation out of CEP scope"
