cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var SLAUGHT "Slaughterings"
cap label var SLAUGHT_ORG "Slaughterings - organic"
cap label var SLAUGHT_OTH "Slaughterings, other than in slaughterhouses"
cap label var GIP "Gross indigenous production"
cap label var IMP_LANI "Imports of live animals"
cap label var IMP_IEU_LANI "Intra-EU imports of live animals"
cap label var IMP_THRD_LANI "Import from third countries of live animals"
cap label var EXP_LANI "Exports of live animals"
cap label var EXP_IEU_LANI "Export intra-EU of live animals"
cap label var EXP_THRD_LANI "Export to third countries of live animals"
cap label var SL "Slaughterings"
cap label var GP "Gross indigenous production"
cap label var IL "Total imports of live animals"
cap label var IN "Intra-EU imports of live animals"
cap label var EL "Total exports of live animals"
cap label var LE "Export to third countries: live animals"
cap label var LI "Import from third countries: live animals"
cap label var EN "Export intra-EU: live animals"
cap label var SLD "Slaughterings, other than in slaughterhouses"
