cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var OGA_HLD_RH "Holder having other gainful activities (related to the agricultural holding)"
cap label var MOGA_HLD_RH "Holder having other gainful activities (related to the agricultural holding) as main activity"
cap label var SOGA_HLD_RH "Holder having other gainful activities (related to the agricultural holding) as secondary activity"
cap label var NOGA_HLD_RH "Holder not having other gainful activities (related to the agricultural holding)"
