cap label var CODE "Label - English"
cap label var ENT_PC "Enterprises - percentage"
cap label var ENT_NR "Enterprises - number"
cap label var ENT_BRTH_NR "Enterprise births - number"
cap label var ENT_BRTH_EMPSIZE_NR "Size of newly born enterprises - persons employed in newly born enterprises divided by enterprise births - average number"
cap label var ENT_DTH_EMPSIZE_NR "Employment in enterprise deaths - persons employed in enterprise deaths divided by enterprise deaths - average number"
cap label var ENT_DTH_NR "Enterprise deaths - number"
cap label var ENT_SRVL_NR "Enterprise survivals - number"
cap label var ENT_SRVL_EMPSIZE_NR "Size of survived enterprises - persons employed in enterprise survivals divided by the same enterprises - average number"
cap label var ENT_SRVL_EMPSIZE_Y3_NR "Size of 3 year old enterprises - persons employed in enterprises newly born 3 years back and survived divided by the same enterprises - average number"
cap label var ENT_SRVL_Y3_NR "Enterprise survivals (3-calendar year survival only) - number"
cap label var ENT_SRVL_CHB_NR "Cohort of enterprises newly born in the reference year having survived respective number of years in future - number"
cap label var ENT_SRVLR_Y3_PC "3 years old survived enterprises’ share of the business population - percentage"
cap label var ENT_SRVLR_PC "Survived enterprises’ share of the business population - percentage"
cap label var ENT_SRVLR_BRTH_PC "Survival rate - enterprise survivals of respective age, divided by enterprise births in respective birth year - percentage"
cap label var ENT_SRVLR_BRTH_CHB_PC "Survival rate - cohort of newly born enterprises in the reference year having survived respective number of years in future divided by enterprise births in the reference year - percentage"
cap label var ENT_SRVLR_BRTH_Y3_PC "Survival rate - 3 years old enterprise survivals divided by enterprise births three years ago - percentage"
cap label var ENT_SALGE1_NR "Enterprises having at least one employee - number"
cap label var ENT_SALGE1_BRTH_NR "Enterprises having the first employee - number"
cap label var ENT_SALGE1_BRTH_PP_PC "Proportion of enterprises having the first employee, by size class - percentage"
cap label var ENT_SALGE1_BRTH_EMPSIZE_NR "Size of enterprises having the first employee - persons employed in enterprises having the first employee divided by number of those enterprises - average number"
cap label var ENT_SALGE1_DTH_NR "Enterprises having no employees anymore - number"
cap label var ENT_SALGE1_DTH_PP_PC "Proportion of enterprises having no employees anymore, by size class - percentage"
cap label var ENT_SALGE1_DTH_EMPSIZE_NR "Size of enterprises having no employees anymore - persons employed in enterprises having no employees anymore divided by number of those enterprises - average number"
cap label var ENT_SALGE1_SRVL_NR "Survivals of enterprises having at least one employee - number"
cap label var ENT_SALGE1_SRVL_Y3_NR "Survivals of enterprises having at least one employee (3-calendar year survival only) - number"
cap label var ENT_SALGE1_SRVL_EMPSIZE_NR "Size of survived employer enterprises - persons employed in survivals of enterprises having at least one employee divided by the same enterprises - average number"
cap label var ENT_SALGE1_SRVL_EMPSIZE_Y3_NR "Size of 3 year old employer enterprises - persons employed in 3 year survivals of enterprises having at least one employee divided by the same enterprises - average number"
cap label var ENT_SALGE1_SRVL_CHB_NR "Cohort of enterprises having the first employee in the reference year and having survived respective number of years in future - number"
cap label var ENT_SALGE1_SRVLR_PC "Survived employer enterprises’ share - survivals of enterprises having at least one employee divided by enterprises having at least one employee - percentage"
cap label var ENT_SALGE1_SRVLR_Y3_PC "3 year old employer enterprises' share - 3 years old survivals of enterprises having at least one employee divided by enterprises having at least one employee - percentage"
cap label var ENT_SALGE1_SRVLR_BRTH_PC "Survival rate in employer enterprises - survivals of enterprises having at least one employee, of respective age, divided by enterprises having the first employee, in respective birth year - percentage"
cap label var ENT_SALGE1_SRVLR_BRTH_CHB_PC "Survival rate - cohort of enterprises having the first employee in the reference year and having survived respective number of years in future divided by enterprises having the first employee in the reference year - percentage"
cap label var ENT_SALGE1_SRVLR_BRTH_Y3_PC "3 years survival rate in employer enterprises - 3 years survivals of enterprises having at least one employee divided by enterprises having the first employee 3 years ago - percentage"
cap label var ENT_SALGE1_BRTHR_DTHR_PC "Employer enterprises business churn - birth and death rate in employer enterprises - percentage"
cap label var ENT_SALGE1_BRTHR_PC "Birth rate of employer enterprises - enterprises having the first employee divided by enterprises having at least one employee - percentage"
cap label var ENT_SALGE1_DTHR_PC "Death rate of employer enterprises - enterprises having no employees anymore divided enterprises having at least one employee - percentage"
cap label var ENT_HGRW_NR "High-growth enterprises measured in employment - number"
cap label var ENT_HGRW_SALSIZE_NR "Size of high growth enterprises, measured in employment - employees in high growth enterprises divided by high growth enterprises - average number"
cap label var ENT_HGRW_YNG_NR "Young high-growth enterprises measured in employment - number"
cap label var ENT_HGRW_YNG_SALSIZE_NR "Size of young high growth enterprises, measured in employment - employees in young high growth enterprises divided by high growth enterprises - average number"
cap label var ENT_HGRWR_YNG_PC "Share of young high growth enterprises, measured in employment, in the population of active enterprises - young high growth enterprises divided by active enterprises with at least 10 employees - percentage"
cap label var ENT_HGRWR_PC "Share of high growth enterprises, measured in employment - high growth enterprises divided by active enterprises with at least 10 employees - percentage"
cap label var ENT_BRTHR_DTHR_PC "Business churn - birth and death rate - percentage"
cap label var ENT_BRTHR_PC "Birth rate - enterprise births divided by active enterprises - percentage"
cap label var ENT_DTHR_PC "Death rate - enterprise deaths divided by active enterprises - percentage"
cap label var ENT_BRTH_PP_PC "Proportion of enterprise births by size class - percentage"
cap label var ENT_DTH_PP_PC "Proportion of enterprise deaths by size class - percentage"
cap label var GRW_ENT_PC "Net business population growth - percentage"
cap label var GRW_ENT_SALGE1_PC "Net growth of enterprises having at least one employee - percentage"
cap label var EMP_PC "Persons employed - percentage"
cap label var EMP_NR "Persons employed - number"
cap label var EMP_ENT_NR "Persons employed per enterprise - number"
cap label var EMP_MFG_PC "Share of employment in manufacturing total - percentage"
cap label var EMP_IND_PC "Share of employment in industry total - percentage"
cap label var EMP_BRTH_NR "Persons employed in newly born enterprises - number"
cap label var EMP_BRTHR_PC "Employment share of enterprise births - persons employed in newly born enterprises divided by persons employed in active enterprises - percentage"
cap label var EMP_DTH_NR "Persons employed in enterprise deaths - number"
cap label var EMP_SRVL_NR "Persons employed in enterprise survivals - number"
cap label var EMP_SRVL_YBRTH_NR "Persons employed in enterprise survivals, in the year of birth - number"
cap label var EMP_SRVL_Y3_NR "Persons employed in enterprises survivals (3-calendar year survival only) - number"
cap label var EMP_SRVL_YBRTH_Y3_NR "Persons employed in enterprises survivals, in the year of birth (3-calendar year survival only) - number"
cap label var EMP_SRVL_CHB_NR "Persons employed in enterprise survivals, by survival age among cohort of enterprises newly born in reference year having survived respective number of years in future - number"
cap label var EMP_SRVL_YBRTH_CHB_NR "Persons employed in the year of birth in the cohort of population of enterprises newly born in reference year having survived respective number of years in future - number"
cap label var EMP_SALGE1_NR "Persons employed in enterprises having at least one employee - number"
cap label var EMP_SALGE1_BRTH_NR "Persons employed in enterprises having the first employee - number"
cap label var EMP_SALGE1_BRTHR_PC "Employment share of enterprises having the first employee - persons employed in enterprises having the first employee divided by persons employed in enterprises having at least one employee - percentage"
cap label var EMP_SALGE1_DTH_NR "Persons employed in enterprises having no employees anymore - number"
cap label var EMP_SALGE1_DTHR_PC "Employment share of enterprises having no employees anymore - persons employed  in enterprises having no employees anymore divided by persons employed having at least one employee - percentage"
cap label var EMP_SALGE1_SRVL_NR "Persons employed in survivals of enterprises having at least one employee - number"
cap label var EMP_SALGE1_SRVL_Y3_NR "Persons employed in survivals of enterprises having at least one employee (3-calendar year survival only) - number"
cap label var EMP_SALGE1_SRVL_YBRTH_NR "Persons employed in survivals of enterprises having at least one employee, in the year of birth - number"
cap label var EMP_SALGE1_SRVL_YBRTH_Y3_NR "Persons employed in survivals of enterprises having at least one employee, in the year of birth (3-calendar year survival only) - number"
cap label var EMP_SALGE1_SRVL_CHB_NR "Persons employed in survivals of enterprises having at least one employee, by survival age, among cohort of enterprises having the first employee in the reference year and having survived respective number of years in future - number"
cap label var EMP_SALGE1_SRVL_YBRTH_CHB_NR "Persons employed in the year of birth in the cohort of population of employer enterprises newly born in reference year having survived respective number of years in future - number"
cap label var EMP_SALGE1_SRVLR_PC "Employment share of survived employer enterprises - persons employed in survivals of enterprises having at least one employee divided by persons employed in enterprises having at least one employee - percentage"
cap label var EMP_SALGE1_SRVLR_Y3_PC "Employment share of 3 year old employer enterprises - persons employed in 3 years survivals of enterprises having at least one employee divided by persons employed in enterprises having at least one employee - percentage"
cap label var EMP_DTHR_PC "Employment share of enterprise deaths - persons employed in enterprise deaths divided by persons employed in active enterprises - percentage"
cap label var EMP_SRVLR_PC "Employment share of survived enterprises - percentage"
cap label var EMP_SRVLR_Y3_PC "Employment share of 3 year old enterprises - persons employed in enterprises newly born 3 years back and survived, divided by persons employed in the population of active enterprises - percentage"
cap label var GRW_EMP_PC "Growth rate of employment - percentage"
cap label var GRW_EMP_SRVL_PC "Survived enterprises employment growth rate - persons employed in enterprise survivals divided by persons employed in the same enterprises in the year of birth - percentage"
cap label var GRW_EMP_SRVL_Y3_PC "3 years old survived enterprises employment growth rate - persons employed in enterprise 3 years survivals divided by persons employed in the same enterprises in the year of birth - percentage"
cap label var GRW_EMP_SRVL_CHB_PC "Survived enterprises employment growth rate by age - persons employed  in enterprise survivals, in the respective year in future among the cohort of enterprises newly born in the reference year having survived to respective year divided by persons employed in the year of birth by the same enterprises - percentage"
cap label var GRW_EMP_SALGE1_SRVL_PC "Survived employer enterprises employment growth rate - persons employed in survivals of enterprises having at least one employee divided by persons employed in the same enterprises in the year of birth - percentage"
cap label var GRW_EMP_SALGE1_SRVL_Y3_PC "3 year old employer enterprises employment growth rate - persons employed in 3 years survivals of enterprises having at least one employee divided by persons employed in the same enterprises in the year of birth - percentage"
cap label var GRW_EMP_SALGE1_SRVL_CHB_PC "Survived employer enterprises employment growth rate by age - persons employed in survivals of enterprises, having at least one employee, in the respective year in future among the cohort of enterprises having the first employee in the reference year and having survived to respective year divided by persons employed in the year of birth of the same enterprises - percentage"
cap label var SAL_NR "Employees - number"
cap label var SAL_BRTH_NR "Employees in newly born enterprises - number"
cap label var SAL_DTH_NR "Employees in enterprise deaths - number"
cap label var SAL_SALGE1_NR "Employees in enterprises having at least one employee - number"
cap label var SAL_SALGE1_BRTH_NR "Employees in enterprises having the first employee - number"
cap label var SAL_SALGE1_DTH_NR "Employees in enterprises having no employees anymore - number"
cap label var SAL_SALGE1_EMP_BRTHR_PC "New employer enterprise paid employment rate - number of employees in enterprises having the first employee divided by persons employed in the same enterprises - percentage"
cap label var SAL_HGRW_NR "Employees in high-growth enterprises measured in employment - number"
cap label var SAL_HGRW_YNG_NR "Employees in young high-growth enterprises measured in employment - number"
cap label var SAL_HGRWR_YNG_PC "Employment share of young high growth enterprises, measured in employment, in the population of active enterprises - employees in  young high growth enterprises divided by employees in active enterprises with at least 10 employees - percentage"
cap label var SAL_HGRWR_PC "Employment share of high growth enterprises, measured in employment - employees in high growth enterprises divided by employees in active enterprises with at least 10 employees - percentage"
cap label var SAL_EMP_BRTHR_PC "New enterprise paid employment rate - employees in newly born enterprises divided by persons employed in newly born enterprises - percentage"
cap label var EMP_LOC_MFG_PC "Share of employment in local units in manufacturing total - percentage"
cap label var EMP_PLOC_NR "Persons employed per local unit - number"
cap label var EMP_LOC_NR "Persons employed in local units - number"
cap label var LOC_NR "Local units - number"
cap label var GRW_EMP_LOC_PC "Growth rate of employment in local units - percentage"
cap label var SAL_EMP_PC "Share of employees in persons employed - percentage"
cap label var SAL_FTE_NR "Employees in full-time equivalent units - number"
cap label var AV_MFG_PC "Share of value added in manufacturing total - percentage"
cap label var AV_VAL_OUT_PC "Value added in output value - percentage"
cap label var AV_SAL_TEUR "Value added per employee - thousand euro"
cap label var AV_SAL_FTE_TEUR "Value added per employee FTE - thousand euro"
cap label var AV_HW_EUR "Value added per hours worked by employees - euro"
cap label var AV_MEUR "Value added - million euro"
cap label var VAL_OUT_MFG_PC "Share of value of output in manufacturing total - percentage"
cap label var VAL_OUT_MEUR "Value of output - million euro"
cap label var LABPRY_TEUR "Apparent labour productivity - thousand euro"
cap label var WAGE_LABPRY_PC "Wage adjusted labour productivity - percentage"
cap label var WAGE_MEUR "Wages and salaries - million euro"
cap label var WAGE_LOC_MEUR "Wages and salaries in local units - million euro"
cap label var HW_NR "Hours worked by employees - number"
cap label var EXPN_SAL_BEN_HW_EUR "Employee benefits expense per hours worked by employees - euro"
cap label var EXPN_SAL_BEN_VAL_OUT_PC "Share of employee benefits expense in production - percentage"
cap label var EXPN_SAL_BEN_PUR_PC "Share of employee benefits expense in total purchases of goods and services - percentage"
cap label var EXPN_SAL_BEN_MEUR "Employee benefits expense - million euro"
cap label var AVG_EXPN_SAL_BEN_TEUR "Average employee benefits expense - thousand euro"
cap label var SS_COST_EXPN_SAL_BEN_PC "Employer's social charges as a percentage of employee benefits expense - percentage"
cap label var SS_COST_MEUR "Social security costs - million euro"
cap label var SLS_TINV_MEUR "Sales proceeds of tangible investments - million euro"
cap label var GOS_AV_PC "Share of gross operating surplus in value added - percentage"
cap label var GOS_MEUR "Gross operating surplus - million euro"
cap label var GOS_EMP_TEUR "Gross operating surplus per person employed - thousand euro"
cap label var GOR_PC "Gross operating rate - percentage"
cap label var LC_EMP_TEUR "Unit labour costs per person employed - thousand euro"
cap label var LC_EMP_LOC_TEUR "Unit labour costs per person employed in local unit - thousand euro"
cap label var LC_AV_PC "Unit labour costs per value added - percentage"
cap label var LC_SAL_FTE_TEUR "Labour cost per employee FTE - thousand euro"
cap label var GRSINV_TNCA_EMP_TEUR "Investment per employee - tangible non-current assets - thousand euro"
cap label var GRSINV_TNCA_AV_PC "Investment rate - tangible non-current assets - percentage"
cap label var GRSINV_MAC_EMP_TEUR "Investment per employee - machinery and equipment - thousand euro"
cap label var GRSINV_MAC_AV_PC "Investment rate - machinery and equipment - percentage"
cap label var GRSINV_TNCA_MEUR "Gross investment in tangible non-current assets - million euro"
cap label var GRSINV_LND_MEUR "Gross investment in land - million euro"
cap label var GRSINV_BLD_MEUR "Gross investment in the acquisition of existing buildings - million euro"
cap label var GRSINV_CON_MEUR "Gross investment in construction and improvement of buildings - million euro"
cap label var GRSINV_MAC_MEUR "Gross investment in machinery and equipment - million euro"
cap label var GRSINV_NTNCA_XGWL_MEUR "Gross investment in intangible non-current assets, other than goodwill - million euro"
cap label var PUR_MEUR "Purchases of goods and services (total) - million euro"
cap label var PUR_RS_MEUR "Purchases of goods and services for resale - million euro"
cap label var PUR_AGN_MEUR "Expenses on services provided through agency workers - million euro"
cap label var PUR_RNT_MEUR "Expenses of long term rental and operating leases - million euro"
cap label var PUR_NRG_MEUR "Purchases of energy products - million euro"
cap label var PUR_SCTR_MEUR "Payments to subcontractors - million euro"
cap label var STK_CHG_GD_MEUR "Change in stock of goods - million euro"
cap label var STK_CHG_GD_FIN_MEUR "Change in stock of finished goods and work-in-progress - million euro"
cap label var STK_CHG_GD_RS_MEUR "Change in stock of goods for resale - million euro"
cap label var GM_GD_RS_MEUR "Gross margin on goods for resale - million euro"
cap label var INV_SOFT_MEUR "Investment in purchased software - million euro"
cap label var NETTUR_MEUR "Net turnover - million euro"
cap label var NETTUR_AFFI_MEUR "Net turnover from agriculture, forestry, fishing and industrial activities - million euro"
cap label var NETTUR_PA_MEUR "Net turnover from the principal activity at the NACE three-digit level - million euro"
cap label var NETTUR_IND_MEUR "Net turnover from industrial activities - million euro"
cap label var NETTUR_IND_XCON_MEUR "Net turnover from industrial activities excluding construction - million euro"
cap label var NETTUR_CON_MEUR "Net turnover from construction - million euro"
cap label var NETTUR_SERV_MEUR "Net turnover from service activities - million euro"
cap label var NETTUR_TRD_MEUR "Net turnover from trading activities of purchase and resale and from intermediary activities - million euro"
cap label var NETTUR_BLD_MEUR "Net turnover from building - million euro"
cap label var NETTUR_CEGNG_MEUR "Net turnover from civil engineering - million euro"
cap label var NETTUR_SCTR_MEUR "Net turnover from subcontracting - million euro"
cap label var NETTUR_EMP_TEUR "Net turnover per person employed - thousand euro"
cap label var NETTUR_MFG_PC "Share of net turnover in manufacturing total - percentage"
cap label var EXP_IM_RND "Intramural R & D expenditure"
cap label var EXP_IM_RND_MEUR "Intramural R & D expenditure - million euro"
cap label var PER_RND_NR "R & D personnel - number"
cap label var AV_ENT_TEUR "Value added per enterprise - thousand euro"
cap label var NETTUR_ENT_TEUR "Net turnover per enterprise - thousand euro"
cap label var JOB_LOST "Jobs lost"
cap label var JOB_LOST_PC "Jobs lost - percentage"
cap label var JOB_LOST_NR "Jobs lost - number"
cap label var JOB_CREA "Jobs created"
cap label var JOB_CREA_PC "Jobs created - percentage"
cap label var JOB_CREA_NR "Jobs created - number"
cap label var ENT_HGRW_NETTUR_NR "High growth enterprises measured in net turnover - number"
cap label var ENT_HGRW_YNG_NETTUR_NR "Young high growth enterprises (gazelles) measured in net turnover - number"
cap label var ENT_M_HGRW_NR "High growth micro enterprises measured in employment - number"
cap label var SAL_M_HGRW_NR "Employees in high growth micro enterprises measured in employment - number"
cap label var ENT_M_HGRW_YNG_NR "Young high growth micro enterprises measured in employment - number"
cap label var SAL_M_HGRW_YNG_NR "Employees in young high growth micro enterprises measured in employment - number"
cap label var ENT_HGRWR_NETTUR_PC "Share of high growth enterprises measured in net turnover in the population of active enterprises with at least 10 employees - percentage"
cap label var ENT_HGRWR_YNG_NETTUR_PC "Share of young high growth enterprises (gazelles) measured in net turnover in the population of active enterprises with at least 10 employees - percentage"
cap label var ENT_M_HGRWR_PC "Share of high growth micro enterprises measured in employment in the total population of active enterprises - percentage"
cap label var SAL_M_HGRWR_PC "Share of employees from high growth micro enterprises measured in employment in the total population of active enterprises - percentage"
cap label var ENT_M_HGRWR_YNG_PC "Share of young high growth micro enterprises measured in employment in the total population of active enterprises - percentage"
cap label var SAL_M_HGRWR_YNG_PC "Share of employees in young high growth micro enterprises measured in employment in the total population of active enterprises - percentage"
cap label var QTY_NET_MA_T "Quantity of traded goods - tonnes"
cap label var STAT_VAL_MEUR "Statistical value of trade - million euro"
