cap label var TOTAL "Total"
cap label var EMPL_OWN "Employer's premises or own premises"
cap label var HOM "Home"
cap label var CLIENT "Clients' place"
cap label var NFIX "Not fixed"
cap label var NFIX_OTH "Not fixed or other"
cap label var NAT_IN "In the territory of the reporting country"
cap label var NAT_UNK "Unknown place of work in the reporting country"
cap label var NAT_OUT "Not in the territory of the reporting country"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
