cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var SCO "Social contributions"
cap label var SCO_EMPL "Employers' social contributions"
cap label var SCO_PER_PRO "Protected persons' social contributions"
cap label var GOV_GEN "General government contributions"
cap label var GOV_GEN_EM "General government contributions - earmarked taxes"
cap label var GOV_GEN_REVGEN "General government contributions - general revenue"
cap label var REC_OTH "Other receipts"
cap label var REC_OTH_PROP "Other receipts - property income"
cap label var REC_OTH_O "Other receipts - miscellaneous other"
cap label var TOTALNOREROUTE "Total receipts"
cap label var SOC_CONTRIBNOREROUTE "Social contribution"
cap label var SEMPLOYER "Employers' social contribution"
cap label var SEACTUAL "Actual employers' social contribution"
cap label var SEIMPUTED "Imputed employers' social contribution"
cap label var SPROT_PERS "Social contribution paid by the protected persons"
cap label var SPEMPLOY "Social contribution paid by the employees"
cap label var SPSELF "Social contribution paid by the self-employed"
cap label var SP_OTH "Social contribution paid by pensioners and other protected persons"
cap label var GG_CONTRIB "General government contributions"
cap label var GEARLYMARK "Earmarked taxes"
cap label var GGENREV "General revenue"
