cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var MOD_SEV "Moderate or severe"
cap label var MOD "Moderate"
cap label var SOME "Some"
cap label var LTD_NSEV_NONE "Limited but not severely or not limited at all"
cap label var LTD "Limited"
cap label var SEV "Severe"
cap label var SM_SEV "Some or severe"
cap label var NONE "None"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
