cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var CPA_A "Products of agriculture, forestry and fishing"
cap label var CPA_A01 "Products of agriculture, hunting and related services"
cap label var CPA_A02 "Products of forestry, logging and related services"
cap label var CPA_A03 "Fish and other fishing products; aquaculture products; support services to fishing"
cap label var CPA_B_E "Industrial products (except construction works)"
cap label var CPA_B "Mining and quarrying"
cap label var CPA_C "Manufactured products"
cap label var CPA_C10_12 "Food, beverages and tobacco products"
cap label var CPA_C13_15 "Textiles, wearing apparel, leather and related products"
cap label var CPA_C16_18 "Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials; Paper and paper products; Printing and recording services"
cap label var CPA_C16 "Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials"
cap label var CPA_C17 "Paper and paper products"
cap label var CPA_C18 "Printing and recording services"
cap label var CPA_C19 "Coke and refined petroleum products"
cap label var CPA_C20_21 "Chemicals and basic pharmaceutical"
cap label var CPA_C20 "Chemicals and chemical products"
cap label var CPA_C21 "Basic pharmaceutical products and pharmaceutical preparations"
cap label var CPA_C22_23 "Rubber and plastic products; Other non-metallic mineral products"
cap label var CPA_C22 "Rubber and plastic products"
cap label var CPA_C23 "Other non-metallic mineral products"
cap label var CPA_C24_25 "Basic metals; Fabricated metal products, except machinery and equipment"
cap label var CPA_C24 "Basic metals"
cap label var CPA_C25 "Fabricated metal products, except machinery and equipment"
cap label var CPA_C26 "Computer, electronic and optical products"
cap label var CPA_C27 "Electrical equipment"
cap label var CPA_C28 "Machinery and equipment n.e.c."
cap label var CPA_C29_30 "Motor vehicles, trailers and semi-trailers; Other transport equipment"
cap label var CPA_C29 "Motor vehicles, trailers and semi-trailers"
cap label var CPA_C30 "Other transport equipment"
cap label var CPA_C31_32 "Furniture and other manufactured goods"
cap label var CPA_C31_33 "Furniture and other manufactured goods;Repair and installation services of machinery and equipment"
cap label var CPA_C33 "Repair and installation services of machinery and equipment"
cap label var CPA_D_E "Electricity, gas, steam and air conditioning; Water supply; sewerage, waste management and remediation services"
cap label var CPA_D "Electricity, gas, steam and air conditioning"
cap label var CPA_D35 "Electricity, gas, steam and air conditioning"
cap label var CPA_E "Water supply; sewerage, waste management and remediation services"
cap label var CPA_E36 "Natural water; water treatment and supply services"
cap label var CPA_E37_39 "Sewerage services; sewage sludge; waste collection, treatment and disposal services; materials recovery services; remediation services and other waste management services"
cap label var CPA_F "Constructions and construction works"
cap label var CPA_G_I "Wholesale and retail trade, transport, accomodation and food service activities"
cap label var CPA_G "Wholesale and retail trade services; repair services of motor vehicles and motorcycles"
cap label var CPA_G45 "Wholesale and retail trade and repair services of motor vehicles and motorcycles"
cap label var CPA_G46 "Wholesale trade services, except of motor vehicles and motorcycles"
cap label var CPA_G47 "Retail trade services, except of motor vehicles and motorcycles"
cap label var CPA_H "Transportation and storage services"
cap label var CPA_H49 "Land transport services and transport services via pipelines"
cap label var CPA_H50 "Water transport services"
cap label var CPA_H51 "Air transport services"
cap label var CPA_H52 "Warehousing and support services for transportation"
cap label var CPA_H53 "Postal and courier services"
cap label var CPA_I "Accommodation and food services"
cap label var CPA_J "Information and communication services"
cap label var CPA_J58_60 "Publishing services; Motion picture, video and television programme production services, sound recording and music publishing; programming and broadcasting services"
cap label var CPA_J58 "Publishing services"
cap label var CPA_J59_60 "Motion picture, video and television programme production services, sound recording and music publishing; programming and broadcasting services"
cap label var CPA_J61 "Telecommunications services"
cap label var CPA_J62_63 "Computer programming, consultancy and related services; Information services"
cap label var CPA_K "Financial and insurance services"
cap label var CPA_K64 "Financial services, except insurance and pension funding"
cap label var CPA_K65 "Insurance, reinsurance and pension funding services, except compulsory social security"
cap label var CPA_K66 "Services auxiliary to financial services and insurance services"
cap label var CPA_L "Real estate services"
cap label var CPA_L68 "Real estate services"
cap label var CPA_L68A "Imputed rents of owner-occupied dwellings"
cap label var CPA_L68B "Real estate services excluding imputed rents"
cap label var CPA_M_N "Professional, scientific and technical services; administrative and support services"
cap label var CPA_M "Professional, scientific and technical services"
cap label var CPA_M69_70 "Legal and accounting services; services of head offices; management consultancy services"
cap label var CPA_M71 "Architectural and engineering services; technical testing and analysis services"
cap label var CPA_M72 "Scientific research and development services"
cap label var CPA_M73 "Advertising and market research services"
cap label var CPA_M74_75 "Other professional, scientific and technical services and veterinary services"
cap label var CPA_N "Administrative and support services"
cap label var CPA_N77 "Rental and leasing services"
cap label var CPA_N78 "Employment services"
cap label var CPA_N79 "Travel agency, tour operator and other reservation services and related services"
cap label var CPA_N80_82 "Security and investigation services; services to buildings and landscape; office administrative, office support and other business support services"
cap label var CPA_O_Q "Public administration, defence, education, human health and social work services"
cap label var CPA_O "Public administration and defence services; compulsory social security services"
cap label var CPA_O84 "Public administration and defence services; compulsory social security services"
cap label var CPA_P "Education services"
cap label var CPA_P85 "Education services"
cap label var CPA_Q "Human health and social work services"
cap label var CPA_Q86 "Human health services"
cap label var CPA_Q87_88 "Residential care services; social work services without accommodation"
cap label var CPA_R_U "Arts, entertainment and recreation; other services; services of household and extra-territorial organizations and bodies"
cap label var CPA_R_S "Entertainement, recreations and other services"
cap label var CPA_R "Arts, entertainment and recreation services"
cap label var CPA_R90_92 "Creative, arts, entertainment, library, archive, museum, other cultural services; gambling and betting services"
cap label var CPA_R93 "Sporting services and amusement and recreation services"
cap label var CPA_S "Other services"
cap label var CPA_S94 "Services furnished by membership organisations"
cap label var CPA_S95 "Repair services of computers and personal and household goods"
cap label var CPA_S96 "Other personal services"
cap label var CPA_T_U "Services of households as employers; undifferentiated goods and services produced by households for own use; Services provided by extraterritorial organisations and bodies"
cap label var CPA_T "Services of households as employers; undifferentiated goods and services produced by households for own use"
cap label var CPA_U "Services provided by extraterritorial organisations and bodies"
cap label var TOTADJ "Total adjusted"
cap label var B1G "Value added, gross"
cap label var B2A3N "Operating surplus and mixed income, net"
cap label var B2A3G "Operating surplus and mixed income, gross"
cap label var B3G "Mixed income, gross"
cap label var D1 "Compensation of employees"
cap label var D11 "Wages and salaries"
cap label var D21X31 "Taxes less subsidies on products"
cap label var D29X39 "Other taxes less other subsidies on production"
cap label var OP "Purchases"
cap label var OP_RES "Direct purchases abroad by residents"
cap label var OP_NRES "Purchases on the domestic territory by non-residents"
cap label var P1 "Output"
cap label var P2 "Intermediate consumption"
cap label var P2_ADJ "Total intermediate consumption /final use"
cap label var P3_P5 "Final consumption expediture and Gross Capital formation"
cap label var P3 "Final consumption expediture"
cap label var P3_S13 "Final consumption expenditure by government"
cap label var P3_S14 "Final consumption expenditure by households"
cap label var P3_S15 "Final consumption expenditure by non-profit organisations serving households (NPISH)"
cap label var P5 "Gross capital formation"
cap label var P5M "Changes in inventories and acquisition less disposals of valuables"
cap label var P6 "Exports of goods and services"
cap label var P6_B0 "Exports to EU members states"
cap label var P6_D0 "Exports to non-member of the EU"
cap label var P6_U2 "Exports to members of the euro area"
cap label var P6_U3 "Exports to non-members of the euro area"
cap label var P6D "Goods sent abroad"
cap label var P6_ADJ "Cif/fob adjustments on exports"
cap label var ADJ_P6 "Cif/fob adjustments on exports"
cap label var P7 "Imports of goods and services"
cap label var P7_ADJ "Cif/fob adjustments on imports"
cap label var ADJ_P7 "Cif/fob adjustments on imports"
cap label var P7_B0 "Imports of goods and services from the EU Member States"
cap label var P7_D0 "Imports of goods and services from the institutions of the EU"
cap label var P7_U2 "Imports of goods and services from members of the Monetary Union"
cap label var P7_U3 "Imports of goods and services from non-members of the Monetary Union"
cap label var P11 "Market output"
cap label var P12 "Output for own final use"
cap label var P13 "Other non-market output"
cap label var P51C "Consumption of fixed capital"
cap label var P51G "Gross capital formation"
cap label var P52 "Changes in inventories"
cap label var P53 "Acquisitions less disposals of valuables"
cap label var LE "Closing balance sheet"
cap label var IMP "Use of imported products"
cap label var EMP_DC "Total employment domestic concept"
cap label var TU "Total use"
cap label var TFU "Total final use"
cap label var TU_PP "Total use at purchasers' prices"
cap label var TS_BP "Total supply at basic prices"
cap label var CIFOBADJ "Cif/fob adjustment"
cap label var DSP "Discrepancy"
cap label var DISC "Discrepancy"
cap label var ITTM "International trade and transport margins"
cap label var MCH "Merchanting"
cap label var NAP "Not applicable"
