cap label var CODE "Label - English"
cap label var M11 "Enterprises"
cap label var M111 "Enterprises from NACE Rev.1.1 section D"
cap label var M112 "Enterprises from NACE Rev.1.1 section K"
cap label var M113 "Enterprises from NACE Rev.1.1 all other sections"
cap label var M12 "Public sector"
cap label var M13 "Households"
cap label var TOTAL "Total"
