cap label var TOTAL "Total"
cap label var CTC_PES "Contact public employment service"
cap label var CTC_PEA "Contact private employment agency"
cap label var APPL_EMPL "Apply to employers directly"
cap label var ASK_RFTU "Ask friends, relatives, trade unions"
cap label var PUBL_ADV "Publish or answer job advertisements"
cap label var STU_ADV "Study job advertisements"
cap label var TAKE_TEST "Take test, interview, examination"
cap label var LOOK_LAND "Look for land, premises, equipment"
cap label var LOOK_LIC "Look for licenses, permits, financial resources"
cap label var OTH "Other"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
