cap label var _1 "Normal"
cap label var _2 "Inward processing"
cap label var _3 "Outward processing"
cap label var _5 "Inward processing (suspension)"
cap label var _6 "Inward processing (drawback)"
cap label var _7 "Economic processing arrangments for textiles"
cap label var _9 "Not recorded from customs declarations"
cap label var T "Total"
