cap label var CODE "Label - English"
cap label var VIM_TOT "Total main grape varieties"
cap label var VIRM_TOT "Total main red grape varieties (R)"
cap label var VIR001 "Agiorgitiko (R)"
cap label var VIR001A "Agiorgitiko N (R)"
cap label var VIR002 "Aglianico (R)"
cap label var VIR002A "Aglianico/Aglianico del Vulture N.(R)"
cap label var VIR003 "Aglianico del Vulture (R)"
cap label var VIR004 "Alfrocheiro (R)"
cap label var VIR004A "Tinta Bastardinha (R)"
cap label var VIR005 "Alicante Henri Bouschet (R)"
cap label var VIR005A "Alicante Bouschet (R)"
cap label var VIR005B "Garnacha Tintorera (R)"
cap label var VIR005C "Alicante Henri Bouschet N (R)"
cap label var VIR005D "Alicante Bouschet (R)"
cap label var VIR006 "Alphonse Lavallee (R)"
cap label var VIR006A "Alphonse Lavallée N (R)"
cap label var VIR007 "Ancellotta (R)"
cap label var VIR007A "Ancellotta (R)"
cap label var VIR008 "Aramon noir (R)"
cap label var VIR008A "Aramon N (R)"
cap label var VIR009 "Avarengo (R)"
cap label var VIR010 "Babeasca neagra (R)"
cap label var VIR010A "Babeasca neagra (R)"
cap label var VIR011 "Baga (R)"
cap label var VIR011A "Baga (R)"
cap label var VIR012 "Barbera nera (R)"
cap label var VIR012A "Barbera N. (R)"
cap label var VIR013 "Trousseau noir (R)"
cap label var VIR013A "Bastardo (R)"
cap label var VIR013B "Graciosa (R)"
cap label var VIR013C "Trousseau N (R)"
cap label var VIR013D "Maturana Tinta (R)"
cap label var VIR014 "Blauburger (R)"
cap label var VIR014A "Blauburger (R)"
cap label var VIR014B "Blauburger (R)"
cap label var VIR015 "Blaufrankisch (R)"
cap label var VIR015A "Burgund mare (R)"
cap label var VIR015B "Frankovka (R)"
cap label var VIR015C "Frankovka modrá (R)"
cap label var VIR015D "Kékfrankos (R)"
cap label var VIR015E "Limberger, blauer (R)"
cap label var VIR015F "Modra frankinja (R)"
cap label var VIR015G "Blaufränkisch (R)"
cap label var VIR015H "Frankovka (R)"
cap label var VIR016 "Bobal (R)"
cap label var VIR017 "Bombino nero (R)"
cap label var VIR017A "Bombino nero N. (R)"
cap label var VIR018 "Bonarda piemontese (R)"
cap label var VIR018A "Bonarda N. (R)"
cap label var VIR019 "Brachetto (R)"
cap label var VIR019A "Brachetto (R)"
cap label var VIR020 "Cabernet franc (R)"
cap label var VIR020A "Cabernet Franc (R)"
cap label var VIR020B "Cabernet franc (R)"
cap label var VIR020C "Cabernet franc N (R)"
cap label var VIR020D "Cabernet franc N. (R)"
cap label var VIR020E "Cabernet Franc (R)"
cap label var VIR020F "Cabernet Franc (R)"
cap label var VIR020G "Cabernet franc N (R)"
cap label var VIR020H "Cabernet franc (R)"
cap label var VIR020I "Cabernet franc (R)"
cap label var VIR020J "Cabernet franc (R)"
cap label var VIR020K "Cabernet franc (R)"
cap label var VIR021 "Cabernet Sauvignon (R)"
cap label var VIR021A "Cabernet Sauvignon (R)"
cap label var VIR021B "Cabernet sauvignon (R)"
cap label var VIR021C "Cabernet-Sauvignon N (R)"
cap label var VIR021D "Cabernet Sauvignon (R)"
cap label var VIR021E "Cabernet Sauvignon N. (R)"
cap label var VIR021F "Cabernet Sauvignon (R)"
cap label var VIR021G "Cabernet Sauvignon (R)"
cap label var VIR021H "Cabernet Sauvignon (R)"
cap label var VIR021I "Cabernet Sauvignon N (R)"
cap label var VIR021J "Cabernet sauvignon (R)"
cap label var VIR021K "Cabernet Sauvignon (O)"
cap label var VIR021L "Cabernet Sauvignon (R)"
cap label var VIR021M "Cabernet sauvignon (R)"
cap label var VIR021N "Canaiolo nero N. (R)"
cap label var VIR022 "Borraçal (R)"
cap label var VIR022A "Caíno (R)"
cap label var VIR022B "Borraçal (R)"
cap label var VIR023 "Calabrese (R)"
cap label var VIR023A "Calabrese N. (R)"
cap label var VIR024 "Caladoc (R)"
cap label var VIR024A "Caladoc N (R)"
cap label var VIR024B "Caladoc (R)"
cap label var VIR025 "Canaiolo nero (R)"
cap label var VIR026 "Carignan noir (R)"
cap label var VIR026A "Carignan (R)"
cap label var VIR026B "Carignano (R)"
cap label var VIR026C "Carignan noir (R)"
cap label var VIR027 "Carmenere (R)"
cap label var VIR027A "Carmenère N (R)"
cap label var VIR027B "Carmenere N. (R)"
cap label var VIR027C "Cabernet Nostrano (R)"
cap label var VIR027D "Cabernet Italiano (R)"
cap label var VIR027E "Cabernet (R)"
cap label var VIR028 "Castelão (R)"
cap label var VIR028A "João-de-Santarem (R)"
cap label var VIR028B "Periquita (R)"
cap label var VIR029 "Ciliegiolo (R)"
cap label var VIR029A "Ciliegiolo N. (R)"
cap label var VIR030 "Cinsaut (R)"
cap label var VIR030A "Cinsaut N (R)"
cap label var VIR030B "Cinsault N (R)"
cap label var VIR030C "Cinsaut N (R)"
cap label var VIR031 "Corvina Veronese (R)"
cap label var VIR031A "Corvina N. (R)"
cap label var VIR032 "Corvinone Veronese (R)"
cap label var VIR032A "Corvinone N. (R)"
cap label var VIR033 "Cot (R)"
cap label var VIR033A "Cot N (R)"
cap label var VIR033B "Kot/Cot (R)"
cap label var VIR033C "Malbec (R)"
cap label var VIR034 "Croatina (R)"
cap label var VIR035 "Dolcetto (R)"
cap label var VIR035A "Dolcetto N. (R)"
cap label var VIR036 "Dornfelder (R)"
cap label var VIR036A "Dornfelder (R)"
cap label var VIR036B "Dornfelder (R)"
cap label var VIR037 "Duras (R)"
cap label var VIR037A "Duras N (R)"
cap label var VIR038 "Fer (R)"
cap label var VIR038A "Fer N (R)"
cap label var VIR039 "Feteasca neagra (R)"
cap label var VIR039A "Feteasca neagra (R)"
cap label var VIR040 "Forcallat Tinta (R)"
cap label var VIR040A "Forcallat Tinta (R)"
cap label var VIR041 "Frappato di vittoria (R)"
cap label var VIR041A "Frappato N. (R)"
cap label var VIR042 "Freisa (R)"
cap label var VIR042A "Freisa N. (R)"
cap label var VIR043 "Gaglioppo (R)"
cap label var VIR043A "Gaglioppo N. (R)"
cap label var VIR044 "Gamay noir (R)"
cap label var VIR044A "Gamay N (R)"
cap label var VIR044B "Gamay N. (R)"
cap label var VIR045 "Garnacha Peluda (R)"
cap label var VIR045A "Garnacha Peluda (R)"
cap label var VIR046 "Garnacha Tinta (R)"
cap label var VIR046A "Cannonau (R)"
cap label var VIR046B "Garnacha (R)"
cap label var VIR046C "Grenache (R)"
cap label var VIR046D "Tocai rosso N. (R)"
cap label var VIR046E "Alicante (R)"
cap label var VIR046F "Grenache Rouge N (R)"
cap label var VIR046G "Garnacha Tinta (R)"
cap label var VIR047 "Graciano (R)"
cap label var VIR047A "Tinta Miúda (R)"
cap label var VIR048 "Gran negro (R)"
cap label var VIR049 "Grand noir (R)"
cap label var VIR049A "Grand Noir (R)"
cap label var VIR050 "Greco nero (R)"
cap label var VIR050A "Greco nero N. (R)"
cap label var VIR051 "Grignolino (R)"
cap label var VIR051A "Grignolino N. (R)"
cap label var VIR052 "Grolleau noir (R)"
cap label var VIR052A "Grolleau N (R)"
cap label var VIR053 "Mouraton (R)"
cap label var VIR053A "Juan García (R)"
cap label var VIR053B "Tinta gorda (R)"
cap label var VIR054 "Jurancon noir (R)"
cap label var VIR054A "Jurançon noir N (R)"
cap label var VIR055 "Kadarka kek (R)"
cap label var VIR055A "Gamza (R)"
cap label var VIR055B "Kadarka (R)"
cap label var VIR056 "Kotsifali (R)"
cap label var VIR056A "Kotsifali N (R)"
cap label var VIR057 "Lagrein (R)"
cap label var VIR057A "Lagrein N. (R)"
cap label var VIR058 "Lambrusco a foglia frastagliata (R)"
cap label var VIR058A "Lambrusco a foglia frastagliata N. (R)"
cap label var VIR059 "Lambrusco di Sorbara (R)"
cap label var VIR059A "Lambrusco di Sorbara N. (R)"
cap label var VIR060 "Lambrusco Grasparossa (R)"
cap label var VIR060A "Lambrusco grasparossa N. (R)"
cap label var VIR061 "Lambrusco Maestri (R)"
cap label var VIR061A "Lambrusco Maestri N. (R)"
cap label var VIR062 "Lambrusco Marani (R)"
cap label var VIR062A "Lambrusco Marani N. (R)"
cap label var VIR063 "Lambrusco Salamino (R)"
cap label var VIR063A "Lambrusco salamino N. (R)"
cap label var VIR064 "Liatiko (R)"
cap label var VIR064A "Liatiko N (R)"
cap label var VIR065 "Listán Prieto (R)"
cap label var VIR065A "Listán Negro (R)"
cap label var VIR066 "Magliocco canino (R)"
cap label var VIR066A "Magliocco canino N."
cap label var VIR067 "Malvasia nera lunga (R)"
cap label var VIR067A "Malvasia nera lunga N. (R)"
cap label var VIR068 "Malvasia nera di Brindisi (R)"
cap label var VIR068A "Malvasia nera di Brindisi/Malvasia nera di Lecce N."
cap label var VIR069 "Malvasia Preta (R)"
cap label var VIR069A "Malvasia Preta"
cap label var VIR070 "Mandilaria (R)"
cap label var VIR070A "Mandilaria N"
cap label var VIR071 "Marselan (R)"
cap label var VIR071A "Marselan N (R)"
cap label var VIR071B "Marselan (R)"
cap label var VIR072 "Marufo (R)"
cap label var VIR072A "Mourisco Roxo (R)"
cap label var VIR073 "Marzemino (R)"
cap label var VIR073A "Marzemino N."
cap label var VIR074 "Kypreiko (R)"
cap label var VIR074A "Mavro (R)"
cap label var VIR075 "Mavroudi (R)"
cap label var VIR075A "Mavroudi N"
cap label var VIR076 "Mavrud (R)"
cap label var VIR076A "Mavrud"
cap label var VIR077 "Mazuela (R)"
cap label var VIR078 "Mencía (R)"
cap label var VIR078A "Jaen (R)"
cap label var VIR078B "Mencía (R)"
cap label var VIR079 "Merlot noir (R)"
cap label var VIR079A "Merlot (R)"
cap label var VIR079B "Merlot (R)"
cap label var VIR079C "Merlot (R)"
cap label var VIR079D "Merlot N (R)"
cap label var VIR079E "Merlot (R)"
cap label var VIR079F "Merlot N. (R)"
cap label var VIR079G "Merlot noir (R)"
cap label var VIR079H "Merlot (R)"
cap label var VIR079I "Merlot (R)"
cap label var VIR079J "Merlot (R)"
cap label var VIR079K "Merlot N (R)"
cap label var VIR079L "Merlot (R)"
cap label var VIR080 "Pinot Meunier (R)"
cap label var VIR080A "Meunier (R)"
cap label var VIR080B "Mullerrebe (R)"
cap label var VIR080C "Schwarzriesling (R)"
cap label var VIR080D "Meunier N. (R)"
cap label var VIR081 "Miguel del arco (R)"
cap label var VIR082 "Molinara (R)"
cap label var VIR082A "Molinara N. (R)"
cap label var VIR083 "Mollar cano (R)"
cap label var VIR083A "Mollar (R)"
cap label var VIR083B "Negramoll (R)"
cap label var VIR083C "Negra Mole (R)"
cap label var VIR084 "Monastrell (R)"
cap label var VIR084A "Mourvèdre N (R)"
cap label var VIR084B "Mataro (R)"
cap label var VIR085 "Monica nera (R)"
cap label var VIR085A "Monica N. (R)"
cap label var VIR086 "Montepulciano (R)"
cap label var VIR086A "Montepulciano/Pugnitello N. (R)"
cap label var VIR087 "Moravia Agria (R)"
cap label var VIR087A "Moravia Agria (R)"
cap label var VIR088 "Moravia Dulce (R)"
cap label var VIR088A "Moravia Dulce (R)"
cap label var VIR089 "Moreto (R)"
cap label var VIR089A "Moreto (R)"
cap label var VIR090 "Moristel (R)"
cap label var VIR091 "Mourisco de semente (R)"
cap label var VIR091A "Mourisco de semente (R)"
cap label var VIR092 "Moschato mavro (R)"
cap label var VIR092A "Moschomavro N (R)"
cap label var VIR093 "Muscat Hamburg (R)"
cap label var VIR093A "Muscat Hamborg (R)"
cap label var VIR093B "Moschato Amvourgou N (R)"
cap label var VIR093C "Muskat Trollinger (R)"
cap label var VIR094 "Nebbiolo (R)"
cap label var VIR094A "Nebbiolo (R)"
cap label var VIR094B "Nebbiolo N. (R)"
cap label var VIR095 "Negrette (R)"
cap label var VIR095A "Négrette N (R)"
cap label var VIR096 "Negro amaro (R)"
cap label var VIR096A "Negro amaro N. (R)"
cap label var VIR097 "Nerello Cappuccio (R)"
cap label var VIR097A "Nerello cappuccio N. (R)"
cap label var VIR098 "Nerello Mascalese (R)"
cap label var VIR098A "Nerello mascalese N. (R)"
cap label var VIR099 "Pamid (R)"
cap label var VIR099A "Pamid (R)"
cap label var VIR099B "Pamidi (O)"
cap label var VIR099C "Rosioara (R)"
cap label var VIR100 "Verdot petit (R)"
cap label var VIR0100A "Petit Verdot N. (R)"
cap label var VIR0100B "Peti Verdo/Petit Verdot (R)"
cap label var VIR0100C "Petit Verdot (R)"
cap label var VIR0100D "Petit Verdot (R)"
cap label var VIR101 "Piedirosso (R)"
cap label var VIR0101A "Piedirosso N. (R)"
cap label var VIR102 "Pinot noir (R)"
cap label var VIR102A "Pinot noir N (R)"
cap label var VIR102B "Blauer Burgunder (R)"
cap label var VIR102C "Blauer Spätburgunder (R)"
cap label var VIR102D "Pinot noir (R)"
cap label var VIR102E "Rulandské modré (R)"
cap label var VIR102F "Rulandské modré (R)"
cap label var VIR102G "Pinot noir N (R)"
cap label var VIR102H "Pinot nero N. (R)"
cap label var VIR102I "Pinot crni (R)"
cap label var VIR102J "Pinot noir (R)"
cap label var VIR102K "Pinot Noar/Pinot Nero/Pinot Noir/Blaw Shpet Burgunder (R)"
cap label var VIR102L "Pinot noir (R)"
cap label var VIR102M "Pinot Noir (R)"
cap label var VIR103 "Plantet (R)"
cap label var VIR103A "Plantet N (R)"
cap label var VIR104 "Plavac mali crni (R)"
cap label var VIR104A "Plavac mali (R)"
cap label var VIR105 "Plavina crna (R)"
cap label var VIR105A "Plavina (R)"
cap label var VIR106 "Portugieser Blau (R)"
cap label var VIR106A "Kékoportó (R)"
cap label var VIR106B "Modry Portugal (R)"
cap label var VIR106C "Oporto (R)"
cap label var VIR106D "Portoghese (R)"
cap label var VIR106E "Blauer Portugieser (R)"
cap label var VIR106F "Modrý Portugal"
cap label var VIR106G "Blauer Portugieser (R)"
cap label var VIR107 "Prieto picudo tinto (R)"
cap label var VIR107A "Prieto Picudo (R)"
cap label var VIR108 "Primitivo (R)"
cap label var VIR108A "Primitivo N. (R)"
cap label var VIR109 "Raboso Piave (R)"
cap label var VIR109A "Raboso Piave N."
cap label var VIR110 "Refosco dal peduncolo rosso (R)"
cap label var VIR110A "Refosco dal peduncolo rosso N. (R)"
cap label var VIR110B "Refosco N (R)"
cap label var VIR111 "Refosco Nostrano (R)"
cap label var VIR111A "Refosk (R)"
cap label var VIR111B "Refosco nostrano N. (R)"
cap label var VIR112 "Regent (R)"
cap label var VIR112A "Regent (R)"
cap label var VIR113 "Rojal Tinta (R)"
cap label var VIR113A "Rojal Tinta (R)"
cap label var VIR114 "Romeiko (R)"
cap label var VIR114A "Romeiko N (R)"
cap label var VIR114B "Tsardana (R)"
cap label var VIR115 "Rondinella (R)"
cap label var VIR115A "Rondinella N. (R)"
cap label var VIR116 "Rosioara (R)"
cap label var VIR117 "Royal (R)"
cap label var VIR118 "Rufete (R)"
cap label var VIR118A "Rufete (R)"
cap label var VIR119 "Sagrantino (R)"
cap label var VIR119A "Sagrantino N. (R)"
cap label var VIR120 "Saint Laurent (R)"
cap label var VIR120A "Svatovavrinecké (R)"
cap label var VIR120B "Svätovavrinecké (R)"
cap label var VIR120C "St. Laurent (R)"
cap label var VIR120D "Sankt Laurent (R)"
cap label var VIR121 "Sangiovese (R)"
cap label var VIR121A "Nielluccio N (R)"
cap label var VIR121B "Sangiovese/Prugnolo gentile N. (R)"
cap label var VIR122 "Santarena (R)"
cap label var VIR122A "Santareno (R)"
cap label var VIR123 "Schiava lombarda (R)"
cap label var VIR123A "Schiava (R)"
cap label var VIR124 "Schiava gentile (R)"
cap label var VIR124A "Schiava gentile N. (R)"
cap label var VIR125 "Schiava grossa (R)"
cap label var VIR125A "Blauer Trollinger (R)"
cap label var VIR126 "Sciaccarello (R)"
cap label var VIR126A "Sciaccarello N (R)"
cap label var VIR127 "Shiroka melnishka loza (R)"
cap label var VIR127A "Shiroka melnishka loza (R)"
cap label var VIR128 "Souson (R)"
cap label var VIR129 "Storgoziya (R)"
cap label var VIR129A "Storgozia (R)"
cap label var VIR130 "Syrah (R)"
cap label var VIR130A "Shiraz (R)"
cap label var VIR130B "Syrah N. (R)"
cap label var VIR130C "Syrah (R)"
cap label var VIR130D "Syrah (R)"
cap label var VIR130E "Syrah (R)"
cap label var VIR130F "Syrah N (R)"
cap label var VIR130G "Syrah N (R)"
cap label var VIR130H "Sira/Syrah (R)"
cap label var VIR130I "Syrah (R)"
cap label var VIR130J "Syrah (R)"
cap label var VIR130K "Syrah (R)"
cap label var VIR130L "Syrah (R)"
cap label var VIR131 "Sirah (R)"
cap label var VIR132 "Tannat (R)"
cap label var VIR132A "Tannat N (R)"
cap label var VIR132B "Tannat N. (R)"
cap label var VIR132C "Tannat (R)"
cap label var VIR133 "Tempranillo tinto (R)"
cap label var VIR133A "Aragonez (R)"
cap label var VIR133B "Tinta Roriz (R)"
cap label var VIR133C "Tinto de toro (R)"
cap label var VIR133D "Tempranillo (R)"
cap label var VIR133E "Tempranillo N (R)"
cap label var VIR134 "Teroldego (R)"
cap label var VIR134A "Teroldego N. (R)"
cap label var VIR135 "Tinta (R)"
cap label var VIR136 "Tinta Barroca (R)"
cap label var VIR136A "Tinta Barroca (R)"
cap label var VIR137 "Tinta Carvalha (R)"
cap label var VIR137A "Tinta Carvalha (R)"
cap label var VIR138 "Molar (R)"
cap label var VIR138A "Tinta Negra (R)"
cap label var VIR139 "Tinto de la Pámpana Blanca (R)"
cap label var VIR139A "Tinto de la Pámpana Blanca (R)"
cap label var VIR140 "Tinto Velasco (R)"
cap label var VIR140A "Tinto Velasco (R)"
cap label var VIR141 "Touriga Franca (R)"
cap label var VIR141A "Touriga Franca (R)"
cap label var VIR142 "Touriga Nacional (R)"
cap label var VIR142A "Touriga Nacional (R)"
cap label var VIR143 "Trepat (R)"
cap label var VIR144 "Trincadeira (R)"
cap label var VIR144A "Tinta Amarela (R)"
cap label var VIR144B "Trincadeira (R)"
cap label var VIR145 "Uva di Troia (R)"
cap label var VIR145A "Uva di Troia N. (R)"
cap label var VIR146 "Uva Longanesi (R)"
cap label var VIR146A "Uva Longanesi N. (R)"
cap label var VIR147 "Villard noir (R)"
cap label var VIR147A "Villard noir N (R)"
cap label var VIR148 "Vinhão (R)"
cap label var VIR148A "Vinhao (R)"
cap label var VIR148B "Sousón (R)"
cap label var VIR149 "Vranac (R)"
cap label var VIR149A "Vranac (R)"
cap label var VIR150 "Xynomavro (R)"
cap label var VIR150A "Xinomavro N (R)"
cap label var VIR151 "Kavcina crna (R)"
cap label var VIR151A "Žametovka (R)"
cap label var VIR152 "Zweigeltrebe Blau (R)"
cap label var VIR152A "Rotburger (R)"
cap label var VIR152B "Zweigelt (R)"
cap label var VIR152C "Blauer Zweigelt (R)"
cap label var VIR152D "Zweigeltrebe (R)"
cap label var VIR152E "Zweigeltrebe (R)"
cap label var VIR152F "Zweigelt (R)"
cap label var VIR153 "Abrusco (R)"
cap label var VIR153A "Colorino N. (R)"
cap label var VIR154 "Fokiano (R)"
cap label var VIR154A "Fokiano N (R)"
cap label var VIR155 "Mavrodaphni (R)"
cap label var VIR155A "Mavrodafni N (R)"
cap label var VIR156 "Abouriou (R)"
cap label var VIR156A "Abouriou N (R)"
cap label var VIR157 "Acolon (R)"
cap label var VIR157A "Acolon (R)"
cap label var VIR158 "Agronómica (R)"
cap label var VIR158A "Agronómica (R)"
cap label var VIR159 "Egiodola (R)"
cap label var VIR159A "Egiodola N (R)"
cap label var VIR160 "André (R)"
cap label var VIR160A "André (R)"
cap label var VIR160B "André (R)"
cap label var VIR161 "Arinarnoa (R)"
cap label var VIR161A "Arinarnoa N"
cap label var VIR162 "Artaban (R)"
cap label var VIR162A "Artaban (R)"
cap label var VIR163 "Babić (R)"
cap label var VIR163A "Babić (R)"
cap label var VIR164 "Pinot Precoce Noir (R)"
cap label var VIR164A "Blauer Frühburgunder (R)"
cap label var VIR165 "Wildbacher Blau (R)"
cap label var VIR165A "Blauer Wildbacher (R)"
cap label var VIR166 "Buket (R)"
cap label var VIR166A "Buket (R)"
cap label var VIR167 "Cabernet Dorsa (R)"
cap label var VIR167A "Cabernet Dorsa (R)"
cap label var VIR168 "Cabernet Mitos (R)"
cap label var VIR168A "Cabernet Mitos (R)"
cap label var VIR169 "Cabernet Moravia (R)"
cap label var VIR169A "Cabernet Moravia (R)"
cap label var VIR170 "Cabinda (R)"
cap label var VIR170A "Cabinda (R)"
cap label var VIR171 "Callet (R)"
cap label var VIR171A "Callet (R)"
cap label var VIR172 "Camarate Tinto (R)"
cap label var VIR172A "Camarate (R)"
cap label var VIR173 "Casculho (R)"
cap label var VIR173A "Casculho (R)"
cap label var VIR174 "Chambourcin (R)"
cap label var VIR174A "Chambourcin N (R)"
cap label var VIR175 "Chenanson (R)"
cap label var VIR175A "Chenanson N (R)"
cap label var VIR176 "Cornifesto (R)"
cap label var VIR176A "Cornifesto (R)"
cap label var VIR177 "Counoise (R)"
cap label var VIR177A "Counoise N (R)"
cap label var VIR178 "Domina (R)"
cap label var VIR178A "Domina (R)"
cap label var VIR179 "Dunaj (R)"
cap label var VIR179A "Dunaj (O)"
cap label var VIR180 "Dunkelfelder (R)"
cap label var VIR180A "Dunkelfelder (R)"
cap label var VIR181 "Espadeiro Tinto (R)"
cap label var VIR181A "Espadeiro Tinto (R)"
cap label var VIR181B "Espadeiro (R)"
cap label var VIR182 "Izabella Nador (R)"
cap label var VIR182A "Izabella Nador (R)"
cap label var VIR183 "Kotsifoliatiko (R)"
cap label var VIR183A "Kotsifoliatiko N (R)"
cap label var VIR184 "Krassato (R)"
cap label var VIR184A "Krasato N (R)"
cap label var VIR185 "Limnio (R)"
cap label var VIR185A "Limnio (R)"
cap label var VIR186 "Lledoner pelut mutant glabre (R)"
cap label var VIR186A "Lledoner pelut mutant glabre (R)"
cap label var VIR187 "Maratheftiko (R)"
cap label var VIR187A "Maratheftiko (R)"
cap label var VIR188 "Vidoc (R)"
cap label var VIR188A "Vidoc (R)"
cap label var VIR189 "Medina (R)"
cap label var VIR189A "Medina (R)"
cap label var VIR190 "Mondeuse Noire (R)"
cap label var VIR190A "Mondeuse N (R)"
cap label var VIR191 "Nero (R)"
cap label var VIR191A "Nero (R)"
cap label var VIR192 "Padeiro (R)"
cap label var VIR192A "Padeiro (R)"
cap label var VIR193 "Pineau d’aunis (R)"
cap label var VIR193A "Pineau d’aunis (R)"
cap label var VIR194 "Poulsard Noir (R)"
cap label var VIR194A "Poulsard N (R)"
cap label var VIR195 "Preto Martinho (R)"
cap label var VIR195A "Preto Martinho (R)"
cap label var VIR196 "Roesler (R)"
cap label var VIR196A "Roesler (R)"
cap label var VIR197 "Rubin (R)"
cap label var VIR197A "Rubin (R)"
cap label var VIR198 "Skylopnichtis (R)"
cap label var VIR198A "Skylopnichtis N (R)"
cap label var VIR199 "Sumoll (R)"
cap label var VIR199A "Sumoll Tinto (R)"
cap label var VIR200 "Terrano (R)"
cap label var VIR200A "Teran (R)"
cap label var VIR201 "Tibouren (R)"
cap label var VIR201A "Tibouren (R)"
cap label var VIR202 "Barca (R)"
cap label var VIR202A "Barca (R)"
cap label var VIR203 "Tinta Francisca (R)"
cap label var VIR203A "Tinta Francisca (R)"
cap label var VIR204 "Tinto Cão (R)"
cap label var VIR204A "Tinto Cão (R)"
cap label var VIR205 "Tinto Sem Nome (R)"
cap label var VIR205A "Tinto Sem Nome (R)"
cap label var VIR206 "Turán (R)"
cap label var VIR206A "Turán (R)"
cap label var VIR207 "Vertzami (R)"
cap label var VIR207A "Vertzami (R)"
cap label var VIR208 "Avgoustiatis (R)"
cap label var VIR208A "Avgoustiatis N (R)"
cap label var VIR209 "Castanal (R)"
cap label var VIR209A "Mourisco (R)"
cap label var VIR210 "Mourisco de trevoes (R)"
cap label var VIR210A "Mourisco de trevoes (R)"
cap label var VIR211 "Parraleta (R)"
cap label var VIR211A "Tinta Caiada (R)"
cap label var VIR212 "Morrastel Bouchet (R)"
cap label var VIR212A "Gran Negro (R)"
cap label var VIR213 "Morisca (R)"
cap label var VIR213A "Morisca (R)"
cap label var VIR214 "Odesskii Chernyi (R)"
cap label var VIR214A "Alibernet (R)"
cap label var VIR215 "Ranna melnishka loza (R)"
cap label var VIR215A "Melnik 55 (R)"
cap label var VIR216 "Sevka (R)"
cap label var VIR216A "Sevka (R)"
cap label var VIR217 "Skopelitikon (R)"
cap label var VIR217A "Skopelitiko N (R)"
cap label var VIR218 "Prokupac (R)"
cap label var VIRM_OTH "Other main red grape varieties (R)"
cap label var VIRMM_TOT "Other main red mixed grape varieties (R)"
cap label var VIWM_TOT "Total main white grape varieties (W)"
cap label var VIW001 "Airén (W)"
cap label var VIW001A "Airén (W)"
cap label var VIW002 "Alarije (W)"
cap label var VIW003 "Albana Bianca (W)"
cap label var VIW003A "Albana B. (W)"
cap label var VIW004 "Albillo Mayor (W)"
cap label var VIW004A "Albillo Mayor (W)"
cap label var VIW004B "Turruntes (W)"
cap label var VIW005 "Albillo Real (W)"
cap label var VIW005A "Albillo Real (W)"
cap label var VIW006 "Planta Fina (W)"
cap label var VIW006A "Alicante Branco (W)"
cap label var VIW006B "Planta Fina de Predalba (W)"
cap label var VIW007 "Aligote (W)"
cap label var VIW007A "Aligoté B (W)"
cap label var VIW007B "Aligote (W)"
cap label var VIW007C "Aligoté (W)"
cap label var VIW008 "Alvarinho (W)"
cap label var VIW008A "Albariño (W)"
cap label var VIW008B "Alvarinho (W)"
cap label var VIW009 "Ansonica (W)"
cap label var VIW009A "Ansonica B. (W)"
cap label var VIW010 "Antão Vaz (W)"
cap label var VIW010A "Antão Vaz (W)"
cap label var VIW011 "Arinto (W)"
cap label var VIW011A "Arinto (W)"
cap label var VIW011B "Pedernã (W)"
cap label var VIW012 "Arneis (W)"
cap label var VIW012A "Arneis B. (W)"
cap label var VIW013 "Assyrtiko (W)"
cap label var VIW013A "Assyrtiko B (W)"
cap label var VIW014 "Athiri Lefko (Kotinis) (W)"
cap label var VIW014A "Athiri (W)"
cap label var VIW015 "Auxerrois (W)"
cap label var VIW015A "Auxerrois B (W)"
cap label var VIW015B "Auxerrois (W)"
cap label var VIW015C "Auxerrois B (W)"
cap label var VIW016 "Avesso (W)"
cap label var VIW016A "Avesso (W)"
cap label var VIW017 "Azal branco (W)"
cap label var VIW017A "Azal (W)"
cap label var VIW018 "Bacchus weiss (W)"
cap label var VIW018A "Bacchus (W)"
cap label var VIW019 "Baco blanc (W)"
cap label var VIW019A "Baco blanc B (W)"
cap label var VIW020 "Beba (W)"
cap label var VIW021 "Bellone (W)"
cap label var VIW021A "Bellone B. (W)"
cap label var VIW022 "Bianca (W)"
cap label var VIW022A "Bianca (W)"
cap label var VIW023 "Biancame (W)"
cap label var VIW024 "Bical (W)"
cap label var VIW024A "Bical (W)"
cap label var VIW025 "Bombino bianco (W)"
cap label var VIW025A "Bombino bianco B. (W)"
cap label var VIW025B "Trebbiano abruzzese (W)"
cap label var VIW025C "Debit (W)"
cap label var VIW026 "Borba (W)"
cap label var VIW026A "Borba (W)"
cap label var VIW027 "Bourboulenc (W)"
cap label var VIW028 "Calagrano (W)"
cap label var VIW029 "Carignan blanc (W)"
cap label var VIW029A "Carinena blanco (W)"
cap label var VIW029B "Carignan blanc B (W)"
cap label var VIW030 "Catarratto bianco comune (W)"
cap label var VIW030A "Catarratto bianco comune/Catarratto bianco lucido B. (W)"
cap label var VIW031 "Catarratto bianco lucido (W)"
cap label var VIW031A "Cataratto lucido (W)"
cap label var VIW032 "Cayetana Blanca (W)"
cap label var VIW032A "Cayetana Blanca (W)"
cap label var VIW033 "Chardonnay blanc (W)"
cap label var VIW033A "Chardonnay (W)"
cap label var VIW033B "Feinburgunder (W)"
cap label var VIW033C "Morillon (W)"
cap label var VIW033D "Sardone (W)"
cap label var VIW033E "Chardonnay B (W)"
cap label var VIW033F "Chardonnay (W)"
cap label var VIW033G "Chardonnay B (W)"
cap label var VIW033H "Chardonnay (W)"
cap label var VIW033I "Chardonnay (W)"
cap label var VIW033J "Chardonnay (W)"
cap label var VIW033K "Chardonnay B. (W)"
cap label var VIW033L "Chardonnay (W)"
cap label var VIW033M "Chardoney/Pino shardone/Chardonnay Blanc (W)"
cap label var VIW033N "Chardonnay (W)"
cap label var VIW033O "Chardonnay (W)"
cap label var VIW033P "Chardonnay (W)"
cap label var VIW034 "Chasan (W)"
cap label var VIW034A "Chasan B (W)"
cap label var VIW035 "Chasselas blanc (W)"
cap label var VIW035A "Chasselas (W)"
cap label var VIW035B "Weisser Gutedel (W)"
cap label var VIW035C "Chasselas B (W)"
cap label var VIW036 "Chenin blanc (W)"
cap label var VIW036A "Chenin B (W)"
cap label var VIW037 "Clairette blanche (W)"
cap label var VIW037A "Clairette B (W)"
cap label var VIW038 "Cococciola (W)"
cap label var VIW038A "Cococciola B. (W)"
cap label var VIW039 "Coda di volpe bianca (W)"
cap label var VIW039A "Coda di volpe bianca (W)"
cap label var VIW040 "Códega do Larinho (W)"
cap label var VIW040A "Côdega de Larinho (W)"
cap label var VIW041 "Colombard (W)"
cap label var VIW041A "Colombard B (W)"
cap label var VIW042 "Cortese (W)"
cap label var VIW042A "Cortese B. (W)"
cap label var VIW043 "Crimpoșie selectionata (W)"
cap label var VIW043A "Crâmpoșie selectionata (W)"
cap label var VIW044 "Cserszegi fuszeres (W)"
cap label var VIW044A "Cserszegi fuszeres (W)"
cap label var VIW045 "Diagalves faux (W)"
cap label var VIW046 "Dimyat (W)"
cap label var VIW046A "Dimjat (W)"
cap label var VIW047 "Elbling Weiss (W)"
cap label var VIW047A "Weisser Elbling (W)"
cap label var VIW048 "Ezerfuertue (W)"
cap label var VIW049 "Ezerjo (W)"
cap label var VIW049A "Ezerjó (W)"
cap label var VIW050 "Falanghina flegrea (W)"
cap label var VIW050A "Falanghina B. (W)"
cap label var VIW051 "Fernão Pires (W)"
cap label var VIW051A "Fernão Pires (W)"
cap label var VIW052 "Feteasca alba (W)"
cap label var VIW052A "Dievcie hrozno (W)"
cap label var VIW052B "Leányka (W)"
cap label var VIW052C "Feteasca alba (W)"
cap label var VIW053 "Feteasca regala (W)"
cap label var VIW053A "Kiralyleanyka (W)"
cap label var VIW053B "Feteasca regala (W)"
cap label var VIW053C "Feteasca regala (W)"
cap label var VIW054 "Fiano (W)"
cap label var VIW054A "Fiano B. (W)"
cap label var VIW055 "Folle blanche (W)"
cap label var VIW055A "Folle blanche B (W)"
cap label var VIW056 "Francuse (W)"
cap label var VIW056A "Francusa (W)"
cap label var VIW057 "Friulano (W)"
cap label var VIW057A "Tocai friulano B. (W)"
cap label var VIW058 "Furmint (W)"
cap label var VIW058A "Moslavac (W)"
cap label var VIW058B "Kéknyela (W)"
cap label var VIW058C "Furmint (W)"
cap label var VIW059 "Galbena de Odobesti (W)"
cap label var VIW059A "Galbena de Odobesti (W)"
cap label var VIW060 "Garganega (W)"
cap label var VIW060A "Garganega/Grecanico dorato B. (W)"
cap label var VIW061 "Garnacha Blanca (W)"
cap label var VIW061A "Grenache blanc B (W)"
cap label var VIW061B "Garnacha Blanca (W)"
cap label var VIW062 "Glera lunga (W)"
cap label var VIW062A "Prosecco lungo (W)"
cap label var VIW063 "Gouveio (W)"
cap label var VIW063A "Godello (W)"
cap label var VIW063B "Gouveio (W)"
cap label var VIW064 "Gouveio Real (W)"
cap label var VIW064A "Gouveio Real (W)"
cap label var VIW065 "Grasa de Cotnari (W)"
cap label var VIW065A "Grasa de Cotnari (W)"
cap label var VIW066 "Grecanico dorato (W)"
cap label var VIW067 "Guardavalle (W)"
cap label var VIW067A "Guardavalle B. (W)"
cap label var VIW068 "Greco bianco 2 (W)"
cap label var VIW068A "Greco bianco 2 (W)"
cap label var VIW069 "Grillo (W)"
cap label var VIW069A "Grillo B. (W)"
cap label var VIW070 "Harslevelue (W)"
cap label var VIW070A "Harslevelue (W)"
cap label var VIW071 "Huxelrebe (W)"
cap label var VIW071A "Huxelrebe (W)"
cap label var VIW072 "Iordan (W)"
cap label var VIW072A "Iordana (W)"
cap label var VIW073 "Irsai Oliver (W)"
cap label var VIW073A "Irsai Oliver (W)"
cap label var VIW073B "Irsai Oliver (W)"
cap label var VIW073C "Irsai Oliver (W)"
cap label var VIW074 "Izsaki sarfeher"
cap label var VIW074A "Arany sarfeher"
cap label var VIW075 "Jacquere (W)"
cap label var VIW075A "Jacquère B (W)"
cap label var VIW076 "Kerner (W)"
cap label var VIW076A "Kerner (W)"
cap label var VIW077 "Koevidinka (W)"
cap label var VIW077A "Kövidinka (W)"
cap label var VIW078 "Kunleany (W)"
cap label var VIW078A "Kunleány (W)"
cap label var VIW079 "Lakhegyi mezes (W)"
cap label var VIW080 "Len de l'El (W)"
cap label var VIW080A "Len de L'El B (W)"
cap label var VIW081 "Loureiro blanco (W)"
cap label var VIW081A "Loureiro (W)"
cap label var VIW081B "Loureira (W)"
cap label var VIW082 "Malvasia (W)"
cap label var VIW082A "Malvasia (W)"
cap label var VIW083 "Malvasia bianca (W)"
cap label var VIW083A "Malvasia bianca B (W)"
cap label var VIW084 "Malvasia bianca di Candia (W)"
cap label var VIW084A "Malvasia bianca di Candia (W)"
cap label var VIW085 "Malvasia bianca lunga (W)"
cap label var VIW085A "Malvasia bianca lunga B. (W)"
cap label var VIW085C "Pavlos (W)"
cap label var VIW086 "Malvasia Branca de São Jorge (W)"
cap label var VIW086A "Malvasia Branca de São Jorge (W)"
cap label var VIW087 "Malvasia del Lazio (W)"
cap label var VIW087A "Malvasia del Lazio B. (W)"
cap label var VIW088 "Malvasia di Candia aromatica (W)"
cap label var VIW088A "Malvasia di Candia aromatica B (W)"
cap label var VIW089 "Malvasia Fina (W)"
cap label var VIW089A "Malvasia Fina (W)"
cap label var VIW090 "Malvasia Istriana (W)"
cap label var VIW090A "Malvazija (W)"
cap label var VIW090B "Malvazija Istarska (W)"
cap label var VIW090C "Malvasia istriana B. (W)"
cap label var VIW091 "Manseng gros blanc (W)"
cap label var VIW091A "Gros Manseng B (W)"
cap label var VIW092 "Manseng petit blanc (W)"
cap label var VIW092A "Petit Manseng (W)"
cap label var VIW092B "Petit Manseng B. (W)"
cap label var VIW093 "Manto Negro (W)"
cap label var VIW093A "Chelva (W)"
cap label var VIW093B "Mantua (W)"
cap label var VIW093C "Montua (W)"
cap label var VIW093D "Manto Negro (W)"
cap label var VIW094 "Marsanne (W)"
cap label var VIW094A "Marsanne B (W)"
cap label var VIW095 "Mauzac blanc (W)"
cap label var VIW095A "Mauzac B (W)"
cap label var VIW096 "Melon (W)"
cap label var VIW096A "Melon B (W)"
cap label var VIW097 "Merseguera (W)"
cap label var VIW097A "Messeguera (W)"
cap label var VIW098 "Misket cherven (W)"
cap label var VIW098A "Misket cherven (W)"
cap label var VIW099 "Monemvassia (W)"
cap label var VIW099A "Monemvassia B (W)"
cap label var VIW100 "Moscato giallo (W)"
cap label var VIW100A "Moscato giallo B. (W)"
cap label var VIW100B "Moscato giallo (W)"
cap label var VIW101 "Muller Thurgau Weiss (W)"
cap label var VIW101A "Müller - Thurgau (W)"
cap label var VIW101B "Riesling x Sylvaner (W)"
cap label var VIW101C "Rivaner B (W)"
cap label var VIW101D "Rizlingszilváni (W)"
cap label var VIW101E "Müller-Thurgau B (W)"
cap label var VIW101F "Müller Thurgau (W)"
cap label var VIW101G "Muller Thurgau B. (W)"
cap label var VIW101H "Müller Thurgau (W)"
cap label var VIW101I "Müller-Thurgau (W)"
cap label var VIW102 "Muscadelle (W)"
cap label var VIW102A "Muscadelle B (W)"
cap label var VIW103 "Muscat a petits grains blancs (W)"
cap label var VIW103A "Moscatel de Grano Menudo (W)"
cap label var VIW103B "Moscatel Galego Branco (W)"
cap label var VIW103C "Moscato bianco B. (W)"
cap label var VIW103D "Moschato aspro (W)"
cap label var VIW103E "Muscat à Petits Grains (W)"
cap label var VIW103F "Muskateller (Gelber) (W)"
cap label var VIW103G "Sárga muskotály (W)"
cap label var VIW103H "Tamaioasa romaneasca (W)"
cap label var VIW103I "Muškat (W)"
cap label var VIW103J "Rumeni muškat (W)"
cap label var VIW103K "Muscat à petits grains blancs B (W)"
cap label var VIW103L "Muskat Peti Gran / Tamianka (W)"
cap label var VIW103M "Gelber Muskateller (W)"
cap label var VIW103N "Muškát žltý (W)"
cap label var VIW104 "Muscat of Alexandria (W)"
cap label var VIW104A "Moscatel de Alejandría (W)"
cap label var VIW104B "Moscatel de Malaga (W)"
cap label var VIW104C "Moscatel Graúdo (W)"
cap label var VIW104D "Moscatel-de-Setúbal (W)"
cap label var VIW104E "Muscat d'Alexandrie B (W)"
cap label var VIW104F "Zibibbo (W)"
cap label var VIW104G "Moschato Alexandrias B (W)"
cap label var VIW104H "Müscat of Alexandria (W)"
cap label var VIW105 "Muscat Ottonel (W)"
cap label var VIW105A "Otthonel muskotaly (W)"
cap label var VIW105B "Muskat-Ottonel (W)"
cap label var VIW105C "Muskat ottonel (W)"
cap label var VIW105D "Muscat ottonel (W)"
cap label var VIW105E "Muscat Ottonel (W)"
cap label var VIW106 "Mustoasa de Maderat (W)"
cap label var VIW106A "Mustoasa de Maderat (W)"
cap label var VIW107 "Neuburger (W)"
cap label var VIW107A "Neuburské (W)"
cap label var VIW107B "Neuburger (W)"
cap label var VIW108 "Nuragus (W)"
cap label var VIW108A "Nuragus B. (W)"
cap label var VIW109 "Courbu blanc (W)"
cap label var VIW109A "Hondarrabi Zuri (W)"
cap label var VIW110 "Ortega (W)"
cap label var VIW110A "Ortega (W)"
cap label var VIW111 "Ortrugo (W)"
cap label var VIW111A "Ortrugo B. (W)"
cap label var VIW112 "Palomino fino (W)"
cap label var VIW112A "Listán Blanco de Canarias/Palomino Fino (W)"
cap label var VIW112B "Malvasia rei (W)"
cap label var VIW112C "Listan B (W)"
cap label var VIW113 "Palomino superior (W)"
cap label var VIW114 "Pardillo (W)"
cap label var VIW114A "Marisancho (W)"
cap label var VIW114B "Verdoncho (W)"
cap label var VIW115 "Pardina (W)"
cap label var VIW116 "Parellada (W)"
cap label var VIW117 "Korinthiaki lefki (W)"
cap label var VIW117A "Passerina (W)"
cap label var VIW118 "Pecorino (W)"
cap label var VIW118A "Pecorino (W)"
cap label var VIW119 "Pedro Ximénez (W)"
cap label var VIW119A "Pedro Ximénez (W)"
cap label var VIW120 "Perruno (W)"
cap label var VIW121 "Grechetto bianco (W)"
cap label var VIW121A "Grechetto/Pignoletto B. (W)"
cap label var VIW122 "Pinot blanc (W)"
cap label var VIW122A "Beli pinot (W)"
cap label var VIW122B "Weisser Burgunder (W)"
cap label var VIW122C "Klevner (W)"
cap label var VIW122D "Pinot Blanc B (W)"
cap label var VIW122E "Rulandské biele (W)"
cap label var VIW122F "Rulandske bile (W)"
cap label var VIW122G "Weisser Burgunder (W)"
cap label var VIW122H "Pinot blanc (W)"
cap label var VIW122I "Pinot Bianco (W)"
cap label var VIW122J "Pinot bijeli (W)"
cap label var VIW122K "Pinot Blanc B (W)"
cap label var VIW123 "Piquepoul blanc (W)"
cap label var VIW123A "Piquepoul blanc B (W)"
cap label var VIW124 "Planta Nova (W)"
cap label var VIW124A "Planta Nova (W)"
cap label var VIW125 "Rabigato (W)"
cap label var VIW125A "Rabigato (W)"
cap label var VIW126 "Rabo de Ovelha (W)"
cap label var VIW126A "Rabo de Ovelha (W)"
cap label var VIW127 "Ribolla gialla (W)"
cap label var VIW127A "Rebula (W)"
cap label var VIW127B "Ribolla gialla B. (W)"
cap label var VIW128 "Riesling Weiss (W)"
cap label var VIW128A "Rajnai rizling (W)"
cap label var VIW128B "Rajnski rizling (W)"
cap label var VIW128C "Renski rizling (W)"
cap label var VIW128D "Riesling/Riesling Weiss (W)"
cap label var VIW128E "Riesling B (W)"
cap label var VIW128F "Weisser Riesling (W)"
cap label var VIW128G "Rizling rýnsky (W)"
cap label var VIW128H "Ryzlink rynsky (W)"
cap label var VIW128I "Riesling de Rhin (W)"
cap label var VIW128J "Weisser Riesling (W)"
cap label var VIW128K "Riesling B (W)"
cap label var VIW128L "Riesling renano B. (W)"
cap label var VIW129 "Rkatsiteli (W)"
cap label var VIW129A "Rkatzitelli/Rkatsiteli (W)"
cap label var VIW129B "Rkatsiteli (W)"
cap label var VIW130 "Robola (W)"
cap label var VIW130A "Robola B (W)"
cap label var VIW131 "Roussanne (W)"
cap label var VIW131A "Roussanne B (W)"
cap label var VIW132 "Sarba (W)"
cap label var VIW132A "Sarba (W)"
cap label var VIW133 "Sauvignon Blanc (W)"
cap label var VIW133A "Muskat-Sylvaner (W)"
cap label var VIW133B "Zeleni sauvignon (W)"
cap label var VIW133C "Sauvignon blanc (W)"
cap label var VIW133D "Sauvignon B (W)"
cap label var VIW133E "Sauvignon (W)"
cap label var VIW133F "Sauvignon (W)"
cap label var VIW133G "Sauvignon B. (W)"
cap label var VIW133H "Sauvignon gros (W)"
cap label var VIW133I "Sauvignon petit (W)"
cap label var VIW133J "Sauvignon Blanc (W)"
cap label var VIW133K "Sauvignon Blanc (W)"
cap label var VIW133L "Sauvignon bijeli (W)"
cap label var VIW133M "Sauvignon Blanc (W)"
cap label var VIW133N "Sovignion blanc/Sauvignon Blanc (W)"
cap label var VIW133O "Sauvignon blanc B (W)"
cap label var VIW133P "Sauvignon (W)"
cap label var VIW134 "Savagnin blanc (W)"
cap label var VIW135 "Savvatiano (W)"
cap label var VIW135A "Savvatiano B (W)"
cap label var VIW136 "Scheurebe (W)"
cap label var VIW136A "Scheurebe (W)"
cap label var VIW136B "Scheurebe (W)"
cap label var VIW137 "Seara Nova (W)"
cap label var VIW137A "Seara Nova (W)"
cap label var VIW138 "Semillon (W)"
cap label var VIW138A "Semillon B (W)"
cap label var VIW138B "Semillon (W)"
cap label var VIW139 "Silvaner grün (W)"
cap label var VIW139A "Grüner Silvaner (W)"
cap label var VIW139B "Sylvaner B (W)"
cap label var VIW139C "Sylvanské zelené"
cap label var VIW139D "Silvánske zelené"
cap label var VIW139E "Silvanac Zeleni"
cap label var VIW140 "Síria (W)"
cap label var VIW140A "Síria (W)"
cap label var VIW140B "Dona Blanca (W)"
cap label var VIW140C "Crato Espanhol (W)"
cap label var VIW140D "Doña Blanca (W)"
cap label var VIW141 "Sultanina (W)"
cap label var VIW141A "Soultanina (W)"
cap label var VIW142 "Terret blanc (W)"
cap label var VIW142A "Terret blanc B (W)"
cap label var VIW143 "Torrontes (W)"
cap label var VIW144 "Tortosina (W)"
cap label var VIW145 "Trajadura (W)"
cap label var VIW145A "Trajadura (W)"
cap label var VIW146 "Trebbiano abruzzese (W)"
cap label var VIW147 "Trebbiano giallo (W)"
cap label var VIW147A "Trebbiano giallo B. (W)"
cap label var VIW148 "Trebbiano romagnolo (W)"
cap label var VIW148A "Trebbiano romagnolo B. (W)"
cap label var VIW149 "Trebbiano toscano (W)"
cap label var VIW149A "Ugni blanc B (W)"
cap label var VIW149B "Biancame/Trebbiano toscano B."
cap label var VIW149C "Yuni blan/Ugni blanc"
cap label var VIW149D "Ugni blanc B"
cap label var VIW150 "Veltliner Frührot (W)"
cap label var VIW150A "Frühroter Veltliner (W)"
cap label var VIW150B "Malvasier (W)"
cap label var VIW150C "Veltlínské červené rané (O)"
cap label var VIW150D "Veltlínske červené skoré (W)"
cap label var VIW151 "Veltliner Grün (W)"
cap label var VIW151A "Veltliner (W)"
cap label var VIW151B "Grüner Veltliner (W)"
cap label var VIW151C "Veltlinske zelene (W)"
cap label var VIW151D "Weissgipfler (W)"
cap label var VIW151E "Zöld velteíini (W)"
cap label var VIW151F "Veltlínske zelené (W)"
cap label var VIW152 "Verdeca (W)"
cap label var VIW153 "Verdejo Blanco (W)"
cap label var VIW153A "Verdejo (W)"
cap label var VIW154 "Verdicchio bianco (W)"
cap label var VIW154A "Trebbiano di Soave/Verdicchio bianco B. (W)"
cap label var VIW154B "Verdicchio bianco (W)"
cap label var VIW155 "Verduzzo friulano (W)"
cap label var VIW155A "Verduzzo friulano B. (W)"
cap label var VIW156 "Verduzzo trevigiano (W)"
cap label var VIW156A "Verduzzo trevigiano B. (W)"
cap label var VIW157 "Vermentino (W)"
cap label var VIW157A "Vermentino B (W)"
cap label var VIW157B "Favorita/Pigato/Vermentino B. (W)"
cap label var VIW158 "Vernaccia di San Gimignano (W)"
cap label var VIW158A "Vernaccia di S. Gimignano/Bervedino B. (W)"
cap label var VIW159 "Vilana (W)"
cap label var VIW159A "Vilana B (W)"
cap label var VIW160 "Viognier (W)"
cap label var VIW160A "Viogner (W)"
cap label var VIW160B "Viogner B (W)"
cap label var VIW160C "Viogner B. (W)"
cap label var VIW160D "Viogner (W)"
cap label var VIW161 "Viosinho (W)"
cap label var VIW161B "Viosinho (W)"
cap label var VIW162 "Vital (W)"
cap label var VIW162B "Vital (W)"
cap label var VIW163 "Viura (W)"
cap label var VIW163A "Macabeo (W)"
cap label var VIW163B "Macabeu B (W)"
cap label var VIW164 "Welschriesling (W)"
cap label var VIW164A "Graševina (W)"
cap label var VIW164B "Laski rizling (W)"
cap label var VIW164C "Olasz rizling (W)"
cap label var VIW164D "Riesling italico B. (W)"
cap label var VIW164E "Risling vlašský (W)"
cap label var VIW164F "Rizling vlassky (W)"
cap label var VIW164G "Ryzlink vlassky (W)"
cap label var VIW162H "Welschriesling (W)"
cap label var VIW162I "Italian riesling (W)"
cap label var VIW162J "Riesling italian"
cap label var VIW165 "Xarello (W)"
cap label var VIW165A "Xarello blanco (W)"
cap label var VIW166 "Xynisteri (W)"
cap label var VIW166A "Xinisteri (W)"
cap label var VIW167 "Zala gyoengye (W)"
cap label var VIW167A "Zalagyöngye (W)"
cap label var VIW168 "Zalema (W)"
cap label var VIW169 "Zenit (W)"
cap label var VIW169A "Zenit (W)"
cap label var VIW170 "Aletta (W)"
cap label var VIW170A "Aletta (Ecs.18.) (W)"
cap label var VIW171 "Asproudes (W)"
cap label var VIW171A "Asproudes B (W)"
cap label var VIW172 "Glera (W)"
cap label var VIW172A "Prosecco B. (W)"
cap label var VIW173 "Malagouzia (W)"
cap label var VIW173A "Malagousia B (W)"
cap label var VIW174 "Manzoni bianco (W)"
cap label var VIW174A "Manzoni bianco (W)"
cap label var VIW175 "Razaki (W)"
cap label var VIW176 "Skiadopoulo (W)"
cap label var VIW176A "Skiadopoulo B"
cap label var VIW176B "Zakynthino B"
cap label var VIW177 "Tempranillo Blanco (W)"
cap label var VIW177A "Tempranillo Blanco (W)"
cap label var VIW178 "Pálava (W)"
cap label var VIW178A "Palava (O)"
cap label var VIW178B "Pálava (W)"
cap label var VIW179 "Aidani Aspro (W)"
cap label var VIW179A "Aidani Aspro B (W)"
cap label var VIW180 "Albarín Blanco (W)"
cap label var VIW180A "Albarín Blanco / Blanco Lexitimo (W)"
cap label var VIW181 "Petrokoritho Lefko (W)"
cap label var VIW181A "Petrokoritho Lefko B (W)"
cap label var VIW182 "Altesse (W)"
cap label var VIW182A "Altesse B (W)"
cap label var VIW183 "Goustolidi (W)"
cap label var VIW183A "Goustolidi B (W)"
cap label var VIW184 "Biancu gentile (W)"
cap label var VIW184A "Biancu Gentile B (W)"
cap label var VIW186 "Bouvier (W)"
cap label var VIW186A "Bouvier (W)"
cap label var VIW187 "Cabernet Blanc (W)"
cap label var VIW187A "Cabernet Blanc (W)"
cap label var VIW188 "Caíño Blanco (W)"
cap label var VIW188A "Caíño Blanco (W)"
cap label var VIW189 "Carrega Branco (W)"
cap label var VIW189A "Carrega Branco (W)"
cap label var VIW190 "Cerceal Branco (W)"
cap label var VIW190A "Cerceal Branco (W)"
cap label var VIW191 "Cercial (W)"
cap label var VIW191A "Cercial (W)"
cap label var VIW192 "Harslevelue (W)"
cap label var VIW192A "Lipovina (W)"
cap label var VIW193 "Danlas (W)"
cap label var VIW193A "Danlas B (W)"
cap label var VIW194 "Debina (W)"
cap label var VIW194A "Debina B (W)"
cap label var VIW196 "Devín (W)"
cap label var VIW196A "Devín (W)"
cap label var VIW197 "Encruzado (W)"
cap label var VIW197A "Encruzado (W)"
cap label var VIW198 "Faberrebe (W)"
cap label var VIW198A "Faberrebe (W)"
cap label var VIW199 "Folgasão (W)"
cap label var VIW199A "Folgasão (W)"
cap label var VIW201 "Folha de Figueira (W)"
cap label var VIW201A "Folha de Figueira (W)"
cap label var VIW202 "Hibernal (W)"
cap label var VIW202A "Hibernal (W)"
cap label var VIW203 "Johanniter (W)"
cap label var VIW203A "Johanniter (W)"
cap label var VIW204 "Juhfark (W)"
cap label var VIW204A "Juhfark (W)"
cap label var VIW205 "Kakotriguis (W)"
cap label var VIW205A "Kakotriguis (W)"
cap label var VIW206 "Kujundzusa Bela (W)"
cap label var VIW206A "Kujundžuša (W)"
cap label var VIW207 "Malvar (W)"
cap label var VIW207A "Malvar (W)"
cap label var VIW208 "Malvasia Dubrovacka (W)"
cap label var VIW208A "Malvasía Aromática (W)"
cap label var VIW209 "Malvasía Volcánica (W)"
cap label var VIW209A "Malvasía Volcánica (W)"
cap label var VIW210 "Manteúdo (W)"
cap label var VIW210A "Manteúdo (W)"
cap label var VIW085B "Maraština (W)"
cap label var VIW211 "Morio Muskat (W)"
cap label var VIW211A "Morio Muskat (W)"
cap label var VIW212 "Misket Varnenski (W)"
cap label var VIW212A "Varnenski misket (W)"
cap label var VIW213 "Pensal Blanca (W)"
cap label var VIW213A "Moll (W)"
cap label var VIW214 "Muscaris (W)"
cap label var VIW214A "Muscaris (W)"
cap label var VIW214B "Muscaris (W)"
cap label var VIW215 "Mopr (W)"
cap label var VIW215A "Muškát moravský (W)"
cap label var VIW215B "Muškát moravský (W)"
cap label var VIW216 "Opsimos Edessis (W)"
cap label var VIW216A "Opsimo Edessis (W)"
cap label var VIW217 "Arbois blanc (W)"
cap label var VIW217A "Orbois (W)"
cap label var VIW218 "Palomino de Jerez(W)"
cap label var VIW218A "Palomino (W)"
cap label var VIW219 "Perrum branco (W)"
cap label var VIW219A "Perrum (W)"
cap label var VIW220 "Courbu Petit (W)"
cap label var VIW220A "Petit Courbu (W)"
cap label var VIW221 "Plăvaie (W)"
cap label var VIW221A "Plăvaie (W)"
cap label var VIW222 "Pošip bijeli (W)"
cap label var VIW222A "Pošip bijeli (W)"
cap label var VIW223 "Potamissi aspro (W)"
cap label var VIW223A "Potamisi B (W)"
cap label var VIW224 "Ranfol Beli (W)"
cap label var VIW224A "Ranfol (W)"
cap label var VIW225 "Rome (W)"
cap label var VIW225A "Rome (W)"
cap label var VIW226 "Rotgipfler (W)"
cap label var VIW226A "Rotgipfler (W)"
cap label var VIW227 "Roupeiro Branco (W)"
cap label var VIW227A "Roupeiro Branco (W)"
cap label var VIW228 "Solaris (W)"
cap label var VIW228A "Solaris (W)"
cap label var VIW228B "Solaris (W)"
cap label var VIW229 "Soreli (W)"
cap label var VIW229A "Soreli (W)"
cap label var VIW230 "Tamarez (W)"
cap label var VIW230A "Tamarez (W)"
cap label var VIW231 "Thrapsathiri B (W)"
cap label var VIW231A "Thrapsathiri (W)"
cap label var VIW232 "Tortosí (W)"
cap label var VIW232A "Tortosí (W)"
cap label var VIW233 "Trbljan (W)"
cap label var VIW233A "Trbljan (W)"
cap label var VIW234 "Verdelho branco (W)"
cap label var VIW234A "Verdelho (W)"
cap label var VIW235 "Vidiano (W)"
cap label var VIW235A "Vidiano B (W)"
cap label var VIW236 "Vijariego Blanco (W)"
cap label var VIW236A "Vijariego Blanco (W)"
cap label var VIW237 "Villard blanc (W)"
cap label var VIW237A "Villard blanc (W)"
cap label var VIW237B "Villard blanc (W)"
cap label var VIW238 "Zengő (W)"
cap label var VIW238A "Zengő (W)"
cap label var VIW239 "Zéta (W)"
cap label var VIW239A "Zéta (W)"
cap label var VIW240 "Žlahtina (W)"
cap label var VIW240A "Žlahtina (W)"
cap label var VIW241 "Avgoulato (W)"
cap label var VIW241A "Rozaki Aspro (W)"
cap label var VIW242 "Poeloeske muskotaly (W)"
cap label var VIW242A "Pölöskei muskotály (W)"
cap label var VIW243 "Tsvetochnyi (W)"
cap label var VIW243A "Blütenmuskateller (W)"
cap label var VIW244 "Montua (W)"
cap label var VIW244A "Diagalves faux (W)"
cap label var VIW244B "Montúa (W)"
cap label var VIW245 "Lagorthi (W)"
cap label var VIW245A "Verdeca/Pampanuto B. (W)"
cap label var VIW246 "Sauvignac (W)"
cap label var VIW246A "Sauvignac (W)"
cap label var VIW247 "Sauvitage (W)"
cap label var VIW247A "Sauvitage (W)"
cap label var VIW248 "Pecsi Szagos (W)"
cap label var VIW248A "Misket vrashanski (W)"
cap label var VIW249 "Zupljanka (W)"
cap label var VIWM_OTH "Other main white grape varieties(W)"
cap label var VIWMM_OTH "Other main white mixed grape varieties (W)"
cap label var VIOM_TOT "Total main other different colour grape varieties (O)"
cap label var VIO001 "Babeasca gris (O)"
cap label var VIO001A "Babeasca gri (O)"
cap label var VIO002 "Garnacha Roja (O)"
cap label var VIO002A "Grenache gris G (O)"
cap label var VIO002B "Grenas rose (O)"
cap label var VIO002C "Garnacha Roja (O)"
cap label var VIO003 "Gewürztraminer (O)"
cap label var VIO003A "Tramin cerveny (O)"
cap label var VIO003B "Traminer aromatico (O)"
cap label var VIO003C "Traminer roz (O)"
cap label var VIO003D "Tramini (O)"
cap label var VIO003E "Gewürztraminer (W)"
cap label var VIO003F "Tramin cerveny (W)"
cap label var VIO003G "Tramin cerveny (W)"
cap label var VIO003H "Traminer (W)"
cap label var VIO003I "Gewürztraminer (W)"
cap label var VIO003K "Gewürztraminer Rs. (O)"
cap label var VIO003L "Roter Traminer (O)"
cap label var VIO003M "Traminac (O)"
cap label var VIO004 "Moschofilero (O)"
cap label var VIO004A "Moschofilero Rs (O)"
cap label var VIO005 "Muscat a petits grains rouges (O)"
cap label var VIO005A "Busuioaca de Bohotin (O)"
cap label var VIO006 "Pinot gris (O)"
cap label var VIO006A "Ruländer/Grauburgunder (O)"
cap label var VIO006B "Pinot grigio (O)"
cap label var VIO006C "Rulander (O)"
cap label var VIO006D "Rulandske sede (O)"
cap label var VIO006E "Sivi pinot (O)"
cap label var VIO006F "Szurkebarat (O)"
cap label var VIO006G "Burgundac sivi (O)"
cap label var VIO006H "Pinot sivi (O)"
cap label var VIO006I "Pinot gris (W)"
cap label var VIO006J "Grauer Burgunder (W)"
cap label var VIO006K "Pinot gris G (O)"
cap label var VIO006L "Pino Gri / Pinot gris (O)"
cap label var VIO006M "Pinot gris (O)"
cap label var VIO007 "Roditis (O)"
cap label var VIO007A "Roditis Rs (O)"
cap label var VIO008 "Sauvignon gris (O)"
cap label var VIO008A "Sauvignon gris (O)"
cap label var VIO009 "Fileri Kokkino (O)"
cap label var VIO009A "Fileri (O)"
cap label var VIO010 "Generosa (O)"
cap label var VIO010A "Generosa (W)"
cap label var VIO011 "Grolleau gris (O)"
cap label var VIO011A "Grolleau gris G (O)"
cap label var VIO013 "Clairette rosé (O)"
cap label var VIO013A "Clairette rosé (O)"
cap label var VIO014 "Giró Ros (O)"
cap label var VIO014A "Giró Ros (O)"
cap label var VIO015 "Gouveio Roxo (O)"
cap label var VIO015A "Gouveio Roxo (O)"
cap label var VIO016 "Portugieser Rot (O)"
cap label var VIO016A "Kraljevina (O)"
cap label var VIO017 "Roter Veltliner (O)"
cap label var VIO017A "Roter Veltliner (W)"
cap label var VIO018 "Souvignier gris (O)"
cap label var VIO018A "Souvignier gris (W)"
cap label var VIO018B "Souvignier gris (W)"
cap label var VIOM_OTH "Other main different colour grape varieties (O)"
cap label var VIOMM_OTH "Other mixed main grape varieties of other colours (O)"
cap label var VIUNKM_TOT "Total main grape varieties without specified colour"
