cap label var CODE "Label - English"
cap label var UNE "Unemployment"
cap label var SICK "Sickness"
cap label var WRK_ACC "Work-related accident"
cap label var CYBSECU_IT "Cybersecurity or IT"
cap label var NRGSUP "Energy supply"
cap label var SUPCH "Supply chain (other than energy supply)"
cap label var ACS_MKT_NEU "Access markets outside the EU"
cap label var NTL_PHENOM "Natural phenomena (natural disasters, extreme drought or flooding etc.)"
cap label var OP_FIN_BSN_OTH "Other operational and financial business risks (related to finance, personnel, prices, exchange rates, legal or regulatory risks etc.)"
cap label var HDEP_LTD_SUPPL "High dependence on limited number of suppliers"
cap label var HDEP_LTD_SUPPL_EU "High dependence on limited number of suppliers located in the EU"
cap label var HDEP_LTD_SUPPL_NEU "High dependence on limited number of suppliers located outside the EU"
