cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var HOM "Home"
cap label var _2HOM "Second home"
cap label var WPL_SCH "Working place or school"
cap label var HOM_OTH "Other people's home"
cap label var REST "Restaurant, café or pub"
cap label var SHOP "Shopping centres, markets, other shops"
cap label var OTH "Other specified place of activity"
cap label var NSP "Unspecified place of activity"
