cap label var CODE "Label - English"
cap label var ENT "Enterprises"
cap label var SAL "Employees"
cap label var EXPN "Expenditure"
cap label var NETTUR "Net turnover"
cap label var EMP "Employed persons"
cap label var SAL14 "Employees in 2014"
cap label var TUR14 "Turnover in 2014"
cap label var TUR14_OUT "Turnover from sales outside the home country in 2014"
cap label var SAL16 "Employees in 2016"
cap label var TUR16 "Turnover in 2016"
cap label var TUR16_OUT "Turnover from sales outside the home country in 2016"
cap label var ENT16 "Enterprises in the population in 2016"
cap label var MKT_GDSERV "Market for goods and/or services"
cap label var LMKT_TUR "Largest market in terms of turnover"
