cap label var CODE "Label - English"
cap label var B1003 "Total utilised agricultural area (UAA) (ha)"
cap label var B1004 "Total irrigated agricultural land (ha)"
cap label var D1301 "Frequency of ozone peaks (Number)"
cap label var D2204 "Municipal waste per capita (Kg/inhab)"
cap label var D5101 "Total surface of the protected areas (ha)"
cap label var D5102 "Share of protected national territory (%)"
cap label var D5201 "Mammals (number)"
cap label var D5202 "Birds (number)"
cap label var D5203 "Reptiles (number)"
cap label var D5204 "Amphibians (number)"
cap label var D5205 "Fish (number)"
cap label var D5206 "Invertebrates (number)"
cap label var D5207 "Vascular plants (number)"
cap label var D5301 "Mammals (%)"
cap label var D5302 "Birds (%)"
cap label var D5303 "Reptiles (%)"
cap label var D5304 "Amphibians (%)"
cap label var D5305 "Fish (%)"
cap label var D5306 "Invertebrates (%)"
cap label var D5307 "Vascular plants (%)"
cap label var F1001 "GDP at current market prices (million euro)"
cap label var F1005 "Annual growth rate of GDP in volume (constant price) (%)"
cap label var F1007 "Final consumption expenditure, as a share of GDP (%)"
cap label var F1008 "Final consumption expenditure of households & NPISHs, as a share of GDP (%)"
cap label var F1009 "Final consumption expenditure of general government, as a share of GDP (%)"
cap label var F1010 "Gross capital formation, as a share of GDP (%)"
cap label var F1012 "Gross fixed  capital formation, as a share of GDP (%)"
cap label var F1014 "Change in stocks, as a share of GDP (%)"
cap label var F1015 "Imports of goods & services, as a share of GDP (%)"
cap label var F1016 "Exports of goods & services, as a share of GDP (%)"
cap label var F1017 "Value added of agriculture, as a share of total VA (%)"
cap label var F1018 "Value added of manufacturing, water and electricity, as a share of total VA (%)"
cap label var F1019 "Value added of construction, as a share of total VA (%)"
cap label var F1020 "Value added of services, as a share of total VA (%)"
cap label var F2009 "Total economy deficit (-) / surplus (+), as a share of GDP - total economy (ESA95 balancing item B.9) (%)"
cap label var F2001 "General government sector deficit (-) / surplus (+), as a share of GDP (%)"
cap label var F2004 "Gross external debt, as a share of GDP (%)"
cap label var F2012 "Gross public debt, as a share of GDP (%)"
cap label var I0003 "Consumer price index (2015 = 100)"
cap label var G0001 "Total area (km²)"
cap label var G1004 "Population density (Inhab / Km²)"
cap label var G2101 "Adult literacy rate, male (%)"
cap label var G2102 "Adult literacy rate, female (%)"
cap label var G2103 "Adult literacy rate, total (%)"
cap label var G2104 "Youth literacy rate, male (%)"
cap label var G2105 "Youth literacy rate, female (%)"
cap label var G2106 "Youth literacy rate, total (%)"
cap label var G2201 "Number of compulsory schooling years (year)"
cap label var G2217 "Net enrolment rate at ISCED 1, male (%)"
cap label var G2218 "Net enrolment rate at ISCED 1, female (%)"
cap label var G2219 "Net enrolment rate at ISCED 1, total (%)"
cap label var G2220 "Net enrolment rate at ISCED 2, male (%)"
cap label var G2221 "Net enrolment rate at ISCED 2, female (%)"
cap label var G2222 "Net enrolment rate at ISCED 2, total (%)"
cap label var G2223 "Gender parity index at ISCED 1 (ratio)"
cap label var G2224 "Gender parity index at ISCED 2 (ratio)"
cap label var G2209 "School completion rate at ISCED 1, male (%)"
cap label var G2210 "School completion rate at ISCED 1, female (%)"
cap label var G2211 "School completion rate at ISCED 1, total (%)"
cap label var G2B01 "Gross enrolment rate in TVET, male, ISCED 3 (%)"
cap label var G2B02 "Gross enrolment rate in TVET, female, ISCED 3 (%)"
cap label var G2B03 "Gross enrolment rate in TVET, total, ISCED 3 (%)"
cap label var G2B09 "Cost per student in TVET (national currency)"
cap label var G3111 "Poverty line, urban (national currency)"
cap label var G3112 "Poverty line, rural (national currency)"
cap label var G3101 "Poverty line, total (national currency)"
cap label var G3102 "Poverty headcount ratio, total (%)"
cap label var G3104 "Income (or expenditure) distribution: S80/S20 quintile share ratio, total (ratio)"
cap label var G3106 "Proportion of persons living in jobless households, total (%)"
cap label var G3304 "Proportion of households with sustainable access to improved sanitation, urban (%)"
cap label var G3305 "Proportion of households with sustainable access to improved sanitation, rural (%)"
cap label var G3306 "Proportion of households with sustainable access to improved sanitation, total (%)"
cap label var G3307 "Proportion of households with access to secure tenure, urban (%)"
cap label var G3308 "Proportion of households with access to secure tenure, rural (%)"
cap label var G3309 "Proportion of households with access to secure tenure, total (%)"
cap label var G3201 "Number of main telephone lines per 1,000 inhabitants (per 1000 Inhab)"
cap label var G3202 "Number of subscriptions to cellular mobile telephone services per 1,000 inhabitants (per 1000 Inhab)"
cap label var G4106 "Total employment, total, 15+ (Number)"
cap label var G4109 "Gross employment-to-population ratio, male, 15-64 (%)"
cap label var G4110 "Gross employment-to-population ratio, female, 15-64 (%)"
cap label var G4111 "Gross employment-to-population ratio, total, 15-64 (%)"
cap label var G4112 "Employment status, wage worker (%)"
cap label var G4113 "Employment status, self-employed (%)"
cap label var G4114 "Employment status, family worker (%)"
cap label var G4204 "Youth unemployment rate, male (%)"
cap label var G4205 "Youth unemployment rate, female (%)"
cap label var G4206 "Youth unemployment rate, total (%)"
cap label var G4312 "Legal minimum hourly wage (national currency)"
cap label var D1302 "Total number of gasoline fueled vehicles (number)"
cap label var D1303 "Total number of diesel powered engines (number)"
cap label var D1304 "Total number of other vehicles (number)"
cap label var D1305 "Total number of vehicles (number)"
cap label var D2504 "Percentage of total population served by municipal waste collection (%)"
cap label var D2505 "Percentage of urban population served by municipal waste collection (%)"
cap label var D2506 "Percentage of rural population served by municipal waste collection (%)"
cap label var F8003 "Government Budget as a share of GDP (%)"
cap label var F8004 "Total annual public expenditure in regular education (current and capital) as a percentage of  GDP (ISCED levels 0-1, 2, 3-4, 5-6) (%)"
cap label var F8006 "Total annual public expenditure in regular education (current and capital) as a percentage of  total Government Expenditure (ISCED levels 0-1, 2, 3-4, 5-6) (%)"
cap label var F8008 "Public investment in education as a share of GDP (%)"
cap label var G25101 "Proportion of youth (20-24 years) having attained ISCED 3 level, male (%)"
cap label var G25102 "Proportion of youth (20-24 years) having attained ISCED 3 level, female (%)"
cap label var G25103 "Proportion of youth (20-24 years) having attained ISCED 3 level, total (%)"
cap label var G25202 "Educational attainment at age 25 and above, male, ISCED 0-1 (%)"
cap label var G25203 "Educational attainment at age 25 and above, male, ISCED 2 (%)"
cap label var G25204 "Educational attainment at age 25 and above, male, ISCED 3-4 (%)"
cap label var G25205 "Educational attainment at age 25 and above, male, ISCED 5-6 (%)"
cap label var G25207 "Educational attainment at age 25 and above, female, ISCED 0-1 (%)"
cap label var G25208 "Educational attainment at age 25 and above, female, ISCED 2 (%)"
cap label var G25209 "Educational attainment at age 25 and above, female, ISCED 3-4 (%)"
cap label var G25210 "Educational attainment at age 25 and above, female, ISCED 5-6 (%)"
cap label var G25212 "Educational attainment at age 25 and above, total, ISCED 0-1 (%)"
cap label var G25213 "Educational attainment at age 25 and above, total, ISCED 2 (%)"
cap label var G25214 "Educational attainment at age 25 and above, total, ISCED 3-4 (%)"
cap label var G25215 "Educational attainment at age 25 and above, total, ISCED 5-6 (%)"
cap label var G25401 "Ratio of students enrolled in tertiary education at ISCED 5-6, male (per 100 000 Inhab)"
cap label var G25402 "Ratio of students enrolled in tertiary education at ISCED 5-6, female (per 100 000 Inhab)"
cap label var G25403 "Ratio of students enrolled in tertiary education at ISCED 5-6, total (per 100 000 Inhab)"
cap label var G25404 "Number of tertiary education (ISCED 5-6) graduates in mathematics, science and technology, male (number)"
cap label var G25405 "Number of tertiary education (ISCED 5-6) graduates in mathematics, science and technology, female (number)"
cap label var G25406 "Number of tertiary education (ISCED 5-6) graduates in mathematics, science and technology, total (number)"
cap label var G25605 "Public expenditure on education as % of total government spending (%)"
cap label var G2B10 "Gross enrolment rate in TVET, male, ISCED 4 (%)"
cap label var G2B11 "Gross enrolment rate in TVET, female, ISCED 4 (%)"
cap label var G2B12 "Gross enrolment rate in TVET, total, ISCED 4 (%)"
cap label var G2B13 "Share of TVET graduates in the overall graduates at ISCED 3 and above, male (%)"
cap label var G2B14 "Share of TVET graduates in the overall graduates at ISCED 3 and above, female (%)"
cap label var G2B15 "Share of TVET graduates in the overall graduates at ISCED 3 and above, total (%)"
cap label var G31A1 "Extreme poverty line, urban (national currency)"
cap label var G31A2 "Extreme poverty line, rural (national currency)"
cap label var G31A3 "Extreme poverty line, total (national currency)"
cap label var G31B11 "At-risk-of poverty rate, male, urban (%)"
cap label var G31B111 "At-risk-of poverty rate, male, urban, 0-17 (%)"
cap label var G31B112 "At-risk-of poverty rate, male, urban,18-64 (%)"
cap label var G31B113 "At-risk-of poverty rate, male, urban, 65+ (%)"
cap label var G31B12 "At-risk-of poverty rate, male, rural (%)"
cap label var G31B121 "At-risk-of poverty rate, male, rural, 0-17 (%)"
cap label var G31B122 "At-risk-of poverty rate, male, rural,18-64 (%)"
cap label var G31B123 "At-risk-of poverty rate, male, rural, 65+ (%)"
cap label var G31B13 "At-risk-of poverty rate, male, total (%)"
cap label var G31B131 "At-risk-of poverty rate, male, total, 0-17 (%)"
cap label var G31B132 "At-risk-of poverty rate, male, total,18-64 (%)"
cap label var G31B133 "At-risk-of poverty rate, male, total, 65+ (%)"
cap label var G31B21 "At-risk-of poverty rate, female, urban (%)"
cap label var G31B211 "At-risk-of poverty rate, female, urban, 0-17 (%)"
cap label var G31B212 "At-risk-of poverty rate, female, urban, 18-64 (%)"
cap label var G31B213 "At-risk-of poverty rate, female, urban, 65+ (%)"
cap label var G31B22 "At-risk-of poverty rate, female, rural (%)"
cap label var G31B221 "At-risk-of poverty rate, female, rural, 0-17 (%)"
cap label var G31B222 "At-risk-of poverty rate, female, rural, 18-64 (%)"
cap label var G31B223 "At-risk-of poverty rate, female, rural, 65+ (%)"
cap label var G31B23 "At-risk-of poverty rate, female, total (%)"
cap label var G31B231 "At-risk-of poverty rate, female, total, 0-17 (%)"
cap label var G31B232 "At-risk-of poverty rate, female, total, 18-64 (%)"
cap label var G31B233 "At-risk-of poverty rate, female, total, 65+ (%)"
cap label var G31B31 "At-risk-of poverty rate, total, urban (%)"
cap label var G31B311 "At-risk-of poverty rate, total, urban, 0-17 (%)"
cap label var G31B312 "At-risk-of poverty rate, total, urban, 18-64 (%)"
cap label var G31B313 "At-risk-of poverty rate, total, urban, 65+ (%)"
cap label var G31B32 "At-risk-of poverty rate, total, rural (%)"
cap label var G31B321 "At-risk-of poverty rate, total, rural, 0-17 (%)"
cap label var G31B322 "At-risk-of poverty rate, total, rural, 18-64 (%)"
cap label var G31B323 "At-risk-of poverty rate, total, rural, 65+ (%)"
cap label var G31B33 "At-risk-of poverty rate, total (%)"
cap label var G31B331 "At-risk-of poverty rate, total, 0-17 (%)"
cap label var G31B332 "At-risk-of poverty rate, total, 18-64 (%)"
cap label var G31B333 "At-risk-of poverty rate, total, 65+ (%)"
cap label var G41A03 "Total employment, total, 15-64 (number)"
cap label var G41B06 "Net economic activity rate, male, 15-64 (%)"
cap label var G41B09 "Net economic activity rate, female, 15-64 (%)"
cap label var G41B12 "Net economic activity rate, total, 15-64 (%)"
cap label var G41D02 "Employment status, worker in a cooperative (%)"
cap label var G42B01 "Unemployment rate by education level, male, Illiterate (%)"
cap label var G42B02 "Unemployment rate by education level, male, ISCED 0-1 (%)"
cap label var G42B03 "Unemployment rate by education level, male, ISCED 2 (%)"
cap label var G42B04 "Unemployment rate by education level, male, ISCED 3-4 (%)"
cap label var G42B05 "Unemployment rate by education level, male, ISCED 5-6 (%)"
cap label var G42B06 "Unemployment rate by education level, female, Illiterate (%)"
cap label var G42B07 "Unemployment rate by education level, female, ISCED 0-1 (%)"
cap label var G42B08 "Unemployment rate by education level, female, ISCED 2 (%)"
cap label var G42B09 "Unemployment rate by education level, female, ISCED 3-4 (%)"
cap label var G42B10 "Unemployment rate by education level, female, ISCED 5-6 (%)"
cap label var G42B11 "Unemployment rate by education level, total, Illiterate (%)"
cap label var G42B12 "Unemployment rate by education level, total, ISCED 0-1 (%)"
cap label var G42B13 "Unemployment rate by education level, total, ISCED 2 (%)"
cap label var G42B14 "Unemployment rate by education level, total, ISCED 3-4 (%)"
cap label var G42B15 "Unemployment rate by education level, total, ISCED 5-6 (%)"
cap label var G42C01 "Proportion of persons living in jobless households, male, 0-17 (%)"
cap label var G42C02 "Proportion of persons living in jobless households, male, 18-64 (%)"
cap label var G42C03 "Proportion of persons living in jobless households, male, total (%)"
cap label var G42C04 "Proportion of persons living in jobless households, female, 0-17 (%)"
cap label var G42C05 "Proportion of persons living in jobless households, female, 18-64 (%)"
cap label var G42C06 "Proportion of persons living in jobless households, female, total (%)"
cap label var G42C07 "Proportion of persons living in jobless households, total, 0-17 (%)"
cap label var G42C08 "Proportion of persons living in jobless households, total, 18-64 (%)"
cap label var G4314 "Nominal wage index, ( A+B ) (index)"
cap label var G4315 "Nominal wage index, ( C ) (index)"
cap label var G4316 "Nominal wage index, ( D+E ) (index)"
cap label var G4317 "Nominal wage index, ( F ) (index)"
cap label var G4318 "Nominal wage index, ( G ) (index)"
cap label var G4319 "Nominal wage index, ( I ) (ondex)"
cap label var G4320 "Nominal wage index, ( H+J+K ) (index)"
cap label var G4321 "Nominal wage index, ( L+M+N+O ) (index)"
cap label var G4322 "Proportion of employees earning less than 50% of the median salary, male (%)"
cap label var G4323 "Proportion of employees earning less than 50% of the median salary, female (%)"
cap label var G4324 "Proportion of employees earning less than 50% of the median salary, total (%)"
