cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var STOP_WRK "Stopped working"
cap label var STOP_WRK_NRENT "Stopped working and did not re-enter the labour market"
cap label var CN_WRK_RENT "Continued working or re-entered the labour market"
cap label var CN_WRK_NCHG "Continued working without changes"
cap label var CN_WRK_WCHG "Continued working with changes"
cap label var NWRK "Not working (for any reason)"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
