cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var TERNAT_REG "Traffic performed on the national territory by vehicles registered in the reporting country or in foreign countries"
cap label var TERNAT_REGNAT "Traffic performed on the national territory by vehicles registered in the reporting country"
cap label var TERNAT_REGFOR "Traffic performed on the national territory by vehicles registered in foreign countries"
cap label var TERFOR_REGNAT "Traffic performed on the foreign territory by vehicles registered in the reporting country"
cap label var TER_REGNAT "Traffic performed on the national or foreign territory by vehicles registered in the reporting country"
cap label var A000 "Total"
cap label var D001 "Motor vehicle movements on national territory (irrespective of registration country)"
cap label var D002 "Motor vehicle movements on national territory (registered in the reporting country"
cap label var D003 "Motor vehicle movements on national territory (registered in foreign countries)"
cap label var D004 "Motor vehicle movements on foreign territory (registered in the reporting country)"
cap label var D005 "Motor vehicle movements on national and foreign territory (registered in the reporting country)"
