cap label var ST_SO_HEAP "Manure solid storage in heaps"
cap label var ST_COMP "Manure stored in compost piles"
cap label var ST_PIT "Manure stored in pits below animal confinement"
cap label var ST_DPLT "Manure stored in deep litter systems"
cap label var ST_LQ_SL_NC "Liquid manure/slurry storage without cover"
cap label var ST_LQ_SL_PC "Liquid manure/slurry storage with permeable cover"
cap label var ST_LQ_SL_IC "Liquid manure/slurry storage with impermeable cover"
cap label var ST_OF "Manure stored in other facilities n.e.c."
