cap label var EXPQNT "Exports quantity"
cap label var EXPVAL "Exports value"
cap label var IMPQNT "Imports quantity"
cap label var IMPVAL "Imports value"
cap label var OWNPRODVAL "Production on own account value"
cap label var OWNVALFLAG "Production on own account value flag"
cap label var OWNVALBASE "Production on own account value rounding base"
cap label var OWNPRODQNT "Production on own account quantity"
cap label var OWNQNTFLAG "Production on own account quantity flag"
cap label var OWNQNTBASE "Production on own account quantity rounding base"
cap label var PQNTBASE "Sold production quantity rounding base"
cap label var PQNTFLAG "Sold production quantity flag"
cap label var PRODQNT "Sold production quantity"
cap label var PRODVAL "Sold production value"
cap label var PVALBASE "Sold production value rounding base"
cap label var PVALFLAG "Sold production value flag"
cap label var QNTUNIT "Quantity unit"
cap label var QUANTITY_100KG "QUANTITY_100KG"
cap label var QUANTITY_IN_100KG "QUANTITY_IN_100KG"
cap label var QUANTITY_IN_KG "QUANTITY_IN_KG"
cap label var QUANTITY_IN_SUPPL_UNIT "QUANTITY_IN_SUPPL_UNIT"
cap label var QUANTITY_IN_TONS "QUANTITY_IN_TONS"
cap label var QUANTITY_TON "QUANTITY_TON"
cap label var QUANTITY_TONS "QUANTITY_TONS"
cap label var SCPRODQNT "Sub-contracted production quantity"
cap label var SCPRODVAL "Sub-contracted production value"
cap label var SCQNTBASE "Sub-contracted production quantity rounding base"
cap label var SCQNTFLAG "Sub-contracted production quantity flag"
cap label var SCVALBASE "Sub-contracted production value rounding base"
cap label var SCVALFLAG "Sub-contracted production value flag"
cap label var SUPPLEMENTARY_QUANTITY "SUPPLEMENTARY_QUANTITY"
cap label var SUPPL_QUANTITY "SUPPL_QUANTITY"
cap label var SUPPL_UNIT "SUPPL_UNIT"
cap label var SUP_QUANTITY "SUP_QUANTITY"
cap label var VALUE_1000EURO "VALUE_1000EURO"
cap label var VALUE_IN_EUR "VALUE_IN_EUR"
cap label var VALUE_IN_EUROS "VALUE_IN_EUROS"
cap label var VALUE_IN_NAC "VALUE_IN_NAC"



