cap label var TOTAL "Total"
cap label var IMG "Native and foreign born immigrants (first and second generation of immigrants)"
cap label var NBO "Native-born"
cap label var NBO_NAT_IMG "Native born with native background and native and foreign born immigrants (first and second generation of immigrants)"
cap label var NBO_NAT "Native-born with native background"
cap label var NBO_IMG "Native-born with mixed background and foreign background (second generation of immigrants)"
cap label var NBO_IMGMIX "Native-born with mixed background (second generation of immigrants)"
cap label var NBO_IMGFOR "Native-born with foreign background (second generation of immigrants)"
cap label var FBO "Foreign-born (first generation of immigrants)"
cap label var NRP "No response"
cap label var OTH "Other"
cap label var UNK "Unknown"
