cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var COIL "Crude oil"
cap label var ROIL "Refined oil products"
cap label var N00 "Natural energy inputs"
cap label var N01 "Fossil non-renewable natural energy inputs"
cap label var N02 "Nuclear non-renewable natural energy inputs"
cap label var N03 "Hydro based renewable natural energy inputs"
cap label var N04 "Wind based renewable natural energy inputs"
cap label var N05 "Solar based renewable natural energy inputs"
cap label var N06 "Biomass based renewable natural energy inputs"
cap label var N07 "Other renewable natural energy inputs"
cap label var P00 "Energy products"
cap label var P08 "Hard coal"
cap label var P09 "Brown coal and peat"
cap label var P10 "Derived gases (= manufactured gases excl. biogas)"
cap label var P11 "Secondary coal products (coke, coal tar, patent fuel, BKB and peat products)"
cap label var P12 "Crude oil, NGL, and other hydrocarbons (excl. bio)"
cap label var P13 "Natural gas (without bio)"
cap label var P14 "Motor spirit (without bio)"
cap label var P15 "Kerosenes and jet fuels (without bio)"
cap label var P16 "Naphtha"
cap label var P17 "Transport diesel (without bio)"
cap label var P18 "Heating and other gasoil (without bio)"
cap label var P19 "Residual fuel oil"
cap label var P20 "Refinery gas, ethane and LPG"
cap label var P21 "Other petroleum products incl. additives/oxygenates and refinery feedstocks"
cap label var P22 "Nuclear fuel"
cap label var P23 "Wood, wood waste and other solid biomass, charcoal"
cap label var P24 "Liquid biofuels"
cap label var P25 "Biogas"
cap label var P26 "Electrical energy"
cap label var P27 "Heat"
cap label var R00 "Energy residuals"
cap label var R28 "Renewable waste"
cap label var R29 "Non-renewable waste"
cap label var R30 "Energy losses all kinds of (during extraction, distribution, storage and transformation, and dissipative heat from end use)"
cap label var R31 "Energy incorporated in products for non-energy use"
cap label var SD_IO "Statistical discrepancy between input and output of all energy flows"
cap label var N00_P00_R00 "Natural energy inputs, energy products and energy residuals"
cap label var EPRD_OUSE "Energy products for own use"
