cap label var CODE "Label - English"
cap label var TOTAL "Total natural energy inputs, energy products and energy residuals"
cap label var NEI "Natural energy inputs"
cap label var NEI_NRFOSS "Fossil non-renewable natural energy inputs"
cap label var NEI_NRNUC "Nuclear non-renewable natural energy inputs"
cap label var NEI_RHYD "Hydro based renewable natural energy inputs"
cap label var NEI_RWND "Wind based renewable natural energy inputs"
cap label var NEI_RSOL "Solar based renewable natural energy inputs"
cap label var NEI_RBIOM "Biomass based renewable natural energy inputs"
cap label var NEI_ROTH "Other renewable natural energy inputs"
cap label var EPRD "Energy products"
cap label var EPRD_HCOAL "Hard coal"
cap label var EPRD_BCOAL_PEAT "Brown coal and peat"
cap label var EPRD_DGAS "Derived gases (manufactured gases excluding biogas)"
cap label var EPRD_SECCOAL "Secondary coal products (coke, coal tar, patent fuel, brown coal briquettes (BKB) and peat products)"
cap label var EPRD_HYDCXBIO "Crude oil, natural gas liquids (NGL) and other hydrocarbons (excluding bio)"
cap label var EPRD_NATGASXBIO "Natural gas (excluding bio)"
cap label var EPRD_MOTSPXBIO "Motor spirit (excluding bio)"
cap label var EPRD_KJFXBIO "Kerosenes and jet fuels (excluding bio)"
cap label var EPRD_NPH "Naphtha"
cap label var EPRD_TRADIEXBIO "Transport diesel (excluding bio)"
cap label var EPRD_HEAT_GOIL_OTHXBIO "Heating and other gasoil (excluding bio)"
cap label var EPRD_RES_OILF "Residual fuel oil"
cap label var EPRD_REFGAS_ETH_LPG "Refinery gas, ethane and liquefied petroleum gases (LPG)"
cap label var EPRD_OTH_PET "Other petroleum products including additives/oxygenates and refinery feedstocks"
cap label var EPRD_NUCF "Nuclear fuels"
cap label var EPRD_SBIOM "Wood, wood waste and other solid biomass, charcoal"
cap label var EPRD_LIQBIOF "Liquid biofuels"
cap label var EPRD_BIOGAS "Biogas"
cap label var EPRD_ELC "Electricity"
cap label var EPRD_HEAT "Heat"
cap label var EPRD_OUSE "Energy products for own use"
cap label var ERES "Energy residuals"
cap label var ERES_RW "Renewable waste"
cap label var ERES_NRW "Non-renewable waste"
cap label var ERES_LOSS "Energy losses during extraction, distribution, storage and transformation, and dissipative heat from end use"
cap label var ERES_INC "Energy incorporated in products for non-energy use"
cap label var INP_OUT_DSP "Statistical discrepancy between input and output of all energy flows"
