cap label var TOTAL "Total"
cap label var CR "Specialist crops"
cap label var FT1_SO "Specialist field crops (calculated with Standard Output)"
cap label var FT15_SO "Specialist cereals, oilseed and protein crops (calculated with Standard Output)"
cap label var FT16_SO "General field cropping (calculated with Standard Output)"
cap label var FT2_SO "Specialist horticulture (calculated with Standard Output)"
cap label var FT21_SO "Specialist horticulture indoor (calculated with Standard Output)"
cap label var FT22_SO "Specialist horticulture outdoor (calculated with Standard Output)"
cap label var FT23_SO "Other horticulture (calculated with Standard Output)"
cap label var FT3_SO "Specialist permanent crops (calculated with Standard Output)"
cap label var FT35_SO "Specialist vineyards (calculated with Standard Output)"
cap label var FT36_SO "Specialist fruit and citrus fruit (calculated with Standard Output)"
cap label var FT37_SO "Specialist olives (calculated with Standard Output)"
cap label var FT38_SO "Various permanent crops combined (calculated with Standard Output)"
cap label var LS "Specialist livestock"
cap label var FT4_SO "Specialist grazing livestock (calculated with Standard Output)"
cap label var FT45_SO "Specialist dairying (calculated with Standard Output)"
cap label var FT46_SO "Specialist cattle-rearing and fattening (calculated with Standard Output)"
cap label var FT47_SO "Cattle-dairying, rearing and fattening combined (calculated with Standard Output)"
cap label var FT48_SO "Sheep, goats and other grazing livestock (calculated with Standard Output)"
cap label var FT5_SO "Specialist granivores (calculated with Standard Output)"
cap label var FT51_SO "Specialist pigs (calculated with Standard Output)"
cap label var FT52_SO "Specialist poultry (calculated with Standard Output)"
cap label var FT53_SO "Various granivores combined (calculated with Standard Output)"
cap label var FT6_SO "Mixed cropping (calculated with Standard Output)"
cap label var FT61_SO "Mixed cropping (calculated with Standard Output)"
cap label var OTH "Specialist - other"
cap label var FT7_SO "Mixed livestock farms (calculated with Standard Output)"
cap label var FT73_SO "Mixed livestock, mainly grazing livestock (calculated with Standard Output)"
cap label var FT74_SO "Mixed livestock, mainly granivores (calculated with Standard Output)"
cap label var FT8_SO "Mixed crops-livestock (calculated with Standard Output)"
cap label var FT83_SO "Field crops-grazing livestock combined (calculated with Standard Output)"
cap label var FT84_SO "Various crops and livestock combined (calculated with Standard Output)"
cap label var FT9_SO "Non-classified farms (calculated with Standard Output)"
cap label var FT90_SO "Non-classified farms (calculated with Standard Output)"
cap label var FT1_SGM "Specialist field crops (calculated with Standard Gross Margin)"
cap label var FT11_SGM "Specialist cereals (calculated with Standard Gross Margin)"
cap label var FT12_SGM "General field cropping (calculated with Standard Gross Margin)"
cap label var FT13_SGM "Specialist cereals, oilseed and protein crops (calculated with Standard Gross Margin)"
cap label var FT14_SGM "General field cropping (calculated with Standard Gross Margin)"
cap label var FT2_SGM "Specialist horticulture (calculated with Standard Gross Margin)"
cap label var FT20_SGM "Specialist horticulture (calculated with Standard Gross Margin)"
cap label var FT3_SGM "Specialist permanent crops (calculated with Standard Gross Margin)"
cap label var FT31_SGM "Specialist vineyards (calculated with Standard Gross Margin)"
cap label var FT32_SGM "Specialist fruit and citrus fruit (calculated with Standard Gross Margin)"
cap label var FT33_SGM "Specialist olives (calculated with Standard Gross Margin)"
cap label var FT34_SGM "Various permanent crops combined (calculated with Standard Gross Margin)"
cap label var FT4_SGM "Specialist grazing livestock (calculated with Standard Gross Margin)"
cap label var FT41_SGM "Specialist dairying (calculated with Standard Gross Margin)"
cap label var FT42_SGM "Specialist cattle-rearing and fattening (calculated with Standard Gross Margin)"
cap label var FT43_SGM "Cattle-dairying, rearing and fattening combined (calculated with Standard Gross Margin)"
cap label var FT44_SGM "Sheep, goats and other grazing livestock (calculated with Standard Gross Margin)"
cap label var FT5_SGM "Specialist granivores (calculated with Standard Gross Margin)"
cap label var FT50_SGM "Specialist granivores (calculated with Standard Gross Margin)"
cap label var FT6_SGM "Mixed cropping (calculated with Standard Gross Margin)"
cap label var FT60_SGM "Mixed cropping (calculated with Standard Gross Margin)"
cap label var FT7_SGM "Mixed livestock farms (calculated with Standard Gross Margin)"
cap label var FT71_SGM "Mixed livestock, mainly grazing livestock (calculated with Standard Gross Margin)"
cap label var FT72_SGM "Mixed livestock, mainly granivores (calculated with Standard Gross Margin)"
cap label var FT8_SGM "Mixed crops-livestock (calculated with Standard Gross Margin)"
cap label var FT81_SGM "Field crops-grazing livestock combined (calculated with Standard Gross Margin)"
cap label var FT82_SGM "Various crops and livestock combined (calculated with Standard Gross Margin)"
cap label var FT9_SGM "Non-classifiable farms (calculated with Standard Gross Margin)"
