cap label var CODE "Label - English"
cap label var B_MD40 "Below 40% of median equivalised income"
cap label var A_MD40 "Above 40% of median equivalised income"
cap label var B_MD50 "Below 50% of median equivalised income"
cap label var A_MD50 "Above 50% of median equivalised income"
cap label var B_MD60 "Below 60% of median equivalised income"
cap label var A_MD60 "Above 60% of median equivalised income"
cap label var B_MD70 "Below 70% of median equivalised income"
cap label var A_MD70 "Above 70% of median equivalised income"
cap label var B_M40 "Below 40% of mean equivalised income"
cap label var A_M40 "Above 40% of mean equivalised income"
cap label var B_M50 "Below 50% of mean equivalised income"
cap label var A_M50 "Above 50% of mean equivalised income"
cap label var B_M60 "Below 60% of mean equivalised income"
cap label var A_M60 "Above 60% of mean equivalised income"
cap label var TOTAL "Total"
