cap label var CODE "Label - English"
cap label var EM_GSD "Households making ends meet with great difficulty, with difficulty or with some difficulty"
cap label var EM_FVE "Households making ends meet fairly easily, easily or very easily"
cap label var EM_GD "Households making ends meet with great difficulty"
cap label var EM_D "Households making ends meet with difficulty"
cap label var EM_SD "Households making ends meet with some difficulty"
cap label var EM_FE "Households making ends meet fairly easily"
cap label var EM_E "Households making ends meet easily"
cap label var EM_VE "Households making ends meet very easily"
