cap label var A "Annual"
cap label var S "Half-yearly, semester"
cap label var Q "Quarterly"
cap label var M "Monthly"
cap label var W "Weekly"
cap label var D "Daily"
cap label var H "Hourly"
cap label var B "Daily – businessweek"
cap label var N "Minutely"
