cap label var CODE "Label - English"
cap label var TOTAL "All customers"
cap label var HH "Household"
cap label var NHH "Non-household"
cap label var IND "Industrial"
cap label var NRG "Energy"
cap label var RES_SERV "Residential and services"
cap label var SERV "Services"
cap label var OTH "Other"
