cap label var CODE "Label - English"
cap label var DIS "Total discharges"
cap label var ALOS "In-patient average length of stay"
cap label var BEDDAY "In-patient hospital bed-days"
cap label var BED_OCC "Bed occupancy rate"
cap label var BED_OCC_GT80 "Bed occupancy rate over 80%"
cap label var BED_OCC_GT95 "Bed occupancy rate over 95%"
cap label var INPAT "In-patient discharges"
cap label var DAYCASE "Day case discharges"
