cap label var CODE "Label - English"
cap label var TIPSBP10 "Current account balance - % of GDP, 3 years average"
cap label var TIPSBP20 "Current account balance - % of GDP"
cap label var TIPSII10 "Net international investment position - % of GDP"
cap label var TIPSER10_1 "Real effective exchange rate, 42 trading partners - 1 year % change"
cap label var TIPSER10_2 "Real effective exchange rate, 42 trading partners - 3 years % change"
cap label var TIPSGO10 "General government sector debt - % of GDP"
cap label var TIPSPD22_1 "Household debt, consolidated including Non-profit institutions serving households - % of GDP"
cap label var TIPSPD22_2 "Household debt, consolidated including Non-profit institutions serving households - million units of national currency"
cap label var TIPSPD30_1 "Non-financial corporations debt - consolidated, % of GDP"
cap label var TIPSPC40_1 "Household including non-profit institutions serving households (NPISH) credit flow, consolidated - % of debt stock (t-1)"
cap label var TIPSPC40_2 "Household including non-profit institutions serving households (NPISH) credit flow, consolidated - million units of national currency"
cap label var TIPSPC30_1 "Non-financial corporations credit flow excluding foreign direct investment, consolidated - % of debt stock (t-1)"
cap label var TIPSPC30_2 "Non-financial corporations credit flow excluding foreign direct investment, consolidated - millions of national currency"
cap label var TIPSHO20 "House price index, nominal - 1 year % change"
cap label var TIPSUN20 "Unemployment rate - %"
cap label var TIPSLM60_1 "Labour force participation rate, % of total population aged 15-64"
cap label var TIPSLM60_2 "Labour force participation rate, % of total population aged 15-64 - % point change (t - (t-3))"
cap label var TIPSII50 "Net international investment position excluding non-defaultable instruments - % of GDP"
cap label var TIPSBP70 "Net Lending/Borrowing (current and capital account) - % of GDP"
cap label var TIPSNA40 "Nominal unit labour cost index - 10 years % change"
cap label var TIPSNA20 "Gross fixed capital formation at current prices - % of GDP"
cap label var TIPSLM10 "Nominal unit labour cost per hour worked - 3 years % change"
cap label var TIPSLM20 "Nominal unit labour cost per hour worked - 1 year % change"
cap label var TIPSPD35 "Non-financial corporations debt excluding foreign direct investments, consolidated"
cap label var TIPSPC20 "Private sector credit flow, consolidated - % of GDP"
cap label var TIPSPC10 "Private sector credit flow, non-consolidated - % of GDP"
cap label var TIPSPD20 "Private sector debt, consolidated - % of GDP"
cap label var TIPSFS10_1 "Total financial sector liabilities, non-consolidated - 1 year % change"
cap label var TIPSFS10_2 "Total financial sector liabilities, non-consolidated - million of national currency"
cap label var TIPSUN10 "Unemployment rate - 3 years average"
cap label var TIPSNA10 "Gross domestic product (GDP) at market prices - annual data"
cap label var TIPSST10 "Gross domestic expenditure on R&D - % of GDP"
cap label var TIPSEX10 "Export market shares - 3 years % change"
cap label var TIPSNA70 "Labour productivity per hour worked - 1 year % change"
cap label var TIPSCP10 "Core inflation differential vis-à-vis EA"
cap label var TIPSPD40 "Household including non-profit institutions serving households (NPISH) debt, consolidated"
cap label var TIPSBD10 "Gross non-performing loans, domestic and foreign entities - % of gross loans"
cap label var TIPSBD20 "Consolidated banking leverage, domestic and foreign entities (asset-to-equity multiple)"
cap label var TIPSBD30 "Tier-1 capital ratio banking sector"
cap label var TIPSBD40 "Return on equity of banks"
cap label var TIPSHO60 "Standardised house price-to-income ratio – annual data"
cap label var TIPSHO50 "Building permits - annual data"
cap label var TIPSLM70_1 "Long-term unemployment rate, % of active population aged 15-74"
cap label var TIPSLM70_2 "Long-term unemployment rate, % of active population aged 15-74 - % point change (t, t-3)"
cap label var TIPSLM80_1 "Youth unemployment rate, % of active population aged 15-74"
cap label var TIPSLM80_2 "Youth unemployment rate - % of active population aged 15-74 - % point change (t, t-3)"
cap label var TIPSLM90_1 "Young people neither in employment nor in education and training (15-29 years) - % of total population"
cap label var TIPSLM90_2 "Young people neither in employment nor in education and training (15-29 years) - % of total population, % point change (t, t-3)"
cap label var TIPSLM100 "Employment rate"
cap label var TIPSLC10_1 "People at risk of poverty or social exclusion - % of total population"
cap label var TIPSLC10_2 "People at risk of poverty or social exclusion - % of total population, % point change (t, t-3)"
cap label var TIPSLC20_1 "People at risk of poverty after social transfer - % of total population"
cap label var TIPSLC20_2 "People at risk of poverty after social transfer - % of total population, % point change (t, t-3)"
cap label var TIPSLC30_1 "Severely materially and socially deprived people - % of total population"
cap label var TIPSLC30_2 "Severely materially and socially deprived people - % of total population, % point change (t, t-3)"
cap label var TIPSLC40_1 "People living in households with very low work Intensity - % of population aged 0-59"
cap label var TIPSLC40_2 "People living in households with very low work intensity - % of population aged 0-59, % point change (t, t-3)"
cap label var TIPSII20 "Net external debt - % of GDP"
cap label var TIPSBP90 "Direct investment liabilities (flows) - % of GDP"
cap label var TIPSBP100 "Direct investment liabilities (stocks) - % of GDP"
cap label var TIPSEN10 "Net trade balance of energy products - % of GDP"
cap label var TIPSER20 "Real effective exchange rate, euro area trading partners - 3 years % change"
cap label var TIPSBP60 "Share of exports of advanced economies"
cap label var TIPSNA30 "Terms of trade by items - 5 years % change"
cap label var TIPSLM50 "Unit labour cost performance related to the euro area - 10 years % change"
cap label var TIPSHO10 "House price index, deflated - 1 year % change"
cap label var TIPSNA50 "Residential construction - % of GDP"
cap label var TIPSPD10 "Private sector debt, non-consolidated - % of GDP"
cap label var TIPSFS20 "Financial sector leverage (debt to equity), non-consolidated - %"
cap label var TIPSNA60 "Employment, domestic concept  - 1 year % change"
cap label var TIPSEX13 "Export market shares, volumes - 1 year % change"
cap label var TIPSBP60_1 "Share of exports of advanced economies - 3 years % change"
cap label var TIPSBP60_2 "Share of exports of advanced economies - 1 year % change"
cap label var TIPSPD30 "Non-financial corporations debt - consolidated, % of GDP"
cap label var TIPSBP19 "Financial account by components, net balance - annual data, million units of national currency"
cap label var TIPSBP22 "Direct investment abroad, main components - annual data, million units of national currency"
cap label var TIPSBP40 "Current account balance - quarterly data"
cap label var TIPSBP50 "Net Lending/Borrowing (current and capital account) - quarterly data"
cap label var TIPSII13 "Direct investment assets, by instruments - annual data, million units of national currency"
cap label var TIPSER12 "Nominal effective exchange rate – euro area trading partners"
cap label var TIPSER13 "Real effective exchange rate – index, 42 trading partners"
cap label var TIPSEX11 "Export market shares by items - 1 year % change"
cap label var TIPSGO11 "Government consolidated gross debt by components - annual data"
cap label var TIPSFS10 "Total financial sector liabilities, non-consolidated - annual data"
cap label var TIPSLM70 "Long-term unemployment rate, % of active population aged 15-74"
cap label var TIPSLM80 "Youth unemployment rate - % of active population aged 15-24"
cap label var TIPSLM90 "Young people neither in employment nor in education and training (15-29 years) - % of the total population in the same age group"
cap label var TIPSHO40 "House price index - quarterly data"
cap label var TIPSLC10 "People at risk of poverty or social exclusion"
cap label var TIPSLC20 "People at risk of poverty after social transfer"
cap label var TIPSLC30 "Severely materially and socially deprived people"
cap label var TIPSLC40 "People living in households with very low work intensity"
cap label var TIPSLM10_2 "Nominal unit labour cost per hour worked - 3 years % change"
