cap label var CODE "Label - English"
cap label var _100100 "Primary production"
cap label var _100300 "Total imports"
cap label var _100500 "Total exports"
cap label var _100900 "Gross inland consumption"
cap label var _101000 "Transformation input"
cap label var _101100 "Transformation output"
cap label var _101800 "Final energy consumption - industry"
cap label var _101900 "Final energy consumption - transport"
cap label var _102000 "Final energy consumption - households/services"
cap label var MSHH "Medium size households"
cap label var MSIND "Non-household, medium size consumers"
cap label var _10_128101D "Stock levels / Opening / (a) All stocks on national territory (b+c+d+e+f+g+h+i)"
cap label var _10_128201D "Stock levels / Closing / (a) All stocks on national territory (b+c+d+e+f+g+h+i)"
cap label var _10_128102 "Stock levels / Opening / (b) Stocks held for other countries under official agreement"
cap label var _10_128202 "Stock levels / Closing / (b) Stocks held for other countries under official agreement"
cap label var _10_128104 "Stock levels / Opening / (c) Stocks with known foreign destination"
cap label var _10_128204 "Stock levels / Closing / (c) Stocks with known foreign destination"
cap label var _10_128108 "Stock levels / Opening / (d) Stocks held in bonded areas and not included in (b) or (c)"
cap label var _10_128208 "Stock levels / Closing / (d) Stocks held in bonded areas and not included in (b) or (c)"
cap label var _10_128109 "Stock levels / Opening / (e) Stocks held by major consumers, obligated by law"
cap label var _10_128209 "Stock levels / Closing / (e) Stocks held by major consumers, obligated by law"
cap label var _10_128110 "Stock levels / Opening / (f) Stocks held on board incoming ocean vessels in port or at mooring"
cap label var _10_128210 "Stock levels / Closing / (f) Stocks held on board incoming ocean vessels in port or at mooring"
cap label var _10_128111 "Stock levels / Opening / (g) Stocks held by government on national territory"
cap label var _10_128211 "Stock levels / Closing / (g) Stocks held by government on national territory"
cap label var _10_128112 "Stock levels / Opening / (h) Stocks held by stock holding organisation on national territory"
cap label var _10_128212 "Stock levels / Closing / (h) Stocks held by stock holding organisation on national territory"
cap label var _10_128113 "Stock levels / Opening / (i) All other stocks held on national territory"
cap label var _10_128213 "Stock levels / Closing / (i) All other stocks held on national territory"
cap label var _10_128105 "Stock levels / Opening / (j) Stocks held abroad under official agreement (o+p+q)"
cap label var _10_128205 "Stock levels / Closing / (j) Stocks held abroad under official agreement (o+p+q)"
cap label var _10_128107 "Stock levels / Opening / (k) Stocks held abroad designated definitely for import into your country"
cap label var _10_128207 "Stock levels / Closing / (k) Stocks held abroad designated definitely for import into your country"
cap label var _10_128114D "Stock levels / Opening / (l) Total stocks"
cap label var _10_128214D "Stock levels / Closing / (l) Total stocks (a-b-c+j+k)"
cap label var _10_128115 "Stock levels / Opening / (m) Other stocks in bonded areas"
cap label var _10_128215 "Stock levels / Closing / (m) Other stocks in bonded areas"
cap label var _10_128116 "Stock levels / Opening / (n) Pipeline fill"
cap label var _10_128216 "Stock levels / Closing / (n) Pipeline fill"
cap label var _10_128117 "Stock levels / Opening / (o) Government stocks held abroad under official agreement"
cap label var _10_128217 "Stock levels / Closing / (o) Government stocks held abroad under official agreement"
cap label var _10_128118 "Stock levels / Opening / (p) Holding organisation's stocks held abroad under official agreement"
cap label var _10_128218 "Stock levels / Closing / (p) Holding organisation's stocks held abroad under official agreement"
cap label var _10_128119 "Stock levels / Opening / (q) Other stocks held abroad under official agreement"
cap label var _10_128219 "Stock levels / Closing / (q) Other stocks held abroad under official agreement"
cap label var _10_1281EU01D "Stock levels / Opening / (EU-a) Emergency stocks (Total) on national territory"
cap label var _10_1282EU01D "Stock levels / Closing / (EU-a) Emergency stocks (Total) on national territory"
cap label var _10_1281EU02 "Stock levels / Opening / (EU-b) Stocks held for other EU Member States under official agreement"
cap label var _10_1282EU02 "Stock levels / Closing / (EU-b) Stocks held for other EU Member States under official agreement"
cap label var _10_1281EU04 "Stock levels / Opening / (EU-c) Stocks with known foreign EU destination"
cap label var _10_1282EU04 "Stock levels / Closing / (EU-c) Stocks with known foreign EU destination"
cap label var _10_1281EU11 "Stock levels / Opening / (EU-g) Stocks held by government on national territory"
cap label var _10_1282EU11 "Stock levels / Closing / (EU-g) Stocks held by government on national territory"
cap label var _10_1281EU12 "Stock levels / Opening / (EU-h) Stocks held by the Cenral Stockholding Entity (CSE) on national territory"
cap label var _10_1282EU12 "Stock levels / Closing / (EU-h) Stocks held by the Cenral Stockholding Entity (CSE) on national territory"
cap label var _10_1281EU09 "Stock levels / Opening / (EU-ie) Stocks held by Economic Operators on national territory"
cap label var _10_1282EU09 "Stock levels / Closing / (EU-ie) Stocks held by Economic Operators on national territory"
cap label var _10_1281EU05 "Stock levels / Opening / (EU-j) Stocks held abroad in other EU Member States under official agreement"
cap label var _10_1282EU05 "Stock levels / Closing / (EU-j) Stocks held abroad in other EU Member States under official agreement"
cap label var _10_1281EU07 "Stock levels / Opening / (EU-k) Stocks held abroad in EU, designated definitely for import into your country"
cap label var _10_1282EU07 "Stock levels / Closing / (EU-k) Stocks held abroad in EU, designated definitely for import into your country"
cap label var _10_1281EU14D "Stock levels / Opening / (EU-l) Emergency Stocks held in accordance with the Directive 2009/119/EC"
cap label var _10_1282EU14D "Stock levels / Closing / (EU-l) Emergency Stocks held in accordance with the Directive 2009/119/EC"
cap label var _10_101108 "Sum of monthly figures / Refinery gross output"
cap label var _10_101307 "Sum of monthly figures / Refinery fuel"
cap label var _10_100300 "Sum of monthly figures / Imports (Balance)"
cap label var _10_100500 "Sum of monthly figures / Exports (Balance)"
cap label var _10_101008 "Sum of monthly figures / Refinery intake (Calculated)"
cap label var _10_100800 "Sum of monthly figures / International marine bunkers"
cap label var _10_105200 "Sum of monthly figures / Gross inland deliveries (Observed)"
cap label var _10_109013 "Sum of monthly figures / Backflows to refineries"
cap label var _10_128101JAN "Opening January / All stocks on national territory"
cap label var _10_128201DEC "Closing December / All stocks on national territory"
cap label var _10_1281EU21 "Stock levels / Opening / (EU) Commercial stocks held by Economic Operators on national territory under Directive 2009/119/EC"
cap label var _10_1282EU21 "Stock levels / Closing / (EU) Commercial stocks held by Economic Operators on national territory under Directive 2009/119/EC"
cap label var _10_3382020070 "Stocks held for other countries / Closing / under official agreement - Albania"
cap label var _10_3382020800 "Stocks held for other countries / Closing / under official agreement - Australia"
cap label var _10_3382020038 "Stocks held for other countries / Closing / under official agreement - Austria"
cap label var _10_3382020012 "Stocks held for other countries / Closing / under official agreement - Belgium"
cap label var _10_3382020093 "Stocks held for other countries / Closing / under official agreement - Bosnia and Herzegovina"
cap label var _10_3382020068 "Stocks held for other countries / Closing / under official agreement - Bulgaria"
cap label var _10_3382020404 "Stocks held for other countries / Closing / under official agreement - Canada"
cap label var _10_3382020510 "Stocks held for other countries / Closing / under official agreement - Chile"
cap label var _10_3382020092 "Stocks held for other countries / Closing / under official agreement - Croatia"
cap label var _10_3382020600 "Stocks held for other countries / Closing / under official agreement - Cyprus"
cap label var _10_3382020061 "Stocks held for other countries / Closing / under official agreement - Czech Republic"
cap label var _10_3382020008 "Stocks held for other countries / Closing / under official agreement - Denmark"
cap label var _10_3382020053 "Stocks held for other countries / Closing / under official agreement - Estonia"
cap label var _10_3382020032 "Stocks held for other countries / Closing / under official agreement - Finland"
cap label var _10_3382020001 "Stocks held for other countries / Closing / under official agreement - France"
cap label var _10_3382020076 "Stocks held for other countries / Closing / under official agreement - Georgia"
cap label var _10_3382020004 "Stocks held for other countries / Closing / under official agreement - Germany"
cap label var _10_3382020009 "Stocks held for other countries / Closing / under official agreement - Greece"
cap label var _10_3382020064 "Stocks held for other countries / Closing / under official agreement - Hungary"
cap label var _10_3382020024 "Stocks held for other countries / Closing / under official agreement - Iceland"
cap label var _10_3382020007 "Stocks held for other countries / Closing / under official agreement - Ireland"
cap label var _10_3382020205 "Stocks held for other countries / Closing / under official agreement - Israel"
cap label var _10_3382020005 "Stocks held for other countries / Closing / under official agreement - Italy"
cap label var _10_3382020732 "Stocks held for other countries / Closing / under official agreement - Japan"
cap label var _10_3382020728 "Stocks held for other countries / Closing / under official agreement - Korea"
cap label var _10_3382020095 "Stocks held for other countries / Closing / under official agreement - Kosovo (under United Nations Security Council Resolution 1244/99)"
cap label var _10_3382020055 "Stocks held for other countries / Closing / under official agreement - Latvia"
cap label var _10_3382020054 "Stocks held for other countries / Closing / under official agreement - Lithuania"
cap label var _10_3382020022 "Stocks held for other countries / Closing / under official agreement - Luxembourg"
cap label var _10_3382020096 "Stocks held for other countries / Closing / under official agreement - North Macedonia"
cap label var _10_3382020085 "Stocks held for other countries / Closing / under official agreement - Malta"
cap label var _10_3382020412 "Stocks held for other countries / Closing / under official agreement - Mexico"
cap label var _10_3382020074 "Stocks held for other countries / Closing / under official agreement - Moldova"
cap label var _10_3382020097 "Stocks held for other countries / Closing / under official agreement - Montenegro"
cap label var _10_3382020003 "Stocks held for other countries / Closing / under official agreement - Netherlands"
cap label var _10_3382020801 "Stocks held for other countries / Closing / under official agreement - New Zealand"
cap label var _10_3382020028 "Stocks held for other countries / Closing / under official agreement - Norway"
cap label var _10_3382020060 "Stocks held for other countries / Closing / under official agreement - Poland"
cap label var _10_3382020040 "Stocks held for other countries / Closing / under official agreement - Portugal"
cap label var _10_3382020066 "Stocks held for other countries / Closing / under official agreement - Romania"
cap label var _10_3382020057 "Stocks held for other countries / Closing / under official agreement - Russian Federation"
cap label var _10_3382020050 "Stocks held for other countries / Closing / under official agreement - Serbia"
cap label var _10_3382020063 "Stocks held for other countries / Closing / under official agreement - Slovak Republic"
cap label var _10_3382020091 "Stocks held for other countries / Closing / under official agreement - Slovenia"
cap label var _10_3382020042 "Stocks held for other countries / Closing / under official agreement - Spain"
cap label var _10_3382020030 "Stocks held for other countries / Closing / under official agreement - Sweden"
cap label var _10_3382020036 "Stocks held for other countries / Closing / under official agreement - Switzerland"
cap label var _10_3382020052 "Stocks held for other countries / Closing / under official agreement - Türkiye"
cap label var _10_3382020058 "Stocks held for other countries / Closing / under official agreement - Ukraine"
cap label var _10_3382020006 "Stocks held for other countries / Closing / under official agreement - United Kingdom"
cap label var _10_3382020400 "Stocks held for other countries / Closing / under official agreement - United States"
cap label var _10_3382020999 "Stocks held for other countries / Closing / under official agreement - Others"
cap label var _10_3382021000D "Stocks held for other countries / Closing / under official agreement - Total"
cap label var _10_3382021010D "Stocks held for other countries / Closing / under official agreement - Total EU MS"
cap label var _10_3382030070 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Albania"
cap label var _10_3382030800 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Australia"
cap label var _10_3382030038 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Austria"
cap label var _10_3382030012 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Belgium"
cap label var _10_3382030093 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Bosnia and Herzegovina"
cap label var _10_3382030068 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Bulgaria"
cap label var _10_3382030404 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Canada"
cap label var _10_3382030510 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Chile"
cap label var _10_3382030092 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Croatia"
cap label var _10_3382030600 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Cyprus"
cap label var _10_3382030061 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Czech Republic"
cap label var _10_3382030008 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Denmark"
cap label var _10_3382030053 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Estonia"
cap label var _10_3382030032 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Finland"
cap label var _10_3382030001 "Stocks held for other countries / Closing / under official agreement / of which as tickets - France"
cap label var _10_3382030076 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Georgia"
cap label var _10_3382030004 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Germany"
cap label var _10_3382030009 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Greece"
cap label var _10_3382030064 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Hungary"
cap label var _10_3382030024 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Iceland"
cap label var _10_3382030007 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Ireland"
cap label var _10_3382030205 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Israel"
cap label var _10_3382030005 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Italy"
cap label var _10_3382030732 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Japan"
cap label var _10_3382030728 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Korea"
cap label var _10_3382030095 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Kosovo (under United Nations Security Council Resolution 1244/99)"
cap label var _10_3382030055 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Latvia"
cap label var _10_3382030054 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Lithuania"
cap label var _10_3382030022 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Luxembourg"
cap label var _10_3382030096 "Stocks held for other countries / Closing / under official agreement / of which as tickets - North Macedonia"
cap label var _10_3382030085 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Malta"
cap label var _10_3382030412 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Mexico"
cap label var _10_3382030074 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Moldova"
cap label var _10_3382030097 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Montenegro"
cap label var _10_3382030003 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Netherlands"
cap label var _10_3382030801 "Stocks held for other countries / Closing / under official agreement / of which as tickets - New Zealand"
cap label var _10_3382030028 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Norway"
cap label var _10_3382030060 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Poland"
cap label var _10_3382030040 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Portugal"
cap label var _10_3382030066 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Romania"
cap label var _10_3382030057 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Russian Federation"
cap label var _10_3382030050 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Serbia"
cap label var _10_3382030063 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Slovak Republic"
cap label var _10_3382030091 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Slovenia"
cap label var _10_3382030042 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Spain"
cap label var _10_3382030030 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Sweden"
cap label var _10_3382030036 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Switzerland"
cap label var _10_3382030052 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Türkiye"
cap label var _10_3382030058 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Ukraine"
cap label var _10_3382030006 "Stocks held for other countries / Closing / under official agreement / of which as tickets - United Kingdom"
cap label var _10_3382030400 "Stocks held for other countries / Closing / under official agreement / of which as tickets - United States"
cap label var _10_3382030999 "Stocks held for other countries / Closing / under official agreement / of which as tickets - Others"
cap label var _10_3382031000D "Stocks held for other countries / Closing / under official agreement / of which as tickets - Total"
cap label var _10_3382031010D "Stocks held for other countries / Closing / under official agreement / of which as tickets - Total EU MS"
cap label var _10_3382040070 "Stocks / Closing / with known foreign destination - Albania"
cap label var _10_3382040800 "Stocks / Closing / with known foreign destination - Australia"
cap label var _10_3382040038 "Stocks / Closing / with known foreign destination - Austria"
cap label var _10_3382040012 "Stocks / Closing / with known foreign destination - Belgium"
cap label var _10_3382040093 "Stocks / Closing / with known foreign destination - Bosnia and Herzegovina"
cap label var _10_3382040068 "Stocks / Closing / with known foreign destination - Bulgaria"
cap label var _10_3382040404 "Stocks / Closing / with known foreign destination - Canada"
cap label var _10_3382040510 "Stocks / Closing / with known foreign destination - Chile"
cap label var _10_3382040092 "Stocks / Closing / with known foreign destination - Croatia"
cap label var _10_3382040600 "Stocks / Closing / with known foreign destination - Cyprus"
cap label var _10_3382040061 "Stocks / Closing / with known foreign destination - Czech Republic"
cap label var _10_3382040008 "Stocks / Closing / with known foreign destination - Denmark"
cap label var _10_3382040053 "Stocks / Closing / with known foreign destination - Estonia"
cap label var _10_3382040032 "Stocks / Closing / with known foreign destination - Finland"
cap label var _10_3382040001 "Stocks / Closing / with known foreign destination - France"
cap label var _10_3382040076 "Stocks / Closing / with known foreign destination - Georgia"
cap label var _10_3382040004 "Stocks / Closing / with known foreign destination - Germany"
cap label var _10_3382040009 "Stocks / Closing / with known foreign destination - Greece"
cap label var _10_3382040064 "Stocks / Closing / with known foreign destination - Hungary"
cap label var _10_3382040024 "Stocks / Closing / with known foreign destination - Iceland"
cap label var _10_3382040007 "Stocks / Closing / with known foreign destination - Ireland"
cap label var _10_3382040205 "Stocks / Closing / with known foreign destination - Israel"
cap label var _10_3382040005 "Stocks / Closing / with known foreign destination - Italy"
cap label var _10_3382040732 "Stocks / Closing / with known foreign destination - Japan"
cap label var _10_3382040728 "Stocks / Closing / with known foreign destination - Korea"
cap label var _10_3382040095 "Stocks / Closing / with known foreign destination - Kosovo (under United Nations Security Council Resolution 1244/99)"
cap label var _10_3382040055 "Stocks / Closing / with known foreign destination - Latvia"
cap label var _10_3382040054 "Stocks / Closing / with known foreign destination - Lithuania"
cap label var _10_3382040022 "Stocks / Closing / with known foreign destination - Luxembourg"
cap label var _10_3382040096 "Stocks / Closing / with known foreign destination - North Macedonia"
cap label var _10_3382040085 "Stocks / Closing / with known foreign destination - Malta"
cap label var _10_3382040412 "Stocks / Closing / with known foreign destination - Mexico"
cap label var _10_3382040074 "Stocks / Closing / with known foreign destination - Moldova"
cap label var _10_3382040097 "Stocks / Closing / with known foreign destination - Montenegro"
cap label var _10_3382040003 "Stocks / Closing / with known foreign destination - Netherlands"
cap label var _10_3382040801 "Stocks / Closing / with known foreign destination - New Zealand"
cap label var _10_3382040028 "Stocks / Closing / with known foreign destination - Norway"
cap label var _10_3382040060 "Stocks / Closing / with known foreign destination - Poland"
cap label var _10_3382040040 "Stocks / Closing / with known foreign destination - Portugal"
cap label var _10_3382040066 "Stocks / Closing / with known foreign destination - Romania"
cap label var _10_3382040057 "Stocks / Closing / with known foreign destination - Russian Federation"
cap label var _10_3382040050 "Stocks / Closing / with known foreign destination - Serbia"
cap label var _10_3382040063 "Stocks / Closing / with known foreign destination - Slovak Republic"
cap label var _10_3382040091 "Stocks / Closing / with known foreign destination - Slovenia"
cap label var _10_3382040042 "Stocks / Closing / with known foreign destination - Spain"
cap label var _10_3382040030 "Stocks / Closing / with known foreign destination - Sweden"
cap label var _10_3382040036 "Stocks / Closing / with known foreign destination - Switzerland"
cap label var _10_3382040052 "Stocks / Closing / with known foreign destination - Türkiye"
cap label var _10_3382040058 "Stocks / Closing / with known foreign destination - Ukraine"
cap label var _10_3382040006 "Stocks / Closing / with known foreign destination - United Kingdom"
cap label var _10_3382040400 "Stocks / Closing / with known foreign destination - United States"
cap label var _10_3382040999 "Stocks / Closing / with known foreign destination - Others"
cap label var _10_3382041000D "Stocks / Closing / with known foreign destination - Total"
cap label var _10_3382041010D "Stocks / Closing / with known foreign destination - Total EU MS"
cap label var _10_3482050070 "Stocks held abroad / Closing / under official agreement - Albania"
cap label var _10_3482050800 "Stocks held abroad / Closing / under official agreement - Australia"
cap label var _10_3482050038 "Stocks held abroad / Closing / under official agreement - Austria"
cap label var _10_3482050012 "Stocks held abroad / Closing / under official agreement - Belgium"
cap label var _10_3482050093 "Stocks held abroad / Closing / under official agreement - Bosnia and Herzegovina"
cap label var _10_3482050068 "Stocks held abroad / Closing / under official agreement - Bulgaria"
cap label var _10_3482050404 "Stocks held abroad / Closing / under official agreement - Canada"
cap label var _10_3482050510 "Stocks held abroad / Closing / under official agreement - Chile"
cap label var _10_3482050092 "Stocks held abroad / Closing / under official agreement - Croatia"
cap label var _10_3482050600 "Stocks held abroad / Closing / under official agreement - Cyprus"
cap label var _10_3482050061 "Stocks held abroad / Closing / under official agreement - Czech Republic"
cap label var _10_3482050008 "Stocks held abroad / Closing / under official agreement - Denmark"
cap label var _10_3482050053 "Stocks held abroad / Closing / under official agreement - Estonia"
cap label var _10_3482050032 "Stocks held abroad / Closing / under official agreement - Finland"
cap label var _10_3482050001 "Stocks held abroad / Closing / under official agreement - France"
cap label var _10_3482050076 "Stocks held abroad / Closing / under official agreement - Georgia"
cap label var _10_3482050004 "Stocks held abroad / Closing / under official agreement - Germany"
cap label var _10_3482050009 "Stocks held abroad / Closing / under official agreement - Greece"
cap label var _10_3482050064 "Stocks held abroad / Closing / under official agreement - Hungary"
cap label var _10_3482050024 "Stocks held abroad / Closing / under official agreement - Iceland"
cap label var _10_3482050007 "Stocks held abroad / Closing / under official agreement - Ireland"
cap label var _10_3482050205 "Stocks held abroad / Closing / under official agreement - Israel"
cap label var _10_3482050005 "Stocks held abroad / Closing / under official agreement - Italy"
cap label var _10_3482050732 "Stocks held abroad / Closing / under official agreement - Japan"
cap label var _10_3482050728 "Stocks held abroad / Closing / under official agreement - Korea"
cap label var _10_3482050095 "Stocks held abroad / Closing / under official agreement - Kosovo (under United Nations Security Council Resolution 1244/99)"
cap label var _10_3482050055 "Stocks held abroad / Closing / under official agreement - Latvia"
cap label var _10_3482050054 "Stocks held abroad / Closing / under official agreement - Lithuania"
cap label var _10_3482050022 "Stocks held abroad / Closing / under official agreement - Luxembourg"
cap label var _10_3482050096 "Stocks held abroad / Closing / under official agreement - North Macedonia"
cap label var _10_3482050085 "Stocks held abroad / Closing / under official agreement - Malta"
cap label var _10_3482050412 "Stocks held abroad / Closing / under official agreement - Mexico"
cap label var _10_3482050074 "Stocks held abroad / Closing / under official agreement - Moldova"
cap label var _10_3482050097 "Stocks held abroad / Closing / under official agreement - Montenegro"
cap label var _10_3482050003 "Stocks held abroad / Closing / under official agreement - Netherlands"
cap label var _10_3482050801 "Stocks held abroad / Closing / under official agreement - New Zealand"
cap label var _10_3482050028 "Stocks held abroad / Closing / under official agreement - Norway"
cap label var _10_3482050060 "Stocks held abroad / Closing / under official agreement - Poland"
cap label var _10_3482050040 "Stocks held abroad / Closing / under official agreement - Portugal"
cap label var _10_3482050066 "Stocks held abroad / Closing / under official agreement - Romania"
cap label var _10_3482050057 "Stocks held abroad / Closing / under official agreement - Russian Federation"
cap label var _10_3482050050 "Stocks held abroad / Closing / under official agreement - Serbia"
cap label var _10_3482050063 "Stocks held abroad / Closing / under official agreement - Slovak Republic"
cap label var _10_3482050091 "Stocks held abroad / Closing / under official agreement - Slovenia"
cap label var _10_3482050042 "Stocks held abroad / Closing / under official agreement - Spain"
cap label var _10_3482050030 "Stocks held abroad / Closing / under official agreement - Sweden"
cap label var _10_3482050036 "Stocks held abroad / Closing / under official agreement - Switzerland"
cap label var _10_3482050052 "Stocks held abroad / Closing / under official agreement - Türkiye"
cap label var _10_3482050058 "Stocks held abroad / Closing / under official agreement - Ukraine"
cap label var _10_3482050006 "Stocks held abroad / Closing / under official agreement - United Kingdom"
cap label var _10_3482050400 "Stocks held abroad / Closing / under official agreement - United States"
cap label var _10_3482050999 "Stocks held abroad / Closing / under official agreement - Others"
cap label var _10_3482051000D "Stocks held abroad / Closing / under official agreement - Total"
cap label var _10_3482051010D "Stocks held abroad / Closing / under official agreement - Total EU MS"
cap label var _10_3482060070 "Stocks held abroad / Closing / under official agreement / of which as tickets - Albania"
cap label var _10_3482060800 "Stocks held abroad / Closing / under official agreement / of which as tickets - Australia"
cap label var _10_3482060038 "Stocks held abroad / Closing / under official agreement / of which as tickets - Austria"
cap label var _10_3482060012 "Stocks held abroad / Closing / under official agreement / of which as tickets - Belgium"
cap label var _10_3482060093 "Stocks held abroad / Closing / under official agreement / of which as tickets - Bosnia and Herzegovina"
cap label var _10_3482060068 "Stocks held abroad / Closing / under official agreement / of which as tickets - Bulgaria"
cap label var _10_3482060404 "Stocks held abroad / Closing / under official agreement / of which as tickets - Canada"
cap label var _10_3482060510 "Stocks held abroad / Closing / under official agreement / of which as tickets - Chile"
cap label var _10_3482060092 "Stocks held abroad / Closing / under official agreement / of which as tickets - Croatia"
cap label var _10_3482060600 "Stocks held abroad / Closing / under official agreement / of which as tickets - Cyprus"
cap label var _10_3482060061 "Stocks held abroad / Closing / under official agreement / of which as tickets - Czech Republic"
cap label var _10_3482060008 "Stocks held abroad / Closing / under official agreement / of which as tickets - Denmark"
cap label var _10_3482060053 "Stocks held abroad / Closing / under official agreement / of which as tickets - Estonia"
cap label var _10_3482060032 "Stocks held abroad / Closing / under official agreement / of which as tickets - Finland"
cap label var _10_3482060001 "Stocks held abroad / Closing / under official agreement / of which as tickets - France"
cap label var _10_3482060076 "Stocks held abroad / Closing / under official agreement / of which as tickets - Georgia"
cap label var _10_3482060004 "Stocks held abroad / Closing / under official agreement / of which as tickets - Germany"
cap label var _10_3482060009 "Stocks held abroad / Closing / under official agreement / of which as tickets - Greece"
cap label var _10_3482060064 "Stocks held abroad / Closing / under official agreement / of which as tickets - Hungary"
cap label var _10_3482060024 "Stocks held abroad / Closing / under official agreement / of which as tickets - Iceland"
cap label var _10_3482060007 "Stocks held abroad / Closing / under official agreement / of which as tickets - Ireland"
cap label var _10_3482060205 "Stocks held abroad / Closing / under official agreement / of which as tickets - Israel"
cap label var _10_3482060005 "Stocks held abroad / Closing / under official agreement / of which as tickets - Italy"
cap label var _10_3482060732 "Stocks held abroad / Closing / under official agreement / of which as tickets - Japan"
cap label var _10_3482060728 "Stocks held abroad / Closing / under official agreement / of which as tickets - Korea"
cap label var _10_3482060095 "Stocks held abroad / Closing / under official agreement / of which as tickets - Kosovo (under United Nations Security Council Resolution 1244/99)"
cap label var _10_3482060055 "Stocks held abroad / Closing / under official agreement / of which as tickets - Latvia"
cap label var _10_3482060054 "Stocks held abroad / Closing / under official agreement / of which as tickets - Lithuania"
cap label var _10_3482060022 "Stocks held abroad / Closing / under official agreement / of which as tickets - Luxembourg"
cap label var _10_3482060096 "Stocks held abroad / Closing / under official agreement / of which as tickets - North Macedonia"
cap label var _10_3482060085 "Stocks held abroad / Closing / under official agreement / of which as tickets - Malta"
cap label var _10_3482060412 "Stocks held abroad / Closing / under official agreement / of which as tickets - Mexico"
cap label var _10_3482060074 "Stocks held abroad / Closing / under official agreement / of which as tickets - Moldova"
cap label var _10_3482060097 "Stocks held abroad / Closing / under official agreement / of which as tickets - Montenegro"
cap label var _10_3482060003 "Stocks held abroad / Closing / under official agreement / of which as tickets - Netherlands"
cap label var _10_3482060801 "Stocks held abroad / Closing / under official agreement / of which as tickets - New Zealand"
cap label var _10_3482060028 "Stocks held abroad / Closing / under official agreement / of which as tickets - Norway"
cap label var _10_3482060060 "Stocks held abroad / Closing / under official agreement / of which as tickets - Poland"
cap label var _10_3482060040 "Stocks held abroad / Closing / under official agreement / of which as tickets - Portugal"
cap label var _10_3482060066 "Stocks held abroad / Closing / under official agreement / of which as tickets - Romania"
cap label var _10_3482060057 "Stocks held abroad / Closing / under official agreement / of which as tickets - Russian Federation"
cap label var _10_3482060050 "Stocks held abroad / Closing / under official agreement / of which as tickets - Serbia"
cap label var _10_3482060063 "Stocks held abroad / Closing / under official agreement / of which as tickets - Slovak Republic"
cap label var _10_3482060091 "Stocks held abroad / Closing / under official agreement / of which as tickets - Slovenia"
cap label var _10_3482060042 "Stocks held abroad / Closing / under official agreement / of which as tickets - Spain"
cap label var _10_3482060030 "Stocks held abroad / Closing / under official agreement / of which as tickets - Sweden"
cap label var _10_3482060036 "Stocks held abroad / Closing / under official agreement / of which as tickets - Switzerland"
cap label var _10_3482060052 "Stocks held abroad / Closing / under official agreement / of which as tickets - Türkiye"
cap label var _10_3482060058 "Stocks held abroad / Closing / under official agreement / of which as tickets - Ukraine"
cap label var _10_3482060006 "Stocks held abroad / Closing / under official agreement / of which as tickets - United Kingdom"
cap label var _10_3482060400 "Stocks held abroad / Closing / under official agreement / of which as tickets - United States"
cap label var _10_3482060999 "Stocks held abroad / Closing / under official agreement / of which as tickets - Others"
cap label var _10_3482061000D "Stocks held abroad / Closing / under official agreement / of which as tickets - Total"
cap label var _10_3482061010D "Stocks held abroad / Closing / under official agreement / of which as tickets - Total EU MS"
cap label var _10_3482EU0070 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Albania"
cap label var _10_3482EU0800 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Australia"
cap label var _10_3482EU0038 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Austria"
cap label var _10_3482EU0012 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Belgium"
cap label var _10_3482EU00093 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Bosnia and Herzegovina"
cap label var _10_3482EU0068 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Bulgaria"
cap label var _10_3482EU0404 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Canada"
cap label var _10_3482EU0510 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Chile"
cap label var _10_3482EU0092 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Croatia"
cap label var _10_3482EU0600 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Cyprus"
cap label var _10_3482EU0061 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Czech Republic"
cap label var _10_3482EU0008 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Denmark"
cap label var _10_3482EU0053 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Estonia"
cap label var _10_3482EU0032 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Finland"
cap label var _10_3482EU0001 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - France"
cap label var _10_3482EU0076 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Georgia"
cap label var _10_3482EU0004 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Germany"
cap label var _10_3482EU0009 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Greece"
cap label var _10_3482EU0064 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Hungary"
cap label var _10_3482EU0024 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Iceland"
cap label var _10_3482EU0007 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Ireland"
cap label var _10_3482EU0205 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Israel"
cap label var _10_3482EU0005 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Italy"
cap label var _10_3482EU0732 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Japan"
cap label var _10_3482EU0728 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Korea"
cap label var _10_3482EU0095 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Kosovo (under United Nations Security Council Resolution 1244/99)"
cap label var _10_3482EU0055 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Latvia"
cap label var _10_3482EU0054 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Lithuania"
cap label var _10_3482EU0022 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Luxembourg"
cap label var _10_3482EU0096 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - North Macedonia"
cap label var _10_3482EU0085 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Malta"
cap label var _10_3482EU0412 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Mexico"
cap label var _10_3482EU0074 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Moldova"
cap label var _10_3482EU0097 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Montenegro"
cap label var _10_3482EU0003 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Netherlands"
cap label var _10_3482EU0801 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - New Zealand"
cap label var _10_3482EU0028 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Norway"
cap label var _10_3482EU0060 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Poland"
cap label var _10_3482EU0040 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Portugal"
cap label var _10_3482EU0066 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Romania"
cap label var _10_3482EU0057 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Russian Federation"
cap label var _10_3482EU0050 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Serbia"
cap label var _10_3482EU0063 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Slovak Republic"
cap label var _10_3482EU0091 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Slovenia"
cap label var _10_3482EU0042 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Spain"
cap label var _10_3482EU0030 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Sweden"
cap label var _10_3482EU0036 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Switzerland"
cap label var _10_3482EU0052 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Türkiye"
cap label var _10_3482EU0058 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Ukraine"
cap label var _10_3482EU0006 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - United Kingdom"
cap label var _10_3482EU0400 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - United States"
cap label var _10_3482EU0999 "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Others"
cap label var _10_3482EU1000D "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Total"
cap label var _10_3482EU1010D "Stocks held abroad / Closing / of which persuant to government / CSE delegation - Total EU MS"
cap label var _10_3482070070 "Stocks held abroad / Closing / designated definitely for import into your country - Albania"
cap label var _10_3482070800 "Stocks held abroad / Closing / designated definitely for import into your country - Australia"
cap label var _10_3482070038 "Stocks held abroad / Closing / designated definitely for import into your country - Austria"
cap label var _10_3482070012 "Stocks held abroad / Closing / designated definitely for import into your country - Belgium"
cap label var _10_3482070093 "Stocks held abroad / Closing / designated definitely for import into your country - Bosnia and Herzegovina"
cap label var _10_3482070068 "Stocks held abroad / Closing / designated definitely for import into your country - Bulgaria"
cap label var _10_3482070404 "Stocks held abroad / Closing / designated definitely for import into your country - Canada"
cap label var _10_3482070510 "Stocks held abroad / Closing / designated definitely for import into your country - Chile"
cap label var _10_3482070092 "Stocks held abroad / Closing / designated definitely for import into your country - Croatia"
cap label var _10_3482070600 "Stocks held abroad / Closing / designated definitely for import into your country - Cyprus"
cap label var _10_3482070061 "Stocks held abroad / Closing / designated definitely for import into your country - Czech Republic"
cap label var _10_3482070008 "Stocks held abroad / Closing / designated definitely for import into your country - Denmark"
cap label var _10_3482070053 "Stocks held abroad / Closing / designated definitely for import into your country - Estonia"
cap label var _10_3482070032 "Stocks held abroad / Closing / designated definitely for import into your country - Finland"
cap label var _10_3482070001 "Stocks held abroad / Closing / designated definitely for import into your country - France"
cap label var _10_3482070076 "Stocks held abroad / Closing / designated definitely for import into your country - Georgia"
cap label var _10_3482070004 "Stocks held abroad / Closing / designated definitely for import into your country - Germany"
cap label var _10_3482070009 "Stocks held abroad / Closing / designated definitely for import into your country - Greece"
cap label var _10_3482070064 "Stocks held abroad / Closing / designated definitely for import into your country - Hungary"
cap label var _10_3482070024 "Stocks held abroad / Closing / designated definitely for import into your country - Iceland"
cap label var _10_3482070007 "Stocks held abroad / Closing / designated definitely for import into your country - Ireland"
cap label var _10_3482070205 "Stocks held abroad / Closing / designated definitely for import into your country - Israel"
cap label var _10_3482070005 "Stocks held abroad / Closing / designated definitely for import into your country - Italy"
cap label var _10_3482070732 "Stocks held abroad / Closing / designated definitely for import into your country - Japan"
cap label var _10_3482070728 "Stocks held abroad / Closing / designated definitely for import into your country - Korea"
cap label var _10_3482070095 "Stocks held abroad / Closing / designated definitely for import into your country - Kosovo (under United Nations Security Council Resolution 1244/99)"
cap label var _10_3482070055 "Stocks held abroad / Closing / designated definitely for import into your country - Latvia"
cap label var _10_3482070054 "Stocks held abroad / Closing / designated definitely for import into your country - Lithuania"
cap label var _10_3482070022 "Stocks held abroad / Closing / designated definitely for import into your country - Luxembourg"
cap label var _10_3482070096 "Stocks held abroad / Closing / designated definitely for import into your country - North Macedonia"
cap label var _10_3482070085 "Stocks held abroad / Closing / designated definitely for import into your country - Malta"
cap label var _10_3482070412 "Stocks held abroad / Closing / designated definitely for import into your country - Mexico"
cap label var _10_3482070074 "Stocks held abroad / Closing / designated definitely for import into your country - Moldova"
cap label var _10_3482070097 "Stocks held abroad / Closing / designated definitely for import into your country - Montenegro"
cap label var _10_3482070003 "Stocks held abroad / Closing / designated definitely for import into your country - Netherlands"
cap label var _10_3482070801 "Stocks held abroad / Closing / designated definitely for import into your country - New Zealand"
cap label var _10_3482070028 "Stocks held abroad / Closing / designated definitely for import into your country - Norway"
cap label var _10_3482070060 "Stocks held abroad / Closing / designated definitely for import into your country - Poland"
cap label var _10_3482070040 "Stocks held abroad / Closing / designated definitely for import into your country - Portugal"
cap label var _10_3482070066 "Stocks held abroad / Closing / designated definitely for import into your country - Romania"
cap label var _10_3482070057 "Stocks held abroad / Closing / designated definitely for import into your country - Russian Federation"
cap label var _10_3482070050 "Stocks held abroad / Closing / designated definitely for import into your country - Serbia"
cap label var _10_3482070063 "Stocks held abroad / Closing / designated definitely for import into your country - Slovak Republic"
cap label var _10_3482070091 "Stocks held abroad / Closing / designated definitely for import into your country - Slovenia"
cap label var _10_3482070042 "Stocks held abroad / Closing / designated definitely for import into your country - Spain"
cap label var _10_3482070030 "Stocks held abroad / Closing / designated definitely for import into your country - Sweden"
cap label var _10_3482070036 "Stocks held abroad / Closing / designated definitely for import into your country - Switzerland"
cap label var _10_3482070052 "Stocks held abroad / Closing / designated definitely for import into your country - Türkiye"
cap label var _10_3482070058 "Stocks held abroad / Closing / designated definitely for import into your country - Ukraine"
cap label var _10_3482070006 "Stocks held abroad / Closing / designated definitely for import into your country - United Kingdom"
cap label var _10_3482070400 "Stocks held abroad / Closing / designated definitely for import into your country - United States"
cap label var _10_3482070999 "Stocks held abroad / Closing / designated definitely for import into your country - Others"
cap label var _10_3482071000D "Stocks held abroad / Closing / designated definitely for import into your country - Total"
cap label var _10_3482071010D "Stocks held abroad / Closing / designated definitely for import into your country - Total EU MS"
cap label var _10_METHOD "Method for Emergency Stocks held by the MS"
cap label var _10_DAYS "Emergency Stocks held by the MS in accordance with the EU Directive (in Days Equivalent)"
cap label var _10_OBLIGATC "Daily net imports or inland consumption for compliance (calculated)"
cap label var _10_OBMETHC "Method for calculation of obligation (calculated)"
cap label var _10_1281EU99C "Minimum stocklevel  for compliance (calculated)"
