cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var AC0 "Personal care"
cap label var AC000 "Unspecified personal care"
cap label var AC0A "Personal care except eating"
cap label var AC01 "Sleep"
cap label var AC010 "Unspecified sleep"
cap label var AC011 "Sleep"
cap label var AC012 "Sick in bed"
cap label var AC02 "Eating"
cap label var AC021 "Eating"
cap label var AC03 "Other and/or unspecified personal care"
cap label var AC030 "Unspecified other personal care"
cap label var AC031 "Washing and dressing"
cap label var AC039 "Other specified personal care"
cap label var AC1 "Employment"
cap label var AC1_2_TR "Work and study"
cap label var AC1_TR "Employment, related activities and travel as part of/during main and second job"
cap label var AC1A "Main and second job and related travel"
cap label var AC1B "Activities related to employment and unspecified employment"
cap label var AC100 "Unspecified employment"
cap label var AC11 "Main job"
cap label var AC111 "Working time in main job"
cap label var AC112 "Coffee and other breaks in main job"
cap label var AC12 "Second job"
cap label var AC121 "Working time in second job"
cap label var AC122 "Coffee and other breaks in second job"
cap label var AC13 "Activities related to employment"
cap label var AC130 "Unspecified activities related to employment"
cap label var AC131 "Lunch break"
cap label var AC139 "Other specified activities related to employment"
cap label var AC2 "Study"
cap label var AC200 "Unspecified study"
cap label var AC21 "School or university"
cap label var AC21A "School and university except homework"
cap label var AC210 "Unspecified activities related to school or university"
cap label var AC211 "Classes and lectures"
cap label var AC212 "Homework"
cap label var AC219 "Other specified activities related to school or university"
cap label var AC22 "Free time study"
cap label var AC221 "Free time study"
cap label var AC3_X_38 "Household and family care, except childcare"
cap label var AC3 "Household and family care"
cap label var AC300 "Unspecified household and family care"
cap label var AC3_TR "Household and family care and related travel"
cap label var AC31 "Food management"
cap label var AC31A "Food management except dish washing"
cap label var AC310 "Unspecified food management"
cap label var AC311 "Food preparation"
cap label var AC312 "Baking"
cap label var AC313 "Dish washing"
cap label var AC314 "Preserving"
cap label var AC319 "Other specified food management"
cap label var AC32 "Household upkeep"
cap label var AC32A "Household upkeep except cleaning dwelling"
cap label var AC320 "Unspecified household upkeep"
cap label var AC321 "Cleaning dwelling"
cap label var AC322 "Cleaning yard"
cap label var AC323 "Heating and water"
cap label var AC324 "Various arrangements"
cap label var AC329 "Other specified household upkeep"
cap label var AC33 "Making and care for textiles"
cap label var AC33A "Handicraft and producing textiles and other care for textiles"
cap label var AC330 "Unspecified making and care for textiles"
cap label var AC331 "Laundry"
cap label var AC332 "Ironing"
cap label var AC333 "Handicraft and producing textiles"
cap label var AC339 "Other specified making and care for textiles"
cap label var AC34 "Gardening and pet care"
cap label var AC34A "Gardening; other pet care"
cap label var AC340 "Unspecified gardening and pet care"
cap label var AC341 "Gardening"
cap label var AC342 "Tending domestic animals"
cap label var AC343 "Caring for pets"
cap label var AC344 "Walking the dog"
cap label var AC349 "Other specified gardening and pet care"
cap label var AC35 "Construction and repairs"
cap label var AC350 "Unspecified construction and repairs"
cap label var AC351 "House construction and renovation"
cap label var AC352 "Repairs of dwelling"
cap label var AC353 "Making, repairing and maintaining equipment"
cap label var AC354 "Vehicle maintenance"
cap label var AC359 "Other specified construction and repairs"
cap label var AC36 "Shopping and services"
cap label var AC360 "Unspecified shopping and services"
cap label var AC361 "Shopping"
cap label var AC362 "Commercial and administrative services"
cap label var AC363 "Personal services"
cap label var AC369 "Other specified shopping and services"
cap label var AC37_39 "Household management and help family member"
cap label var AC37 "Household management"
cap label var AC371 "Household management"
cap label var AC38 "Childcare, including teaching, reading and talking with child"
cap label var AC38A "Childcare, except teaching, reading and talking"
cap label var AC38B "Teaching, reading and talking with child"
cap label var AC380 "Unspecified childcare"
cap label var AC381 "Physical care and supervision"
cap label var AC382 "Teaching the child"
cap label var AC383 "Reading, playing and talking with child"
cap label var AC384 "Accompanying child"
cap label var AC389 "Other specified childcare"
cap label var AC39 "Help to an adult family member"
cap label var AC391 "Help to an adult family member"
cap label var AC4_8 "Leisure, social and associative life"
cap label var AC4_8A "Leisure, social and associative life except TV and video"
cap label var AC4 "Volunteer work and meetings"
cap label var AC400 "Unspecified volunteer work and meetings"
cap label var AC41 "Organisational work"
cap label var AC41A "Formal voluntary activities"
cap label var AC410 "Unspecified organisational work"
cap label var AC411 "Work for an organisation"
cap label var AC412 "Volunteer work through an organisation"
cap label var AC419 "Other specified organisational work"
cap label var AC42 "Informal help to other households"
cap label var AC42A "Informal voluntary activities"
cap label var AC420 "Unspecified informal help"
cap label var AC421 "Food management as help"
cap label var AC422 "Household upkeep as help"
cap label var AC423 "Gardening and pet care as help"
cap label var AC424 "Construction and repairs as help"
cap label var AC425 "Shopping and services as help"
cap label var AC426 "Help in employment and farming"
cap label var AC427 "Childcare as help"
cap label var AC428 "Help to an adult of another household"
cap label var AC429 "Other specified informal help"
cap label var AC43 "Participatory activities"
cap label var AC43A "Active citizenship"
cap label var AC430 "Unspecified participatory activities"
cap label var AC431 "Meetings"
cap label var AC432 "Religious activities"
cap label var AC439 "Other specified participatory activities"
cap label var AC5 "Social life and entertainment"
cap label var AC500 "Unspecified social life and entertainment"
cap label var AC51 "Social life"
cap label var AC51A "Visiting and feasts"
cap label var AC51B "Other social life"
cap label var AC510 "Unspecified social life"
cap label var AC511 "Socialising with family"
cap label var AC512 "Visiting and receiving visitors"
cap label var AC513 "Feasts"
cap label var AC514 "Telephone conversation"
cap label var AC519 "Other specified social life"
cap label var AC52 "Entertainment and culture"
cap label var AC52A "Cultural activities (cinema, live performances or cultural sites)"
cap label var AC520 "Unspecified entertainment and culture"
cap label var AC521 "Cinema"
cap label var AC522 "Theatre and concerts"
cap label var AC522A "Live performances (theatre, concerts, ballet)"
cap label var AC523 "Art exhibitions and museums"
cap label var AC523H "Cultural sites (historical monuments, museums, art galleries or archaeological sites)"
cap label var AC524 "Library"
cap label var AC525 "Sports events"
cap label var AC529 "Other specified entertainment and culture"
cap label var AC53 "Resting"
cap label var AC531 "Resting - time out"
cap label var AC6 "Sports and outdoor activities"
cap label var AC6A "Sports and outdoor activities except walking and hiking"
cap label var AC600 "Unspecified sports and outdoor activities"
cap label var AC61 "Physical exercise"
cap label var AC610 "Unspecified physical exercise"
cap label var AC611 "Walking and hiking"
cap label var AC612 "Jogging and running"
cap label var AC613 "Biking, skiing and skating"
cap label var AC614 "Ball games"
cap label var AC615 "Gymnastics"
cap label var AC616 "Fitness"
cap label var AC617 "Water sports"
cap label var AC619 "Other specified physical exercise"
cap label var AC62 "Productive exercise"
cap label var AC620 "Unspecified productive exercise"
cap label var AC621 "Hunting and fishing"
cap label var AC622 "Picking berries, mushrooms and herbs"
cap label var AC629 "Other specified productive exercise"
cap label var AC63 "Sports related activities"
cap label var AC631 "Sports related activities"
cap label var AC7 "Hobbies and games"
cap label var AC7A "Computing"
cap label var AC7B "Hobbies and games except computing and computer games"
cap label var AC700 "Unspecified hobbies and games"
cap label var AC71 "Arts"
cap label var AC710 "Unspecified arts"
cap label var AC711 "Visual arts"
cap label var AC712 "Performing arts"
cap label var AC713 "Literary arts"
cap label var AC719 "Other specified arts"
cap label var AC72 "Hobbies"
cap label var AC720 "Unspecified hobbies"
cap label var AC721 "Collecting"
cap label var AC722 "Computing - programming"
cap label var AC723 "Information by computing"
cap label var AC724 "Communication by computing"
cap label var AC725 "Other computing"
cap label var AC726 "Correspondence"
cap label var AC729 "Other specified hobbies"
cap label var AC73 "Games"
cap label var AC730 "Unspecified games"
cap label var AC731 "Solo games and play"
cap label var AC732 "Parlour games and play"
cap label var AC733 "Computer games"
cap label var AC734 "Gambling"
cap label var AC739 "Other specified games"
cap label var AC8 "Mass media"
cap label var AC800 "Unspecified mass media"
cap label var AC81 "Reading"
cap label var AC810 "Unspecified reading"
cap label var AC811 "Reading, except books"
cap label var AC812 "Reading books"
cap label var AC819 "Other specified reading"
cap label var AC82 "Television and video"
cap label var AC821 "Watching television"
cap label var AC822 "Watching video"
cap label var AC83 "Radio and music"
cap label var AC830 "Unspecified listening to radio and music"
cap label var AC831 "Listening to radio"
cap label var AC832 "Listening to recordings"
cap label var AC4_8NSP "Unspecified leisure"
cap label var AC9 "Travel and unspecified time use"
cap label var AC9A "Travel except travel related to jobs"
cap label var AC9B "Travel related to study"
cap label var AC9C "Travel related to other household purposes"
cap label var AC9D "Travel related to leisure, social and associative life"
cap label var AC9E "Travel to/from work/study"
cap label var AC900 "Unspecified travel purpose"
cap label var AC901 "Travel related to personal care"
cap label var AC911 "Travel as part of/during main job"
cap label var AC912 "Travel as part of/during second job"
cap label var AC913 "Travel to/from work"
cap label var AC921 "Travel to/from school or university"
cap label var AC922 "Travel related to free time study"
cap label var AC931 "Travel related to household care"
cap label var AC936 "Travel related to shopping and services"
cap label var AC938 "Transporting a child"
cap label var AC939 "Transporting an adult family member"
cap label var AC941 "Travel related to organisational work"
cap label var AC942 "Travel related to informal help"
cap label var AC943 "Travel related to participatory activities"
cap label var AC951 "Travel related to social life"
cap label var AC952 "Travel related to entertainment and culture"
cap label var AC961 "Travel related to sports and outdoor activities"
cap label var AC971 "Travel related to hobbies"
cap label var AC981 "Travel related to changing locality"
cap label var AC982 "Driving for pleasure"
cap label var AC995 "Filling in the time use diary"
cap label var AC998 "Unspecified leisure time"
cap label var AC999 "Other unspecified time use"
cap label var AC90NSP "Unspecified travel"
cap label var AC99NSP "Unspecified time use"
cap label var NSP "Unspecified time use and travel"
cap label var AC_PNP_MAIN "Paid and unpaid productive main activities"
cap label var AC_NP_MAIN "Productive unpaid main activities"
cap label var AC_NP_SEC "Productive unpaid secondary activities"
