cap label var CODE "Label - English"
cap label var NR_HH_POP "Number of households in the population"
cap label var PC_POP "Percentage of households in the population"
cap label var PC_HH_POP "Percentage of households in the population"
cap label var NR "Number of households in the sample"
cap label var NR_HH_SPL "Number of households in the sample"
cap label var NR_PER_SPL "Number of persons in the sample"
cap label var PER "Average number of persons in the household"
cap label var AVG_PER "Average number of persons in the household"
cap label var AVG_EMP "Average number of employed persons in the household"
cap label var AVG_UNE "Average number of unemployed persons in the household"
cap label var AVG_RET "Average number of retired persons in the household"
cap label var AVG_YCH "Average number of children under 18 years in the household"
cap label var AVG_DCH "Average number of dependent children in the household"
cap label var AE "Average number of adult equivalents in the household"
cap label var AVG_AE "Average number of adult equivalents in the household"
cap label var PC_HH_DRW_S_BRW_M "Percentage of households needing to draw on savings or to borrow money"
cap label var PC_HH_DEBT_IN "Percentage of households in arrears"
