cap label var CODE "Label - English"
cap label var PEDS "Potential environmentally damaging subsidies"
cap label var PEDS_FF "Potential environmentally damaging subsidies related to fossil fuels"
cap label var PEDS_OTH "Potential environmentally damaging subsidies other than fossil fuels"
cap label var NAP "Not applicable"
