cap label var CODE "Label - English"
cap label var DSL_CON "Direct sale to consumer"
cap label var DSL_CON_ON "Direct sale to consumer - on site farm stores, stands, kiosks, pickups or farm gate"
cap label var DSL_CON_OFF "Direct sale to consumer - off-site farm stores or stands"
cap label var DSL_CON_FRMMKT "Direct sale to consumer - farmer’s markets"
cap label var DSL_CON_DIRDLV "Direct sale to consumer - direct delivery to consumer"
cap label var DSL_CON_CSAFB "Direct sale to consumer - community supported agriculture or food basket"
cap label var DSL_CON_OTH "Direct sale to consumer - other direct sale to consumer"
cap label var SL_PRR "Sale to producer organisation/cooperative"
cap label var SL_RTL "Sale to retailer"
cap label var SL_PRC_FOOD "Sale to food processor"
cap label var SL_WHLS "Sale to wholesaler"
cap label var SL_OTH_FRM "Sale to other farms"
cap label var SL_EXP_INTM "Sale to export intermediaries"
cap label var OTH "Other"
