cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var SLAUGHT_TOT "Slaughterings - total"
cap label var SLAUGHT "Slaughterings"
cap label var SLAUGHT_ORG "Slaughterings - organic"
cap label var SLAUGHT_OTH "Slaughterings, other than in slaughterhouses"
cap label var GIP "Gross indigenous production"
cap label var IMP "Imports"
cap label var IMP_IEU "Intra-EU imports"
cap label var IMP_XEU "Imports extra-EU"
cap label var IMP_THRD "Imports from third countries"
cap label var EXP "Exports"
cap label var EXP_IEU "Export intra-EU"
cap label var EXP_XEU "Exports extra-EU"
cap label var EXP_THRD "Exports to third countries"
cap label var IMP_LANI "Imports of live animals"
cap label var IMP_IEU_LANI "Intra-EU imports of live animals"
cap label var IMP_THRD_LANI "Imports from third countries of live animals"
cap label var EXP_LANI "Exports of live animals"
cap label var EXP_IEU_LANI "Exports intra-EU of live animals"
cap label var EXP_THRD_LANI "Exports to third countries of live animals"
cap label var GP "Gross indigenous production"
