cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var S "Services"
cap label var ISS "International supply of services (ISS)"
cap label var SA "Services: manufacturing services on physical inputs owned by others"
cap label var SB "Services: maintenance and repair services n.i.e."
cap label var SBG "Services: maintenance and repair services n.i.e. (of which goods)"
cap label var SC "Services: transport"
cap label var SC1 "Services: sea transport"
cap label var SC2 "Services: air transport"
cap label var SC3 "Services: other modes of transport"
cap label var SC4 "Services: postal and courier services"
cap label var SCB "Services: all modes of transport; freight"
cap label var SD "Services: travel"
cap label var SDG "Services: travel (of which goods)"
cap label var SE "Services: construction"
cap label var SEG "Services: construction (of which goods)"
cap label var SF "Services: insurance and pension services"
cap label var SG "Services: financial services"
cap label var SH "Services: charges for the use of intellectual property n.i.e."
cap label var SI "Services: telecommunications, computer, and information services"
cap label var SI1 "Services: telecommunications services"
cap label var SI2 "Services: computer services"
cap label var SI3 "Services: information services"
cap label var SJ "Services: other business services"
cap label var SJ1 "Services: research and development services"
cap label var SJ2 "Services: professional and management consulting services"
cap label var SJ21 "Services: legal, accounting, management consulting, and public relations services"
cap label var SJ22 "Services: advertising, market research, and public opinion polling services"
cap label var SJ3 "Services: technical, trade-related, and other business services"
cap label var SJ31 "Services: architectural, engineering, scientific, and other technical services"
cap label var SJ32 "Services: waste treatment and de-pollution, agricultural and mining services"
cap label var SJ33 "Services: operating leasing services"
cap label var SJ34T "Services: total trade related transactions"
cap label var SJ34 "Services: trade-related services"
cap label var SJ34D "Services: distribution services"
cap label var SJ35 "Services: other business services n.i.e."
cap label var SK "Services: personal, cultural, and recreational services"
cap label var SK1 "Services: audiovisual and related services"
cap label var SK2 "Services: personal, cultural, and recreational services other than audiovisual and related services"
cap label var SL "Services: government goods and services n.i.e."
cap label var SLG "Services: government goods and services n.i.e. (of which goods)"
cap label var SN "Services: services not allocated"
