cap label var TOTAL "Total"
cap label var PRECIP "Precipitation"
cap label var EVAP_TSP "Actual evapotranspiration"
cap label var INTFL "Internal Flow"
cap label var INFL_NBT "Actual external inflow from neighbouring territories"
cap label var OUTFL "Total actual outflow"
cap label var OUTFL_SEA "Total actual outflow into the sea"
cap label var OUTFL_NBT "Total actual outflow into neighbouring territories"
cap label var RFW_RES "Renewable freshwater resources"
cap label var AQUI "Recharge into the aquifer"
cap label var GWAA "Groundwater available for annual abstraction"
cap label var FW_95LTAA "Freshwater resources 95% of years, LTAA"
cap label var ABST "Total gross abstraction"
cap label var ABS_PWS "Water abstraction for public water supply"
cap label var ABS_AGR "Water abstraction for agriculture"
cap label var ABS_AGR_IR "Water abstraction for agriculture - irrigation"
cap label var ABS_AGR_AQ "Water abstraction for agriculture - aquaculture"
cap label var ABS_MIN "Water abstraction for mining and quarrying"
cap label var ABS_IND "Water abstraction for manufacturing industry"
cap label var ABS_IND_CL "Water abstraction for manufacturing industry - cooling"
cap label var ABS_ELC_CL "Water abstraction for production of electricity - cooling"
cap label var ABS_CON "Water abstraction for construction"
cap label var ABS_SER "Water abstraction for services"
cap label var ABS_HH "Water abstraction for private households"
cap label var ABS_OTH "Water abstraction for other uses"
cap label var ABS_NET "Water abstraction - net"
cap label var REW "Water returned without use"
cap label var IMP "Imports of water"
cap label var IMP_REG "Water transferred from other regions (imports)"
cap label var EXP "Exports of water"
cap label var EXP_REG "Water transferred to other regions (exports)"
cap label var LOSS "Losses during transport - total"
cap label var LOSS_EVAP "Evaporation losses"
cap label var LOSS_LEAK "Leakage losses"
cap label var LOSS_USE "Losses during use - total"
cap label var AVL_USE "Water available for use"
cap label var WAU "Water available for use"
cap label var WAFU "Water available for final use"
cap label var GEN_HYDRO "Generation of hydroelectricity"
cap label var ART_RES "Artificial reservoirs"
cap label var PWS "Public water supply"
cap label var SOWS "Self and other water supply"
cap label var PWS_SOWS "Public water supply and self and other supply"
cap label var CONS_USE "Consumptive water use"
cap label var CONSUM "Total water consumption"
cap label var POP_PWS "Population connected to public water supply (%)"
cap label var CWD "Total cooling water discharged"
cap label var CWD_IW "Cooling water discharged to inland waters"
cap label var CWD_SEA "Cooling water discharged to marine waters"
cap label var ABS_DSW "Desalinated water abstracted"
cap label var ABS_RUW "Reused water abstracted"
cap label var DIS "Total discharges of wastewater treatment plants (urban and other)"
cap label var DIS_IW "Total discharges to inland waters"
cap label var DIS_SEA "Total discharges to the sea"
cap label var WEI "Water exploitation index"
cap label var VOL_RES "Exploitable volume of reservoirs"
