cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var MT "Means-tested"
cap label var NMT "Non means-tested"
cap label var NAP "Not applicable"
cap label var NON_MEANS "Non means-tested"
cap label var MEANS "Means-tested"
