cap label var CODE "Label - English"
cap label var PROV_CR_MF11_12 "Crop provision - crops, crop residues (used), fodder crops and grazed biomass"
cap label var PROV_CR_MF11 "Crop provision - crops (excluding fodder crops)"
cap label var PROV_CR_MF111 "Crop provision - cereals"
cap label var PROV_CR_MF112 "Crop provision - roots, tubers"
cap label var PROV_CR_MF113 "Crop provision - sugar crops"
cap label var PROV_CR_MF114 "Crop provision - pulses"
cap label var PROV_CR_MF115 "Crop provision - nuts"
cap label var PROV_CR_MF116 "Crop provision - oil-bearing crops"
cap label var PROV_CR_MF117 "Crop provision - vegetables"
cap label var PROV_CR_MF118 "Crop provision - fruits"
cap label var PROV_CR_MF119 "Crop provision - fibres"
cap label var PROV_CR_MF11A "Crop provision - other crops (excluding fodder crops) n.e.c."
cap label var PROV_CR_MF12 "Crop provision - crop residues (used), fodder crops and grazed biomass"
cap label var PROV_CR_MF121 "Crop provision - crop residues (used)"
cap label var PROV_CR_MF1211 "Crop provision - straw"
cap label var PROV_CR_MF1212 "Crop provision - other crop residues (sugar and fodder beet leaves, etc.)"
cap label var PROV_CR_MF122 "Crop provision - fodder crops and grazed biomass"
cap label var PROV_CR_MF1221 "Crop provision - fodder crops (including biomass harvest from grassland)"
cap label var PROV_CR_MF1222 "Crop provision - grazed biomass"
cap label var PROV_POLN_MF11_12 "Provision of crop pollination - crops, crop residues (used), fodder crops and grazed biomass"
cap label var PROV_POLN_MF11 "Provision of crop pollination - crops (excluding fodder crops)"
cap label var PROV_POLN_MF111 "Provision of crop pollination - cereals"
cap label var PROV_POLN_MF112 "Provision of crop pollination - roots, tubers"
cap label var PROV_POLN_MF113 "Provision of crop pollination - sugar crops"
cap label var PROV_POLN_MF114 "Provision of crop pollination - pulses"
cap label var PROV_POLN_MF115 "Provision of crop pollination - nuts"
cap label var PROV_POLN_MF116 "Provision of crop pollination - oil-bearing crops"
cap label var PROV_POLN_MF117 "Provision of crop pollination - vegetables"
cap label var PROV_POLN_MF118 "Provision of crop pollination - fruits"
cap label var PROV_POLN_MF119 "Provision of crop pollination - fibres"
cap label var PROV_POLN_MF11A "Provision of crop pollination - other crops (excluding fodder crops) n.e.c."
cap label var PROV_POLN_MF12 "Provision of crop pollination - crop residues (used), fodder crops and grazed biomass"
cap label var PROV_POLN_MF121 "Provision of crop pollination - crop residues (used)"
cap label var PROV_POLN_MF1211 "Provision of crop pollination - straw"
cap label var PROV_POLN_MF1212 "Provision of crop pollination - other crop residues (sugar and fodder beet leaves, etc.)"
cap label var PROV_POLN_MF122 "Provision of crop pollination - fodder crops and grazed biomass"
cap label var PROV_POLN_MF1221 "Provision of crop pollination - fodder crops (including biomass harvest from grassland)"
cap label var PROV_POLN_MF1222 "Provision of crop pollination - grazed biomass"
cap label var PROV_WD_MF13MEMO "Wood provision - net increment of timber stock (memo item) (increment cultivated)"
cap label var PROV_WD_MF13 "Wood provision - wood (removals non cultivated)"
cap label var REG_AIR_FL_PM10 "Regulation - air filtration - PM10"
cap label var REG_AIR_FL_PM2P5 "Regulation - air filtration - PM2.5"
cap label var REG_CO2_SEQ_NET "Global climate regulation CO2 - net sequestration"
cap label var REG_CO2_SEQ_NET_PRIM "Global climate regulation CO2 - primary net sequestration"
cap label var REG_CO2_STO_CM30 "Global climate regulation CO2 - storage 30 cm"
cap label var REG_CO2_STO_CM100 "Global climate regulation CO2 - storage 100 cm"
cap label var REG_CO2_STO_WHL "Global climate regulation CO2 - storage whole depth"
cap label var REG_CL_RED_DEGC_GT25 "Local climate regulation (cooling) - reduction of temperature on days exceeding 25 degrees"
cap label var CLT_TOUR_NGT_SP "Cultural/outdoor activities - nature-based tourism - nights spent"
cap label var CLT_REC_VIS "Cultural/outdoor activities - nature-based recreation - visits"
cap label var REG_CL_DEGC_GT25 "Local climate regulation (cooling) - days with maximum temperature exceeding 25°C"
cap label var REG_CL_DEGC_GT30 "Local climate regulation (cooling) - days with maximum temperature exceeding 30°C"
cap label var REG_CL_DEGC_GT35 "Local climate regulation (cooling) - days with maximum temperature exceeding 35°C"
cap label var REG_CL_URB_DEGC_GT25 "Local climate regulation (cooling) - urban area with an observed daily maximum temperature exceeding 25°C during the summer"
cap label var REG_CL_URB_DEGC_GT30 "Local climate regulation (cooling) - urban area  with an observed daily maximum temperature exceeding 30°C during the summer"
cap label var REG_CL_URB_DEGC_GT35 "Local climate regulation (cooling) - urban area  with an observed daily maximum temperature exceeding 35°C during the summer"
cap label var REG_CL_BEN_PER "Local climate regulation (cooling) - benefitting persons"
cap label var REG_AIR_FL_BEN_PER "Regulation - air filtration - benefitting persons"
cap label var REG_CO2_EMIS "Global climate regulation CO2 - emissions"
