cap label var CODE "Label - English"
cap label var PTEN "Protein content"
cap label var PTEN_ORG "Protein content - organic"
cap label var PTEN_MC_ORG "Cows' milk protein content - organic"
cap label var PRD "Product obtained"
cap label var PRD_ORG "Product obtained - organic"
cap label var BTE "Butter equivalent"
cap label var FAT "Fat content (t)"
cap label var FAT_ORG "Fat content - organic"
cap label var USM "Utilization of skimmed milk and buttermilk (1 000 t)"
cap label var USM_ORG "Use of skimmed milk - organic"
cap label var UWM "Utilization of whole milk (1 000 t)"
cap label var UWM_ORG "Use of whole milk - organic"
cap label var WPE "Whey powder equivalent"
cap label var FCA "Fat content (% of product weight) (annual)"
cap label var PCA "Protein content (% of product weight) (annual)"
cap label var PRO "Products obtained (1 000 t)"
cap label var PAT "Protein content (t)"
