cap label var CODE "Label - English"
cap label var FIN "Financial situation"
cap label var ACCOM "Accommodation"
cap label var JOB "Job"
cap label var COM "Commuting time"
cap label var TIME "Time use"
cap label var LIFE "Life as a whole"
cap label var REC_GA "Recreational and green areas"
cap label var LIVENV "Living environment"
cap label var PER_RELS "Personal relationships"
cap label var MEANLIFE "Meaning of life"
