cap label var CODE "Label - English"
cap label var ECOCON_01_01A "Green areas in cities and adjacent towns and suburbs (LAU)"
cap label var ECOCON_01_01B "Green areas in settlements and other artificial areas (ECO01)"
cap label var ECOCON_01_01C "Green areas in urban areas as per NRR"
cap label var ECOCON_01_01D "Green areas in urban areas as per NRR limited to ECO01"
cap label var ECOCON_01_01E "Total national area of urban green space (NRR)"
cap label var ECOCON_01_02A "Concentration of PM2.5 in city LAUs"
cap label var ECOCON_02_01A "Cropland SOC - all soils (topsoil 30 cm)"
cap label var ECOCON_02_01B "Cropland SOC - mineral (topsoil 30 cm)"
cap label var ECOCON_02_01C "Cropland SOC - organic (whole depth)"
cap label var ECOCON_02_01C1 "Cropland SOC - organic (soil 100 cm)"
cap label var ECOCON_02_01C2 "Cropland SOC - organic (topsoil 30 cm)"
cap label var ECOCON_03_01A "Grassland SOC - all soils (topsoil 30 cm)"
cap label var ECOCON_03_01B "Grassland SOC - mineral (topsoil 30 cm)"
cap label var ECOCON_03_01C "Grassland SOC - organic (whole depth)"
cap label var ECOCON_03_01C1 "Grassland SOC - organic (soil 100 cm)"
cap label var ECOCON_03_01C2 "Grassland SOC - organic (topsoil 30 cm)"
cap label var ECOCON_02_03_02 "Common farmland bird index"
cap label var ECOCON_04_01 "Common forest bird index"
cap label var ECOCON_04_02A "Deadwood"
cap label var ECOCON_04_02A1 "Deadwood - standing"
cap label var ECOCON_04_02A2 "Deadwood - lying"
cap label var ECOCON_04_03 "Tree cover density"
cap label var ECOCON_11_01 "Artificial impervious cover in coastal zone (1 km)"
