cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var OWN "Own account"
cap label var HIRE "Hire or reward"
cap label var NSP "Not specified"
cap label var NOT_SPEC "Not specified"
cap label var TOT "Total"
