cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var CP01 "Food and non-alcoholic beverages"
cap label var CP011 "Food"
cap label var CP0111 "Cereals and cereal products (ND)"
cap label var CP01111 "Cereals (ND)"
cap label var CP01112 "Flour of cereals (ND)"
cap label var CP01113 "Bread and bakery products (ND)"
cap label var CP01114 "Breakfast cereals (ND)"
cap label var CP01115 "Macaroni, noodles, couscous and similar pasta products (ND)"
cap label var CP01119 "Other milled cereal and grain products (ND)"
cap label var CP0112 "Live animals, and meat and other parts of slaughtered land animals (ND)"
cap label var CP01121 "Live land animals (ND)"
cap label var CP01122 "Meat, fresh, chilled or frozen (ND)"
cap label var CP01123 "Meat, dried, salted, in brine or smoked (ND)"
cap label var CP01124 "Offal, blood and other parts of slaughtered animals, fresh, chilled or frozen, dried, salted, in brine or smoked (ND)"
cap label var CP01125 "Preparations of meat, offal, blood and other parts of slaughtered animals (ND)"
cap label var CP0113 "Fish and other seafood (ND)"
cap label var CP01131 "Fish, live, fresh, chilled or frozen (ND)"
cap label var CP01132 "Fish, dried, salted, in brine or smoked (ND)"
cap label var CP01133 "Fish preparations (ND)"
cap label var CP01134 "Other seafood, live, fresh, chilled or frozen (ND)"
cap label var CP01135 "Other seafood, dried, salted, in brine or smoked (ND)"
cap label var CP01136 "Other seafood preparations (ND)"
cap label var CP01137 "Livers, roes and other offal of fish and of other seafood in all forms (ND)"
cap label var CP0114 "Milk, other dairy products and eggs (ND)"
cap label var CP01141 "Raw and whole milk (ND)"
cap label var CP01142 "Skimmed milk (ND)"
cap label var CP01143 "Other milk and cream (ND)"
cap label var CP01144 "Non-animal milk (ND)"
cap label var CP01145 "Cheese (ND)"
cap label var CP01146 "Yoghurt and similar products (ND)"
cap label var CP01147 "Milk-based dessert and beverages (ND)"
cap label var CP01148 "Eggs (ND)"
cap label var CP01149 "Other dairy products (ND)"
cap label var CP0115 "Oils and fats (ND)"
cap label var CP01151 "Vegetable oils (ND)"
cap label var CP01152 "Butter and other oils and fats derived from milk (ND)"
cap label var CP01153 "Margarine and similar preparations (ND)"
cap label var CP01159 "Other animal oils and fats (ND)"
cap label var CP0116 "Fruits and nuts (ND)"
cap label var CP01161 "Dates, figs and tropical fruits, fresh (ND)"
cap label var CP01162 "Citrus fruits, fresh (ND)"
cap label var CP01163 "Stone fruits and pome fruits, fresh (ND)"
cap label var CP01164 "Berries, fresh (ND)"
cap label var CP01165 "Other fruits, fresh (ND)"
cap label var CP01166 "Fruits, frozen (ND)"
cap label var CP01167 "Fruits, dried and dehydrated (ND)"
cap label var CP01168 "Nuts, in shell or shelled (ND)"
cap label var CP01169 "Fruits and nuts, ground, and in other preparations (ND)"
cap label var CP0117 "Vegetables, tubers, plantains, cooking bananas and pulses (ND)"
cap label var CP01171 "Leafy or stem vegetables, fresh or chilled (ND)"
cap label var CP01172 "Fruit-bearing vegetables, fresh or chilled (ND)"
cap label var CP01173 "Green leguminous vegetables, fresh or chilled (ND)"
cap label var CP01174 "Other vegetables, fresh or chilled (ND)"
cap label var CP01175 "Tubers, plantains and cooking bananas, fresh or chilled (ND)"
cap label var CP01176 "Pulses (ND)"
cap label var CP01177 "Other vegetables, tubers, plantains and cooking bananas, dried and dehydrated (ND)"
cap label var CP01178 "Vegetables, tubers, plantains and cooking bananas, frozen (ND)"
cap label var CP01179 "Vegetables, tubers, plantains, cooking bananas and pulses, ground, and in other preparations (ND)"
cap label var CP0118 "Sugar, confectionery and desserts (ND)"
cap label var CP01181 "Cane sugar and beet sugar (ND)"
cap label var CP01182 "Other sugars and sugar substitutes (ND)"
cap label var CP01183 "Jams, marmalades, fruit jellies, purées and pastes, and honey (ND)"
cap label var CP01184 "Nut purées, nut butters and nut pastes (ND)"
cap label var CP01185 "Chocolate, cocoa and cocoa-based food products (ND)"
cap label var CP01186 "Ice, ice cream and sorbets (ND)"
cap label var CP0119 "Ready-made food and other food products (ND)"
cap label var CP01191 "Ready-made food (ND)"
cap label var CP01192 "Baby food (ND)"
cap label var CP01193 "Salt, condiments and sauces (ND)"
cap label var CP01194 "Spices, culinary herbs and seeds (ND)"
cap label var CP01199 "Other food products n.e.c. (ND)"
cap label var CP012 "Non-alcoholic beverages"
cap label var CP0121 "Fruit and vegetable juices (ND)"
cap label var CP01210 "Fruit and vegetable juices (ND)"
cap label var CP0122 "Coffee and coffee substitutes (ND)"
cap label var CP01220 "Coffee and coffee substitutes (ND)"
cap label var CP0123 "Tea, maté and other plant-derived products for infusion (ND)"
cap label var CP01230 "Tea, maté and other plant-derived products for infusion (ND)"
cap label var CP0124 "Cocoa drinks (ND)"
cap label var CP01240 "Cocoa drinks (ND)"
cap label var CP0125 "Water (ND)"
cap label var CP01250 "Water (ND)"
cap label var CP0126 "Soft drinks (ND)"
cap label var CP01260 "Soft drinks (ND)"
cap label var CP0129 "Other non-alcoholic beverages (ND)"
cap label var CP01290 "Other non-alcoholic beverages (ND)"
cap label var CP013 "Services for processing primary goods for food and non-alcoholic beverages"
cap label var CP0130 "Services for processing primary goods for food and non-alcoholic beverages (S)"
cap label var CP01300 "Services for processing primary goods for food and non-alcoholic beverages (S)"
cap label var CP02 "Alcoholic beverages, tobacco and narcotics"
cap label var CP021 "Alcoholic beverages"
cap label var CP0211 "Spirits and liquors (ND)"
cap label var CP02110 "Spirits and liquors (ND)"
cap label var CP0212 "Wine (ND)"
cap label var CP02121 "Wine from grapes (ND)"
cap label var CP02122 "Wine from other sources (ND)"
cap label var CP0213 "Beer (ND)"
cap label var CP02130 "Beer (ND)"
cap label var CP0219 "Other alcoholic beverages (ND)"
cap label var CP02190 "Other alcoholic beverages (ND)"
cap label var CP022 "Alcohol production services"
cap label var CP0220 "Alcohol production services (S)"
cap label var CP02200 "Alcohol production services (S)"
cap label var CP023 "Tobacco"
cap label var CP0230 "Tobacco (ND)"
cap label var CP02301 "Cigarettes (ND)"
cap label var CP02302 "Cigars (ND)"
cap label var CP02309 "Other tobacco products (ND)"
cap label var CP024 "Narcotics"
cap label var CP0240 "Narcotics (ND)"
cap label var CP02400 "Narcotics (ND)"
cap label var CP03 "Clothing and footwear"
cap label var CP031 "Clothing"
cap label var CP0311 "Clothing materials (SD)"
cap label var CP03110 "Clothing materials (SD)"
cap label var CP0312 "Garments (SD)"
cap label var CP03121 "Garments for men or boys (SD)"
cap label var CP03122 "Garments for women or girls (SD)"
cap label var CP03123 "Garments for infants (under 2 years of age) (SD)"
cap label var CP03124 "School uniforms (SD)"
cap label var CP0313 "Other articles of clothing and clothing accessories (SD)"
cap label var CP03131 "Other articles of clothing (SD)"
cap label var CP03132 "Clothing accessories (SD)"
cap label var CP0314 "Cleaning, repair, tailoring and hire of clothing (S)"
cap label var CP03141 "Cleaning of clothing (S)"
cap label var CP03142 "Repair, tailoring and hire of clothing (S)"
cap label var CP032 "Footwear"
cap label var CP0321 "Shoes and other footwear (SD)"
cap label var CP03211 "Footwear for men (SD)"
cap label var CP03212 "Footwear for women (SD)"
cap label var CP03213 "Footwear for infants and children (SD)"
cap label var CP0322 "Cleaning, repair and hire of footwear (S)"
cap label var CP03220 "Cleaning, repair and hire of footwear (S)"
cap label var CP04 "Housing, water, electricity, gas and other fuels"
cap label var CP041 "Actual rental payments made for housing"
cap label var CP0411 "Actual rental payments made by tenants for main residence (S)"
cap label var CP04110 "Actual rental payments made by tenants for main residence (S)"
cap label var CP0412 "Other actual rental payments (S)"
cap label var CP04121 "Actual rental payments made by tenants for secondary residences (S)"
cap label var CP04122 "Garage rental payments and other rental payments made by tenants (S)"
cap label var CP042 "Imputed rental payments for housing"
cap label var CP0421 "Imputed rental payments of owner-occupiers for their main residence (S)"
cap label var CP04210 "Imputed rental payments of owner-occupiers for their main residence (S)"
cap label var CP0422 "Other imputed rentals (S)"
cap label var CP04220 "Other imputed rentals (S)"
cap label var CP043 "Maintenance, repair and security of the dwelling"
cap label var CP0431 "Security equipment and materials for dwelling maintenance and repair"
cap label var CP04311 "Materials for the maintenance and repair of the dwelling (ND)"
cap label var CP04312 "Security equipment (SD)"
cap label var CP0432 "Services for the maintenance, repair and security of the dwelling (S)"
cap label var CP04320 "Services for the maintenance, repair and security of the dwelling (S)"
cap label var CP044 "Water supply and miscellaneous services relating to the dwelling"
cap label var CP0441 "Water supply (ND)"
cap label var CP04411 "Water supply delivered through network systems (ND)"
cap label var CP04412 "Water supply delivered through other systems (ND)"
cap label var CP0442 "Refuse collection (S)"
cap label var CP04420 "Refuse collection (S)"
cap label var CP0443 "Sewage collection (S)"
cap label var CP04431 "Sewage collection through sewer systems (S)"
cap label var CP04432 "Sewage collection through on-site sanitation systems (S)"
cap label var CP0444 "Other services related to the dwelling (S)"
cap label var CP04441 "Charges for maintenance of multi-occupied buildings (S)"
cap label var CP04449 "Other services related to the dwelling n.e.c. (S)"
cap label var CP045 "Electricity, gas and other fuels"
cap label var CP0451 "Electricity (ND)"
cap label var CP04510 "Electricity (ND)"
cap label var CP0452 "Gas (ND)"
cap label var CP04521 "Natural gas through networks (ND)"
cap label var CP04522 "Liquefied hydrocarbons (ND)"
cap label var CP0453 "Liquid fuels (ND)"
cap label var CP04530 "Liquid fuels (ND)"
cap label var CP0454 "Solid fuels (ND)"
cap label var CP04541 "Coal, coal briquettes, peat and peat briquettes (ND)"
cap label var CP04542 "Wood fuel, including pellets and briquettes (ND)"
cap label var CP04543 "Charcoal (ND)"
cap label var CP04549 "Other solid fuels (ND)"
cap label var CP0455 "Other energy for heating and cooling (ND)"
cap label var CP04550 "Other energy for heating and cooling (ND)"
cap label var CP05 "Furnishings, household equipment and routine household maintenance"
cap label var CP051 "Furniture, furnishings, and loose carpets"
cap label var CP0511 "Furniture, furnishings and loose carpets (D)"
cap label var CP05111 "Household furniture (D)"
cap label var CP05112 "Garden and camping furniture (D)"
cap label var CP05113 "Lighting equipment (D)"
cap label var CP05114 "Furnishings, loose carpets and rugs (D)"
cap label var CP0512 "Repair, installation and hire of furniture, furnishings and loose carpets (S)"
cap label var CP05120 "Repair, installation and hire of furniture, furnishings and loose carpets (S)"
cap label var CP052 "Household textiles"
cap label var CP0521 "Household textiles (SD)"
cap label var CP05211 "Furnishing fabrics and curtains (SD)"
cap label var CP05212 "Bed linen and bedding (SD)"
cap label var CP05213 "Table linen and bathroom linen (SD)"
cap label var CP05219 "Other household textiles (SD)"
cap label var CP0522 "Repair, hire and sewing services of household textiles (S)"
cap label var CP05220 "Repair, hire and sewing services of household textiles (S)"
cap label var CP053 "Household appliances"
cap label var CP0531 "Major electric and other household appliances (D)"
cap label var CP05311 "Major kitchen appliances (D)"
cap label var CP05312 "Major laundry appliances (D)"
cap label var CP05313 "Heaters and air conditioners (D)"
cap label var CP05314 "Cleaning equipment (D)"
cap label var CP05319 "Other major household appliances (D)"
cap label var CP0532 "Small household appliances (SD)"
cap label var CP05321 "Small appliances for the cooking and processing of food (SD)"
cap label var CP05322 "Small appliances for the preparation of beverages (SD)"
cap label var CP05329 "Other small household appliances (SD)"
cap label var CP0533 "Repair, installation and hire of household appliances (S)"
cap label var CP05330 "Repair, installation and hire of household appliances (S)"
cap label var CP054 "Glassware, tableware and household utensils"
cap label var CP0540 "Glassware, tableware and household utensils (SD)"
cap label var CP05401 "Glassware, crystal ware, ceramic ware and china ware (SD)"
cap label var CP05402 "Cutlery, flatware and silverware (SD)"
cap label var CP05403 "Kitchen utensils and articles (SD)"
cap label var CP05404 "Repair and hire of glassware, tableware and household utensils (S)"
cap label var CP055 "Tools and equipment for house and garden"
cap label var CP0551 "Motorized tools and equipment (D)"
cap label var CP05510 "Motorized tools and equipment (D)"
cap label var CP0552 "Non-motorized tools and miscellaneous accessories (SD)"
cap label var CP05521 "Non-motorized tools (SD)"
cap label var CP05522 "Miscellaneous accessories (SD)"
cap label var CP0553 "Repair and hire of motorized and non-motorized tools and equipment (S)"
cap label var CP05530 "Repair and hire of motorized and non-motorized tools and equipment (S)"
cap label var CP056 "Goods and services for routine household maintenance"
cap label var CP0561 "Non-durable household goods (ND)"
cap label var CP05611 "Household cleaning and maintenance products (ND)"
cap label var CP05619 "Other non-durable household goods (ND)"
cap label var CP0562 "Domestic services and household services (S)"
cap label var CP05621 "Domestic services provided by paid staff (S)"
cap label var CP05629 "Other household services (S)"
cap label var CP06 "Health"
cap label var CP061 "Medicines and health products"
cap label var CP0611 "Medicines (ND)"
cap label var CP06111 "Medicines, vaccines and other pharmaceutical preparations (ND)"
cap label var CP0612 "Medical products (ND)"
cap label var CP06121 "Medical diagnostic products (ND)"
cap label var CP06122 "Preventive and protective devices (ND)"
cap label var CP06123 "Treatment devices for personal use (ND)"
cap label var CP0613 "Assistive products (D)"
cap label var CP06131 "Assistive products for vision (D)"
cap label var CP06133 "Assistive products for mobility and daily living (D)"
cap label var CP06132 "Assistive products for hearing and communication (D)"
cap label var CP0614 "Repair, rental and maintenance of medical and assistive products (S)"
cap label var CP06140 "Repair, rental and maintenance of medical and assistive products (S)"
cap label var CP062 "Outpatient care services"
cap label var CP0621 "Preventive care services (S)"
cap label var CP06211 "Immunization services (S)"
cap label var CP06219 "Other preventive care services (S)"
cap label var CP0622 "Outpatient dental services (S)"
cap label var CP06221 "Dental preventive services (S)"
cap label var CP06229 "Other outpatient dental services (S)"
cap label var CP0623 "Other outpatient care services (S)"
cap label var CP06231 "Outpatient curative and rehabilitative services (S)"
cap label var CP06232 "Outpatient long-term care services (S)"
cap label var CP063 "Inpatient care services"
cap label var CP0631 "Inpatient curative and rehabilitative services (S)"
cap label var CP06310 "Inpatient curative and rehabilitative services (S)"
cap label var CP0632 "Inpatient long-term care services (S)"
cap label var CP06320 "Inpatient long-term care services (S)"
cap label var CP064 "Other health services"
cap label var CP0641 "Diagnostic imaging services and medical laboratory services (S)"
cap label var CP06410 "Diagnostic imaging services and medical laboratory services (S)"
cap label var CP0642 "Patient emergency transportation and emergency rescue services (S)"
cap label var CP06420 "Patient emergency transportation and emergency rescue services (S)"
cap label var CP07 "Transport"
cap label var CP071 "Purchase of vehicles"
cap label var CP0711 "Motor cars (D)"
cap label var CP07111 "New motor cars (D)"
cap label var CP07112 "Second-hand motor cars (D)"
cap label var CP0712 "Motorcycles (D)"
cap label var CP07120 "Motorcycles (D)"
cap label var CP0713 "Bicycles (D)"
cap label var CP07130 "Bicycles (D)"
cap label var CP0714 "Animal-drawn vehicles (D)"
cap label var CP07140 "Animal-drawn vehicles (D)"
cap label var CP072 "Operation of personal transport equipment"
cap label var CP0721 "Parts and accessories for personal transport equipment (SD)"
cap label var CP07211 "Tyres (SD)"
cap label var CP07212 "Parts for personal transport equipment (SD)"
cap label var CP07213 "Accessories for personal transport equipment (SD)"
cap label var CP0722 "Fuels and lubricants for personal transport equipment (ND)"
cap label var CP07221 "Diesel (ND)"
cap label var CP07222 "Petrol (ND)"
cap label var CP07223 "Other fuels for personal transport equipment (ND)"
cap label var CP07224 "Lubricants (ND)"
cap label var CP0723 "Maintenance and repair of personal transport equipment (S)"
cap label var CP07230 "Maintenance and repair of personal transport equipment (S)"
cap label var CP0724 "Other services related to personal transport equipment (S)"
cap label var CP07241 "Parking services (S)"
cap label var CP07242 "Toll facilities (S)"
cap label var CP07243 "Driving lessons, tests, licences and roadworthiness tests (S)"
cap label var CP07244 "Hire of personal transport equipment without driver (S)"
cap label var CP073 "Passenger transport services"
cap label var CP0731 "Passenger transport by railway (S)"
cap label var CP07311 "Passenger transport by train (S)"
cap label var CP07312 "Passenger transport by rapid transit and tram (S)"
cap label var CP0732 "Passenger transport by road (S)"
cap label var CP07321 "Passenger transport by bus and coach (S)"
cap label var CP07322 "Passenger transport by taxi and hired vehicle with driver (S)"
cap label var CP07323 "Passenger transport for students to and from school (S)"
cap label var CP07329 "Other passenger transport by road (S)"
cap label var CP0733 "Passenger transport by air (S)"
cap label var CP07331 "Passenger transport by air, domestic (S)"
cap label var CP07332 "Passenger transport by air, international (S)"
cap label var CP0734 "Passenger transport by sea and inland waterway (S)"
cap label var CP07340 "Passenger transport by sea and inland waterway (S)"
cap label var CP0735 "Combined passenger transport (S)"
cap label var CP07350 "Combined passenger transport (S)"
cap label var CP0736 "Other passenger transport services (S)"
cap label var CP07360 "Other passenger transport services (S)"
cap label var CP074 "Transport services for goods"
cap label var CP0741 "Postal and courier services (S)"
cap label var CP07411 "Letter handling services (S)"
cap label var CP07412 "Courier and parcel delivery services (S)"
cap label var CP0749 "Other transport of goods (S)"
cap label var CP07491 "Removal and storage services (S)"
cap label var CP07492 "Delivery of goods (S)"
cap label var CP08 "Information and communication"
cap label var CP081 "Information and communication equipment"
cap label var CP0811 "Fixed telephone equipment (D)"
cap label var CP08110 "Fixed telephone equipment (D)"
cap label var CP0812 "Mobile telephone equipment (D)"
cap label var CP08120 "Mobile telephone equipment (D)"
cap label var CP0813 "Information processing equipment (D)"
cap label var CP08131 "Computers, laptops and tablets (D)"
cap label var CP08132 "Peripheral equipment and its consumable components (D)"
cap label var CP0814 "Equipment for the reception, recording and reproduction of sound and vision (D)"
cap label var CP08140 "Equipment for the reception, recording and reproduction of sound and vision (D)"
cap label var CP0815 "Unrecorded recording media (SD)"
cap label var CP08150 "Unrecorded recording media (SD)"
cap label var CP0819 "Other information and communication equipment and accessories (D)"
cap label var CP08191 "Other information and communication equipment (D)"
cap label var CP08192 "Other information and communication accessories (SD)"
cap label var CP082 "Software, excluding games"
cap label var CP0820 "Software, excluding games (S)"
cap label var CP08200 "Software, excluding games (S)"
cap label var CP083 "Information and communication services"
cap label var CP0831 "Fixed communication services (S)"
cap label var CP08310 "Fixed communication services (S)"
cap label var CP0832 "Mobile communication services (S)"
cap label var CP08320 "Mobile communication services (S)"
cap label var CP0833 "Internet access provision services and online storage services (S)"
cap label var CP08330 "Internet access provision services and online storage services (S)"
cap label var CP0834 "Bundled telecommunication services (S)"
cap label var CP08340 "Bundled telecommunication services (S)"
cap label var CP0835 "Repair and rental of information and communication equipment (S)"
cap label var CP08350 "Repair and rental of information and communication equipment (S)"
cap label var CP0839 "Other information and communication services (S)"
cap label var CP08391 "Television and radio licences and fees (S)"
cap label var CP08392 "Subscriptions to audiovisual streaming services and rental of audiovisual content (S)"
cap label var CP08399 "Other information and communication services n.e.c. (S)"
cap label var CP09 "Recreation, sport and culture"
cap label var CP091 "Recreational durables"
cap label var CP0911 "Photographic and cinematographic equipment and optical instruments (D)"
cap label var CP09111 "Cameras (D)"
cap label var CP09112 "Accessories for photographic and cinematographic equipment (D)"
cap label var CP09113 "Optical instruments (D)"
cap label var CP0912 "Major recreational durables (D)"
cap label var CP09121 "Camper vans, caravans and trailers (D)"
cap label var CP09122 "Aeroplanes, microlight aircraft, gliders, hang gliders and hot-air balloons (D)"
cap label var CP09123 "Boats, yachts, outboard motors and other water-sport equipment (D)"
cap label var CP09124 "Horses, ponies, camels and dromedaries and accessories (D)"
cap label var CP09129 "Other major recreational durables (D)"
cap label var CP092 "Other recreational goods"
cap label var CP0921 "Games, toys and hobby-related articles (SD)"
cap label var CP09211 "Video game computers, consoles, game applications and software (SD)"
cap label var CP09212 "Other games, toys and hobby-related articles (SD)"
cap label var CP09213 "Celebration articles (ND)"
cap label var CP0922 "Sporting, camping and open-air recreation equipment (SD)"
cap label var CP09221 "Sporting equipment (SD)"
cap label var CP09222 "Camping and open-air recreation equipment (SD)"
cap label var CP093 "Garden products and pets"
cap label var CP0931 "Garden products, plants and flowers (ND)"
cap label var CP09311 "Garden products (ND)"
cap label var CP09312 "Plants, seeds and flowers (ND)"
cap label var CP0932 "Pets and pet products (D)"
cap label var CP09321 "Pets (D)"
cap label var CP09322 "Products for pets and other household animals (ND)"
cap label var CP094 "Recreational services"
cap label var CP0941 "Hire and repair of photographic and cinematographic equipment and optical instruments (S)"
cap label var CP09410 "Hire and repair of photographic and cinematographic equipment and optical instruments (S)"
cap label var CP0942 "Hire, maintenance and repair of major recreational durables (S)"
cap label var CP09421 "Hire, maintenance and repair of camper vans and caravans (S)"
cap label var CP09422 "Hire, maintenance and repair of other major recreational durables (S)"
cap label var CP0943 "Hire and repair of games, toys and hobby-related articles (S)"
cap label var CP09431 "Hire of game software and subscription to online games (S)"
cap label var CP09432 "Hire and repair of other games, toys and hobby-related articles (S)"
cap label var CP0944 "Hire and repair of sporting, camping and open-air recreational equipment (S)"
cap label var CP09440 "Hire and repair of sporting, camping and open-air recreational equipment (S)"
cap label var CP0945 "Veterinary and other services for pets (S)"
cap label var CP09450 "Veterinary and other services for pets (S)"
cap label var CP0946 "Recreational and sporting services (S)"
cap label var CP09461 "Recreational and leisure services (S)"
cap label var CP09462 "Services associated with the practice of sports (S)"
cap label var CP09463 "Services associated with attendance at sporting events (S)"
cap label var CP0947 "Games of chance (S)"
cap label var CP09470 "Games of chance (S)"
cap label var CP095 "Cultural goods"
cap label var CP0951 "Musical instruments (D)"
cap label var CP09510 "Musical instruments (D)"
cap label var CP0952 "Audiovisual media (SD)"
cap label var CP09520 "Audiovisual media (SD)"
cap label var CP096 "Cultural services"
cap label var CP0961 "Services provided by cinemas, theatres and concert venues (S)"
cap label var CP09610 "Services provided by cinemas, theatres and concert venues (S)"
cap label var CP0962 "Services provided by museums, libraries and cultural sites (S)"
cap label var CP09620 "Services provided by museums, libraries and cultural sites (S)"
cap label var CP0963 "Photographic services (S)"
cap label var CP09630 "Photographic services (S)"
cap label var CP0969 "Other cultural services (S)"
cap label var CP09690 "Other cultural services (S)"
cap label var CP097 "Newspapers, books and stationery"
cap label var CP0971 "Books (SD)"
cap label var CP09711 "Educational books and textbooks (SD)"
cap label var CP09719 "Other books (SD)"
cap label var CP0972 "Newspapers and periodicals (ND)"
cap label var CP09721 "Newspapers (ND)"
cap label var CP09722 "Magazines and periodicals (ND)"
cap label var CP0973 "Miscellaneous printed matter (ND)"
cap label var CP09730 "Miscellaneous printed matter (ND)"
cap label var CP0974 "Stationery and drawing materials (ND)"
cap label var CP09740 "Stationery and drawing materials (ND)"
cap label var CP098 "Package holidays"
cap label var CP0980 "Package holidays (S)"
cap label var CP09800 "Package holidays (S)"
cap label var CP10 "Education services"
cap label var CP101 "Early childhood and primary education"
cap label var CP1010 "Early childhood and primary education (S)"
cap label var CP10101 "Early childhood education (S)"
cap label var CP10102 "Primary education (S)"
cap label var CP102 "Secondary education"
cap label var CP1020 "Secondary education (S)"
cap label var CP10200 "Secondary education (S)"
cap label var CP103 "Post-secondary non-tertiary education"
cap label var CP1030 "Post-secondary non-tertiary education (S)"
cap label var CP10300 "Post-secondary non-tertiary education (S)"
cap label var CP104 "Tertiary education"
cap label var CP1040 "Tertiary education (S)"
cap label var CP10400 "Tertiary education (S)"
cap label var CP105 "Education not defined by level"
cap label var CP1050 "Education not defined by level (S)"
cap label var CP10501 "Tutoring (S)"
cap label var CP10509 "Other education not defined by level (S)"
cap label var CP11 "Restaurants and accommodation services"
cap label var CP111 "Food and beverage serving services"
cap label var CP1111 "Restaurants, cafés and the like (S)"
cap label var CP11111 "Restaurants, cafés and the like – with full service (S)"
cap label var CP11112 "Restaurants, cafés and the like – with limited service (S)"
cap label var CP1112 "Canteens, cafeterias and refectories (S)"
cap label var CP11121 "Canteens and cafeterias of universities, schools and kindergartens (S)"
cap label var CP11129 "Other canteens, cafeterias and refectories (S)"
cap label var CP112 "Accommodation services"
cap label var CP1120 "Accommodation services (S)"
cap label var CP11201 "Hotels, motels, inns and similar accommodation services (S)"
cap label var CP11202 "Holiday centres, camping sites, youth hostels and similar accommodation services (S)"
cap label var CP11203 "Accommodation services of boarding schools, universities and other educational establishments (S)"
cap label var CP11209 "Other accommodation services (S)"
cap label var CP12 "Insurance and financial services"
cap label var CP121 "Insurance"
cap label var CP1211 "Life and accident insurance (S)"
cap label var CP12110 "Life and accident insurance (S)"
cap label var CP1212 "Insurance connected with health (S)"
cap label var CP12120 "Insurance connected with health (S)"
cap label var CP1213 "Insurance connected with dwellings (S)"
cap label var CP12130 "Insurance connected with dwellings (S)"
cap label var CP1214 "Insurance connected with transport (S)"
cap label var CP12141 "Personal transport insurance (S)"
cap label var CP12142 "Travel insurance (S)"
cap label var CP1219 "Other insurance (S)"
cap label var CP12190 "Other insurance (S)"
cap label var CP122 "Financial services"
cap label var CP1221 "Financial intermediation services indirectly measured (S)"
cap label var CP12210 "Financial intermediation services indirectly measured (S)"
cap label var CP1222 "Explicit charges by deposit-taking corporations (S)"
cap label var CP12220 "Explicit charges by deposit-taking corporations (S)"
cap label var CP1229 "Other financial services (S)"
cap label var CP12291 "Remittances fees (S)"
cap label var CP12299 "Other financial services n.e.c. (S)"
cap label var CP13 "Personal care, social protection and miscellaneous goods and services"
cap label var CP131 "Personal care"
cap label var CP1311 "Electric appliances for personal care (SD)"
cap label var CP13111 "Purchase of electric appliances for personal care (SD)"
cap label var CP13112 "Repair of electric appliances for personal care (S)"
cap label var CP1312 "Other appliances, articles and products for personal care (ND)"
cap label var CP13120 "Other appliances, articles and products for personal care (ND)"
cap label var CP1313 "Hairdressing salons and personal grooming establishments (S)"
cap label var CP13131 "Hairdressing (S)"
cap label var CP13132 "Personal grooming treatments (S)"
cap label var CP132 "Other personal effects"
cap label var CP1321 "Jewellery and watches (D)"
cap label var CP13211 "Purchase of jewellery and watches (D)"
cap label var CP13212 "Repair and hire of jewellery, clocks and watches (S)"
cap label var CP1322 "Devotional articles and articles for religious and ritual celebrations (SD)"
cap label var CP13220 "Devotional articles and articles for religious and ritual celebrations (SD)"
cap label var CP1329 "Other personal effects n.e.c. (SD)"
cap label var CP13291 "Travel goods, baby articles and other personal effects n.e.c. (SD)"
cap label var CP13292 "Repair and hire of other personal effects (S)"
cap label var CP133 "Social protection"
cap label var CP1330 "Social protection (S)"
cap label var CP13301 "Childcare services (S)"
cap label var CP13302 "Retirement homes for elderly persons and residences for disabled persons, not providing medical care (S)"
cap label var CP13303 "Home care services for elderly and disabled (S)"
cap label var CP13309 "Other social protection services (S)"
cap label var CP139 "Other services"
cap label var CP1390 "Other services (S)"
cap label var CP13901 "Prostitution (S)"
cap label var CP13902 "Religious services (S)"
cap label var CP13909 "Other services n.e.c. (S)"
