cap label var TOTAL "Total"
cap label var ANY_MNY "Any monetary income"
cap label var WORK "Income from work"
cap label var WORK_WAGE "Wages and salaries"
cap label var WORK_SELF "Self-employment income"
cap label var PRIV "Private sources"
cap label var PRIV_CAP "Capital income"
cap label var PRIV_RENT "Property/rental income"
cap label var PRIV_TRF "Private transfers"
cap label var SOC_TRF "Social transfers"
cap label var SOC_RET "Old-age/survivors pensions"
cap label var SOC_NRET "Social transfers - other than old-age/survivors pensions"
cap label var SOC_UNE "Unemployment related transfers"
cap label var SOC_FAM "Family related transfers"
cap label var SOC_SICK "Sickness/invalidity related transfers"
cap label var SOC_EDUC "Education related transfers"
cap label var SOC_ASS "Social assistance"
cap label var SOC_HOUS "Housing allowance"
cap label var SOC_OTH "Other social transfers, n.e.s."
cap label var SOC_NRUS "Social transfers other than old-age/survivors pensions and unemployment, sickness/invalidity related benefits"
cap label var PRIMARY "Primary income"
cap label var SECONDARY "Secondary income"
cap label var UNK "Unknown"
