cap label var CODE "Label - English"
cap label var _10_196102 "Closing stocks"
cap label var B_195500 "Demand"
cap label var B_190100 "Primary production"
cap label var B_190300 "Imports"
cap label var B_190400 "Stock Changes"
cap label var B_190500 "Exports"
cap label var B_190600 "Net Imports"
cap label var B_190900 "Supply"
cap label var B_191008 "Refinery intake"
cap label var B_191108 "Refinery output"
cap label var B_197000 "Total gross production"
cap label var MSHH "Medium size households"
cap label var MSIND "Non-household, medium size consumers"
cap label var HDD "Heating degree days"
cap label var CDD "Cooling degree days"
cap label var CMPY_NR "Reporting companies - number"
cap label var COMP_NR "Number of reporting companies"
cap label var API_DEG "API Gravity - degree"
cap label var SULPH_PC "Sulphur content - percentage (%)"
cap label var VOL_THS_BBL "Volume - thousand barrels"
cap label var VAL_THS_USD "Value - thousand USD"
cap label var AVGPRC_USD_BBL "Average price - USD per barrel"
cap label var AVGPRC_USD_T "Average price - USD per tonne"
cap label var WT_THS_T "Weight - thousand tonnes"
