cap label var CODE "Label - English"
cap label var FARM_NR "Farm - number"
cap label var UAA_HA "Utilised agricultural area - hectare"
cap label var FA_HA "Farm area - hectare"
cap label var FAXSAA_HA "Farm area excluding special agricultural production areas - hectare"
cap label var FARM_NR_LS "Farms with livestock - number"
cap label var FARM_LSU_LS "Farms with livestock - live stock unit"
cap label var SO_EUR "Standard output - euro"
cap label var LF_D_AWU "Labour force directly employed - annual working unit"
cap label var FARM_NR_PD_GT50 "Farms whose household consumes more than 50% of the final production - number"
cap label var HRI1 "Harmonised risk indicator 1"
cap label var HRI2 "Harmonised risk indicator 2"
cap label var I_NUT "Nutrient inputs"
cap label var I_FER "Total consumption of fertilisers (except manure)"
cap label var I_FER_MIN "Consumption of mineral fertilisers"
cap label var I_FER_ORG "Consumption of organic fertilisers (except manure)"
cap label var I_FER_ORG_SS "Consumption of organic fertilisers (except manure) - sewage sludge"
cap label var I_FER_ORG_UC "Consumption of organic fertilisers (except manure) - urban compost"
cap label var I_FER_ORG_IW "Consumption of organic fertilisers (except manure) - industrial waste products"
cap label var I_FER_ORG_OTH "Consumption of organic fertilisers (except manure) - other products"
cap label var I_MNR "Manure input"
cap label var I_MNR_IMP_LQ_SL "Import of liquid manure/slurry from the farm"
cap label var I_MNR_IMP_SO "Import of solid manure from the farm"
cap label var I_MNR_WDR "Manure withdrawals"
cap label var I_MNR_WDR_NAU "Manure withdrawals - non-agricultural use"
cap label var I_MNR_WDR_IW "Manure withdrawals - processed as industrial waste"
cap label var I_MNR_WDR_ELM "Manure withdrawals - exported livestock manure"
cap label var I_MNR_WDR_OTH "Manure withdrawals - other"
cap label var I_MNR_IMP "Manure imports"
cap label var I_NUT_OTH "Other nutrient inputs"
cap label var I_NUT_OTH_BFN "Other nutrient inputs - biological fixation of nitrogen"
cap label var I_NUT_OTH_AD "Other nutrient inputs - atmospheric deposition"
cap label var I_NUT_OTH_SPM "Other nutrient inputs - seeds and planting material"
cap label var O_NUT "Nutrient outputs"
cap label var O_HVT_CF "Nutrient removal by harvest of crops and forage"
cap label var O_RES_RMOV "Nutrient removal by crop residues removed from the field"
cap label var O_RES_RMOV_HLS "Nutrient removal by crop residues removed from the field - head leaves and stems"
cap label var O_RES_RMOV_STW "Nutrient removal by crop residues removed from the field - straw"
cap label var O_RES_RMOV_OTH "Nutrient removal by crop residues removed from the field - other"
cap label var O_RES_BRN "Nutrient removal by crop residues burned on the field"
cap label var MNR_EXP_LQ_SL "Export of liquid manure / slurry from the farm"
cap label var MNR_EXP_SO "Export of solid manure from the farm"
