cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var PRD "Production (volume)"
cap label var VOL_SLS "Volume of sales"
cap label var NETTUR "Net turnover"
cap label var NETTUR_DOM "Domestic net turnover"
cap label var NETTUR_NDOM "Non-domestic net turnover"
cap label var NETTUR_NDOM_EU "Non-domestic net turnover - euro area"
cap label var NETTUR_NDOM_NEU "Non-domestic net turnover - non-euro area"
cap label var EMP "Persons employed"
cap label var HW "Hours worked by employees"
cap label var WAGE "Wages and salaries"
cap label var PRC_IMP "Import prices"
cap label var PRC_IMP_EU "Import prices - euro area"
cap label var PRC_IMP_NEU "Import prices - non-euro area"
cap label var PRC_PRR_DOM "Domestic producer prices"
cap label var PRC_PRR_NDOM "Non-domestic producer prices"
cap label var PRC_PRR_NDOM_EU "Non-domestic producer prices - euro area"
cap label var PRC_PRR_NDOM_NEU "Non-domestic producer prices - non-euro area"
cap label var PRC_PRR "Producer prices"
cap label var PRC_PRR_B2B "Producer prices - business-to business"
cap label var COST "Costs"
cap label var FIN_SIT "Financial situation of the business"
cap label var FIN_COS "Cost (interest and other) of obtaining finance"
cap label var FIN_DEB "Debt/turnover ratio of business"
cap label var FIN_OTH "Other terms or conditions of finance"
cap label var FIN_BUR "Burden or effort of obtaining finance"
cap label var FIN_WIL "Willingness of banks to provide finance"
cap label var OTH "Other reason(s)"
cap label var REG "Registrations"
cap label var BKRT "Bankruptcy declarations"
cap label var BPRM_DW "Building permits - number of dwellings"
cap label var BPRM_SQM "Building permits - m2 of useful floor area"
