cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var LFOE "Late foetal mortality"
cap label var ENEO "Early neonatal mortality"
cap label var NEO "Neonatal mortality"
cap label var PERI "Perinatal mortality"
cap label var INF "Infant mortality"
cap label var PRVT "Preventable mortality"
cap label var TRT "Treatable mortality"
