cap label var CODE "Label - English"
cap label var COM "COM"
cap label var EE_DVC "EE_DVC"
cap label var FAM "FAM"
cap label var LIB "LIB"
cap label var MUS "MUS"
cap label var PRM "PRM"
cap label var TOTAL "TOTAL"
cap label var TV "TV"
