cap label var CODE "Label - English"
cap label var ARA "Arable land"
cap label var ARAXTIL "Arable land excluding tillage"
cap label var TIL_CV "Conventional tillage"
cap label var TIL_CSERV "Conservational tillage"
cap label var TIL_ZERO "Zero tillage"
