cap label var _1 "Food and beverages"
cap label var _11 "Food and beverages / Primary"
cap label var _111 "Food and beverages / Primary / Mainly for industry"
cap label var _112 "Food and beverages / Primary / Mainly for household consumption"
cap label var _12 "Food and beverages / Processed"
cap label var _121 "Food and beverages / Processed / Mainly for industry"
cap label var _122 "Food and beverages / Processed / Mainly for household consumption"
cap label var _2 "Industrial supplies not elsewhere specified"
cap label var _21 "Industrial supplies not elsewhere specified / Primary"
cap label var _210 "Industrial supplies not elsewhere specified / Primary"
cap label var _22 "Industrial supplies not elsewhere specified / Processed"
cap label var _220 "Industrial supplies not elsewhere specified / Processed"
cap label var _3 "Fuels and lubricants"
cap label var _31 "Fuels and lubricants / Primary"
cap label var _310 "Fuels and lubricants / Primary"
cap label var _32 "Fuels and lubricants / Processed"
cap label var _321 "Fuels and lubricants / Processed / Motor spirit"
cap label var _322 "Fuels and lubricants / Processed / Other"
cap label var _4 "Capital goods (except transport equipment) and parts and accessories thereof"
cap label var _41 "Capital goods (except transport equipment)"
cap label var _410 "Capital goods (except transport equipment)"
cap label var _42 "Capital goods / Parts and accessories"
cap label var _420 "Capital goods / Parts and accessories"
cap label var _5 "Transport equipment and parts and accessories thereof"
cap label var _51 "Transport equipment and parts and accessories thereof / Passenger motor cars"
cap label var _510 "Transport equipment and parts and accessories thereof / Passenger motor cars"
cap label var _52 "Transport equipment and parts and accessories thereof / Other"
cap label var _521 "Transport equipment and parts and accessories thereof / Other / Industrial"
cap label var _522 "Transport equipment and parts and accessories thereof / Other / Non-industrial"
cap label var _53 "Transport equipment and parts and accessories thereof / Parts and accessories"
cap label var _530 "Transport equipment and parts and accessories thereof / Parts and accessories"
cap label var _6 "Consumer goods not elsewhere specified"
cap label var _61 "Consumer goods not elsewhere specified / Durable"
cap label var _610 "Consumer goods not elsewhere specified / Durable"
cap label var _62 "Consumer goods not elsewhere specified / Semi-durable"
cap label var _620 "Consumer goods not elsewhere specified / Semi-durable"
cap label var _63 "Consumer goods not elsewhere specified / Non-durable"
cap label var _630 "Consumer goods not elsewhere specified / Non-durable"
cap label var _7 "Goods not elsewhere specified"
cap label var _70 "Goods not elsewhere specified"
cap label var _700 "Goods not elsewhere specified"
cap label var CAPGOOD "Capital goods"
cap label var CONGOOD "Consumer goods"
cap label var CONTRAN "Consumption goods, including passenger motor cars"
cap label var INTGOOD "Intermediate goods, excluding motor spirit"
cap label var TOTAL "Total"
cap label var XXX "Parts of confidential trade, of trade broken down at chapter level only and of trade under the declaration limit, not elsewhere classified"
