cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var ED_MATCH "Educational attainment level matches job requirements"
cap label var ED_HGR "Educational attainment level higher than job requirements"
cap label var ED_LWR "Educational attainment level lower than job requirements"
cap label var SKIL_MATCH "Skills match job requirements"
cap label var SKIL_HGR "Skills higher than job requirements"
cap label var SKIL_LWR "Skills lower than job requirements"
cap label var NAP "Not applicable"
cap label var NRP "No response"
