cap label var CODE "Label - English"
cap label var CH "Chicks hatched"
cap label var CU "Chicks for use"
cap label var CU_F "Chicks for use - female"
cap label var CP "Chicks placed"
cap label var EPI "Eggs placed in incubation"
cap label var EXP "Exports"
cap label var EXP_IEU "Exports intra-EU"
cap label var EXP_XEU "Exports extra-EU"
cap label var IMP "Imports"
cap label var IMP_IEU "Imports intra-EU"
cap label var IMP_XEU "Imports extra-EU"
