cap label var TOTAL "Total"
cap label var CONT_ORD "Content and order of tasks"
cap label var ORD_CONT "Order and content"
cap label var CONT "Content"
cap label var ORD "Order"
cap label var SOMECONT_SOMEORD "Some or large on content and order of tasks"
cap label var SM_LORD_SM_LCONT "Some or large on order and content"
cap label var LTLCONT_SOMEORD "Little or none on content and some or large on order of tasks"
cap label var SM_LORD_LTL_NONECONT "Some or large on order and little or none on content"
cap label var SOMECONT_LTLORD "Some or large on content and little or none on order of tasks"
cap label var LTL_NONEORD_SM_LCONT "Little or none on order and some or large on content"
cap label var LTLCONT_LTLORD "Little or none on content and order of tasks"
cap label var LTL_NONEORD_LCONT "Little or none on order and large on content"
cap label var LORD_LCONT "Large on order and content"
cap label var LORD_SMCONT "Large on order and some on content"
cap label var LORD_LTL_NONECONT "Large on order and little or none on content"
cap label var SMORD_LCONT "Some on order and large on content"
cap label var AMOST_SMORD_SMCONT "At most some on order and content"
cap label var SMORD_SMCONT "Some on order and content"
cap label var SMORD_LTL_NONECONT "Some on order and little or none on content"
cap label var LTL_NONEORD_SMCONT "Little or none on order and some on content"
cap label var LTL_NONEORD_LTL_NONECONT "Little or none on order and content"
cap label var L_VL_ORD_CONT "Large or very large on order or content"
cap label var L_VLORD_L_VLCONT "Large or very large on order and content"
cap label var L_VLORD_SMCONT "Large or very large on order and some on content"
cap label var L_VLORD_LTL_NONECONT "Large or very large on order and little or none on content"
cap label var SMORD_L_VLCONT "Some on order and large or very large on content"
cap label var LTL_NONEORD_L_VLCONT "Little or none on order and large or very large on content"
cap label var NONE "None"
cap label var NAP "Not applicable"
cap label var NRP "No response"
