cap label var CODE "Label - English"
cap label var b "break in time series"
cap label var bd "break in time series, definition differs (see metadata)"
cap label var bde "break in time series, definition differs (see metadata), estimated"
cap label var bdep "break in time series, definition differs (see metadata), estimated, provisional"
cap label var bdf "break in time series, definition differs (see metadata), forecast"
cap label var bdn "break in time series, definition differs (see metadata), not significant"
cap label var bdp "break in time series, definition differs (see metadata), provisional"
cap label var bdu "break in time series, definition differs (see metadata), low reliability"
cap label var be "break in time series, estimated"
cap label var bep "break in time series, estimated, provisional"
cap label var bf "break in time series, forecast"
cap label var bn "break in time series, not significant"
cap label var bp "break in time series, provisional"
cap label var bpu "break in time series, provisional, low reliability"
cap label var bu "break in time series, low reliability"
cap label var bz "break in time series, not applicable"
cap label var d "definition differs (see metadata)"
cap label var de "definition differs (see metadata), estimated"
cap label var dep "definition differs (see metadata), estimated, provisional"
cap label var df "definition differs (see metadata), forecast"
cap label var dn "definition differs (see metadata), not significant"
cap label var dp "definition differs (see metadata), provisional"
cap label var dpu "definition differs (see metadata), provisional, low reliability"
cap label var du "definition differs (see metadata), low reliability"
cap label var e "estimated"
cap label var ep "estimated, provisional"
cap label var f "forecast"
cap label var n "not significant"
cap label var p "provisional"
cap label var pu "provisional, low reliability"
cap label var u "low reliability"
cap label var bdip "break in time series, definition differs (see metadata), value imputed by Eurostat or other receiving agencies, provisional"
cap label var bdi "break in time series, definition differs (see metadata), value imputed by Eurostat or other receiving agencies"
cap label var bdm "break in time series, definition differs (see metadata), missing value; data cannot exist"
cap label var bip "break in time series, value imputed by Eurostat or other receiving agencies, provisional"
cap label var bi "break in time series, value imputed by Eurostat or other receiving agencies"
cap label var bm "break in time series, missing value; data cannot exist"
cap label var dip "definition differs (see metadata), value imputed by Eurostat or other receiving agencies, provisional"
cap label var di "definition differs (see metadata), value imputed by Eurostat or other receiving agencies"
cap label var dm "definition differs (see metadata), missing value; data cannot exist"
cap label var ip "value imputed by Eurostat or other receiving agencies, provisional"
cap label var i "value imputed by Eurostat or other receiving agencies"
cap label var m "missing value; data cannot exist"
