cap label var AD "ANDORRA"
cap label var AE "UNITED ARAB EMIRATES"
cap label var AF "AFGHANISTAN"
cap label var AG "ANTIGUA and BARBUDA"
cap label var AI "ANGUILLA"
cap label var AL "ALBANIA"
cap label var AM "ARMENIA(1993-2500);ARMENIA(1992-1992)"
cap label var AN "NL ANTILLES(incl. ARUBA->1986)(1987-2012);NL ANTILLES(incl. ARUBA->1986)(1976-1986)"
cap label var AO "ANGOLA"
cap label var AQ "ANTARCTICA"
cap label var AR "ARGENTINA"
cap label var AS "AMERICAN SAMOA"
cap label var AT "AUSTRIA"
cap label var AU "AUSTRALIA"
cap label var AW "ARUBA"
cap label var AZ "AZERBAIJAN(1993-2500);AZERBAIJAN(1992-1992)"
cap label var BA "BOSNIA and HERZEGOVINA(1993-2500);BOSNIA and HERZEGOVINA(1992-1992)"
cap label var BB "BARBADOS"
cap label var BD "BANGLADESH"
cap label var BE "BELGIUM(1999-2500);BELGIUM (and LUXBG -> 1998)(1976-1998)"
cap label var BF "BURKINA FASO (UPPER VOLTA->85)"
cap label var BG "BULGARIA"
cap label var BH "BAHRAIN"
cap label var BI "BURUNDI"
cap label var BJ "BENIN (DAHOMEY -> 1976)"
cap label var BL "ST. BARTHELEMY"
cap label var BM "BERMUDA"
cap label var BN "BRUNEI DARUSSALAM"
cap label var BO "BOLIVIA"
cap label var BQ "BONAIRE, SINT EUSTATIUS AND SABA"
cap label var BR "BRAZIL"
cap label var BS "BAHAMAS"
cap label var BT "BHUTAN"
cap label var BV "BOUVET ISLAND"
cap label var BW "BOTSWANA"
cap label var BY "BELARUS(1993-2500);BELARUS(1992-1992)"
cap label var BZ "BELIZE"
cap label var CA "CANADA"
cap label var CC "COCOS (KEELING), ISLANDS"
cap label var CD "CONGO (DEM. REP.)(ZAIRE->1997)"
cap label var CF "CENTRAL AFRICAN REPUBLIC"
cap label var CG "CONGO"
cap label var CH "SWITZERLAND (incl.LIECHT.->94)(1995-2500);SWITZERLAND (incl.LIECHT.->94)(1976-1994)"
cap label var CI "COTE D IVOIRE"
cap label var CK "COOK ISLANDS"
cap label var CL "CHILE"
cap label var CM "CAMEROON"
cap label var CN "CHINA (PEOPLE'S REPUBLIC OF)"
cap label var CO "COLOMBIA"
cap label var CR "COSTA RICA"
cap label var CS "SERBIA AND MONTENEGRO(2003-2500);CZECHOSLOVAKIA(1976-1992)"
cap label var CU "CUBA"
cap label var CV "CAPE VERDE"
cap label var CW "CURACAO"
cap label var CX "CHRISTMAS ISLAND"
cap label var CY "CYPRUS"
cap label var CZ "CZECHIA"
cap label var DD "GERMANY DEMOCRATIC REPUBLIC"
cap label var DE "GERMANY(1991-2500);GERMANY(1976-1990)"
cap label var DJ "DJIBOUTI (AFARS and ISSAS->77)"
cap label var DK "DENMARK"
cap label var DM "DOMINICA"
cap label var DO "DOMINICAN REPUBLIC"
cap label var DZ "ALGERIA"
cap label var EC "ECUADOR"
cap label var EE "ESTONIA(1993-2500);ESTONIA(1992-1992)"
cap label var EG "EGYPT"
cap label var EH "WESTERN SAHARA(2013-2500);CEUTA & MELLILA,SPANISH SAHARA(1976-1976)"
cap label var ER "ERITREA"
cap label var ES "SPAIN(1997-2500);SPAIN(1986-1996);SPAIN(1976-1985)"
cap label var ET "ETHIOPIA (incl. ERITREA -> 93)(1994-2500);ETHIOPIA (incl. ERITREA -> 93)(1976-1993)"
cap label var FI "FINLAND"
cap label var FJ "FIJI ISLANDS"
cap label var FK "FALKLAND ISLANDS(1992-2500);FALKLAND ISLANDS(1976-1991)"
cap label var FM "MICRONESIA (FEDERATED STAT.OF)"
cap label var FO "FAROE ISLANDS(1993-2500);FAROE ISLANDS(1976-1992)"
cap label var FR "FRANCE(1997-2500);FRANCE(1976-1996)"
cap label var GA "GABON"
cap label var GB "UNITED KINGDOM"
cap label var GD "GRENADA"
cap label var GE "GEORGIA(1993-2500);GEORGIA(1992-1992)"
cap label var GF "FRENCH GUIANA"
cap label var GH "GHANA"
cap label var GI "GIBRALTAR"
cap label var GL "GREENLAND"
cap label var GM "GAMBIA"
cap label var GN "GUINEA"
cap label var GP "GUADELOUPE"
cap label var GQ "EQUATORIAL GUINEA"
cap label var GR "GREECE(1981-2500);GREECE(1976-1980)"
cap label var GS "SOUTH GEORGIA AND S.SANDWICH IS."
cap label var GT "GUATEMALA"
cap label var GU "GUAM"
cap label var GW "GUINEA-BISSAU"
cap label var GY "GUYANA"
cap label var HK "HONG KONG"
cap label var HM "HEARD ISLAND & MCDONALD ISLAN."
cap label var HN "HONDURAS"
cap label var HR "CROATIA(1993-2500);CROATIA(1992-1992)"
cap label var HT "HAITI"
cap label var HU "HUNGARY"
cap label var ID "INDONESIA(2001-2500);INDONESIA (excl. TP -> 1996)(1977-2000);INDONESIA (excl. TP -> 1996)(1976-1976)"
cap label var IE "IRELAND"
cap label var IL "ISRAEL (+GAZA and JERICHO->94)(1995-2500);ISRAEL (+GAZA and JERICHO->94)(1976-1994)"
cap label var IN "INDIA"
cap label var IO "BRITISH INDIAN OCEAN TERRITORY"
cap label var IQ "IRAQ"
cap label var IR "IRAN (ISLAMIC REPUBLIC OF)"
cap label var IS "ICELAND"
cap label var IT "ITALY(1994-2500);ITALY(1976-1993)"
cap label var JM "JAMAICA"
cap label var JO "JORDAN"
cap label var JP "JAPAN"
cap label var KE "KENYA"
cap label var KG "KYRGYZ, REPUBLIC (ex KYRGYZSTAN ->2005)(1993-2500);KYRGYZSTAN(1992-1992)"
cap label var KH "CAMBODIA (FORMER KAMPUCHEA)"
cap label var KI "KIRIBATI(+PN->80);(->79:BR.O.)(1981-2500);KIRIBATI(+PN->80);(->79:BR.O.)(1980-1980);KIRIBATI(+PN->80);(->79:BR.O.)(1976-1979)"
cap label var KM "COMOROS (incl. MAYOTTE -> 76)(1977-2500);COMOROS (incl. MAYOTTE -> 76)(1976-1976)"
cap label var KN "St KITTS and NEVIS"
cap label var KP "KOREA(DEMOCR.PEOPLE'S REPU.OF)"
cap label var KR "KOREA (REPUBLIC OF)"
cap label var KW "KUWAIT"
cap label var KY "CAYMAN ISLANDS"
cap label var KZ "KAZAKHSTAN(1993-2500);KAZAKHSTAN(1992-1992)"
cap label var LA "LAO (PEOPLE'S DEMOCRATIC)"
cap label var LB "LEBANON"
cap label var LC "St LUCIA"
cap label var LI "LIECHTENSTEIN"
cap label var LK "SRI LANKA"
cap label var LR "LIBERIA"
cap label var LS "LESOTHO"
cap label var LT "LITHUANIA(1993-2500);LITHUANIA(1992-1992)"
cap label var LU "LUXEMBOURG"
cap label var LV "LATVIA(1993-2500);LATVIA(1992-1992)"
cap label var LY "SOC.P. LIBYAN ARAB JAMAHIRIYA"
cap label var MA "MOROCCO"
cap label var MD "MOLDOVA (REPUBLIC OF)(1993-2500);MOLDOVA (REPUBLIC OF)(1992-1992)"
cap label var ME "MONTENEGRO (since 2007)"
cap label var MG "MADAGASCAR"
cap label var MH "MARSHALL ISLANDS"
cap label var MK "NORTH MACEDONIA"
cap label var ML "MALI"
cap label var MM "MYANMAR"
cap label var MN "MONGOLIA"
cap label var MO "MACAO"
cap label var MP "NORTHERN MARIANA ISLANDS"
cap label var MQ "MARTINIQUE"
cap label var MR "MAURITANIA(incl.Sp SAH.from77)(1977-2500);MAURITANIA(incl.Sp SAH.from77)(1976-1976)"
cap label var MS "MONTSERRAT"
cap label var MT "MALTA"
cap label var MU "MAURITIUS"
cap label var MV "MALDIVES"
cap label var MW "MALAWI"
cap label var MX "MEXICO"
cap label var MY "MALAYSIA"
cap label var MZ "MOZAMBIQUE"
cap label var NA "NAMIBIA"
cap label var NC "NEW CALEDONIA"
cap label var NE "NIGER"
cap label var NF "NORFOLK ISLAND"
cap label var NG "NIGERIA"
cap label var NI "NICARAGUA"
cap label var NL "NETHERLANDS"
cap label var NO "NORWAY(incl.SJ excl.1995,1996)(1997-2500);NORWAY(incl.SJ excl.1995,1996)(1995-1996);NORWAY(incl.SJ excl.1995,1996)(1976-1994)"
cap label var NP "NEPAL"
cap label var NR "NAURU"
cap label var NU "NIUE"
cap label var NZ "NEW ZEALAND"
cap label var OM "OMAN"
cap label var PA "PANAMA (excl. CANAL -> 80)(1981-2500);PANAMA (excl. CANAL -> 80)(1976-1980)"
cap label var PE "PERU"
cap label var PF "FRENCH POLYNESIA"
cap label var PG "PAPUA NEW GUINEA"
cap label var PH "PHILIPPINES"
cap label var PK "PAKISTAN"
cap label var PL "POLAND"
cap label var PM "SAINT PIERRE and MIQUELON"
cap label var PN "PITCAIRN"
cap label var PS "OCCUPIED PALESTINIAN TERRITORY"
cap label var PT "PORTUGAL(1986-2500);PORTUGAL(1976-1985)"
cap label var PW "PALAU"
cap label var PY "PARAGUAY"
cap label var PZ "PANAMA CANAL"
cap label var QA "QATAR"
cap label var QP "HIGH SEAS"
cap label var QQ "STORES and PROVISIONS(1999-2500);STORES and PROVISIONS(1976-1992)"
cap label var QR "STORES and PROVISIONS INTRA(1999-2500);STORES and PROVISIONS INTRA(1993-1998)"
cap label var QS "STORES and PROVISIONS EXTRA(1999-2500);STORES and PROVISIONS EXTRA(1993-1998)"
cap label var QT "W.INDIES(+DM,LC,VC->79,AG->82)(1986-1986);W.INDIES(+DM,LC,VC->79,AG->82)(1983-1985);W.INDIES(+DM,LC,VC->79,AG->82)(1980-1982);W.INDIES(+DM,LC,VC->79,AG->82)(1976-1979)"
cap label var QU "COUNTRIES and TERRIT. NOT DET.(1993-2500);COUNTRIES and TERRIT. NOT DET.(1976-1992)"
cap label var QV "COUNTRIESandTERR.NOT DET.INTRA"
cap label var QW "COUNTRIESandTERR.NOT DET.EXTRA"
cap label var QX "SEC. COUNTRIES"
cap label var QY "SECRET COUNTRIES INTRA(1994-2500);SECRET COUNTRIES INTRA(1976-1993)"
cap label var QZ "SECRET COUNTRIES EXTRA(1994-2500);SECRET COUNTRIES EXTRA(1976-1993)"
cap label var RE "REUNION"
cap label var RO "ROMANIA"
cap label var RU "RUSSIAN FEDERATION(1993-2500);RUSSIAN FEDERATION(1992-1992)"
cap label var RW "RWANDA"
cap label var SA "SAUDI ARABIA"
cap label var SB "SOLOMON ISLANDS"
cap label var SC "SEYCHELLES"
cap label var SD "SUDAN"
cap label var SE "SWEDEN"
cap label var SG "SINGAPORE"
cap label var SH "SAINT HELENA"
cap label var SI "SLOVENIA(1993-2500);SLOVENIA(1992-1992)"
cap label var SJ "SVALBARD"
cap label var SK "SLOVAKIA"
cap label var SL "SIERRA LEONE"
cap label var SM "SAN MARINO"
cap label var SN "SENEGAL"
cap label var SO "SOMALIA"
cap label var SR "SURINAME"
cap label var SS "SOUTH SOUDAN"
cap label var ST "SAO TOME and PRINCIPE"
cap label var SU "SOVIET UNION(1992-1992);SOVIET UNION(1976-1991)"
cap label var SV "EL SALVADOR"
cap label var SX "SINT MARTEEN"
cap label var SY "SYRIAN ARAB REPUBLIC"
cap label var SZ "ESWATINI"
cap label var TC "TURKS and CAICOS ISLANDS"
cap label var TD "CHAD"
cap label var TF "FRENCH SOUTHERN TERRITORIES"
cap label var TG "TOGO"
cap label var TH "THAILAND"
cap label var TJ "TAJIKISTAN(1993-2500);TAJIKISTAN(1992-1992)"
cap label var TK "TOKELAU"
cap label var TL "TIMOR-LESTE"
cap label var TM "TURKMENISTAN(1993-2500);TURKMENISTAN(1992-1992)"
cap label var TN "TUNISIA"
cap label var TO "TONGA"
cap label var TP "EAST TIMOR(2001-2002);PORTUGESE TIMOR(1976-1976)"
cap label var TR "TÜRKIYE"
cap label var TT "TRINIDAD and TOBAGO"
cap label var TV "TUVALU"
cap label var TW "TAIWAN"
cap label var TZ "TANZANIA (UNITED REPUBLIC OF)"
cap label var UA "UKRAINE(1993-2500);UKRAINE(1992-1992)"
cap label var UG "UGANDA"
cap label var UM "US MINOR OUTLYING ISLANDS"
cap label var US "UNITED STATES(1995-2500);UNITED STATES(1976-1994)"
cap label var UY "URUGUAY"
cap label var UZ "UZBEKISTAN(1993-2500);UZBEKISTAN(1992-1992)"
cap label var VA "HOLY SEE (VATICAN CITY STATE ->2005)"
cap label var VC "St VINCENT and GRENADINES"
cap label var VD "NORTH  VIETNAM"
cap label var VE "VENEZUELA"
cap label var VG "BRIT.VIRGIN ISL.(+MONTSE.->94)(1995-2500);BRIT.VIRGIN ISL.(+MONTSE.->94)(1987-1994)"
cap label var VI "US VIRGIN ISLANDS"
cap label var VN "VIETNAM (excl. NORTH -> 1976)(1977-2500);VIETNAM (excl. NORTH -> 1976)(1976-1976)"
cap label var VU "VANUATU (NEW HEBRIDES -> 1980)"
cap label var WF "WALLIS and FUTUNA"
cap label var WS "SAMOA"
cap label var XA "AMER.OCEANIA(incl. FM,MH ->91)(1995-2000);AMER.OCEANIA(incl. FM,MH ->91)(1994-1994);AMER.OCEANIA(incl. FM,MH ->91)(1992-1993);AMER.OCEANIA(incl. FM,MH ->91)(1976-1991)"
cap label var XB "CANARY ISLANDS(1986-1996);CANARY ISLANDS(1976-1985)"
cap label var XC "CEUTA (incl. MELILLA -> 1998)(1999-2500);CEUTA (incl. MELILLA -> 1998)(1986-1998);CEUTA (incl. MELILLA -> 1998)(1977-1985)"
cap label var XK "KOSOVO"
cap label var XL "MELILLA"
cap label var XM "MONTENEGRO (2005-2006)"
cap label var XO "AUSTRALIAN OCEANIA"
cap label var XP "WEST BANK and GAZA STRIP"
cap label var XR "POLAR REGIONS(1992-2000);POLAR REGIONS(1976-1991)"
cap label var XS "SERBIA"
cap label var XZ "NEW ZEALAND OCEANIA"
cap label var YD "SOUTH YEMEN"
cap label var YE "YEMEN (excl. SOUTH -> 1990)(1991-2500);YEMEN (excl. SOUTH -> 1990)(1976-1990)"
cap label var YT "MAYOTTE"
cap label var YU "YUGOSL.(incl. SI,HR,BA ->1991)(1993-2003);YUGOSL.(incl. SI,HR,BA ->1991)(1992-1992);YUGOSL.(incl. SI,HR,BA ->1991)(1976-1991)"
cap label var ZA "SOUTH AFRICA (incl. NA -> 89)(1990-2500);SOUTH AFRICA (incl. NA -> 89)(1976-1989)"
cap label var ZM "ZAMBIA"
cap label var ZW "ZIMBABWE (RHODESIA -> 1980)"
cap label var ZZ "No data, work code"
