cap label var CODE "Label - English"
cap label var TOT_GD "All goods"
cap label var TOT_GD_X_CRM "All goods other than critical raw materials"
cap label var TOT_CRM "All critical raw materials"
cap label var BAUX "Bauxite"
cap label var SB "Antimony"
cap label var AS "Arsenic"
cap label var BRT "Baryte"
cap label var BE "Beryllium"
cap label var BI "Bismuth"
cap label var BOR "Boron/Borate"
cap label var CO "Cobalt"
cap label var COCO "Coking Coal"
cap label var FSP "Feldspar"
cap label var FL "Fluorspar"
cap label var GA "Gallium"
cap label var GE "Germanium"
cap label var HF "Hafnium"
cap label var HE "Helium"
cap label var HVY_RAR "Heavy rare earth elements"
cap label var LI "Lithium"
cap label var LGHT_RAR "Light rare earth elements"
cap label var MG "Magnesium"
cap label var MN "Manganese"
cap label var GR "Natural graphite"
cap label var NB "Niobium"
cap label var PT "Platinum group metals"
cap label var PHOR "Phosphate rock"
cap label var CU "Copper"
cap label var P "Phosphorus"
cap label var SC "Scandium"
cap label var SIME "Silicon metal"
cap label var SR "Strontium"
cap label var TA "Tantalum"
cap label var TI "Titanium metal"
cap label var W "Tungsten"
cap label var V "Vanadium"
cap label var NI "Nickel"
cap label var TOT_GD_X_NZIG "All goods other than net-zero industry goods"
cap label var TOT_NZIG "All net-zero industry goods"
cap label var SOL "Solar technologies (including PV, solar thermal electric and solar thermal technologies)"
cap label var ON_WND_OFF_REN "Onshore wind and offshore renewable technologies"
cap label var BA_NRG_ST "Battery and energy storage technologies"
cap label var HEP_GTH "Heat pumps and geothermal energy technologies"
cap label var HYD "Hydrogen technologies (including electrolysers and fuel cells)"
cap label var BIOG_BIOM_S "Sustainable biogas and biomethane technologies"
cap label var CCS "Carbon capture and storage (CCS) technologies"
cap label var ELC_G "Electricity grid technologies (including electric charging technologies for transport and technologies to digitalise the grid)"
cap label var NUC_FIS "Nuclear fission energy technologies (including nuclear fuel cycle technologies)"
cap label var FUEL_ALT "Sustainable alternative fuels technologies"
cap label var HYDPOW "Hydropower technologies"
cap label var REN_NRG_NSP "Renewable energy technologies (not elsewhere specified)"
cap label var NRG_EFCY "Energy system-related energy efficiency technologies (including heat grid technologies)"
cap label var REN_FUEL_NBIO "Renewable fuels of non-biological origin technologies"
cap label var BIOT_NRG "Biotech climate and energy solutions"
cap label var TRS_DECARB_NSP "Transformative industrial technologies for decarbonisation (not elsewhere specified)"
cap label var TRA_UTL_CO2 "CO2 transport and utilisation technologies"
cap label var WNDP_ELCP_TRA "Wind propulsion and electric propulsion technologies for transport"
cap label var NUC_NSP "Nuclear technologies (not elsewhere specified)"
cap label var _0000 "All products"
cap label var _2000 "Solid fuels"
cap label var _2111 "Hard coal"
cap label var _2112 "Patent fuels"
cap label var _2121 "Coke oven coke"
cap label var _2210 "Lignite/brown coal"
cap label var _2230 "BKB (brown coal briquettes)"
cap label var _2310 "Peat"
cap label var _2410 "Oil shale and oil sands"
cap label var _3000 "Total petroleum products"
cap label var _3000A "Total crude oil and petroleum products (blended with bio components)"
cap label var _3100A "Crude oil, NGLs, feedstocks, additives/oxygenates and other hydrocarbons (blended with bio components)"
cap label var _3105 "Crude oil (without NGL)"
cap label var _3106 "Natural gas liquids (NGL)"
cap label var _3191 "Refinery feedstocks"
cap label var _3192A "Additives/oxygenates (blended with bio components)"
cap label var _3193 "Other hydrocarbons"
cap label var _3196 "Of which: biofuels (3192A)"
cap label var _3200 "All petroleum products"
cap label var _3200A "Total products (blended with bio components)"
cap label var _3214 "Refinery gas"
cap label var _3215 "Ethane"
cap label var _3220 "Liquified petroleum gas (LPG)"
cap label var _3230 "Motor spirit"
cap label var _3234 "Gasoline (without bio components)"
cap label var _3234A "Total motor gasoline (blended with bio components)"
cap label var _3235 "Aviation gasoline"
cap label var _3240 "Kerosenes - jet fuels"
cap label var _3244 "Other kerosene"
cap label var _3246 "Gasoline type jet fuel"
cap label var _3247 "Kerosene type jet fuel (without bio components)"
cap label var _3247A "Total kerosene type jet fuel (blended with bio components)"
cap label var _3250 "Naphtha"
cap label var _3260 "Gas/diesel oil (without bio components)"
cap label var _3260A "Total gas/diesel oil (blended with bio components)"
cap label var _3265A "Road diesel (blended with bio components)"
cap label var _3266 "Heating and other gas oil (blended with bio components)"
cap label var _3270A "Total fuel oil"
cap label var _3271 "Fuel oil-low sulphur (<1%)"
cap label var _3272 "Fuel oil-high sulphur (>=1%)"
cap label var _3285 "Petroleum coke"
cap label var _3290 "Other products"
cap label var _4000 "Gas"
cap label var _4100 "Natural gas"
cap label var _4101 "Of which: LNG"
cap label var _5500 "Renewable energies"
cap label var _5510 "Hydro power"
cap label var _5546O "Biogasoline"
cap label var _5547O "Biodiesels"
cap label var _5549O "Bio jet kerosene"
cap label var _6000 "Electrical energy"
cap label var _010000 "Cereals (including seeds)"
cap label var _011000 "Wheat and spelt"
cap label var _011100 "Common wheat and spelt"
cap label var _011200 "Durum wheat"
cap label var _012000 "Rye and winter cereal mixtures (meslin)"
cap label var _013000 "Barley"
cap label var _013100 "Fodder barley"
cap label var _013200 "Malting barley"
cap label var _014000 "Oats and summer cereal mixtures"
cap label var _015000 "Grain maize"
cap label var _016000 "Rice"
cap label var _019000 "Other cereals"
cap label var _020000 "Industrial crops"
cap label var _021000 "Oilseeds and oleaginous fruits (including seeds)"
cap label var _021100 "Rape and turnip rape seed"
cap label var _021200 "Sunflower"
cap label var _021300 "Soya"
cap label var _021900 "Other oleaginous products"
cap label var _022000 "Protein crops (including seeds)"
cap label var _023000 "Raw tobacco"
cap label var _024000 "Sugar beet"
cap label var _029000 "Other industrial crops"
cap label var _029100 "Fibre crops"
cap label var _029200 "Hops"
cap label var _029900 "Other industrial crops - others"
cap label var _030000 "Forage plants"
cap label var _031000 "Fodder maize"
cap label var _032000 "Fodder root crops (including forage beet)"
cap label var _033000 "Green maize"
cap label var _039000 "Other forage plants"
cap label var _039100 "Hay"
cap label var _039200 "Straw"
cap label var _039300 "Silage"
cap label var _039900 "Other forage plants - others"
cap label var _040000 "Vegetables and horticultural products"
cap label var _041000 "Fresh vegetables (including melons)"
cap label var _041100 "Cauliflower"
cap label var _041200 "Tomatoes"
cap label var _041900 "Other fresh vegetables"
cap label var _041910 "Cabbage"
cap label var _041920 "Lettuce"
cap label var _041930 "Spinach"
cap label var _041940 "Cucumbers"
cap label var _041950 "Carrots"
cap label var _041960 "Onions"
cap label var _041970 "Fresh beans"
cap label var _041980 "Fresh pulses"
cap label var _041990 "Fresh peas"
cap label var _041999 "Other fresh vegetables - other"
cap label var _042000 "Plants and flowers"
cap label var _050000 "Potatoes (including seeds)"
cap label var _051000 "Potatoes for consumption"
cap label var _051100 "Early potatoes"
cap label var _051200 "Main crop potatoes"
cap label var _052000 "Seed potatoes"
cap label var _059000 "Other potatoes"
cap label var _060000 "Fruit"
cap label var _061000 "Fresh fruit"
cap label var _061100 "Apples for fresh consumption"
cap label var _061200 "Pears for fresh consumption"
cap label var _061300 "Peaches"
cap label var _061900 "Other fresh fruit"
cap label var _061910 "Cherries"
cap label var _061920 "Plums"
cap label var _061930 "Strawberries"
cap label var _061940 "Nuts and dried fruit"
cap label var _061941 "Nuts"
cap label var _061942 "Dried fruit"
cap label var _061990 "Other fresh fruit - other"
cap label var _062000 "Citrus fruit"
cap label var _062100 "Sweet oranges"
cap label var _062200 "Mandarins"
cap label var _062300 "Lemons and acid limes"
cap label var _062900 "Other citrus fruit"
cap label var _063000 "Fruits from subtropical and tropical climate zones"
cap label var _064000 "Grapes"
cap label var _064100 "Grapes for table use"
cap label var _064900 "Other grapes, fresh"
cap label var _065000 "Olives"
cap label var _065100 "Olives for table use"
cap label var _065900 "Other olives"
cap label var _070000 "Wine"
cap label var _071000 "Table wine"
cap label var _071100 "Vin de pays or Vinho regional or Vino de la tierra"
cap label var _071900 "Other table wine"
cap label var _072000 "Quality wine"
cap label var _073000 "PDO and PGI"
cap label var _073100 "PDO"
cap label var _073200 "PGI"
cap label var _078000 "Other wines than PDO and PGI"
cap label var _079000 "Other wine"
cap label var _080000 "Olive oil"
cap label var _090000 "Other crop products"
cap label var _091000 "Vegetative materials used primarily for plaiting"
cap label var _092000 "Seeds"
cap label var _099000 "Other crop products - others"
cap label var _100000 "Total crop, including fruit  and vegetables"
cap label var _101000 "Total crop, excluding fruit  and vegetables"
cap label var _110000 "Animals"
cap label var _111000 "Live cattle"
cap label var _111100 "Cattle excluding calves"
cap label var _111200 "Calves"
cap label var _112000 "Live pigs"
cap label var _113000 "Live horses, asses, mules and hinnies"
cap label var _114000 "Live sheep and goats"
cap label var _115000 "Live poultry"
cap label var _115100 "Chickens (species)"
cap label var _115900 "Other poultry"
cap label var _119000 "Other animals"
cap label var _120000 "Animal products"
cap label var _121000 "Milk or raw milk"
cap label var _121100 "Raw cows' milk"
cap label var _121900 "Other milk types"
cap label var _122000 "Eggs"
cap label var _129000 "Other animal products"
cap label var _130000 "Total animal"
cap label var _140000 "Total agricultural goods, including fruit and vegetables"
cap label var _141000 "Total agricultural goods, excluding fruit and vegetables"
cap label var _200000 "Goods and services currently consumed in agriculture (Input 1)"
cap label var _201000 "Seeds and planting stock"
cap label var _202000 "Energy; lubricants"
cap label var _202100 "Electricity"
cap label var _202200 "Fuels for heating"
cap label var _202300 "Motor fuels"
cap label var _202400 "Lubricants"
cap label var _202900 "Lubricants and other energy products than electricity, and heating and motor fuels"
cap label var _203000 "Fertilisers and soil improvers"
cap label var _203100 "Straight fertilizers"
cap label var _203110 "Nitrogenous fertilizers"
cap label var _203120 "Phosphatic fertilizers"
cap label var _203130 "Potassic fertilizers"
cap label var _203200 "Compound fertilizers"
cap label var _203210 "NP fertilizers"
cap label var _203220 "PK fertilizers"
cap label var _203230 "NPK fertilizers"
cap label var _203900 "Other fertilizers, soil improvers"
cap label var _204000 "Plant protection products"
cap label var _204100 "Fungicides and bactericides"
cap label var _204200 "Insecticides and acaricides"
cap label var _204300 "Herbicides, haulm destructors and moss killers"
cap label var _204900 "Other plant protection products"
cap label var _205000 "Veterinary expenses"
cap label var _206000 "Animal feedingstuffs"
cap label var _206100 "Straight feedingstuffs"
cap label var _206110 "Cereals and milling by-products"
cap label var _206120 "Oilcakes"
cap label var _206130 "Products of animal origin"
cap label var _206190 "Other straight feeding stuffs"
cap label var _206200 "Compound feedingstuffs"
cap label var _206210 "Compound feedingstuffs for calves"
cap label var _206220 "Compound feedingstuffs for cattle excluding calves"
cap label var _206230 "Compound feedingstuffs for pigs"
cap label var _206240 "Compound feedingstuffs for poultry"
cap label var _206290 "Other compound feedingstuffs"
cap label var _207000 "Maintenance of materials"
cap label var _208000 "Maintenance of buildings"
cap label var _209000 "Other goods and services"
cap label var _210000 "Goods and services contributing to agricultural investment (Input 2)"
cap label var _211000 "Materials"
cap label var _211100 "Machinery and other equipment"
cap label var _211110 "Rotovators and other 2 wheel equipment"
cap label var _211120 "Machinery and equipment  for cultivation"
cap label var _211130 "Machinery and equipment for harvesting"
cap label var _211140 "Farm machinery and installations"
cap label var _211141 "Farm machinery and installations for crop production"
cap label var _211142 "Farm machinery and installations for animal production"
cap label var _211149 "Other farm machinery and installations"
cap label var _211200 "Transport equipment"
cap label var _211210 "Tractors"
cap label var _211290 "Other vehicles"
cap label var _212000 "Buildings"
cap label var _212100 "Farm buildings (non-residential)"
cap label var _212900 "Other works except land improvements (other buildings, structures, etc.)"
cap label var _219000 "Other"
cap label var _220000 "Input total (Input 1 + Input 2)"
