cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var CLSPER "Close person"
cap label var HLTH_SOC "Health or social service"
cap label var SUPP "Support service"
cap label var POLC "Police"
cap label var ANY "Any person or service"
cap label var OFCL_WRK "Official body (support/health/social service or police or officials at work)"
cap label var NOFCL_WRK "Unofficial (colleague, close person or someone else)"
cap label var HLTH_SOC_SUPP_POLC "Health, social or support service or police"
cap label var SUPP_POLC "Support service or police"
cap label var OFCL_SCH "Official body (support/health/social service or police or someone in school)"
cap label var NOFCL_SCH "Unofficial (friends, family member or someone else)"
cap label var SUPP_LEG "Legal or victim support service"
