cap label var CODE "Label - English"
cap label var EU27_2020 "European Union - 27 countries (from 2020)"
cap label var EA20 "Euro area – 20 countries (from 2023)"
cap label var BE "Belgium"
cap label var BG "Bulgaria"
cap label var CZ "Czechia"
cap label var DK "Denmark"
cap label var DE "Germany"
cap label var EE "Estonia"
cap label var IE "Ireland"
cap label var EL "Greece"
cap label var ES "Spain"
cap label var FR "France"
cap label var HR "Croatia"
cap label var IT "Italy"
cap label var CY "Cyprus"
cap label var LV "Latvia"
cap label var LT "Lithuania"
cap label var LU "Luxembourg"
cap label var HU "Hungary"
cap label var MT "Malta"
cap label var NL "Netherlands"
cap label var AT "Austria"
cap label var PL "Poland"
cap label var PT "Portugal"
cap label var RO "Romania"
cap label var SI "Slovenia"
cap label var SK "Slovakia"
cap label var FI "Finland"
cap label var SE "Sweden"
cap label var IS "Iceland"
cap label var LI "Liechtenstein"
cap label var NO "Norway"
cap label var CH "Switzerland"
cap label var UK "United Kingdom"
cap label var BA "Bosnia and Herzegovina"
cap label var ME "Montenegro"
cap label var MD "Moldova"
cap label var MK "North Macedonia"
cap label var GE "Georgia"
cap label var AL "Albania"
cap label var RS "Serbia"
cap label var TR "Türkiye"
cap label var UA "Ukraine"
cap label var XK "Kosovo*"
cap label var AD "Andorra"
cap label var BY "Belarus"
cap label var JE "Jersey"
cap label var CQ "Sark"
cap label var VA "Holy See"
cap label var IM "Isle of Man"
cap label var MC "Monaco"
cap label var RU "Russia"
cap label var SM "San Marino"
cap label var NEU27_2020 "Non-EU27 countries (from 2020)"
cap label var AO "Angola"
cap label var CM "Cameroon"
cap label var CF "Central African Republic"
cap label var TD "Chad"
cap label var CG "Congo"
cap label var CD "Democratic Republic of the Congo"
cap label var GQ "Equatorial Guinea"
cap label var GA "Gabon"
cap label var ST "São Tomé and Príncipe"
cap label var BI "Burundi"
cap label var KM "Comoros"
cap label var DJ "Djibouti"
cap label var ER "Eritrea"
cap label var ET "Ethiopia"
cap label var KE "Kenya"
cap label var MG "Madagascar"
cap label var MW "Malawi"
cap label var MU "Mauritius"
cap label var MZ "Mozambique"
cap label var RW "Rwanda"
cap label var SC "Seychelles"
cap label var SO "Somalia"
cap label var UG "Uganda"
cap label var TZ "Tanzania"
cap label var ZM "Zambia"
cap label var ZW "Zimbabwe"
cap label var DZ "Algeria"
cap label var EG "Egypt"
cap label var LY "Libya"
cap label var MA "Morocco"
cap label var SS "South Sudan"
cap label var SD "Sudan"
cap label var TN "Tunisia"
cap label var EH "Western Sahara"
cap label var BW "Botswana"
cap label var LS "Lesotho"
cap label var NA "Namibia"
cap label var ZA "South Africa"
cap label var SZ "Eswatini"
cap label var BJ "Benin"
cap label var BF "Burkina Faso"
cap label var CV "Cabo Verde"
cap label var CI "Côte d’Ivoire"
cap label var GM "Gambia, The"
cap label var GH "Ghana"
cap label var GN "Guinea"
cap label var GW "Guinea-Bissau"
cap label var LR "Liberia"
cap label var ML "Mali"
cap label var MR "Mauritania"
cap label var NE "Niger"
cap label var NG "Nigeria"
cap label var SN "Senegal"
cap label var SL "Sierra Leone"
cap label var TG "Togo"
cap label var CA "Canada"
cap label var US "United States"
cap label var AG "Antigua and Barbuda"
cap label var BS "Bahamas"
cap label var BB "Barbados"
cap label var CU "Cuba"
cap label var DM "Dominica"
cap label var DO "Dominican Republic"
cap label var GD "Grenada"
cap label var HT "Haiti"
cap label var JM "Jamaica"
cap label var KN "Saint Kitts and Nevis"
cap label var LC "Saint Lucia"
cap label var VC "Saint Vincent and the Grenadines"
cap label var TT "Trinidad and Tobago"
cap label var BZ "Belize"
cap label var CR "Costa Rica"
cap label var SV "El Salvador"
cap label var GT "Guatemala"
cap label var HN "Honduras"
cap label var MX "Mexico"
cap label var NI "Nicaragua"
cap label var PA "Panama"
cap label var AR "Argentina"
cap label var BO "Bolivia"
cap label var BR "Brazil"
cap label var CL "Chile"
cap label var CO "Colombia"
cap label var EC "Ecuador"
cap label var GY "Guyana"
cap label var PY "Paraguay"
cap label var PE "Peru"
cap label var SR "Suriname"
cap label var UY "Uruguay"
cap label var VE "Venezuela"
cap label var KZ "Kazakhstan"
cap label var KG "Kyrgyzstan"
cap label var TJ "Tajikistan"
cap label var TM "Turkmenistan"
cap label var UZ "Uzbekistan"
cap label var CN "China"
cap label var JP "Japan"
cap label var MN "Mongolia"
cap label var KP "North Korea"
cap label var KR "South Korea"
cap label var TW "Taiwan"
cap label var AF "Afghanistan"
cap label var BD "Bangladesh"
cap label var BT "Bhutan"
cap label var IN "India"
cap label var IR "Iran"
cap label var MV "Maldives"
cap label var NP "Nepal"
cap label var PK "Pakistan"
cap label var LK "Sri Lanka"
cap label var BN "Brunei Darussalam"
cap label var KH "Cambodia"
cap label var ID "Indonesia"
cap label var LA "Laos"
cap label var MY "Malaysia"
cap label var MM "Myanmar/Burma"
cap label var PH "Philippines"
cap label var SG "Singapore"
cap label var TH "Thailand"
cap label var TL "Timor-Leste"
cap label var VN "Viet Nam"
cap label var AM "Armenia"
cap label var AZ "Azerbaijan"
cap label var BH "Bahrain"
cap label var IQ "Iraq"
cap label var IL "Israel"
cap label var JO "Jordan"
cap label var KW "Kuwait"
cap label var LB "Lebanon"
cap label var PS "Palestine*"
cap label var OM "Oman"
cap label var QA "Qatar"
cap label var SA "Saudi Arabia"
cap label var SY "Syria"
cap label var AE "United Arab Emirates"
cap label var YE "Yemen"
cap label var AU "Australia"
cap label var NZ "New Zealand"
cap label var FJ "Fiji"
cap label var PG "Papua New Guinea"
cap label var SB "Solomon Islands"
cap label var VU "Vanuatu"
cap label var KI "Kiribati"
cap label var MH "Marshall Islands"
cap label var FM "Federated States of Micronesia"
cap label var NR "Nauru"
cap label var WS "Samoa"
cap label var TO "Tonga"
cap label var TV "Tuvalu"
cap label var AQ "Antarctica"
cap label var TOTAL "Total"
cap label var WORLD "All countries of the world"
cap label var WRL_REST "Rest of the world"
cap label var UNK "Unknown"
