cap label var ENT_NR "Enterprises - number"
cap label var TUR_GPW_MEUR "Turnover or gross premiums written - million euro"
cap label var EMP_NR "Persons employed - number"
cap label var TUR_EMP_TEUR "Turnover per person employed - thousand euro"
cap label var GRW_EMP_PC "Growth rate of employment - percentage"
cap label var EMP_ENT_NR "Persons employed per enterprise - number"
cap label var TUR_MFG_PC "Share of turnover in manufacturing total - percentage"
cap label var EMP_MFG_PC "Share of employment in manufacturing total - percentage"
cap label var EMP_IND_PC "Share of employment in industry total - percentage"
