cap label var TOTAL "Total"
cap label var SERV_EE "Services provided electronically"
cap label var SERV_DOM "Services provided by people sent from domestic country"
cap label var SERV_ABR "Services provided by people sent from abroad"
cap label var SERV_RES "Services provided by people resident where the services take place"
