cap label var CODE "Label - English"
cap label var PLC_MKT "Amount placed on the market"
cap label var I_TAX_CHRG_LEV "Amount calculated from mandatory taxes, charges or levies"
cap label var X_TAX_CHRG_LEV "Amount exempt from mandatory taxes, charges or levies"
cap label var I_X_TAX_CHRG_LEV "Amount calculated from mandatory taxes, charges or levies and amount exempt from taxes, charges or levies"
