cap label var CODE "Label - English"
cap label var CAP_HAT "Hatching capacity"
cap label var HAT "Hatcheries"
cap label var INCB "Incubations"
cap label var INCB_LAY "Incubations - utilization laying"
cap label var INCB_DUAL "Incubations - dual purpose utilization"
cap label var INCB_TBL "Incubations - utilization table"
cap label var EPI "Eggs placed in incubation"
cap label var EPI_LAY "Eggs placed in incubation - breeds for laying use"
cap label var EPI_MEAT "Eggs placed in incubation - breeds for meat use"
cap label var EPI_MIX "Eggs placed in incubation - breeds for mixed use"
cap label var CAP "Hatching capacity"
cap label var INC "Incubations: total"
cap label var LAY "Incubations: utilization laying"
cap label var MIX "Incubations: dual purpose utilization"
cap label var UTI "Incubations: utilization table"
