cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var SCO "Social contributions"
cap label var SCO_EMPL "Employers' social contributions"
cap label var SCO_PER_PRO "Protected persons' social contributions"
cap label var GOV_GEN "General government contributions"
cap label var GOV_GEN_EM "General government contributions - earmarked taxes"
cap label var GOV_GEN_REVGEN "General government contributions - general revenue"
cap label var REC_OTH "Other receipts"
cap label var REC_OTH_PROP "Other receipts - property income"
cap label var REC_OTH_O "Other receipts - miscellaneous other"
