cap label var _08111133 "Marble and travertine, crude or roughly trimmed"
cap label var _08111136 "Marble and travertine merely cut into rectangular or square blocks or slabs"
cap label var _08111150 "Ecaussine and other calcareous monumental or building stone of an apparent specific gravity >= 2,5"
cap label var _08111220 "Quartzite (crude, roughly trimmed or merely cut)"
cap label var _08111233 "Granite, crude or roughly trimmed"
cap label var _08111236 "Granite merely cut into rectangular (including square) blocks or slabs"
cap label var _08111250 "Sandstone"
cap label var _08111260 "Other monumental or building stone"
cap label var _08111261 "Porphyry (crude, roughly trimmed or merely cut)"
cap label var _08111262 "Basalt (crude, roughly trimmed or merely cut)"
cap label var _08111269 "Other monumental or building stone (excluding porphyry and basalt)"
cap label var _08111290 "Porphyry, basalt, quartzites and other monumental or building stone, crude, roughly trimmed or merely cut (excluding calcareous monumental or building stone of a gravity >= 2,5, granite and sandstone)"
cap label var _081112Z1 "Porphyry, basalt and other monumental or building stone"
cap label var _08112030 "Gypsum and anhydrite"
cap label var _08112050 "Limestone flux, limestone and other calcareous stone used for the manufacture of lime or cement (excluding crushed limestone aggregate and calcareous dimension stone)"
cap label var _08113010 "Chalk"
cap label var _08113030 "Dolomite, crude, roughly trimmed or merely cut into rectangular or square blocks or slabs (excluding calcined or sintered dolomite, agglomerated dolomite and broken or crushed dolomite for concrete aggregates, road metalling or railway or other ballast)"
cap label var _08114000 "Slate, crude, roughly trimmed or merely cut into rectangular or square blocks or slabs"
cap label var _08122140 "Kaolin, not calcined"
cap label var _08122160 "Kaolinitic clays (ball and plastic clays)"
cap label var _08122210 "Bentonite"
cap label var _08122230 "Fireclay"
cap label var _08122250 "Common clays and shales for construction use (excluding bentonite, fireclay, expanded clays, kaolin and kaolinic clays); andalusite, kyanite and sillimanite; mullite; chamotte or dinas earths"
cap label var _08122255 "Bentonite"
cap label var _08122260 "Andalusite, kyanite and sillimanite"
cap label var _08122270 "Mullite"
cap label var _08122280 "Chamotte or dinas earths"
cap label var _08911100 "Natural calcium phosphates; natural aluminium calcium phosphates and phosphatic chalk"
cap label var _08911200 "Unroasted iron pyrites; crude or unrefined sulphur (including recovered sulphur)"
cap label var _08911220 "Natural calcium phosphates; natural aluminium calcium phosphates and phosphatic chalk"
cap label var _08911230 "Crude or unrefined sulphur (including recovered sulphur)"
cap label var _08911900 "Other chemical and fertiliser minerals"
cap label var _08911910 "Natural barium sulphate (barytes) and carbonate  (witherite)"
cap label var _08911911 "Natural borates and concentrates thereof (not calcined), but not including borates separated from natural brine; natural boric acid containing not more than 85 % of H3BO3 calculated on the dry weight"
cap label var _08911912 "Fluorspar"
cap label var _08911913 "Kieserite, epsomite (natural magnesium sulphates)"
cap label var _08911919 "Other mineral substances n.e.s. (excluding vermiculite, perlite and chlorites, unexpanded and kieserite, epsomite (natural magnesium sulphates))"
cap label var _08931000 "Salt (including denatured salt but excluding salt suitable for human consumption) and pure sodium chloride, whether or not in aqueous solution or containing added anti-caking or free-flowing agents"
cap label var _08991000 "Natural bitumen and natural asphalt; asphaltites and asphaltic rocks"
cap label var _08992100 "Precious and semi-precious stones (excluding industrial diamonds), unworked or simply sawn or roughly shaped"
cap label var _08992110 "Diamonds unworked or simply sawn or roughly shaped"
cap label var _08992120 "Precious stones (other than diamonds) and semi-precious stones, unworked or simply sawn or roughly shaped"
cap label var _08992200 "Industrial diamonds, unworked or simply sawn, cleaved or bruted; pumice stone; emery; natural corundum, natural garnet and other natural abrasives"
cap label var _08992210 "Industrial diamonds. Unworked or simply sawn, cleaved or bruted, but not mounted or set"
cap label var _08992220 "Pumice stone"
cap label var _08992230 "Emery, natural corundum, natural garnet and other natural abrasives, whether or not heat-treated"
cap label var _08992900 "Other minerals"
cap label var _08992910 "Natural graphite"
cap label var _08992913 "Natural magnesium carbonate (magnesite);"
cap label var _08992914 "Dead-burned (sintered) magnesia"
cap label var _08992915 "Fused magnesia and other magnesium oxide"
cap label var _08992920 "Other minerals"
cap label var _10843000 "Salt suitable for human consumption"
cap label var _13101000 "Wool grease and fatty substances derived therefrom, including lanolin"
cap label var _13102100 "Raw silk (not thrown)"
cap label var _13102200 "Wool, degreased or carbonised, not carded or combed"
cap label var _13102300 "Noils of wool or fine animal hair"
cap label var _13102400 "Wool or animal hair, carded or combed (including wool tops)"
cap label var _13102500 "Cotton, carded or combed"
cap label var _13102600 "Jute and other textile fibres (except flax, true hemp and ramie), processed but not spun"
cap label var _13102900 "Other vegetable textile fibres, processed but not spun"
cap label var _13103100 "Synthetic staple fibres, carded, combed or otherwise processed for spinning"
cap label var _13103200 "Artificial staple fibres, carded, combed or otherwise processed for spinning"
cap label var _13104010 "Silk yarn, n.p.r.s. (excluding spun from silk waste)"
cap label var _13104030 "Yarn spun from silk waste, n.p.r.s."
cap label var _13104050 "Silk yarn and silk waste yarn, p.r.s.; silk-worm gut"
cap label var _13105010 "Yarn of carded wool or fine animal hair, n.p.r.s."
cap label var _13105030 "Yarn of combed wool or fine animal hair, n.p.r.s."
cap label var _13105050 "Yarn of wool or fine animal hair, p.r.s."
cap label var _13106132 "Yarn of uncombed cotton, n.p.r.s., for woven fabrics (excluding for carpets and floor coverings)"
cap label var _13106133 "Yarn of uncombed cotton, n.p.r.s., for knitted fabrics and hosiery"
cap label var _13106135 "Yarn of uncombed cotton, n.p.r.s., for other uses (including carpets and floor coverings)"
cap label var _13106152 "Yarn of combed cotton, n.p.r.s., for woven fabrics (excluding for carpets and floor coverings)"
cap label var _13106153 "Yarn of combed cotton, n.p.r.s., for knitted fabrics and hosiery"
cap label var _13106155 "Yarn of combed cotton, n.p.r.s., for other uses (including carpets and floor coverings)"
cap label var _13106160 "Cotton yarn, p.r.s. (excluding sewing thread)"
cap label var _131061Z1 "Cotton yarn of uncombed fibres, n.p.r.s."
cap label var _131061Z2 "Cotton yarn of combed fibres, n.p.r.s."
cap label var _13106200 "Cotton sewing thread"
cap label var _13107110 "Flax yarn, n.p.r.s."
cap label var _13107120 "Flax yarn, p.r.s."
cap label var _13107200 "Yarn of vegetable or bast fibres (excluding flax); paper yarn"
cap label var _13108110 "Multiple or cabled synthetic filament yarn, n.p.r.s."
cap label var _13108130 "Multiple or cabled yarn of artificial filaments, n.p.r.s. (excluding sewing thread)"
cap label var _13108150 "Man-made filament yarn, p.r.s. (excluding sewing thread)"
cap label var _13108210 "Yarn (other than sewing thread) containing >= 85 % by weight of synthetic staple fibres, n.p.r.s."
cap label var _13108250 "Yarn (other than sewing thread) containing >= 85 % by weight of synthetic staple fibres, p.r.s."
cap label var _13108320 "Yarn containing < 85 % by weight of polyester staple fibres (other than sewing thread), mixed with artificial fibres, n.p.r.s."
cap label var _13108333 "Yarn containing < 85 % by weight of synthetic staple fibres (other than sewing thread) mixed with carded wool or fine animal hair, n.p.r.s."
cap label var _13108336 "Yarn containing < 85 % by weight of synthetic staple fibres, mixed with combed wool or fine animal hair, n.p.r.s."
cap label var _13108340 "Yarn containing < 85 % by weight of synthetic staple fibres (other than sewing thread), mixed with cotton, n.p.r.s."
cap label var _13108380 "Other yarns, containing < 85 % by weight of synthetic staple fibres (other than sewing thread), n.p.r.s., n.e.c."
cap label var _13108390 "Yarn containing < 85 % by weight of synthetic staple fibres (other than sewing thread), p.r.s."
cap label var _131083Z0 "Yarn of synthetic staple fibres mixed with wool, n.p.r.s"
cap label var _13108410 "Yarn (other than sewing thread) of artificial staple fibres, n.p.r.s."
cap label var _13108430 "Yarn (other than sewing thread) of artificial staple fibres, p.r.s."
cap label var _13108510 "Sewing thread of man-made filaments"
cap label var _13108550 "Sewing thread of man-made staple fibres"
cap label var _13201230 "Woven fabrics of carded wool or carded fine animal hair"
cap label var _13201260 "Woven fabrics of combed wool or combed fine animal hair; woven fabrics of coarse animal hair"
cap label var _13201330 "Woven fabrics of flax, containing >= 85 % by weight of flax"
cap label var _13201360 "Woven fabrics of flax, containing < 85 % by weight of flax"
cap label var _13201400 "Woven fabrics of jute or of other textile bast fibres (excluding flax, true hemp, ramie)"
cap label var _13201900 "Woven fabrics of true hemp, ramie or other vegetable textile fibres (excluding flax, jute, other textile bast fibres); paper yarn"
cap label var _13202014 "Woven fabrics of cotton, not of yarns of different colours, weighing <= 200 g/m², for clothing"
cap label var _13202017 "Woven fabrics of cotton, not of yarns of different colours, weighing <= 200 g/m², for household linen or home furnishing textiles"
cap label var _13202019 "Woven fabrics of cotton, not of yarns of different colours, weighing <= 200 g/m², for technical or industrial uses (excluding gauze, medical gauze)"
cap label var _13202031 "Woven fabrics of cotton of yarns of different colours, weighing <= 200 g/m², for shirts and blouses"
cap label var _13202042 "Woven fabrics of cotton, not of yarns of different colours, weighing > 200 g/m², for clothing"
cap label var _13202044 "Woven fabrics of cotton, not of yarns of different colours, weighing > 200 g/m², for household linen or home furnishing textiles"
cap label var _13202049 "Woven fabrics of cotton, not of yarns of different colours, weighing > 200 g/m², for technical or industrial uses"
cap label var _13202072 "Woven fabrics of cotton of yarns of different colours, for other clothing"
cap label var _13202074 "Woven fabrics of cotton of yarns of different colours, for household linen or home furnishing textiles"
cap label var _13202079 "Woven fabrics of cotton of yarns of different colours, for technical or industrial uses"
cap label var _132020Z1 "Cotton fabrics, <= 200 g/m² (excluding gauze and coloured yarns)"
cap label var _132020Z2 "Cotton fabrics, > 200 g/m² (excluding coloured yarns)"
cap label var _132020Z3 "Woven fabrics of cotton of yarns of different colours (excluding denim)"
cap label var _13203150 "Woven fabrics of synthetic filament yarns (excluding those obtained from high tenacity yarn or strip and the like)"
cap label var _13203170 "Woven fabrics of artificial filament yarns (excluding those obtained from high tenacity yarn)"
cap label var _13203210 "Woven fabrics of synthetic staple fibres, containing 85 % or more by weight of synthetic staple fibres"
cap label var _13203220 "Woven fabrics of synthetic staple fibres, containing less than 85 % by weight of such fibres, mixed mainly or solely with cotton (excluding fabrics of yarns of different colours)"
cap label var _13203230 "Woven fabrics of synthetic staple fibres, containing less than 85 % by weight of such fibres, mixed mainly or solely with cotton, of yarns of different colours"
cap label var _13203240 "Woven fabrics of synthetic staple fibres mixed mainly or solely with carded wool or fine animal hair"
cap label var _13203250 "Woven fabrics of synthetic staple fibres mixed mainly or solely with combed wool or fine animal hair"
cap label var _13203290 "Woven fabrics of synthetic staple fibres mixed other than with wool, fine animal hair or cotton"
cap label var _13203330 "Woven fabrics of artificial staple fibres, not of yarns of different colours"
cap label var _13204200 "Terry towelling and similar woven terry fabrics of cotton"
cap label var _13204300 "Terry towelling and similar woven terry fabrics (excluding of cotton)"
cap label var _13911100 "Pile fabrics, terry fabrics, knitted or crocheted"
cap label var _13911910 "Knitted or crocheted fabrics (excluding pile fabrics)"
cap label var _15112200 "Patent leather; patent laminated leather and metallised leather"
cap label var _15113100 "Leather, of bovine animals, without hair, whole"
cap label var _15113200 "Leather, of bovine animals, without hair, not whole"
cap label var _15113300 "Leather, of equine animals, without hair"
cap label var _15114130 "Sheep or lamb skin leather without wool on, tanned but not further prepared (excluding chamois leather)"
cap label var _15114150 "Sheep or lamb skin leather without wool on, parchment-dressed or prepared after tanning (excluding chamois, patent, patent laminated leather and metallised leather)"
cap label var _15114230 "Goat or kid skin leather without hair on; tanned or pre-tanned but not further prepared (excluding chamois leather)"
cap label var _15114250 "Goat or kid skin leather without hair on, parchment-dressed or prepared after tanning (excluding chamois leather, patent leather, patent laminated leather and metallised leather)"
cap label var _15114330 "Leather of swine without hair on, tanned but not further prepared"
cap label var _15114350 "Leather of swine without hair on; parchment-dressed or prepared after tanning (excluding patent leather; patent laminated leather and metallised leather)"
cap label var _15115100 "Leather of other animals, without hair on"
cap label var _15115200 "Composition leather with a basis of leather or leather fibre, in slabs, sheets or strips"
cap label var _17111100 "Chemical wood pulp, dissolving grades"
cap label var _17111200 "Chemical wood pulp, soda or sulphate, other than dissolving grades"
cap label var _17111300 "Chemical wood pulp, sulphite, other than dissolving grades"
cap label var _17111400 "Mechanical wood pulp; semi-chemical wood pulp; pulps of fibrous cellulosic material other than wood"
cap label var _19103000 "Pitch and pitch coke, obtained from coal tar or from other mineral tars"
cap label var _20111120 "Argon"
cap label var _20111130 "Rare gases (excluding argon)"
cap label var _20111140 "Helium"
cap label var _20111150 "Hydrogen"
cap label var _20111160 "Nitrogen"
cap label var _20111170 "Oxygen"
cap label var _20111190 "Nitrogen"
cap label var _20111230 "Carbon dioxide"
cap label var _20111250 "Sulphur trioxide (sulphuric anhydride); diarsenic trioxide"
cap label var _20111270 "Nitrogen oxides"
cap label var _20111290 "Inorganic oxygen compounds of non metals (excluding sulphur trioxide (sulphuric anhydride); diarsenic trioxide, nitrogen oxides, silicon dioxide, sulphur dioxide, carbon dioxide)"
cap label var _20111300 "Liquid air; compressed air"
cap label var _20121130 "Zinc oxide; zinc peroxide"
cap label var _20121150 "Titanium oxides"
cap label var _20121200 "Chromium, manganese, lead and copper oxides and hydroxides"
cap label var _20121210 "Manganese oxides. Manganese dioxide"
cap label var _20121220 "Manganese oxides. Manganese oxide containing by weight 77 % or more of manganese"
cap label var _20121230 "Manganese oxides. Manganese oxide containing by weight less than 77 % of manganese"
cap label var _20121240 "Chromium, lead and copper oxides and hydroxides"
cap label var _20121910 "Iron oxides and hydroxides; earth colours containing 70 % or more by weight of combined iron evaluated as Fe2O3"
cap label var _20121930 "Cobalt oxides and hydroxides; commercial cobalt oxides"
cap label var _20121950 "Lithium oxide and hydroxide; vanadium oxides and hydroxides; nickel oxides and hydroxides; germanium oxides and zirconium dioxide"
cap label var _20121955 "Lithium oxide and hydroxide"
cap label var _20121960 "Vanadium oxides and hydroxides"
cap label var _20121965 "Nickel oxides and hydroxides"
cap label var _20121970 "Germanium oxides and zirconium dioxide"
cap label var _20121973 "Molybdenum oxides and hydroxides"
cap label var _20121975 "Antimony oxides"
cap label var _20121980 "Beryllium oxide and hydroxide"
cap label var _20121981 "Tungsten oxides and hydroxides"
cap label var _20121990 "Other inorganic bases; other metal oxides, hydroxides and peroxides, n.e.c."
cap label var _20121995 "Other inorganic bases; other metal oxides, hydroxides and peroxides, n.e.c."
cap label var _20121996 "Tin oxides and hydroxides"
cap label var _20121997 "Other inorganic bases; other metal oxides, hydroxides and peroxides (excluding tin oxides and hydroxides), n.e.c."
cap label var _201219Z0 "Other inorganic bases; other metal oxides, hydroxides and peroxides, n.e.c."
cap label var _20122110 "Disperse dyes and preparations based thereon"
cap label var _20122120 "Acid and mordant dyes and preparations based thereon"
cap label var _20122130 "Basic dyes and preparations based thereon"
cap label var _20122140 "Direct dyes and preparations based thereon"
cap label var _20122150 "Other synthetic organic colouring matters"
cap label var _20122160 "Synthetic organic products used as fluorescent brightening agents"
cap label var _20122170 "Colour lakes; preparations based on colour lakes"
cap label var _20122250 "Tanning extracts of vegetable origin; tannins and their salts, ethers, esters and other derivatives"
cap label var _20122270 "Colouring matter of vegetable or animal origin and preparations based thereon (including dyeing extracts) (excluding animal black)"
cap label var _20122330 "Synthetic organic tanning substances"
cap label var _20122350 "Inorganic tanning substances; tanning preparations; enzymatic preparations for pre-tanning"
cap label var _20122415 "Pigments and preparations based on titanium dioxide containing >= 80 % by weight of titanium dioxide"
cap label var _20122419 "Pigments and preparations based on titanium dioxide (excluding those containing >= 80 % by weight of titanium dioxide)"
cap label var _20122440 "Pigments and preparations based on chromium or cadmium compounds"
cap label var _20122450 "Other colouring matter; pigments and preparations based on inorganic or mineral colouring matter; inorganic products of a kind used as luminophores"
cap label var _20122470 "Other colouring matter, preparations and luminophores"
cap label var _20132111 "Chlorine"
cap label var _20132116 "Iodine; fluorine; bromine"
cap label var _20132120 "Sulphur, sublimed or precipitated; colloidal sulphur"
cap label var _20132130 "Carbon (carbon blacks and other forms of carbon, n.e.c.)"
cap label var _20132140 "Boron; tellurium"
cap label var _20132141 "Boron"
cap label var _20132142 "Tellurium"
cap label var _20132150 "Silicon"
cap label var _20132160 "Silicon. Containing by weight not less than 99,99 % of silicon"
cap label var _20132170 "Silicon. Other than containing by weight not less than 99,99 % of silicon"
cap label var _20132180 "Phosphorus; arsenic; selenium"
cap label var _20132181 "Phosphorus"
cap label var _20132185 "Arsenic; selenium"
cap label var _20132210 "Phosphorus oxychloride"
cap label var _20132220 "Phosphorus trichloride"
cap label var _20132230 "Phosphorus trichloride"
cap label var _20132235 "Chlorides and chloride oxides of phosphorus"
cap label var _20132237 "Halides and halide-oxides of non-metals (excluding chlorides and chloride oxides of phosphorus)"
cap label var _20132240 "Chlorides and chloride oxides of phosphorus (excl. phosphorus oxy-, tri- and pentachloride)"
cap label var _20132260 "Sulphides of non-metals; commercial phosphorus trisulphide"
cap label var _20132270 "Phosphorus sulphides, commercial phosphorus trisulphide"
cap label var _20132280 "Sulphides of non-metals (excluding phosphorus sulphides; commercial phosphorus trisulphide)"
cap label var _20132300 "Alkali or alkaline-earth metals; rare-earth metals, scandium and yttrium; mercury"
cap label var _20132310 "Cerium, lanthanum, praseodymium, neodymium and samarium"
cap label var _20132311 "Europium, gadolinium, terbium, dysprosium, holmium, erbium, thulium, ytterbium, lutetium and yttrium"
cap label var _20132312 "Scandium metal"
cap label var _20132319 "Alkali or alkaline-earth metals; rare-earth metals; mercury (excluding cerium, lanthanum, praseodymium, neodymium and samarium, europium, gadolinium, terbium, dysprosium, holmium, erbium, thulium, ytterbium, lutetium and yttrium and scandium metal)"
cap label var _20132413 "Hydrogen chloride (hydrochloric acid)"
cap label var _20132415 "Chlorosulphuric acid"
cap label var _20132433 "Sulphuric acid"
cap label var _20132434 "Sulphuric acid; oleum"
cap label var _20132435 "Oleum"
cap label var _20132453 "Diphosphorus pentaoxide"
cap label var _20132455 "Phosphoric acid and polyphosphoric acids"
cap label var _20132460 "Oxides of boron; boric acids; inorganic acids (excluding hydrogen fluoride)"
cap label var _20132462 "Diboron trioxide"
cap label var _20132465 "Oxides of boron and boric acids (excl. diboron trioxide)"
cap label var _20132469 "Other inorganic acids and other inorganic oxygen compounds of non-metals (excluding hydrogen fluoride)"
cap label var _20132473 "Hydrogen fluoride (hydrofluoric acid)"
cap label var _20132475 "Silicon dioxide"
cap label var _20132477 "Sulphur dioxide"
cap label var _20132525 "Sodium hydroxide (caustic soda), solid"
cap label var _20132527 "Sodium hydroxide in aqueous solution (soda lye or liquid soda)"
cap label var _20132530 "Potassium hydroxide (caustic potash)"
cap label var _20132535 "Potassium hydroxide (caustic potash), solid"
cap label var _20132537 "Potassium hydroxide in an aqueous solution (potassium lye or liquid potassium)"
cap label var _20132550 "Peroxides of sodium or potassium"
cap label var _20132560 "Hydroxide and peroxide of magnesium; oxides, hydroxides and peroxides of strontium or barium"
cap label var _20132563 "Hydroxide and peroxide of magnesium"
cap label var _20132565 "Oxides, hydroxides and peroxides, of strontium or barium"
cap label var _20132570 "Aluminium hydroxide"
cap label var _20132580 "Hydrazine and hydroxylamine and their inorganic salts"
cap label var _20133110 "Fluorides; fluorosilicates; fluoroaluminates and other complex fluorine salts"
cap label var _20133115 "Fluorides; fluorosilicates; fluoroaluminates and other complex fluorine salts (Lithium hexafluorophosphate (1-), Lithium difluorophosphate, Lithium hexafluoroarsenate monohydrate, Lithium tetrafluoroborate)"
cap label var _20133119 "Fluorides; fluorosilicates; fluoroaluminates and other complex fluorine salts (excl. sodium hexafluoroaluminate "synthetic cryolite"; hexafluorophosphate (1-), difluorophosphate, hexafluoroarsenate monohydrate and tetrafluoroborate of lithium; inorganic or organic compounds of mercury)"
cap label var _20133130 "Chlorides (excluding ammonium chloride)"
cap label var _20133131 "Magnesium chlorides"
cap label var _20133132 "Nickel chlorides"
cap label var _20133133 "Tin chlorides"
cap label var _20133134 "Cobalt chlorides"
cap label var _20133135 "Lithium chloride"
cap label var _20133138 "Other chlorides (excluding lithium, ammonium, magnesium, nickel, tin and cobalt chloride) n.e.s."
cap label var _20133139 "Other chlorides n.e.s."
cap label var _20133150 "Chloride oxides and chloride hydroxides of copper and other metals"
cap label var _20133170 "Bromides and bromide oxides; iodides and iodide oxides"
cap label var _20133171 "Bromides and bromide oxides (excl. bromides of sodium or of potassium)"
cap label var _20133172 "Lithium bromide"
cap label var _20133173 "Bromides and bromide oxides (excl. bromides of sodium, of potassium and of lithium)"
cap label var _20133179 "Bromides of sodium or of potassium; iodides and iodide oxides"
cap label var _201331Z1 "Other chlorides n.e.s. (excluding ammonium, magnesium, nickel, tin and cobalt chloride)"
cap label var _201331Z2 "Bromides and bromide oxides (excl. bromides of sodium or of potassium)"
cap label var _20133230 "Hypochlorites; commercial calcium hypochlorite; chlorites; hypobromites"
cap label var _20133250 "Chlorates and perchlorates; bromates and perbromates; iodates and periodates"
cap label var _20133251 "Lithium perchlorate"
cap label var _20133259 "Chlorates and perchlorates; bromates and perbromates; iodates and periodates (excluding lithium perchlorate)"
cap label var _201332Z1 "Chlorates and perchlorates; bromates and perbromates; iodates and periodates"
cap label var _20134110 "Sulphides; polysulphides, whether or not chemically defined; dithionites and sulphoxylates"
cap label var _20134111 "Sulphides of calcium, of antimony or of iron"
cap label var _20134120 "Sulphides; polysulphides, whether or not chemically defined; dithionites and sulphoxylates (excluding of calcium, antimony and iron)"
cap label var _20134133 "Sulphites"
cap label var _20134135 "Thiosulphates"
cap label var _20134150 "Sulphates of aluminium"
cap label var _20134151 "Sulphates of barium or aluminium"
cap label var _20134155 "Sulphates of barium"
cap label var _20134157 "Sulphates (excluding those of aluminium and barium)"
cap label var _20134160 "Sulphates of magnesium"
cap label var _20134161 "Sulphates of nickel"
cap label var _20134162 "Sulphates of cobalt; of titanium"
cap label var _20134165 "Sulphates (excluding those of aluminium, barium, magnesium, nickel, cobalt, titanium)"
cap label var _20134173 "Alums"
cap label var _20134175 "Peroxosulphates (persulphates)"
cap label var _20134210 "Nitrates (excluding those of potassium)"
cap label var _20134211 "Nitrates of barium; of beryllium; of cadmium; of cobalt; of nickel; of lead"
cap label var _20134212 "Nitrates of copper and other (excluding those of potassium, of barium, of beryllium, of cadmium, of cobalt, of nickel, of lead)"
cap label var _20134213 "Nitrates of barium; of beryllium; of cadmium;  of lead"
cap label var _20134214 "Nitrate of cobalt"
cap label var _20134215 "Nitrate of nickel"
cap label var _20134220 "Phosphinates (hypophosphites) and phosphonates (phosphites)"
cap label var _20134230 "Phosphates of mono- or di-sodium"
cap label var _20134240 "Calcium hydrogenorthophosphate (dicalcium phosphate)"
cap label var _20134270 "Sodium triphosphate (sodium tripolyphosphate)"
cap label var _20134280 "Phosphates (excluding calcium hydrogenorthophosphate and mono- or disodium phosphate); polyphosphates (excluding sodium triphosphate)"
cap label var _20134281 "Lithium iron phosphate"
cap label var _20134289 "Phosphates (excluding calcium hydrogenorthophosphate and mono- or disodium phosphate, and lithium iron phosphate); polyphosphates (excluding sodium triphosphate)"
cap label var _201342Z1 "Nitrates of barium; of beryllium; of cadmium; of cobalt; of nickel; of lead"
cap label var _201342Z2 "Phosphates (excluding calcium hydrogenorthophosphate and mono- or disodium phosphate); polyphosphates (excluding sodium triphosphate)"
cap label var _20134310 "Disodium carbonate"
cap label var _20134320 "Sodium hydrogencarbonate (sodium bicarbonate)"
cap label var _20134340 "Calcium carbonate"
cap label var _20134350 "Lithium carbonates"
cap label var _20134351 "Lithium carbonates with a minimum content of 99,5% of Li2CO3 or more"
cap label var _20134352 "Lithium carbonates with a content of less than  99,5% of Li2CO3"
cap label var _20134390 "Other carbonates"
cap label var _20134395 "Other carbonates n.e.s."
cap label var _20134396 "Cobalt carbonates"
cap label var _20134399 "Other carbonates (excluding cobalt carbonates)"
cap label var _201343Z1 "Lithium carbonates"
cap label var _201343Z2 "Other carbonates n.e.s."
cap label var _20135125 "Chromates and dichromates; peroxochromates"
cap label var _20135270 "Compounds, inorganic or organic, of mercury, chemically defined as mercury (excluding amalgams)"
cap label var _20135275 "Compounds, inorganic or organic, of mercury, not chemically defined (excluding amalgams)"
cap label var _20136220 "Cyanides; cyanide oxides and complex cyanides"
cap label var _20136230 "Borates; peroxoborates (perborates)"
cap label var _20136240 "Silicates; commercial alkali metal silicates"
cap label var _20136270 "Double or complex silicates"
cap label var _20136280 "Salts of inorganic acids or peroxoacids (excluding azides and double or complex silicates)"
cap label var _20136300 "Hydrogen peroxide"
cap label var _20136410 "Carbides of silicon, whether or not chemically defined"
cap label var _20136420 "Carbides of boron, whether or not chemically defined"
cap label var _20136430 "Carbides of tungsten, whether or not chemically defined"
cap label var _20136450 "Carbides whether or not chemically defined"
cap label var _20136451 "Carbides of aluminium, of chromium, of molybdenum, of vanadium, of tantalum; of titanium, whether or not chemically defined"
cap label var _20136480 "Phosphides (excluding ferrophosphorus), whether or not chemically defined; hydrides, nitrides, azides, silicides and borides, whether or not chemically defined, other than compounds which are also carbides of heading 20.13.64.50"
cap label var _20136490 "Other carbides n.e.s."
cap label var _20141120 "Saturated acyclic hydrocarbons"
cap label var _20141130 "Ethylene"
cap label var _20141140 "Propene (propylene)"
cap label var _20141150 "Butene (butylene) and isomers thereof"
cap label var _20141160 "Buta-1,3-diene and isoprene"
cap label var _20141165 "Unsaturated acyclic hydrocarbons; buta-1.3-diene"
cap label var _20141167 "Unsaturated acyclic hydrocarbons; Isoprene"
cap label var _20141190 "Unsaturated acyclic hydrocarbons (excluding ethylene, propene, butene, buta-1,3-diene and isoprene)"
cap label var _20141213 "Cyclohexane"
cap label var _20141215 "Cyclanes; cyclenes and cycloterpenes (excluding cyclohexane)"
cap label var _20141223 "Benzene"
cap label var _20141225 "Toluene"
cap label var _20141243 "o-Xylene"
cap label var _20141245 "p-Xylene"
cap label var _20141247 "m-Xylene and mixed xylene isomers"
cap label var _20141250 "Styrene"
cap label var _20141260 "Ethylbenzene"
cap label var _20141270 "Cumene"
cap label var _20141290 "Other cyclic hydrocarbons"
cap label var _20141313 "Chloromethane (methyl chloride) and chloroethane (ethyl chloride)"
cap label var _20141315 "Dichloromethane (methylene chloride)"
cap label var _20141323 "Chloroform (trichloromethane)"
cap label var _20141325 "Carbon tetrachloride"
cap label var _20141353 "1,2-Dichloroethane (ethylene dichloride)"
cap label var _20141357 "Saturated chlorinated derivatives of acyclic hydrocarbons, n.e.c."
cap label var _20141371 "Vinyl chloride (chloroethylene)"
cap label var _20141374 "Trichloroethylene; tetrachloroethylene (perchloroethylene)"
cap label var _20141379 "Unsaturated chlorinated derivatives of acyclic hydrocarbons (excluding vinyl chloride, trichloroethylene, tetrachloroethylene)"
cap label var _20141450 "Derivatives of hydrocarbons containing only sulpho groups; their salts and ethyl esters"
cap label var _20141470 "Derivatives of hydrocarbons containing only nitro or only nitroso groups"
cap label var _20141490 "Derivatives of hydrocarbons (excluding those containing only sulpho groups; their salts and ethyl esters, those containing only nitro or only nitroso groups)"
cap label var _20142100 "Industrial fatty alcohols"
cap label var _20142210 "Methanol (methyl alcohol)"
cap label var _20142220 "Propan-1-ol (propyl alcohol) and propan-2-ol (isopropyl alcohol)"
cap label var _20142230 "Butan-1-ol (n-butyl alcohol)"
cap label var _20142240 "Butanols (excluding butan-1-ol (n-butyl alcohol))"
cap label var _20142263 "Octanol (octyl alcohol) and isomers thereof"
cap label var _20142265 "Lauryl alcohol; cetyl alcohol; stearyl alcohol and other saturated monohydric alcohols (excluding methyl, propyl and isopropyl, n-butyl, other butanols, octyl)"
cap label var _20142270 "Unsaturated monohydric alcohols"
cap label var _20142310 "Ethylene glycol (ethanediol)"
cap label var _20142320 "Propylene glycol (propane-1,2-diol)"
cap label var _20142333 "D-glucitol (sorbitol)"
cap label var _20142337 "Diols and polyhydric alcohols (excluding ethylene glycol and propylene glycol, D-glucitol and tetramethylene glycol having a bio-based carbon content of 100 % by mass)"
cap label var _20142338 "Butane-1,4-diol or tetramethylene glycol (1,4-butanediol) having a bio-based carbon content of 100 % by mass"
cap label var _20142339 "Diols and polyhydric alcohols (excluding ethylene glycol and propylene glycol, D-glucitol)"
cap label var _20142350 "Halogenated, sulphonated, nitrated or nitrosated derivatives of acyclic alcohols"
cap label var _20142360 "Glycerol (including synthetic; excluding crude, waters and lyes)"
cap label var _20142373 "Cyclanic, cyclenic or cycloterpenic alcohols and their halogenated, sulphonated, nitrated or nitrosated derivatives"
cap label var _20142375 "Aromatic alcohols and their halogenated, sulphonated, nitrated or nitrosated derivatives"
cap label var _20142410 "Monophenols"
cap label var _20142433 "4,4-Isopropylidenediphenol (bisphenol A; diphenylolpropane) and its salts"
cap label var _20142439 "Polyphenols (including salts; excluding 4,4 isopropylidenediphenol) and phenol-alcohols"
cap label var _20142450 "Halogenated, sulphonated, nitrated or nitrosated derivatives of phenols or phenol-alcohols"
cap label var _20143120 "Industrial stearic acid"
cap label var _20143130 "Industrial oleic acid"
cap label var _20143150 "Industrial tall oil fatty acids"
cap label var _20143195 "Industrial monocarboxylic fatty acids distilled (excluding stearic, oleic tall oil)"
cap label var _20143197 "Industrial monocarboxylic fatty acids (excluding stearic, oleic, tall oil, distilled)"
cap label var _20143215 "Ethyl acetate"
cap label var _20143219 "Esters of acetic acid (excluding ethyl acetate)"
cap label var _20143220 "Mono-, di- or tri-chloroacetic acids; propionic, butanoic and pentanoic acids; their salts and esters"
cap label var _20143230 "Palmitic acid, its salts and esters"
cap label var _20143235 "Palmitic acid, stearic acid, their salts and esters"
cap label var _20143240 "Stearic acid, its salts and esters"
cap label var _20143250 "Formic acid, its salts and esters"
cap label var _20143271 "Acetic acid"
cap label var _20143277 "Acetic anhydride"
cap label var _20143278 "Salts of acetic acid"
cap label var _20143280 "Lauric acid and others; salts and esters"
cap label var _20143310 "Acrylic acid and its salts and other monocarboxylic acid"
cap label var _20143320 "Esters of acrylic acid"
cap label var _20143330 "Methacrylic acid and its salts"
cap label var _20143340 "Esters of methacrylic acid"
cap label var _20143350 "Oleic, linoleic or linolenic acids; their salts and esters"
cap label var _20143363 "Benzoic acid; its salts and esters"
cap label var _20143365 "Benzoyl peroxide and benzoyl chloride"
cap label var _20143367 "Phenylacetic acid; its salts and esters"
cap label var _20143370 "Aromatic monocarboxylic acids, (anhydrides), halides, peroxides, peroxyacids, derivatives excluding benzoic acid, phenylacetic acids their salts/esters, benzoyl peroxide, benzoyl chloride"
cap label var _20143381 "Oxalic, azelaic, malonic, other, cyclanic, cylenic or cycloterpenic polycarboxylic acids, salts (excluding butanedioic acid having a bio-based carbon content of 100 % by mass)"
cap label var _20143382 "Ethane-1,2-dicarboxylic acid or butanedioic acid (succinic acid) having a bio-based carbon content of 100 % by mass"
cap label var _20143383 "Oxalic, azelaic, malonic, other, cyclanic, cylenic or cycloterpenic polycarboxylic acids, salts"
cap label var _20143385 "Adipic acid; its salts and esters"
cap label var _20143387 "Maleic anhydride"
cap label var _20143410 "Dibutyl and dioctyl orthophthalates"
cap label var _20143420 "Other esters of orthophthalic acid"
cap label var _20143430 "Phthalic anhydride; terephthalic acid and its salts"
cap label var _20143440 "Aromatic polycarboxylic acids, their anhydrides, halides, peroxides, peroxyacids and their halogenated, sulphonated, nitrated or nitrosated derivatives (excluding esters of orthophthalic acid, phthalic anhydride, terephthalic acid and its salts)"
cap label var _20143473 "Citric acid and its salts and esters"
cap label var _20143475 "Carboxylic acid with alcohol, phenol, aldehyde or ketone functions"
cap label var _201434Z1 "Esters of orthophthalic acid"
cap label var _20144113 "Methylamine; di- or trimethylamine and their salts"
cap label var _20144119 "Other acylic monoamines and their derivatives; salts thereof"
cap label var _20144123 "Hexamethylenediamine and its salts; ethylenediamine and its salts"
cap label var _20144129 "Other acyclic polyamines and their derivatives; salts thereof"
cap label var _20144130 "Cyclanic, cyclenic or cycloterpenic mono- or polyamines, and their derivatives; salts thereof"
cap label var _20144151 "Aniline and its salts (excluding derivatives)"
cap label var _20144153 "Aniline derivatives and their salts"
cap label var _20144159 "Other aromatic monoamines and their derivatives; salts thereof"
cap label var _20144170 "Aromatic polyamines and their derivatives; salts thereof"
cap label var _20144233 "Monoethanolamine and its salts"
cap label var _20144235 "Diethanolamine and its salts"
cap label var _20144237 "Triethanolamine and its salts"
cap label var _20144238 "Amino-alcohols, their ethers and esters with only 1 oxygen function and their salts (excluding monoethanolamine and its salts, diethanolamine and its salts)"
cap label var _20144239 "Amino-alcohols, their ethers and esters with only 1 oxygen function and their salts (excluding monoethanolamine and its salts, diethanolamine and its salts, triethanolamine and its salts)"
cap label var _20144290 "Oxygen-function amino-compounds (excluding amino-alcohols, their esters and ethers and salts thereof, lysine and its salts and esters, glutamic acid its salts and esters)"
cap label var _20144310 "Ureines and their derivatives; salts thereof"
cap label var _20144320 "Saccharin and its salts"
cap label var _20144330 "Imides and their derivatives, and salts thereof (excluding saccharin and its salts)"
cap label var _20144340 "Imines and their derivatives; and salts thereof"
cap label var _20144350 "Acrylonitrile"
cap label var _20144360 "1-Cyanoguanidine (dicyandiamide)"
cap label var _20144370 "Nitrile-function compounds (excluding acrylonitrile, 1-cyanoguanidine (dicyandiamide))"
cap label var _20144420 "Diazo-, azo- or azoxy-compounds"
cap label var _20144430 "Organic derivatives of hydrazine or of hydroxylamine"
cap label var _20144450 "Isocyanates"
cap label var _20144490 "Compounds with other nitrogen function (excluding isocyanates)"
cap label var _20145133 "Thiocarbamates and dithiocarbamates; thiuram mono-, di- or tetrasulphides; methionine"
cap label var _20145139 "Other organo-sulphur compounds"
cap label var _20145150 "Organo-inorganic compounds (excluding organo-sulphur compounds)"
cap label var _20145151 "Organo-inorganic compounds (excluding organo-sulphur compounds)"
cap label var _20145210 "Heterocyclic compounds with oxygen only hetero-atom(s) (including coumarin; methylcoumarins and ethylcoumarins) (excluding other lactones)"
cap label var _20145215 "Tetrahydrofuran, 2-Furaldehyde, Furfuryl alcohol, Tetrahydrofurfuryl alcohol and Piperonal"
cap label var _20145225 "Heterocyclic compounds with oxygen only hetero-atom(s) (excluding other lactones)"
cap label var _20145230 "Heterocyclic compounds with nitrogen only hetero-atom(s); containing an unfused imidazole ring (excluding hydantoin and its derivatives)"
cap label var _20145260 "Melamine"
cap label var _20145280 "Compounds containing in the structure an unfused pyridine ring or a quinoline or isoquinoline ring-system, not further fused; lactames; other heterocyclic compounds with nitrogen hetero-atom(s) only (excluding compounds containing in the structure an unfused pyrazole ring, an unfused imidazole ring, a pyrimidine ring, a piperazine ring or an unfused triazine ring)"
cap label var _20145290 "Nucleic acids and other heterocyclic compounds - thiazole, benzothiazole, other cycles"
cap label var _20145350 "Phosphoric esters; and their salts (including lactophosphates; their halogenated; sulphonated; nitrated or nitrosated derivatives)"
cap label var _20145380 "Esters of other inorganic acids of non-metals (excluding esters of hydrogen halides) and their salts; their halogenated, sulphonated, nitrated or nitrosated derivatives"
cap label var _20146111 "Methanal (formaldehyde)"
cap label var _20146113 "Ethanal (acetaldehyde)"
cap label var _20146115 "Butanal (butyraldehyde; normal isomer)"
cap label var _20146119 "Acyclic aldehydes, without other oxygen function (excluding methanal (formaldehyde), ethanal (acetaldehyde), butanal (butyraldehyde; normal isomer))"
cap label var _20146160 "Paraformaldehyde"
cap label var _201461Z0 "Acyclic aldehydes without other oxygen function (excluding methanal, ethanal)"
cap label var _20146211 "Acetone"
cap label var _20146213 "Butanone (methyl ethyl ketone)"
cap label var _20146215 "4-Methylpentan-2-one (methyl isobutyl ketone)"
cap label var _20146219 "Acyclic ketones; without other oxygen function (excluding acetone, butanone (methyl ethyl ketone), 4-methylpentan-2-one (methyl isobutyl ketone))"
cap label var _20146231 "Camphor; aromatic ketones without other oxygen function; ketone-alcohols; ketone-aldehydes; ketone-phenols and ketones with other oxygen function"
cap label var _20146233 "Cyclohexanone and methylcyclohexanones"
cap label var _20146235 "Ionones and methylionones"
cap label var _20146239 "Cyclanic, cyclenic or cycloterpenic ketones without other oxygen function (excluding camphor, cyclohexanone and methylcyclohexanones, ionones and methylionones)"
cap label var _20146260 "Quinones"
cap label var _20146270 "Halogenated; sulphonated; nitrated or nitrosated derivatives of ketones and quinones"
cap label var _201462Z0 "Aromatic ketones without other oxygen function; ketone-alcohols and ketone-aldehydes; ketone-phenols and ketones with other oxygen function; other cyclanic, cyclenic or cycloterpenic ketones without other oxygen function"
cap label var _20146310 "Acyclic ethers and their halogenated, sulphonated, nitrated or nitrosated derivatives"
cap label var _20146323 "Cyclanic, cyclenic or cycloterpenic ethers and their halogenated, sulphonated, nitrated or nitrosated derivatives"
cap label var _20146325 "Aromatic ethers and their halogenated, sulphonated, nitrated or nitrosated derivatives"
cap label var _20146333 "2,2-Oxydiethanol (diethylene glycol; digol)"
cap label var _20146339 "Ether-alcohols and their halogenated, sulphonated, nitrated or nitrosated derivatives (excluding 2,2-Oxydiethanol)"
cap label var _20146373 "Oxirane (ethylene oxide)"
cap label var _20146375 "Methyloxirane (propylene oxide)"
cap label var _20146379 "Epoxides, epoxyalcohols, -phenols, epoxyethers, with a 3-membered ring and their halogenated, sulphonated, nitrated/nitrosated derivatives excluding oxirane, methyloxirane (propylene oxide)"
cap label var _20146380 "Acetals and hemiacetals and their halogenated; sulphonated; nitrated or nitrosated derivatives"
cap label var _20146381 "Acetals and hemiacetals and their halogenated; sulphonated; nitrated or nitrosated derivatives"
cap label var _20146430 "Other organic compounds, n.e.c."
cap label var _20147170 "Wood tar; wood tar oils; wood creosote; wood naphtha; vegetable pitch; brewers’ pitch and similar preparations based on rosin, resin acids or on vegetable pitch"
cap label var _20147320 "Benzol (benzene), toluol (toluene) and xylol (xylenes)"
cap label var _20147340 "Naphthalene and other aromatic hydrocarbon mixtures (excluding benzene, toluene, xylene)"
cap label var _20147360 "Phenols"
cap label var _20147390 "Other oils and oil products, n.e.c."
cap label var _20151050 "Nitric acid; sulphonitric acids"
cap label var _20151075 "Anhydrous ammonia"
cap label var _20151077 "Ammonia in aqueous solution"
cap label var _20152030 "Ammonium chloride"
cap label var _20152080 "Nitrites"
cap label var _20153130 "Urea containing > 45 % by weight of nitrogen on the dry anhydrous product (excluding in tablets or similar forms or in packages of a weight of <= 10 kg)"
cap label var _20153180 "Urea containing <= 45 % by weight of nitrogen on the dry anhydrous product (excluding in tablets or similar forms or in packages of a weight of <= 10 kg)"
cap label var _20153200 "Ammonium sulphate (excluding in tablets or similar forms or in packages of a weight of <= 10 kg)"
cap label var _20153300 "Ammonium nitrate (excluding in tablets or similar forms or in packages of a weight of <= 10 kg)"
cap label var _20153400 "Double salts and mixtures of calcium nitrate and ammonium nitrate (excluding in tablets or similar forms or in packages of a weight of <= 10 kg)"
cap label var _20153530 "Mixtures of ammonium nitrate with calcium carbonate, <= 28 % nitrogen by weight"
cap label var _20153580 "Mixtures of ammonium nitrate with calcium carbonate, > 28 % nitrogen by weight"
cap label var _20153600 "Mixtures of urea and ammonium nitrate in aqueous or ammoniacal solution (excluding in tablets or similar forms or in packages of a weight of <= 10 kg)"
cap label var _20153930 "Double salts and mixtures of ammonium sulphate and ammonium nitrate (excluding in tablets or similar forms or in packages of a weight of <= 10 kg)"
cap label var _20153960 "Mixtures of urea and ammonium nitrate in aqueous or ammoniacal solution (excluding in tablets or similar forms or in packages of a weight of <= 10 kg)"
cap label var _20153990 "Mineral or chemical fertilisers, nitrogenous, n.e.c."
cap label var _20154100 "Superphosphates (excluding potassic, in tablets or similar forms or in packages of a weight of <= 10 kg)"
cap label var _20154900 "Mineral or chemical fertilisers, phosphatic n.e.c."
cap label var _20155100 "Potassium chloride (excluding in tablets or similar forms or in packages of a weight of <= 10 kg)"
cap label var _20155200 "Potassium sulphate (excluding in tablets or similar forms or in packages of a weight of <= 10 kg)"
cap label var _20155900 "Mineral or chemical fertilisers, potassic, n.e.c."
cap label var _20156000 "Sodium nitrate"
cap label var _20157100 "Mineral or chemical fertilisers containing the three fertilising elements nitrogen, phosphorus and potassium (excluding those in tablets or similar forms, or in packages with a gross weight of <= 10 kg)"
cap label var _20157130 "Fertilizers containing nitrogen, phosphorus and potassium, > 10% nitrogen"
cap label var _20157180 "Fertilizers containing nitrogen, phosphorus and potassium, <= 10% nitrogen"
cap label var _20157200 "Diammonium hydrogenorthophosphate (diammonium phosphate) (excluding in tablets or similar forms or in packages of a weight of <= 10 kg)"
cap label var _20157300 "Ammonium dihydrogenorthophosphate (monoammonium phosphate)"
cap label var _20157400 "Other mineral or chemical fertilisers containing the two fertilising elements nitrogen and phosphorus"
cap label var _20157500 "Mineral or chemical fertilisers containing the two fertilising elements phosphorus and potassium"
cap label var _20157600 "Nitrates of potassium"
cap label var _20157930 "Fertilisers in tablets or similar forms or in packages of a gross weight of <= 10 kg)"
cap label var _20157980 "Other fertilisers, n.e.c."
cap label var _20158000 "Animal or vegetable fertilisers"
cap label var _20161035 "Linear polyethylene having a specific gravity < 0,94, in primary forms"
cap label var _20161039 "Polyethylene having a specific gravity < 0,94, in primary forms (excluding linear)"
cap label var _20161050 "Polyethylene having a specific gravity of >= 0,94, in primary forms"
cap label var _20161070 "Ethylene-vinyl acetate copolymers, in primary forms"
cap label var _20161090 "Polymers of ethylene, in primary forms (excluding polyethylene, ethylene-vinyl acetate copolymers)"
cap label var _20162035 "Expansible polystyrene, in primary forms"
cap label var _20162039 "Polystyrene, in primary forms (excluding expansible polystyrene)"
cap label var _20162050 "Styrene-acrylonitrile (SAN) copolymers, in primary forms"
cap label var _20162070 "Acrylonitrile-butadiene-styrene (ABS) copolymers, in primary forms"
cap label var _20162090 "Polymers of styrene, in primary forms (excluding polystyrene, styrene-acrylonitrile (SAN) copolymers, acrylonitrile-butadiene-styrene (ABS) copolymers)"
cap label var _20163010 "Polyvinyl chloride, not mixed with any other substances, in primary forms"
cap label var _20163023 "Non-plasticised polyvinyl chloride mixed with any other substance, in primary forms"
cap label var _20163025 "Plasticised polyvinyl chloride mixed with any other substance, in primary forms"
cap label var _20163040 "Vinyl chloride-vinyl acetate copolymers and other vinyl chloride copolymers, in primary forms"
cap label var _20163060 "Fluoropolymers"
cap label var _20163090 "Polymers of halogenated olefins, in primary forms, n.e.c."
cap label var _20164013 "Polyacetals, in primary forms"
cap label var _20164015 "Polyethylene glycols and other polyether alcohols, in primary forms"
cap label var _20164020 "Polyethers, in primary forms (excluding polyacetals, polyether alcohols)"
cap label var _20164030 "Epoxide resins, in primary forms"
cap label var _20164040 "Polycarbonates, in primary forms"
cap label var _20164050 "Alkyd resins, in primary forms"
cap label var _20164062 "Polyethylene terephthalate in primary forms having a viscosity number of >= 78 ml/g"
cap label var _20164064 "Other polyethylene terephthalate in primary forms"
cap label var _20164070 "Unsaturated liquid polyesters, in primary forms (excluding polyacetals, polyethers, epoxide resins, polycarbonates, alkyd resins, polyethylene terephthalate)"
cap label var _20164080 "Unsaturated polyesters, in primary forms (excluding liquid polyesters, polyacetals, polyethers, epoxide resins, polycarbonates, alkyd resins, polyethylene terephthalate)"
cap label var _20164090 "Polyesters, in primary forms (excluding polyacetals, polyethers, epoxide resins, polycarbonates, alkyd resins, polyethylene terephthalate, other unsaturated polyesters)"
cap label var _20165130 "Polypropylene, in primary forms"
cap label var _20165150 "Polymers of propylene or of other olefins, in primary forms (excluding polypropylene)"
cap label var _20165230 "Polymers of vinyl acetate, in aqueous dispersion, in primary forms"
cap label var _20165250 "Polymers of vinyl acetate, in primary forms (excluding in aqueous dispersion)"
cap label var _20165270 "Polymers of vinyl esters or other vinyl polymers, in primary forms (excluding vinyl acetate)"
cap label var _20165350 "Polymethyl methacrylate, in primary forms"
cap label var _20165390 "Acrylic polymers, in primary forms (excluding polymethyl methacrylate)"
cap label var _20165450 "Polyamide -6, -11, -12, -6,6, -6,9, -6,10 or -6,12, in primary forms"
cap label var _20165490 "Polyamides, in primary forms (excluding polyamide -6, -11, -12, -6,6, -6,9, -6,10 or -6,12)"
cap label var _20165550 "Urea resins and thiourea resins, in primary forms"
cap label var _20165570 "Melamine resins, in primary forms"
cap label var _20165630 "Amino resins, in primary forms (excluding urea and thiourea resins, melamine resins)"
cap label var _20165650 "Phenolic resins, in primary forms"
cap label var _20165670 "Polyurethanes, in primary forms"
cap label var _20165700 "Silicones, in primary forms"
cap label var _20165920 "Petroleum resins, coumarone-indene resins, polyterpenes, polysulphides, polysulphones, etc., n.e.c., in primary forms"
cap label var _20165940 "Cellulose and its chemical derivatives, n.e.c., in primary forms"
cap label var _20165945 "Petroleum resins, coumarone-indene resins, polyterpenes, polysulphides, polysulphones, etc., n.e.c., in primary forms"
cap label var _20165950 "Petroleum resins, coumarone-indene resins, polyterpenes, polysulphides, polysulphones, etc., n.e.c., in primary forms"
cap label var _20165955 "Petroleum resins, coumarone-indene resins, polyterpenes, polysulphides, polysulphones, etc., n.e.c., in primary forms"
cap label var _20165960 "Natural and modified natural polymers, in primary forms (including alginic acid, hardened proteins, chemical derivatives of natural rubber)"
cap label var _20165965 "Petroleum resins, coumarone-indene resins, polyterpenes, polysulphides, polysulphones, etc., n.e.c., in primary forms"
cap label var _20165970 "Ion-exchangers based on synthetic or natural polymers, in primary forms"
cap label var _20171050 "Synthetic latex rubber"
cap label var _20171090 "Synthetic rubber (excluding latex)"
cap label var _20411000 "Glycerol (glycerine), crude; glycerol waters and glycerol lyes"
cap label var _20412020 "Anionic organic surface-active agents (excluding soap)"
cap label var _20412030 "Cationic organic surface-active agents (excluding soap)"
cap label var _20412050 "Non-ionic organic surface-active agents (excluding soap)"
cap label var _20412090 "Organic surface-active agents (excluding soap, anionic, cationic, non-ionic)"
cap label var _20594159 "Lubricants having a bio-based carbon content of at least 25 % by mass and which are biodegradable at a level of at least 60 %"
cap label var _20601110 "Aramids staple, not carded, combed or otherwise processed for spinning"
cap label var _20601120 "Other polyamide tow and staple, not carded, combed or otherwise processed for spinning"
cap label var _20601130 "Polyester tow and staple, not carded, combed or otherwise processed for spinning"
cap label var _20601140 "Acrylic tow and staple, not carded, combed or otherwise processed for spinning"
cap label var _20601150 "Polypropylene synthetic tow and staple not carded, combed or otherwise processed for spinning"
cap label var _20601190 "Other synthetic tow and staple not carded, combed or otherwise processed for spinning"
cap label var _21101030 "Salicylic acid and its salts"
cap label var _21101050 "O-acetylsalicylic acid; its salts and esters"
cap label var _21101070 "Esters of salicylic acid and their salts (excluding of O-acetylsalicylic acid)"
cap label var _21102010 "Lysine and its esters, and salts thereof"
cap label var _21102020 "Glutamic acid and its salts"
cap label var _21102040 "Quaternary ammonium salts and hydroxides; lecithins and other phosphoaminolipids, whether or not chemically defined"
cap label var _21102060 "Acyclic amides and their derivatives, and salts thereof (including acyclic carbamates)"
cap label var _21102070 "Cyclic amides and their derivatives, and salts thereof (including cyclic carbamates) (excluding ureines and their derivatives, and salts thereof)"
cap label var _21103110 "Lactones (excluding coumarin, methylcoumarins and ethylcoumarins)"
cap label var _21103117 "Phenolphthalein; 1-Hydroxy-4-{1-(4-hydroxy-3-methoxycarbonyl-1-naphthyl)-3-oxo-1H,3H-benzo{de}isochromen-1-yl}-6-octadecyloxy-2-naphthoic acid; 3'-Chloro-6'-cyclohexylaminospiro{isobenzofuran-1(3H),9'-xanthen}-3-one; 6'-(N-Ethyl-p-toluidino)-2'-methylspiro{isobenzofuran-1(3H),9'-xanthen}-3-one; Methyl-6-docosyloxy-1-hydroxy-4-{1-(4-hydroxy-3-methyl-1-phenanthryl)-3-oxo-1H,3H-naphtho{1,8-cd}pyran-1-yl}naphthalene-2-carboxylate, gamma-Butyrolactone"
cap label var _21103119 "Lactones (excluding phenolphthalein; 1-Hydroxy-4-{1-(4-hydroxy-3-methoxycarbonyl-1-naphthyl)-3-oxo-1H,3H-benzo{de}isochromen-1-yl}-6-octadecyloxy-2-naphthoic acid; 3’-Chloro-6’-cyclohexylaminospiro{isobenzofuran-1(3H),9’-xanthen}-3-one; 6’-(N-Ethyl-p-toluidino)-2’-methylspiro{isobenzofuran-1(3H),9’-xanthen}-3-one; Methyl-6-docosyloxy-1-hydroxy-4-{1-(4-hydroxy-3-methyl-1-phenanthryl)-3-oxo-1H,3H-naphtho{1,8-cd}pyran-1-yl}naphthalene-2-carboxyla, gamma-Butyrolactone, and inorganic or organic compounds of mercury)"
cap label var _21103130 "Compounds containing an unfused pyrazole ring (whether or not hydrogenated) in the structure"
cap label var _21103140 "Hydantoin and its derivatives"
cap label var _21103155 "Malonylurea (barbituric acid) and its derivatives, and salts thereof"
cap label var _21103159 "Compounds containing a pyrimidine ring (whether or not hydrogenated) or piperazine ring in the structure (excluding malonylurea (barbituric acid) and its derivatives)"
cap label var _21103170 "Compounds containing an unfused triazine ring (whether or not hydrogenated) in the structure (excluding melamine)"
cap label var _21103180 "Compounds containing a phenothiazine ring-system (whether or not hydrogenated); not further fused"
cap label var _21103200 "Sulphonamides"
cap label var _21104000 "Sugars, pure (excluding glucose, etc.); sugar ethers and salts, etc."
cap label var _21105400 "Antibiotics"
cap label var _22191000 "Reclaimed rubber in primary forms or in plates, sheets or strips"
cap label var _23511100 "Cement clinker"
cap label var _23523030 "Calcined and sintered dolomite, crude, roughly trimmed or merely cut into rectangular or square blocks or slabs"
cap label var _23523050 "Agglomerated dolomite (including tarred dolomite)"
cap label var _23523051 "Dolomite ramming mix"
cap label var _23991940 "Calcined kaolin"
cap label var _24106470 "Bars and rods of stainless steel, cold-formed or cold-finished and further worked, or hot-formed and further worked, n.e.s. (excluding forged products)"
cap label var _24106660 "Bars and rods, of alloy steel, cold-formed or cold-finished (e.g. by cold-drawing), painted, coated, clad or further worked (excluding stainless steel)"
cap label var _2410T110 "Pig iron"
cap label var _2410T121 "Crude steel: non-alloy steel produced in electric furnaces"
cap label var _2410T122 "Crude steel: non-alloy steel produced by other processes than in electric furnaces"
cap label var _2410T131 "Crude steel: alloy steel other than stainless steel produced in electric furnaces"
cap label var _2410T132 "Crude steel: alloy steel other than stainless steel produced by other processes than in electric furnaces"
cap label var _2410T141 "Crude steel: stainless and heat resisting steel produced in electric furnaces"
cap label var _2410T142 "Crude steel: stainless and heat resisting steel produced by other processes than in electric furnaces"
cap label var _2410T211 "Hot-rolled flat products in coil (wide strip) of a width of 600 mm or more"
cap label var _2410T212 "Hot-rolled flat products in coil of a width less than 600 mm"
cap label var _2410T221 "Plate and sheet rolled in lengths in wide strip mills"
cap label var _2410T222 "Plate, sheet and wide flat, hot-rolled in mills other than wide strip mills"
cap label var _2410T231 "Hot-rolled wire rod"
cap label var _2410T241 "Concrete reinforcing bars"
cap label var _2410T242 "Other hot-rolled bars"
cap label var _2410T243 "Hot-rolled and forged light sections of a web height of less than 80 mm and angles"
cap label var _2410T244 "Heavy sections"
cap label var _2410T251 "Sheet piling"
cap label var _2410T252 "Railway material"
cap label var _2410T260 "Welded sections"
cap label var _2410T310 "Cold-rolled sheet, plate and strip and blackplate, >= 600 mm wide"
cap label var _2410T320 "Electrical sheet and strip"
cap label var _2410T330 "Tinplate, other tinned sheet and electrically chromium-coated steel (ECCS)"
cap label var _2410T340 "Hot-dipped metal-coated sheet"
cap label var _2410T350 "Electrolytically metal-coated sheet"
cap label var _2410T360 "Organic-coated sheet"
cap label var _24311010 "Bars and rods, of non-alloy free-cutting steel, not further worked than cold-formed or cold-finished (e.g. by cold-drawing)"
cap label var _24311020 "Other bars and rods of iron or non-alloy steel, not further worked than cold-formed or cold-finished (e.g. by cold-drawing), containing by weight < 0,25 % of carbon, of square or other than rectangular cross-section (excluding those of free-cutting steel)"
cap label var _24311030 "Other bars and rods of iron or non-alloy steel, not further worked than cold-formed or cold-finished (e.g. by cold-drawing), containing by weight < 0,25 % of carbon of rectangular ‘other than square’ cross-section (excluding those of free-cutting steel)"
cap label var _24311040 "Other bars and rods of iron or non-alloy steel, cold-formed or cold-finished and further worked, or hot-formed and further worked, n.e.c. (excluding hot-rolled, hot-drawn or hot-extruded, not further worked than clad, and forged products)"
cap label var _24311050 "Other bars and rods of iron or non-alloy steel, not further worked than cold-formed or cold-finished (e.g. by cold-drawing), containing by weight >= 0,25  % of carbon (excluding those of free-cutting steel)"
cap label var _24311060 "Angles, shapes and sections, of iron or non-alloy steel, not further worked than cold-formed or cold-finished (e.g. by cold-drawing) (excluding profiled sheet)"
cap label var _24312010 "Bars and rods, of high-speed steel, not further worked than cold-formed or cold-finished, even further worked, or hot-formed and further worked (excluding forged, semi-finished or flat-rolled products, hot-rolled bars and rods in irregularly wound coils); bars and rods, of silico-manganese steel, only cold-formed or cold-finished or hot-rolled, including further worked (excluding hot-rolled, hot-drawn or extruded, just clad, semi-finished products, flat-rolled products, hot-rolled bars and rods in irregularly wound coils)"
cap label var _24312020 "Bars/rods, 0,9 % to 1,15 % of carbon, 0,5 % to 2 % of chromium and, if present <= 0,5 % of molybdenum, only cold-formed or cold-finished (e.g. by cold-drawing) (excluding semi-finished or flat-rolled products; hot-rolled bars or rods in irregularly wound coils)"
cap label var _24312030 "Bars and rods of tool steel, only cold-formed or cold-finished (e.g. by cold-drawing) (excluding semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)"
cap label var _24312040 "Bars and rods, of alloy steel, not further worked than cold-formed or cold-finished (e.g. by cold-drawing) (excluding stainless steel, high-speed steel, silico-manganese steel, alloy bearing steel, tool steel)"
cap label var _24312050 "Sections, of alloy steel other than stainless, cold-finished or cold-formed (e.g. by cold-drawing)"
cap label var _24313000 "Cold-drawn bars and solid profiles of stainless steel"
cap label var _24411030 "Silver, unwrought or in powder form (including plated with gold or platinum)"
cap label var _24411050 "Silver, in semi-manufactured forms (including plated with gold or platinum) (excluding unwrought or in powder form)"
cap label var _24412030 "Gold, unwrought or in powder form for non-monetary use (including plated with platinum)"
cap label var _24412035 "Gold (including gold plated with platinum), in powder form"
cap label var _24412040 "Gold (including gold plated with platinum), unwrought or in semi-manufactured forms"
cap label var _24412050 "Gold, in semi-manufactured forms for non-monetary use (including plated with platinum) (excluding unwrought or in powder form)"
cap label var _24412070 "Monetary gold (including gold plated with platinum)"
cap label var _24413010 "Platinum. Unwrought or in powder form"
cap label var _24413015 "Palladium. Unwrought or in powder form"
cap label var _24413020 "Rhodium. Unwrought or in powder form"
cap label var _24413025 "Iridium, osmium and ruthenium. Unwrought or in powder form"
cap label var _24413030 "Platinum, palladium, rhodium, iridium, osmium and ruthenium, unwrought or in powder form"
cap label var _24413040 "Platinum in bars, rods, wire and sections; plates; sheets and strips of a thickness, excluding any backing, exceeding 0,15 mm"
cap label var _24413045 "Platinum in semi-manufactured forms"
cap label var _24413050 "Platinum, palladium, rhodium, iridium, osmium and ruthenium, in semi-manufactured forms (excluding unwrought or in powder form)"
cap label var _24413055 "Palladium in semi-manufactured forms"
cap label var _24413060 "Rhodium in semi-manufactured forms"
cap label var _24413065 "Iridium, osmium and ruthenium in semi-manufactured forms"
cap label var _24414000 "Base metals or silver, clad with gold, semi-manufactured but not further worked"
cap label var _24415030 "Base metals clad with silver, semi-manufactured but not further worked"
cap label var _24415050 "Base metals, silver or gold, clad with platinum, semi-manufactured but not further worked"
cap label var _24421130 "Unwrought non-alloy aluminium (excluding powders and flakes)"
cap label var _24421153 "Unwrought aluminium alloys in primary form (excluding aluminium powders and flakes)"
cap label var _24421154 "Unwrought aluminium alloys (excluding aluminium powders and flakes)"
cap label var _24421155 "Unwrought aluminium alloys in secondary form (excluding aluminium powders and flakes)"
cap label var _24421200 "Aluminium oxide (excluding artificial corundum)"
cap label var _24422100 "Aluminium powders and flakes (excluding prepared powders or flakes for use as colours, paints or the like)"
cap label var _24422230 "Aluminium bars, rods and profiles (excluding rods and profiles prepared for use in structures)"
cap label var _24422250 "Aluminium alloy bars, rods, profiles and hollow profiles (excluding rods and profiles prepared for use in structures)"
cap label var _24422330 "Non-alloy aluminium wire (excluding insulated electric wire and cable, twine and cordage reinforced with aluminium wire, stranded wire and cables)"
cap label var _24422350 "Aluminium alloy wire (excluding insulated electric wire and cable, twine and cordage reinforced with aluminium wire, stranded wire and cables)"
cap label var _24422430 "Aluminium plates, sheets and strips > 0,2 mm thick"
cap label var _24422450 "Aluminium alloy plates, sheets and strips > 0,2 mm thick"
cap label var _24422500 "Aluminium foil of a thickness (excluding any backing) <= 0,2 mm"
cap label var _24422630 "Aluminium tubes and pipes (excluding hollow profiles, tube or pipe fittings, flexible tubing, tubes and pipes prepared for use in structures, machinery or vehicle parts, or the like)"
cap label var _24422650 "Aluminium alloy tubes and pipes (excluding hollow profiles, tubes or pipe fittings, flexible tubing, tubes and pipes prepared for use in structures, machinery or vehicle parts, or the like)"
cap label var _24422670 "Aluminium tube or pipe fittings (including couplings, elbows and sleeves) (excluding fittings with taps, cocks and valves, tube supports, bolts and nuts, clamps)"
cap label var _24431130 "Refined unwrought lead (excluding lead powders or flakes)"
cap label var _24431150 "Unwrought lead containing antimony (excluding lead powders or flakes)"
cap label var _24431190 "Unwrought lead (excluding lead powders or flakes, unwrought lead containing antimony, refined)"
cap label var _24431230 "Unwrought non-alloy zinc (excluding zinc dust, powders and flakes)"
cap label var _24431250 "Unwrought zinc alloys (excluding zinc dust, powders and flakes)"
cap label var _24431330 "Unwrought non-alloy tin (excluding tin powders and flakes)"
cap label var _24431350 "Unwrought tin alloys (excluding tin powders and flakes)"
cap label var _24432100 "Lead plates, sheets, strip and foil; lead powders and flakes (excluding lead powders or flakes prepared as colours; paints or the like, insulated electric strip)"
cap label var _24432200 "Zinc dust, powders and flakes (excluding zinc dust powders or flakes prepared as colours, paints or the like, zinc pellets)"
cap label var _24432300 "Zinc bars, rods, profiles, wire, plates, sheets, strip and foil"
cap label var _24432400 "Tin bars, rods, profiles and wires"
cap label var _24441100 "Copper mattes; cement copper (precipitated copper) (excluding copper powder)"
cap label var _24441200 "Unrefined copper, copper anodes for electrolytic refining (including blister copper) (excluding electrocopper-plating, electroplating anodes)"
cap label var _24441330 "Unwrought unalloyed refined copper (excluding rolled, extruded or forged sintered products)"
cap label var _24441370 "Unwrought copper alloys (excluding rolled, extruded or forged sintered products); master alloys of copper (including alloys which are not usefully malleable) (excluding copper phosphide (phosphor copper) containing > 15 % by weight of phosphorous)"
cap label var _24442100 "Copper powders and flakes excluding cement copper, powders/flake powders used in the preparation of paints such as bronzes/golds, (chemical compounds), refined copper shot"
cap label var _24442200 "Copper and copper alloy bars, rods, profiles and hollow profiles (excluding bars and rods obtained by casting or sintering, copper wire rod in coils)"
cap label var _24442330 "Copper wire, refined (transv. section > 6 mm), of copper alloy"
cap label var _24442350 "Copper wire with cross-sectional dimension > 0,5 mm, <= 6 mm (excluding twine or cord reinforced with wire, stranded wire and cables)"
cap label var _24442370 "Copper wire with cross-sectional dimension <= 0,5 mm (excluding twine or cord reinforced with wire, stranded wire and cables)"
cap label var _24442400 "Copper and copper alloy plates, sheets and strip of a thickness > 0,15 mm (excluding expanded copper metal, insulated electric strip)"
cap label var _24442500 "Copper foil, of a thickness (excluding any backing) <= 0,15 mm"
cap label var _24442630 "Copper tubes and pipes"
cap label var _24442650 "Copper and copper alloy tube/pipe fittings including couplings, elbows, sleeves, tees and joints excluding bolts and nuts used for assembling/fixing pipes/tubes, fittings with taps, cocks, valves"
cap label var _24451100 "Nickel, unwrought"
cap label var _24451110 "Nickel, not alloyed, unwrought"
cap label var _24451120 "Unwrought nickel alloys"
cap label var _24451200 "Nickel mattes, nickel oxide sinters and other intermediate products of nickel metallurgy (including impure nickel oxides, nickel speiss, impure ferro-nickel)"
cap label var _24451210 "Nickel mattes"
cap label var _24451220 "Nickel mattes"
cap label var _24452100 "Nickel powders and flakes (excluding nickel oxide sinters)"
cap label var _24452200 "Nickel and nickel alloy bars, rods, profiles and wires (excluding prepared bars, rods or profiles for use in structures, insulated electric bars and wire, enamelled wire)"
cap label var _24452300 "Nickel and nickel alloy plate, sheet, strip and foil (excluding expanded metal)"
cap label var _24452400 "Nickel tubes, pipes and tube or pipe fittings"
cap label var _24453013 "Tungsten (wolfram) and articles thereof (excluding waste and scrap), n.e.c."
cap label var _24453014 "Tungsten powder and unwrought tungsten, incl. bars and rods obtained simply by sintering"
cap label var _24453015 "Tungsten and articles thereof; bars and rods, other than those obtained simply by sintering, profiles, wire, plates, sheets, strip and foil"
cap label var _24453017 "Molybdenum and articles thereof (excluding waste and scrap), n.e.c."
cap label var _24453020 "Tantalum, unwrought, incl. bars and rods of tantalum obtained simply by sintering; tantalum powder"
cap label var _24453021 "Tantalum and articles thereof. Bars and rods, other than those obtained simply by sintering, profiles, wire, plates, sheets, strip and foil"
cap label var _24453022 "Other articles of tantalum (excluding waste and scrap), n.e.s."
cap label var _24453023 "Tantalum and articles thereof (excluding waste and scrap), n.e.c."
cap label var _24453024 "Unwrought magnesium, containing >= 99,8% by weight of magnesium"
cap label var _24453025 "Magnesium and articles thereof (excluding waste and scrap), n.e.c."
cap label var _24453026 "Unwrought magnesium, containing < 99,8% by weight of magnesium"
cap label var _24453027 "Cobalt mattes and other intermediate products of cobalt metallurgy; cobalt and articles thereof (excluding waste and scrap), n.e.c."
cap label var _24453028 "Other articles of magnesium (excluding waste and scrap), n.e.s."
cap label var _24453030 "Bismuth and articles thereof, including waste and scrap, n.e.c.; cadmium and articles thereof (excluding waste and scrap), n.e.c."
cap label var _24453031 "Unwrought bismuth; bismuth powders; (excluding waste and scrap)"
cap label var _24453032 "Articles of bismuth, n.e.s. (excluding waste and scrap)"
cap label var _24453033 "Cadmium and articles thereof (excluding waste and scrap), n.e.c."
cap label var _24453034 "Unwrought cadmium; cadmium powders (excluding waste and scrap)"
cap label var _24453035 "Cobalt mattes and other intermediate products of cobalt metallurgy; unwrought cobalt; powders (excl. cobalt waste and scrap)"
cap label var _24453036 "Articles of cobalt, n.e.s."
cap label var _24453037 "Other cadmium and articles thereof (excluding waste and scrap, cadmium powders and unwrought cadmium), n.e.c."
cap label var _24453038 "Bismuth and articles thereof containing more than 99,99 % of bismuth, by weight (excluding waste and scrap)"
cap label var _24453039 "Bismuth and articles thereof containing ? 99,99 % of bismuth, by weight (excluding waste and scrap)"
cap label var _24453041 "Titanium, unwrought; powders"
cap label var _24453042 "Titanium and articles thereof; bars and rods, profiles, wire, plates, sheets, strip and foil, tubes and pipes, other (excluding waste and scrap)"
cap label var _24453043 "Titanium and articles thereof (excluding waste and scrap), n.e.c."
cap label var _24453045 "Antimony. Unwrought antimony; powders"
cap label var _24453046 "Antimony and articles thereof (excluding unwrought antimony; powders; waste and scrap)"
cap label var _24453047 "Zirconium and articles thereof (excluding waste and scrap), n.e.c.; antimony and articles thereof (excluding waste and scrap), n.e.c."
cap label var _24453048 "Zirconium and articles thereof (excluding waste and scrap), n.e.c."
cap label var _24453049 "Unwrought zirconium; zirconium powders (excluding waste and scrap)"
cap label var _24453050 "Other zirconium and articles thereof (excluding waste and scrap, zirconium powders and unwrought zirconium), n.e.c."
cap label var _24453055 "Beryllium, chromium, germanium, vanadium, gallium, hafnium (‘celtium’), indium, niobium (‘columbium’), rhenium and thallium, and articles of these metals, n.e.c.; waste and scrap of these metals (excluding of beryllium, chromium and thallium)"
cap label var _24453057 "Manganese and articles thereof, including waste and scrap, n.e.c.; cermets and articles thereof, including waste and scrap, n.e.c."
cap label var _24453058 "Germanium and articles thereof (excluding waste and scrap, germanium powders and unwrought germanium), n.e.c."
cap label var _24453059 "Unwrought niobium; niobium powders (excluding waste and scrap)"
cap label var _24453060 "Unwrought beryllium; beryllium powders"
cap label var _24453061 "Articles of beryllium, n.e.s. (excluding waste and scrap)"
cap label var _24453062 "Unwrought hafnium "celtium"; hafnium powders;"
cap label var _24453063 "Articles of hafnium "celtium" and germanium, n.e.s."
cap label var _24453064 "Unwrought niobium "columbium" and rhenium; niobium "columbium" or rhenium powders"
cap label var _24453065 "Articles of niobium "columbium" or rhenium, n.e.s."
cap label var _24453066 "Niobium "columbium", rhenium, gallium, indium, vanadium and germanium waste and scrap (excl. ashes and residues containing these metals)"
cap label var _24453067 "Niobium (columbium) and articles thereof (excluding waste and scrap, niobium powders and unrought niobium), n.e.c."
cap label var _24453068 "Unwrought hafnium; hafnium powders (excluding waste and scrap)"
cap label var _24453069 "Other hafnium and articles thereof (excluding waste and scrap. hafnium powders and unwrought hafnium), n.e.c."
cap label var _24453070 "Unwrought indium; indium powders"
cap label var _24453071 "Articles of gallium, indium and vanadium, n.e.s."
cap label var _24453072 "Indium and articles thereof (other than unwrought, waste and scrap and powders) n.e.c."
cap label var _24453073 "Unwrought gallium; gallium powders"
cap label var _24453074 "Gallium and articles thereof (other than unwrought, waste and scrap and powders) n.e.c."
cap label var _24453075 "Vanadium and articles thereof (other than unwrought, waste and scrap and powders) n.e.c."
cap label var _24453076 "Unwrought vanadium; vanadium powders (excl. ash and residues containing vanadium)"
cap label var _24453079 "Unwrought germanium; germanium powders"
cap label var _24453082 "Chromium and thallium, and articles of these metals, n.e.c.; (excluding waste and scrap of these metals)"
cap label var _24453085 "Manganese. Unwrought manganese; powders"
cap label var _24453086 "Manganese waste and scrap (excl. ash and residues containing manganese)"
cap label var _24453087 "Articles of manganese, n.e.s."
cap label var _24453090 "Cermets and articles thereof, n.e.s.; waste and scrap of cermets (excl. ash and residues containing cermets)"
cap label var _24453091 "Cermets unwrought"
cap label var _24453092 "Cermets and articles thereof (excluding unwrought)"
cap label var _24453093 "Chromium unwrought; powders"
cap label var _24453094 "Chromium and articles thereof  (excluding unwrought and powders)"
cap label var _24453095 "Thallium unwrought; powders"
cap label var _24453096 "Thallium and articles thereof (excluding unwrought and powders)"
cap label var _24453097 "Unwrought rhenium; rhenium powders (excluding waste and scrap)"
cap label var _24453098 "Other rhenium and articles thereof (excluding waste and scrap, rhenium powders and unwrought rhenium), n.e.c."
cap label var _244530Z1 "Articles of gallium, indium and vanadium (other than unwrought, waste and scrap and powders), n.e.s."
cap label var _24512000 "Tubes, pipes and hollow profiles of cast iron excluding tubes, pipes, hollow profiles made into identifiable parts of articles, such as sections of central heating radiators and machinery parts"
cap label var _24513030 "Tube or pipe fittings, of non-malleable cast iron"
cap label var _24513050 "Tube or pipe fittings of malleable cast iron"
cap label var _24513051 "Tube or pipe fittings of cast iron (excl. of non-malleable cast iron)"
cap label var _24523000 "Tube or pipe fittings of cast steel"
cap label var _24523010 "Cast tube or pipe fittings of steel"
cap label var _25992960 "Other articles of tin, n.e.c."
cap label var _25992963 "Tin plates, sheets and strip, of a thickness > 0,2 mm; tin foil (whether or not printed or backed with paper, paperboard, plastics or similar backing materials), of a thickness (excluding any backing) <= 0,2 mm; tin powders and flakes; tin tubes, pipes and tube or pipe fittings (for example, couplings, elbows, sleeves)"
cap label var _25992971 "Zinc tubes, pipes and tube or pipe fittings (couplings, elbows, sleeves)"
cap label var _25992972 "Articles of zinc, n.e.c."
cap label var _25992974 "Other articles of lead, n.e.c."
cap label var _25992975 "Lead tubes, pipes, and tube or pipe fittings (couplings, elbows, sleeves)"
cap label var _25992976 "Lead bars, rods, profiles and wire (excluding coated rods, cast rods intended for rolling, drawing or for re-casting into shaped articles, bars and rods by sintering, insulated electric wire)"
cap label var _38322100 "Secondary raw materials of platinum group metals"
cap label var _38322110 "Secondary raw material of silver"
cap label var _38322200 "Secondary raw materials of ferrous metals: iron"
cap label var _38322300 "Secondary raw materials of copper"
cap label var _38322400 "Secondary raw materials of nickel"
cap label var _38322500 "Secondary raw materials of aluminium"
cap label var _38322901 "Secondary raw materials of cobalt"
cap label var _38322902 "Secondary raw materials of lithium"
cap label var _38322903 "Secondary raw materials of rare earth metals"
cap label var _38322910 "Secondary raw materials of other metals"
cap label var _38322940 "Slag sands"
cap label var _399900Z7 "Kaolin"
cap label var _399900Z9 "Tube or pipe fittings of cast iron and cast steel"
cap label var _399901Z0 "Bismuth and articles thereof; unwrought hafnium, hafnium powders; secondary raw materials of other metals (excluding of precious metals, iron, copper, nickel, aluminium, cobalt, lithium and rare earth metals)"
