cap label var CODE "Label - English"
cap label var TOTAL "Total area"
cap label var LAND "Land area"
cap label var DZT "Area affected by desertification"
cap label var PRY_A00 "Productivity of artificial land"
cap label var A00 "Artificial land"
cap label var A10 "Built-up area"
cap label var A11 "Buildings with 1 to 3 floors"
cap label var A12 "Buildings with more than 3 floors"
cap label var A13 "Greenhouses"
cap label var A20 "Artificial, non built-up area"
cap label var A21 "Artificial, non built-up area feature"
cap label var A22 "Artificial, non built-up linear feature"
cap label var A30 "Other artificial areas"
cap label var B00 "Cropland"
cap label var B00_PI "Photo interpreted crops"
cap label var B10_50_PI "Photo interpreted non permanent crops"
cap label var B70_80_PI "Photo interpreted permanent crops"
cap label var B10 "Cereals"
cap label var B11 "Common wheat"
cap label var B12 "Durum wheat"
cap label var B13 "Barley"
cap label var B14 "Rye"
cap label var B15 "Oats"
cap label var B16 "Maize"
cap label var B17 "Rice"
cap label var B18 "Triticale"
cap label var B19 "Other cereals"
cap label var B20 "Root and tuber vegetables"
cap label var B21 "Potatoes"
cap label var B22 "Sugar beet"
cap label var B23 "Other root and tuber vegetables"
cap label var B30 "Non permanent industrial crops"
cap label var B31 "Sunflower"
cap label var B32 "Rape and turnip rape"
cap label var B33 "Soya"
cap label var B34 "Cotton"
cap label var B35 "Other fibre and oleaginous crops"
cap label var B36 "Tobacco"
cap label var B37 "Other non permanent industrial crops"
cap label var B40 "Dry pulses, fresh vegetables and ornamental plants"
cap label var B41 "Dry pulses"
cap label var B42 "Tomatoes"
cap label var B43 "Other fresh vegetables"
cap label var B44 "Floriculture and ornamental plants"
cap label var B45 "Strawberries"
cap label var B50 "Fodder crops"
cap label var FOA_NFOA "Forage area and non-forage area"
cap label var FOA "Forage area"
cap label var NFOA "Non-forage area"
cap label var B51 "Clover"
cap label var B52 "Lucerne"
cap label var B53 "Other legumes and mixtures for fodder"
cap label var B54 "Mixed cereals for fodder"
cap label var B55 "Temporary grassland"
cap label var B70 "Fruit trees and berries"
cap label var B71 "Apple trees"
cap label var B72 "Pear trees"
cap label var B73 "Cherry trees"
cap label var B74 "Nut trees"
cap label var B75 "Other fruit trees and berries"
cap label var B76 "Orange trees"
cap label var B77 "Other citrus trees"
cap label var B80 "Other permanent crops"
cap label var B81 "Olive trees"
cap label var B82 "Vineyard"
cap label var B83 "Nurseries"
cap label var B84 "Permanent industrial crops"
cap label var C00 "Woodland"
cap label var TOT_FAO "Forest and other wooded land (FAO)"
cap label var FOR_FAO "Forest (FAO)"
cap label var OWL_FAO "Other wooded land (FAO)"
cap label var OWL_NFAO "Other wooded land (not FAO)"
cap label var C10 "Broadleaved woodland"
cap label var C20 "Coniferous woodland"
cap label var C21 "Spruce dominated coniferous woodland"
cap label var C22 "Pine dominated coniferous woodland"
cap label var C23 "Other coniferous woodland"
cap label var C30 "Mixed woodland"
cap label var C31 "Spruce dominated mixed woodland"
cap label var C32 "Pine dominated mixed woodland"
cap label var C33 "Other mixed woodland"
cap label var D00 "Shrubland"
cap label var D10 "Shrubland with sparse tree cover"
cap label var D20 "Shrubland without tree cover"
cap label var E00 "Grassland"
cap label var E10 "Grassland with sparse tree or shrub cover"
cap label var E20 "Grassland without tree or shrub cover"
cap label var E30 "Spontaneous vegetation"
cap label var F00 "Bare land"
cap label var F10 "Rocks and stones"
cap label var F20 "Sand"
cap label var F30 "Lichens and moss"
cap label var F40 "Other bare soil"
cap label var G00 "Water"
cap label var G10 "Inland water body"
cap label var G11 "Inland fresh water body"
cap label var G12 "Inland salty water body"
cap label var G20 "Inland running water"
cap label var G21 "Inland fresh running water"
cap label var G22 "Inland salty running water"
cap label var G30 "Transitional water body"
cap label var G40 "Sea and ocean"
cap label var G50 "Glacier, permanent snow"
cap label var H00 "Wetland"
cap label var H10 "Inland wetland"
cap label var H11 "Inland marsh"
cap label var H12 "Peatbog"
cap label var H20 "Coastal wetland"
cap label var H21 "Salt-marsh"
cap label var H22 "Salines and other chemical deposits"
cap label var H23 "Intertidal flat"
cap label var RAT_LAND "Ratio of land consumption rate to population growth rate (number)"
