cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var OGA_TAOLA "Tourism, accommodation and other leisure activities"
cap label var OGA_HC "Handicraft"
cap label var OGA_PCS_FPRD "Processing of farm products"
cap label var OGA_PRD_REN "Production of renewable energy"
cap label var OGA_WPCS "Wood processing"
cap label var OGA_AQUA "Aquaculture"
cap label var OGA_ACW "Agricultural contractual work (using production means of the holding)"
cap label var OGA_NACW "Non-agricultural contractual work (using production means of the holding)"
cap label var OGA_FOR "Forestry"
cap label var OGA_HSES "Provision of health, social or educational services"
cap label var OGA_OTH "Other gainful activities related to the agricultural holding n.e.c."
