cap label var TOTAL "Total"
cap label var WRK "Income from work"
cap label var WORK "Income from work"
cap label var PRV "Private sources"
cap label var PRIV "Private sources"
cap label var SOC_TRF "Social transfers"
cap label var SOC_TRF_PEN "Social transfers including pensions"
cap label var SOC_TRF_X_PEN "Social transfers excluding pensions"
cap label var PRIM "Primary income"
cap label var PRIMARY "Primary income"
cap label var SEC "Secondary income"
cap label var SECONDARY "Secondary income"
cap label var UNK "Unknown"
