cap label var CODE "Label - English"
cap label var EUR "Europe"
cap label var EU "European Union (EU6-1958, EU9-1973, EU10-1981, EU12-1986, EU15-1995, EU25-2004, EU27-2007, EU28-2013, EU27-2020)"
cap label var EU27_2020 "European Union - 27 countries (from 2020)"
cap label var EU28 "European Union - 28 countries (2013-2020)"
cap label var EU27_2007 "European Union - 27 countries (2007-2013)"
cap label var EU25 "European Union - 25 countries (2004-2006)"
cap label var EU15 "European Union - 15 countries (1995-2004)"
cap label var EA "Euro area (EA11-1999, EA12-2001, EA13-2007, EA15-2008, EA16-2009, EA17-2011, EA18-2014, EA19-2015, EA20-2023)"
cap label var EA20 "Euro area – 20 countries (from 2023)"
cap label var BE "Belgium"
cap label var BG "Bulgaria"
cap label var CZ "Czechia"
cap label var DK "Denmark"
cap label var DE "Germany"
cap label var DEW "Federal Republic of Germany (former territory of the FRG only)"
cap label var EX_DD "German Democratic Republic"
cap label var EE "Estonia"
cap label var IE "Ireland"
cap label var EL "Greece"
cap label var ES "Spain"
cap label var FR "France"
cap label var YT "Mayotte (FR - part of EU as of 01.01.2014)"
cap label var HR "Croatia"
cap label var IT "Italy"
cap label var CY "Cyprus"
cap label var LV "Latvia"
cap label var LT "Lithuania"
cap label var LU "Luxembourg"
cap label var HU "Hungary"
cap label var MT "Malta"
cap label var NL "Netherlands"
cap label var AT "Austria"
cap label var PL "Poland"
cap label var PT "Portugal"
cap label var RO "Romania"
cap label var SI "Slovenia"
cap label var SK "Slovakia"
cap label var FI "Finland"
cap label var SE "Sweden"
cap label var EU_OTH "Other EU countries"
cap label var EU27_2020_EFTA_FOR "EU27 countries (from 2020) or EFTA countries except reporting country"
cap label var EU28_EFTA_FOR "EU28 countries (2013-2020) or EFTA countries except reporting country"
cap label var EU_FOR "EU-countries except reporting country"
cap label var EU27_2020_FOR "EU27 countries (from 2020) except reporting country"
cap label var EU28_FOR "EU28 countries (2013-2020) except reporting country"
cap label var EU27_2007_FOR "EU27 countries (2007-2013) except reporting country"
cap label var EU25_FOR "EU25 countries (2004-2006) except reporting country"
cap label var EU15_FOR "EU15 countries (1995-2004) except reporting country"
cap label var EEA "European Economic Area (EEA18-1995, EEA28-2004, EEA30-2007, EEA31-2013, EEA30-2020)"
cap label var EFTA "European Free Trade Association"
cap label var IS "Iceland"
cap label var LI "Liechtenstein"
cap label var NO "Norway"
cap label var CH "Switzerland"
cap label var EFTA_FOR "European Free Trade Association except reporting country"
cap label var EFTA_OTH "Other European Free Trade Association countries"
cap label var UK "United Kingdom"
cap label var UK_OCT "British overseas countries and territories"
cap label var CC9_23_FOR "Candidate countries from 2023 (9 countries) except reporting country"
cap label var CC8_22_FOR "Candidate countries from 2022 (8 countries) except reporting country"
cap label var CC5_15_FOR "Candidate countries from 2015 (5 countries) except reporting country"
cap label var CC5_13_FOR_X_IS "Candidate countries in 2013 (5 countries) except reporting country and Iceland"
cap label var CC4_10 "Candidate countries in 2010 (4 countries)"
cap label var CC3_07 "Candidate countries in 2007 (3 countries)"
cap label var BA "Bosnia and Herzegovina"
cap label var ME "Montenegro"
cap label var MD "Moldova"
cap label var MK "North Macedonia"
cap label var GE "Georgia"
cap label var AL "Albania"
cap label var RS "Serbia"
cap label var TR "Türkiye"
cap label var UA "Ukraine"
cap label var XK "Kosovo*"
cap label var EUR_C_E "Central and Eastern Europe"
cap label var EUR_C_E_OTH "Other Central and Eastern European countries"
cap label var AD "Andorra"
cap label var BY "Belarus"
cap label var GG "Guernsey"
cap label var JE "Jersey"
cap label var FO "Faroes"
cap label var GI "Gibraltar"
cap label var VA "Holy See"
cap label var IM "Isle of Man"
cap label var MC "Monaco"
cap label var RU "Russia"
cap label var SM "San Marino"
cap label var CZ_SK "Czechoslovakia"
cap label var RS_ME "Serbia and Montenegro"
cap label var EX_YU "Yugoslavia"
cap label var EX_SU "Soviet Union"
cap label var EX_SU_EUR "European Republics of the former Soviet Union"
cap label var EXT "Countries other than EU, EFTA and Candidate countries"
cap label var HDC_EXT "Highly developed countries (other than EU, EFTA and Candidate countries)"
cap label var MDC_EXT "Medium developed countries (other than EU, EFTA and Candidate countries)"
cap label var LDC_EXT "Less developed countries (other than EU, EFTA and Candidate countries)"
cap label var EXT_EU27_2020 "Extra-EU27 (from 2020)"
cap label var EXT_EU28 "Extra-EU28 (2013-2020)"
cap label var EXT_EU27_2007 "Extra-EU27 (2007-2013)"
cap label var EXT_EU15 "Extra-EU15 (1995-2004)"
cap label var EXT_FOR_HDI "Countries other than EU, EFTA and Candidate countries with Human Development Index (HDI) ranking"
cap label var EXT_FOR_HDI_VH "Countries other than EU, EFTA and Candidate countries with very high Human Development Index (HDI)"
cap label var EXT_FOR_HDI_H "Countries other than EU, EFTA and Candidate countries with high Human Development Index (HDI)"
cap label var EXT_FOR_HDI_M "Countries other than EU, EFTA and Candidate countries with medium Human Development Index (HDI)"
cap label var EXT_FOR_HDI_L "Countries other than EU, EFTA and Candidate countries with low Human Development Index (HDI)"
cap label var NEU "Non-EU countries (aggregate changing according to the context)"
cap label var NEU_HDI_H "Non-EU countries with high Human Development Index (HDI)"
cap label var NEU_HDI_M "Non-EU countries with medium Human Development Index (HDI)"
cap label var NEU_HDI_L "Non-EU countries with low Human Development Index (HDI)"
cap label var NEU_NHDI "Non-EU countries with no Human Development Index (HDI) ranking"
cap label var NEU27_2020_NEFTA "Non-EU27 countries (from 2020) nor EFTA countries"
cap label var NEU28_NEFTA "Non-EU28 countries (2013-2020) nor EFTA countries"
cap label var NEU27_2020 "Non-EU27 countries (from 2020)"
cap label var NEU_FOR "Non-EU countries nor reporting country (aggregate changing according to the context)"
cap label var NEU27_2020_FOR "Non-EU27 countries (from 2020) nor reporting country"
cap label var NEU28_FOR "Non-EU28 countries (2013-2020) nor reporting country"
cap label var NEU27_2007_FOR "Non-EU27 countries (2007-2013) nor reporting country"
cap label var NEU27_2007_FOR_STLS "Non-EU27 countries (2007-2013) nor reporting country and stateless"
cap label var NEU15_FOR "Non-EU15 countries (1995-2004) nor reporting country"
cap label var EUR_NEU "European non-EU countries (aggregate changing according to the context)"
cap label var EUR_NEU15 "European non-EU15 countries (1995-2004)"
cap label var EUR_OTH "Other European countries (aggregate changing according to the context)"
cap label var AFR "Africa"
cap label var AFR_C "Central Africa"
cap label var AO "Angola"
cap label var CM "Cameroon"
cap label var CF "Central African Republic"
cap label var TD "Chad"
cap label var CG "Congo"
cap label var CD "Democratic Republic of the Congo"
cap label var GQ "Equatorial Guinea"
cap label var GA "Gabon"
cap label var ST "São Tomé and Príncipe"
cap label var AFR_E "Eastern Africa"
cap label var BI "Burundi"
cap label var KM "Comoros"
cap label var DJ "Djibouti"
cap label var ER "Eritrea"
cap label var ET "Ethiopia"
cap label var KE "Kenya"
cap label var MG "Madagascar"
cap label var MW "Malawi"
cap label var MU "Mauritius"
cap label var MZ "Mozambique"
cap label var RW "Rwanda"
cap label var SC "Seychelles"
cap label var SO "Somalia"
cap label var UG "Uganda"
cap label var TZ "Tanzania"
cap label var ZM "Zambia"
cap label var ZW "Zimbabwe"
cap label var AFR_N "Northern Africa"
cap label var DZ "Algeria"
cap label var EG "Egypt"
cap label var LY "Libya"
cap label var MA "Morocco"
cap label var SS "South Sudan"
cap label var SD "Sudan"
cap label var TN "Tunisia"
cap label var EH "Western Sahara"
cap label var AFR_S "Southern Africa"
cap label var BW "Botswana"
cap label var LS "Lesotho"
cap label var NA "Namibia"
cap label var ZA "South Africa"
cap label var SZ "Eswatini"
cap label var AFR_W "Western Africa"
cap label var BJ "Benin"
cap label var BF "Burkina Faso"
cap label var CV "Cabo Verde"
cap label var CI "Côte d’Ivoire"
cap label var GM "Gambia, The"
cap label var GH "Ghana"
cap label var GN "Guinea"
cap label var GW "Guinea-Bissau"
cap label var LR "Liberia"
cap label var ML "Mali"
cap label var MR "Mauritania"
cap label var NE "Niger"
cap label var NG "Nigeria"
cap label var SH "Saint Helena, Ascension and Tristan da Cunha"
cap label var SN "Senegal"
cap label var SL "Sierra Leone"
cap label var TG "Togo"
cap label var AFR_OTH "Other African countries (aggregate changing according to the context)"
cap label var AME "America"
cap label var AME_N "Northern America"
cap label var BM "Bermuda"
cap label var CA "Canada"
cap label var GL "Greenland"
cap label var PM "Saint Pierre and Miquelon"
cap label var US "United States"
cap label var AME_N_OTH "Other Northern American countries"
cap label var AME_X_N "Caribbean, Central and South America"
cap label var CRB "Caribbean"
cap label var AI "Anguilla"
cap label var AG "Antigua and Barbuda"
cap label var AW "Aruba"
cap label var BS "Bahamas"
cap label var BB "Barbados"
cap label var BQ "Bonaire, Saint Eustatius and Saba"
cap label var VG "British Virgin Islands"
cap label var KY "Cayman Islands"
cap label var CU "Cuba"
cap label var CW "Curaçao"
cap label var DM "Dominica"
cap label var DO "Dominican Republic"
cap label var GD "Grenada"
cap label var HT "Haiti"
cap label var JM "Jamaica"
cap label var MS "Montserrat"
cap label var AN "Netherlands Antilles"
cap label var PR "Puerto Rico"
cap label var BL "Saint Barthélemy"
cap label var KN "Saint Kitts and Nevis"
cap label var LC "Saint Lucia"
cap label var MF "Saint Martin"
cap label var VC "Saint Vincent and the Grenadines"
cap label var SX "Sint Maarten"
cap label var TT "Trinidad and Tobago"
cap label var TC "Turks and Caicos Islands"
cap label var CRB_OTH "Other Caribbean countries"
cap label var AME_C_S "Central and South America"
cap label var AME_C "Central America"
cap label var BZ "Belize"
cap label var CR "Costa Rica"
cap label var SV "El Salvador"
cap label var GT "Guatemala"
cap label var HN "Honduras"
cap label var MX "Mexico"
cap label var NI "Nicaragua"
cap label var PA "Panama"
cap label var AME_C_OTH "Other Central American countries"
cap label var AME_S "South America"
cap label var AR "Argentina"
cap label var BO "Bolivia"
cap label var BR "Brazil"
cap label var CL "Chile"
cap label var CO "Colombia"
cap label var EC "Ecuador"
cap label var FK "Falkland Islands"
cap label var GY "Guyana"
cap label var PY "Paraguay"
cap label var PE "Peru"
cap label var SR "Suriname"
cap label var UY "Uruguay"
cap label var VE "Venezuela"
cap label var AME_S_OTH "Other South American countries"
cap label var AME_X_N_OTH "Other Caribbean, Central and South American countries"
cap label var AME_OTH "Other American countries (aggregate changing according to the context)"
cap label var ASI "Asia"
cap label var ASI_C "Central Asia"
cap label var KZ "Kazakhstan"
cap label var KG "Kyrgyzstan"
cap label var TJ "Tajikistan"
cap label var TM "Turkmenistan"
cap label var UZ "Uzbekistan"
cap label var ASI_E "Eastern Asia"
cap label var CN "China"
cap label var CN_X_HK "China except Hong Kong"
cap label var HK "Hong Kong"
cap label var MO "Macao"
cap label var JP "Japan"
cap label var MN "Mongolia"
cap label var KP "North Korea"
cap label var KR "South Korea"
cap label var TW "Taiwan"
cap label var ASI_S "Southern Asia"
cap label var AF "Afghanistan"
cap label var BD "Bangladesh"
cap label var BT "Bhutan"
cap label var IN "India"
cap label var IR "Iran"
cap label var MV "Maldives"
cap label var NP "Nepal"
cap label var PK "Pakistan"
cap label var LK "Sri Lanka"
cap label var ASI_S_E "South-Eastern Asia"
cap label var BN "Brunei Darussalam"
cap label var KH "Cambodia"
cap label var ID "Indonesia"
cap label var LA "Laos"
cap label var MY "Malaysia"
cap label var MM "Myanmar/Burma"
cap label var PH "Philippines"
cap label var SG "Singapore"
cap label var TH "Thailand"
cap label var TL "Timor-Leste"
cap label var VN "Viet Nam"
cap label var ASI_W "Western Asia"
cap label var AM "Armenia"
cap label var AZ "Azerbaijan"
cap label var BH "Bahrain"
cap label var IQ "Iraq"
cap label var IL "Israel"
cap label var JO "Jordan"
cap label var KW "Kuwait"
cap label var LB "Lebanon"
cap label var PS "Palestine*"
cap label var OM "Oman"
cap label var QA "Qatar"
cap label var SA "Saudi Arabia"
cap label var SY "Syria"
cap label var AE "United Arab Emirates"
cap label var YE "Yemen"
cap label var EX_YE "Former North Yemen (before 1990)"
cap label var EX_YD "Former South Yemen (before 1990)"
cap label var ASI_NME "Near and Middle East Asia (aggregate changing according to the context)"
cap label var ASI_W_OTH "Other Western Asian countries"
cap label var EX_SU_ASI "Asian Republics of the former Soviet Union"
cap label var ASI_OTH "Other Asian countries (aggregate changing according to the context)"
cap label var OCE "Oceania"
cap label var AU_NZ "Australia and New Zealand"
cap label var AU "Australia"
cap label var NZ "New Zealand"
cap label var MEL "Melanesia"
cap label var FJ "Fiji"
cap label var NC "New Caledonia"
cap label var PG "Papua New Guinea"
cap label var SB "Solomon Islands"
cap label var VU "Vanuatu"
cap label var MIC "Micronesia"
cap label var KI "Kiribati"
cap label var MH "Marshall Islands"
cap label var FM "Federated States of Micronesia"
cap label var NR "Nauru"
cap label var PW "Palau"
cap label var POL "Polynesia"
cap label var CK "Cook Islands"
cap label var PF "French Polynesia"
cap label var NU "Niue"
cap label var PN "Pitcairn Islands"
cap label var WS "Samoa"
cap label var TK "Tokelau"
cap label var TO "Tonga"
cap label var TV "Tuvalu"
cap label var WF "Wallis and Futuna"
cap label var OCE_OTH "Other Oceanian countries (aggregate changing according to the context)"
cap label var TF "French Southern and Antarctic Lands"
cap label var FOR_STLS "Foreign country and stateless"
cap label var FOR "Foreign country"
cap label var NAT "Reporting country"
cap label var RNC "Recognised non-citizens"
cap label var STLS "Stateless"
cap label var TOTAL "Total"
cap label var OTH "Others"
cap label var NAL "Not allocated"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var NSP "Not specified"
cap label var UNK "Unknown"
