cap label var CODE "Label - English"
cap label var PROD_BP "Production value at basic price"
cap label var SUBS "Subsidies on products"
cap label var TAX "Taxes on products"
cap label var PROD_PP "Production value at producer price"
cap label var I07A_EQ_Y "Holdings with manure storage facilities"
cap label var I07A1_EQ_Y "Holdings with storage facilities for solid dung"
cap label var I07A2_EQ_Y "Holdings with storage facilities for liquid manure"
cap label var I07A3_EQ_Y "Holdings with storage facilities for slurry"
cap label var I07A31_EQ_Y "Holdings with storage facilities for slurry: tank"
cap label var I07A32_EQ_Y "Holdings with storage facilities for slurry: lagoon"
cap label var I07A1_EQ_YC "Holdings with covered storage facilities for solid dung"
cap label var I07A2_EQ_YC "Holdings with covered storage facilities for liquid manure"
cap label var I07A3_EQ_YC "Holdings with covered storage facilities for slurry"
cap label var HIGH_INP "High-input farms"
cap label var LOW_INP "Low-input farms"
cap label var MED_INP "Medium-input farms"
cap label var ENT "Number of enterprises"
cap label var PROD "Annual production (1000 t)"
cap label var BAL_UAA "Gross nutrient balance per hectare UAA (kg of nutrient per ha)"
cap label var INP_UAA "Nutrient inputs per hectare UAA (kg of nutrient per ha)"
cap label var OUT_UAA "Nutrient outputs per hectare UAA (kg of nutrient per ha)"
cap label var BAL "Gross nutrient balance (Inputs minus Outputs) (tonnes of nutrient)"
cap label var TOT_N_EMIS "Total nitrogen emissions (tonnes)"
cap label var BAL_NET "Nett nutrient balance (gross nutrient balance minus total nitrogen emissions) (tonnes of nutrient)"
cap label var BAL_NET_UAA "Nett nutrient balance per hectare UAA (kg of nutrient per ha)"
cap label var INP_NT "Nutrient inputs (tonnes of nutrient)"
cap label var I_FRT "Total consumption of fertilisers (except manure) (tonnes of nutrient)"
cap label var I_FRT_MIN "Consumption of mineral fertilisers (tonnes of nutrient)"
cap label var I_FRT_ORG "Consumption of organic fertilisers (except manure) (tonnes of nutrient)"
cap label var I_MNR "Manure input (tonnes of nutrient)"
cap label var I_MNR_PRD "Manure production from total livestock (tonnes of nutrient)"
cap label var I_MNR_PCT "Manure production from cattle (tonnes of nutrient)"
cap label var I_MNR_PPG "Manure production from pigs (tonnes of nutrient)"
cap label var I_MNR_PSP "Manure production from sheep and goats (tonnes of nutrient)"
cap label var I_MNR_PPL "Manure production from poultry (tonnes of nutrient)"
cap label var I_MNR_POTH "Manure production from other livestock (tonnes of nutrient)"
cap label var I_MNR_WDR "Manure withdrawals (tonnes of nutrient)"
cap label var I_MNR_IMP "Manure imports (tonnes of nutrient)"
cap label var I_OTH "Other nutrient inputs (tonnes of nutrient)"
cap label var I_OTH_BIO "Other nutrient inputs: biological fixation of nitrogen (tonnes of nutrient)"
cap label var I_OTH_DEP "Other nutrient inputs: atmospheric deposition (tonnes of nutrient)"
cap label var I_OTH_SEED "Other nutrient inputs: seeds and planting material (tonnes of nutrient)"
cap label var OUT_NT "Nutrient outputs (tonnes of nutrient)"
cap label var O_CRP "Nutrient removal by harvest of crops (tonnes of nutrient)"
cap label var O_CRP_CER "Nutrient removal by harvest of cereals (tonnes of nutrient)"
cap label var O_CRP_PUL "Nutrient removal by harvest of dried pulses (tonnes of nutrient)"
cap label var O_CRP_ROO "Nutrient removal by harvest of root crops (tonnes of nutrient)"
cap label var O_CRP_IND "Nutrient removal by harvest of industrial crops (tonnes of nutrient)"
cap label var O_CRP_VEG "Nutrient removal by harvest of vegetables (tonnes of nutrient)"
cap label var O_CRP_FRU "Nutrient removal by harvest of fruits (tonnes of nutrient)"
cap label var O_CRP_ORN "Nutrient removal by harvest of ornamental crops (tonnes of nutrient)"
cap label var O_CRP_OTH "Nutrient removal by harvest of other crops (tonnes of nutrient)"
cap label var O_FOD "Nutrient removal by harvest and grazing of fodder (tonnes of nutrient)"
cap label var O_FOD_PGR "Nutrient removal by harvest and grazing of permanent grasslands (tonnes of nutrient)"
cap label var O_FOD_PGA "Nutrient removal by harvest of plants harvested green from arable land (tonnes of nutrient)"
cap label var O_RES "Nutrient removal by crop residues removed from the field (tonnes of nutrient)"
cap label var O_BRN "Nutrient removal by crop residues burned on the field (tonnes of nutrient)"
cap label var UAA "Utilised agricultural area (1000 ha)"
