cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var TOT_FIN "Financial reasons - total"
cap label var FIN_FAR_TRA_WAIT "Financial reasons, distance or transportation, waiting list"
cap label var FIN_DST_TRA_WAIT "Financial reasons, distance or transportation, waiting list"
cap label var FIN "Financial reasons"
cap label var FAR_TRA "Distance or transportation"
cap label var DST_TRA "Distance or transportation"
cap label var FAR "Distance"
cap label var DST "Distance"
cap label var DIF "Difficulty"
cap label var WAIT "Waiting list"
cap label var TIME "Time"
cap label var NINT "No interest"
cap label var NNB "None in the neighbourhood"
cap label var EDUC_END "Last formal education completed"
cap label var WI_WRK "Wish to work"
cap label var PREF_WRK "Preference to work"
cap label var TOOEXP "Too expensive"
cap label var TOOFAR "Too far to travel"
cap label var TOOEFW "Too expensive or too far to travel or waiting list"
cap label var LAYOFF "Lay-off"
cap label var NF_FT_PJOB "No full-time or permanent job found"
cap label var NF_FTJOB "No full-time job found"
cap label var NF_PJOB "No permanent job found"
cap label var JOB_TCTR "Job only available with a temporary contract"
cap label var ILLDIS "Own illness or disability"
cap label var FAM_PER "Other family or personal responsibilities"
cap label var FAM_PER_OTH "Other family or personal reasons"
cap label var FAMCARE "Looking after children or incapacitated adults"
cap label var FAM_OTH "Other family reasons"
cap label var FAM_HLTH_OTH "Family, health or other reasons"
cap label var INEDUC "In education or training"
cap label var RETIRED "Retired"
cap label var THKNOWK "Think no work is available"
cap label var NONEED "No need"
cap label var NOTIME "No time"
cap label var NO_UNMET "No unmet needs to declare"
cap label var NOKNOW "Didn't know any good doctor or specialist"
cap label var MULTI "Part of multinational enterprise group"
cap label var TOOSMALL "The domestic market is too small"
cap label var CUT_NICHE "Cutting edge products or specialised niche services"
cap label var NET "Internet driven demand"
cap label var OUTSOURC "Outsourcing driven demand"
cap label var ANM "Access to new markets"
cap label var MJOB "Mainly job related reasons"
cap label var MPER "Mainly personal/social reasons"
cap label var REDLC "Reduction of labour costs"
cap label var REDOC "Reduction of other costs than labour costs"
cap label var FOLLOW "Following the behaviour/example of competitors/clients"
cap label var QUAL "Improved quality or introduction of new products"
cap label var STRAT "Strategic decisions taken by the group head"
cap label var CORE "Focus on core business"
cap label var KNOW "Access to specialized knowledge/technologies"
cap label var LKLAB "Lack of qualified labour"
cap label var REDDT "Reduced delivery times"
cap label var REGL "Less regulation affecting the enterprise, e.g. less environmental regulation"
cap label var MPLC "Difficult to manage due to physical distance, language and cultural differences"
cap label var QPS "Insufficient quality of product/service at the foreign location"
cap label var PRDCT "Low labour productivity at the foreign location"
cap label var QPER "Lack of qualified personnel at the foreign location"
cap label var DELT "Too long delivery time to customers"
cap label var SUPPL "Problems with supplier flexibility and ability to supply"
cap label var PREQ "Prerequisites"
cap label var COST "Costs"
cap label var TAX "Tax or other financial incentives"
cap label var WAITING "Waiting list"
cap label var FEAR "Fear of doctor, hospital, examination or treatment"
cap label var HOPING "Wanted to wait and see if problem got better on its own"
cap label var OTHERM "Other motivations"
cap label var NRESP "No answer"
cap label var STAY_NJ "Purpose and conditions of stay not justified"
cap label var ALERT "An alert has been issued"
cap label var FAM "Family reasons"
cap label var FAM_EU "Family member joining an EU citizen"
cap label var FAM_CH_EU "Child joining an EU citizen"
cap label var FAM_OTH_EU "Other family member joining an EU citizen"
cap label var FAM_NEU "Family member joining a non EU citizen"
cap label var FAM_OTH_NEU "Other family member joining a non EU citizen"
cap label var EDUC "Education reasons"
cap label var OCCUP "Remunerated activities reasons"
cap label var PER "Personal reasons"
cap label var PER_HOL "Holidays, leisure and recreation"
cap label var PER_VFR "Visits to friends and relatives"
cap label var PER_OTH "Other personal reasons"
cap label var HOL "Holidays"
cap label var PROF "Professional, business"
cap label var BUCL "Business already a client"
cap label var LOC "Bank branch local"
cap label var BTIN "Best interest rate related terms offered"
cap label var BTNIN "Best non-interest rate related terms offered"
cap label var EMSF "Bank emphasis on smaller firms"
cap label var GDCL "Bank branch known for good client relationships"
cap label var MAINT "Maintain the business as a going concern"
cap label var GROW "Grow the business domestic activities"
cap label var EXP "Finance export sales"
cap label var INN "Finance innovation and R&D"
cap label var ACQU "For mergers and acquisitions"
cap label var INTL "Develop international activities"
cap label var ECO "General economic outlook"
cap label var LOCM "Limited demand in the local/domestic markets"
cap label var FORM "Limited demand in foreign markets"
cap label var AVPER "Limited availability of suitable new personnel"
cap label var LSPER "Loss of existing personnel"
cap label var TRPB "Business transfer problems e.g. inheritance"
cap label var HILAB "High cost of labour"
cap label var INVES "Necessary investment into equipment"
cap label var OUTPD "Products getting outdated (R&D necessary, product lead time)"
cap label var TCOMP "Technological competition"
cap label var NWENT "New entrants in the market"
cap label var PCOMP "Price competition/small margins"
cap label var RGFR "Regulatory framework"
cap label var LKFI "Lack of fiscal incentives"
cap label var DIFIT "Difficult access to information technology"
cap label var IW_OTH "Other infrastructure weakness"
cap label var NEFIN "Not enough financing"
cap label var PCR "Poor credit rating"
cap label var LOWNCAP "Lack of own capital"
cap label var LKC "Lack of own capital"
cap label var ICG "Insufficient collateral or guarantee"
cap label var IRP "Insufficient or risky potential (of the business or project)"
cap label var TML "Already too many loans or too much debt"
cap label var NLH "No loan history"
cap label var PLH "Poor loan history"
cap label var NRS "No reason given"
cap label var HIR "Interest rates too high"
cap label var NIR "Unacceptable non-interest-rate related conditions"
cap label var INA "Inability of existing shareholders to subscribe for more shares"
cap label var EXC "Too much equity in exchange for the funds offered asked by potential new shareholders"
cap label var CON "Too many concessions in exchange for equity finance asked by potential new shareholders"
cap label var DEV "Business potential development insufficient or too risky according to potential new shareholders"
cap label var DEB "Business had too many debts according to potential new shareholders"
cap label var HLTH "Health reasons"
cap label var SAFE "Safety reasons"
cap label var DISMIS "Dismissed or made redundant"
cap label var JOBLIM "Job of limited duration that ended"
cap label var EDUTRA "Education or training"
cap label var ERLY_RET "Early retirement"
cap label var NORM_RET "Normal retirement"
cap label var LHCBAD_PEF "Both longstanding health condition or a basic activity difficulty and personal or environmental factors"
cap label var LHCBADO "Longstanding health condition or a basic activity difficulty only"
cap label var PEFO "Personal or environmental factors only"
cap label var LACKQUAL "Lack of qualifications/experience"
cap label var LACKAPPJOB "Lack of appropriate job opportunities"
cap label var FAMRESP "Family/caring responsibilities"
cap label var OPER "Other personal or environmental reasons"
cap label var NOLIMW "No limitation in work"
cap label var HCOST "High costs"
cap label var LEXPT_RLV "Lack of relevant expertise"
cap label var INCOMP_ESS "Incompatibility with existing equipment, software or systems"
cap label var DIF_AVL_QUAL "Difficulties with availability or quality of the necessary data"
cap label var CNC_VL_DPR "Concerns regarding violation of data protection and privacy"
cap label var LCLRY_LEG "Lack of clarity about the legal consequences"
cap label var ETH "Ethical considerations"
cap label var AI_NUSE "Artificial Intelligence technologies are not useful"
cap label var NLIM "No limitation"
cap label var HLTH_AGE "Health or age reasons"
cap label var AGFOD_OTH "Age, gender, foreign origin, disability and other reason"
cap label var AGE "Age"
cap label var GEND "Gender"
cap label var ORI_FOR "Foreign origin"
cap label var DIS "Disability"
cap label var DIS_OTH "Disability or other reason"
cap label var NPL "No places available"
cap label var OH_NSUI "Opening hours not suitable"
cap label var QUAL_NSAT "Quality of the services available not satisfactory"
cap label var NND "No need"
cap label var CO_NADT "Not admitted to the course or programme"
cap label var CO_NSUI "No suitable courses or programmes available"
cap label var NPROV "Not provided by employer"
cap label var NCARE "No care services available"
cap label var NF_SALJOB "No job found as employee"
cap label var CN_BSN_FAM "Continued the family business"
cap label var NPW_OTH "Not planned or wanted but started for another reason"
cap label var W_DIF "Wanted but encountered difficulties"
cap label var W_PERDIF "Wanted but encountered difficulties for personal reasons"
cap label var W_NPERDIF "Wanted but encountered difficulties which were not due to personal reasons"
cap label var W_OTH "Wanted for other reason"
cap label var NW "Did not want"
cap label var LINFL_PRC "Lack of influence on price setting"
cap label var LACS_FIN "Lack of access to financing"
cap label var D_PAY_NPAY "Delayed payments or non-payments"
cap label var HABUR "High administrative burden"
cap label var FIN_HS "Periods of financial hardship"
cap label var NCUS_NASG_NPRJ "Periods of having no customer, no assignments or project to work on"
cap label var NDIF "No difficulties"
cap label var PREF_WRK_ALN "Preferring working alone"
cap label var DIF_F_SUI_STAF "Difficulty finding suitable staff"
cap label var C_LEGFRAM "Complicated legal framework"
cap label var HSC "High social contributions"
cap label var NAW "Not aware"
cap label var NPS "Not possible"
cap label var NPS_OCC "Not possible due to occupation"
cap label var PREF_WRK_SCTR "Preferring working with subcontractors or associates"
cap label var WI_CL "Client's wish"
cap label var FIN_NSECU "Financial insecurity"
cap label var DIF_G_FIN "Difficulty getting financing"
cap label var STRS_RESP_RSK "Stress, responsibility, risk"
cap label var LS_CVG_SOPROT "Less social protection coverage"
cap label var R_COSTPR "Responding to cost pressures"
cap label var I_ENTPERF "Improving enterprise's performance"
cap label var OP_OPPO_NEWMKT "Opening up new market opportunities"
cap label var R_MKTPR "Responding to market pressures"
cap label var R_REGL "Responding to regulatory provisions"
cap label var PER_ENV_ONL "Personal or environmental reasons only"
cap label var PER_ENV_OTH "Other personal or environmental reasons"
cap label var FAM_CARE_PER_OTH "Care of adults with disabilities or children and other family or personal reasons"
cap label var FAM_CARE "Care of adults with disabilities or children"
cap label var FAM_SPOU_EU "Spouse or partner joining an EU citizen"
cap label var FAM_CH_NEU "Child joining a non EU citizen"
cap label var FAM_SPOU_NEU "Spouse or partner joining a non EU citizen"
cap label var NSERV_ACS "No service accessible or vacant"
cap label var CH_SELF_CARE "Children take care of themselves"
cap label var SERV_OTH "Other service related reasons"
cap label var LCARE_D_ST "Lack of care services during the day or at special times"
cap label var LCARE_D "Lack of care services during the day"
cap label var LCARE_ST "Lack of care services at special times"
cap label var CARE_TXP "Care services are too expensive"
cap label var CARE_QUAL_NS "Available care services are not of sufficient quality"
cap label var EDUC_TNG_RET_OTH "Education or training, retirement or other reason"
cap label var EDUC_TNG "Education or training"
cap label var EDUC_TNG_NSUI "No suitable offer for education or training"
cap label var EDUC_STU "Study"
cap label var EDUC_OTH "Other educational reasons"
cap label var TNG "Training"
cap label var ITNG_S "Initial training sufficient"
cap label var EXPT_TNG_NS "Insufficient expertise to develop a training plan"
cap label var FOC_IVT "Focus on IVT rather than on CVT"
cap label var CAP_IVT "Use of productive capacities of IVT participants"
cap label var EFF_REC "Major CVT efforts made in recent years"
cap label var BST_FUEMP "Selection of the best IVT participants for future employment"
cap label var RSRCH "Research"
cap label var PUPXCH_EDUC "Pupil exchange scheme or educational project"
cap label var AUPAIR "Au pairing"
cap label var CO_LANG_NAVL_NAFD "Language courses not available or not affordable"
cap label var SKIL_LANG_S "Language skills sufficient"
cap label var NAP_CO_LANG_PT "Not applicable - participation in language course"
cap label var DST_LANG_CLT "Distance, language or culture"
cap label var DST_RND_TLRG "Distance between production process and R&D or product design too large"
cap label var FIN_NENO "Not enough financing"
cap label var FIN_EXP "Financing exports"
cap label var ELIG_PEN "Eligibility for a pension reached"
cap label var RETAGE_MAX "Maximum retirement age reached"
cap label var FINARR_FV "Favourable financial arrangements"
cap label var JOB_OTH "Other job-related reasons"
cap label var ILL_DIS_OWN "Own illness or disability"
cap label var CARE_FAM_OTH "Care responsibilities or other family reasons"
cap label var FIN_INN_RND "Financing innovation and R&D"
cap label var NSECU_FIN "Financial insecurity"
cap label var TAX_FIN "Tax or financial reasons"
cap label var LFISC "Lack of fiscal incentives"
cap label var TXP_DIF "Too expensive or difficult"
cap label var TXP "Too expensive"
cap label var PR_INC_S "Providing sufficient income"
cap label var E_PEN_PR_INC_S "Establishing/increasing retirement pension entitlements and providing sufficient income"
cap label var E_PEN "Establishing/increasing retirement pension entitlements"
cap label var O_FINASSI_EU "Obtaining financial assistance from the EU"
cap label var O_FINASSI_OTH "Obtaining financial assistance from other external sources"
cap label var HCOST_EXPC "Higher costs than expected"
cap label var HCOST_CVT "High costs of CVT courses"
cap label var HLC "High labour costs"
cap label var RED_LC "Reduction of labour costs"
cap label var RED_OTHXLC "Reduction of other costs not related to labour"
cap label var LABPRY_NS "Insufficient labour productivity"
cap label var LQLFLAB "Lack of qualified labour"
cap label var TXP_TFAR_WLIST "Too expensive or too far or waiting list"
cap label var TFAR "Too far"
cap label var NTIME "No time"
cap label var LTIME_FAM "Lack of time due to family commitments"
cap label var LTIME_WRK_STU "Lack of time due to work or study commitments"
cap label var HWL_NTIME "High workload and limited/no time available for staff to participate in CVT"
cap label var NPRIOR "No priority"
cap label var PR_REQ "Only provided when requested"
cap label var WLIST "Waiting list"
cap label var LINC_ILL "Lack of income in case of sickness/illness"
cap label var LHC_BAD_PER_ENV "Longstanding health condition or a basic activity difficulty and personal or environmental reasons"
cap label var LHC_BAD_ONL "Longstanding health condition or a basic activity difficulty only"
cap label var GDOC_UNK "Good doctor or specialist not known"
cap label var FEAR_DR_HSP "Fear of doctor, hospital, examination or treatment"
cap label var HOPE "Hope to get better"
cap label var NMT_EXPC_TDIF "Study did not meet expectations or too difficult"
cap label var NMT_ND_INT "Study did not meet needs or interest"
cap label var NND_NINT "No need or no interest"
cap label var OPHR_NSUI "Opening hours not suitable"
cap label var NUMT_ND "No unmet needs"
cap label var NUMT_ND_PROF "No unmet needs and professional care used"
cap label var NUMT_ND_NPROF "No unmet needs and no professional care used"
cap label var NLIM_TNG "No limitation in the level of training provided"
cap label var NADT_CO "Not admitted to the course or programme"
cap label var LCVT_SUI "Lack of suitable CVT courses in the market"
cap label var NPR_EMPL "Not provided by employer"
cap label var REF_ND_SERV "Refused by person needing such services"
cap label var NACT_NB "No such activities in the neighbourhood"
cap label var LVL_APP "Level of education attained considered appropriate"
cap label var DIF_ASS "Difficult to assess enterprise's training needs"
cap label var DIF_F_STAF_SUI "Difficulty finding suitable staff"
cap label var DIF_ACS_ITEC "Difficult access to information technology"
cap label var DIF_FRCHG_PRD "Difficulty due to frequent changes to the product"
cap label var WRK_NENO "Not enough work"
cap label var NWRKTIME_ARR "No working time arrangements"
cap label var ARR_ALN_PTN "Arranged alone or with partner"
cap label var INFSUPP "Informal support"
cap label var WRKHR_LG "Long working hours"
cap label var DIF_WRKSCD "Unpredictable or difficult work schedules"
cap label var COM_LG "Long commute"
cap label var DMJOB "Demanding or exhausting job"
cap label var LSUPP_EMPL_PUB "Lack of support from employer or public services"
cap label var LSUPP_EMPL "Lack of employer support"
cap label var LSUPP_PUB "Lack of public services support"
cap label var SKD "Schedule"
cap label var JOB "Job related reasons"
cap label var F_JOB "Job found"
cap label var LOST_NF_JOB "Lost job and/or no job found"
cap label var NW_PJOB "No permanent job wanted"
cap label var B_NJOB "Believing no job available"
cap label var EMP_F_JOB "Employment - job found before migrating"
cap label var EMP_NF_JOB "Employment - no job found before migrating"
cap label var PROB "Probation"
cap label var DISM "Dismissed or made redundant"
cap label var JOB_LTD_END "End of limited duration job"
cap label var RECR_SKIL_ND "People recruited with the skills needed"
cap label var DISC_MNG_SAL "Discussion between management and employees"
cap label var NMM_RECR "Prevention of mismatch with enterprise needs in case of external recruitment"
cap label var RESIS_SAL "Resistance among employees"
cap label var O_CERT_GTNG "Obtaining certification/accreditation as a good training enterprise"
cap label var O_COM_MNG "Obtaining commitment of management to the importance of CVT"
cap label var RESP_OWNTIME "Responsibility of the employees in their own time"
cap label var QLF_COR "Existing qualifications, skills and competences corresponded to the current needs of the enterprise"
cap label var QLF_FUSAL "Qualification of future employees according to the needs of the enterprise"
cap label var LAPP_JOBOPPO "Lack of appropriate job opportunities"
cap label var LQLF "Lack of qualifications/experience"
cap label var NEG_PLE "Negative previous learning experience"
cap label var CO_BKD_OUT "Course booked out"
cap label var REG_TF "Too few registrations"
cap label var JOBSRCH_ENTR "Job-searching or entrepreneurship"
cap label var EMP "Employment reasons"
cap label var EMP_BLUE "EU Blue card"
cap label var EMP_HSW "Highly skilled workers"
cap label var EMP_RSE "Researchers"
cap label var EMP_WRK_SEAS "Seasonal workers"
cap label var EMP_OTH "Other employment reasons"
cap label var RET "Retirement"
cap label var RET_EARL "Early retirement"
cap label var RET_NML "Normal retirement"
cap label var VS "Voluntary service"
cap label var EVS "European Voluntary Service (EVS)"
cap label var VS_OTH "Other voluntary service"
cap label var CHG_FAM "Change from family reasons"
cap label var CHG_FAM_EDUC "Change from family to education reasons"
cap label var CHG_FAM_EMP "Change from family to employment reasons"
cap label var CHG_FAM_OTH "Change from family to other reasons"
cap label var CHG_EDUC "Change from education reasons"
cap label var CHG_EDUC_FAM "Change from education to family reasons"
cap label var CHG_EDUC_EMP "Change from education to employment reasons"
cap label var CHG_EDUC_OTH "Change from education to other reasons"
cap label var CHG_EMP "Change from employment reasons"
cap label var CHG_EMP_FAM "Change from employment to family reasons"
cap label var CHG_EMP_EDUC "Change from employment to education reasons"
cap label var CHG_EMP_OTH "Change from employment to other reasons"
cap label var CHG_OTH "Change from other reasons"
cap label var CHG_OTH_FAM "Change from other to family reasons"
cap label var CHG_OTH_EDUC "Change from other to education reasons"
cap label var CHG_OTH_EMP "Change from other to employment reasons"
cap label var IPROT_ASY "International protection or asylum"
cap label var RFG_SPROT_HUM "International protection (refugee and subsidiary protection status) and humanitarian status"
cap label var RFG_SPROT "International protection status (refugee and subsidiary protection status)"
cap label var RFG "Refugee status"
cap label var SPROT "Subsidiary protection status"
cap label var HUM "Humanitarian status"
cap label var SPN_RFG "Sponsor with refugee status"
cap label var SPN_SPROT "Sponsor with subsidiary protection status"
cap label var SPN_HUM "Sponsor with humanitarian status"
cap label var SPN_UNK "Sponsor with unknown status"
cap label var RES "Residence"
cap label var UAM "Unaccompanied minors"
cap label var WDN_RVOC "Withdrawn due to revocation"
cap label var WDN_END "Withdrawn due to ending"
cap label var WDN_REF_RNEW "Withdrawn due to refusal to renew"
cap label var VICT_TRFF_HMN "Victims of trafficking in human beings"
cap label var C_LAW_CAGRM "Complying with the law or collective agreements"
cap label var DOC_FLS "False travel document(s)"
cap label var DOC_NV "No valid travel document(s)"
cap label var VISA_RPRM_FLS "False visa or residence permit"
cap label var VISA_RPRM_NV "No valid visa or residence permit"
cap label var STAY_M3 "Person already stayed 3 months in a 6-months period"
cap label var SUBS_NS "Insufficient means of subsistence"
cap label var PUB_THRT "Person considered to be a public threat"
cap label var ENTRY_NLEG "Illegal entry"
cap label var OSTAY "Overstay"
cap label var IC_TRF "Intra-corporate transferee permit"
cap label var LT_MOB "Long-term mobility permit"
cap label var REQ_FOEMPL "Requested by former employer"
cap label var PRCT_USU "Usual practice in the field"
cap label var OPPO_SUI "Suitable opportunity"
cap label var CN_FAMBSN "Continued the family business"
cap label var WRKHR_FLEX "Flexible working hours"
cap label var PAY_NPAY_DL "Delayed payments or non-payments"
cap label var REGLFRAM "Regulatory framework"
cap label var LEGFRAM_CMPL "Complicated legal framework"
cap label var LS_REG "Less regulation (e.g. environmental regulation)"
cap label var STRAT_DEC "Strategic decisions by group head"
cap label var FOC_CORBSN "Focus on core business"
cap label var DLVTIME_TLG "Delivery time too long"
cap label var QUAL_NS "Insufficient quality"
cap label var LQLFPER_FOR "Lack of qualified personnel at the foreign location"
cap label var LFLEX_SUP "Lack of flexibility or ability to supply"
cap label var ACS_NEWMKT "Access to new markets"
cap label var ACS_SPEKNOW "Access to specialised knowledge/technologies"
cap label var NACS_CP_INET "No access to a computer or internet"
cap label var FL_BHV_COMP "Following the behaviour/example of competitors/clients"
cap label var LOG "Logistics"
cap label var IQUAL_NEWPRD "Improved quality or new products"
cap label var COMP "Competitiveness"
cap label var IH_KH "In-house know-how"
cap label var S_DOMPRD "Streamlining of domestic production process"
cap label var NSUBSC_SHR "Unable to subscribe for further shares"
cap label var EQUIT_TM "Too much equity"
cap label var CONC_TM "Too many concessions"
cap label var BSNPT_NS_RSK "Insufficient or risky business potential"
cap label var LOAN_TM_DEBT_TH "Too many loans or too high debt"
cap label var POORCRED "Poor credit rating"
cap label var LCAPOWN "Lack of own capital"
cap label var COLT_GAR_NS "Insufficient collateral or guarantee"
cap label var NLOAN_HST "No loan history"
cap label var BST_INT_RT "Best interest rate"
cap label var POORLOAN_HST "Poor loan history"
cap label var INT_RT_TH "Interest rates too high"
cap label var NACC_NINT_RT "Unacceptable conditions (other than interest rate)"
cap label var ALR_CL "Already client"
cap label var LOC_BANK "Local bank"
cap label var BST_OTH_XINT_RT "Best other conditions not related to interest-rates"
cap label var EMPH_BSN_SML "Emphasis on smaller business"
cap label var K_GCLRELS "Known for good client relationships"
cap label var ECON_OUTL "General economic outlook"
cap label var LTDDM_DOMMKT "Limited demand in the local/domestic markets"
cap label var LTDDM_FORMKT "Limited demand in foreign markets"
cap label var LTDAVL_PER_SUI "Limited availability of suitable personnel"
cap label var LOSS_PER "Loss of existing personnel"
cap label var BSNTRF_PB "Business transfer problems (e.g. inheritance)"
cap label var INV_EQ "Necessary investment into equipment"
cap label var PRD_OUTD "Products becoming outdated"
cap label var TEC_COMP "Technological competition"
cap label var NEWENT_MKT "New entrants in the market"
cap label var PRC_MRG "Price competition/small margins"
cap label var INFR_WEAK_OTH "Other infrastructure weakness"
cap label var MNT_BSN "Maintaining the business"
cap label var GR_DOMBSN "Growing domestic business"
cap label var MERG_ACQ "Mergers and acquisitions"
cap label var DEV_INTLBSN "Developing international business"
cap label var MULTINAT "Part of multinational enterprise group"
cap label var DOMMKT_TSML "Domestic market too small"
cap label var INET_DRV "Internet-driven"
cap label var HARS_BULLY "Harassment or bullying"
cap label var TPR_OLWRK "Time pressure or overload of work"
cap label var VLN_THRT "Violence or threat of violence"
cap label var CHM_SMO_GAS "Chemicals, dusts, fumes, smoke or gases"
cap label var ACT_SVCONC "Activities involving strong visual concentration"
cap label var H_HVYLOAD "Handling of heavy loads"
cap label var NOIS_VIB "Noise or vibration"
cap label var DIF_WPST_WMV "Difficult work postures, work movements"
cap label var RSK_ACC "Risk of accident"
cap label var LCOMM_ORG "Lack of communication or cooperation within the organisation"
cap label var DEAL_DIFCUS "Dealing with difficult customers, patients, pupils, etc."
cap label var NSECU_JOB "Job insecurity"
cap label var LAUTN_WPACE "Lack of autonomy, or lack of influence over the work pace or work processes"
cap label var TIR_PFPSN "Tiring or painful positions"
cap label var RPTMOV "Repetitive hand or arm movements"
cap label var SLP_TRP_FAL "Slips, trips and falls"
cap label var U_MAC_HNTL "Use of machines or hand tools (excluding vehicles)"
cap label var U_VEH "Use of vehicles (in the course of work, excluding on the way to and from work)"
cap label var SGN_OTH "Another significant risk factor"
cap label var COV19 "COVID-19 related effects"
cap label var GDSERV_OUTD "Goods or services outdated quickly"
cap label var GDSERV_SS "Competitor goods or services easily substituted"
cap label var NEWCOMP_THRT "New competitors as a major threat of enterprises’ market position"
cap label var SCOMP_ABR "Strong competition from abroad"
cap label var DIF_P_TECDEV "Difficulty predicting future technological developments"
cap label var DIF_P_COMPACT "Difficulty predicting competitor's actions"
cap label var DIF_P_CHG_DM "Difficulty predicting changes in demand"
cap label var LOSS_CL_INCR_PRC "Loss of clients due to increases of the price"
cap label var GOV_PLCY_MEAS "Government policies or measures"
cap label var INCR_CUSDM "Increasing customer demand"
cap label var INCR_COST_PRC "Increasing costs or input prices"
cap label var IMPC_WTHR "Impacts of extreme weather conditions"
cap label var REG "Existing regulations"
cap label var TAX_CHRG_FEE "Existing taxes, charges or fees"
cap label var REG_TAX_FU "Regulations or taxes expected in the future"
cap label var GRNT_S_FINOTH "Government grants, subsidies or other financial incentive"
cap label var MKTDM "Current or expected market demand"
cap label var I_ENTREPUT "Improving enterprise's reputation"
cap label var VA_INIT "Voluntary actions or initiatives within the sector"
cap label var HCOST_EWM "High cost of energy, water or materials"
cap label var PUB_PROC "Need to meet requirements for public procurement"
cap label var NOTF_RECV "Notification received"
cap label var REF_BIO_DATA "Refused to provide biometric data"
cap label var SANC_RU "Sanctions on Russia"
cap label var ENV "Environmental policy related factors"
cap label var W_E_MNS_OTH "Watching/experiencing by other means"
cap label var VOL_AD "Volumes of admission"
cap label var LABMKT_SIT "Labour market situation"
cap label var RENT_END "End of rental contract"
cap label var NHAB_ACCOM "Uninhabitable accommodation"
cap label var LEAV_INST "Leaving an institution after a long stay and no home to go to"
cap label var MOV_SPH "Moved into social or subsidised private housing"
cap label var FIN_NEC "Financially necessary"
cap label var FIN_ATR "Financially attractive"
cap label var PTN_SPOU_WRK "Partner/spouse still working"
cap label var E_WRK_PRD "Enjoy working/being productive"
cap label var S_SOC_INTG "Staying socially integrated"
cap label var RELS_FAM "Relationship or family related reasons"
cap label var LRES "Lack of resources"
cap label var DIF_ACS_PHY "Difficult physical access"
cap label var SERV_NAVL "Service not available"
cap label var NONE "None"
cap label var OTH "Other reason"
cap label var OTH_NLCARE "Other reason not linked with the lack of suitable care services"
cap label var OUTSRC_DRV "Outsourcing driven"
cap label var OTH_LCARE "Other reason linked with the lack of suitable care services"
cap label var NAP_APLD "Not applicable - applied for recognition"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var NSP "Not specified"
cap label var UNK "Unknown"
