cap label var CODE "Label - English"
cap label var GDP "Gross domestic product"
cap label var A01 "Actual individual consumption"
cap label var A0101 "Food and non-alcoholic beverages"
cap label var A010101 "Food"
cap label var A01010101 "Cereals and cereal products"
cap label var A01010102 "Live animals, meat and other parts of slaughtered land animals"
cap label var A01010103 "Fish and other seafood"
cap label var A01010104 "Milk, other dairy products and eggs"
cap label var A01010105 "Oils and fats"
cap label var A01010106 "Fruits and nuts"
cap label var A01010107 "Vegetables, tubers, plantains, cooking bananas and pulses"
cap label var A01010108 "Sugar, confectionery and desserts"
cap label var A01010109 "Ready-made food and other food products n.e.c."
cap label var A010102 "Non-alcoholic beverages"
cap label var A0102 "Alcoholic beverages, tobacco and narcotics"
cap label var A010201 "Alcoholic beverages"
cap label var A010203 "Tobacco"
cap label var A0103 "Clothing and footwear"
cap label var A010301 "Clothing"
cap label var A010302 "Footwear"
cap label var A0104 "Housing, water, electricity, gas and other fuels"
cap label var A010405 "Electricity, gas and other fuels"
cap label var A0105 "Furnishings, household equipment and routine household maintenance"
cap label var A010501 "Furniture, furnishings and loose carpets (prices only)"
cap label var A010503 "Households appliances"
cap label var A0106 "Health"
cap label var A010603 "Inpatient care services"
cap label var A0107 "Transport"
cap label var A010701 "Purchase of vehicles"
cap label var A010702 "Fuels and lubricants for personal transport equipment (ND)"
cap label var A010703 "Passenger transport services"
cap label var A0108 "Information and communication"
cap label var A010801 "Information and communication equipment"
cap label var A0109 "Recreation, sport and culture"
cap label var A0110 "Education services"
cap label var A0111 "Restaurants and accommodation services"
cap label var A0112 "Miscellaneous goods and services"
cap label var A04 "Actual collective consumption"
cap label var A05 "Gross fixed capital formation"
cap label var A0501 "Machinery and equipment"
cap label var A050101 "Metal products and equipment (excl. electrical and optical)"
cap label var A050102 "Electrical and optical equipment"
cap label var A050103 "Transport equipment"
cap label var A0502 "Construction"
cap label var A050201 "Residential buildings"
cap label var A050202 "Non-residential buildings"
cap label var A050203 "Civil engineering works"
cap label var A0503 "Software"
cap label var E01 "Final consumption expenditure"
cap label var E011 "Household final consumption expenditure"
cap label var E012 "Government final consumption expenditure"
cap label var E0121 "Collective consumption expenditure"
cap label var E0122 "Individual consumption expenditure"
cap label var P01 "Total goods"
cap label var P0101 "Consumer goods"
cap label var P010101 "Non-durable"
cap label var P010102 "Semi-durable"
cap label var P010103 "Durable goods"
cap label var P0102 "Capital goods"
cap label var P02 "Total services"
cap label var P0201 "Consumer services"
cap label var P0202 "Government services"
cap label var P020201 "Collective services"
cap label var P020202 "Individual services"
