cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var AC0_X_021 "Personal care except eating"
cap label var AC0 "Personal care"
cap label var AC01 "Sleeping"
cap label var AC011 "Sleeping"
cap label var AC012 "Sick in bed"
cap label var AC02 "Eating"
cap label var AC021 "Eating"
cap label var AC03 "Other personal care"
cap label var AC031 "Washing and dressing"
cap label var AC032 "Personal care services"
cap label var AC039 "Other or unspecified personal care"
cap label var AC1_2 "Employment and study"
cap label var AC1 "Employment"
cap label var AC11_12 "Employment, related activities and travel as part of/during main and second job"
cap label var AC11 "Main job and second job"
cap label var AC111 "Working time in main and second job (including short breaks and travel at work)"
cap label var AC12 "Activities related to employment"
cap label var AC121 "Lunch break in main and second jobs"
cap label var AC129 "Other or unspecified activities related to employment"
cap label var AC2 "Study"
cap label var AC21_X_212 "School or university except homework"
cap label var AC21 "School or university"
cap label var AC211 "Classes and lectures"
cap label var AC212 "Homework"
cap label var AC213 "Internship"
cap label var AC214 "Breaks at school/ university"
cap label var AC215 "Extracurricular classes"
cap label var AC219 "Other/ unspecified activities related to study"
cap label var AC22 "Free time study"
cap label var AC221 "Free time study"
cap label var AC3_713 "Household and family care and making handicraft products"
cap label var AC3_713_X_38 "Household and family care and making handicraft products except childcare"
cap label var AC3_713_936_980 "Household and family care and related travel and making handicraft products"
cap label var AC3 "Household and family care"
cap label var AC30 "Unspecified household and family care"
cap label var AC300_371 "Household management and unspecified household and family care"
cap label var AC300 "Unspecified household and family care"
cap label var AC31_X_312 "Food management except dish washing"
cap label var AC31 "Food management"
cap label var AC311 "Food preparation and baking"
cap label var AC312 "Dish washing"
cap label var AC313 "Storing, arranging, preserving food stocks"
cap label var AC32_X_321 "Household upkeep except cleaning dwelling"
cap label var AC32 "Household upkeep"
cap label var AC321 "Cleaning dwelling"
cap label var AC322 "Cleaning garden"
cap label var AC323 "Heating dwelling and water"
cap label var AC324 "Arranging household goods and materials"
cap label var AC325 "Recycling and disposal of waste"
cap label var AC329 "Other or unspecified household upkeep"
cap label var AC33 "Care for textiles"
cap label var AC331 "Laundry"
cap label var AC332 "Ironing"
cap label var AC339_713 "Other or unspecified textile care and making handicraft products"
cap label var AC339 "Other or unspecified textile care"
cap label var AC34 "Gardening and pet care"
cap label var AC341_349 "Gardening and other or unspecified gardening and pet care"
cap label var AC341 "Gardening"
cap label var AC342 "Tending domestic animals"
cap label var AC343 "Caring for pets"
cap label var AC344 "Walking the dog"
cap label var AC349 "Other or unspecified gardening and pet care"
cap label var AC35 "Construction and repairs"
cap label var AC351 "House construction and renovation"
cap label var AC352 "Repairs to dwelling"
cap label var AC353 "Making, repairing and maintaining equipment"
cap label var AC354 "Vehicle maintenance"
cap label var AC359 "Other or unspecified construction and repairs"
cap label var AC36 "Shopping and services"
cap label var AC361 "Shopping (including online/ e-shopping)"
cap label var AC362 "Commercial and administrative services"
cap label var AC369 "Other or unspecified shopping and services"
cap label var AC37 "Household management"
cap label var AC371 "Household management"
cap label var AC38_X_382_383 "Childcare, except teaching, reading, playing and talking"
cap label var AC38 "Childcare"
cap label var AC381 "Physical care and supervision of child"
cap label var AC382_383 "Teaching, reading, playing and talking with child"
cap label var AC382 "Teaching the child"
cap label var AC383 "Reading, playing and talking with child"
cap label var AC384 "Accompanying child"
cap label var AC389 "Other or unspecified childcare"
cap label var AC39 "Help to an adult household member"
cap label var AC391 "Physical care of an adult household member"
cap label var AC392 "Other support to an adult household member"
cap label var AC4_8_998_X_713 "Leisure, social and associative life, except making handicraft products"
cap label var AC4_8_998_X_713_821 "Leisure, social and associative life except making handicraft products and TV and video"
cap label var AC4 "Voluntary work and meetings"
cap label var AC41 "Organisational work"
cap label var AC411 "Organisational work (work for or through an organisation)"
cap label var AC42 "Informal help to other households"
cap label var AC421 "Construction and repairs as help"
cap label var AC422 "Help in employment and farming"
cap label var AC423 "Care of own children living in another household"
cap label var AC424 "Childcare as help to another household"
cap label var AC425 "Help to an adult person of another household"
cap label var AC429 "Other/ unspecified informal help to another household"
cap label var AC43 "Participatory and religious activities"
cap label var AC431 "Meetings"
cap label var AC432 "Religious activities"
cap label var AC433 "Visits to cemetery and grave care"
cap label var AC439 "Other or unspecified participatory activities"
cap label var AC5 "Social life and entertainment"
cap label var AC51 "Social life"
cap label var AC511 "Socialising with family"
cap label var AC512_513_519 "Socialising with others (visits, celebrations and other)"
cap label var AC512 "Visiting and receiving visitors"
cap label var AC513 "Celebrations"
cap label var AC514_516 "Virtual social life"
cap label var AC514 "Audio and video conversation"
cap label var AC515 "Communication by text messaging (SMS, instant messages, email, etc.)"
cap label var AC516 "Time spent on social media"
cap label var AC519 "Other or unspecified social life"
cap label var AC52 "Entertainment and culture"
cap label var AC521 "Cinema"
cap label var AC522 "Theatre and concerts"
cap label var AC523 "Art exhibitions and museums"
cap label var AC524 "Library"
cap label var AC525 "Attending live sports events"
cap label var AC526 "Zoos, botanical gardens, natural reserves, etc."
cap label var AC529 "Other or unspecified entertainment and culture"
cap label var AC53 "Resting - time out"
cap label var AC531 "Resting - time out"
cap label var AC6_X_611 "Sports and outdoor activities except walking and hiking"
cap label var AC6 "Sports and outdoor activities"
cap label var AC61 "Physical exercise"
cap label var AC611 "Walking and hiking"
cap label var AC612 "Jogging and running"
cap label var AC613 "Cycling, skiing and skating"
cap label var AC614 "Ball games"
cap label var AC615 "Gymnastics and fitness"
cap label var AC616 "Water sports"
cap label var AC619 "Other or unspecified sports or outdoor activities"
cap label var AC62 "Productive exercise"
cap label var AC621 "Productive exercise (e.g. hunting, fishing, picking berries, mushrooms or herbs)"
cap label var AC63 "Sports related activities"
cap label var AC631 "Sports related activities"
cap label var AC711_712_719_731_732_739 "Arts and hobbies (except making handicraft products), and games (except computer, console, mobile games)"
cap label var AC7 "Hobbies"
cap label var AC71 "Arts and hobbies"
cap label var AC711 "Arts (visual, performing, literary)"
cap label var AC712 "Collecting"
cap label var AC713 "Making handicraft products"
cap label var AC719 "Other or unspecified hobbies"
cap label var AC72 "Computing"
cap label var AC721 "Computing"
cap label var AC722 "Information search using internet"
cap label var AC729 "Other or unspecified computing"
cap label var AC73 "Games"
cap label var AC731 "Solo games and play, gambling"
cap label var AC732 "Parlour games and play"
cap label var AC733_735 "Computer games, console games (on home console) and mobile games (on handheld device/ smartphone)"
cap label var AC733 "Computer games"
cap label var AC734 "Console games (on home console)"
cap label var AC735 "Mobile games (on handheld device/ smartphone)"
cap label var AC739 "Other or unspecified games"
cap label var AC8 "Mass media"
cap label var AC81_X_812 "Reading, except reading books"
cap label var AC81 "Reading"
cap label var AC811 "Reading periodicals"
cap label var AC812 "Reading books"
cap label var AC819 "Other or unspecified reading"
cap label var AC82 "TV, video and DVD"
cap label var AC821 "Watching TV, video or DVD"
cap label var AC83 "Radio and recordings"
cap label var AC831 "Listening to radio or recordings"
cap label var AC9_X_910 "Travel except travel related to/from work"
cap label var AC9 "Travel and unspecified time use - travel by purpose"
cap label var AC910_920 "Travel to/from work/study"
cap label var AC910 "Travel to/ from work"
cap label var AC920 "Travel related to study"
cap label var AC936 "Travel related to shopping and services"
cap label var AC938_939 "Travel related to childcare and to other household care"
cap label var AC938 "Travel related to childcare"
cap label var AC939 "Travel related to other household care"
cap label var AC940_980 "Travel related to leisure, social and associative life"
cap label var AC940 "Travel related to voluntary work and meetings"
cap label var AC950 "Travel related to social life"
cap label var AC960 "Travel related to other leisure"
cap label var AC980 "Travel related to changing locality"
cap label var AC900_980 "Travel by purpose"
cap label var AC900_995_999 "Other or unspecified travel purpose, filling in the time use diary and other unspecified time use"
cap label var AC900 "Other or unspecified travel purpose"
cap label var AC995_999 "Filling in the time use diary and other unspecified time use"
cap label var AC995 "Filling in the time use diary"
cap label var AC998 "Unspecified leisure time"
cap label var AC999 "Other unspecified time use"
cap label var AC_PNP_MAIN "Productive paid and unpaid main activities"
cap label var AC_NP_TOT "Productive unpaid main and secondary activities"
cap label var AC_NP_MAIN "Productive unpaid main activities"
cap label var AC_NP_SEC "Productive unpaid secondary activities"
