cap label var CODE "Label - English"
cap label var TOTAL "All schemes"
cap label var GOV_CTL_C_CON_B "Central government schemes - compulsory - contributory - basic"
cap label var GOV_CTL_C_CON_S "Central government schemes - compulsory - contributory - supplementary"
cap label var GOV_CTL_C_NCON_B "Central government schemes - compulsory - non-contributory - basic"
cap label var GOV_CTL_C_NCON_S "Central government schemes - compulsory - non-contributory - supplementary"
cap label var GOV_CTL_NC_CON_B "Central government schemes - non-compulsory - contributory - basic"
cap label var GOV_CTL_NC_CON_S "Central government schemes - non-compulsory - contributory - supplementary"
cap label var GOV_CTL_NC_NCON_B "Central government schemes - non-compulsory - non-contributory - basic"
cap label var GOV_CTL_NC_NCON_S "Central government schemes - non-compulsory - non-contributory - supplementary"
cap label var GOV_LOC_B "State or local government schemes - basic"
cap label var GOV_LOC_S "State or local government schemes - supplementary"
cap label var SAL_B "Schemes for employees - basic"
cap label var SAL_S "Schemes for employees - supplementary"
cap label var OTH_NGOV_B "Other not government controlled schemes - basic"
cap label var OTH_NGOV_S "Other not government controlled schemes - supplementary"
