cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var GOV_LOC "Government or local authority"
cap label var EMPL "Employer"
cap label var EMPL_A "Employer - actual contributions"
cap label var EMPL_I "Employer - imputed contributions"
cap label var PER_PRO "Protected persons"
cap label var SAL "Employees"
cap label var SELF "Self-employed"
cap label var PEN_PER_PRO_OTH "Pensioners and other protected persons"
cap label var EMP "Employer"
cap label var INST_OTH "Other institution"
cap label var HH "Household"
cap label var PER_NHH "Private person who is not household member"
cap label var OTH "Other"
cap label var UNK "Unknown"
