cap label var CW_M "Co-worker - male"
cap label var BOSS_M "Boss - male"
cap label var OTH_W_M "Other work-related - male"
cap label var PERP "Perpetrators - male or female"
cap label var PERP_M "Perpetrators - male"
cap label var PERP_F "Perpetrators - female"
cap label var IPTN "Intimate partner - male or female"
cap label var NPTN "Non-partner - male or female"
cap label var NPTN_M "Non-partner - male"
cap label var NPTN_F "Non-partner - female"
cap label var FAM_REL "Family member or relative - male or female"
cap label var FAM_REL_M "Family member or relative - male"
cap label var KNW "Any known - male or female"
cap label var KNW_M "Any known - male"
cap label var KNW_OTH "Other known (non-family or relative) - male or female"
cap label var KNW_OTH_M "Other known (non-family or relative) - male"
cap label var STRNG "Stranger - male or female"
cap label var STRNG_M "Stranger - male"
