cap label var CODE "Label - English"
cap label var HOLD_HOLD "hold: Total number of holdings"
cap label var HOLDSL_HOLD "hold: Sole holder holdings"
cap label var HOLDLEG_GRP_HOLD "hold: Legal persons or group holdings"
cap label var AGRAREA_HA " Utilised agricultural area"
cap label var AGRAREA_HOLD "hold with Utilised agricultural area"
cap label var B_1_HA " Arable land"
cap label var B_1_HOLD "hold: Arable land"
cap label var B_1_1_HA " Cereals"
cap label var B_1_1_HOLD "hold: Cereals"
cap label var B_1_1_1_HA " Common wheat and spelt"
cap label var B_1_1_1_HOLD "hold: Common wheat and spelt"
cap label var B_1_1_2_HA " Durum wheat"
cap label var B_1_1_2_HOLD "hold: Durum wheat"
cap label var B_1_1_3_HA " Rye"
cap label var B_1_1_3_HOLD "hold: Rye"
cap label var B_1_1_4_HA " Barley"
cap label var B_1_1_4_HOLD "hold: Barley"
cap label var B_1_1_5_HA " Oats"
cap label var B_1_1_5_HOLD "hold: Oats"
cap label var B_1_1_6_HA " Grain maize"
cap label var B_1_1_6_HOLD "hold: Grain maize"
cap label var B_1_1_7_HA " Rice"
cap label var B_1_1_7_HOLD "hold: Rice"
cap label var B_1_1_99_HA " Other cereals"
cap label var B_1_1_99_HOLD "hold: Other cereals"
cap label var B_1_2_HA " Pulses - total"
cap label var B_1_2_HOLD "hold: Pulses - total"
cap label var B_1_345_HA " Root crops"
cap label var B_1_345_HOLD "hold: Root crops"
cap label var B_1_3_HA " Potatoes"
cap label var B_1_3_HOLD "hold: Potatoes"
cap label var B_1_4_HA " Sugar beet"
cap label var B_1_4_HOLD "hold: Sugar beet"
cap label var B_3_99_HA " Fodder crops and grass"
cap label var B_3_99_HOLD "hold: Fodder crops and grass"
cap label var B_1_5_HA " Fodder roots and brassicas"
cap label var B_1_5_HOLD "hold: Fodder roots and brassicas"
cap label var B_1_6_HA " Industrial crops - total"
cap label var B_1_6_HOLD "hold: Industrial crops - total"
cap label var B_1_6_1_HA " Tobacco"
cap label var B_1_6_1_HOLD "hold: Tobacco"
cap label var B_1_6_2_HA " Hops"
cap label var B_1_6_2_HOLD "hold: Hops"
cap label var B_1_6_3_HA " Cotton"
cap label var B_1_6_3_HOLD "hold: Cotton"
cap label var B_1_6_4_HA " Rape and turnip"
cap label var B_1_6_4_HOLD "hold: Rape and turnip"
cap label var B_1_6_5_HA " Sunflower"
cap label var B_1_6_5_HOLD "hold: Sunflower"
cap label var B_1_6_6_HA " Soya"
cap label var B_1_6_6_HOLD "hold: Soya"
cap label var B_1_6_7_11_HA "  Other oil-seed or fibre crops"
cap label var B_1_6_7_11_HOLD "hold:  Other oil-seed or fibre crops"
cap label var B_1_6_12_HA " Aromatic, medicinal and culinary plants"
cap label var B_1_6_12_HOLD "hold: Aromatic, medicinal and culinary plants"
cap label var B_1_6_99_HA " Industrial crops not mentioned elsewhere"
cap label var B_1_6_99_HOLD "hold: Industrial crops not mentioned elsewhere"
cap label var B_4_7_7_2_8_2_HA " Under glass:Vegetables, flowers and permanent crops"
cap label var B_4_7_7_2_8_2_HOLD "hold: Under glass:Vegetables, flowers and permanent crops"
cap label var B_1_7_HA " Fresh vegetables, melons, strawberries"
cap label var B_1_7_HOLD "hold: Fresh vegetables, melons, strawberries"
cap label var B_1_7_1_HA " Outdoor: Fresh vegetables, melons, strawberries"
cap label var B_1_7_1_HOLD "hold: Outdoor: Fresh vegetables, melons, strawberries"
cap label var B_1_7_1_1_HA " Open field: Outdoor: Fresh vegetables, melons, strawberries"
cap label var B_1_7_1_1_HOLD "hold: Open field: Outdoor: Fresh vegetables, melons, strawberries"
cap label var B_1_7_1_2_HA " Market gardening: Outdoor: Fresh vegetables, melons, strawberries"
cap label var B_1_7_1_2_HOLD "hold: Market gardening: Outdoor: Fresh vegetables, melons, strawberries"
cap label var B_1_7_2_HA " Under glass: Fresh vegetables, melons, strawberries"
cap label var B_1_7_2_HOLD "hold: Under glass: Fresh vegetables, melons, strawberries"
cap label var B_1_8_HA " Flowers and ornemental plants"
cap label var B_1_8_HOLD "hold: Flowers and ornemental plants"
cap label var B_1_8_1_HA " Outdoor: Flowers and ornemental plants"
cap label var B_1_8_1_HOLD "hold: Outdoor: Flowers and ornemental plants"
cap label var B_1_8_2_HA " Under glass: Flowers and ornemental plants"
cap label var B_1_8_2_HOLD "hold: Under glass: Flowers and ornemental plants"
cap label var B_1_9_HA " Fodder crops - total"
cap label var B_1_9_HOLD "hold: Fodder crops - total"
cap label var B_1_9_1_HA " Fodder crops - temporary grass"
cap label var B_1_9_1_HOLD "hold: Fodder crops - temporary grass"
cap label var B_1_9_2_HA " Total: Other green fodder: Fodder crops"
cap label var B_1_9_2_HOLD "hold: Total: Other green fodder: Fodder crops"
cap label var B_1_9_2_1_HA " Green maize: Other green fodder: Fodder crops"
cap label var B_1_9_2_1_HOLD "hold: Green maize: Other green fodder: Fodder crops"
cap label var B_1_9_2_2_HA " Other fodder crops: leguminous plants: Fodder crops"
cap label var B_1_9_2_2_HOLD "hold: Other fodder crops: leguminous plants: Fodder crops"
cap label var B_1_9_2_99_HA " Other green fodder - other than green maize and leguminous"
cap label var B_1_9_2_99_HOLD "hold: Other green fodder - other than green maize and leguminous"
cap label var B_1_10_11_HA " Seeds, seedlings and other crops on arable land"
cap label var B_1_10_11_HOLD "hold: Seeds, seedlings and other crops on arable land"
cap label var B_1_10_HA " Seeds and seedlings"
cap label var B_1_10_HOLD "hold: Seeds and seedlings"
cap label var B_1_11_HA " Other crops on arable land"
cap label var B_1_11_HOLD "hold: Other crops on arable land"
cap label var B_1_12_HA " Fallow land - total (with and w/o subsidies)"
cap label var B_1_12_HOLD "hold: Fallow land - total (with and w/o subsidies)"
cap label var B_2_HA " Kitchen gardens"
cap label var B_2_HOLD "hold: Kitchen gardens"
cap label var B_3_HA " Total: Permanent grassland and meadow"
cap label var B_3_HOLD "hold: Total: Permanent grassland and meadow"
cap label var B_3_1_HA " Pasture and meadow: Permanent grassland and meadow"
cap label var B_3_1_HOLD "hold: Pasture and meadow: Permanent grassland and meadow"
cap label var B_3_2_HA " Rough grazings: Permanent grassland and meadow"
cap label var B_3_2_HOLD "hold: Rough grazings: Permanent grassland and meadow"
cap label var B_3_3_HA " Permanent grassland and meadow - not used for production, eligible for subsidies"
cap label var B_3_3_HOLD "hold: Permanent grassland and meadow - not used for production, eligible for subsidies"
cap label var B_4_HA " Permanent crops"
cap label var B_4_HOLD "hold: Permanent crops"
cap label var B_4_1_HA " Fruit and berry plantations - total"
cap label var B_4_1_HOLD "hold: Fruit and berry plantations - total"
cap label var B_4_1_1_HA " Fruit species: Fruit and berry plantations"
cap label var B_4_1_1_HOLD "hold: Fruit species: Fruit and berry plantations"
cap label var B_4_1_1_1_HA " Fruit species of temperate climate zones"
cap label var B_4_1_1_1_HOLD "hold: Fruit species of temperate climate zones"
cap label var B_4_1_1_2_HA " Fruit species of subtropical climate zones"
cap label var B_4_1_1_2_HOLD "hold: Fruit species of subtropical climate zones"
cap label var B_4_1_2_HA " Berry species : Fruit and berry plantations"
cap label var B_4_1_2_HOLD "hold: Berry species: Fruit and berry plantations"
cap label var B_4_1_99_1_HA " Temperate climate: Fruit and berry plantations - until 2007"
cap label var B_4_1_99_1_HOLD "hold: Temperate climate: Fruit and berry plantations - until 2007"
cap label var B_4_1_99_2_HA " Subtropical climate :Fruit and berry plantations - until 2007"
cap label var B_4_1_99_2_HOLD "hold: Subtropical climate: Fruit and berry plantations - until 2007"
cap label var B_4_1_3_HA " Nuts: Fruit and berry plantations"
cap label var B_4_1_3_HOLD "hold:  Nuts: Fruit and berry plantations"
cap label var B_4_2_HA " Citrus plantations"
cap label var B_4_2_HOLD "hold: Citrus plantations"
cap label var B_4_3_HA " Olive plantations - total"
cap label var B_4_3_HOLD "hold: Olive plantations - total"
cap label var B_4_3_1_HA " Olive plantations - table olives"
cap label var B_4_3_1_HOLD "hold: Olive plantations - table olives"
cap label var B_4_3_2_HA " Olive plantations - oil production"
cap label var B_4_3_2_HOLD "hold: Olive plantations - oil production"
cap label var B_4_4_HA " Vineyards - total"
cap label var B_4_4_HOLD "hold: Vineyards - total"
cap label var B_4_4_1_HA " Vineyards - quality wine"
cap label var B_4_4_1_HOLD "hold: Vineyards - quality wine"
cap label var B_4_4_2_HA " Vineyards - other wines"
cap label var B_4_4_2_HOLD "hold: Vineyards - other wines"
cap label var B_4_4_3_HA " Vineyards - table grapes"
cap label var B_4_4_3_HOLD "hold: Vineyards - table grapes"
cap label var B_4_4_4_HA " Vineyards - raisins"
cap label var B_4_4_4_HOLD "hold: Vineyards - raisins"
cap label var B_4_5_HA " Nurseries"
cap label var B_4_5_HOLD "hold: Nurseries"
cap label var B_4_6_HA " Other permanent crops"
cap label var B_4_6_HOLD "hold: Other permanent crops"
cap label var B_4_7_HA " Permanent crops under glass"
cap label var B_4_7_HOLD "hold: Permanent crops under glass"
cap label var B_5_HA " Other land - Total"
cap label var B_5_HOLD "hold: Other land - Total"
cap label var B_5_1_5_3_HA " Unutilised agricultural land and other areas"
cap label var B_5_1_5_3_HOLD "hold: Unutilised agricultural land and other areas"
cap label var B_5_1_HA " Unutilised agricultural land"
cap label var B_5_1_HOLD "hold: Unutilised agricultural land"
cap label var B_5_2_HA " Wooded area"
cap label var B_5_2_HOLD "hold: Wooded area"
cap label var B_5_2_1_HA " Wooded area - with short rotation"
cap label var B_5_2_1_HOLD "hold: Wooded area - with short rotation"
cap label var B_5_3_HA " Other land"
cap label var B_5_3_HOLD "hold: Other land"
cap label var B_6_1_HA " Mushrooms"
cap label var B_6_1_HOLD "hold: Mushrooms"
cap label var B_6_3_HA " Energy crops"
cap label var B_6_3_HOLD "hold: Energy crops"
cap label var B_6_3_1_HA " Energy crops on set-aside area"
cap label var B_6_3_1_HOLD "hold: Energy crops on set-aside area"
cap label var B_6_4_HA " Genetically modified crops"
cap label var B_6_4_HOLD "hold: Genetically modified crops"
cap label var B_6_2_1_HA " Total irrigable area"
cap label var B_6_2_1_HOLD "hold: Total irrigable area"
cap label var B_6_2_2_HA " Irrigated at least once a year : Total (excl. kitchen gardens and area under glass)"
cap label var B_6_2_2_HOLD "hold with area irrigated at least once a year: Total (excl. kitchen gardens and area under glass)"
cap label var B_6_2_2_99_HOLD "hold with area irrigated at least once a year: Total (incl. kitchen gardens and area under glass)"
cap label var C_LIVESTOCK_HOLD "hold: Number of holdings with livestock"
cap label var C_LIVESTOCK_LSU "LSU of the holdings with livestock"
cap label var C_1_HEADS " Equidae"
cap label var C_1_HOLD "hold: Equidae"
cap label var C_2_HEADS " Cattle - total"
cap label var C_2_HOLD "hold: Cattle - total"
cap label var C_2_1_HEADS " Bovine <1 year old - total"
cap label var C_2_1_HOLD "hold: Bovine <1 year old - total"
cap label var C_2_2_HEADS " Bovine 1-<2 years - males"
cap label var C_2_2_HOLD "hold: Bovine 1-<2 years - males"
cap label var C_2_3_HEADS " Bovine 1-<2 years - females"
cap label var C_2_3_HOLD "hold: Bovine 1-<2 years - females"
cap label var C_2_4_HEADS " Bovine 2 years and older - males"
cap label var C_2_4_HOLD "hold: Bovine 2 years and older - males"
cap label var C_2_5_HEADS " Heifers, 2 years and older"
cap label var C_2_5_HOLD "hold: Heifers, 2 years and older"
cap label var C_2_6_HEADS " Dairy cows"
cap label var C_2_6_HOLD "hold: Dairy cows"
cap label var C_2_99_HEADS " Other cows, bovine 2 years old and over"
cap label var C_2_99_HOLD "hold: Other cows, bovine 2 years old and over"
cap label var C_3_1_HEADS " Sheep - total"
cap label var C_3_1_HOLD "hold: Sheep - total"
cap label var C_3_1_1_HEADS " Sheep - breeding females"
cap label var C_3_1_1_HOLD "hold: Sheep - breeding females"
cap label var C_3_1_99_HEADS " Sheep - others"
cap label var C_3_1_99_HOLD "hold: Sheep - others"
cap label var C_3_2_HEADS " Goats"
cap label var C_3_2_HOLD "hold: Goats"
cap label var C_3_2_1_HEADS " Goats - breeding females"
cap label var C_3_2_1_HOLD "hold: Goats - breeding females"
cap label var C_3_2_99_HEADS " Goats - others"
cap label var C_3_2_99_HOLD "hold: Goats - others"
cap label var C_4_HEADS " Pigs"
cap label var C_4_HOLD "hold: Pigs"
cap label var C_4_1_HEADS " Pigs - piglets under 20 kg"
cap label var C_4_1_HOLD "hold: Pigs - piglets under 20 kg"
cap label var C_4_2_HEADS " Pigs - breeding sows over 50 kg"
cap label var C_4_2_HOLD "hold: Pigs - breeding sows over 50 kg"
cap label var C_4_99_HEADS " Pigs - others"
cap label var C_4_99_HOLD "hold: Pigs - others"
cap label var C_5_1000_HEADS "1000 heads: Poultry"
cap label var C_5_HOLD "hold: Poultry"
cap label var C_5_1_1000_HEADS "1000 heads: Poultry - broilers"
cap label var C_5_1_HOLD "hold: Poultry - broilers"
cap label var C_5_2_1000_HEADS "1000 heads: Laying hens"
cap label var C_5_2_HOLD "hold: Laying hens"
cap label var C_5_3_1000_HEADS "1000 heads: Poultry - others"
cap label var C_5_3_HOLD "hold: Poultry - others"
cap label var C_6_HEADS " Rabbits (breeding females)"
cap label var C_6_HOLD "hold: Rabbits (breeding females)"
cap label var C_7_HIVE " Beehives"
cap label var C_7_HOLD "hold: Beehives"
cap label var C_99_EQ_Y_HOLD "Holdings with other livestock"
cap label var A_3_2_1_HOLD "hold:Organic farming - certified"
cap label var A_3_2_1_HA "Organic farming - certified"
cap label var A_3_2_2_HOLD "hold:Farming system - Conversion to organic farming"
cap label var A_3_2_2_HA "Farming system - Conversion to organic farming"
cap label var A_3_2_3_HOLD "hold:Organic farming (incl. in conversion)"
cap label var A_3_2_3_HA "Organic farming (incl. in conversion)"
cap label var A_3_2_3_1_HOLD "hold:Organic farming - cereals"
cap label var A_3_2_3_1_HA "Organic farming - cereals"
cap label var A_3_2_3_2_HOLD "hold:Organic farming - dried pulses"
cap label var A_3_2_3_2_HA "Organic farming - dried pulses"
cap label var A_3_2_3_3_HOLD "hold:Organic farming - potatoes"
cap label var A_3_2_3_3_HA "Organic farming - potatoes"
cap label var A_3_2_3_4_HOLD "hold:Organic farming - sugar beet"
cap label var A_3_2_3_4_HA "Organic farming - sugar beet"
cap label var A_3_2_3_5_HOLD "hold:Organic farming - oil seed crops"
cap label var A_3_2_3_5_HA "Organic farming - oil crops"
cap label var A_3_2_3_6_HOLD "hold:Organic farming - fresh vegetables, melons, strawberries"
cap label var A_3_2_3_6_HA "Organic farming - fresh vegetables, melons, strawberries"
cap label var A_3_2_3_7_HOLD "hold:Organic farming - pasture and meadow, excl. rough grazings"
cap label var A_3_2_3_7_HA "Organic farming - pasture and meadow, excl. rough grazings"
cap label var A_3_2_3_8_HOLD "hold:Organic farming - fruit and berry"
cap label var A_3_2_3_8_HA "Organic farming - fruit and berry"
cap label var A_3_2_3_9_HOLD "hold:Organic farming - citrus fruit"
cap label var A_3_2_3_9_HA "Organic farming - citrus fruit"
cap label var A_3_2_3_10_HOLD "hold:Organic farming - olives"
cap label var A_3_2_3_10_HA "Organic farming - olives"
cap label var A_3_2_3_11_HOLD "hold:Organic farming - vineyards"
cap label var A_3_2_3_11_HA "Organic farming - vineyards"
cap label var A_3_2_3_99_HOLD "hold:Organic farming - other crops"
cap label var A_3_2_3_99_HA "Organic farming - other crops"
cap label var A_3_2_4_1_HOLD "hold: Organic farming - bovine animals"
cap label var A_3_2_4_1_HEADS "Organic farming - bovine animals"
cap label var A_3_2_4_2_HOLD "hold: Organic farming - pigs"
cap label var A_3_2_4_2_HEADS "Organic farming - pigs"
cap label var A_3_2_4_3_HOLD "hold: Organic farming - sheep and goats"
cap label var A_3_2_4_3_HEADS "Organic farming - sheep and goats"
cap label var A_3_2_4_4_HOLD "hold: Organic farming - poultry"
cap label var A_3_2_4_4_HEADS "Organic farming - poultry"
cap label var A_3_2_4_5_EQ_Y_HOLD "hold: Organic farming - with other animals"
cap label var E_1_2_4B_EQ_Y_HOLD "Hold. with vocational training by manager in last 12 months"
cap label var M_8_1_1_HA " Average area irrigated in the last 3 years"
cap label var M_8_1_1_HOLD "hold: Average area irrigated in the last 3 years"
cap label var M_8_1_2_1_HA " Area irrigated in the previous 12 months: cereals (excl. maize and rice)"
cap label var M_8_1_2_1_HOLD "hold: Area irrigated in the previous 12 months: cereals (excl. maize and rice)"
cap label var M_8_1_2_2_HA " Area irrigated in the previous 12 months: maize (grain and green)"
cap label var M_8_1_2_2_HOLD "hold: Area irrigated in the previous 12 months: maize (grain and green)"
cap label var M_8_1_2_3_HA " Area irrigated in the previous 12 months: rice"
cap label var M_8_1_2_3_HOLD "hold: Area irrigated in the previous 12 months: rice"
cap label var M_8_1_2_4_HA " Area irrigated in the previous 12 months: pulses"
cap label var M_8_1_2_4_HOLD "hold: Area irrigated in the previous 12 months: pulses"
cap label var M_8_1_2_5_HA " Area irrigated in the previous 12 months: potatoes"
cap label var M_8_1_2_5_HOLD "hold: Area irrigated in the previous 12 months: potatoes"
cap label var M_8_1_2_6_HA " Area irrigated in the previous 12 months: sugar beet"
cap label var M_8_1_2_6_HOLD "hold: Area irrigated in the previous 12 months: sugar beet"
cap label var M_8_1_2_7_HA " Area irrigated in the previous 12 months: rape and turnip rape"
cap label var M_8_1_2_7_HOLD "hold: Area irrigated in the previous 12 months: rape and turnip rape"
cap label var M_8_1_2_8_HA " Area irrigated in the previous 12 months: sunflower"
cap label var M_8_1_2_8_HOLD "hold: Area irrigated in the previous 12 months: sunflower"
cap label var M_8_1_2_9_HA " Area irrigated in the previous 12 months: textile crops"
cap label var M_8_1_2_9_HOLD "hold: Area irrigated in the previous 12 months: textile crops"
cap label var M_8_1_2_10_HA " Area irrigated in the previous 12 months: Fresh vegetables, melons, strawberries - open field"
cap label var M_8_1_2_10_HOLD "hold: Area irrigated in the previous 12 months: Fresh vegetables, melons, strawberries - open field"
cap label var M_8_1_2_11_HA " Area irrigated in the previous 12 months: Temporary and permanent grass grass"
cap label var M_8_1_2_11_HOLD "hold: Area irrigated in the previous 12 months: Temporary and permanent grass grass"
cap label var M_8_1_2_12_HA " Area irrigated in the previous 12 months: other crops on arable land"
cap label var M_8_1_2_12_HOLD "hold: Area irrigated in the previous 12 months: other crops on arable land"
cap label var M_8_1_2_13_HA " Area irrigated in the previous 12 months: fruit and berry plantations"
cap label var M_8_1_2_13_HOLD "hold: Area irrigated in the previous 12 months: fruit and berry plantations"
cap label var M_8_1_2_14_HA " Area irrigated in the previous 12 months: citrus plantations"
cap label var M_8_1_2_14_HOLD "hold: Area irrigated in the previous 12 months: citrus plantations"
cap label var M_8_1_2_15_HA " Area irrigated in the previous 12 months: olive plantations"
cap label var M_8_1_2_15_HOLD "hold: Area irrigated in the previous 12 months: olive plantations"
cap label var M_8_1_2_16_HA " Area irrigated in the previous 12 months: vineyards"
cap label var M_8_1_2_16_HOLD "hold: Area irrigated in the previous 12 months: vineyards"
cap label var M_8_2_1_EQ_Y_HOLD "hold: Holdings with: Irrigation method: Surface irrigation"
cap label var M_8_2_2_EQ_Y_HOLD "hold: Holdings with: Irrigation method: Sprinkler irrigation"
cap label var M_8_2_3_EQ_Y_HOLD "hold: Holdings with: Irrigation method: Drop irrigation"
cap label var M_8_3_1_EQ_Y_HOLD "hold: Holdings with: Source of water: on-farm ground water"
cap label var M_8_3_2_EQ_Y_HOLD "hold: Holdings with: Source of water: on-farm surface water"
cap label var M_8_3_3_EQ_Y_HOLD "hold: Holdings with: Source of water: off-farm surface water"
cap label var M_8_3_4_EQ_Y_HOLD "hold: Holdings with: Source of water: off-farm water from water supply networks"
cap label var M_8_3_99_EQ_Y_HOLD "hold: Holdings with: Source of water: other sources"
cap label var M_8_4_M3 "Volume of water used for irrigation per year - in m3"
cap label var LFH_W_PERS " Sole holders working on the farm"
cap label var LFH_W_F_PERS " Female: Sole holders working on the farm"
cap label var LFH_W_M_PERS " Male: Sole holders working on the farm"
cap label var LFRMF_PERS " Labour force - members of sole holders' family"
cap label var LFRMF_M_PERS " Male: Labour force: members of sole holders' family"
cap label var LFRMF_F_PERS " Female: Labour force: members of sole holders' family"
cap label var LFRF_PERS " Family labour force"
cap label var LFRF_M_PERS " Male: Family labour force"
cap label var LFRF_F_PERS " Female: Family labour force"
cap label var LFRNF_PERS " Regular non family labour force"
cap label var LFRNF_M_PERS " Male: Regular non family labour force"
cap label var LFRNF_F_PERS " Female: Regular non family labour force"
cap label var LFR_PERS " Regular Labour force"
cap label var LFR_M_PERS " Male: Regular labour force"
cap label var LFR_F_PERS " Female: Regular labour force"
cap label var LFH_AWU " Sole holders"
cap label var LFH_W_F_AWU " Female: Sole holders working on the farm"
cap label var LFH_W_M_AWU " Male: Sole holders working on the farm"
cap label var LFRMF_AWU " Labour force : members of sole holders' family"
cap label var LFRMF_M_AWU " Male: Labour force: members of sole holders' family - calculated"
cap label var LFRMF_F_AWU " Female: Labour force: members of sole holders' family-calculated"
cap label var LFRF_AWU " Family labour force"
cap label var LFRF_M_AWU " Male: Family labour force"
cap label var LFRF_F_AWU " Females: Family labour force"
cap label var LFRNF_AWU " Regular non family labour force"
cap label var LFRNF_M_AWU " Male: Regular non family labour force"
cap label var LFRNF_F_AWU " Female: Regular non family labour force"
cap label var LFR_AWU " Regular Labour force"
cap label var LFR_M_AWU " Male: Regular labour force"
cap label var LFR_F_AWU " Female: Regular labour force"
cap label var LFNRNF_AWU " Non-family labour force working on non-regular basis"
cap label var LFD_AWU " Total: Labour force directly employed by the holding"
cap label var LFND_AWU " Labour force  not directly employed by the holding"
cap label var SO_EURO " Standard output (SO)"
cap label var A_3_1_1_HA " Farming by owner: Agricultural area"
cap label var A_3_1_1_HOLD "hold: Farming by owner: Agricultural area"
cap label var A_3_1_2_HA " Farming by tenant: Agricultural area"
cap label var A_3_1_2_HOLD "hold: Farming by tenant: Agricultural area"
cap label var A_3_1_3_HA " Shared farming or other modes: Agricultural area"
cap label var A_3_1_3_HOLD "hold: Shared farming or other modes: Agricultural area"
cap label var TOTAREA_HA " Total area"
cap label var TOTAREA_HOLD "hold: Total area"
cap label var A_3_3_1_EQ_Y_HOLD "hold: More than 50% of producion self-consumed by the holder"
cap label var D_2_1_1_Y_HOLD "Holdings with equipment for energy production: wind"
cap label var D_2_1_1_Y_HA " UAA of holdings with equipment for energy production: wind"
cap label var D_2_1_2_Y_HOLD "Holdings with equipment for energy production: biomass"
cap label var D_2_1_2_Y_HA " UAA of holdings with equipment for energy production: biomass"
cap label var D_2_1_2_1_Y_HOLD "Holdings with equipment for energy production: bio- methane from biomass"
cap label var D_2_1_2_1_Y_HA " UAA of holdings with equipment for energy production: bio- methane from biomass"
cap label var D_2_1_3_Y_HOLD "Holdings with equipment for energy production: solar energy"
cap label var D_2_1_3_Y_HA " UAA of holdings with equipment for energy production: solar energy"
cap label var D_2_1_4_Y_HOLD "Holdings with equipment for energy production: hydro- energy"
cap label var D_2_1_4_Y_HA " UAA of holdings with equipment for energy production: hydro- energy"
cap label var D_2_1_99_Y_HOLD "Holdings with equipment for energy production: other sources"
cap label var D_2_1_99_Y_HA " UAA of holdings with equipment for energy production: other sources"
cap label var OGA_H_D_Y_HOLD "hold. with OGA of the sole holder-manager related directly to the holding"
cap label var OGA_H_N_Y_HOLD "hold. with OGA of the sole holder-manager not related directly to the holding"
cap label var OGA_S_D_Y_HOLD "hold. with OGA of the spouse of the sole holder-manager related directly to the holding"
cap label var OGA_S_N_Y_HOLD "hold. with OGA of the spouse of the sole holder-manager not related directly to the holding"
cap label var OGA_F_M_PERS " other family members of sole holder with major OGA"
cap label var OGA_F_M_HOLD "hold: other family members of sole holder with major OGA"
cap label var OGA_F_S_PERS " other family members of sole holder with subsidiary OGA"
cap label var OGA_F_S_HOLD "hold: other family members of sole holder with subsidiary OGA"
cap label var OGA_F_D_PERS " other family members of sole holder with OGA related to the holding"
cap label var OGA_F_D_HOLD "hold: other family members of sole holder with OGA related to the holding"
cap label var OGA_F_N_PERS "other family members of sole holder with OGA not related to the holding"
cap label var OGA_F_N_HOLD "hold:other family members of sole holder with OGA not related to the holding"
cap label var OGA_N_D_M_PERS "non-family workers with major OGA related to the holding"
cap label var OGA_N_D_M_HOLD "hold: non-family workers with major OGA related to the holding"
cap label var OGA_N_D_S_PERS "non-family workers with subsidiary OGA related to the holding"
cap label var OGA_N_D_S_HOLD "hold:non-family workers with subsidiary OGA related to the holding"
cap label var OGA_F_1_Y_HOLD "Holdings with OGA"
cap label var OGA_F_1_Y_HA " UAA of hold. with OGA"
cap label var OGA_F_1_Y_EUR " SO of hold. with OGA"
cap label var OGA_F_1_Y_LSU "LSU of hold. with OGA"
cap label var OGA_F_1_1_Y_HOLD "hold:Tourism as OGA"
cap label var OGA_F_1_1_Y_HA " UAA of hold. with tourism as OGA"
cap label var OGA_F_1_1_Y_EUR " SO of hold. with tourism as OGA"
cap label var OGA_F_1_1_Y_LSU "LSU of hold. with tourism as OGA"
cap label var OGA_F_1_2_Y_HOLD "hold: Handicraft as OGA"
cap label var OGA_F_1_2_Y_HA " UAA of hold. with handcraft as OGA"
cap label var OGA_F_1_2_Y_EUR " SO of hold. with handcraft as OGA"
cap label var OGA_F_1_2_Y_LSU "LSU of hold. with handcraft as OGA"
cap label var OGA_F_1_3_Y_HOLD "hold:Processing of farm products as OGA"
cap label var OGA_F_1_3_Y_HA " UAA of hold with processing of farm products as OGA"
cap label var OGA_F_1_3_Y_EUR " SO of hold with processing of farm products as OGA"
cap label var OGA_F_1_3_Y_LSU "LSU of hold with processing of farm products as OGA"
cap label var OGA_F_1_4_Y_HOLD "hold:Renewable energy production as OGA"
cap label var OGA_F_1_4_Y_HA " UAA of hold. with renewable energy production as OGA"
cap label var OGA_F_1_4_Y_EUR " SO of hold. with renewable energy production as OGA"
cap label var OGA_F_1_4_Y_LSU "LSU of hold. with renewable energy production as OGA"
cap label var OGA_F_1_5_Y_HOLD "hold: Wood processing as OGA"
cap label var OGA_F_1_5_Y_HA " UAA of hold. with wood processing as OGA"
cap label var OGA_F_1_5_Y_EUR " SO of hold. with wood processing as OGA"
cap label var OGA_F_1_5_Y_LSU "LSU of hold. with wood processing as OGA"
cap label var OGA_F_1_6_Y_HOLD "hold: Aquaculture as OGA"
cap label var OGA_F_1_6_Y_HA " UAA of hold. with aquaculture as OGA"
cap label var OGA_F_1_6_Y_EUR " SO of hold. with aquaculture as OGA"
cap label var OGA_F_1_6_Y_LSU "LSU of hold. with aquaculture as OGA"
cap label var OGA_F_1_7_Y_HOLD "hold: Contractual work as OGA"
cap label var OGA_F_1_7_Y_HA " UAA of hold. with contractual work as OGA"
cap label var OGA_F_1_7_Y_EUR " SO of hold. with contractual work as OGA"
cap label var OGA_F_1_7_Y_LSU "LSU of hold. with contractual work as OGA"
cap label var OGA_F_1_7_1_Y_HOLD "hold:Contractual agricultural work as OGA"
cap label var OGA_F_1_7_1_Y_HA " UAA of hold. with contractual agricultural work as OGA"
cap label var OGA_F_1_7_1_Y_EUR " SO of hold. with contractual agricultural work as OGA"
cap label var OGA_F_1_7_1_Y_LSU "LSU of hold. with contractual agricultural work as OGA"
cap label var OGA_F_1_7_2_Y_HOLD "hold:Contractual non-agricultural work as OGA"
cap label var OGA_F_1_7_2_Y_HA " UAA of hold. with contractual non-agricultural work as OGA"
cap label var OGA_F_1_7_2_Y_EUR "SO of hold. with contractual non-agricultural work as OGA"
cap label var OGA_F_1_7_2_Y_LSU "LSU of hold. with contractual non-agricultural work as OGA"
cap label var OGA_F_1_8_Y_HOLD "hold: Forestry-work as OGA"
cap label var OGA_F_1_8_Y_HA " UAA of hold. with forestry-work as OGA"
cap label var OGA_F_1_8_Y_EUR " SO of hold. with forestry-work as OGA"
cap label var OGA_F_1_8_Y_LSU "LSU of hold. with forestry-work as OGA"
cap label var OGA_F_1_99_Y_HOLD "hold: OGA not mentioned elsewhere"
cap label var OGA_F_1_99_Y_HA " UAA of hold. with OGA n.m.e."
cap label var OGA_F_1_99_Y_EUR " SO of hold. with OGA n.m.e."
cap label var OGA_F_1_99_Y_LSU "LSU of hold. with OGA n.m.e."
cap label var OGA_F_2_1_0_HOLD "Holdings with up to 10% of turnover coming from OGA"
cap label var OGA_F_2_1_0_HA " UAA of hold. with up to 10% of turnover coming from OGA"
cap label var OGA_F_2_1_0_EUR " SO of hold. with up to 10% of turnover coming from OGA"
cap label var OGA_F_2_1_0_LSU "LSU of hold. with up to 10% of turnover coming from OGA"
cap label var OGA_F_2_1_11_HOLD "Holdings with 10% to 50% of turnover coming from OGA"
cap label var OGA_F_2_1_11_HA " UAA of hold. with 10% to 50% of turnover coming from OGA"
cap label var OGA_F_2_1_11_EUR " SO of hold. with 10% to 50% of turnover coming from OGA"
cap label var OGA_F_2_1_11_LSU " of hold. with 10% to 50% of turnover coming from OGA"
cap label var OGA_F_2_1_51_HOLD "Holdings with more than 50% of turnover coming from OGA"
cap label var OGA_F_2_1_51_HA " UAA of hold. with more than 50% of turnover coming from OGA"
cap label var OGA_F_2_1_51_EUR " SO of hold. with more than 50% of turnover coming from OGA"
cap label var OGA_F_2_1_51_LSU "LSU of hold. with more than 50% of turnover coming from OGA"
cap label var RD_G_1_Y_HOLD "holdings benefiting from listed measures of rural development support"
cap label var RD_G_1_Y_HA " UAA of hold. benefiting from listed measures of rural development support"
cap label var RD_G_1_Y_EUR " SO of hold. benefiting from listed measures of rural development support"
cap label var RD_G_1_Y_LSU "LSU of of hold. benefiting from listed measures of rural development support"
cap label var RD_G_1_1_Y_HOLD "holdings benefiting advisory services "
cap label var RD_G_1_1_Y_HA " UAA of hold. benefiting advisory services "
cap label var RD_G_1_1_Y_EUR " SO of hold. benefiting advisory services "
cap label var RD_G_1_1_Y_LSU "LSU of hold. benefiting advisory services "
cap label var RD_G_1_2_Y_HOLD "holdings benefiting measures for modernisation "
cap label var RD_G_1_2_Y_HA " UAA of hold. benefiting measures for modernisation "
cap label var RD_G_1_2_Y_EUR " SO of hold. benefiting measures for modernisation "
cap label var RD_G_1_2_Y_LSU "LSU of hold. benefiting measures for modernisation "
cap label var RD_G_1_3_Y_HOLD "holdings benefiting measures adding value to products "
cap label var RD_G_1_3_Y_HA " UAA of hold. benefiting measures adding value to products "
cap label var RD_G_1_3_Y_EUR "SO of hold. benefiting measures adding value to products "
cap label var RD_G_1_3_Y_LSU "LSU of hold. benefiting measures adding value to products "
cap label var RD_G_1_4_Y_HOLD "holdings benefiting measures Community standards "
cap label var RD_G_1_4_Y_HA " UAA of hold. benefiting measures Community standards "
cap label var RD_G_1_4_Y_EUR " SO of hold. benefiting measures Community standards "
cap label var RD_G_1_4_Y_LSU "LSU of hold. benefiting measures Community standards "
cap label var RD_G_1_5_Y_HOLD "holdings benefiting measures Food quality scheme "
cap label var RD_G_1_5_Y_HA " UAA of hold. benefiting measures Food quality scheme "
cap label var RD_G_1_5_Y_EUR " SO of hold. benefiting measures Food quality scheme "
cap label var RD_G_1_5_Y_LSU "LSU of hold. benefiting measures Food quality scheme "
cap label var RD_G_1_6_Y_HOLD "holdings benefiting measures Natura 2000 payments "
cap label var RD_G_1_6_Y_HA " UAA of hold. benefiting measures Natura 2000 payments "
cap label var RD_G_1_6_Y_EUR " SO of hold. benefiting measures Natura 2000 payments "
cap label var RD_G_1_6_Y_LSU "LSU of hold. benefiting measures Natura 2000 payments "
cap label var RD_G_1_7_Y_HOLD "holdings benefiting measures for payments under Water Framework Directive "
cap label var RD_G_1_7_Y_HA " UAA of hold. benefiting measures for payments under Water Framework Directive "
cap label var RD_G_1_7_Y_EUR " SO of hold. benefiting measures for payments under Water Framework Directive "
cap label var RD_G_1_7_Y_LSU "LSU of hold. benefiting measures for payments under Water Framework Directive "
cap label var RD_G_1_8_Y_HOLD "holdings benefiting measures for Agri-environment payments "
cap label var RD_G_1_8_Y_HA " UAA of hold. benefiting measures for Agri-environment payments "
cap label var RD_G_1_8_Y_EUR " SO of hold. benefiting measures for Agri-environment payments "
cap label var RD_G_1_8_Y_LSU "LSU of hold. benefiting measures for Agri-environment payments "
cap label var RD_G_1_8_1_Y_HOLD "holdings benefiting measures for Agri-environment payments for organic farming "
cap label var RD_G_1_8_1_Y_HA " UAA of hold. benefiting measures for Agri-environment payments for organic farming "
cap label var RD_G_1_8_1_Y_EUR " SO of hold. benefiting measures for Agri-environment payments for organic farming "
cap label var RD_G_1_8_1_Y_LSU "LSU of hold. benefiting measures for Agri-environment payments for organic farming "
cap label var RD_G_1_9_Y_HOLD "holdings benefiting measures for Animal welfare payments "
cap label var RD_G_1_9_Y_HA " UAA of hold. benefiting measures for Animal welfare payments "
cap label var RD_G_1_9_Y_EUR " SO of hold. benefiting measures for Animal welfare payments "
cap label var RD_G_1_9_Y_LSU "LSU of hold. benefiting measures for Animal welfare payments "
cap label var RD_G_1_10_Y_HOLD "holdings benefiting measures for Diversification into non-agricultural activities "
cap label var RD_G_1_10_Y_HA " UAA of hold. benefiting measures for Diversification into non-agricultural activities "
cap label var RD_G_1_10_Y_EUR " SO of hold. benefiting measures for Diversification into non-agricultural activities "
cap label var RD_G_1_10_Y_LSU "LSU of hold. benefiting measures for Diversification into non-agricultural activities "
cap label var RD_G_1_11_Y_HOLD "holdings benefiting measures for Encouragement of tourism activities "
cap label var RD_G_1_11_Y_HA " UAA of hold. benefiting measures for Encouragement of tourism activities "
cap label var RD_G_1_11_Y_EUR " SO of hold. benefiting measures for Encouragement of tourism activities "
cap label var RD_G_1_11_Y_LSU "LSU of hold. benefiting measures for Encouragement of tourism activities "
cap label var D_1_1_A "Four-wheel tractors, track-laying tractors, tool carriers belonging exclusively to the holding"
cap label var D_1_1_B "Cultivators etc. belonging exclusively to the holding"
cap label var D_1_1_C "Combine harvesters belonging exclusively to the holding"
cap label var D_1_1_D "Other fully mechanised harvesters belonging exclusively to the holding"
cap label var D_1_2_A_EQ_Y "Use in the last 12 months of four-wheel tractors etc. used by several holdings"
cap label var D_1_2_B_EQ_Y "Use in the last 12 months of cultivators etc. used by several holdings"
cap label var D_1_2_C_EQ_Y "Use in the last 12 months of combine harvesters used by several holdings"
cap label var D_1_2_D_EQ_Y "Use in the last 12 months of other fully mechanised harvesters used by several holdings"
