cap label var CODE "Label - English"
cap label var SPR "Social protection benefits"
cap label var CASH "Cash benefits"
cap label var CASH_P "Periodic cash benefits"
cap label var CASH_P_PSICK "Periodic cash benefits - paid sick leave"
cap label var CASH_P_DIS_PEN "Periodic cash benefits - disability pension"
cap label var CASH_P_ERRC "Periodic cash benefits - early retirement benefit due to reduced capacity to work"
cap label var CASH_P_OLD_PEN "Periodic cash benefits - old age pension"
cap label var CASH_P_AOLD_PEN "Periodic cash benefits - anticipated old age pension"
cap label var CASH_P_PART_PEN "Periodic cash benefits - partial pension"
cap label var CASH_P_CARE "Periodic cash benefits - care allowance"
cap label var CASH_P_EH "Periodic cash benefits - economic integration of the handicapped"
cap label var CASH_P_SRV_PEN "Periodic cash benefits - survivors' pension"
cap label var CASH_P_MNTCHB "Periodic cash benefits - income maintenance in the event of childbirth"
cap label var CASH_P_PARL "Periodic cash benefits - parental leave"
cap label var CASH_P_FAM_ALL "Periodic cash benefits - family or child allowance"
cap label var CASH_P_UNE_FULL "Periodic cash benefits - full unemployment"
cap label var CASH_P_UNE_PART "Periodic cash benefits - partial unemployment"
cap label var CASH_P_ERLM "Periodic cash benefits - early retirement benefit for labour market reasons"
cap label var CASH_P_VT_ALL "Periodic cash benefits - vocational training allowance"
cap label var CASH_P_INC "Periodic cash benefits - income support"
cap label var CASH_P_OTH "Periodic cash benefits - other"
cap label var CASH_LUMP "Lump sum cash benefits"
cap label var CASH_LUMP_CARE "Lump sum cash benefits - care allowance"
cap label var CASH_LUMP_EH "Lump sum cash benefits - economic integration of the handicapped"
cap label var CASH_LUMP_DTH "Lump sum cash benefits - death grant"
cap label var CASH_LUMP_BRTH "Lump sum cash benefits - birth grant"
cap label var CASH_LUMP_PARL "Lump sum cash benefits - parental leave"
cap label var CASH_LUMP_VT_ALL "Lump sum cash benefits - vocational training allowance"
cap label var CASH_LUMP_RED_COMP "Lump sum cash benefits - redundancy compensation"
cap label var CASH_LUMP_OTH "Lump sum cash benefits - other"
cap label var KND "Benefits in kind"
cap label var KND_IN "Benefits in kind - in-patient care"
cap label var KND_IN_DPR "Benefits in kind - in-patient care direct provision"
cap label var KND_IN_REMB "Benefits in kind - in-patient care reimbursement"
cap label var KND_OUT "Benefits in kind - out-patient care"
cap label var KND_OUT_DPR_PHRM "Benefits in kind - out-patient care direct provision of pharmaceutical products"
cap label var KND_OUT_DPR_OTH "Benefits in kind - out-patient care other direct provision"
cap label var KND_OUT_REMB_PHRM "Benefits in kind - out-patient care reimbursement of pharmaceutical products"
cap label var KND_OUT_REMB_OTH "Benefits in kind - out-patient care other reimbursement"
cap label var KND_CHDC "Benefits in kind - child day care"
cap label var KND_ACCOM "Benefits in kind - accommodation"
cap label var KND_ASS_DT "Benefits in kind - assistance in carrying out daily tasks"
cap label var KND_REH "Benefits in kind - rehabilitation"
cap label var KND_FUNE "Benefits in kind - funeral expenses"
cap label var KND_HOM "Benefits in kind - home help"
cap label var KND_MOB "Benefits in kind - mobility and resettlement"
cap label var KND_VT "Benefits in kind - vocational training"
cap label var KND_PSJOB "Benefits in kind - placement services and job search assistance"
cap label var KND_RENT "Benefits in kind - rent"
cap label var KND_RENT_SHOU "Benefits in kind - rent - social housing"
cap label var KND_RENT_OTH "Benefits in kind - rent - other"
cap label var KND_OWN "Benefits in kind - benefit to owner-occupiers"
cap label var KND_REH_ABUS "Benefits on kind - rehabilitation of alcohol and drugs abusers"
cap label var KND_OTH "Benefits in kind - other"
cap label var SPBENEFNOREROUTE "Social protection benefits"
cap label var SNONTARGETNOREROUTE "Non means-tested benefits"
cap label var STARGETNOREROUTE "Means-tested benefits"
cap label var STTCASH "Cash benefits"
cap label var SNTCASH "Cash benefits (non means-tested)"
cap label var STACASH "Cash benefits (means-tested)"
cap label var STTCPERIOD "Periodic cash benefits"
cap label var SNTCPERIOD "Periodic cash benefits (non means-tested)"
cap label var STACPERIOD "Periodic cash benefits (means-tested)"
cap label var STTCPSICK "Paid sick leave benefit"
cap label var SNTCPSICK "Paid sick leave benefit (non means-tested)"
cap label var STACPSICK "Paid sick leave benefit (means-tested)"
cap label var STTCPDISPEN "Disability pension"
cap label var SNTCPDISPEN "Disability pension (non means-tested)"
cap label var STACPDISPEN "Disability pension (means-tested)"
cap label var STTCPEARLYRED "Early retirement benefit due to reduced capacity to work"
cap label var SNTCPEARLYRED "Early retirement benefit due to reduced capacity to work (non means-tested)"
cap label var STACPEARLYRED "Early retirement benefit due to reduced capacity to work (means-tested)"
cap label var STTCPOLDPEN "Old age pension"
cap label var SNTCPOLDPEN "Old age pension (non means-tested)"
cap label var STACPOLDPEN "Old age pension (means-tested)"
cap label var STTCPANTPEN "Anticipated old age pension"
cap label var SNTCPANTPEN "Anticipated old age pension (non means-tested)"
cap label var STACPANTPEN "Anticipated old age pension (means-tested)"
cap label var STTCPPARPEN "Partial pension"
cap label var SNTCPPARPEN "Partial pension (non means-tested)"
cap label var STACPPARPEN "Partial pension (means-tested)"
cap label var STTCPCARE "Periodic care allowance"
cap label var SNTCPCARE "Periodic care allowance (non means-tested)"
cap label var STACPCARE "Periodic care allowance (means-tested)"
cap label var STTCPECOHAND "Periodic economic integration of the handicapped"
cap label var SNTCPECOHAND "Periodic economic integration of the handicapped (non means-tested)"
cap label var STACPECOHAND "Periodic economic integration of the handicapped (means-tested)"
cap label var STTCPSURVPEN "Survivors pension"
cap label var SNTCPSURVPEN "Survivors pension (non means-tested)"
cap label var STACPSURVPEN "Survivors pension (means-tested)"
cap label var STTCPCHILD "Income maintenance benefit in the event of childbirth"
cap label var SNTCPCHILD "Income maintenance benefit in the event of childbirth (non means-tested)"
cap label var STACPCHILD "Income maintenance benefit in the event of childbirth (means-tested)"
cap label var STTCPPARENT "Periodic parental leave benefit"
cap label var SNTCPPARENT "Parental leave benefit periodic (non means-tested)"
cap label var STACPPARENT "Parental leave benefit periodic (means-tested)"
cap label var STTCPALLOW "Family or child allowance"
cap label var SNTCPALLOW "Family or child allowance (non means-tested)"
cap label var STACPALLOW "Family or child allowance (means-tested)"
cap label var STTCPFULLUNEMP "Full unemployment benefits"
cap label var SNTCPFULLUNEMP "Full unemployment benefits (non means-tested)"
cap label var STACPFULLUNEMP "Full unemployment benefits (means-tested)"
cap label var STTCPPARTUNEMP "Partial unemployment"
cap label var SNTCPPARTUNEMP "Partial unemployment. (non means-tested)"
cap label var STACPPARTUNEMP "Partial unemployment (means-tested)"
cap label var STTCPEARLYMARK "Early retirement benefit for labour market reasons"
cap label var SNTCPEARLYMARK "Early retirement benefit for labour market reasons (non means-tested)"
cap label var STACPEARLYMARK "Early retirement benefit for labour market reasons (means-tested)"
cap label var STTCPVOCAT "Periodic benefit vocational training"
cap label var SNTCPVOCAT "Periodic benefit vocational training (non means-tested)"
cap label var STACPVOCAT "Periodic benefit vocational training (means-tested)"
cap label var STTCPINCSUP "Income support"
cap label var SNTCPINCSUP "Income support (non means-tested)"
cap label var STACPINCSUP "Income support (means-tested)"
cap label var STTCP_OTH "Other periodic cash benefits"
cap label var SNTCP_OTH "Other periodic cash benefits (non means-tested)"
cap label var STACP_OTH "Other periodic cash benefits (means-tested)"
cap label var STTCLUMP "Lump sum cash benefits"
cap label var SNTCLUMP "Lump sum cash benefits (non means-tested)"
cap label var STACLUMP "Lump sum cash benefits (means-tested)"
cap label var STTCLCARE "Lump sum care allowance"
cap label var SNTCLCARE "Lump sum care allowance (non means-tested)"
cap label var STACLCARE "Lump sum care allowance (means-tested)"
cap label var STTCLECOHAND "Lump sum economic integration of the handicapped"
cap label var SNTCLECOHAND "Lump sum economic integration of the handicapped (non means-tested)"
cap label var STACLECOHAND "Lump sum economic integration of the handicapped (means-tested)"
cap label var STTCLDEATH "Death grant"
cap label var SNTCLDEATH "Death grant (non means-tested)"
cap label var STACLDEATH "Death grant (means-tested)"
cap label var STTCLBIRTH "Birth grant"
cap label var SNTCLBIRTH "Birth grant (non means-tested)"
cap label var STACLBIRTH "Birth grant (means-tested)"
cap label var STTCLPARENT "Parental leave benefits lump sum"
cap label var SNTCLPARENT "Parental leave benefits lump sum (non means-tested)"
cap label var STACLPARENT "Parental leave benefits lump sum (means-tested)"
cap label var STTCLVOCAT "Lump sum benefit vocational training"
cap label var SNTCLVOCAT "Lump sum benefit vocational training (non means-tested)"
cap label var STACLVOCAT "Lump sum benefit vocational training (means-tested)"
cap label var STTCLRED "Lump sum benefit redundancy compensation"
cap label var SNTCLRED "Lump sum benefit redundancy compensation (non means-tested)"
cap label var STACLRED "Lump sum benefit redundancy compensation (means-tested)"
cap label var STTCL_OTH "Other lump sum cash benefits"
cap label var SNTCL_OTH "Other lump sum cash benefits (non means-tested)"
cap label var STACL_OTH "Other lump sum cash benefits (means-tested)"
cap label var STTKIND "Benefits in kind"
cap label var SNTKIND "Benefits in kind (non means-tested)"
cap label var STAKIND "Benefits in kind (means-tested)"
cap label var STTKINCARE "In-patient care"
cap label var SNTKINCARE "In-patient care (non means-tested)"
cap label var STAKINCARE "In-patient care (means-tested)"
cap label var STTKIDIRECT "In-patient care direct provision"
cap label var SNTKIDIRECT "In-patient care direct provision (non means-tested)"
cap label var STAKIDIRECT "In-patient care direct provision (means-tested)"
cap label var STTKIREMB "In-patient care reimbursment"
cap label var SNTKIREMB "In-patient care remboursment (non means-tested)"
cap label var STAKIREMB "In-patient care remboursment (means-tested)"
cap label var STTKOUTCARE "Out-patient care"
cap label var SNTKOUTCARE "Out-patient care (non means-tested)"
cap label var STAKOUTCARE "Out-patient care (means-tested)"
cap label var STTKODIR_PHAR "Out-patient care direct provision of pharmaceutical products"
cap label var SNTKODIR_PHAR "Out-patient care direct provision of pharmaceitical products (non means-tested)"
cap label var STAKODIR_PHAR "Out-patient care direct provision of pharm. products (means-tested)"
cap label var STTKODIR_OTH "Out-patient care other direct provision"
cap label var SNTKODIR_OTH "Out-patient care other direct provision (non means-tested)"
cap label var STAKODIR_OTH "Out-patient care other direct provision (means-tested)"
cap label var STTKOREMB_PHAR "Out-patient care reimbursment of pharmaceutical products"
cap label var SNTKOREMB_PHAR "Out-patient care rembursment of pharmaceutical products (non means-tested)"
cap label var STAKOREMB_PHAR "Out-patient care rembursment of pharmaceutical products (means-tested)"
cap label var STTKOREMB_OTH "Out-patient care other reimbursment"
cap label var SNTKOREMB_OTH "Out-patient care other rembursment (non means-tested)"
cap label var STAKOREMB_OTH "Out-patient care other rembursment (means-tested)"
cap label var STTKCHILD "Child day care"
cap label var SNTKCHILD "Child day care (non means-tested)"
cap label var STAKCHILD "Child day care (means-tested)"
cap label var STTKACCOMOD "Accomodation"
cap label var SNTKACCOMOD "Accommodation (non means-tested)"
cap label var STAKACCOMOD "Accommodation (means-tested)"
cap label var STTKASSIST "Assistance in carrying daily tasks"
cap label var SNTKASSIST "Assistance in carrying daily tasks (non means-tested)"
cap label var STAKASSIST "Assistance in carrying daily tasks (means-tested)"
cap label var STTKREHAB "Rehabilitation"
cap label var SNTKREHAB "Rehabilitation (non means-tested)"
cap label var STAKREHAB "Rehabilitation (means-tested)"
cap label var STTKFUNERAL "Funeral expenses"
cap label var SNTKFUNERAL "Funeral expenses (non means-tested)"
cap label var STAKFUNERAL "Funeral expenses (means-tested)"
cap label var STTKHOME "Home help"
cap label var SNTKHOME "Home help (non means-tested)"
cap label var STAKHOME "Home help (means-tested)"
cap label var STTKMOBIL "Mobility and resettlement benefits"
cap label var SNTKMOBIL "Mobility and resettlement benefits (non means-tested)"
cap label var STAKMOBIL "Mobility and resettlement benefits (means-tested)"
cap label var STTKVOCAT "Vocational training"
cap label var SNTKVOCAT "Vocational training (non means-tested)"
cap label var STAKVOCAT "Vocational training (means-tested)"
cap label var STTKPLACEMENT "Placement services and job search assistance"
cap label var SNTKPLACEMENT "Placement services and job search assistance (non means-tested)"
cap label var STAKPLACEMENT "Placement services and job search assistance (means-tested)"
cap label var STAKRENT "Rent benefits (means-tested)"
cap label var STAKRHOUSE "Social housing (means-tested)"
cap label var STAKR_OTH "Other rent benefits (means-tested)"
cap label var STAKOWNER "Benefits to owner-occupiers (means-tested)"
cap label var STTKDRUGS "Rehabilitation of alcohol and drugs abusers"
cap label var SNTKDRUGS "Rehabilitation of alcohol and drugs abusers (non means-tested)"
cap label var STAKDRUGS "Rehabilitation of alcohol and drugs abusers (means-tested)"
cap label var STTK_OTH "Other benefits in kind"
cap label var SNTK_OTH "Other benefits in kind (non means-tested)"
cap label var STAK_OTH "Other benefits in kind (means-tested)"
