cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var EU "EU framework"
cap label var UR "Union Resettlement"
cap label var UHA "Union Humanitarian admission"
cap label var JHAC15 "Agreement in Justice and Home Affairs (JHA) Council on 20.07.2015"
cap label var DIR_2011_95 "Directive 2011/95/EU, article 23 on maintaining family unity"
cap label var DIR_2003_86 "Directive 2003/86/EC on the right to family reunification"
cap label var REGL_2013_1305 "Regulation (EU) No 1305/2013, article 32 on areas facing natural constraints"
cap label var NAT "National framework"
cap label var NATR "National Resettlement"
cap label var NATHA "National Humanitarian admission"
cap label var OTH "Other"
cap label var UNK "Unknown"
