cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var SAV "Saving households"
cap label var NSAV "Dissaving households"
cap label var ASD_M "Households putting money aside"
cap label var DRW_S "Households needing to draw on savings"
cap label var BRW_M "Households needing to borrow money"
cap label var NASD_NBRW_M_NDRW_S "Households neither putting money aside nor needing to draw on savings or borrow"
cap label var DRW_S_BRW_M "Households needing to draw on savings or to borrow money"
cap label var NDRW_S_NBRW_M "Households not needing to draw on savings or to borrow money"
cap label var UNK "Unknown"
