cap label var CODE "Label - English"
cap label var TOTAL "Total area"
cap label var LAND "Land area"
cap label var U100 "Primary sector"
cap label var U110 "Agriculture"
cap label var U111 "Agriculture (excluding fallow land and kitchen gardens)"
cap label var U112 "Fallow land"
cap label var U113 "Kitchen gardens"
cap label var U120 "Forestry"
cap label var U130 "Fishing and aquaculture"
cap label var HENVI "Land use with heavy environmental impact"
cap label var U140 "Mining and quarrying"
cap label var U150 "Other primary sector activities"
cap label var U200 "Secondary sector"
cap label var U210 "Energy production"
cap label var U220 "Industry and manufacturing"
cap label var U221 "Manufacturing of food products, beverages and tobacco products"
cap label var U222 "Manufacturing of textile products"
cap label var U223 "Coal, crude petroleum and metal processing"
cap label var U224 "Production of other non-metal mineral products"
cap label var U225 "Chemical and allied industries"
cap label var U226 "Manufacturing of machinery and equipment"
cap label var U227 "Manufacturing of wood based products and related activities"
cap label var U228 "Printing and reproduction"
cap label var U300 "Tertiary sector, transports, utilities and residential areas"
cap label var U310 "Transport, telecommunication, energy distribution, storage, protective works"
cap label var U311 "Railway transport"
cap label var U312 "Road transport"
cap label var U313 "Water transport"
cap label var U314 "Air transport"
cap label var U315 "Transport via pipelines"
cap label var U316 "Telecommunication"
cap label var U317 "Logistics and storage"
cap label var U318 "Protection infrastructure"
cap label var U319 "Electricity, gas and thermal power distribution"
cap label var U320 "Water and waste treatment"
cap label var U321 "Water supply and treatment"
cap label var U322 "Waste treatment"
cap label var U330 "Construction"
cap label var U340_370 "Services and residential area"
cap label var U340 "Commercial, financial, professional and information services"
cap label var U341 "Commerce"
cap label var U342 "Financial, professional and information services"
cap label var U350 "Community services"
cap label var U360 "Arts, entertainement and recreation"
cap label var U361 "Arts and entertainement"
cap label var U362 "Sports"
cap label var U370 "Residential area"
cap label var U400 "Unused and abandoned areas"
cap label var U410 "Abandoned areas"
cap label var U411 "Abandoned industrial area"
cap label var U412 "Abandoned commercial area"
cap label var U413 "Abandoned transport area"
cap label var U414 "Abandoned residential area"
cap label var U415 "Other abandoned areas"
cap label var U420 "Semi-natural and natural areas not in use"
cap label var L0008 "Land area - total"
cap label var LU "Total land use"
cap label var LUA "Agriculture"
cap label var LUB "Forestry"
cap label var LUC "Fishing and aquaculture"
cap label var LUD "Land use with heavy environmental impact"
cap label var LUE "Services and residential area"
cap label var LUF "Unused and abandoned areas"
cap label var LUG "Other primary sector activities"
cap label var LUD1 "Mining and quarrying"
cap label var LUD2 "Energy production"
cap label var LUD3 "Industry and manufacturing"
cap label var LUD4 "Water and waste treatment"
cap label var LUD5 "Construction"
cap label var LUD6 "Transport, telecommunication, energy distribution, storage, protective works"
cap label var LUE1 "Commercial, financial, professional and information services"
cap label var LUE2 "Community services"
cap label var LUE3 "Arts, entertainement and recreation"
cap label var LUE4 "Residential area"
cap label var LUE5 "Nature reserves"
