cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var A "Agriculture, forestry and fishing"
cap label var A01 "Crop and animal production, hunting and related service activities"
cap label var A02 "Forestry and logging"
cap label var A03 "Fishing and aquaculture"
cap label var B_E "Industry (except construction)"
cap label var B "Mining and quarrying"
cap label var B05 "Mining of coal and lignite"
cap label var B06 "Extraction of crude petroleum and natural gas"
cap label var B07 "Mining of metal ores"
cap label var B08 "Other mining and quarrying"
cap label var B09 "Mining support servic activities"
cap label var C "Manufacturing"
cap label var C10_12 "Manufacture of food products; beverages and tobacco products"
cap label var C10 "Manufacture of food products"
cap label var C11 "Manufacture of beverages"
cap label var C12 "Manufacture of tobacco products"
cap label var C13_15 "Manufacture of textiles, wearing apparel, leather and related products"
cap label var C13 "Manufacture of textiles"
cap label var C14 "Manufacture of wearing apparel"
cap label var C15 "Manufacutre of leather and related products"
cap label var C16_18 "Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials; paper and paper products; printing and reproduction of recorded media"
cap label var C16 "Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials"
cap label var C17 "Manufacture of paper and paper products"
cap label var C18 "Printing and reproduction of recorded media"
cap label var C19 "Manufacture of coke and refined petroleum products"
cap label var C20_21 "Manufacture of chemicals and basic pharmaceutical products"
cap label var C20 "Manufacture of chemicals and chemical products"
cap label var C21 "Manufacture of basic pharmaceutical products and pharmaceutical preparations"
cap label var C22_23 "Manufacture of rubber and plastic products; other non-metallic mineral products"
cap label var C22 "Manufacture of rubber and plastic products"
cap label var C23 "Manufacture of other non-metallic mineral products"
cap label var C24_25 "Manufacture of basic metals; fabricated metal products, except machinery and equipment"
cap label var C24 "Manufacture of basic metals"
cap label var C25 "Manufacture of fabricated metal products, except machinery and equipment"
cap label var C26 "Manufacture of computer, electronic and optical products"
cap label var C27 "Manufacture of electrical equipment"
cap label var C28 "Manufacture of machinery and equipment n.e.c."
cap label var C29_30 "Manufacture of motor vehicles, trailers and semi-trailers; other transport equipment"
cap label var C29 "Manufacture of motor vehicles, trailers and semi-trailers"
cap label var C30 "Manufacture of other transport equipment"
cap label var C31_33 "Manufacture of furniture, other manufactured goods, repair and installation services of machinery and equipment"
cap label var C31_32 "Manufacture of furniture; other manufacturing"
cap label var C31 "Manufacture of furniture"
cap label var C32 "Other manufacturing"
cap label var C33 "Repair and installation of machinery and equipment"
cap label var D_E "Electricity, gas, steam and air conditioning supply; water supply; sewerage, waste management and remediation services"
cap label var D "Electricity, gas, steam and air conditioning supply"
cap label var D35 "Electricity, gas, steam and air conditioning supply"
cap label var E "Water supply; sewerage, waste management and remediation services"
cap label var E36 "Water collection, treatment and supply"
cap label var E37_39 "Sewerage, waste management, remediation activities"
cap label var E37 "Sewerage"
cap label var E38 "Waste collection, treatment and disposal activities; materials recovery"
cap label var E39 "Remediation activities and other waste management services"
cap label var F "Construction"
cap label var F41 "Construction of buildings"
cap label var F42 "Civil engineering"
cap label var F43 "Specialised construction activities"
cap label var G_I "Wholesale and retail trade, transport, accomodation and food service activities"
cap label var G "Wholesale and retail trade services; repair services of motor vehicles and motorcycles"
cap label var G45 "Wholesale and retail trade and repair of motor vehicles and motorcycles"
cap label var G46 "Wholesale trade, except of motor vehicles and motorcycles"
cap label var G47 "Retail trade, except of motor vehicles and motorcycles"
cap label var H "Transportation and storage services"
cap label var H49 "Land transport and transport via pipelines"
cap label var H50 "Water transport"
cap label var H51 "Air transport"
cap label var H52 "Warehousing and support activities for transportation"
cap label var H53 "Postal and courier activities"
cap label var I "Accommodation and food service activities"
cap label var I55 "Accommodation"
cap label var I56 "Food and beverage service activities"
cap label var J "Information and communication"
cap label var J58_60 "Publishing activities; motion picture, video, television programme production; programming and broadcasting activities"
cap label var J58 "Publishing activities"
cap label var J59_60 "Motion picture, video, television programme production; programming and broadcasting activities"
cap label var J59 "Motion picture, video, television programme production, sound recording and music publishing activities"
cap label var J60 "Programming and broadcasting activities"
cap label var J61 "Telecommunications"
cap label var J62_63 "Computer programming, consultancy, and information service activities"
cap label var J62 "Computer programming, consultancy and related activities"
cap label var J63 "Information service activities"
cap label var K "Financial and insurance activities"
cap label var K64 "Financial service activities, except insurance and pension funding"
cap label var K65 "Insurance, reinsurance and pension funding, except compulsory social security"
cap label var K66 "Activities auxiliary to financial services and insurance activities"
cap label var L "Real estate activities"
cap label var L68 "Real estate activities"
cap label var L68A "Imputed rents of owner-occupied dwellings"
cap label var L68B "Real estate activities excluding imputed rents"
cap label var M_N "Professional, scientific and technical activities; administrative and support service activities"
cap label var M "Professional, scientific and technical services"
cap label var M69_70 "Legal and accounting activities; activities of head offices; management consultancy activities"
cap label var M69 "Legal and accounting activities"
cap label var M70 "Activities of head offices; management consultancy activities"
cap label var M71 "Architectural and engineering activities; technical testing and analysis"
cap label var M72 "Scientific research and development"
cap label var M73 "Advertising and market research"
cap label var M74_75 "Other professional, scientific and technical activities; veterinary activities"
cap label var M74 "Other professional, scientific and technical activities"
cap label var M75 "Veterinary activities"
cap label var N "Administrative and support services"
cap label var N77 "Rental and leasing activities"
cap label var N78 "Employment activities"
cap label var N79 "Travel agency, tour operator reservation service and related activities"
cap label var N80_82 "Security and investigation, service and landscape, office administrative and support activities"
cap label var N80 "Security and investigation activities"
cap label var N81 "Services to buildings and landscape activities"
cap label var N82 "Office administrative, office support and other business support activities"
cap label var O_Q "Public administration, defence, education, human health and social work services"
cap label var O "Public administration and defence; compulsory social security"
cap label var O84 "Public administration and defence; compulsory social security"
cap label var P "Education"
cap label var P85 "Education"
cap label var Q "Human health and social work services"
cap label var Q86 "Human health activities"
cap label var Q87_88 "Residential care activities and social work activities without accommodation"
cap label var Q87 "Residential care activities"
cap label var Q88 "Social work activities without accommodation"
cap label var R_U "Arts, entertainment and recreation; other service activities; activities of household and extra-territorial organizations and bodies"
cap label var R "Entertainement, recreations services"
cap label var R90 "Creative, arts and entertainment activities"
cap label var R91 "Libraries, archives, museums and other cultural activities"
cap label var R92 "Gambling and betting activities"
cap label var R_S "Arts, entertainment and recreation; other service activities"
cap label var R90_92 "Creative, arts and entertainment activities; libraries, archives, museums and other cultural activities; gambling and betting activities"
cap label var R93 "Sports activities and amusement and recreation activities"
cap label var S "Other services"
cap label var S94 "Activities of membership organisations"
cap label var S95 "Repair of computers and personal and household goods"
cap label var S96 "Other personal service activities"
cap label var T_U "Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use; activities of extraterritorial organisations and bodies"
cap label var T "Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use"
cap label var T97 "Activities of households as employers of domestic personnel"
cap label var T98 "Undifferentiated goods-and-services-producing activities of private households for own use"
cap label var U "Activities of extraterritorial organisations and bodies"
cap label var TOT_X_A02 "All NACE activities except forestry and logging"
cap label var D21X31 "Taxes less subsidies on products"
cap label var P7 "Imports of goods and services"
cap label var P7_B0 "Imports from EU member states"
cap label var P7_D0 "Imports from non-members of the EU"
cap label var P7_U2 "Imports from members of the euro area"
cap label var P7_U3 "Imports from non-members of the euro area"
cap label var TS "Total supply"
cap label var TS_PP "Total supply at purchasers' prices"
cap label var TS_BP "Total supply at basic prices"
cap label var OTTM "Trade and transport margins"
