cap label var CODE "Label - English"
cap label var WA_1 "Total gross abstraction"
cap label var WA_1_1 "Abstraction by public water supply"
cap label var W18_1 "Population connected to public water supply (% of national population) - (only available for public water supply)"
cap label var W18_2 "Total supply"
cap label var W18_2_1 "Supply to agriculture, forestry, fishing (total)"
cap label var W18_2_1_1 "Supply to agriculture, for irrigation purposes"
cap label var W18_2_3 "Supply to manufacturing industries (total)"
cap label var W18_2_4 "Supply to the production and distribution of electricity (total)"
cap label var W18_2_7_2 "Supply to the domestic sector, households"
cap label var WW2_1 "Primary treatment"
cap label var WW2_5 "Secondary and tertiary treatment"
