cap label var TOTAL "Total"
cap label var IMG "Native and foreign born immigrants (first and second generation of immigrants)"
cap label var NBO_FBO_NAT_ABR_A1 "At least one adult native-born with both parents native-born and at least one adult foreign-born or native-born with one or both parents born abroad"
cap label var FBO_NBO_ABR "Foreign-born or native-born with one or both parents born abroad (first and second generations)"
cap label var FBO_NBO_ABR_A1 "At least one adult foreign-born and at least one adult native-born with one or both parents born abroad (first and second generation only)"
cap label var NBO "Native-born"
cap label var NBO_NAT_IMG "Native born with native background and native and foreign born immigrants (first and second generation of immigrants)"
cap label var NBO_NAT "Native-born with both parents native-born"
cap label var NBO_NAT_A "Adults native-born with both parents native-born"
cap label var NBO_IMG "Native-born with mixed background and foreign background (second generation of immigrants)"
cap label var NBO_ABR "Native-born with one or both parents born abroad (second generation)"
cap label var NBO_ABR_A "Adults native-born with one or both parents born abroad (second generation)"
cap label var NBO_IMGMIX "Native-born with mixed background (second generation of immigrants)"
cap label var NBO_ABR_PAR1 "Native-born with one parent born abroad (second generation)"
cap label var NBO_IMGFOR "Native-born with foreign background (second generation of immigrants)"
cap label var NBO_ABR_PAR2 "Native-born with both parents born abroad (second generation)"
cap label var FBO "Foreign-born (first generation)"
cap label var FBO_A "Adults foreign-born (first generation)"
cap label var FBO_ABR_A "Adults foreign-born or with one or both parents born abroad"
cap label var NRP "No response"
cap label var OTH "Other"
cap label var UNK "Unknown"
