cap label var CODE "Label - English"
cap label var ENT "Enterprise"
cap label var PRD "Production"
cap label var PRD_BP "Production value at basic price"
cap label var PRD_PP "Production value at producer price"
cap label var SUB "Subsidies on products"
cap label var TAX "Taxes on products"
cap label var FARM_NR "Farm - number"
cap label var UAA_HA "Utilised agricultural area - hectare"
cap label var FA_HA "Farm area - hectare"
cap label var FAXSAA_HA "Farm area excluding special agricultural production areas - hectare"
cap label var FARM_NR_LS "Farms with livestock - number"
cap label var FARM_LSU_LS "Farms with livestock - live stock unit"
cap label var SO_EUR "Standard output - euro"
cap label var LF_D_AWU "Labour force directly employed - annual working unit"
cap label var FARM_NR_PD_GT50 "Farms whose household consumes more than 50% of the final production - number"
cap label var TENURE_SHR "Share of tenure type"
cap label var SX_HLD_SHR "Share of sex of holder"
cap label var IND_A "Indicator A - index of the real income of factors in agriculture per annual work unit"
cap label var IND_B "Indicator B - index of real net agricultural entrepreneurial income, per unpaid annual work unit"
cap label var IND_C "Indicator C - net entrepreneurial income of agriculture"
cap label var RFI_AWU_CLV "Real factor income in agriculture per annual work unit (chain linked volumes)"
cap label var HRI1 "Harmonised risk indicator 1"
cap label var HRI2 "Harmonised risk indicator 2"
cap label var I_NUT "Nutrient inputs"
cap label var I_FER "Total consumption of fertilisers (except manure)"
cap label var I_FER_MIN "Consumption of mineral fertilisers"
cap label var I_FER_ORG "Consumption of organic fertilisers (except manure)"
cap label var I_FER_ORG_SS "Consumption of organic fertilisers (except manure) - sewage sludge"
cap label var I_FER_ORG_UC "Consumption of organic fertilisers (except manure) - urban compost"
cap label var I_FER_ORG_IW "Consumption of organic fertilisers (except manure) - industrial waste products"
cap label var I_FER_ORG_OTH "Consumption of organic fertilisers (except manure) - other products"
cap label var I_MNR "Manure input"
cap label var I_MNR_IMP_LQ_SL "Import of liquid manure/slurry from the farm"
cap label var I_MNR_IMP_SO "Import of solid manure from the farm"
cap label var I_MNR_WDR "Manure withdrawals"
cap label var I_MNR_WDR_NAU "Manure withdrawals - non-agricultural use"
cap label var I_MNR_WDR_IW "Manure withdrawals - processed as industrial waste"
cap label var I_MNR_WDR_ELM "Manure withdrawals - exported livestock manure"
cap label var I_MNR_WDR_OTH "Manure withdrawals - other"
cap label var I_MNR_IMP "Manure imports"
cap label var I_NUT_OTH "Other nutrient inputs"
cap label var I_NUT_OTH_BFN "Other nutrient inputs - biological fixation of nitrogen"
cap label var I_NUT_OTH_AD "Other nutrient inputs - atmospheric deposition"
cap label var I_NUT_OTH_SPM "Other nutrient inputs - seeds and planting material"
cap label var O_NUT "Nutrient outputs"
cap label var O_HVT_CF "Nutrient removal by harvest of crops and forage"
cap label var O_RES_RMOV "Nutrient removal by crop residues removed from the field"
cap label var O_RES_RMOV_HLS "Nutrient removal by crop residues removed from the field - head leaves and stems"
cap label var O_RES_RMOV_STW "Nutrient removal by crop residues removed from the field - straw"
cap label var O_RES_RMOV_OTH "Nutrient removal by crop residues removed from the field - other"
cap label var O_RES_BRN "Nutrient removal by crop residues burned on the field"
cap label var MNR_EXP_LQ_SL "Export of liquid manure / slurry from the farm"
cap label var MNR_EXP_SO "Export of solid manure from the farm"
cap label var I_IFA "Inorganic fertilisers for agriculture"
cap label var I_IFA_USF "Inorganic fertilisers for agriculture - urea straight fertilisers"
cap label var I_OFA_SS "Organic fertilisers for agriculture - sewage sludge"
cap label var I_OFA_OTH "Organic fertilisers for agriculture - other"
cap label var I_OMFA "Organo-mineral fertilisers for agriculture"
cap label var O_CF "Crop and forage"
cap label var O_CR "Crop residues (removed from the field)"
cap label var O_CR_HLS "Crop residues (removed from the field) - head leaves and stems"
cap label var O_CR_STW "Crop residues (removed from the field) - straw"
cap label var O_CR_OTH "Crop residues (removed from the field) - other"
cap label var I_BF "Biological fixation"
cap label var I_AD "Atmospheric deposition"
cap label var I_SD "Seeds"
cap label var I_LE "Livestock excretion"
cap label var O_LMW "Livestock manure withdrawals"
cap label var O_LMW_ELM "Livestock manure withdrawals - exported livestock manure"
cap label var O_LMW_OTH "Livestock manure withdrawals - other manure withdrawals"
cap label var I_OLMI "Other livestock manure inputs"
cap label var I_OLMI_ILM "Other livestock manure inputs - imported livestock manure"
cap label var I_OLMI_OTH "Other livestock manure inputs - other manure inputs"
