cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var OLD_SRV "Old age and survivors' pension"
cap label var OLD_TOT "Total old age pensions"
cap label var OLD "Old age pension"
cap label var OLD_ONL "Old-age pension only"
cap label var OLD_S "Statutory old-age pension"
cap label var OLD_S_ONL "Statutory old-age pension only"
cap label var OLD_S_OCC_PER "Statutory old-age pension and occupational and/or personal pension"
cap label var OLD_S_RED_APEN "Statutory old-age pension with reduction due to anticipated pension benefit"
cap label var OLD_S_BNS_RET_DEF "Statutory old-age pension with bonus due to retirement deferment"
cap label var OLD_S_NRED_NBNS "Statutory old-age pension without reduction or bonus"
cap label var OCC_PER_ONL "Occupational and/or personal pension only"
cap label var AOLD "Anticipated old age pension"
cap label var PART "Partial pension"
cap label var DIS_TOT "Total disability pensions"
cap label var DIS "Disability pension"
cap label var DIS_P_DIS_OTH_ONL "Disability pension or other periodic disability benefits only"
cap label var OLD_DIS_P_DIS_OTH "Old-age and disability pension or other periodic disability benefits"
cap label var SRV "Survivors' pension"
cap label var ERRC "Early retirement benefit due to reduced capacity to work"
cap label var ERLM "Early retirement benefit for labour market reasons"
cap label var ANY "Any pension"
cap label var NONE "None"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var SCPOLDSURV "Old age plus survivors pensions"
cap label var SCPTOTOLDAGE "Total old age pensions"
cap label var SCPOLDPEN "Old age pension"
cap label var SCPANTPEN "Anticipated old age pension"
cap label var SCPPARPEN "Partial pension"
cap label var SCPTOTDISAB "Total disability pensions"
cap label var SCPDISPEN "Disability pension"
cap label var SCPEARLYRED "Early retirement benefit due to reduced capacity to work"
cap label var SCPSURVPEN "Survivors pension"
cap label var SCPEARLYMARK "Early retirement benefit for labour market reasons"
