cap label var CODE "Label - English"
cap label var _4141050 "Households - D1 (annual consumption: 8.37 GJ)"
cap label var _4141100 "Households - D2 (annual consumption: 16.74 GJ)"
cap label var _4141150 "Households - D3 (annual consumption: 83.70 GJ)"
cap label var _4141200 "Households - D3-b (annual consumption: 125.60 GJ)"
cap label var _4141250 "Households - D4 (annual consumption: 1 047 GJ)"
cap label var _4141300 "Households - D2-b (UK only) (annual consumption: 33.49 GJ)"
cap label var _4142050 "Industry - I1 (annual consumption: 418.6 GJ; no load factor) (for Belgium: fixed supply (non-erasable) for non-specific applications that can easily be substituted by residual fuel oils (CNE 1 P 1))"
cap label var _4142100 "Industry - I2 (annual consumption: 4 186 GJ; load factor: 200 days) (for Belgium: fixed supply (non-erasable) for non-specific applications that can easily be substituted by residual fuel oils (CNE 1 P 1))"
cap label var _4142150 "Industry - I3-1 (annual consumption: 41 860 GJ; load factor: 200 days, 1 600 hours) (for Belgium: fixed supply (non-erasable) for non-specific applications that can easily be substituted by residual fuel oils (CNE 1 P 1))"
cap label var _4142200 "Industry - I3-2 (annual consumption: 41 860 GJ; load factor: 250 days, 4 000 hours) (for Belgium: fixed supply (non-erasable) for non-specific applications that can easily be substituted by residual fuel oils (CNE 1 P 1))"
cap label var _4142250 "Industry - I4-1(annual consumption: 418 600 GJ; load factor: 250 days, 4 000 hours) (for Belgium: fixed supply (non-erasable) for non-specific applications that can easily be substituted by residual fuel oils (CNE 1 P 1))"
cap label var _4142300 "Industry - I4-2 (annual consumption: 418 600 GJ; load factor: 330 days, 8 000 hours) (for Belgium: fixed supply (non-erasable) for non-specific applications that can easily be substituted by residual fuel oils (CNE 1 P 1))"
cap label var _4142350 "Industry - I5 (annual consumption: 4 186 000 GJ; load factor: 330 days, 8 000 hours) (for Belgium: fixed supply (non-erasable) for non-specific applications that can easily be substituted by residual fuel oils (CNE 1 P 1))"
cap label var _4161050 "Households - Da (annual consumption: 600 kWh)"
cap label var _4161100 "Households - Db (annual consumption: 1 200 kWh)"
cap label var _4161150 "Households - Dc (annual consumption: 3 500 kWh of which night 1 300)"
cap label var _4161200 "Households - Dd (annual consumption :7 500 kWh of which night 2 500)"
cap label var _4161250 "Households - De (annual consumption: 20 000 kWh of which night 15 000)"
cap label var _4162050 "Industry - Ia (annual consumption: 30 MWh; maximum demand: 30 kW; annual load: 1 000 hours) (for Luxembourg: 50% power reduction during hours of heavy loading)"
cap label var _4162100 "Industry - Ib (annual consumption: 50 MWh; maximum demand: 50 kW; annual load: 1 000 hours) (for Luxembourg: 50% power reduction during hours of heavy loading)"
cap label var _4162150 "Industry - Ic (annual consumption: 160 MWh; maximum demand: 100 kW; annual load: 1 600 hours) (for Luxembourg: 50% power reduction during hours of heavy loading)"
cap label var _4162200 "Industry - Id (annual consumption: 1 250 MWh; maximum demand: 500 kW; annual load: 2 500 hours) (for Luxembourg: 50% power reduction during hours of heavy loading)"
cap label var _4162250 "Industry - Ie (annual consumption: 2 000 MWh; maximum demand: 500 kW; annual load: 4 000 hours) (for Luxembourg: 50% power reduction during hours of heavy loading)"
cap label var _4162300 "Industry - If (annual consumption: 10 000 MWh; maximum demand: 2 500 kW; annual load: 4 000 hours) (for Luxembourg: 50% power reduction during hours of heavy loading)"
cap label var _4162350 "Industry - Ig (annual consumption: 24 000 MWh; maximum demand: 4 000 kW; annual load: 6 000 hours) (for Luxembourg: 50% power reduction during hours of heavy loading)"
cap label var _4162400 "Industry - Ih (annual consumption: 50 000 MWh; maximum demand: 10 000 kW; annual load: 5 000 hours) (for Luxembourg: 50% power reduction during hours of heavy loading)"
cap label var _4162450 "Industry - Ii (annual consumption: 70 000 MWh; maximum demand: 10 000 kW; annual load: 7 000 hours) (for Luxembourg: 50% power reduction during hours of heavy loading)"
cap label var _4262600 "Industry 25 MW (covering maximum demands of between 17.5 and 37.5 MW)"
cap label var _4262610 "Industry 25 MW (lowest)"
cap label var _4262620 "Industry 25 MW (highest)"
cap label var _4262630 "Industry 25 MW base 5000 hours (France only)"
cap label var _4262700 "Industry 50 MW (covering maximun demands of between 37.5 and 62.5 MW)"
cap label var _4262710 "Industry 50 MW (lowest)"
cap label var _4262720 "Industry 50 MW (highest)"
cap label var _4262730 "Industry 50 MW base 5000 hours (France only)"
cap label var _4262800 "Industry 75 MW (covering maximun demands of between 62.5 and 75 MW)"
cap label var _4262810 "Industry 75 MW (lowest)"
cap label var _4262820 "Industry 75 MW (highest)"
cap label var _4262830 "Industry 75 MW base 5000 hours (France only)"
cap label var _4142051 "Industry - I1 (Belgium only: completely erasable supply for non-specific applications that can easily be substituted by residual fuel oils (CNE 0 P 0.9))"
cap label var _4142052 "Industry - I1 (Belgium only: 50% erasable supply for non-specific applications that can easily be substituted by residual fuel oils (CNE 0.5 P 1))"
cap label var _4142054 "Industry - I1 (Belgium only: fixed supply (non-erasable) for specific applications that can not easily be substituted by residual fuel oils (CNE 1 P1.1))"
cap label var _4142101 "Industry - I2 (Belgium only: completely erasable supply for non-specific applications that can easily be substituted by residual fuel oils (CNE 0 P 0.9))"
cap label var _4142102 "Industry - I2 (Belgium only: 50% erasable supply for non-specific applications that can easily be substituted by residual fuel oils (CNE 0.5 P 1))"
cap label var _4142104 "Industry - I2 (Belgium only: fixed supply (non-erasable) for specific applications that can not easily be substituted by residual fuel oils (CNE 1 P1.1))"
cap label var _4142151 "Industry - I3-1 (Belgium only: completely erasable supply for non-specific applications that can easily be substituted by residual fuel oils (CNE 0 P 0.9))"
cap label var _4142152 "Industry - I3-1 (Belgium only: 50% erasable supply for non-specific applications that can easily be substituted by residual fuel oils (CNE 0.5 P 1))"
cap label var _4142154 "Industry - I3-1 (Belgium only: fixed supply (non-erasable) for specific applications that can not easily be substituted by residual fuel oils (CNE 1 P1.1))"
cap label var _4142201 "Industry - I3-2 (Belgium only: completely erasable supply for non-specific applications that can easily be substituted by residual fuel oils (CNE 0 P 0.9))"
cap label var _4142202 "Industry - I3-2 (Belgium only: 50% erasable supply for non-specific applications that can easily be substituted by residual fuel oils (CNE 0.5 P 1))"
cap label var _4142204 "Industry - I3-2 (Belgium only: fixed supply (non-erasable) for specific applications that can not easily be substituted by residual fuel oils (CNE 1 P1.1))"
cap label var _4142251 "Industry - I4-1 (Belgium only: completely erasable supply for non-specific applications that can easily be substituted by residual fuel oils (CNE 0 P 0.9))"
cap label var _4142252 "Industry - I4-1 (Belgium only: 50% erasable supply for non-specific applications that can easily be substituted by residual fuel oils (CNE 0.5 P 1))"
cap label var _4142254 "Industry - I4-1 (Belgium only: fixed supply (non-erasable) for specific applications that can not easily be substituted by residual fuel oils (CNE 1 P1.1))"
cap label var _4142301 "Industry - I4-2 (Belgium only: completely erasable supply for non-specific applications that can easily be substituted by residual fuel oils (CNE 0 P 0.9))"
cap label var _4142302 "Industry - I4-2 (Belgium only: 50% erasable supply for non-specific applications that can easily be substituted by residual fuel oils (CNE 0.5 P 1))"
cap label var _4142304 "Industry - I4-2 (Belgium only: fixed supply (non-erasable) for specific applications that can not easily be substituted by residual fuel oils (CNE 1 P1.1))"
cap label var _4142351 "Industry - I5 (Belgium only: completely erasable supply for non-specific applications that can easily be substituted by residual fuel oils (CNE 0 P 0.9))"
cap label var _4142352 "Industry - I5 (Belgium only: 50% erasable supply for non-specific applications that can easily be substituted by residual fuel oils (CNE 0.5 P 1))"
cap label var _4142354 "Industry - I5 (Belgium only: fixed supply (non-erasable) for specific applications that can not easily be substituted by residual fuel oils (CNE 1 P1.1))"
cap label var _4162051 "Industry - Ia (Luxembourg only: 0% power reduction during hours of heavy loading)"
cap label var _4162053 "Industry - Ia (Luxembourg only: 100% power reduction during hours of heavy loading)"
cap label var _4162101 "Industry - Ib (Luxembourg only: 0% power reduction during hours of heavy loading)"
cap label var _4162103 "Industry - Ib (Luxembourg only: 100% power reduction during hours of heavy loading)"
cap label var _4162151 "Industry - Ic (Luxembourg only: 0% power reduction during hours of heavy loading)"
cap label var _4162153 "Industry - Ic (Luxembourg only: 100% power reduction during hours of heavy loading)"
cap label var _4162201 "Industry - Id (Luxembourg only: 0% power reduction during hours of heavy loading)"
cap label var _4162203 "Industry - Id (Luxembourg only: 100% power reduction during hours of heavy loading)"
cap label var _4162251 "Industry - Ie (Luxembourg only: 0% power reduction during hours of heavy loading)"
cap label var _4162253 "Industry - Ie (Luxembourg only: 100% power reduction during hours of heavy loading)"
cap label var _4162301 "Industry - If (Luxembourg only: 0% power reduction during hours of heavy loading)"
cap label var _4162303 "Industry - If (Luxembourg only: 100% power reduction during hours of heavy loading)"
cap label var _4162351 "Industry - Ig (Luxembourg only: 0% power reduction during hours of heavy loading)"
cap label var _4162353 "Industry - Ig (Luxembourg only: 100% power reduction during hours of heavy loading)"
cap label var _4162401 "Industry - Ih (Luxembourg only: 0% power reduction during hours of heavy loading)"
cap label var _4162403 "Industry - Ih (Luxembourg only: 100% power reduction during hours of heavy loading)"
cap label var _4162451 "Industry - Ii (Luxembourg only: 0% power reduction during hours of heavy loading)"
cap label var _4162453 "Industry - Ii (Luxembourg only: 100% power reduction during hours of heavy loading)"
cap label var _4262631 "Industry 25 MW base -6% (France only)"
cap label var _4262632 "Industry 25 MW base -8% (France only)"
cap label var _4262633 "Industry 25 MW base -10% (France only)"
cap label var _4262634 "Industry 25 MW reference (Portugal only)"
cap label var _4262731 "Industry 50 MW base -6% (France only)"
cap label var _4262732 "Industry 50 MW base -8% (France only)"
cap label var _4262733 "Industry 50 MW base -10% (France only)"
cap label var _4262734 "Industry 50 MW reference (Portugal only)"
cap label var _4262831 "Industry 75 MW base -6% (France only)"
cap label var _4262832 "Industry 75 MW base -8% (France only)"
cap label var _4262833 "Industry 75 MW base -10% (France only)"
