cap label var CODE "Label - English"
cap label var SET_PAC "Price set by platform, app or clients"
cap label var RNG_PAC "Range of price given by platform, app or clients"
cap label var NEGOT_PAC "Price negotiated with platform, app or clients"
cap label var SET_OSELF_OTH "Price set by oneself or other party"
