cap label var CODE "Label - English"
cap label var TOT_EGSS "Total environmental goods and services sector"
cap label var ANC "Ancillary activities"
cap label var MKT "Market activities"
cap label var ES_CS "Market activities - environmental specific and connected services"
cap label var ES_CP "Market activities - environmental specific and connected products"
cap label var C_REP "Market activities - cleaner and resource efficient products"
cap label var NMKT "Non-market activities"
cap label var OWN_USE "Own final use activities"
