cap label var CODE "Label - English"
cap label var SUG_SB_PC "Sugar content of sugar beet (%)"
cap label var AR "Area (cultivation/harvested/production) (1000 ha)"
cap label var PR "Harvested production (1000 t)"
cap label var PR_HU_EU "Harvested production in EU standard humidity (1000 t)"
cap label var YI "Yield (tonne/ha)"
cap label var YI_HU_EU "Yield in EU standard humidity (tonne/ha)"
cap label var HOL "Number of holders (1000)"
cap label var ANI "Number of animals (1000)"
cap label var MA "Main area (1000 ha)"
cap label var HU "Humidity (%)"
cap label var HU_EU "EU standard humidity (%)"
