cap label var CODE "Label - English"
cap label var TOTAL "All sectors"
cap label var DOM "Domestic"
cap label var BES "Business enterprise sector"
cap label var BES_IN "Business enterprises within the enterprise group"
cap label var BES_DOM "Domestic business enterprise sector"
cap label var BES_UNAF "Business enterprise sector - unaffiliated enterprises"
cap label var GOV "Government sector"
cap label var GOV_GUF "Government - general university funds"
cap label var GOV_DIR "Government - direct government"
cap label var DOM_X_GOV "Funds from domestic sources other than government"
cap label var HES "Higher education sector"
cap label var PNP "Private non-profit sector"
cap label var ROW "Rest of the world"
cap label var ROW_BES "Rest of the world - business enterprise sector"
cap label var ROW_BES_IN "Rest of the world - business enterprises within the enterprise group"
cap label var ROW_BES_UNAF "Rest of the world - business enterprise sector - unaffiliated enterprises"
cap label var ROW_BES_OTH "Rest of the world - other business enterprise companies"
cap label var ROW_GOV "Rest of the world - government sector"
cap label var ROW_HES "Rest of the world - higher education sector"
cap label var ROW_HES_FOR "Rest of the world - higher education sector - foreign branch campuses"
cap label var ROW_HES_O "Rest of the world - higher education sector - other higher education institutions"
cap label var ROW_PNP "Rest of the world - private non-profit sector"
cap label var ROW_EC "Rest of the world - European Commission"
cap label var ROW_IORG "Rest of the world - international organisations"
cap label var ROW_IORG_X_EC "Rest of the world - international organisations (excluding EC)"
cap label var ROW_OTH "Rest of the world - other sources"
cap label var ROW_OTH_GOV "Rest of the world - other sources - government sector"
cap label var ROW_OTH_HES "Rest of the world - other sources - higher education sector"
cap label var ROW_OTH_HES_FOR "Rest of the world - other sources - higher education sector - foreign branch campuses"
cap label var ROW_OTH_HES_O "Rest of the world - other sources - higher education sector - other higher education institutions"
cap label var ROW_OTH_PNP "Rest of the world - other sources - private non-profit sector"
cap label var ROW_OTH_NEC "Rest of the world - other sources - not elsewhere classified"
cap label var NAP "Not applicable"
