cap label var CODE "Label - English"
cap label var TOTAL "Total"
cap label var HS0101 "Live horses, asses, mules and hinnies"
cap label var HS0102 "Live bovine animals"
cap label var HS0103 "Live swine"
cap label var HS0104 "Live sheep and goats"
cap label var HS0105 "Live poultry, that is to say, fowls of the species Gallus domesticus, ducks, geese, turkeys and guinea fowls"
cap label var HS0106 "Other live animals"
cap label var HS0201 "Meat of bovine animals, fresh or chilled"
cap label var HS0202 "Meat of bovine animals, frozen"
cap label var HS0203 "Meat of swine, fresh, chilled or frozen"
cap label var HS0204 "Meat of sheep or goats, fresh, chilled or frozen"
cap label var HS0205 "Meat of horses, asses, mules or hinnies, fresh, chilled or frozen"
cap label var HS0206 "Edible offal of bovine animals, swine, sheep, goats, horses, asses, mules or hinnies, fresh, chilled or frozen"
cap label var HS020610 "Edible offal of bovine animals, fresh or chilled"
cap label var HS020621 "Edible tongues of bovine animals, frozen"
cap label var HS020622 "Edible livers of bovine animals, frozen"
cap label var HS020629 "Other edible offal of bovine animals, frozen"
cap label var HS020630 "Edible offal of swine, fresh or chilled"
cap label var HS020641 "Edible livers of swine, frozen"
cap label var HS020649 "Other edible offal of swine, frozen"
cap label var HS020680 "Other edible offal, fresh or chilled"
cap label var HS020690 "Other edible offal, frozen"
cap label var HS0207 "Meat and edible offal of fowls of the species Gallus domesticus, ducks, geese, turkeys and guinea fowls, fresh, chilled or frozen"
cap label var HS0208 "Other meat and edible meat offal, fresh, chilled or frozen"
cap label var HS0209 "Pig fat, free of lean meat, and poultry fat, not rendered or otherwise extracted, fresh, chilled, frozen, salted, in brine, dried or smoked"
cap label var HS0210 "Meat and edible meat offal, salted, in brine, dried or smoked; edible flours and meals of meat or meat offal"
cap label var HS0301 "Live fish"
cap label var HS030191 "Trout (Salmo trutta, Oncorhynchus mykiss, Oncorhynchus clarki, Oncorhynchus aguabonita, Oncorhynchus gilae, Oncorhynchus apache and Oncorhynchus chrysogaster)"
cap label var HS030192 "Eels (Anguilla spp.)"
cap label var HS030193 "Carp (Cyprinus spp., Carassius spp., Ctenopharyngodon idellus, Hypophthalmichthys spp., Cirrhinus spp., Mylopharyngodon piceus, Catla catla, Labeo spp., Osteochilus hasselti, Leptobarbus hoeveni, Megalobrama spp.)"
cap label var HS030199 "Other live fish"
cap label var HS0302 "Fish, fresh or chilled, excluding fish fillets and other fish meat (whether or not minced), fresh, chilled or frozen (heading 03.04)"
cap label var HS030211 "Trout (Salmo trutta, Oncorhynchus mykiss, Oncorhynchus clarki, Oncorhynchus aguabonita, Oncorhynchus gilae, Oncorhynchus apache and Oncorhynchus chrysogaster), fresh or chilled"
cap label var HS030213 "Pacific salmon (Oncorhynchus nerka, Oncorhynchus gorbuscha, Oncorhynchus keta, Oncorhynchus tschawytscha, Oncorhynchus kisutch, Oncorhynchus masou and Oncorhynchus rhodurus), fresh or chilled"
cap label var HS030214 "Atlantic salmon (Salmo salar) and Danube salmon (Hucho hucho), fresh or chilled"
cap label var HS030219 "Other salmonidae, fresh or chilled"
cap label var HS030246 "Cobia (Rachycentron canadum), fresh or chilled"
cap label var HS030271 "Tilapias (Oreochromis spp.), fresh or chilled"
cap label var HS030272 "Catfish (Pangasius spp., Silurus spp., Clarias spp., Ictalurus spp.), fresh or chilled"
cap label var HS030273 "Carp (Cyprinus spp., Carassius spp., Ctenopharyngodon idellus, Hypophthalmichthys spp., Cirrhinus spp., Mylopharyngodon piceus, Catla catla, Labeo spp., Osteochilus hasselti, Leptobarbus hoeveni, Megalobrama spp.), fresh or chilled"
cap label var HS030274 "Eels (Anguilla spp.), fresh or chilled"
cap label var HS030279 "Nile perch (Lates niloticus) and snakeheads (Channa spp.), fresh or chilled"
cap label var HS030281 "Dogfish and other sharks, fresh or chilled"
cap label var HS030282 "Rays and skates (Rajidae), fresh or chilled"
cap label var HS030284 "Sea bass (Dicentrarchus spp.), fresh or chilled"
cap label var HS030285 "Sea bream (Sparidae), fresh or chilled"
cap label var HS030289 "Other fish, fresh or chilled"
cap label var HS030292 "Shark fins, fresh or chilled"
cap label var HS0303 "Fish, frozen, excluding fish fillets and other fish meat (whether or not minced), fresh, chilled or frozen (heading 03.04)"
cap label var HS030311 "Sockeye salmon (red salmon) (Oncorhynchus nerka), frozen"
cap label var HS030312 "Other Pacific salmon (Oncorhynchus gorbuscha, Oncorhynchus keta, Oncorhynchus tschawytscha, Oncorhynchus kisutch, Oncorhynchus masou and Oncorhynchus rhodurus), frozen"
cap label var HS030313 "Atlantic salmon (Salmo salar) and Danube salmon (Hucho hucho), frozen"
cap label var HS030314 "Trout (Salmo trutta, Oncorhynchus mykiss, Oncorhynchus clarki, Oncorhynchus aguabonita, Oncorhynchus gilae, Oncorhynchus apache and Oncorhynchus chrysogaster), frozen"
cap label var HS030319 "Other salmonidae, excluding edible fish offal: livers, roes, milt, fish fins, heads, tails, maws and other edible fish offal (subheadings 0303.91 to 0303.99), frozen"
cap label var HS030323 "Tilapias (Oreochromis spp.), frozen"
cap label var HS030324 "Catfish (Pangasius spp., Silurus spp., Clarias spp., Ictalurus spp.), frozen"
cap label var HS030325 "Carp (Cyprinus spp., Carassius spp., Ctenopharyngodon idellus, Hypophthalmichthys spp., Cirrhinus spp., Mylopharyngodon piceus, Catla catla, Labeo spp., Osteochilus hasselti, Leptobarbus hoeveni, Megalobrama spp.), frozen"
cap label var HS030326 "Eels (Anguilla spp.), frozen"
cap label var HS030329 "Nile perch (Lates niloticus) and snakeheads (Channa spp.), frozen"
cap label var HS030356 "Cobia (Rachycentron canadum), frozen"
cap label var HS030381 "Dogfish and other sharks, frozen"
cap label var HS030382 "Rays and skates (Rajidae), frozen"
cap label var HS030384 "Seabass (Dicentrarchus spp.), frozen"
cap label var HS030389 "Other fish, frozen"
cap label var HS030392 "Shark fins, frozen"
cap label var HS0304 "Fish fillets and other fish meat (whether or not minced), fresh, chilled or frozen"
cap label var HS030431 "Fillets of tilapias (Oreochromis spp.), fresh or chilled"
cap label var HS030432 "Fillets of catfish (Pangasius spp., Silurus spp., Clarias spp., Ictalurus spp.), fresh or chilled"
cap label var HS030433 "Fillets of Nile Perch (Lates niloticus), fresh or chilled"
cap label var HS030439 "Fillets of carp (Cyprinus spp., Carassius spp., Ctenopharyngodon idellus, Hypophthalmichthys spp., Cirrhinus spp., Mylopharyngodon piceus, Catla catla, Labeo spp., Osteochilus hasselti, Leptobarbus hoeveni, Megalobrama spp.), eels (Anguilla spp.) and snakeheads (Channa spp.), fresh or chilled"
cap label var HS030441 "Fillets of Pacific salmon (Oncorhynchus nerka, Oncorhynchus gorbuscha, Oncorhynchus keta, Oncorhynchus tschawytscha, Oncorhynchus kisutch, Oncorhynchus masou and Oncorhynchus rhodurus), Atlantic salmon (Salmo salar) and Danube salmon (Huchohucho), fresh or chilled"
cap label var HS030442 "Fillets of trout (Salmo trutta, Oncorhynchus mykiss, Oncorhynchus clarki, Oncorhynchus aguabonita, Oncorhynchus gilae, Oncorhynchus apache and Oncorhynchus chrysogaster), fresh or chilled"
cap label var HS030447 "Fillets of dogfish and other sharks, fresh or chilled"
cap label var HS030448 "Fillets of rays and skates (Rajidae), fresh or chilled"
cap label var HS030449 "Other fish fillets, fresh or chilled"
cap label var HS030461 "Fillets of tilapias (Oreochromis spp.), frozen"
cap label var HS030462 "Fillets of catfish (Pangasius spp., Silurus spp., Clarias spp., Ictalurus spp.), frozen"
cap label var HS030463 "Fillets of Nile Perch (Lates niloticus), frozen"
cap label var HS030469 "Fillets of carp (Cyprinus spp., Carassius spp., Ctenopharyngodon idellus, Hypophthalmichthys spp., Cirrhinus spp., Mylopharyngodon piceus, Catla catla, Labeo spp., Osteochilus hasselti, Leptobarbus hoeveni, Megalobrama spp.), eels (Anguilla spp.) and snakeheads (Channa spp.), frozen"
cap label var HS030481 "Fillets of Pacific salmon (Oncorhynchus nerka, Oncorhynchus gorbuscha, Oncorhynchus keta, Oncorhynchus tschawytscha, Oncorhynchus kisutch, Oncorhynchus masou and Oncorhynchus rhodurus), Atlantic salmon (Salmo salar) and Danube salmon (Huchohucho), frozen"
cap label var HS030482 "Fillets of trout (Salmo trutta, Oncorhynchus mykiss, Oncorhynchus clarki, Oncorhynchus aguabonita, Oncorhynchus gilae, Oncorhynchus apache and Oncorhynchus chrysogaster), frozen"
cap label var HS030488 "Fillets of dogfish, other sharks, rays and skates (Rajidae), frozen"
cap label var HS030489 "Other fish fillets, frozen"
cap label var HS0305 "Fish, dried, salted or in brine; smoked fish, whether or not cooked before or during the smoking process"
cap label var HS030531 "Fillets of tilapias (Oreochromis spp.), catfish (Pangasius spp., Silurus spp., Clarias spp., Ictalurus spp.), carp (Cyprinus spp., Carassius spp., Ctenopharyngodon idellus, Hypophthalmichthys spp., Cirrhinus spp., Mylopharyngodon piceus, Catla catla, Labeo spp., Osteochilus hasselti, Leptobarbus hoeveni, Megalobrama spp.), eels (Anguilla spp.), Nile perch (Lates niloticus) and snakeheads (Channa spp.), dried, salted or in brine, but not smoked"
cap label var HS030539 "Other fish fillets, dried, salted or in brine, but not smoked"
cap label var HS030541 "Pacific salmon (Oncorhynchus nerka, Oncorhynchus gorbuscha, Oncorhynchus keta, Oncorhynchus tschawytscha, Oncorhynchus kisutch, Oncorhynchus masou and Oncorhynchus rhodurus), Atlantic salmon (Salmo salar) and Danube salmon (Hucho hucho), smoked, including fillets, other than edible fish offal"
cap label var HS030543 "Trout (Salmo trutta, Oncorhynchus mykiss, Oncorhynchus clarki, Oncorhynchus aguabonita, Oncorhynchus gilae, Oncorhynchus apache and Oncorhynchus chrysogaster), smoked, including fillets, other than edible fish offal"
cap label var HS030544 "Tilapias (Oreochromis spp.), catfish (Pangasius spp., Silurus spp., Clarias spp., Ictalurus spp.), carp (Cyprinus spp., Carassius spp., Ctenopharyngodon idellus, Hypophthalmichthys spp., Cirrhinus spp., Mylopharyngodon piceus, Catla catla, Labeo spp., Osteochilus hasselti, Leptobarbus hoeveni, Megalobrama spp.), eels (Anguilla spp.), Nile perch (Lates niloticus) and snakeheads (Channa spp.), smoked, including fillets, other than edible fish offal"
cap label var HS030549 "Other smoked fish, including fillets, other than edible fish offal"
cap label var HS030552 "Tilapias (Oreochromis spp.), catfish (Pangasius spp., Silurus spp., Clarias spp., Ictalurus spp.), carp (Cyprinus spp., Carassius spp., Ctenopharyngodon idellus, Hypophthalmichthys spp., Cirrhinus spp., Mylopharyngodon piceus, Catla catla, Labeo spp., Osteochilus hasselti, Leptobarbus hoeveni, Megalobrama spp.), eels (Anguilla spp.), Nile perch (Lates niloticus) and snakeheads (Channa spp.), dried, other than edible fish offal, wheter or not salted but not smoked"
cap label var HS030559 "Other dried fish, other than edible fish offal, whether or not salted but not smoked"
cap label var HS030564 "Tilapias (Oreochromis spp.), catfish (Pangasius spp., Silurus spp., Clarias spp., Ictalurus spp.), carp (Cyprinus spp., Carassius spp., Ctenopharyngodon idellus, Hypophthalmichthys spp., Cirrhinus spp., Mylopharyngodon piceus, Catla catla, Labeo spp., Osteochilus hasselti, Leptobarbus hoeveni, Megalobrama spp.), eels (Anguilla spp.), Nile perch (Lates niloticus) and snakeheads (Channa spp.), salted but not dried or smoked and fish in brine, other than edible fish offal"
cap label var HS030569 "Other fish, salted but not dried or smoked and fish in brine, other than edible fish offal"
cap label var HS030571 "Shark fins"
cap label var HS0306 "Crustaceans, whether in shell or not, live, fresh, chilled, frozen, dried, salted or in brine; smoked crustaceans, whether in shell or not, whether or not cooked before or during the smoking process; crustaceans, in shell, cooked by steaming or by boiling in water, whether or not chilled, frozen, dried, salted or in brine"
cap label var HS030611 "Rock lobster and other sea crawfish (Palinurus spp., Panulirus spp., Jasus spp.), frozen"
cap label var HS030612 "Lobsters (Homarus spp.), frozen"
cap label var HS030614 "Crabs, frozen"
cap label var HS030615 "Norway lobsters (Nephrops norvegicus), frozen"
cap label var HS030616 "Cold-water shrimps and prawns (Pandalus spp., Crangon crangon), frozen"
cap label var HS030617 "Other shrimps and prawns, frozen"
cap label var HS030619 "Other crustaceans, frozen"
cap label var HS030631 "Rock lobster and other sea crawfish (Palinurus spp., Panulirus spp., Jasus spp.), live, fresh or chilled"
cap label var HS030632 "Lobsters (Homarus spp.), live, fresh or chilled"
cap label var HS030633 "Crabs, live, fresh or chilled"
cap label var HS030634 "Norway lobsters (Nephrops norvegicus), live, fresh or chilled"
cap label var HS030635 "Cold-water shrimps and prawns (Pandalus spp., Crangon crangon), live, fresh or chilled"
cap label var HS030636 "Other shrimps and prawns, live, fresh or chilled"
cap label var HS030639 "Other crustaceans, live, fresh or chilled"
cap label var HS030691 "Rock lobster and other sea crawfish (Palinurus spp., Panulirus spp. and Jasus spp.), whether in shell or not, dried, salted, smoked or in brine, including in shell, cooked by steaming or by boiling in water"
cap label var HS030692 "Lobsters (Homarus spp.), whether in shell or not, dried, salted, smoked or in brine, including lobsters in shell, cooked by steaming or by boiling in water"
cap label var HS030693 "Crabs, whether in shell or not, dried, salted, smoked or in brine, including crabs in shell, cooked by steaming or by boiling in water"
cap label var HS030694 "Norway lobsters (Nephrops norvegicus), whether in shell or not, dried, salted, smoked or in brine, including lobsters in shell, cooked by steaming or by boiling in water"
cap label var HS030695 "Shrimps and prawns, whether in shell or not, dried, salted, smoked or in brine, including ones in shell, cooked by steaming or by boiling in water"
cap label var HS030699 "Other crustaceans, whether in shell or not, dried, salted, smoked or in brine, incl. crustaceans in shell, cooked by steaming or by boiling in water"
cap label var HS0401 "Milk and cream, not concentrated nor containing added sugar or other sweetening matter"
cap label var HS040110 "Milk and cream of a fat content, by weight, not exceeding 1 %, not concentrated nor containing added sugar or other sweetening matter"
cap label var HS040120 "Milk and cream of a fat content, by weight, exceeding 1 % but not exceeding 6 %, not concentrated nor containing added sugar or other sweetening matter"
cap label var HS040140 "Milk and cream of a fat content, by weight, exceeding 6 % but not exceeding 10 %, not concentrated nor containing added sugar or other sweetening matter"
cap label var HS040150 "Milk and cream of a fat content, by weight, exceeding 10 %, not concentrated nor containing added sugar or other sweetening matter"
cap label var HS0402 "Milk and cream, concentrated or containing added sugar or other sweetening matter"
cap label var HS040210 "Milk and cream, concentrated or containing added sugar or other sweetening matter, in powder, granules or other solid forms, of a fat content, by weight, not exceeding 1.5 %"
cap label var HS040221 "Milk and cream, in powder, granules or other solid forms, of a fat content, by weight, exceeding 1.5 %, not containing added sugar or other sweetening matter"
cap label var HS040229 "Other milk and cream, concentrated or containing added sugar or other sweetening matter, in powder, granules or other solid forms, of a fat content, by weight, exceeding 1.5 %"
cap label var HS040291 "Other milk and cream, in powder, granules or other solid forms, of a fat content, by weight, exceeding 1.5 %, not containing added sugar or other sweetening matter"
cap label var HS040299 "Other milk and cream concentrated or containing added sugar or other sweetening matter"
cap label var HS0403 "Yogurt; buttermilk, curdled milk and cream, kephir and other fermented or acidified milk and cream, whether or not concentrated or containing added sugar or other sweetening matter or flavoured or containing added fruit, nuts or cocoa"
cap label var HS040320 "Yogurt"
cap label var HS040390 "Buttermilk, curdled milk and cream, kephir and other fermented or acidified milk and cream, whether or not concentrated or containing added sugar or other sweetening matter or flavoured or containing added fruit, nuts or cocoa (excl. yogurt)"
cap label var HS0404 "Whey, whether or not concentrated or containing added sugar or other sweetening matter; products consisting of natural milk constituents, whether or not containing added sugar or other sweetening matter, not elsewhere specified or included"
cap label var HS040410 "Whey and modified whey, whether or not concentrated or containing added sugar or other sweetening matter"
cap label var HS040490 "Products consisting of natural milk constituents, whether or not containing added sugar or other sweetening matter, not elsewhere specified or included"
cap label var HS0405 "Butter and other fats and oils derived from milk; dairy spreads"
cap label var HS040510 "Butter"
cap label var HS0406 "Cheese and curd"
cap label var HS040610 "Fresh (unripened or uncured) cheese, including whey cheese, and curd"
cap label var HS040620 "Grated or powdered cheese, of all kinds"
cap label var HS040630 "Processed cheese, not grated or powdered"
cap label var HS040640 "Blue-veined cheese and other cheese containing veins produced by Penicillium roqueforti"
cap label var HS040690 "Other cheese"
cap label var HS0407 "Birds' eggs, in shell, fresh, preserved or cooked"
cap label var HS0408 "Birds' eggs, not in shell, and egg yolks, fresh, dried, cooked by steaming or by boiling in water, moulded, frozen or otherwise preserved, whether or not containing added sugar or other sweetening matter"
cap label var HS0701 "Potatoes, fresh or chilled"
cap label var HS0702 "Tomatoes, fresh or chilled"
cap label var HS0703 "Onions, shallots, garlic, leeks and other alliaceous vegetables, fresh or chilled"
cap label var HS0704 "Cabbages, cauliflowers, kohlrabi, kale and similar edible brassicas, fresh or chilled"
cap label var HS0705 "Lettuce (Lactuca sativa) and chicory (Cichorium spp.), fresh or chilled"
cap label var HS0706 "Carrots, turnips, salad beetroot, salsify, celeriac, radishes and similar edible roots, fresh or chilled"
cap label var HS0707 "Cucumbers and gherkins, fresh or chilled"
cap label var HS0708 "Leguminous vegetables, shelled or unshelled, fresh or chilled"
cap label var HS0709 "Other vegetables, fresh or chilled"
cap label var HS0710 "Vegetables (uncooked or cooked by steaming or boiling in water), frozen"
cap label var HS0711 "Vegetables provisionally preserved, but unsuitable in that state for immediate consumption"
cap label var HS071120 "Olives, provisionally preserved, but unsuitable in that state for immediate consumption"
cap label var HS071140 "Cucumbers and gherkins provisionally preserved, but unsuitable in that state for immediate consumption"
cap label var HS071190 "Other vegetables; mixtures of vegetables provisionally preserved, but unsuitable in that state for immediate consumption"
cap label var HS0712 "Dried vegetables, whole, cut, sliced, broken or in powder, but not further prepared"
cap label var HS0713 "Dried leguminous vegetables, shelled, whether or not skinned or split"
cap label var HS0714 "Manioc, arrowroot, salep, Jerusalem artichokes, sweet potatoes and similar roots and tubers with high starch or inulin content, fresh, chilled, frozen or dried, whether or not sliced or in the form of pellets; sago pith"
cap label var HS0801 "Coconuts, Brazil nuts and cashew nuts, fresh or dried, whether or not shelled or peeled"
cap label var HS0802 "Other nuts, fresh or dried, whether or not shelled or peeled"
cap label var HS0803 "Bananas, including plantains, fresh or dried"
cap label var HS0804 "Dates, figs, pineapples, avocados, guavas, mangoes and mangosteens, fresh or dried"
cap label var HS0805 "Citrus fruit, fresh or dried"
cap label var HS0806 "Grapes, fresh or dried"
cap label var HS0807 "Melons (including watermelons) and papaws (papayas), fresh"
cap label var HS080810 "Apples, fresh"
cap label var HS080830 "Pears, fresh"
cap label var HS080840 "Quinces, fresh"
cap label var HS080910 "Apricots, fresh"
cap label var HS080921 "Sour cherries (Prunus cerasus), fresh"
cap label var HS080929 "Other cherries, fresh"
cap label var HS080930 "Peaches, including nectarines, fresh"
cap label var HS080940 "Plums and sloes, fresh"
cap label var HS0810 "Other fruit, fresh"
cap label var HS0811 "Fruit and nuts, uncooked or cooked by steaming or boiling in water, frozen, whether or not containing added sugar or other sweetening matter"
cap label var HS0812 "Fruit and nuts provisionally preserved, but unsuitable in that state for immediate consumption"
cap label var HS0813 "Fruit, dried, other than coconuts, Brazil nuts and cashew nuts, other nuts, bananas, dates, figs, pineapples, avocados, guavas, mangoes and mangosteens, citrus fruit and grapes (headings 08.01 to 08.06); mixtures of nuts or dried fruits"
cap label var HS081310 "Apricots, dried"
cap label var HS081320 "Prunes, dried"
cap label var HS081330 "Apples, dried"
cap label var HS081340 "Other fruit, dried"
cap label var HS081350 "Mixtures of nuts or dried fruits"
cap label var HS0901 "Coffee, whether or not roasted or decaffeinated; coffee husks and skins; coffee substitutes containing coffee in any proportion"
cap label var HS0902 "Tea, whether or not flavoured"
cap label var HS0903 "Maté"
cap label var HS0904 "Pepper of the genus Piper; dried or crushed or ground fruits of the genus Capsicum or of the genus Pimenta"
cap label var HS0905 "Vanilla"
cap label var HS0906 "Cinnamon and cinnamon-tree flowers"
cap label var HS0907 "Cloves (whole fruit, cloves and stems)"
cap label var HS0908 "Nutmeg, mace and cardamoms"
cap label var HS0909 "Seeds of anis, badian, fennel, coriander, cumin or caraway; juniper berries"
cap label var HS0910 "Ginger, saffron, turmeric (curcuma), thyme, bay leaves, curry and other spices"
cap label var HS1001 "Wheat and meslin"
cap label var HS1002 "Rye"
cap label var HS1003 "Barley"
cap label var HS1004 "Oats"
cap label var HS1005 "Maize (corn)"
cap label var HS1006 "Rice"
cap label var HS1007 "Grain sorghum"
cap label var HS1008 "Buckwheat, millet and canary seeds; other cereals"
cap label var HS1101 "Wheat or meslin flour"
cap label var HS110220 "Maize (corn) flour"
cap label var HS110290 "Other cereal flours"
cap label var HS110311 "Groats and meal of wheat"
cap label var HS110313 "Groats and meal of maize (corn)"
cap label var HS110319 "Groats and meal of other cereals"
cap label var HS110320 "Pellets"
cap label var HS1104 "Cereal grains otherwise worked (for example, hulled, rolled, flaked, pearled, sliced or kibbled), except rice in the husk (paddy or rough), husked (brown), semi-milled or wholly milled and broken (heading 10.06); germ of cereals, whole, rolled, flaked or ground"
cap label var HS110412 "Grains of oats, rolled or flaked"
cap label var HS110419 "Grains of other cereals, rolled or flaked"
cap label var HS110422 "Other worked grains (for example, hulled, pearled, sliced or kibbled) of oats"
cap label var HS110423 "Other worked grains (for example, hulled, pearled, sliced or kibbled) of maize (corn)"
cap label var HS110429 "Other worked grains (for example, hulled, pearled, sliced or kibbled) of other cereals"
cap label var HS110430 "Germ of cereals, whole, rolled, flaked or ground"
cap label var HS1105 "Flour, meal, powder, flakes, granules and pellets of potatoes"
cap label var HS1106 "Flour, meal and powder of the dried leguminous vegetables, shelled, whether or not skinned or split (heading 07.13), of sago or of roots or tubers of manioc, arrowroot, salep, Jerusalem artichokes, sweet potatoes and similar roots and tubers with high starch or inulin content; sago pith (heading 07.14) or of edible fruit and nuts; peel of citrus fruit or melons (products of Chapter 8)"
cap label var HS1107 "Malt, whether or not roasted"
cap label var HS110710 "Malt, not roasted"
cap label var HS110720 "Malt, roasted"
cap label var HS1108 "Starches; inulin"
cap label var HS110811 "Wheat starch"
cap label var HS110812 "Maize (corn) starch"
cap label var HS110813 "Potato starch"
cap label var HS110814 "Manioc (cassava) starch"
cap label var HS110819 "Other starches"
cap label var HS1109 "Wheat gluten, whether or not dried"
cap label var HS1201 "Soya beans, whether or not broken"
cap label var HS1202 "Ground-nuts, not roasted or otherwise cooked, whether or not shelled or broken"
cap label var HS1203 "Copra"
cap label var HS1204 "Linseed, whether or not broken"
cap label var HS1205 "Rape or colza seeds, whether or not broken"
cap label var HS1206 "Sunflower seeds, whether or not broken"
cap label var HS1207 "Other oil seeds and oleaginous fruits, whether or not broken"
cap label var HS120710 "Palm nuts and kernels, whether or not broken"
cap label var HS120721 "Cotton seeds, whether or not broken"
cap label var HS120729 "Other cotton seeds, whether or not broken"
cap label var HS120730 "Castor oil seeds, whether or not broken"
cap label var HS120740 "Sesamum seeds, whether or not broken"
cap label var HS120750 "Mustard seeds, whether or not broken"
cap label var HS120760 "Safflower (Carthamus tinctorius) seeds, whether or not broken"
cap label var HS1208 "Flours and meals of oil seeds or oleaginous fruits, other than those of mustard"
cap label var HS1210 "Hop cones, fresh or dried, whether or not ground, powdered or in the form of pellets; lupulin"
cap label var HS1212 "Locust beans, seaweeds and other algae, sugar beet and sugar cane, fresh, chilled, frozen or dried, whether or not ground; fruit stones and kernels and other vegetable products (including unroasted chicory roots of the variety Cichorium intybus sativum) of a kind used primarily for human consumption, not elsewhere specified or included"
cap label var HS121291 "Sugar beet, fresh, chilled, frozen or dried, whether or not ground"
cap label var HS121293 "Sugar cane, fresh, chilled, frozen or dried, whether or not ground"
cap label var HS121299 "Other fruit stones and kernels and other vegetable products (including unroasted chicory roots of the variety Cichorium intybus sativum) of a kind used primarily for human consumption, not elsewhere specified or included"
cap label var HS1214 "Swedes, mangolds, fodder roots, hay, alfalfa, clover, sainfoin, forage kale, lupines, vetches and similar forage products, whether or not in the form of pellets"
cap label var HS1404 "Vegetable products not elsewhere specified or included"
cap label var HS140420 "Cotton linters"
cap label var HS1507 "Soya-bean oil and its fractions, whether or not refined, but not chemically modified"
cap label var HS1508 "Ground-nut oil and its fractions, whether or not refined, but not chemically modified"
cap label var HS1509 "Olive oil and its fractions, whether or not refined, but not chemically modified"
cap label var HS1510 "Other oils and their fractions, obtained solely from olives, whether or not refined, but not chemically modified, including blends of these oils or fractions with oils or fractions of olive oil and its fractions (heading 1509)"
cap label var HS1511 "Palm oil and its fractions, whether or not refined, but not chemically modified"
cap label var HS1512 "Sunflower-seed, safflower or cotton-seed oil and fractions thereof, whether or not refined, but not chemically modified"
cap label var HS1513 "Coconut (copra), palm kernel or babassu oil and fractions thereof, whether or not refined, but not chemically modified"
cap label var HS151311 "Coconut (copra) oil and its fractions, whether or not refined, but not chemically modified, crude oil"
cap label var HS151319 "Other coconut (copra) oil and its fractions, whether or not refined, but not chemically modified"
cap label var HS151321 "Palm kernel or babassu oil and fractions thereof, whether or not refined, but not chemically modified, crude oil"
cap label var HS151329 "Other palm kernel and babassu oil and their fractions, whether or not refined, but not chemically modified"
cap label var HS1514 "Rape, colza or mustard oil and fractions thereof, whether or not refined, but not chemically modified"
cap label var HS1515 "Other fixed vegetable or microbial fats and oils (including jojoba oil) and their fractions, whether or not refined, but not chemically modified"
cap label var HS1516 "Animal, vegetable or microbial fats and oils and their fractions, partly or wholly hydrogenated, inter-esterified, re-esterified or elaidinised, whether or not refined, but not further prepared"
cap label var HS1517 "Margarine; edible mixtures or preparations of animal, vegetable or microbial fats or oils or of fractions of different fats or oils of this Chapter, other than edible fats and oils or their fractions, partly or wholly hydrogenated, inter-esterified, re-esterified or elaidinised, whether or not refined, but not further prepared (heading 15.16)"
cap label var HS1518 "Animal, vegetable or microbial fats and oils and their fractions, boiled, oxidised, dehydrated, sulphurised, blown, polymerised by heat in vacuum or in inert gas or otherwise chemically modified, excluding those partly or wholly hydrogenated, inter-esterified, re-esterified or elaidinised, whether or not refined, but not further prepared (heading 15.16); inedible mixtures or preparations of animal, vegetable or microbial fats or oils or of fractions of different fats or oils of this Chapter, not elsewhere specified or included"
cap label var HS1601 "Sausages and similar products, of meat, meat offal, blood or insects; food preparations based on these products"
cap label var HS1602 "Other prepared or preserved meat, meat offal, blood or insects"
cap label var HS1604 "Prepared or preserved fish; caviar and caviar substitutes prepared from fish eggs"
cap label var HS160411 "Salmon, whole or in pieces, but not minced"
cap label var HS160419 "Other fish, whole or in pieces, but not minced"
cap label var HS160420 "Other fish, prepared or preserved"
cap label var HS1605 "Crustaceans, molluscs and other aquatic invertebrates, prepared or preserved"
cap label var HS160510 "Crab, prepared or preserved"
cap label var HS160521 "Shrimps and prawns, not in airtight containers"
cap label var HS160529 "Other shrimps and prawns, prepared or preserved"
cap label var HS160530 "Lobster, prepared or preserved"
cap label var HS160540 "Other crustaceans, prepared or preserved"
cap label var HS1701 "Cane or beet sugar and chemically pure sucrose, in solid form"
cap label var HS170112 "Raw beet sugar, in solid form, not containing added flavouring or colouring matter"
cap label var HS170113 "Raw cane sugar, in solid form, not containing added flavouring or colouring matter, obtained without centrifugation, with sucrose content 69° to 93°, containing only natural anhedral microcrystals (see subheading note 2.)"
cap label var HS170114 "Other raw cane sugar,in solid form, not containing added flavouring or colouring matter"
cap label var HS170191 "Other cane or beet sugar and chemically pure sucrose,in solid form, containing added flavouring or colouring"
cap label var HS170199 "Other cane or beet sugar and chemically pure sucrose, in solid form"
cap label var HS1703 "Molasses resulting from the extraction or refining of sugar"
cap label var HS1704 "Sugar confectionery (including white chocolate), not containing cocoa"
cap label var HS1801 "Cocoa beans, whole or broken, raw or roasted"
cap label var HS1803 "Cocoa paste, whether or not defatted"
cap label var HS1804 "Cocoa butter, fat and oil"
cap label var HS1805 "Cocoa powder, not containing added sugar or other sweetening matter"
cap label var HS1806 "Chocolate and other food preparations containing cocoa"
cap label var HS1902 "Pasta, whether or not cooked or stuffed (with meat or other substances) or otherwise prepared, such as spaghetti, macaroni, noodles, lasagne, gnocchi, ravioli, cannelloni; couscous, whether or not prepared"
cap label var HS190211 "Uncooked pasta, not stuffed or otherwise prepared, containing eggs"
cap label var HS190219 "Other uncooked pasta, not stuffed or otherwise prepared"
cap label var HS190220 "Stuffed pasta, whether or not cooked or otherwise prepared"
cap label var HS190230 "Other pasta, whether or not cooked or otherwise prepared"
cap label var HS190240 "Couscous, whether or not prepared"
cap label var HS1904 "Prepared foods obtained by the swelling or roasting of cereals or cereal products (for example, corn flakes); cereals (other than maize (corn)) in grain form or in the form of flakes or other worked grains (except flour, groats and meal), pre-cooked, or otherwise prepared, not elsewhere specified or included"
cap label var HS1905 "Bread, pastry, cakes, biscuits and other bakers' wares, whether or not containing cocoa; communion wafers, empty cachets of a kind suitable for pharmaceutical use, sealing wafers, rice paper and similar products"
cap label var HS2001 "Vegetables, fruit, nuts and other edible parts of plants, prepared or preserved by vinegar or acetic acid"
cap label var HS2002 "Tomatoes, prepared or preserved otherwise than by vinegar or acetic acid"
cap label var HS2003 "Mushrooms and truffles, prepared or preserved otherwise than by vinegar or acetic acid"
cap label var HS2004 "Vegetables prepared or preserved otherwise than by vinegar or acetic acid, frozen, other than vegetables, fruit, nuts, fruit-peel and other parts of plants,preserved by sugar (drained, glacé or crystallised) (heading 20.06)"
cap label var HS2005 "Other vegetables prepared or preserved otherwise than by vinegar or acetic acid, not frozen, other than vegetables, fruit, nuts, fruit-peel and other parts of plants,preserved by sugar (drained, glacé or crystallised) (heading 20.06)"
cap label var HS2006 "Vegetables, fruit, nuts, fruit-peel and other parts of plants, preserved by sugar (drained, glacé or crystallised)"
cap label var HS2007 "Jams, fruit jellies, marmalades, fruit or nut purée and fruit or nut pastes, obtained by cooking, whether or not containing added sugar or other sweetening matter"
cap label var HS2008 "Fruit, nuts and other edible parts of plants, otherwise prepared or preserved, whether or not containing added sugar or other sweetening matter or spirit, not elsewhere specified or included"
cap label var HS2009 "Fruit or nut juices (including grape must and coconut water) and vegetable juices, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter"
cap label var HS200911 "Orange juice, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter, frozen"
cap label var HS200912 "Orange juice, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter, not frozen, of a Brix value not exceeding 20"
cap label var HS200919 "Other orange juice, unfermented, whether or not containing added sugar or other sweetening matter"
cap label var HS200921 "Grapefruit juice, pomelo juice, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter, of a Brix value not exceeding 20"
cap label var HS200929 "Other grapefruit juice, pomelo juice, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter, of a Brix value not exceeding 20"
cap label var HS200931 "Single citrus fruit juice, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter, of a Brix value not exceeding 20"
cap label var HS200939 "Other single citrus fruit juice, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter, of a Brix value not exceeding 20"
cap label var HS200941 "Pineapple juice, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter, of a Brix value not exceeding 20"
cap label var HS200949 "Other pineapple juice, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter, of a Brix value not exceeding 20"
cap label var HS200950 "Tomato juice, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter"
cap label var HS200961 "Grape juice (including grape must), unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter, of a Brix value not exceeding 30"
cap label var HS200969 "Other grape juice (including grape must), unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter, of a Brix value not exceeding 30"
cap label var HS200971 "Apple juice, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter, of a Brix value not exceeding 20"
cap label var HS200979 "Other apple juice, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter, of a Brix value not exceeding 20"
cap label var HS200981 "Cranberry (Vaccinium macrocarpon, Vaccinium oxycoccos) juice; lingonberry (Vaccinium vitis-idaea) juice, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter"
cap label var HS200989 "Other juice of fruit, nut or vegetables, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter"
cap label var HS200990 "Mixtures of fruit juices (including grape must and coconut water), and vegetable juices, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter"
cap label var HS2103 "Sauces and preparations therefor; mixed condiments and mixed seasonings; mustard flour and meal and prepared mustard"
cap label var HS210310 "Soya sauce"
cap label var HS210320 "Tomato ketchup and other tomato sauces"
cap label var HS210330 "Mustard flour and meal and prepared mustard"
cap label var HS210390 "Other sauces and preparations therefor; mixed condiments and mixed seasonings; mustard flour and meal and prepared mustard"
cap label var HS2105 "Ice cream and other edible ice, whether or not containing cocoa"
cap label var HS2203 "Beer made from malt"
cap label var HS2204 "Wine of fresh grapes, including fortified wines; grape must other than fruit or nut juices (including grape must and coconut water) and vegetable juices, unfermented and not containing added spirit, whether or not containing added sugar or other sweetening matter (heading 20.09)"
cap label var HS2205 "Vermouth and other wine of fresh grapes, flavoured with plants or aromatic substances"
cap label var HS2206 "Other fermented beverages (for example, cider, perry, mead, saké); mixtures of fermented beverages and mixtures of fermented beverages and non-alcoholic beverages, not elsewhere specified or included"
cap label var HS2209 "Vinegar and substitutes for vinegar obtained from acetic acid"
cap label var HS2304 "Oil-cake and other solid residues, whether or not ground or in the form of pellets, resulting from the extraction of soya-bean oil"
cap label var HS2305 "Oil-cake and other solid residues, whether or not ground or in the form of pellets, resulting from the extraction of ground-nut oil"
cap label var HS2306 "Oil-cake and other solid residues, whether or not ground or in the form of pellets, resulting from the extraction of vegetable or microbial fats or oils, other than those resulting from the extraction of soya-bean oil or ground-nut oil (heading 23.04 or 23.05)"
cap label var HS230610 "Oil-cake and other solid residues, whether or not ground or in the form of pellets, resulting from the extraction of cotton seeds"
cap label var HS230620 "Oil-cake and other solid residues, whether or not ground or in the form of pellets, resulting from the extraction of linseed"
cap label var HS230630 "Oil-cake and other solid residues, whether or not ground or in the form of pellets, resulting from the extraction of sunflower seeds"
cap label var HS230641 "Oil-cake and other solid residues, whether or not ground or in the form of pellets, resulting from the extraction of low erucic acid rape or colza seeds"
cap label var HS230649 "Other oil-cake and other solid residues, whether or not ground or in the form of pellets, resulting from the extraction of rape or colza seeds"
cap label var HS230650 "Oil-cake and other solid residues, whether or not ground or in the form of pellets, resulting from the extraction of coconut or copra"
cap label var HS230660 "Oil-cake and other solid residues, whether or not ground or in the form of pellets, resulting from the extraction of palm nuts or kernels"
cap label var HS230690 "Other oil-cake and other solid residues, whether or not ground or in the form of pellets, resulting from the extraction of vegetable fats or oils"
cap label var HS2401 "Unmanufactured tobacco; tobacco refuse"
cap label var HS2402 "Cigars, cheroots, cigarillos and cigarettes of tobacco or of tobacco substitutes"
cap label var HS2403 "Other manufactured tobacco and manufactured tobacco substitutes; «homogenised» or «reconstituted» tobacco; tobacco extracts and essences"
cap label var HS4001 "Natural rubber, balata, gutta-percha, guayule, chicle and similar natural gums, in primary forms or in plates, sheets or strip"
cap label var HS4005 "Compounded rubber, unvulcanised, in primary forms or in plates, sheets or strip"
cap label var HS4006 "Other forms (for example, rods, tubes and profile shapes) and articles (for example, discs and rings), of unvulcanised rubber"
cap label var HS4007 "Vulcanised rubber thread and cord"
cap label var HS4008 "Plates, sheets, strip, rods and profile shapes, of vulcanised rubber other than hard rubber"
cap label var HS4010 "Conveyor or transmission belts or belting, of vulcanised rubber"
cap label var HS4011 "New pneumatic tyres, of rubber"
cap label var HS4012 "Retreaded or used pneumatic tyres of rubber; solid or cushion tyres, tyre treads and tyre flaps, of rubber"
cap label var HS4013 "Inner tubes, of rubber"
cap label var HS4015 "Articles of apparel and clothing accessories (including gloves, mittens and mitts), for all purposes, of vulcanised rubber other than hard rubber"
cap label var HS4016 "Other articles of vulcanised rubber other than hard rubber"
cap label var HS4017 "Hard rubber (for example, ebonite) in all forms, including waste and scrap; articles of hard rubber"
cap label var HS4101 "Raw hides and skins of bovine (including buffalo) or equine animals (fresh, or salted, dried, limed, pickled or otherwise preserved, but not tanned, parchment-dressed or further prepared), whether or not dehaired or split"
cap label var HS4102 "Raw skins of sheep or lambs, fresh, or salted, dried, limed, pickled or otherwise preserved, whether or not dehaired or split (excl. those with wool on, fleeces of Astrakhan, Caracul, Persian, Broadtail or similar lambs, or of Indian, Chinese, Mongolian or Tibetan lambs and tanned, parchment-dressed or further prepared)"
cap label var HS4103 "Other raw hides and skins, fresh, or salted, dried, limed, pickled or otherwise preserved, whether or not dehaired or split (excl. those of bovine animals, equine animals, sheep and lambs, those with wool on and those of goats or kids from Yemen, Mongolia or Tibet and tanned, parchment-dressed or further prepared)"
cap label var HS4104 "Tanned or crust hides and skins of bovine (including buffalo) or equine animals, without hair on, whether or not split, but not further prepared"
cap label var HS4105 "Tanned or crust skins of sheep or lambs, without wool on, whether or not split, but not further prepared"
cap label var HS4106 "Tanned or crust hides and skins of other animals, without wool or hair on, whether or not split, but not further prepared"
cap label var HS4107 "Leather further prepared after tanning or crusting, including parchment-dressed leather, of bovine, including buffalo or equine animals, without hair on, whether or not split (excl. chamois leather, patent leather and patent laminated leather, and metallised leather)"
cap label var HS4112 "Leather further prepared after tanning or crusting, including parchment-dressed leather, of sheep or lamb, without wool on, whether or not split, other than chamois leather, patent leather and patent laminated leather, and metallized leather (heading 41.14)"
cap label var HS4113 "Leather further prepared after tanning or crusting, including parchment-dressed leather, of other animals, without wool or hair on, whether or not split, other than chamois leather, patent leather and patent laminated leather, and metallized leather (heading 41.14)"
cap label var HS4114 "Chamois (including combination chamois) leather; patent leather and patent laminated leather; metallised leather"
cap label var HS4401 "Fuel wood, in logs, in billets, in twigs, in faggots or in similar forms; wood in chips or particles; sawdust and wood waste and scrap, whether or not agglomerated in logs, briquettes, pellets or similar forms"
cap label var HS4402 "Wood charcoal (including shell or nut charcoal), whether or not agglomerated"
cap label var HS4403 "Wood in the rough, whether or not stripped of bark or sapwood, or roughly squared"
cap label var HS4404 "Hoopwood; split poles; piles, pickets and stakes of wood, pointed but not sawn lengthwise; wooden sticks, roughly trimmed but not turned, bent or otherwise worked, suitable for the manufacture of walking-sticks, umbrellas, tool handles or the like; chipwood and the like"
cap label var HS4405 "Wood wool; wood flour"
cap label var HS4406 "Railway or tramway sleepers (cross-ties) of wood"
cap label var HS4407 "Wood sawn or chipped lengthwise, sliced or peeled, whether or not planed, sanded or end-jointed, of a thickness exceeding 6 mm"
cap label var HS4408 "Sheets for veneering (including those obtained by slicing laminated wood), for plywood or for similar laminated wood and other wood, sawn lengthwise, sliced or peeled, whether or not planed, sanded, spliced or end-jointed, of a thickness not exceeding 6 mm"
cap label var HS4409 "Wood (including strips and friezes for parquet flooring, not assembled) continuously shaped (tongued, grooved, rebated, chamfered, V-jointed, beaded, moulded, rounded or the like) along any of its edges, ends or faces, whether or not planed, sanded or end-jointed"
cap label var HS4410 "Particle board, oriented strand board (OSB) and similar board (for example, waferboard) of wood or other ligneous materials, whether or not agglomerated with resins or other organic binding substances"
cap label var HS4411 "Fibreboard of wood or other ligneous materials, whether or not bonded with resins or other organic substances"
cap label var HS4412 "Plywood, veneered panels and similar laminated wood"
cap label var HS4413 "Densified wood, in blocks, plates, strips or profile shapes"
cap label var HS4414 "Wooden frames for paintings, photographs, mirrors or similar objects"
cap label var HS4415 "Packing cases, boxes, crates, drums and similar packings, of wood; cable-drums of wood; pallets, box pallets and other load boards, of wood; pallet collars of wood"
cap label var HS4416 "Casks, barrels, vats, tubs and other coopers' products parts thereof, of wood, includig staves"
cap label var HS4417 "Tools, tool bodies, tool handles, broom or brush bodies and handles, of wood; boot or shoe lasts and trees, of wood"
cap label var HS4418 "Builders' joinery and carpentry of wood, including cellular wood panels, assembled flooring panels, shingles and shakes"
cap label var HS4419 "Tableware and kitchenware, of wood"
cap label var HS4420 "Wood marquetry and inlaid wood"
cap label var HS4421 "Other articles of wood"
cap label var HS4501 "Natural cork, raw or simply prepared; waste cork; crushed, granulated or ground cork"
cap label var HS4502 "Natural cork, debacked or roughly squared, or in rectangular (including square) blocks, plates, sheets or strip (including sharp-edged blanks for corks or stoppers)"
cap label var HS4503 "Articles of natural cork"
cap label var HS4504 "Agglomerated cork (with or without a binding substance) and articles of agglomerated cork"
cap label var HS4701 "Mechanical wood pulp"
cap label var HS4702 "Chemical wood pulp, dissolving grades"
cap label var HS4703 "Chemical wood pulp, soda or sulphate, other than dissolving grades"
cap label var HS4704 "Chemical wood pulp, sulphite, other than dissolving grades"
cap label var HS4705 "Wood pulp obtained by a combination of mechanical and chemical pulping processes"
cap label var HS4801 "Newsprint, in rolls or sheets"
cap label var HS4802 "Uncoated paper and paperboard, of a kind used for writing, printing or other graphic purposes, and non-perforated punchcards and punch-tape paper, in rolls or in square or rectangular sheets, of any size, and handmade paper and paperboard (excl. newsprint of heading 4801 and paper of heading 4803)"
cap label var HS4803 "Toilet or facial tissue stock, towel or napkin stock and similar paper of a kind used for household or sanitary purposes, cellulose wadding and webs of cellulose fibres, whether or not creped, crinkled, embossed, perforated, surface-coloured, surface-decorated or printed, in rolls or sheets"
cap label var HS4804 "Uncoated kraft paper and paperboard, in rolls of a width > 36 cm or in square or rectangular sheets with one side > 36 cm and the other side > 15 cm in the unfolded state (excl. goods of heading 4802 or 4803)"
cap label var HS4805 "Other paper and paperboard, uncoated, in rolls of a width > 36 cm or in square or rectangular sheets with one side > 36 cm and the other side > 15 cm in the unfolded state, not worked other than as specified in Note 3 to this chapter, n.e.s."
cap label var HS4806 "Vegetable parchment, greaseproof papers, tracing papers and glassine and other glazed transparent or translucent papers, in rolls or sheets"
cap label var HS4807 "Composite paper and paperboard (made by sticking flat layers of paper or paperboard together with an adhesive), not surface-coated or impregnated, whether or not internally reinforced, in rolls or sheets"
cap label var HS4808 "Corrugated paper and paperboard "with or without glued flat surface sheets", creped, crinkled, embossed or perforated, in rolls of a width > 36 cm or in square or rectangular sheets with one side > 36 cm and the other side > 15 cm in the unfolded state (excl. goods of heading 4803)"
cap label var HS4809 "Carbon paper, self-copy paper and other copying or transfer papers (including coated or impregnated paper for duplicator stencils or offset plates), whether or not printed, in rolls or sheets"
cap label var HS4810 "Paper and paperboard, coated on one or both sides with kaolin (China clay) or other inorganic substances, with or without a binder, and with no other coating, whether or not surface-coloured, surface-decorated or printed, in rolls or rectangular (including square) sheets, of any size"
cap label var HS4811 "Paper, paperboard, cellulose wadding and webs of cellulose fibres, coated, impregnated, covered, surface-coloured, surface-decorated or printed, in rolls or in square or rectangular sheets, of any size (excl. goods of heading 4803, 4809 and 4810)"
cap label var HS4812 "Filter blocks, slabs and plates, of paper pulp"
cap label var HS4813 "Cigarette paper, whether or not cut to size or in the form of booklets or tubes"
cap label var HS4814 "Wallpaper and similar wall coverings of paper; window transparencies of paper"
cap label var HS4816 "Carbon paper, self-copy paper and other copying or transfer papers, in rolls of a width of <= 36 cm or in rectangular or square sheets with no side measuring > 36 cm in the unfolded state, or cut into shapes other than rectangles or squares, together with full duplicator stencils and offset plates of paper, whether or not in boxes"
cap label var HS4817 "Envelopes, letter cards, plain postcards and correspondence cards, of paper or paperboard; boxes, pouches, wallets and writing compendiums, of paper or paperboard, containing an assortment of paper stationery"
cap label var HS4818 "Toilet paper and similar paper, cellulose wadding or webs of cellulose fibres, of a kind used for household or sanitary purposes, in rolls of a width not exceeding 36 cm, or cut to size or shape; handkerchiefs, cleansing tissues, towels, tablecloths, serviettes, bed sheets and similar household, sanitary or hospital articles, articles of apparel and clothing accessories, of paper pulp, paper, cellulose wadding or webs of cellulose fibres"
cap label var HS4819 "Cartons, boxes, cases, bags and other packing containers, of paper, paperboard, cellulose wadding or webs of cellulose fibres; box files, letter trays, and similar articles, of paper or paperboard of a kind used in offices, shops or the like"
cap label var HS4820 "Registers, account books, note books, order books, receipt books, letter pads, memorandum pads, diaries and similar articles, exercise books, blotting-pads, binders (loose-leaf or other), folders, file covers, manifold business forms, interleaved carbon sets and other articles of stationery, of paper or paperboard; albums for samples or for collections and book covers, of paper or paperboard"
cap label var HS4821 "Paper or paperboard labels of all kinds, whether or not printed"
cap label var HS4822 "Bobbins, spools, cops and similar supports of paper pulp, paper or paperboard (whether or not perforated or hardened)"
cap label var HS4823 "Other paper, paperboard, cellulose wadding and webs of cellulose fibres, cut to size or shape; other articles of paper pulp, paper, paperboard, cellulose wadding or webs of cellulose fibres"
cap label var HS4901 "Printed books, brochures, leaflets and similar printed matter, whether or not in single sheets"
cap label var HS4902 "Newspapers, journals and periodicals, whether or not illustrated or containing advertising material"
cap label var HS4903 "Children's picture, drawing or colouring books"
cap label var HS4904 "Music, printed or in manuscript, whether or not bound or illustrated"
cap label var HS4905 "Maps and hydrographic or similar charts of all kinds, including atlases, wall maps, topographical plans and globes, printed"
cap label var HS4906 "Plans and drawings for architectural, engineering, industrial, commercial, topographical or similar purposes, being originals drawn by hand; hand-written texts; photographic reproductions on sensitised paper and carbon copies of the foregoing"
cap label var HS4907 "Unused postage, revenue or similar stamps of current or new issue in the country in which they have, or will have, a recognised face value; stamp-impressed paper; banknotes; cheque forms; stock, share or bond certificates and similar documents of title"
cap label var HS4909 "Printed or illustrated postcards; printed cards bearing personal greetings, messages or announcements, whether or not illustrated, with or without envelopes or trimmings"
cap label var HS4910 "Calendars of any kinds, printed, including calendars blocks"
cap label var HS4911 "Other printed matter, including printed pictures and photographs"
cap label var HS5101 "Wool, neither carded nor combed"
cap label var HS5102 "Fine or coarse animal hair, not carded or combed"
cap label var HS5104 "Garnetted stock of wool or of fine or coarse animal hair"
cap label var HS5105 "Wool and fine or coarse animal hair, carded or combed (including combed wool in fragments)"
cap label var HS5106 "Yarn of carded wool, not put up for retail sale"
cap label var HS5107 "Yarn of combed wool, not put up for retail sale"
cap label var HS5108 "Yarn of fine animal hair (carded or combed), not put up for retail sale"
cap label var HS5109 "Yarn of wool or fine animal hair, put up for retail sale"
cap label var HS5110 "Yarn of coarse animal hair or of horsehair (including gimped horsehair yarn), whether or not put up for retail sale"
cap label var HS5111 "Woven fabrics of carded wool or of carded fine animal hair"
cap label var HS5112 "Woven fabrics of combed wool or of combed fine animal hair"
cap label var HS5113 "Woven fabrics of coarse animal hair or of horsehair"
cap label var HS5201 "Cotton, not carded or combed"
cap label var HS5203 "Cotton, carded or combed"
cap label var HS5204 "Cotton sewing thread, whether or not put up for retail sale"
cap label var HS5205 "Cotton yarn (other than sewing thread), containing 85 % or more by weight of cotton, not put up for retail sale"
cap label var HS5206 "Cotton yarn (other than sewing thread), containing less than 85 % by weight of cotton, not put up for retail sale"
cap label var HS5207 "Cotton yarn (other than sewing thread) put up for retail sale"
cap label var HS5208 "Woven fabrics of cotton, containing 85 % or more by weight of cotton, weighing not more than 200 g/m2"
cap label var HS5209 "Woven fabrics of cotton, containing 85 % or more by weight of cotton, weighing more than 200 g/m2"
cap label var HS5210 "Woven fabrics of cotton, containing less than 85 % by weight of cotton, mixed mainly or solely with man-made fibres, weighing not more than 200 g/m2"
cap label var HS5211 "Woven fabrics of cotton, containing less than 85 % by weight of cotton, mixed mainly or solely with man-made fibres, weighing more than 200 g/m2"
cap label var HS5212 "Other woven fabrics of cotton"
cap label var HS5301 "Flax, raw or processed but not spun; flax tow and waste (including yarn waste and garnetted stock)"
cap label var HS5302 "True hemp (Cannabis sativa L.), raw or processed but not spun; tow and waste of true hemp (including yarn waste and garnetted stock)"
cap label var HS5303 "Jute and other textile bast fibres (excluding flax, true hemp and ramie), raw or processed but not spun; tow and waste of these fibres (including yarn waste and garnetted stock)"
cap label var HS5305 "Coconut, abaca (Manila hemp or Musa textilis Nee), ramie and other vegetable textile fibres, not elsewhere specified or included, raw or processed but not spun; tow, noils and waste of these fibres (including yarn waste and garnetted stock)"
cap label var HS5306 "Flax yarn"
cap label var HS5307 "Yarn of jute or of other textile bast fibres (excluding flax, true hemp and ramie), raw or processed but not spun; tow and waste of these fibres (including yarn waste and garnetted stock) (heading 5303)"
cap label var HS5308 "Yarn of other vegetable textile fibres; paper yarn"
cap label var HS5309 "Woven fabrics of flax"
cap label var HS5310 "Woven fabrics of jute or of other textile bast fibres (excluding flax, true hemp and ramie), raw or processed but not spun; tow and waste of these fibres (including yarn waste and garnetted stock) (heading 5303)"
cap label var HS5311 "Woven fabrics of other vegetable textile fibres; woven fabrics of paper yarn"
cap label var HS6101 "Men's or boys' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind-jackets and similar articles, knitted or crocheted, other than suits, ensembles, jackets, blazers, trousers, bib and brace overalls, breeches and shorts (other than swimwear) (heading 61.03)"
cap label var HS610120 "Men's or boys' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind-jackets and similar articles of cotton, knitted or crocheted, other than suits, ensembles, jackets, blazers, trousers, bib and brace overalls, breeches and shorts (other than swimwear) (heading 61.03.)"
cap label var HS6102 "Women's or girls' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind- jackets and similar articles, knitted or crocheted, other than suits, ensembles, jackets, blazers, dresses, skirts, divided skirts, trousers, bib and brace overalls, breeches and shorts (other than swimwear) (heading 61.04)"
cap label var HS610210 "Women's or girls' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind- jackets and similar articles, of wool or fine animal hair, knitted or crocheted, other than suits, ensembles, jackets, blazers, dresses, skirts, divided skirts, trousers, bib and brace overalls, breeches and shorts (other than swimwear) (heading 61.04)"
cap label var HS610220 "Women's or girls' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind- jackets and similar articles, of cotton, knitted or crocheted, other than other than suits, ensembles, jackets, blazers, dresses, skirts, divided skirts, trousers, bib and brace overalls, breeches and shorts (other than swimwear) (heading 61.04)"
cap label var HS6103 "Men's or boys' suits, ensembles, jackets, blazers, trousers, bib and brace overalls, breeches and shorts (other than swimwear), knitted or crocheted"
cap label var HS610322 "Men's or boys' ensembles, of cotton, knitted or crocheted"
cap label var HS610331 "Men's or boys' jackets and blazers of wool or fine animal hair, knitted or crocheted"
cap label var HS610332 "Men's or boys' jackets and blazers of cotton, knitted or crocheted"
cap label var HS610341 "Men's or boys' trousers, bib and brace overalls, breeches and shorts of wool or fine animal hair, knitted or crocheted"
cap label var HS610342 "Men's or boys' trousers, bib and brace overalls, breeches and shorts of cotton, knitted or crocheted"
cap label var HS6104 "Women's or girls' suits, ensembles, jackets, blazers, dresses, skirts, divided skirts, trousers, bib and brace overalls, breeches and shorts (other than swimwear), knitted or crocheted"
cap label var HS610422 "Women's or girls' ensembles of cotton, knitted or crocheted"
cap label var HS610431 "Women's or girls' jackets and blazers of wool or fine animal hair, knitted or crocheted"
cap label var HS610432 "Women's or girls' jackets and blazers of cotton, knitted or crocheted"
cap label var HS610441 "Women's or girls' dresses of wool or fine animal hair, knitted or crocheted"
cap label var HS610442 "Women's or girls' dresses of cotton, knitted or crocheted"
cap label var HS610451 "Women's or girls' skirts and divided skirts of wool or fine animal hair, knitted or crocheted"
cap label var HS610452 "Women's or girls' skirts and divided skirts of cotton, knitted or crocheted"
cap label var HS610461 "Women's or girls' trousers, bib and brace overalls, breeches and shorts of wool or fine animal hair, knitted or crocheted"
cap label var HS610462 "Women's or girls' trousers, bib and brace overalls, breeches and shorts of cotton, knitted or crocheted"
cap label var HS6105 "Men's or boys' shirts, knitted or crocheted"
cap label var HS610510 "Men's or boys' shirts, of cotton, knitted or crocheted"
cap label var HS6106 "Women's or girls' blouses, shirts and shirt-blouses, knitted or crocheted"
cap label var HS610610 "Women's or girls' blouses, shirts and shirt-blouses of cotton, knitted or crocheted"
cap label var HS6107 "Men's or boys' underpants, briefs, nightshirts, pyjamas, bathrobes, dressing gowns and similar articles, knitted or crocheted"
cap label var HS610711 "Men's or boys' underpants and briefs of cotton, knitted or crocheted"
cap label var HS610721 "Men's or boys' nightshirts and pyjamas of cotton, knitted or crocheted"
cap label var HS610791 "Men's or boys' bathrobes, dressing gowns and similar articles of cotton, knitted or crocheted"
cap label var HS6108 "Women's or girls' slips, petticoats, briefs, panties, nightdresses, pyjamas, negligees, bathrobes, dressing gowns and similar articles, knitted or crocheted"
cap label var HS610821 "Women's or girls' briefs and panties of cotton, knitted or crocheted"
cap label var HS610831 "Women's or girls' nightdresses and pyjamas of cotton, knitted or crocheted"
cap label var HS610891 "Women's or girls' negligés, bathrobes, dressing gowns, housejackets and similar articles of cotton, knitted or crocheted"
cap label var HS6109 "T-shirts, singlets and other vests, knitted or crocheted"
cap label var HS610910 "T-shirts, singlets and other vests of cotton, knitted or crocheted"
cap label var HS6110 "Jerseys, pullovers, cardigans, waistcoats and similar articles, knitted or crocheted"
cap label var HS611011 "Jerseys, pullovers, cardigans, waistcoats and similar articles, of wool, knitted or crocheted"
cap label var HS611020 "Jerseys, pullovers, cardigans, waistcoats and similar articles, of cotton, knitted or crocheted"
cap label var HS6111 "Babies' garments and clothing accessories, knitted or crocheted"
cap label var HS611120 "Babies' garments and clothing accessories of cotton, knitted or crocheted"
cap label var HS6112 "Track suits, ski suits and swimwear, knitted or crocheted"
cap label var HS611211 "Track-suits of cotton, knitted or crocheted"
cap label var HS6114 "Other garments, knitted or crocheted"
cap label var HS611420 "Other garments, of cotton, knitted or crocheted"
cap label var HS6115 "Panty hose, tights, stockings, socks and other hosiery, including graduated compression hosiery (for example, stockings for varicose veins) and footwear without applied soles, knitted or crocheted"
cap label var HS611594 "Other panty hose, tights, stockings, socks and other hosiery, including graduated compression hosiery (for example, stockings for varicose veins) and footwear without applied soles, of wool or fine animal hair, knitted or crocheted"
cap label var HS611595 "Other panty hose, tights, stockings, socks and other hosiery, including graduated compression hosiery (for example, stockings for varicose veins) and footwear without applied soles, of cotton, knitted or crocheted"
cap label var HS6116 "Gloves, mittens and mitts, knitted or crocheted"
cap label var HS611691 "Gloves, mittens and mitts, of wool or fine animal hair, knitted or crocheted"
cap label var HS611692 "Gloves, mittens and mitts, of cotton, knitted or crocheted"
cap label var HS6201 "Men’s or boys’ overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind-jackets and similar articles, other than suits, ensembles, jackets, blazers, trousers, bib and brace overalls, breeches and shorts (other than swimwear) (heading 62.03)"
cap label var HS620120 "Men's or boys' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind-jackets and similar articles of wool or fine animal hair, other than suits, ensembles, jackets, blazers, trousers, bib and brace overalls, breeches and shorts (other than swimwear) (heading 62.03)"
cap label var HS620130 "Men's or boys' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind-jackets and similar articles of cotton, other than suits, ensembles, jackets, blazers, trousers, bib and brace overalls, breeches and shorts (other than swimwear) (heading 62.03)"
cap label var HS6202 "Women's or girls' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind-jackets and similar articles, other than suits, ensembles, jackets, blazers, dresses, skirts, divided skirts, trousers, bib and brace overalls, breeches and shorts (other than swimwear) (heading 62.04)"
cap label var HS620220 "Women's or girls' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind-jackets and similar articles of wool or fine animal hair, other than suits, ensembles, jackets, blazers, dresses, skirts, divided skirts, trousers, bib and brace overalls, breeches and shorts (other than swimwear) (heading 62.04)"
cap label var HS620230 "Women's or girls' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind-jackets and similar articles of cotton (excl. knitted or crocheted), other than suits, ensembles, jackets, blazers, dresses, skirts, divided skirts, trousers, bib and brace overalls, breeches and shorts (other than swimwear) (heading 62.04)"
cap label var HS6203 "Men's or boys' suits, ensembles, jackets, blazers, trousers, bib and brace overalls, breeches and shorts (other than swimwear)"
cap label var HS620311 "Men's or boys' suits of wool or fine animal hair"
cap label var HS620322 "Men's or boys' ensembles of cotton"
cap label var HS620331 "Men's or boys' jackets and blazers of wool or fine animal hair"
cap label var HS620332 "Men's or boys' jackets and blazers of cotton"
cap label var HS620341 "Men's or boys' trousers, bib and brace overalls, breeches and shorts, of wool or fine animal hair"
cap label var HS620342 "Men's or boys' trousers, bib and brace overalls, breeches and shorts, of cotton"
cap label var HS6204 "Women's or girls' suits, ensembles, jackets, blazers, dresses, skirts, divided skirts, trousers, bib and brace overalls, breeches and shorts (other than swimwear)"
cap label var HS620411 "Women's or girls' suits of wool or fine animal hair"
cap label var HS620412 "Women's or girls' suits of cotton"
cap label var HS620421 "Women's or girls' ensembles of wool or fine animal hair"
cap label var HS620422 "Women's or girls' ensembles of cotton"
cap label var HS620431 "Women's or girls' jackets and blazers of wool or fine animal hair"
cap label var HS620432 "Women's or girls' jackets and blazers of cotton"
cap label var HS620441 "Women's or girls' dresses of wool or fine animal hair"
cap label var HS620442 "Women's or girls' dresses of cotton"
cap label var HS620451 "Women's or girls' skirts and divided skirts of wool or fine animal hair"
cap label var HS620452 "Women's or girls' skirts and divided skirts of cotton"
cap label var HS620461 "Women's or girls' trousers, bib and brace overalls, breeches and shorts of wool or fine animal hair"
cap label var HS620462 "Women's or girls' trousers, bib and brace overalls, breeches and shorts of cotton"
cap label var HS6205 "Men's or boys' shirts"
cap label var HS620520 "Men's or boys' shirts of cotton"
cap label var HS6206 "Women's or girls' blouses, shirts and shirt-blouses"
cap label var HS620620 "Women's or girls' blouses, shirts and shirt-blouses of wool or fine animal hair"
cap label var HS620630 "Women's or girls' blouses, shirts and shirt-blouses of cotton"
cap label var HS6207 "Men's or boys' singlets and other vests, underpants, briefs, nightshirts, pyjamas, bathrobes, dressing gowns and similar articles"
cap label var HS620711 "Men's or boys' underpants and briefs of cotton"
cap label var HS620721 "Men's or boys' nightshirts and pyjamas of cotton"
cap label var HS620791 "Men's or boys' singlets and other vests, bathrobes, dressing gowns and similar articles of cotton"
cap label var HS6208 "Women's or girls' singlets and other vests, slips, petticoats, briefs, panties, nightdresses, pyjamas, negligees, bathrobes, dressing gowns and similar articles"
cap label var HS620821 "Women's or girls' nightdresses and pyjamas of cotton"
cap label var HS620891 "Women's or girls' singlets and other vests, briefs, panties, negligees, bathrobes, dressing gowns and similar articles of cotton"
cap label var HS6209 "Babies' garments and clothing accessories"
cap label var HS620920 "Babies' garments and clothing accessories of cotton"
cap label var HS6211 "Track suits, ski suits and swimwear; other garments"
cap label var HS621132 "Men's or boys' other garments, of cotton"
cap label var HS621142 "Women's or girls' other garments, of cotton"
cap label var HS6213 "Handkerchiefs"
cap label var HS621320 "Handkerchiefs of cotton"
cap label var HS6214 "Shawls, scarves, mufflers, mantillas, veils and the like"
cap label var HS621420 "Shawls, scarves, mufflers, mantillas, veils and similar articles of wool or fine animal hair"
cap label var HS9403 "Other furniture and parts thereof"
cap label var HS9406 "Prefabricated buildings"
cap label var NAP "Not applicable"
